### ISSUE TITLE
Improve readability for the "Show XML" function

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#100]
**Is your feature request related to a problem? Please describe.**
When trying to find or locate the relevant xml code in a document (ex: in order to give you examples) I use the text content as reference point. This is tedious and I need to go to Notepad++ sometimes

**Describe the solution you'd like**
 It woud be nice if in that "Show XML" screen two things could happen
-highlight the pure text content only 
-allow a search and highlight the occurencies 
At a first look I think this is an easy with from programming efforts perspective. 

**Describe alternatives you've considered**
At this moment I am using Notepad++ which can color code the XML

**Comment by stevencohn** [comment]
Nope. Sorry. Not easy and not worth it.

**Comment by CLITrees** [comment]
ok ..I tried my luck :-)

**Comment by stevencohn** [comment]
I honestly wish it was easy and completely understand. Using it as a diagnostic tool has been invaluable and I have looked into various improvements - trust me, many times! But I want to prioritize other features as I'm sure you understand.

**Comment by 1001QAdotNET** [comment]
Not a problem... in the end I should be able to do certain things using the plugin hook you provided but I dont seem to find the time.😥
