### ISSUE TITLE
Task summary page/report/Snippet

### ISSUE THREAD

**Issue by olivermarshall2** [stevencohn/OneMore#1000]
# Problem to Solve

I'm desperate for a way to summarise the task (tick box tags) within my onenote. I can use the Find Tags feature, which is nice, but isn't a great panel to work from as you work through your task lists.

# New Feature/Solution

An auto-update page/report/snippet/table that shows the task (tick box tag item) and page name, Notebook name etc.

It would be great to be able to create a page that had a summary of all the tick boxes in my notebook, ordered by something (for me, by Page title) that could be easily updated (button, menu etc) and that optionally showed completed items.

**Comment by stevencohn** [comment]
Do you know that this is part of the built-in Find Tags command? Click Find Tags on the Home ribbon bar. That opens the Tags Summary panel. Group by Title. And click Show only unchecked items. 

It does show all tags, not only checkboxes. But this will group them together but it an easy way to find uncheck/incomplete items.

<img width="194" alt="image" src="https://user-images.githubusercontent.com/9964757/227190017-5117e3e8-e05f-4bb2-9a74-45048ef8fc80.png">

**Comment by olivermarshall2** [comment]
Wow, thanks, I'd never noticed that bit at the bottom (I have my screens in portrait so it's far far away). 

But I guess, can you make the experience better? Auto-update of a table of them? Greater search filters (this week or last week or "older" isn't very granular). etc. 

Great tool though btw. Very appreciated.

**Comment by julie777** [comment]
With the OneNote find tags feature you can
- find all tags or checkbox tags that are not checked
- group by tag name, section,  date, title
- save tags to a summary page which lists each tag and has a link to it on the page

in File/Options/Advanced/Tags you can choose whether tags in the summary are dimmed or not. By dimming tags in the summary they won't be included in the results from find tags so you won't see duplicates.

**Comment by stevencohn** [comment]
Agreed with @julie777. I could only add incremental improvements over what OneNote already offers. I'll close this unless there is a compelling reason to reconsider.

**Comment by stevencohn** [comment]
Closing due to comments
