### ISSUE TITLE
Title Style Issues

### ISSUE THREAD

**Issue by Silfra-glacier** [stevencohn/OneMore#1002]
Hello! When adapting selected text to the text style of onemore, not only will the selected text be changed to the target style, but other text styles will also be changed to other text styles (affected). How can I solve this problem?

**Comment by stevencohn** [comment]
Investigating... there are some things that need to be cleaned up.

While I'm looking, it would be great it you could explain a bit of detail describing your exact use case so I can be sure to test that too. Thanks!

**Comment by julie777** [comment]
Does this fix keep the Heading Style from continuing on the next line/paragraph?

**Comment by julie777** [comment]
hmmm...

Does it only happen when there is no next paragraph?
If so could applying the Heading style automatically create an empty next paragraph with normal style?

OneNote Heading Styles apply to a single paragraph (with no selection) and when hitting enter the next paragraph is normal.

**Comment by stevencohn** [comment]
I could easily create a next paragraph but that means you need to use the arrow keys or mouse to get there rather than type Enter in a natural flow.

**Comment by Silfra-glacier** [comment]
Hello, long time no see.
Specific test cases may need to be recorded on the screen to better express themselves, as I will explain in detail below.
If I customize a title style (hereinafter referred to as "Style 1") and try to set a line (or paragraph) to "Style 1" after entering some text on the page, using shortcut keys or mouse clicks, etc., the target paragraph or line successfully becomes "Style 1", but other text or some paragraphs will also be affected, This impact includes but is not limited to the following situations:
1. Font size decreases
2. Change the font style from "bold" to "Microsoft YaHei"
... etc
The main impact is 1.
Therefore, every time I modify the style, I have to spend time modifying other affected text again, which wastes a lot of time, even more than manually modifying the original text style. 😂
By the way, pages with this issue currently only occur in the following situations:
This page originally did not use any style of "onemore" when entering text, and generally speaking, this page has "Formula" (that is, "ink formula" function), or there is text, which already has the style provided by "onenote".
After preparing for this prerequisite, closing the page, opening the page again to input some text, and then using the style provided by "onemore" (usually a custom style), the above problem will inevitably occur.
Here are some features:
1. Directly using the style provided by Onemore while typing on a blank page will not cause the above problem.
When the above problem occurs, if the affected text is deleted and the text is inputted again, the problematic text will not be affected thereafter. (Therefore, I sometimes delete problematic formulas or paragraphs and input them again)
3. Regarding feature 2, the problem may occur with the original text. Even if I delete the problematic text, if I later copy and paste the original text again, the problem will still occur (i.e., I can only manually input it again instead of pasting the original text)
Thank you for seeing this. I hope my description is accurate and I look forward to repairing and updating it.

Here are the details:

https://github.com/stevencohn/OneMore/assets/68190236/105027f9-e0bb-46c4-ae29-e3b942c3a0d5

**Comment by Silfra-glacier** [comment]
I found the latest release 5.8.5 in the distribution, but there are still the same issues. The problem description and video are the same. 😢

**Comment by Silfra-glacier** [comment]
Provide another record：

https://github.com/stevencohn/OneMore/assets/68190236/cdd19a51-6438-44e1-ac83-a8bbdd292e93

Thanks.

**Comment by Silfra-glacier** [comment]
> Hello, long time no see. Specific test cases may need to be recorded on the screen to better express themselves, as I will explain in detail below. If I customize a title style (hereinafter referred to as "Style 1") and try to set a line (or paragraph) to "Style 1" after entering some text on the page, using shortcut keys or mouse clicks, etc., the target paragraph or line successfully becomes "Style 1", but other text or some paragraphs will also be affected, This impact includes but is not limited to the following situations:
> 
> 1. Font size decreases
> 2. Change the font style from "bold" to "Microsoft YaHei"
>    ... etc
>    The main impact is 1.
>    Therefore, every time I modify the style, I have to spend time modifying other affected text again, which wastes a lot of time, even more than manually modifying the original text style. 😂
>    By the way, pages with this issue currently only occur in the following situations:
>    This page originally did not use any style of "onemore" when entering text, and generally speaking, this page has "Formula" (that is, "ink formula" function), or there is text, which already has the style provided by "onenote".
>    After preparing for this prerequisite, closing the page, opening the page again to input some text, and then using the style provided by "onemore" (usually a custom style), the above problem will inevitably occur.
>    Here are some features:
> 3. Directly using the style provided by Onemore while typing on a blank page will not cause the above problem.
>    When the above problem occurs, if the affected text is deleted and the text is inputted again, the problematic text will not be affected thereafter. (Therefore, I sometimes delete problematic formulas or paragraphs and input them again)
> 4. Regarding feature 2, the problem may occur with the original text. Even if I delete the problematic text, if I later copy and paste the original text again, the problem will still occur (i.e., I can only manually input it again instead of pasting the original text)
>    Thank you for seeing this. I hope my description is accurate and I look forward to repairing and updating it.
> 
> Here are the details:
> 
>  bandicam.2023-07-16.12-08-32-273.mp4

Added version: 5.8.4

**Comment by Silfra-glacier** [comment]
> Provide another record：
> 
>  bandicam.2023-07-16.13-21-45-513.mp4 
> Thanks.

Added version: 5.8.5

**Comment by stevencohn** [comment]
@Silfra-glacier There is a know issue where applying a custom style, then pressing Enter, results in the following paragraph also being that style even though it appears visually to be a Normal paragraph. This means that when you change any style in the following paragraph, it will suddenly be redrawn using the custom style.

The temporary work-around when applying a custom style to a paragraph is to press Enter and then immediately press Ctrl+Shift+N to make the second paragraph Normal.

I am trying to come up with a solution for this.

**Comment by tinnted** [comment]
I am having a similar issue with applying style where the font changes to calibre even though my onenote default is another font 

Check the gif below for the issue 
![OneMore](https://github.com/stevencohn/OneMore/assets/18625849/6449ca5d-1787-45bf-9459-30217d435408)
