### ISSUE TITLE
Selecting Manage Favorites Causes crash

### ISSUE THREAD

**Issue by julie777** [stevencohn/OneMore#1008]
# Problem to Solve

When I select "manage favorites" from the Favorites menu, or with the 2 dots from the favorite chooser dialog, or while in settings, it causes a crash.

Several times I just selected continue because I was in the process of writing up another issue. 
Eventually it really messed up OneMore and I shut down OneNote. (It was so strange, I accidentally clicked on styles instead of favorites and it just showed 4 tiny icons, instead of the normal styles menu.)

I tried removing the last favorite I added from favorites.xml to see if that was the problem but the crash still happens. I have no idea when this behavior started because I don't remember the last time I view the settings for favorites. 

I have included
- the OneMore log
- the details from the crash dialog
- my favorites file (renamed .txt)

# To Reproduce

1. Open Favorites Menu
2. Click Manage Favorites
3. Crash
4. Select Continue and the favorites table shown is empty
5. OneMore is left very confused and OneNote needs to be restarted.

# Expected Behavior

Show the settings for favorites.

# Screenshots

![image](https://user-images.githubusercontent.com/5090005/229194803-f8b10eab-34fa-4f5c-9dcd-fc88b780b374.png)

![image](https://user-images.githubusercontent.com/5090005/229195036-ef50aec9-a115-4c39-a9fa-01596ef8f213.png)

# Environment (if applicable)

 - OneNote Version:  O365,
 - OneMore Version 5.8.4 with OneNote 16.0.16130.20332

# Additional Context

[OneMore.log](https://github.com/stevencohn/OneMore/files/11124683/OneMore.log)
[error from dialog.txt](https://github.com/stevencohn/OneMore/files/11124684/error.from.dialog.txt)
[Favorites.txt](https://github.com/stevencohn/OneMore/files/11124702/Favorites.txt)

**Comment by stevencohn** [comment]
There's likely another favorite in your list that's orphaned, not just the last one. That table attempts to cross-check each favorite with its source and tags it as suspicious or unknown depending on what it can or cannot find.

**Comment by julie777** [comment]
I'm not sure what you mean by the three dot menu.

Are you planning to fix the crash or is that by design?

**Comment by julie777** [comment]
I just found two orphaned links by just trying to go to the favorite.

They bring up a long series of message boxes in the process. I can't believe that it takes this many messages just to say "it doesn't exist".

This is what happens when I say yes I want to ignore safety and follow the link.
I assume that this mess is all Microsoft.

![image](https://user-images.githubusercontent.com/5090005/229312198-a4e55b9f-f062-4c15-a606-46e55e42e485.png)
![image](https://user-images.githubusercontent.com/5090005/229312205-9d1ca7a2-a202-4faf-9ecb-34f625b85b12.png)
![image](https://user-images.githubusercontent.com/5090005/229312211-f31a7b06-1b9e-4975-a22c-8fee827876a8.png)
![image](https://user-images.githubusercontent.com/5090005/229312215-79fc588c-4c99-4492-a858-b96cef6c0928.png)
![image](https://user-images.githubusercontent.com/5090005/229312221-6fc4fa9e-12a4-4981-8fec-0efe503c1659.png)
![image](https://user-images.githubusercontent.com/5090005/229312225-c5ee1589-66d1-4d2c-854f-e8c7389764b9.png)
![image](https://user-images.githubusercontent.com/5090005/229312233-696bd04f-d727-4c87-8843-264e53e8c6b4.png)
![image](https://user-images.githubusercontent.com/5090005/229312238-d0ac42c6-7c1e-499c-a7fc-2759567e47f7.png)
![image](https://user-images.githubusercontent.com/5090005/229312242-5b7f8d41-30b2-41f4-938e-402d854db981.png)

**Comment by stevencohn** [comment]
Will be fixed with the next releease. This is the three-dot menu

<img width="426" alt="image" src="https://user-images.githubusercontent.com/9964757/229313096-44704f3f-2d09-4ca7-9af8-bf602687f365.png">

**Comment by julie777** [comment]
Not for me

![image](https://user-images.githubusercontent.com/5090005/229383073-aeb0b2fe-c62d-4cfe-a379-ca6bbee19f04.png)

I even made the dialog wider to see if the third dot would appear.
I just realized that you are using a different version because your three dots has a dropdown and mine goes straight to settings.
