### ISSUE TITLE
Can “Copy to unformatted text”？

### ISSUE THREAD

**Issue by chinesecalvin8282** [stevencohn/OneMore#1012]
# How can I help you?

Ask away...

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by chinesecalvin8282** [comment]
Can “Copy to unformatted text”

**Comment by stevencohn** [comment]
Yes, OneMore has a paste-as-text keyboard shortcut. Press `Ctrl + Shift + V`.
All default OneMore keyboard shortcuts are [listed here](https://onemoreaddin.com/the-basics/OneNote%20Keyboard%20Shortcuts.htm).

**Comment by julie777** [comment]
It just occurred to me that you might mean paste as text into onenote.

The problem that I have is copying text from OneNote and pasting it somewhere else. If I paste it into Outlook it keeps the formatting as much as it can. However, when I paste it into a web form it, such as a github issue, then it pastes as an image. Right click paste doesn't give me any options.

(I often write a post in ON first to make sure I don't type for 15 minutes and have a web hick-up lose it all.)

**Comment by stevenmcohn** [comment]
Yes, when you copy content, most modern apps will generate multiple different formats of that content and load them onto the system clipboard. OneNote will typically copy content as-text and as-HTML. It's then up to the target app to read what it deems as the most appropriate format from the clipboard and paste that. Some apps may further transform that content further, for example, pasting into word provides options to Keep Formatting or Merge Formatting.
