### ISSUE TITLE
Updater does not work: "Error running command UpdateCommand"

### ISSUE THREAD

**Issue by kranix0** [stevencohn/OneMore#1016]
# Problem to Solve

The built-in updater doesn't work. This has been the same since I started using OneMore a few months' ago.

# To Reproduce

Steps to reproduce the behaviour:
1. Start OneNote
2. If an update to OneMore is available, a prompt will automatically show
3. Start the update

# Expected Behavior

The update should execute without error.

# Screenshots

<img width="318" alt="image" src="https://user-images.githubusercontent.com/461278/231033769-8c93139a-d036-4d9e-a13a-065257d52f59.png">
<img width="342" alt="image" src="https://user-images.githubusercontent.com/461278/231033825-2096d9ca-3c7d-4950-b6d0-c32363d9ac25.png">

# Environment (if applicable)

Windows 11
From logs: en-GB/en-GB, v5.4.2, OneNote 15.0, Office 16.0

# Additional Context

I see a "The process cannot access the file because it is being used by another process" error in the log file.

[OneMore.log](https://github.com/stevencohn/OneMore/files/11195343/OneMore.log)

**Comment by stevencohn** [comment]
This should all be fixed in a later version, 5.7.2 having the most recent fix to the Update dialog and the auto-update feature. That means updating _from_ 5.7.2 to a later version will be fixed.
