### ISSUE TITLE
Feature request: ability to merge cells in a table

### ISSUE THREAD

**Issue by jun488** [stevencohn/OneMore#102]
**Is your feature request related to a problem? Please describe.**
Feature request related to a limitation with tables in OneNote 2016 - you can not merge cells in a table, which makes it challenging and time consuming to organize data.

**Describe the solution you'd like**
1. Highlight multiple cells in a table - several cells in a single row, column, or both. Click an option in the menu to merge multiple cells into a single cell. Content can be added to that cell, such as text, images or other tables.
2. Select the merged cell in a table. Click an option in the menu to un-merge the cells. Existing content is either removed or placed in the top-left most un-merged cell.

**Describe alternatives you've considered**
Two workarounds:
1. Create separate tables with different width/height. This works well enough when some cells in a single row need to be merged. Much more challenging when cells in a column need to be merged. Either way, this often causes alignment issues, can be time consuming and often leads to poor readability.
2. Create a separate box with a new table, set a background color, place the table on top of your existing table. This can be time consuming and causes major alignment issues if the original table or cell position/size are changed.

**Additional context**
Attached image is one of the worst examples of workaround 1 being applied. There are 5 tables, one has invisible borders to allow more than one table to be placed in the same row, which leads to the wide empty column in the middle.
![image](https://user-images.githubusercontent.com/21346164/100535109-b84ad980-31ca-11eb-93e3-1eb69c71232b.png)

**Comment by stevencohn** [comment]
This is something I've been trying to solve for quite a while. Thanks for the suggestions. Let me think about it.

**Comment by stevencohn** [comment]
You may have something with workaround #2. I can envision a command that creates and overlay cell above selected cells, across either columns or rows or even rectangular, and adds metadata that "binds" that overlay to those cells. There would need to be a second command to realign the overlay whenever the page layout changes, snapping it back into its assigned position, which could be adding text before the primary table, adding text, cells, or rows to the table, or style and font size changes. The question is how clunky that might be. I'll play with it a bit. Might not be too difficult (famous last words)

**Comment by stevencohn** [comment]
If you're subscribed to receive emails on this discussion, you may have received a promising message from me about a solution... well, that blew up quickly. I realized something right away that would make the overlay solution practically impossible :-(

**Comment by jun488** [comment]
No problem, thank you for trying!

Uservoice feature request for whatever it's worth https://onenote.uservoice.com/forums/327186-onenote-for-windows/suggestions/6340014-ability-to-merge-cells-in-a-table?

This is probably APi for the OneNote web version, but I did not find any mentions of colspan or rowspan, so we'll have to wait for the feature above sometime during this century https://docs.microsoft.com/en-us/graph/onenote-input-output-html#tables

**Comment by stevencohn** [comment]
There really is no reasonable way to do this. Closing this ticket
