### ISSUE TITLE
Realtime Markdown input

### ISSUE THREAD

**Issue by dXrayb** [stevencohn/OneMore#1021]
# New Feature/Solution

Is that possible OneMore support Realtime Markdown input like OneMark plugin.
![image](https://user-images.githubusercontent.com/4825195/233291710-35847cb4-5549-490d-9458-a65e0d4e4cdf.png)

**Comment by stevencohn** [comment]
There should be no problem running both OneMore and OneMark together.

**Comment by stevencohn** [comment]
Is there something lacking in OneMark?

**Comment by jasonjac2** [comment]
I hadn't seen this plugin - it looks good.  I had a quick look at their privacy statement.... I always caution people about installing everything / anything in terms of reducing the "security attack surface", so I like to work out: what jurisdiction they author operates under; their responsiveness to questions; their attention to detail on things like privacy...... So if I were answering your questions Steven it would be: Not lacking, just another risk vs reward calculation.

I balance this with wanting to reward innovators for  doing good work an paying accordingly (hence the sponsorship of tools I think are great).  So I'm glad this was mentioned, I'm definitely interested in it.

On their privacy policy:
They are explicit about anonymous data they collect, which is great, but an oversight (either on me or them), is they don't mention what private / personal data they collect.  It seems to miss the "we do not transmit or collect personal information, other than that given in registration or direct contact with us (e.g. e-mails)."

They refer to External Sites, but I wasn't sure if any of the rendering of images etc requires the data being transmitted to a 3rd party. 

Other thougths:
- if would be great to have a list of 3rd party add-ins for OneNote and reviews from users. Steven, do you have any that you rate / don't like that you could review?

**Comment by jasonjac2** [comment]
Also, in the screenshot about, there are 2 x editor windows, a MD and an live one.  Are they hacking ON's rendering or does ON have the option of injections additonal "frames"?

**Comment by dXrayb** [comment]
![live a7029049_1_](https://user-images.githubusercontent.com/4825195/233898652-78100ff7-0513-4178-914c-408f36dedb2a.gif)
I think this demo is more suitable for the effect of this function.

**Comment by jasonjac2** [comment]
So reading it the FAQ, both the formatted and MD version of the page is stored.  I am intrigued how they manage to intercept key presses etc.

**Comment by stevencohn** [comment]
It's easy to create a global key hook. This is how OneMore defines its own keyboard shortcuts. But it doesn't "monitor" all key activity like OneMark needs to.

I wonder how this scales. Does it still perform just as well with a very large or complicated page?

Regardless of the "curiosity factor" - can I do it? wouldn't it be cool? - I'm not hearing anything about what users want differently from what OneMark has to offer. I'm not going to duplicate it just to duplicate it. If users really want a markdown-centric note taking app then use Obsidian.

**Comment by stevencohn** [comment]
> Also, in the screenshot about, there are 2 x editor windows, a MD and an live one. Are they hacking ON's rendering or does ON have the option of injections additonal "frames"?

It looks like that's a OneMark-specific window, not an embedded view inside OneNote

**Comment by dXrayb** [comment]
I think it's a very useful feature. OneMore can export Markdown, why can't it be directly inputted? Wouldn't that be more convenient?

**Comment by bayeslearner** [comment]
Is this feature implemented? Note onemark IS NOT free.  It is a license software.  Costs 30$.

**Comment by dXrayb** [comment]
> Is this feature implemented? Note onemark IS NOT free. It is a license software. Costs 30$.

You can get this feature through OneMark or One Markdown, but there is no chance to get it free.
