### ISSUE TITLE
Add "Open folder as Onenote" to Explorer

### ISSUE THREAD

**Issue by maphew** [stevencohn/OneMore#1022]
# New Feature/Solution

Onenote 2007 added "Open as Notebobook in Onenote" to Windows Explorer context menu. This integration was removed in later editions of Onenote but according to Onenote Gems this feature still exists it's just not exposed ([ref](https://www.onenotegem.com/a/documents/gem-for-OneNote/2019/1124/1121.html)).

[[](![image](https://user-images.githubusercontent.com/486200/233454453-6f83cca4-3b96-43a0-989d-a348abee7620.png)](https://www.onenotegem.com/a/documents/gem-for-OneNote/2019/1124/1121.html)

**Comment by maphew** [comment]
Alternative and perhaps better solution: Add Onenote as destination in Send To context menu (since it will work with documents and files as well as folders)

Recipe:

1. Locate Onenote launch shortcut, e.g. `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\OneNote.lnk`, by entering `shell:Common Programs` into Explorer address bar
2. Open the SendTo folder (`shell:sendto` --> `%AppData%\Roaming\Microsoft\Windows\SendTo`)
3. Select \#1 and ctrl drag into \#2.

It would be nice but not essential if this convenience could be added to the Onemore install program.

Sources:
* https://answers.microsoft.com/en-us/windows/forum/all/how-to-include-onenote-in-sendto-context-menu-in/c376fc82-aa62-4477-bbe4-8eca6e86742b 
* https://pureinfotech.com/windows-11-shell-commands-list/

**Comment by stevencohn** [comment]
You can open an existing local notebook folder using the OneNote File/Open menu. You can create a new local notebook using the OneNote File/New menu.

This is likely a less than 1% use case so will place it in the parking lot for now, low priority

**Comment by maphew** [comment]
No argument about the low percent use case, however I'd like to point out that File-New and File-Open are not precisely the same as Send-to-Onenote or Select-open-with-onenote. The latter works with any folder, which might have content that's not created by OneNote, while the former is either creating a new OneNote book or opening an existing one.

At any rate, for my use I'm satisfied with the Send-to method.

**Comment by stevencohn** [comment]
Closing as I see no difference between the built-in ability to create a new notebook in a folder or open an existing notebook from within a folder.
