### ISSUE TITLE
New Feature/ markmap and markdown hotkeys convert support

### ISSUE THREAD

**Issue by ALbur** [stevencohn/OneMore#1028]
# New Feature
Similar to the current feature for converting PlantUML images, it would be beneficial to have support for markmap (https://markmap.js.org/) and a hotkeys for converting markdown syntax to display on OneNote pages.
![image](https://user-images.githubusercontent.com/24468956/235331083-63edb2e4-1cdc-46c2-a69c-2fdcd0219c42.png)
![image](https://user-images.githubusercontent.com/24468956/235331089-41ab7218-d572-487f-afc0-d4b6a5fbd6e4.png)

**Comment by the-moog** [comment]
+1 for adding even basic Markdown. (Despite being rejected here: https://github.com/stevencohn/OneMore/issues/1021#issue-1676165831)

I use VSCode a lot, and plugins for that allow inline Markdown, plus most README's are Markdown, and Doxygen/pydoc are able to render it - hence most non-code text is also Markdown .
Being able to copy code snippets from/to OneNote+OneMore and VSCode, and keep the rendering would be amazing - TBH rather surprised M$ are not doing this, but in the 30+ years I have used Windows, M$ have always failed to adopt common concepts across their apps, so why start now.....Hmm perhaps they'll just adopt, support and bundle this project instead :-) 

Though personally I'd happily pay for OneMark, our organisation will usually push back on closed source extensions being installed when they have remote monitoring policies. Our organisation has (quite justified) paranoia about IP leaks.  Most open source code suffers less from this issue as IT deparment can validate it's license terms, telemetry content and even build it themselves if they are concerned.

BTW: Being able to automate markdown output from shared OneNotes through OneMore Markdown rendering from the (ideally Linux) command line / RPC / Jenkins would also be useful for CI doc generation in Doxygen.
(I won't hold by breath for M$ to cross platform OneNote yet)

**Comment by dXrayb** [comment]
https://github.com/stevencohn/OneMore/issues/1021
According this, I think this feature will never add to Onemore.

**Comment by stevencohn** [comment]
Added _Convert to Markdown_ command to convert selected markdown text to formatted OneNote content. Bound to Shift+Alt+M.... Next release
