### ISSUE TITLE
not menu display bar

### ISSUE THREAD

**Issue by yanite** [stevencohn/OneMore#1032]
office 2016 
cat onemore.log 

01| Starting dllhost 19492, 2401 Mhz, 32 MB, zh-CN/zh-CN, v5.8.4, OneNote 15.0, Office 14.0, 2023-05-14 23:03
01| ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.16327.20248)
01| ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
01| ..OneAddInsUpdate(custom[])
01| ..OnStartupComplete(custom[])
01| ..starting command service
01| ..starting reminder service
01| ..starting navigation service
01| ..ready
06| error invoking action
06| System.Runtime.InteropServices.COMException
Message: 异常来自 HRESULT:0x80042019
Description: The query is invalid
ErrorCode: 0x80042019 (-2147213287)
HResult: 0x80042019 (-2147213287)
Source: Microsoft.Office.Interop.OneNote
StackTrace:    在 Microsoft.Office.Interop.OneNote.ApplicationClassCOM.FindMeta(String bstrStartNodeID, String bstrSearchStringName, String& pbstrHierarchyXmlOut, Boolean fIncludeUnindexedPages, XMLSchema xsSchema)
   在 River.OneMoreAddIn.OneNote.<>c__DisplayClass71_0.<SearchMeta>b__0()
   在 River.OneMoreAddIn.OneNote.<InvokeWithRetry>d__34.MoveNext()
TargetSite: [Microsoft.Office.Interop.OneNote] Microsoft.Office.Interop.OneNote.ApplicationClassCOM::FindMeta()

03| defined 43 hotkeys for input locale 2052
16| error invoking action
16| System.Runtime.InteropServices.COMException
Message: 异常来自 HRESULT:0x80042019
Description: The query is invalid
ErrorCode: 0x80042019 (-2147213287)
HResult: 0x80042019 (-2147213287)
Source: Microsoft.Office.Interop.OneNote
StackTrace:    在 Microsoft.Office.Interop.OneNote.ApplicationClassCOM.FindMeta(String bstrStartNodeID, String bstrSearchStringName, String& pbstrHierarchyXmlOut, Boolean fIncludeUnindexedPages, XMLSchema xsSchema)
   在 River.OneMoreAddIn.OneNote.<>c__DisplayClass71_0.<SearchMeta>b__0()
   在 River.OneMoreAddIn.OneNote.<InvokeWithRetry>d__34.MoveNext()
TargetSite: [Microsoft.Office.Interop.OneNote] Microsoft.Office.Interop.OneNote.ApplicationClassCOM::FindMeta()

01| OneAddInsUpdate(custom[])
01| OnBeginShutdown(custom[])
01| ..shutting down UI
01| ..OnDisconnection(RemoveMode:ext_dm_HostShutdown,custom:[])
01| ..closing log

01| Starting dllhost 22320, 2401 Mhz, 32 MB, zh-CN/zh-CN, v5.8.4, OneNote 15.0, Office 14.0, 2023-05-14 23:11
01| ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.16327.20248)
01| ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
01| ..OneAddInsUpdate(custom[])
01| ..OnStartupComplete(custom[])
01| ..starting command service
01| ..starting reminder service
01| ..starting navigation service
01| ..ready
06| error invoking action
06| System.Runtime.InteropServices.COMException
Message: 异常来自 HRESULT:0x80042019
Description: The query is invalid
ErrorCode: 0x80042019 (-2147213287)
HResult: 0x80042019 (-2147213287)
Source: Microsoft.Office.Interop.OneNote
StackTrace:    在 Microsoft.Office.Interop.OneNote.ApplicationClassCOM.FindMeta(String bstrStartNodeID, String bstrSearchStringName, String& pbstrHierarchyXmlOut, Boolean fIncludeUnindexedPages, XMLSchema xsSchema)
   在 River.OneMoreAddIn.OneNote.<>c__DisplayClass71_0.<SearchMeta>b__0()
   在 River.OneMoreAddIn.OneNote.<InvokeWithRetry>d__34.MoveNext()
TargetSite: [Microsoft.Office.Interop.OneNote] Microsoft.Office.Interop.OneNote.ApplicationClassCOM::FindMeta()

03| defined 43 hotkeys for input locale 2052
01| OnBeginShutdown(custom[])
01| ..shutting down UI
01| ..OnDisconnection(RemoveMode:ext_dm_HostShutdown,custom:[])
01| ..closing log

**Comment by untitleder** [comment]
same issue
Microsoft® OneNote® 适用于 Microsoft 365MSO (版本 2304 Build 16.0.16327.20200) 32 位
cat onemore.log

01| Starting dllhost 16808, 2803 Mhz, 128 MB, zh-CN/zh-CN, v5.8.4, OneNote 15.0, Office 16.0, 2023-05-20 11:19
01| ..C:\Program Files (x86)\Microsoft Office\Root\Office16\ONENOTE.EXE (16.0.16327.20248)
01| ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
01| ..OneAddInsUpdate(custom[])
01| ..OnStartupComplete(custom[])
01| ..starting command service
01| ..starting reminder service
01| ..starting navigation service
01| ..ready
06| error decoding reminder
06| 03| defined 43 hotkeys for input locale 2052
System.NullReferenceException
Message: 未将对象引用设置到对象的实例。
Source: River.OneMoreAddIn
StackTrace:    在 River.OneMoreAddIn.Commands.ReminderSerializer.Decode(String value)
TargetSite: [River.OneMoreAddIn] River.OneMoreAddIn.Commands.ReminderSerializer::Decode()

**Comment by stevencohn** [comment]
Not able to reproduce but added extra error handling around reminder discovery and deserialization that might help... will be available as part of the next release
