### ISSUE TITLE
Add  progress bar for the add on operations

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#105]
**Is your feature request related to a problem? Please describe.**
Currently a spinning wheel is used but that is confusing, you can't be sure if OneNote or Windows is in trouble (slow) or it is the addon

**Describe the solution you'd like**
Currently a spinning wheel is used but that is confusing, you can't be sure if OneNote or Windows is in trouble (slow) or it is the addon
**Describe alternatives you've considered**
N/A

**Comment by stevencohn** [comment]
The addon has a progress bar for  many operations that may take a while. Which one are you specifically worried about?

**Comment by 1001QAdotNET** [comment]
The ones that I am using the most are the clean up ones and the one that adds indentation. I dont remember seeing the progress bar there. As you know I am reading ample articles or books and when I ise the addon I do ir for large pieces of text.

**Comment by stevencohn** [comment]
OK thanks. I'll try testing with longer pages! 

Generally, the commands themselves are quicker than the time it takes to load and save the page content through the interop APIs so I may be able to speed up some command logic but, at some point, may be constrained by the OneNote APIs themselves

**Comment by stevencohn** [comment]
As I suspected, the commands take less than a second (most less than 1/10 sec) but loading and re-saving very long pages can take 10-30 seconds depending on length and complexity. Adding a progress bar wouldn't improve the experience because the expensive operations are atomic and still result in a spinning mouse cursor.
