### ISSUE TITLE
TOC links created by OneMore don't work

### ISSUE THREAD

**Issue by dshively** [stevencohn/OneMore#1052]
When creating a TOC within a page, none of the links work (including each [Top of Page] link). They don't generate an error; they just don't do anything at all.

All created links are in the form of:
`onenote:https://d.docs.live.net/<unique id>/<path to my notebook>#<page name><section-id><page-id><object-id>`

This behavior applies to most of my notebooks. I do have one notebook in which TOC links work. In this case, the TOC generates links in the form of:
`onenote:#<page name><section-id><page-id><object-id>`

In other words, the following OneDrive notebook path is not included:
`https://d.docs.live.net/<unique id>/<path to my notebook>`

To reproduce:
1. Create a new page
2. Create a couple of headings with text under each
3. Select Snippets > Table of Contents > Insert a table of headings on this page
4. Check "Add link to each heading to jump to the top of page"
5. The links created are of the type above which contain "d.docs.live.net", and they don't do anything (no error messages, etc.)

Expected behavior:
TOC is created with links that don't have the "d.docs.live.net" notebook path, and these links actually work.

I should note that I am signed in to OneDrive, and the embedded unique identifier is the same in notebooks for which the TOC links work as it is in notebooks for which the TOC links do not work.

I should also note that I tried using OneTastic to create a page TOC on the same page, and the links generated are the local links (i.e. without "d.docs.live.net"), and thus work correctly. Not a solution, because I'd rather use OneMore.

BTW all the above applies to:
OneMore Version 5.8.5 with thick client OneNote 16.0.16529.20154

Thanks,
Danny

**Comment by stevencohn** [comment]
When a Table of Contents is created, all hyperlink should be created with URLs that contain base-path attributes as described here. The full URL syntax is determined by whether the notebook is managed locally or managed on OneDrive. Local notebooks will have hyperlink hrefs of the form

`onenote:#Headings&amp;section-id=...&amp;page-id=...&amp;object-id=...&amp;F&amp;base-path=C:\local-path-here.one`

whereas OneDrive notebooks will have hyperlink hrefs of the form

`onenote:#Headings&amp;section-id=...&amp;page-id=...&amp;object-id=...&amp;F&amp;base-path=https://onedrive-path-here.one`

Notice that they diff by base-path attribute, specifying either a local hard-drive URI or a remote OneDrive URI.

If your TOC does not contain the base-path attribute then I would need more information as this is internally generated by OneNote, not generated by OneMore.

**Comment by dshively** [comment]
None of my notebooks have TOC URLs containing the base-path attribute. As I said in my original posts, the TOC URLs are all in the form of either: 
`onenote:#<page name><section-id><page-id><object-id>`
or 
`onenote:https://d.docs.live.net/<unique id>/<path to my notebook>#<page name><section-id><page-id><object-id>`

When checking notebook file location via File > Info, the file locations of **all** of my notebooks are in the form of:
`https://onedrive.live.com/view.aspx?resid=<unique id>&id=documents `

This is true whether OneMore generates TOC links in either of the two forms I mentioned above (again, neither of those two forms include a base-path attribute). 

Which leaves me with two questions:
1. What additional information do you need, given my TOC links don't contain the base-path attribute?
2. How can I stipulate to OneNote that I want to manage my notebooks locally (short of uninstalling OneDrive)? 

For context, I have used OneDrive to mirror my local Documents folder continually for several years, and I have also used OneNote in exactly the same way for several years. I don't detect any correlation between notebook creation date and which notebooks have TOC links with `https://d.docs.live.net` in the URL.

**Comment by stevencohn** [comment]
After looking more closely, the base-path doesn't appear to be relevant at all anyway. I can use OneMore's XML Dialog to edit the page and remove that part of the URL and links still work as expected.

OneMore uses an internal OneNote Interop API to convert a page object (paragraph) to a URL. OneMore doesn't generate these URLs itself or modify them in any way. 

So it's either a bug in OneNote or there's something else going on. You're not using a beta or pre-release version, are you?

**Comment by dshively** [comment]
Just checked my version and saw that an update is available. I updated and am now using the following version (pasted from "About OneNote":
Microsoft® OneNote® for Microsoft 365 MSO (Version 2307 Build 16.0.16626.20028) 64-bit 
As before, I'm using OneMore 5.8.5

I just re-reproduced the same behavior. I took an existing notebook page that had never had a TOC, and I used OneMore to create the TOC. As above, all of the created links are in the form of: 
`onenote:https://d.docs.live.net/<unique id>/<path to my notebook>#<page name><section-id><page-id><object-id>`

For a given heading, I then _manually_ used the context menu > Copy Link to Paragraph to generate an URL for the heading. That URL was in the form of:
`onenote:#<page name>&section-id=<section-id>&page-id=<page-id>&object-id=<object-id>&base-path=https://d.docs.live.net/<unique id>/<path to my notebook>`

So interestingly, the base-path attribute is now present. And, as before, the manually generated link works perfectly. 

As before, in other TOC URLs found in OneMore-generated TOCs, if I simply remove the 
`https://d.docs.live.net/<unique id>/<path to my notebook>`
portion from the generated URL, the link works correctly.

**Comment by dshively** [comment]
Just a quick update to say that I am no longer able to reproduce the issue. I'm not sure what's changed, but I'm using OneMore 5.8.5 and the latest version of OneNote:
`Microsoft® OneNote® for Microsoft 365 MSO (Version 2307 Build 16.0.16626.20086) 64-bit `

Now, links created by the OneMore TOC snippet work correctly. They're still in the form I noted above (i.e. with the "d.docs.live.net" URL), but they work now. Perhaps this was a OneNote bug, or some temporary misconfiguration of my OneDrive, or something else. Since I don't know what was broken, I don't know how it got fixed.

But anyway, as far as I'm concerned this one can be closed. Thanks for your time!
