### ISSUE TITLE
setting export/import for synchronization on multiple computers

### ISSUE THREAD

**Issue by youarenever** [stevencohn/OneMore#1053]
This is a great plugin, thank you so much!

Can you add a setting export/import functionality that includes all configurations such as settings, Snippets, etc., to facilitate synchronization on multiple computers?

**Comment by stevencohn** [comment]
I could but it also quite simple to copy your settings file from one computer to another. It should be located here: %APPDATA%\OneMore\settings.xml

Just copy it to another computer under the same path, %APPDATA%\OneMore
