### ISSUE TITLE
API link?

### ISSUE THREAD

**Issue by SmartBoy84** [stevencohn/OneMore#1054]
Would it be possible for links to **specific** highlights be implemented? Currently only whole paragraphs can be linked

**Comment by stevenmcohn** [comment]
No. This is limited by OneNote functionality. OneNote can hyperlink to "objects" on a page. A paragraph, an image, an embedded file - these are the smallest objects on a page. 

A highlight within a paragraph is nothing more than text styling within a paragraph, not an object itself.

**Comment by stevencohn** [comment]
No. This is limited by OneNote functionality. OneNote can hyperlink to "objects" on a page. A paragraph, an image, an embedded file - these are the smallest objects on a page.

A highlight within a paragraph is nothing more than text styling within a paragraph, not an object itself.

**Comment by SmartBoy84** [comment]
Unfortunate, thanks for explaining!
