### ISSUE TITLE
web in onenote?

### ISSUE THREAD

**Issue by youarenever** [stevencohn/OneMore#1063]
hi, I have a question. In the higher version of OneNote 2016, it supports embedding some website content directly into the page display, like this screenshot. 
![image](https://github.com/stevencohn/OneMore/assets/18183177/8ba0722f-b334-4037-a3c0-a17127305dde)

However, the websites supported by OneNote are limited. Is there any way to support website and local HTML content? This would increase the possibilities.

Thanks

**Comment by stevencohn** [comment]
Unfortunately, no.
