### ISSUE TITLE
Add page splitting function

### ISSUE THREAD

**Issue by Silfra-glacier** [stevencohn/OneMore#1065]
Hello, with the update of OneNote, some pages have too much content (especially ink). When the page is too long (which usually makes the size of a page after export exceed 60MB), various operations such as moving and writing can become very cumbersome.
I hope to add page splitting function, customize parameters, specify the number of pages to be divided, or use the length of each divided page to directly truncate the page from the specified length of the current page to form a new page. I can choose whether to keep the original page. (This may be difficult at the truncation point, but it can be "rough truncation", such as choosing not to process images or other logic)
thanks

**Comment by stevencohn** [comment]
OneMore already has a _Split Page_ command. It's available on the OneMore Page menu. It will split a page based on Heading 1 boundaries https://onemoreaddin.com/commands/Page%20Commands.htm
