### ISSUE TITLE
Upload XML to GitHub

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#107]
**Is your feature request related to a problem? Please describe.**
Upload the XML version of a page to GitHub

**Describe the solution you'd like**
This would allow version control for the pages the user chose to track 

**Describe alternatives you've considered**
Manual uploading or via the Python plugin hook

**Additional context**
I think this would be a nice feature

**Comment by stevencohn** [comment]
This is a fair amount of work that certainly has alternative solutions, not the least of which is the built-in page versioning feature in OneNote. I know that's not perfect and you can't control when versions are created.
