### ISSUE TITLE
Feature: Ability to remove idents in a selection of text

### ISSUE THREAD

**Issue by jwhalen99** [stevencohn/OneMore#108]
I would love to be able to quickly left align selected text removing all spaces and tabs.

i.e.

Test line 1
   Test Line 2
      Test Line 3
      Test line 4

**Becomes:**
Test line 1
Test line 2
Test line 3
Test line 4

This makes it much easier when cutting and pasting list of stuff that you want to quickly remove all padded spaces.

**Comment by stevencohn** [comment]
If you mean trim leading whitespace, as opposed to outdenting indented lines, that this is possible. OneMore already has a trim trailing whitespace command. I think it would be easy enough to add a trim leading whitespace command.

Is this what you're asking?

**Comment by jwhalen99** [comment]
Yes that is exactly what I am asking for. Trim leading white spaces. Unfortunately when I posted the comment it actually trimmed the white spaces in my example :)
