### ISSUE TITLE
FR: Show and convert image format 

### ISSUE THREAD

**Issue by raenye** [stevencohn/OneMore#1081]
# Problem to Solve

OneNote supports multiple image formats (PNG, JPG, EMF; maybe others) and when pasting images from the clipboard, the format is (mostly) retained. In particular, when pasting images taken by snipping tools (either the built-in OneNote's "take screen clipping", or Windows' snipping tool), the image format is always PNG. This may lead to excessive storage size.

#152 went a long way towards being able to assess the extent of the problem (by showing storage size in the `Resize and Adjust Image` dialog) and to fix it (by either reducing quality, or exporting to an external editor) but it could be made much more streamlined and useful.

Currently a reduction of quality from 100 to 50 does very little to reduce the storage size in PNG format (which is expected, PNG is lossless and not suited to photo-like images).

# New Feature/Solution

1) Show current image format in the `Resize and Adjust Image` dialog.
2) Be able to convert between formats as part of the quality reduction feature.
3) Hopefully, some method to batch process notes or notebooks.

## Alternative Solutions

1) It is possible to find out the current format of an image using the following process:
Right click --> `Open Image With` --> switch to `Paint` and see the file extension.
2) It is possible to convert the format using `Save As` within `Paint`, copy the contents to the clipboard (as JPG) and paste it to OneNote over the current image, losing properties such as display height/width and hyperlinks.
3) Obviously current workarounds need to be done manually per-image.

# Additional Context

Most of the infrastructure seems to be there, thanks to #152

Thanks!

**Comment by stevencohn** [comment]
Resize dialog displays image type, appended to the "Preview" group box title.

Added Compress Images command to the Images menu to compress selected or all images on the current page. Shows number of images affected and storage bytes saved in the XML.

**Comment by stevencohn** [comment]
After further testing, I realized a few things. I should have remembered this already but both JPG and PNG are compressed file formats. The only way to decrease the storage size is to decrease quality and/or dimensions. Unfortunately, OneNote seems to do something strange with images of reduced quality and, even though OneMore hands it a smaller image, the end result is somehow a longer stream of bytes stored on the page! (It's stored as a Base64 string representation of the image byte stream.)

This means that regardless of whether it's PNG or JPG, the real way to reduce the stored size of an image is to shrink the dimensions which is the original intend of the Resize and Adjust dialog.

I'll keep the Compress Images command to continue experimenting but I'm not convinced of its usefulness.

**Comment by stevencohn** [comment]
Change algorithm from quality to resize. 
Quality will be compromised as a result of the resize! So it will be up to the user to decide whether the incremental saving in storage are worth the loss in quality

**Comment by raenye** [comment]
Thank you, I will test it once the next release is available.

It does seem that workaround 2 above yields a shorter byte stream without any noticeable effect (that is, when the image is photo-like so lossy JPEG makes more sense than a lossless format such as PNG).
