### ISSUE TITLE
Icons in Menu are not clear in Dark Grey or Black mode

### ISSUE THREAD

**Issue by JohnMarkHowell** [stevencohn/OneMore#1082]
# Problem to Solve

When changing the appearance of OneNote to Dark Grey or Black, the OneMore icons become unrecognizable. Please see the attached screenshots.

# To Reproduce

1. Open OneNote (with the OneMore add-in installed and enabled)
2. Change appearance to either Dark Grey or Black

# Expected Behavior

You should still be able to recognize the icons in the OneMore menu bar section.

# Screenshots

![DarkGreyAndBlack](https://github.com/stevencohn/OneMore/assets/5066153/20c1061b-99b5-4d60-9121-4a33ddf13be7)

# Environment Windows 11 Enterprise 22H2 Build# 22621.1992

 - OneNote Version: Microsoft® OneNote® for Microsoft 365 MSO (Version 2307 Build 16.0.16626.20170) 64-bit 
 - OneMore Version Version 5.8.5 with OneNote 16.0.16626.20170

# Additional Context

**Comment by stevencohn** [comment]
Interesting because I always run in Dark mode and see this

<img width="158" alt="image" src="https://github.com/stevencohn/OneMore/assets/9964757/3d29eb3e-5567-45b6-8f0f-26a8ab7125cf">

So I'm not sure how to replicate your problem.

**Comment by JohnMarkHowell** [comment]
If that's the case, then I am inclined to believe it is a display driver issue, not a OneMore issue.
Thank you for such a quick response and such an amazing add-in.  I purchased OneMark and was not happy with its 'quirks' and saw your add-in. OneMore blows OneMark away in features and quality.

Any plans for adding Json to the list of languages for styling (Alt+C) ?

**Comment by stevencohn** [comment]
You can use Javascript to style Json. Works well enough that I haven't considered making it its own language. But could if there's a need.

**Comment by JohnMarkHowell** [comment]
@stevencohn I found the culprit of the odd display. If I change the theme from the Settings app, everything seems to display fine. However, if I change the theme from inside OneNote, the coloring is not displayed properly. 
This is not an ask for a fix, but just letting you know.
Thank you again for an amazing add-in!

**Comment by stevencohn** [comment]
I guess that makes sense since OneNote doesn't inform addins like OneMore that it's changing the theme. Upon startup, OneNote asks OneMore for its bits of the ribbon to display. If you restart OneNote, does it look OK then?

**Comment by JohnMarkHowell** [comment]
It does if I only have one instance of OneNote up. If I have multiple instances, then it seems I have to close them all before the ribbon seems OK.
