### ISSUE TITLE
Embed Page can not embed a page without a note container?

### ISSUE THREAD

**Issue by seaspeak** [stevencohn/OneMore#1085]
# Problem to Solve

Embed Page embeds the first and only the first note container.
Should Embed Page embed all contents in a page?

# To Reproduce

1. Copy and Paste a picture to a new page. 
2. Drag the picture out of the container while holding the Shift key.
3. Embed this page from another page.
4. OneMore shows no content in this page.

# Expected Behavior

"Embed Page" should embed all contents in a page.

# Screenshots

# Environment (if applicable)

 - OneNote Version: 64bit 2021
 - OneMore Version: 5.8.5

# Additional Context

**Comment by stevencohn** [comment]
This is as-designed. There is additional complexity in pulling in multiple containers as far as layout, sequencing etc. Yes, there are alternative solutions but the complexity is still real.

The intent is that you can define and reuse/embed small modules/widgets/components/snippets rather than highly complex content.

**Comment by seaspeak** [comment]
I see. I can understand the reson to embed the first container only now, thanks.

My point is there is a chance that a page with no container still contains something. For exmaple, inserting a printout, a floating picture (see the attached screenshot). A little frustrating to see things but can't embed them. Pasting it into a container solves anything, of course. I am a bit of a perfectionist. :-)

Is that possible to change the algorithm to embed the first object, a container or something else(I don't know what are they will be)?

![image](https://github.com/stevencohn/OneMore/assets/8821870/cb33bd53-97ca-48cc-8811-ee6eca24bd22)

**Comment by stevencohn** [comment]
FYI, first object of a printout is the first page only. There's no way to differentiate this from multiple background images or file attachments.

**Comment by stevencohn** [comment]
Oh, I was going to grab the first item, regardless of what it is. Do you want me to keep this open?

**Comment by seaspeak** [comment]
> Oh, I was going to grab the first item, regardless of what it is. Do you want me to keep this open?

Oh, I misunderstood your meaning. This has made me question my own judgment. If you think it's feasible, please reopen it.
