### ISSUE TITLE
Link Reference to This Page refresh does not update changed page titles

### ISSUE THREAD

**Issue by zhongguocn** [stevencohn/OneMore#1089]
# Problem to Solve
After adding a link to page B in page A, if you modify the title of page B, you Refresh the reference information in page A . the text of the link in page A does not automatically update to reflect the modified title of page B.

# To Reproduce

Step1
![image](https://github.com/stevencohn/OneMore/assets/38025627/d7efc9ef-1cf1-439e-accb-2246d934edaf)

![image](https://github.com/stevencohn/OneMore/assets/38025627/cd5815f4-6093-4a61-8649-484a3b9f5214)

Step2
Change Title of Second page

![image](https://github.com/stevencohn/OneMore/assets/38025627/a036c578-cf65-4cc3-ad84-67eafd21ac1d)

Step3
Refresh Linked References in First Page
![image](https://github.com/stevencohn/OneMore/assets/38025627/b7024d6c-ab65-4989-bb80-ac18544ae91b)

**Comment by stevencohn** [comment]
That's not how this command works.

You have pages A and B, where A links to B _and_ B links to A. 
Then you _Link refs to this page_ from page A.

That will only look for pages that mention the title of page A, hyperlink those title references to page A, and create a summary report of those pages at the bottom of page A. It's a one-way lookup - it will not change references on page A to other pages. 

There is a slightly related command, _Refresh Page References_. This is also a one-way command. If page A references page B and you rename page B, then you can run this command _from page B_ and will update other pages that link to it.

**Comment by stevencohn** [comment]
However, now that I look closer, the Refresh Page References command does indeed have a bug so I'm fixing that for the next reelease.

**Comment by stevencohn** [comment]
It's fixed. Will be part of the next release.
