### ISSUE TITLE
Feature: Ability to insert horizonal line as a keyboard shortcut

### ISSUE THREAD

**Issue by jwhalen99** [stevencohn/OneMore#109]
**Is your feature request related to a problem? Please describe.**
It would really be helpful to be able to add a horizontal line as a keyboard shortcut.
I use this feature a lot to basically breakup ideas or chunks of code.

You currently have it as a snippit.

**Comment by stevencohn** [comment]
Shift + Alt + Minus

Keyboard shortcuts are listed here: https://github.com/stevencohn/OneMore/wiki
