### ISSUE TITLE
Rotating Highlighter: No color and four colors in order

### ISSUE THREAD

**Issue by seaspeak** [stevencohn/OneMore#1090]
# Problem to Solve

1. There should be No Color in the rotating order.
2. Four colors collection, yellow, red, green , blue, is popular and enough.

# New Feature/Solution

So far there is no shortcut to remove the highlight. Adding a No Color in order is a fast and good way to implement it.

## Alternative Solutions

A floating menu is even better. Check the screenshot from Google Play book below.
ChatGPT also recommends four colors for general purpose.

>
![image](https://github.com/stevencohn/OneMore/assets/8821870/70f4ed12-a7e0-40cf-8910-db25fc5ecd2d)

# Additional Context
From Google Play Book
![image](https://github.com/stevencohn/OneMore/assets/8821870/52ce65b3-ab0c-429f-b39c-61e2b0921312)

**Comment by 1001QAdotNET** [comment]
Chatgpt is a f...moron!
If you happen to have a long phrase that spans multiple short rows you often end up with adjacent colors in successive lines, hence my request to actually add more colors not to remove colors
Probably a solution to keep everybody happy is to make the theme customizable to the order of how many colors and what colors, with no color an option.

**Comment by stevencohn** [comment]
Rotating Highlighter itself is admittedly a rather specific requirement. I like the idea of optionally allowing no-color in the rotation. But I'm hesitant to add too much complexity to a very simple and narrow feature.

**Comment by seaspeak** [comment]
Can you explain how you use the tool specifically? Actually, I don't quite understand the use case, can't picture how people will rainbow their book contents. The note-taking methods I know are all from Google. Most of them suggest keeping it simple and less colors and giving the color a meaning. I guess people use the tool for vairous purpose.

Anyway, my main point is 
1. to add No Color in the roation. 
2. Introduce another keyboard shortcut to repeat the last color so that it won't change the rotating function.

The Google Play book floating menu is just piece of information for reference. It is too much.

**Comment by stevencohn** [comment]
OneNote has a built-in highlighter than you can use to select a color and then highlight multiple selections with that same color.

The Rotating Highlighter was suggested by a user who wanted to highlight multiple contiguous runs of text within a paragraph but still be able to differentiate those selections. This was a simple and effective way of creating a visual delineation in this case.

**Comment by 1001QAdotNET** [comment]
> I don't quite understand the use case, can't picture how people will rainbow their book contents. 
I was the one who asked for this feature
If you read complex IT/Science books and you need to distinguish between various concepts requirements etc etc introduced in the same phrase you need such tool. 
The idea is to be able to come back later and quickly recap what is important by just reading the highlighted text
Someone asked for a feature to extract all these from a book or text you are reading. I support that request
The idea is to extract the bits of info you need, the essential knowledge and get rid of the bloated text that was required to explain the concepts.

**Comment by stevencohn** [comment]
Yes, you did. Here is the [original ask](https://github.com/stevencohn/OneMore/issues/54) which means, given a block of text, highlight two contiguous runs but with different colors, allowing highlighting like this:

<img width="296" alt="image" src="https://github.com/stevencohn/OneMore/assets/9964757/ccd1039d-e4bc-4e22-a137-63f7635a5eea">

Without the rotation, you end up with this

<img width="295" alt="image" src="https://github.com/stevencohn/OneMore/assets/9964757/15c5a160-1c62-48f6-a23e-b2427acaabd7">

What you're asking now is an entirely different feature - using highlighting to logically associate blocks of text by their highlight. What I think you're actually asking for is a pinned palette of colors that you can selectively choose from by either clicking or pressing assigned keys.

**Comment by 1001QAdotNET** [comment]
I thinkby "you" you mean @seaspeak 
My request  https://github.com/stevencohn/OneMore/issues/1086 is asking about the option for the user to add a custom set of colors and to make that more than 5 eventually

**Comment by stevencohn** [comment]
I was referring to your original ticket #54 from way back in 2020

**Comment by stevencohn** [comment]
Rather than complicate and change the behavior of the Rotating Highlighter command, `Ctrl+Shift+0` is now bound to a new _Remove Highlighting_ command

**Comment by seaspeak** [comment]
> Rather than complicate and change the behavior of the Rotating Highlighter command, `Ctrl+Shift+0` is now bound to a new _Remove Highlighting_ command

Do you mean `Ctrl+Alt+0`? which sets the style to 'Normal', changes every thing not just background color.

**Comment by stevencohn** [comment]
No. `Ctrl+Alt+0` remains the same; this is a built-in OneNote binding. `Ctrl+Shift+0` will only remove highlighting and keep all other styling

**Comment by seaspeak** [comment]
> No. `Ctrl+Alt+0` remains the same; this is a built-in OneNote binding. `Ctrl+Shift+0` will only remove highlighting and keep all other styling
Interesting, I don't have that binding. Let me figure it out....

**Comment by stevencohn** [comment]
You won't have it because I just checked it into the code base. It will be available in the next release as labeled on this ticket.
