### ISSUE TITLE
Rotating Highlighter: Start from the last color

### ISSUE THREAD

**Issue by seaspeak** [stevencohn/OneMore#1091]
# Problem to Solve

There is a high chance that the user would use the same color next time.

# New Feature/Solution

After the user stop rotating the color, OneMore could wait for a short period of time, e.g. one second, then remember that current color. Next time, OneMore should start from the last (current) color not from the next color.
But if the current color is No Color (#1090), it should start from the next color.

## Alternative Solutions

1. add No Color in the roation.
2. Introduce another keyboard shortcut to repeat the last color so that it won't change the rotating function.

# Additional Context

**Comment by 1001QAdotNET** [comment]
If you need things to work that way all you have to do is to press the highlighter multiple times to get to the color you want to start with. This will over complicate a simple tool and the user won't get the idea.
The way you are describing it will duplicate two colors at the end of the cycle/start of a new one if the user waits 1 second or whatever that time would be. "Waiting" happens a lot because you are highlighting as you read 

Please don't mess up with this tool, not sure how you use it but the two changes you just suggested are going to make a mess out of it and it would become unusable and confusing

**Comment by seaspeak** [comment]
I just add an alternative solution: Introduce another keyboard shortcut to repeat the last color so that it won't change the rotating function.

**Comment by stevencohn** [comment]
There's also the built-in highlighter...

**Comment by seaspeak** [comment]
Do you mean Ctrl + Alt + H? Can't switch color quickly.

**Comment by stevencohn** [comment]
Yes, it is what it is. Colors are on the toolbar drop down. Yes, it's a click away but it's a perfectly viable solution.

**Comment by seaspeak** [comment]
The "Rotating Highlighter" almost meets my needs; the built-in one is just too slow. Additionally, when text is selected, the Rotating Highlighter doesn't allow me to see which color has been applied after highlighting. Is there a way to make it more visible to the user?

**Comment by 1001QAdotNET** [comment]
Maybe Steven could change the color of the button with each iteration, to indicate the next color that would be applied if the button in pressed. It the button is pressed, and nothing is selected it will simply move to the next color

**Comment by 1001QAdotNET** [comment]
As long as it does not modify the rotation anything added should be fine if others need it

**Comment by stevencohn** [comment]
`Ctrl+Shift+H` is the default binding for rotating highlighter
`Ctrl+Shift+J` is bound to _highlight using most recently used highlighter color_

**Comment by seaspeak** [comment]
> Excellent idea! But sadly no, I cannot change the color :-(

It might sound silly. How about after applying the highlight, deselect for a blink moment (200 milliseconds or so) to reveal the highlight color, and then select back.

**Comment by stevencohn** [comment]
Making any updates to the page, writing back to OneNote through the interop API, is the slowest step and will be highly noticeable on larger pages. You're talking about three updates in a role actually.
