### ISSUE TITLE
Add the option to synchronize/offset the rotating highlighter and the onemore highlighter

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#1095]
I am thinking this could be easy.
In order to change the default highlighter you need to select your new color
I am assumming this could also be API driven
If that is possible then it should be possible to set the rotating highlighter, if the users wants this, with the rotating highlighter
What would be the advantage of this ?
Assume you have used the rotating highlighter and this marked the text for you and it moved to the next color
When it does that it could also set the color of the default onenote highlighter to the next color in the onemore selected theme
When you select the text for the next highlighting this always brings up the context dialog but this time the next color you would want is alredy set there you can just simply use it (instead of using the rotating highlighter that will apply the same color) 
This is practically a shortcut. 
The disadvantage is that is you use the highlighter again it will repeat the color.
Not sure if there is a way to monitor the use of the system highlighter and set that one to a new color (from the onemore theme) after it was used. If this is possible then the default highlither could be turned into an alternative to the rotating highlighter

I hope this is not that complicated as it is to describe it :-):-)

**Comment by stevencohn** [comment]
The blocking issue is that the OneNote Office Interop API provides no access to manipulate or drive the built-in functionality or ribbon, including setting the highlighter color.
