### ISSUE TITLE
Table Of Contents - Section Groups - make them consistent 

### ISSUE THREAD

**Issue by jasonjac2** [stevencohn/OneMore#1100]
# Problem to Solve
Periodically I do a "Table Of Contents | Add page with table of sections of this Notebook" + Include Pages.
I leave it for a while and it produces me a lovely page.  I can actually take that page and do lots with it (copy to excel, save to HTML Save to PDF).

![image](https://github.com/stevencohn/OneMore/assets/68282090/3158f3f2-88c7-43ce-be7f-1d937479bfe5)

The problem is that section groups are a little inconsistent.  I don't use section groups very much.
They don't appear as links and also are indendted and bold and have extra blank lines in front of them.
![image](https://github.com/stevencohn/OneMore/assets/68282090/c681f527-b958-4211-947e-ec861d3c19ae)

# New Feature/Solution

Just make them consistent, even if they aren't hyperlinks.
Ideally identify section and section groups in the ToC.  Clicking a Section link can be confusing as it takes you to the most recent page you were on in that section - to this end either (Section) (Section Group)  tagged to the end would visually make it clear.

Thanks as always for an AMAZIN product. Jason

**Comment by stevencohn** [comment]
<img width="332" alt="image" src="https://github.com/stevencohn/OneMore/assets/9964757/40a99fd5-76f9-479a-b42a-21c747474c3b">

**Comment by stevencohn** [comment]
Removed extra line.
Prefix section with Section symbol
I tried various forms of icons, labels, bold vs italic vs normal. But I'm trying to keep it clean.

Regarding the "last page visited" when clicking on a section, this is default OneNote behavior and I didn't want to change that. If you want a specific page then you should be able to click the page in the TOC.

**Comment by jasonjac2** [comment]
Thanks.  some kind of visual feedback is fine for section and section group to stop you from clicking it and feeling like you have gone to a random page. 

You must have a carrier bag of features due for the next release by now.

**Comment by stevencohn** [comment]
You can track what's upcoming by looking for tickets labeled as next-release 
https://github.com/stevencohn/OneMore/issues?q=is%3Aissue+is%3Aopen+label%3Anext-release
