### ISSUE TITLE
The 'Duplicate Page' feature cannot copy ink colors

### ISSUE THREAD

**Issue by Silfra-glacier** [stevencohn/OneMore#1101]
Hello,
When repeating the page, all ink colors turn black instead of the original colors. This situation only occurs on pages with long page content, which may also contain many images, but not on short pages. It may be a bug, and I hope it can be fixed in the next version.
thanks

**Comment by stevencohn** [comment]
I tried testing this with various pages, including a 3MB+ page with about a dozen images but wasn't able to reproduce this. If you can export and share an example page, that would be really helpful.

**Comment by Silfra-glacier** [comment]
Hello,
This is a possible page (at least on my device), where all the highlighter colors change to black after the repeated page takes effect.
![image](https://github.com/stevencohn/OneMore/assets/68190236/14be6b8d-e869-4795-98fb-b6edb9615d18)
![image](https://github.com/stevencohn/OneMore/assets/68190236/63a9328f-7ef7-43b8-af6b-3f8012628b16)
link：https://pan.baidu.com/s/1PtmfUPpXVwIzcJnc6dZlIw?pwd=5hs9 
pwd：5hs9

**Comment by stevencohn** [comment]
Note to self - the highlighted text is done using the Draw highlighter (ink) not the text highlighter (background)

Still unable to repro

**Comment by stevencohn** [comment]
Cannot reproduce
