### ISSUE TITLE
TAG Granularity

### ISSUE THREAD

**Issue by TechNick-92** [stevencohn/OneMore#1103]
# Problem to Solve

Hi Steven,
Thanks for the tool you have provided to those who enjoy MS One Note.

# Problem:
Currently One Note tags apply by default to a paragraph. This is not ideal. For example, it is not possible to sort by a list of keywords only in a given text, a list of concepts only... The full paragraph will be searched instead. 

Imagine you are studying any topic, from a textbook. You are on Chapter 1 right now, you have taken your notes after scoping and chunking the chapter, perhaps in outline form. Now you are about to format such note for easier visualization of concepts, definitions, keywords to aid long-term encoding and so on and so forth. 

Within this text, there might be words, concepts that you might want to tag so to sort for them as a form of maximumly shrunk note. Think about this practice, after you have gone through all the required chapters of your textbooks, manual, etc...

If you make 1 section for such textbook, and a page for each chapter, you can the sort all they keywords, all the identified key concepts, definitions, formulas out of the whole textbook. 

Without this feature, the existing tagging mechanism is not that worthy. The only faux work around would be to insert keywords in the note on a line of their own, the same for concepts, formulas, etc... which would though destroy the cohesiveness and visual of the note. 

# New Feature/Solution
Akin to creating your own styles within OneMore -where you can choose to apply the style to words in paragraph, paragraph or including them in TOC, we could have the option of applying TAGS to words in paragraph as well. 

Thank you for your effort in bringing up OneMore.

Nick

**Comment by stevenmcohn** [comment]
You're correct in that OneNote tags only apply to a paragraph. There's no way to change that. OneMore's tags apply to an entire page.

I think what you're asking for is very similar to this request, #1031. It's a different take but I think the result is the same. Please take a look and let me know if that suits your needs.

**Comment by stevencohn** [comment]
You're correct in that OneNote tags only apply to a paragraph. There's no way to change that. OneMore's tags apply to an entire page.

I think what you're asking for is very similar to this request, https://github.com/stevencohn/OneMore/issues/1031. It's a different take but I think the result is the same. Please take a look and let me know if that suits your needs.

**Comment by TechNick-92** [comment]
Hi Steven,
Yes, it seems very similar. Could that be achieved through styles? It's not the TAG itself, that matters. In a way, a style is kind of a tag. In other words, given the already existing granularity in styles, could styles then be made searchable? Like the existing "find tags" mechanism, that leads to the "tag summary" panel. I am wondering because in the request you have linked, the talk is about kind of filtering the text that is not highlighted or bolded. I would guess, perhaps wrongly, that then even a given color could be filtered, and by this logic, a color + a font + nth thing, which would equal, a style. 

I am not a programmer though, so please forgive me if I my ideas are non-sense. I am just trying to create and optimize a ultimate and comprehensive note-taking system. There is already everything needed within One Note and One More, I am just exploring further possibilities for fine-fine tuning. 

By the way, thanks for pointing out the option of tagging the page within One More. This allows for an incredibly easy implementation of the "Zattelkasten Method". At least, a broader version, less annoying to implement and very useful for research. Without this feature, I would have never bothered to apply this method. Now it's implementable at a cost of time equaling 0. 

I have download your app yesterday and I am really enjoying it. 

Thanks, 
Nick

**Comment by stevencohn** [comment]
Original OneMore tags have been superseded by hashtags offering specific granularity. From there, summaries and reports could be envisioned. That could be discussed in a new ticket, similar to #1030. So closing this ticket for now.
