### ISSUE TITLE
Resize images dialog doesn't pop up, OneNote page unresponsive

### ISSUE THREAD

**Issue by andyylin** [stevencohn/OneMore#1104]
# Problem to Solve

When I click the Resize Images button without selecting an image (to resize all images on the page), the dialog box does not pop up, and the OneNote page shows a blinking cursor but is unresponsive to mouse and keyboard input.

Selecting an individual image does not cause this problem.

# To Reproduce

1. Navigate to a page with multiple images
2. Click on Resize Images without first selecting an image on the page

# Expected Behavior

Usually, the resize all images dialog box pops up.

# Screenshots

# Environment (if applicable)

 - OneNote Version: 16.0.16626.20170
 - OneMore Version 5.8.5

# Additional Context

```
06| Log restarted
01| OnBeginShutdown(custom[])
01| ..shutting down UI
01| OnDisconnection(RemoveMode:ext_dm_HostShutdown,custom:[])
01| disposing 6 streams
01| closing log

01| Starting dllhost 16120, 2600 Mhz, 16 MB, en-US/en-US, v5.8.5, OneNote 15.0, Office 16.0, 2023-08-29 09:51
01| ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.16626.20170)
01| ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
01| ..OneAddInsUpdate(custom[])
01| ..OneAddInsUpdate(custom[])
01| ..building ribbon
01| ..building ribbon colorizer commands
01| ..building ribbon language proofing commands
01| ..building context menu
01| ..OnStartupComplete(custom[])
01| ..starting command service
01| ..starting reminder service
01| ..starting navigation service
01| ..ready
03| defined 44 hotkeys for input locale 1033
17| Running command ResizeImagesCommand
03| ..Running command AboutCommand
```

**Comment by stevencohn** [comment]
I'm afraid I don't have enough information to reproduce this. I've never seen this behavior.

My only thought is to try to run the Office installer in "repair" mode.

**Comment by andyylin** [comment]
> I'm afraid I don't have enough information to reproduce this. I've never seen this behavior.
> 
> My only thought is to try to run the Office installer in "repair" mode.

I installed Office updates and just tested, seems to be working now. Thanks.

**Comment by FunkyJustin** [comment]
I am experiencing the same error, will try to see if repairing fixes the problem
