### ISSUE TITLE
Failure in Export Page - Page title with /'s in it(1 or 2)

### ISSUE THREAD

**Issue by jasonjac2** [stevencohn/OneMore#1107]
# Problem to Solve

Attempt to export a page with a page title: Daily / Weekly / Monthly
Results in: ".\Daily" folder containing "Weekly" folder and then this folder is empty.

# Environment (if applicable)
Version 5.8.5 with OneNote 16.0.16626.20170
Windows 64 bit, OneNote 32 bit.

# Additional Context

Add any other context about the problem here. Attach page XML file or the app log file as appropriate. You can find the log file here: %localappdata%\temp\OneMore.log

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by jasonjac2** [comment]
Doh - it works if you select "Replace Special Characters"!
... but shouldn't it alway make the filename legal by default?

**Comment by stevencohn** [comment]
Agreed. Will clean filename of invalid characters by default, replacing them with underscores.
Additionally, changed the "_Replace special characters in filename..._" option to be "_Replace spaces in filename..._"
