### ISSUE TITLE
Multiple footnotes in a paragraph are not renumbered in sequence

### ISSUE THREAD

**Issue by lronkitty** [stevencohn/OneMore#1118]
# Problem to Solve

If there are multiple references in one row, the number of references will be wrong.

# To Reproduce

First, I add two references in one row like this:
![Untitled](https://github.com/stevencohn/OneMore/assets/55337516/ab3cd662-edab-40ce-8b9d-55f65ef6e976)
Then, I add a new references in anywhere ( in the same row or in another row) will gets some wrong. The number of new reference will be [2] in the screen short, while it should be [3], and the linked reference is also [2].
![image](https://github.com/stevencohn/OneMore/assets/55337516/ae19581c-09d6-47a2-8845-9a92b8f89602)
![image](https://github.com/stevencohn/OneMore/assets/55337516/f89f35f6-03e2-4c41-9e87-597f9a186811)
It's seem like no matter how many references in a raw, the new reference will count the references as one when it's generated.
![image](https://github.com/stevencohn/OneMore/assets/55337516/2d85d441-1855-447f-9690-473512adaac3)

# Environment (if applicable)

 - OneNote Version: [e.g. both Office 2016 and 2019, 64bit.]
 - OneMore Version [e.g. 5.9]

# Additional Context

Add any other context about the problem here. Attach page XML file or the app log file as appropriate. You can find the log file here: %localappdata%\temp\OneMore.log

Log like this:

01| Starting dllhost 11236, 2301 Mhz, 32 MB, en-US/en-US, v5.9.0, OneNote 15.0, Office 16.0, 2023-09-12 11:33
01| ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.16731.20170)
01| ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
01| ..OneAddInsUpdate(custom[])
01| ..building ribbon
01| ..building ribbon colorizer commands
01| ..building ribbon language proofing commands
01| ..building context menu
01| ..OnStartupComplete(custom[])
01| ..starting command service
01| ..starting reminder service
01| ..starting navigation service
01| ..ready
03| defined 46 hotkeys for input locale 1033
14| Running command AddFootnoteCommand
03| Running command AddFootnoteCommand
13| Running command AddFootnoteCommand
04| Running command AddFootnoteCommand
04| Running command AddFootnoteCommand
14| Running command RemoveFootnoteCommand
03| Running command AddFootnoteCommand
17| Running command AddFootnoteCommand
13| Running command AddFootnoteCommand
09| Running command AddFootnoteCommand
15| Running command AddFootnoteCommand
03| Running command AddFootnoteCommand
15| Running command AboutCommand

**Comment by lronkitty** [comment]
Hi, is there any chance that we can fix it?

**Comment by lronkitty** [comment]
@stevencohn Hi, is there any chance that we can fix it?

**Comment by stevencohn** [comment]
I investigate for next release

**Comment by lronkitty** [comment]
Thanks a lot
