### ISSUE TITLE
Documentation suggestion - Quick Access Toolbar

### ISSUE THREAD

**Issue by JRPX33** [stevencohn/OneMore#1119]
# Problem to Solve

Show users a way to make OneMore even more amazing with the Quick Access Toolbar.

# New Feature/Solution

I'd suggest putting in the documentation, or even in the main screenshots area an example of putting OneMore into the Quick Access Toolbar.   I've never really used that functionality, but I stumbled upon doing it with OneMore and it has dramatically sped up  my use of onenote and onemore.

In my example, I put the PowerShell formatting and the SQL Server FOrmatting and the Picture reduce buttons.  I end up using one of these at least once per hour during the work day.

I found putting them directly in the ribbon to take up too much screen real estate, but the QAT was perfect.    I found the optimal way to do this to move them.

## Alternative Solutions

Provide a clear and concise description of any alternative solutions or features you've considered.

# Additional Context

This is an article I wrote for our internal staff on how to do the customization.  Feel free to grab as much (or little) of this as is helpful.

I've found that if you put OneMore commands directly in the OneNote Quick Access Toolbar (QAT), they make OneNote even better!   I first tried putting them in the Ribbon directly, but they are so large they take up too much real estate, so the QAT is the way to go.

Having them one click away is really handy.
![image](https://github.com/stevencohn/OneMore/assets/123988676/d829d11d-3fb4-4d98-bb9f-1f7e7b907c7e)

I found the process of getting them there a bit confusing and after some trial and error here's the process I came up with. 

First, find the commands you want in the OneNote Ribbon icon.  

We'll need to know their exact name because they don't show up in the QAT list under the hierarchy, but all as individual commands.  I'm going to use "PowerShell" and "Resize and Adjust"
![image](https://github.com/stevencohn/OneMore/assets/123988676/ddf12907-af3b-44f5-8a85-a831a4f2df2e)
![image](https://github.com/stevencohn/OneMore/assets/123988676/c273728d-7b6e-46fd-96d6-585f2cd74d69)

Now, Go to work on the QAT.

First, set the QAT to be below the ribbon.  Otherwise you lose the colors and they're further away.
![image](https://github.com/stevencohn/OneMore/assets/123988676/920bed24-58ae-4dd2-995a-fdd2dc6a5fef)
Then go to more commands…
![image](https://github.com/stevencohn/OneMore/assets/123988676/e5a7791f-ffe2-4713-9bd2-680ded79e4ff)
Pick the "Home" tab to limit the number of items in the list.
![image](https://github.com/stevencohn/OneMore/assets/123988676/8f00603d-375e-4e8d-9af2-07c1134565de)
Then scroll down to our first one, PowerShell  and Add that.
![image](https://github.com/stevencohn/OneMore/assets/123988676/08274148-a083-489b-a0a5-fe50fa57578e)
Then scroll down to "Resize and Adjust" and add that one.
![image](https://github.com/stevencohn/OneMore/assets/123988676/4a13c2f2-84ae-4919-b415-b34949aaad11)
Finally, let's add the Images menu.   Note this looks like it will let you drill down and add submenu items, but it doesn't.  It's going to add the whole menu.
![image](https://github.com/stevencohn/OneMore/assets/123988676/847d0f9c-9d52-46f1-acdc-0be6fdf1b221)

And Voila!   We have our QAT!
![image](https://github.com/stevencohn/OneMore/assets/123988676/04eac21b-4229-41ff-93ed-0cccc5f71c65)
Now an ugly pasted powershell script is one click away from looking like this:
![image](https://github.com/stevencohn/OneMore/assets/123988676/68c3f296-cef9-40e9-a966-9d4a03203464)
To This!
![image](https://github.com/stevencohn/OneMore/assets/123988676/c457e645-c054-4ec4-a437-5a907b37d108)
and we've got the whole images menu as a dropdown right here if we need it.

![image](https://github.com/stevencohn/OneMore/assets/123988676/21664cf9-8210-4955-8bd9-c88f8ad570be)

Enjoy!

**Comment by stevencohn** [comment]
Thanks!

https://onemoreaddin.com/the-basics/OneNote%20QAT.htm
