### ISSUE TITLE
Merge outline elements in a page

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#112]
**Is your feature request related to a problem? Please describe.**
After merging multiple pages in one page the resulting page has each merged page in its outline

**Describe the solution you'd like**
I would like OneMore to extract a list of outline elements in the current page and provide the user with the option to select which outlines to be merged in one big outline

**Describe alternatives you've considered**
this can't be done otherwise than manually 

**Additional context**
as indicated this is a feature that would complement the Merge pages feature

**Comment by stevencohn** [comment]
Merging containers when all pages each contain exactly one container. Otherwise, containers are collected and added to the target page as originally designed. See issue #111
