### ISSUE TITLE
Installing on enterprise machine without admin access

### ISSUE THREAD

**Issue by manojknaikade** [stevencohn/OneMore#1124]
Hi Steven,

Our admin tried to install the addin on my company laptop but for some reason it does not show up in onenote. 
When I open onenote as admin user the addin is visible.
I also tried to install using command line as admin user but did not work as well.

What do you think would be the correct method to install the addin in this situation.
Thanks a lot in advance :-)

Cheers
Manoj

**Comment by stevencohn** [comment]
You can forward this info to your admin, maybe it will help.

The installer uses the %ProgramFiles%\River\OneMore\OneMoreSetupActions.exe program to do most of its work. It runs these commands:

1. OneMoreSetupActions.exe --install-x86
2. OneMoreSetupActions.exe --install-registrywow
3. OneMoreSetupActions.exe --install-activesetup

The last step (--install-avctivesetup) create an "Active Setup" registry key here

`HKLM:\\Software\Microsoft\Active Setup\Installed Components\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}`

<img width="455" alt="image" src="https://github.com/stevencohn/OneMore/assets/9964757/8afe1376-5a83-446e-846e-7fdc081a3531">

Make sure that key exists after the install. If not, check the log file at %temp%\OneMoreSetup.log

Or, you can run that step manual (as admin)

`%ProgramFiles%\River\OneMore\OneMoreSetupActions.exe --install-activesetup`

Then, when a non-admin user logs in, it will automatically complete the setup for that user. It takes about 20-30 seconds and is a one-time step. Then OneMore should appear on the OneNote Home tab.

**Comment by manojknaikade** [comment]
Thanks for the quick reply Steven 😊 I will convey this to our admin. Hopefully it works 🤞🏼✌🏼On 22 Sep 2023, at 14:59, Steven ***@***.***> wrote:﻿
You can forward this info to your admin, maybe it will help.
The installer uses the %ProgramFiles%\River\OneMore\OneMoreSetupActions.exe program to do most of its work. It runs these commands:

OneMoreSetupActions.exe --install-x86
OneMoreSetupActions.exe --install-registrywow
OneMoreSetupActions.exe --install-activesetup

The last step (--install-avctivesetup) create an "Active Setup" registry key here
HKLM:\\Software\Microsoft\Active Setup\Installed Components\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}

Make sure that key exists after the install. If not, check the log file at %temp%\OneMoreSetup.log
Or, you can run that step manual (as admin)
%ProgramFiles%\River\OneMore\OneMoreSetupActions.exe --install-activesetup
Then, when a non-admin user logs in, it will automatically complete the setup for that user. It takes about 20-30 seconds and is a one-time step. Then OneMore should appear on the OneNote Home tab.
