### ISSUE TITLE
What unit are the width and height values in?

### ISSUE THREAD

**Issue by gexgd0419** [stevencohn/OneMore#1131]
I thought those are just pixels, but that does not seem to be the case.

Using the OneNote's built-in feature to set an image to its original size, I found that the width and height values are smaller than the size in pixels.

For example, a 64x64px image becomes 48x48, a 500x375px image becomes 375x281.25, a 400x184px image becomes 300x138.

**Comment by stevencohn** [comment]
It is pixels but then that is adjusted by both OneNote and Windows to account for high-def screens, resolution, pixel density, scaling, aspect ratio, etc. 

For example, I normally run my Windows desktop at max resolution but 150% scaling. So a 100x100 image will actually be drawn across a boundary of 150x150 pixels, which you'll notice if you try a screen clipping with something like Greenshot.

And this is why the OneMore Resize Image dialog shows both View size and Image size. The Image size is the actual size in pixels of the raw image data. The View size is the dimensions used to currently display the image on the page

<img width="251" alt="image" src="https://github.com/stevencohn/OneMore/assets/9964757/5c15fffa-c791-4341-84d4-0f79e9043a8b">

**Comment by gexgd0419** [comment]
View sizes are stored in notebooks, so I think that they should be fixed and independent of resolution and scaling.

Yes, a 100x100px image will be 150x150 physical pixels at 150% scaling. But if the view size is the displayed size, it should be 150x150, larger than the image size, 100x100. However, when I use the built-in feature to set the image to its original size, its view size will always be smaller than the image size. (View size 48x48 vs Image size 64x64 at "original size")

Changing my display's scaling ratio doesn't affect that.
