### ISSUE TITLE
Can only build if located at C:\GitHub\OneMore

### ISSUE THREAD

**Issue by winterstew** [stevencohn/OneMore#1132]
# Problem to Solve

Following Setup instructions for building from source fails

# To Reproduce

Starting from scratch with Visual Studio, I followed your instructions ( https://onemoreaddin.com/developers/Setup.htm ) as closely as I could and found a couple issues:

# What I did to resolve
 1) I had to download a CLI nuget.exe (I put it in C:\Windows\) so build.ps1 could find it.
2) I had to clone into C:\GitHub\OneMore in order to build

  If I tried to work from "C:\Users\my user name\Documents\GitHut\OneMore" I got a "Could not resolve this reference. Could not locate the assembly 'Windows'" error.  I expect the problem is due to a relative reference to the assembly (as described here https://stackoverflow.com/questions/50828235/referencing-windows-sdk-winmd-files-and-vs-team-services-build ) or the spaces in my user name.

**Comment by stevencohn** [comment]
I updated and pushed a new version of update-sdk.ps1. Resync your local repo and run it again to set paths in the csproj.

**Comment by winterstew** [comment]
Running .\update-sdk.ps1 gived me:

    Method invocation failed because [System.IO.Path] does not contain a method named 'Exists'.
    At C:\GitHub\OneMore\update-sdk.ps1:98 char:21
    + ...         if (($matches[2] -ne $sdkver) -or ![System.IO.Path]::Exists($ ...
    +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
        + FullyQualifiedErrorId : MethodNotFound

**Comment by stevencohn** [comment]
I'm not sure I understand why you might be seeing that. Could you add this statement just prior to that `if` statement?

`write-host "matches2=[$($matches[2])] sdkver=[$sdkver], p=[$p]"`

and post it here.

**Comment by winterstew** [comment]
OK, well here is the result:
  
```
PS C:\GitHub\OneMore> .\update-sdk.ps1

Updating Windows SDK 10.0.22621.0 (C:\Program Files (x86)\Windows Kits\10\)

OK NET Framework path is already correct
matches2=[10.0.22621.0] sdkver=[10.0.22621.0], p=[..\..\..\Program Files (x86)\Windows 
Kits\10\UnionMetadata\\10.0.22621.0\\Windows.winmd]
Method invocation failed because [System.IO.Path] does not contain a method named 'Exists'.
At C:\GitHub\OneMore\update-sdk.ps1:99 char:21
+ ...         if (($matches[2] -ne $sdkver) -or ![System.IO.Path]::Exists($ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound  

OK no changes required
PS C:\GitHub\OneMore> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22621.1778
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.1778
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
As another interesting observation:
```
PS C:\GitHub\OneMore> [System.IO.Path]::Exists( "." )
Method invocation failed because [System.IO.Path] does not contain a method named 'Exists'.
At line:1 char:1
+ [System.IO.Path]::Exists( "." )
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

PS C:\GitHub\OneMore> [System.IO.Directory]::Exists( "." )
True
```

**Comment by stevencohn** [comment]
Got it. Path.Exists was introduced in a later version of PowerShell/.NET. 

I'll switch to Directory.Exists like you suggest.
