### ISSUE TITLE
Search within selected Notebooks

### ISSUE THREAD

**Issue by JRPX33** [stevencohn/OneMore#1134]
OneNote is my second brain, so I have my whole life in there… Home, Work, Tech Notes, Programming snippets, etc. The fantastic search is one of the main things I like about OneNote, but after so many years of using it, my search results are increasingly stuffed with pages that aren't relevant.

Currently OneNote can search by Page, Section, Section Group, one notebook, or All notebooks. However, I know most of the time when searching that many if not most of my notebooks that are open don't have the answer I'm looking for, but I'm not sure of the specifci one that does.   So it would be incredibly helpful if I was able to search for a **subset** of notebooks, excluding my home ones or my work ones,  for example.   Or searching both my technical notes and one particular client's notebook.   Ideally, I'd be able to create groupings of notebooks so I could search across all my personal notebooks, or across only work notebooks, or even across all microsoft related notebooks.    And then if I didn't find what I wanted, I could add in my QuickNotes notebooks to the search criteria which tend to have misc content that I haven't filed yet.

Some of this idea might be covered with the expanded use of tags (I'm still digesting your ideas there and will comment soon) but I thought I'd present this as a related alternative.  For me this might be easier, particular when dealing with older notes that weren't tagged yet.  If tags were the main way of finding things, I think I'd have to go through and add tags to thousands of pages to accomplish what I was describing above.

Thanks for considering this!

**Comment by stevencohn** [comment]
I think this at least overlaps with my hashtags concept. I'm not intending on fully replacing the search capabilities. It has been asked for in the past but the goals right now it to rethink how we categorize and find information rather than just random search terms. But scoping to a subset of notebooks is certainly possible for the hashtag feature.

**Comment by jasonjac2** [comment]
Refining searches without making it cumbersome is the holy grail.  I, like you, have everything in oneNote and am wrestling with the overhead of organising so finding things is easy. 
I would vote for this, but also to be more ambitious: Notebook(s); page title; page body; NOT in page title; filter on  last modified; filter on page created.

**Comment by stevencohn** [comment]
Supercede by #1646
