### ISSUE TITLE
Button on quicknote screen to add Full OneNote Menus.

### ISSUE THREAD

**Issue by JRPX33** [stevencohn/OneMore#1135]
I make extensive use of OneNote's quicknote function.  It's incredibly handy to be in the middle of something else, and double click in the task bar on the OneNote icon and have it open up a new OneNote page for me to start pasting and typing into.

However, this presents the note with no toolbars.  Yes, it will pull down if you hover over the menu bar, but it doesn't include all menus (it's missing OneMore, for example!).  The only way to get the full menus from here is to click the "normal View" button in the upper right.  But this then expands OneNote to fill the whole screen.   I then have to double-click on the OneNote top menu bar to get it to go back to a normal sized window.

On my laptop this isn't so bad, but at work I have a widescreen monitor and the note becomes HUGE and takes a bit of mouse work to get there.

I find myself going through this cycle of clicking normal and double-clicking the task bar about  once per hour it seems.   I'm not sure if it's possible to customize what's shown on the quicknote, but I thought I'd ask....

Workarounds I've considered are:
1) Writing an AutoHotKey script to map a keyboard shortcut to these two actions
2) Writing an AutoHotKey script that would map a double click in the task bar directly to a new onenote page with the full menubar there to start with.

Thanks for considering!

**Comment by stevencohn** [comment]
There is no way to automate this programmatically. Your AutoHotKey solution may be the most practical honestly.
