### ISSUE TITLE
Option: Fading popup showing shortcut key when you use a OneMore command or hove hint

### ISSUE THREAD

**Issue by jasonjac2** [stevencohn/OneMore#1138]
# Problem to Solve
This is a nice rather than a must.,
Learning shortcut keys  rather than using the mouse.

Hover hint or fading popup would really help.

# New Feature/Solution

I love the way in the command palette that you can see the currently assigned shortcut key.
Generally in office, on the ribbon, if you hover over a ribbon command, you get the shortcut key.
This isn't the case for OM commands from the ribbon or right click menu items.
So: either add the shortcut to the tooltip hover hint OR have an option, as you invoke the command from the ribbon / menu item, show a hint for a second that shows the shortcut key.

Have an option to switch it off / on.

## Alternative Solutions
Use the command palette or everything and learn them that way.

**Comment by stevencohn** [comment]
OneNote has a problem where it cannot always reload the ribbon once initially loaded. This means that if you change shortcut key mappings, the hover info might be wrong. This is why OneMore doesn't include the shortcut keys on hover.

The Command Palette rebuilds its dropdown every time you open the palette; this is why it can show shortcut keys without uncertainty.

**Comment by jasonjac2** [comment]
Yes, I thought your hints on menuitems and ribbons may be limited.  What about the fading popup when you invoke the command?  A bit like the "copied" one for copy link to page.  I think having these kind of tasnparent popup bubbles (with the option to turn them off if they annoy you) is a great way to go.
