### ISSUE TITLE
Forked OneMore

### ISSUE THREAD

**Issue by winterstew** [stevencohn/OneMore#1139]
# How can I help you?

I am loving OneMore for the capabilities it adds.  I mentioned in my feature request from 4 days ago, that I use OneNote as preparation for running role playing games.  When I am preparing a game from published content I frequently copy and paste text from PDF documents.  Each line always get annoyingly pasted as a separate paragraph in OneNote.  

To remedy this, I used your very helpful guide for adding new commands to OneMore.  I created a [MergeParagraphCommand](https://github.com/winterstew/OneMore/blob/main/OneMore/Commands/Clean/MergeParagraphCommand.cs) to do this.  If you are interested, please take it and incorporate it; I have forked it here https://github.com/winterstew/OneMore.  If not, I understand, I am not professionally trained so my code can be a bit mungey.  

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
Nice! But OneMore already has this feature - OneMore/Edit/Join Paragraph [as described here](https://onemoreaddin.com/commands/Edit%20Commands.htm). Enjoy!

**Comment by winterstew** [comment]
That is hilarious.  I can believe I missed that.
