### ISSUE TITLE
show the XML code for a selected text

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#114]
**Is your feature request related to a problem? Please describe.**
I was trying to see how a picture is stored in OneNote and it took me a while to figure out it stored in the cloud and an element ID was used. I was looking for binary data

**Describe the solution you'd like**
t would be nice if the user who is looking for this info could select the element and click on **Show the xml code** which will just show the code for a selected element

This could be easily implemented since the XML already has that info, all that is needed is to strip out the unselected part

**Comment by stevencohn** [comment]
You can simple search for selected="all"

**Comment by 1001QAdotNET** [comment]
yes but I still see all the things that I am not interested in surrounding those elements

**Comment by stevencohn** [comment]
Maybe I could add an option to the XML Dialog to only show selected elements. But I'm not going to add another command to the OneMore menus to do this. 

Still, this is low priority

**Comment by 1001QAdotNET** [comment]
yes that is good enough, I was actually thinking about the same

**Comment by stevencohn** [comment]
https://github.com/stevencohn/OneMore/releases/tag/3.10.3

Highlights in yellow all elements (lines) that contain selected="all" attribute
Colors gray all edited-by attributes

**Comment by 1001QAdotNET** [comment]
Hopefully I will be able to see and test this when I can install 3.10.3

**Comment by 1001QAdotNET** [comment]
yes this one looks good, I will continue to use it, no news here will be good news

**Comment by 1001QAdotNET** [comment]
This seem to have a bug when the selected text is XML escaped. It should select everything down to `</one:T>`
See the below picture and you an use the sample that I used to for the XML colorizer to test and reproduce the below

![image](https://user-images.githubusercontent.com/17384308/102426026-8e702000-3fdc-11eb-979f-f3940dee8f5b.png)

**Comment by stevencohn** [comment]
It's working as designed. It highlights lines that contain selected=all  

That's all.

**Comment by stevencohn** [comment]
The graphic binhex encoded data can be shown in the xml viewer by changing the scope to All or Binary. 

You can decide the binhex to get a Bitmap image

**Comment by stevencohn** [comment]
The graphic binhex encoded data can be shown in the xml viewer by changing the scope to All or Binary. 

You can decide the binhex to get a Bitmap image

**Comment by 1001QAdotNET** [comment]
got it,  I thought it would select the text as well. not a problem them
