### ISSUE TITLE
Application of Code Box Reverts Text Font 

### ISSUE THREAD

**Issue by PaulJamesTaylor** [stevencohn/OneMore#1142]
# Problem to Solve

When I create a new page with a template that has a non standard font, change the font of some text, and then apply a code box the text with the changed font will revert back to the original font of the page template.

# To Reproduce

1) Create a page using a template with a non standard font of 14
2) Write a line of text on the page (should be font 14)
3) Write another line of text and change the font to 11
4) Paste some code into the page
5) Create a text box around the code
   a) highlight code
   b) use keyboard combo ctrl+shift+p
   c) type in "code box"
   d) hit enter
6) Verify that the second line of text has had its font changed from 11 back to 14

# Expected Behavior

Applying a code box should not change the font of text outside of the code box

# Screenshots

N/A

# Environment (if applicable)

 - OneNote Version:  O365, 64bit
 - OneMore Version 5.9

# Additional Context

N/A

**Comment by stevencohn** [comment]
Unable to repro

<img width="311" alt="image" src="https://github.com/stevencohn/OneMore/assets/9964757/56a8841a-4cde-4f59-a93d-d1ba4759afe5">

**Comment by stevencohn** [comment]
Closing due to no response.

The box commands have recently been updated as of v6.2.1 so _might_ have been improved. We need a repeatable pattern in order to address this concern.

**Comment by BeeboTaylor** [comment]
@stevencohn thanks, I'll test in the new version.
