### ISSUE TITLE
Add copy function and place it in the first level menu

### ISSUE THREAD

**Issue by jiahe224** [stevencohn/OneMore#1143]
# Problem to Solve

When using OneNote's copy function, text will turn into pictures after pasting.

**Comment by jasonjac2** [comment]
Hi @jiahe224 
Pasting where?
When you copy various formats registered with the clipboard. It is the responsibility of the "paste" app to decide which formats to support.

**Comment by jasonjac2** [comment]
Sorry, I think I may  have got this wrong.  You want to "copy as image"?

**Comment by stevencohn** [comment]
Like Jason, I think I'm also unsure what your question means exactly.

OneNote has a number of options in its Paste menu

<img width="148" alt="image" src="https://github.com/stevencohn/OneMore/assets/9964757/ad1e7fcb-a4fa-43f7-b624-ee0dd0e519a4">

The last one shown here is the Paste as Image option.

So if you are saying that when you paste text, it magically gets transformed into an image then I'm guessing that you're pasting as image, either inadvertently or indirectly (maybe a strange key mapping?)

Or, if you are saying that you want to paste text as an image then that's exactly what that last paste option provides.

So there's nothing OneMore can do here. Either way, it's a built-in OneNote capability.

**Comment by jiahe224** [comment]
> Sorry, I think I may have got this wrong. You want to "copy as image"?

No. When I copy the text in OneNote and paste it into WeChat, it turns into a picture. The gem does not have this problem.

![动画3](https://github.com/stevencohn/OneMore/assets/35186992/f05643d8-3e8f-426b-8750-f8b6c022f67c)

**Comment by stevencohn** [comment]
Is this is a problem report or a feature request?

It looks like you're using the native built-in Copy command from OneNote. When you copy text in OneNote, it pushes an HTML format, a Unicode format, and a Plain Text format of that text on the Clipboard. When you paste into another app, that app gets to chose which format it wants to paste from those available on the Clipboard.

Are you asking for a Copy as Plaintext command in OneNote?

**Comment by jasonjac2** [comment]
@stevencohn I have witnessed this before, are you sure that ON doesn't register an image format as well?
I am not sure I can reproduce it, but I have had to "wash" the clipboard through notepad++ to get the text.

I agree this is outside the scope of OneMore, more support :-). 
Regards,
JAC

**Comment by stevencohn** [comment]
@jiahe224 Sorry I guess I didn't even notice the title of this ticket! It is indeed a feature request. Thanks.

**Comment by jiahe224** [comment]
> Copy as Plaintext

yes, Copy as Plaintext. 
(I'm very sorry, my English is not good yet, so I rely on Google Translate.)

**Comment by stevencohn** [comment]
Add _Copy as Text_ command to the OneMore Edit menu. This can be added to the context menu through OneMore settings.
