### ISSUE TITLE
Enhancement Request To Configure Container Width

### ISSUE THREAD

**Issue by PaulJamesTaylor** [stevencohn/OneMore#1144]
# Problem to Solve

When creating a page using the default template the container width defaults to 540 points (a point being 1/72 of an inch).  You can see this defined in the XML data as (see the XML element "one:Size width"):

  <one:Outline selected="partial">
     ...
    <one:Size width="540.0" height="26.85543441772461" />
    ...
  </one:Outline>

I, like many people, like to do preliminary long form writing for research in Onenote and would like the format of that writing to match Microsoft Word where it will eventually get exported.  In order to match MS Word the width of the container would need to be 468 points.  This number is determined by the following formula:

- a page is 8.5" wide
- margins on the page are 1"
- (8.5 - 1 - 1) * 72 = 6.5 * 72 = 468

However, for pages with research notes, I like to use a template with a width of 600, 650, and 700 points depending on whether the content has outlines, screen captures, tables, etc.  

The problem is there there is no easy way to precisely set the container width.  There are many postings on the web and the tip most often given is the following:  add some dashes, manually size the container by adjusting the right margin using the mouse so that the dashes fit on a single line, and then deleting the dashes and saving the page as a template.  I don't actually use containers, but the principle is the same for pages without containers .  

I found a macro in Onetastic that can do this easily, it sets the $PageOutline.width to the manually entered value and it definitely solves the problem.  However, this is one of the few features in Onetastic that I find that is useful and it is a little ubsurd to maintain an annual subscription for a simple feature like that.  

# New Feature/Solution

This request is to implement a function to set the container width of a page to a value input by the user.

## Alternative Solutions

- Manual adjustment by dragging the right margin with the mouse.
- Onetastic has a macro that does this

# Additional Context

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
Hi. Thanks for the request. OneMore does already have this capability. See the [Arrange Containers](https://onemoreaddin.com/commands/Page%20Commands.htm) command. If using the first option, it will set the width of the containers on the page to the specified width. Enjoy!

**Comment by PaulJamesTaylor** [comment]
Steven, I confirmed this fulfills my request, thanks for the tip.  I'll close it out.
