### ISSUE TITLE
Click on an image to show full size......

### ISSUE THREAD

**Issue by jasonjac2** [stevencohn/OneMore#1148]
# Problem to Solve
We have a lot of screenshots in our on pages.  They can really disrupt the flow of a page becuase to be able to see details it needs to be 1:1, but at 1:1 it takes up so much of the page that you lose sight of where you are / do far too much page up and down.  Alternative is resize it, then you you have to resize it to show the level of dewtail you need.

Provide a clear and concise description of the problem, e.g. I'm always frustrated when...

# New Feature/Solution
Click on image and hotkey to display it in a non modal resizable window.

Provide a clear and concise description of what you want to happen.

## Alternative Solutions

Provide a clear and concise description of any alternative solutions or features you've considered.

# Additional Context

Provide any other context or screenshots about the feature request here.

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by sbennett18** [comment]
Would love something like this.
The best I've come up with in native OneNote is to create a subpage "Collateral" that includes a table with all of the full size images.
Then on the main page I create a small image and link to the full size image on my Collateral page. Then you can just hit Back to go back to the main page.
But it's pretty cumbersome and not storage efficient to have two copies of each screenshot.
This kind of modal approach or something else would be awesome!

**Comment by jasonjac2** [comment]
My plan B approach (rather than hotkey) would be to be able to assign a "oneMore:" link to it, so that when you click it, OneMore is invoked, gets the image, and does the same. just a different way of invoking.

Just to be clear - I would prefer it to be a non-modal form that pops up, so I can leave that floating while I continue to interact with ON.

**Comment by jasonjac2** [comment]
My plan B approach (rather than hotkey) would be to be able to assign a "oneMore:" link to it, so that when you click it, OneMore is invoked, gets the image, and does the same. just a different way of invoking.

Just to be clear - I would prefer it to be a non-modal form that pops up, so I can leave that floating while I continue to interact with ON.

**Comment by stevencohn** [comment]
There are a couple of OneMore alternatives that I just want to point out...

1. Open Image With...
2. Crop and Rotate
3. Edit and Adjust

All of these can show the image in its full native size. I understand that each has its own limitations and none of them are particularly lightweight. But they're there.

**Comment by jasonjac2** [comment]
Yep, open image with is a bit of a winner I guess.
I use paint.net, but I could add my own viewer.  What cleans up the temp file generated?

I might write a light weight viewer that reads the navigation.json to give it a caption and a link, keeps tabs for ones you have opened and allows you to click to get back to them.  Also single key to close or go back to source.

**Comment by sbennett18** [comment]
@jasonjac2 Do you use [PowerToys](https://github.com/microsoft/PowerToys) by chance? I wonder if you could get the Open Image With to launch [Peek](https://github.com/microsoft/PowerToys#peek)?

**Comment by jasonjac2** [comment]
@sbennett18 I like the idea of it, but can't see how to invoke it.  I tried: 

"C:\Program Files\PowerToys\WinUI3Apps\PowerToys.Peek.UI.exe" "c:\3\untitled.png"
and nothing happened.

**Comment by stevencohn** [comment]
This discussion seems to be resolved by available alternatives. Closing for now.
