### ISSUE TITLE
Apply a Code syntax highlighter  to a selected text

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#115]
**Is your feature request related to a problem? Please describe.**
Code syntax highlighter 

**Describe the solution you'd like**
I would like to be able to select code and apply synthax highlighting to it (replace the black and white formatting with whatever the synthax highlighter returns)
**Describe alternatives you've considered**
Currently using VSCode and copy with formatting or this https://pygments.org/demo/
**Additional context**
Some times the highlighting is lost when copied to OneNote
This could be an easy win or might be difficult you know better. It seems that Python has this option, I expect C/C++ to have similar libraries

Sorry for the flurry of requests, I am working with OneNote and ..that is what is happening :-) ideas pop up like mushrooms after rain

**Comment by 1001QAdotNET** [comment]
PS: I am still working on a couple of things (unittesting) but soon I will be able to start developing plugins for OneMore using the feature you implemented, so I might attempt to deal with these by myself. I will still run them through you as making them native will be better and faster. If you will not have cycles or interest I will do it at my end

**Comment by stevencohn** [comment]
I've been working on this for a week or so already! It's non-trivial but present some challenges that I want to work through. These are the kind of things I like adding to OneMore - adds usefulness (especially if it helps me specifically) and challenges me. Although I admit, sometimes the quick wins are good too ;-)

**Comment by 1001QAdotNET** [comment]
I am glad I hit the nail with this one :-)

**Comment by 1001QAdotNET** [comment]
As I am ramping up my coding activity I will probably come up with requests more in line with this sort of features
