### ISSUE TITLE
Can add a function to set Chinese and English fonts separately. Sincerely thanks

### ISSUE THREAD

**Issue by styuanqn2022** [stevencohn/OneMore#1152]
# New Feature/Solution

After OneNote switches between Chinese and English input methods, the English font will not automatically change to Times New Roman. Can you add a function to "set Chinese and English fonts separately", Song Dynasty and Times New Roman.

**Comment by stevencohn** [comment]
I think you're asking me if I can change the default font OneNote uses when you select different languages. Unfortunately, it cannot be changed at run-time programmatically.

I can change the default font for the current user. But you'd then still need to restart OneNote.
