### ISSUE TITLE
Simplify and Unify the Goto Favorite Menu

### ISSUE THREAD

**Issue by julie777** [stevencohn/OneMore#1156]
# Problem to Solve

Favorites works differently when initiated from the Ribbon Icon and From the keyboard shortcut.
In addition, the Favorites button on the ribbon conflates "go to favorite" with other favorite related items.

Assumption: the majority of the time, (certainly more than 90%) when the user selects the favorites menu in the ribbon or opens the favorites search dialog with `<alt>f` they want to go to a favorite page.

Based on that assumption, there should be a dedicated and optimal way to go to a favorite page. All other actions associated with favorites should be accessed in a different manner.

# New Feature/Solution

Many applications that I use have the notion of a combo-box drop down menu with a text box at the top of the items to filter the selection. This allows both keyboard only operation and mouse use with a single UI element. At the moment I cannot think of exactly what I mean, but `<ctrl>b` in firefox provides a complicated example. 

I would like both clicking on the "go to favorite" button in the ribbon and the keyboard shortcut to open the current menu, but modified by showing a text box at the top and removing all non-favorites from the menu. 
- the first item in the list is selected when the menu opens
- `<enter>` will goes to the selected item
- The arrow keys move the selection
- typing always goes into the text box and filters the list. 
    - This also resets the selection to the first item in the list as the list is filtered.
- at any time clicking on an item in the menu goes to that page.

**Comment by jasonjac2** [comment]
Hi  - When you say "current menu" do you mean the dropdown from the ribbon OR the current dialogue box?

I think that you can have one source of data (the favourites) but have 2 completely different access methods and each will suit certain users.  The ribbon is suitable when there are a few items and that may suit some users. For me I want to have lots of favourites and ultimately I would like extra functionality in the fav dialogue that just wouldn't work with the ribbon - e.g.
- editing favourites with your own "description"
- Reordering
- copy as link
- Select all, copy as links
- ....
All these can happen on a rich dialogue, but not in a ribbon.  
Anyway, just my 2c.

**Comment by stevencohn** [comment]
This discussion seems to have a reasonable conclusion. Closing for now.
