### ISSUE TITLE
When is the "Update" button available in the Show XML dialog?

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#116]
Hi Steven

Could you add an option for plain questions (currently we either post a bug or a feature request)?
And now the question: what does the user have to do in the Show XML screen to get the Update button activated, that does not seem to work no matter what I do there

**Comment by stevencohn** [comment]
The dialog hides editedByAttributes: object id, last modified dttm, etc., by default to make it easier to see the content.

Untick the "Hide edited-by-attributes" checkbox.... yeah, the one that says "uncheck to edit page" :-)

**Comment by 1001QAdotNET** [comment]
I thought I checked everything in that dialog :-) thank you, sorry for consuming your cycles
