### ISSUE TITLE
OneNote Inserts MindManager File

### ISSUE THREAD

**Issue by liuyuqiangchn** [stevencohn/OneMore#1166]
Hi, I've been using MindManager to create mind maps for a long time, and one of the biggest problems that has been bothering me for a long time is how to insert mind maps into OneNote!

In OneNote, it's easy to insert an excel file, when the excel file is opened in external excel, click save in excel, the excel image will be updated along with it.
![ONENOTE_zzYdYXEbyo](https://github.com/stevencohn/OneMore/assets/22015183/b8f48b59-cbd3-4f51-a644-e6c8c3c938e0)

Please, can you realize, insert MindManager file in OneNote, when this file is opened with MindManager, click save, the picture will also update with it.
![ONENOTE_zV2ZQF0P4A](https://github.com/stevencohn/OneMore/assets/22015183/42bff474-69d9-4b20-9b69-05fc490729e8)

Finally, thank you for creating this plugin, it helps me a lot!

**Comment by stevencohn** [comment]
Sorry this is not possible with Microsoft current implementation of the OneNote API used by OneMore.

**Comment by jasonjac2** [comment]
.... but you could expand the planUML type set up to use local / remote / public Mermaid...... @liuyuqiangchn are you fixed on MindManager?

**Comment by stevencohn** [comment]
I didn't know about Mermaid. I'll look into it

**Comment by stevencohn** [comment]
PlantUML can create mindmaps too https://docs-as-co.de/news/mind-maps/

**Comment by liuyuqiangchn** [comment]
Thank you very much for your answers, I usually use software to create mind maps because mine are more complex, and now I see that it's not very easy to create mind maps in OneNote
