### ISSUE TITLE
Feature to preserve original image/attatchment filenames when exporting

### ISSUE THREAD

**Issue by maslos** [stevencohn/OneMore#1168]
# Problem to Solve

Hello, can i ask for a feature to preserve original image/attatchment filenames when exporting?
When i do "save as" i can save photo/attachment with original filename but when i export with OneMore it renames all photos to something like "image001".

Thank you in advance

**Comment by maslos** [comment]
So, there is no way for such functionallity? :(

**Comment by stevenmcohn** [comment]
The filename of an image (png, gif, jpg) is entirely lost when you add it to a OneNote page.

The only way I can envision it working is manual. It would be possible to build a command to "name" an image and that could be either presented in a caption or hidden inside the page along with the image and then used to name the exported file. But it would have nothing to do with the original filename and would be a little fragile, e.g. it would be easy to delete the caption, again losing that info. I don't think this is a viable option.

**Comment by stevencohn** [comment]
The filename of an image (png, gif, jpg) is entirely lost when you add it to a OneNote page.

The only way I can envision it working is manual. It would be possible to build a command to "name" an image and that could be either presented in a caption or hidden inside the page along with the image and then used to name the exported file. But it would have nothing to do with the original filename and would be a little fragile, e.g. it would be easy to delete the caption, again losing that info. I don't think this is a viable option.
