### ISSUE TITLE
Make the Run plugin more customizable, add a convenient way to select the path to a scripts library, list the scripts in the selected path

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#117]
**Is your feature request related to a problem? Please describe.**
Make the Run plugin feature more user friendly

**Describe the solution you'd like**
The Run plugin dialog could be improved to allow the selection of the folder containing the arguments (for python or power shell these would be scripts)
After that the folder was selected it can be scanned and a drop down list could allow the user to select a script script (any of the files found in that folder)
Any variation of this idea would greatly help
An option could be to manually register plugins and give the option in that screen to select what plugin (or combintions of plugins and arguments

![image](https://user-images.githubusercontent.com/17384308/101971221-bbe45480-3bfd-11eb-8ef3-21b8e05455bb.png)

**Comment by 1001QAdotNET** [comment]
I think this should have its own ribbon button like Favorites and Custom Styles have in OneMore

**Comment by stevencohn** [comment]
You might be the only user of this. I'm reluctant to promote something intended to be experimental as a main feature of OneMore. 

But you can easily add it to a custom ribbon group yourself.

**Comment by 1001QAdotNET** [comment]
I might end up publishing my plugins (if they are decent enough) and then others could use it
They will need a convenient way to use them as I will do during the developement

If decide to publish them should I create my own or you would be ok to create a folder in your repo and have me use PRs?

**Comment by stevencohn** [comment]
Submit them and I'll take a look.

**Comment by CLITrees** [comment]
Thank you I can now browse for the plugin parameter
Any chance we would be able to registers plugin/parameter pairs and have them predefined somewhere in the OneMore menus like the custom styles or favorite pages?

**Comment by 1001QAdotNET** [comment]
Thank you I can now browse for the plugin parameter
Any chance we would be able to registers plugin/parameter pairs and have them predefined somewhere in the OneMore menus like the custom styles or favorite pages?
