### ISSUE TITLE
Add diff colorization

### ISSUE THREAD

**Issue by koppor** [stevencohn/OneMore#1170]
# Problem to Solve

"Code" highlighting using diff

Example:

```diff
- old line
+ new line
```

# New Feature/Solution

Add "diff" to Colorize"

![image](https://github.com/stevencohn/OneMore/assets/1366654/49417872-b8e7-4a28-be6a-764db79f94e1)

## Alternative Solutions

Manual coloring

**Comment by stevencohn** [comment]
You're talking about Linux `diff -color` or `colordiff` style output? 

Rule such as these?

* Lines starting with `+` or `>` then green
* Lines starting with `-` or `<` then red
* Lines starting with `space` then default
* All other lines then cyan

Something like that?

**Comment by jasonjac2** [comment]
If you could combine that with a syntax highlight, that would be great, e.g. C# with Diff.
I still haven't perfected my Pascal / Delphi one.
