### ISSUE TITLE
Highlighted command in Command Palette shows extra kerning space

### ISSUE THREAD

**Issue by koppor** [stevencohn/OneMore#1172]
# Problem to Solve

Two command names miss a "t"

![image](https://github.com/stevencohn/OneMore/assets/1366654/45d6495c-533b-42f6-b697-103d6b110772)

# To Reproduce

1. Go To **More > Command Palette**
2. Type in "table"

**Comment by stevencohn** [comment]
Removed extra kerning prior to phrase within word

**Comment by stevencohn** [comment]
Removed extra kerning space between substrings of words

<img width="190" alt="image" src="https://github.com/stevencohn/OneMore/assets/9964757/04ab1b5f-b134-4e3c-a86f-a74dba71746f">
