### ISSUE TITLE
Reminder Summary Report

### ISSUE THREAD

**Issue by andycross99** [stevencohn/OneMore#1189]
This report has been working fine but in the last few days it has lost the ability to update some of the new Reminders that have been entered or changed. Is there a command to fix or refresh these links please. Thanks in advance:-)

**Comment by stevencohn** [comment]
Can you please attach the log file. It should be in %TEMP%\OneMore.log

**Comment by andycross99** [comment]
Hi Steven

 

Used search everywhere for this .LOG file  but cannot find it. Did a manual search in WINDOWS /  TEMP  still no Onemore.log file. Do you have any more suggestions what to do ?

 

Best regards

Andy

**Comment by stevencohn** [comment]
%TEMP% is typically defined as C:\Users\your-username\AppData\Local\Temp, e.g. C:\Users\steven\AppData\Local\Temp

The Reminder Report page is also entirely coincidental. Unless you've manually customized the page, you can delete it and recreate it as a new report page.

But I would be interested to see if there are any errors in your log file, if you can find it :-)

**Comment by andycross99** [comment]
Hi Steven 

 

It was in a hidden folder. I have deleted and renewed the report but I still get the same errors.

 

Best Regards

Andy

**Comment by andycross99** [comment]
Did you not get the LOG file attachments?

**Comment by andycross99** [comment]
I think I have found the problem. 

 

After I reinstalled the application I noticed that some of the right click context menus had gone but not all. I went in and removed everything to do with the reminder menus, restarted it enabled them again, restarted and now it all appears to work. 😊

**Comment by stevencohn** [comment]
Good to know. I'm not sure why yet but I'll take a look

**Comment by andycross99** [comment]
Hi Steven

 

I spoke too soon same problem as before!

**Comment by stevencohn** [comment]
Best guess is what I noted above, that OneNote isn't great when you update the same content from multiple computers, even if you're logging in using the Microsoft Office account; object on a page will have one set of IDs on one machine but those same objects will different IDs on another machine.

The workaround here is to hyperlink a reminder to its target page if it first can't find a hyperlink to the specific paragraph. Not perfect, but workable.
