### ISSUE TITLE
Add a "Disable Spellcheck" (or "Keep Proofing Language") Option to Custom Styles

### ISSUE THREAD

**Issue by Ziflin** [stevencohn/OneMore#1191]
# Problem to Solve

I've been using Onetastic for years solely to have one custom style for "inline code" (`such as this text`) and another for HTML-pasted "code" snippets and both _disable_ spell checking. To get this to work I simply need to have it apply the "Proofing Language" with the styles and have the language set to Latin/etc. similar to how OneMore's custom colorizer does it (https://github.com/stevencohn/OneMore/issues/216). 

# New Feature/Solution

Ideally there would be a new option in the Custom Style "Options" section to "Disable Spellchecking" as that is the actual intent. Then OneMore could set the Proofing Language when applying the style similar to how it does with the colorizer.

**Comment by stevencohn** [comment]
Colorizing a paragraph (line ended with a hard return) will disable spell check by setting the proofing language to Yoruba for the paragraph (with my sincere apologies to the Yorubians!)

However, it doesn't do that for inline colorizing. I can do that though! Thanks for the suggestion.

**Comment by stevencohn** [comment]
Just a clarification... OneMore does disable spell checking when you use the Colorize command for inline code, by selecting a run of text within a paragraph and then using the Colorize/lang command.

Styles are just that and have no association with coding languages. So I think your title is correct, asking for a disable spellcheck option for a style (end of sentence!) But considering you get the same functionality by using the Colorize command, do you still need this option on custom styles?

**Comment by Ziflin** [comment]
Awesome! Thanks for adding it! Look forward to the next release.

**Comment by stevencohn** [comment]
While implemented for the next release, there is a newly discovered OneNote defect, as described by [this tech note question](https://learn.microsoft.com/en-us/answers/questions/1455780/onenote-interop-api-updatepagecontent-breaks-spell).

**Comment by Ziflin** [comment]
I'm not sure if it's at all related to that OneNote bug, but I did notice that selecting a word than has been turned into a hyperlink (to a website URL), and then clicking the OneMore button to "Disable spell checking with selected content" will apply the proofing language to the *entire* page instead of just the selection. (If the hyperlink is created after disabling spell check, it works fine.)  I can create a new issue for that if need be.

**Comment by stevencohn** [comment]
No you're right. This is a OneMore bug, not OneNote.

It is due to the fact that OneMore can't tell the difference between a selected text range within a hyperlink and simply placing the text cursor over a hyperlink; even without selecting one or more characters, OneNote indicates that the entire hyperlink is selected. So OneMore has logic to handle this exception, however, the bug you mention above can be fixed and I will do that against this ticket. No need for a new one.
