### ISSUE TITLE
Style "Spacing" not working

### ISSUE THREAD

**Issue by nhwCoder** [stevencohn/OneMore#1197]
# Problem to Solve

When changing for a style like "Normal" the Spacing value (e.g. to 40) this is not working using "Apply These Styles to Page".

# To Reproduce

1. Click on "My Styles"
2. Click on "Edit Styles"
3. Select Style Name "Normal"
4. Change Spacing (e.g. 40)
5. Click OK

6. Click on "My Styles"
7. Click on "Apply These Styles to Page"

# Expected Behavior

Spacing for normal text should be changed, but doesn't change.

# Environment (if applicable)

 - OneNote Version: 16.0.16924.20150
 - OneMore Version 5.9.0

Thanks for any feedback/solution

**Comment by stevencohn** [comment]
I think it's a problem with the dialog not saving the settings. Can you please try this:

Edit the style, change the Spacing, and Tab out of that field before clicking OK.
Then try to apply the styles. Does that work?

**Comment by stevencohn** [comment]
Is this _space before_ or _space after_? 

When you chose _space before_, this will not affect the very first line at the top of an Outline container.

**Comment by nhwCoder** [comment]
Thanks for the fix! Appreciate it.
