### ISSUE TITLE
OneMore absent in Home Ribbon - any thing to make it appear?

### ISSUE THREAD

**Issue by onlytanmoy** [stevencohn/OneMore#1201]
Hi, I installed the latest version (OneMore_5.9.0_Setupx64) in my Win 11 64 bit machine running OneNote 32bit.
It installed all fine but I don't find the OneMore in the ribbon.
When I go to File - Options - Add-ins > I can see it as active
![image](https://github.com/stevencohn/OneMore/assets/48493659/4742432f-c292-478b-bcb6-479227587493)
Tried uninstalling and re-installing same issue, let me know the solution please.

**Comment by stevencohn** [comment]
Following with #1218
