### ISSUE TITLE
Unicode Support

### ISSUE THREAD

**Issue by panhaoyu** [stevencohn/OneMore#1203]
# Problem to Solve

Nearly all the inputs can only insert ascii characters.
However, in many cases, unicode input in required.
By copy-paste, the input areas can have unicode value. But directly typing from input method is not available.

# To Reproduce

1. Go to any page.
2. Press "Ctrl + H"
3. Input unicode values directly from input method.
4. Unable to input.

# Expected Behavior

Can input  unicode value.

# Screenshots

![image](https://github.com/stevencohn/OneMore/assets/23495987/c507f128-89c8-4936-8495-eaa186089ab7)

# Environment (if applicable)

 - OneNote Version: O365 64bit
 - OneMore Version： 5.9.0

![image](https://github.com/stevencohn/OneMore/assets/23495987/02a460c0-2517-4f9b-9d3e-e9e51a62339c)

**Comment by stevencohn** [comment]
Are you talking about entering Unicode characters by using the Alt-X-code method, like you would use in the CMD console? This method does not work in any of the Office applications [as noted in this article](https://support.microsoft.com/en-us/office/insert-ascii-or-unicode-latin-based-symbols-and-characters-d13f58d3-7bcb-44a7-a4d5-972ee12e50e0#:~:text=To%20insert%20a%20Unicode%20character%2C%20type%20the%20character,codes%2C%20see%20Unicode%20character%20code%20charts%20by%20script.).

But I can emulate typing Unicode using the on screen keyboard after changing the input language to Simplified Chinese:

<img width="291" alt="image" src="https://github.com/stevencohn/OneMore/assets/9964757/d162b7a3-f66b-4066-a279-c0799a9fb945">

**Comment by panhaoyu** [comment]
Okay thanks for your reply, I think its an uncompatibility between my input method and the program. I'll test it more carefully and update the bug here later.
