### ISSUE TITLE
Outline formatting - Every usage/run adds an empty space after every style (Heading1, etc.)

### ISSUE THREAD

**Issue by nhwCoder** [stevencohn/OneMore#1204]
# Problem to Solve

Outline formatting - Every usage/run adds an empty space after the text-string of every style (Heading1, etc.)

# To Reproduce

1. Create a page with styles
H1
H2
H3
H2
H3
3. Click on 'More\Numbering\Outline formatting'
5. See error
Every usage/run adds an empty space after the text-string of every style (Heading1, etc.)
Problem: If you run this several times on the page, you have many empty spaces after every style  (Heading1, etc.)

# Expected Behavior

No added spaces after every style (Heading1, etc.).

# Environment (if applicable)

 - OneNote Version: 5.9.0 64bit
 - OneMore Version 16.0.17029.20068

# Additional Context

Like OneMore!
Thanks in advance for any solution.

**Comment by nhwCoder** [comment]
Thanks for the fix! Great.

**Comment by jasonjac2** [comment]
@nhwCoder  are you building and installing a custom build?

**Comment by nhwCoder** [comment]
No, I use your default installer releases.
