### ISSUE TITLE
Change number formatting in OneNote Storage Analysis

### ISSUE THREAD

**Issue by JRPX33** [stevencohn/OneMore#1206]
# Problem to Solve

The OneNote Storage Analysis report is a fantastic tool.  However, when I'm skimming through it to try to find the portions that are unusually large and need cleaning up, It's really hard to find the big ones since the units are jumping back and forth between KB, MB and GB.  I can understand why some folks would want it this way, but for me, it makes it much harder to read.

# New Feature/Solution

Would be great to have an option in the report to use consistent units... so for example, just do everything in GB or MB.  Ideally rounded to two decimal places would be fine for my purposes.

**Comment by stevencohn** [comment]
<img width="485" alt="image" src="https://github.com/stevencohn/OneMore/assets/9964757/2b7654d6-eac5-4578-9448-c572efac74dc">
