### ISSUE TITLE
Display Template Name That Page Was Created From

### ISSUE THREAD

**Issue by PaulJamesTaylor** [stevencohn/OneMore#1213]
# Problem to Solve

I would like the ability to know what template was used to create a page.

# New Feature/Solution

I would like to be able to enter a command in the command palette that would trigger a pop-up displaying which template was used to create a page.

## Alternative Solutions

Maybe display it on the "show XML" page?

# Additional Context

I use this feature in Onetastic.  I don't know of any other way of displaying the template that the page was built from.  I don't use it frequently, I would put this at very low priority, but it would be nice to have when I disable Onetastic.

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
This will appear in the Show XML dialog when viewing the page. Look at the top line containing the one:Page element and scan over to find the stationaryName attribute. That should tell you the name of the template.

Is that sufficient?

**Comment by PaulJamesTaylor** [comment]
Yes, this is very sufficient for my requirements.  Thanks for the tip.  I did actually search this file but missed it as I was searching the substring "template".
