### ISSUE TITLE
Searching for Tags doesn't newly tagged pages.

### ISSUE THREAD

**Issue by KingKoolK37** [stevencohn/OneMore#1219]
# Problem to Solve

When using onemore's tagging system, newly added tags do show up on the page and in the tagging menu. But when searching for this tag with the ”find tagged pages” function only old pages with this tag show up.

# To Reproduce

1. Tag a page using ”tag page” function with eg 'test_tag'
2. Click on ”add tag”
3. Click on ”ok” to close the ”tag page” window
4. Open ”Find Tagged Pages” function and enter the tag eg 'test_tag'
5. Click on search

# Expected Behavior

This should return all the pages tagged with this tag.

# Screenshots

# Environment (if applicable)

 - OneNote Version: OneNote 16.0.17029.20068
 - OneMore Version Version 6.0.0

# Additional Context

Add any other context about the problem here. Attach page XML file or the app log file as appropriate. You can find the log file here: %localappdata%\temp\OneMore.log

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
This is not a bug. It's scheduled to scan every 2 minutes, adjustable in Settings down to every 1 minute. The Find Hashtag dialog box also has an option on the 3-dot menu to force a scan on demand.

**Comment by KingKoolK37** [comment]
Hi Steven,

thanks for the swift reply. Note that I am not talking about the new Hashtag feature. This is about the old ”Tag Page” and ”Find Tagged Pages” features. The newly added tags have been added days before I tried finding them using ”Find Tagged Pages”.
![image](https://github.com/stevencohn/OneMore/assets/70904626/dde758a8-cfa6-4547-8640-3cd30e1d4bcd)

**Comment by stevencohn** [comment]
Ah OK. So you have a page with two tags, _type_book_ and _test_. And you can't find the _test_ tag? Just to be sure, did you add the _test_ tag using the Tag Page command? It will not work if you type a new tag directly on the page in that upper container. Hopefully that sounds like a silly question but I have to ask.

**Comment by KingKoolK37** [comment]
Thanks for getting back to me.

Yes, I added both the _test_ and the _type_book_ tag using "Tag Page" command. Also note that not only can't the _test_ tag not be found at all, but also the page cannot be found when looking for the _type_book_ tag

**Comment by stevencohn** [comment]
Page tags are now deprecated as of v6.2.1. That version helps you upgrade your page tags to hashtags and then disables the page tag commands. Those commands will be removed in a later release of OneMore.
