### ISSUE TITLE
Add the option to save and restore the OneNote/OneMore settings

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#122]
**Is your feature request related to a problem? Please describe.**
Due to bugs sometimes we need to remove the addon completely
This removes the settings as awee
**Describe the solution you'd like**
Would it be easy and possible to add the option to export import settings 

**Describe alternatives you've considered**
N/A

**Comment by stevencohn** [comment]
Which settings are you talking about? The OneMore settings are stored in a location unknown to the installer and that means the settings are actually never removed (which could be viewed as a bug unto itself).

If you're talking about the quick access toolbar, unfortunately I have no control over that.

**Comment by 1001QAdotNET** [comment]
any settings that can be exported and imported back
Is there any way for onemore to determine what is in the quick access bar and save that and restore it if needed ?

**Comment by stevencohn** [comment]
Unfortunately no. OneMore has control over its own Settings dialog, the last-used values in some of the dialogs such as the Plugin dialog, and that's about it. It doesn't have any way to find out what's in the Quick Access toolbar or any other OneNote options.

And as a I said, the installers leave the OneMore settings even after you uninstall it. So they should be rediscovered automatically the next time it's installed. Note that the About dialog Update function actually does a full uninstall and reinstall and the OneMore settings aren't lost during that (never seen them lost myself)

**Comment by 1001QAdotNET** [comment]
OK I was hoping for a quick way to bring back my quick access bar settings
