### ISSUE TITLE
Failed to upgrade to OneMore_6.0.0_Setupx64.msi

### ISSUE THREAD

**Issue by gpbicego** [stevencohn/OneMore#1222]
# Problem to Solve
The setup stops with error:
"There is a problem with Windows Installer package. A program required for this install to complete could not be run."

# Environment (if applicable)
 - Version 5.9.0 with OneNote 16.0.17029.20068

# MSI log when the error dialog appears
...
Property(N): PrimaryVolumeSpaceAvailable = 0
Property(N): PrimaryVolumeSpaceRequired = 0
Property(N): PrimaryVolumeSpaceRemaining = 0
Property(N): INSTALLLEVEL = 1
MSI (s) (80:B0) [12:06:04:557]: Note: 1: 2262 2: Error 3: -2147287038 
MSI (s) (80:B0) [12:06:04:557]: Note: 1: 2262 2: Error 3: -2147287038 
Action ended 12:06:04: RemoveExistingProducts. Return value 1.
MSI (s) (80:B0) [12:06:04:557]: Doing action: InstallFinalize
Action 12:06:04: InstallFinalize. 
Action start 12:06:04: InstallFinalize.
MSI (s) (80:B0) [12:06:04:557]: Note: 1: 2265 2:  3: -2147287035 
MSI (s) (80:B0) [12:06:04:557]: User policy value 'DisableRollback' is 0
MSI (s) (80:B0) [12:06:04:557]: Machine policy value 'DisableRollback' is 0
MSI (s) (80:B0) [12:06:04:572]: Note: 1: 2265 2:  3: -2147287035 
Action 12:06:04: RollbackCleanup. Removing backup files
MSI (s) (80:10) [12:06:04:572]: System Environment : Client has accepted UAC prompt
MSI (s) (80:B0) [12:06:04:588]: Note: 1: 1721 2: _9BC3F1AB_73D3_473D_9D75_142C6B2A856B 3: C:\Program Files\River\OneMoreAddIn\OneMoreSetupActions.exe 4: --install-registrywow 
MSI (s) (80:B0) [12:06:04:588]: Note: 1: 2262 2: Error 3: -2147287038 
MSI (c) (34:B0) [12:06:04:588]: Note: 1: 2262 2: Error 3: -2147287038 
DEBUG: Error 2835:  The control ErrorIcon was not found on dialog ErrorDialog
The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2835. The arguments are: ErrorIcon, ErrorDialog, 

Thank you very much

**Comment by MikeJPelton** [comment]
Yip, me too - 
![image](https://github.com/stevencohn/OneMore/assets/139790238/b4bf3403-5a06-44ad-86ef-cd05012f533f)

**Comment by kpatzwald** [comment]
Same for me. I tried it direct out of OneNote and with the update-package from the website.

**Comment by jasonjac2** [comment]
... but once it installs OK, i.e. it appears back in the ribbon?  I had the same when I was running the installer for the 2nd time, because the update (1st time) installed and then OneMore was removed from the ribbon and from add-ins.

**Comment by ludwig-loth** [comment]
For me aswell. I can't install it. I tried a complete fresh install and it won't work.

**OneNote: ** Version 2311 Build 16.0.17029.20028 64 Bit 
**Windows: **  Windows 11 Pro 23H2 22631.2861

**Comment by stevencohn** [comment]
I'm able to reproduce this but admit I don't understand why it's failing yet since nothing has changed around that area. 

Anyway, until this is fixed, you can uninstall from "Apps and Features"/Win10 or "Installed Apps"/Win11 and then download and run the 6.0 installer separately and that should work.

**Comment by stevencohn** [comment]
The way the installed is supposed to work - and always has! - is that, on an upgrade, it uninstalls the old version, removing all files, then adds the new files and runs a couple of custom actions. But just before those custom actions run, the new files are deleted! If there are any installer gurus out there that could help, I'll buy you a virtual beer.

**Comment by gpbicego** [comment]
> I'm able to reproduce this but admit I don't understand why it's failing yet since nothing has changed around that area.
> 
> Anyway, until this is fixed, you can uninstall from "Apps and Features"/Win10 or "Installed Apps"/Win11 and then download and run the 6.0 installer separately and that should work.

I tried this, but I had to restart Windows before the installation was successful (I run the program in compatibility mode for Previous version of Windows https://github.com/stevencohn/OneMore/issues/941#issuecomment-1655352871)

**Comment by maphew** [comment]
For me uninstalling first from control panel does not work. I haven't tried rebooting yet. There is a log file in `AppData\Local\Temp` and another in `C:\Windows\SystemTemp`. I had to take ownership of the 2nd in order to look at it,

Here's the Appdata log. It was initially longer but I cleared it before last attempt. I thought I'd saved the content but alas, it's gone:
```
======================================================================
starting action: --install .. 2023-12-18 12:40:36 PM
Installer architecture (x64), OS architecture (x64), requesting (x64)
OneMore installer running as user NT AUTHORITY\SYSTEM (S-1-5-18) elevated
on behalf of MYDOM\system

Register... version 6.0.0

ShutdownOneNoteAction.Install ---
dllhost process not found
stopping process ONENOTE, pid 27412
install failed; error registering
System.ComponentModel.Win32Exception
Message: Access is denied
Source: System
StackTrace:    at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.Kill()
   at OneMoreSetupActions.ShutdownOneNoteAction.StopOneNote()
   at OneMoreSetupActions.ShutdownOneNoteAction.Install()
   at OneMoreSetupActions.Program.Install()
TargetSite: [System] System.Diagnostics.ProcessManager::OpenProcess()
```

The system log file does not contain entries for today's upgrade and install attempts. Here's the entry for the previous version (I've obfuscated the active directory domain):
```
======================================================================
starting action: --install .. 2023-09-11 2:28:08 PM
Installer architecture (x64), OS architecture (x64), requesting (x64)
OneMore installer running as user NT AUTHORITY\SYSTEM (S-1-5-18) elevated
on behalf of MYDOM\system

Register... version 5.9.0

ShutdownOneNoteAction.Install ---
dllhost process not found
ONENOTE process not found

ProtocolHandlerAction.Install ---
step 0: opening HKLM:\Software\Classes\onemore
step 1: setting properties of HKLM:\Software\Classes\onemore
step 2: opening HKLM:\Software\Classes\onemore\shell\open\command
step 3: setting properties of HKLM:\Software\Classes\onemore\shell\open\command
verified: key created HKEY_LOCAL_MACHINE\Software\Classes\onemore\shell\open\command

TrustedProtocolAction.Install ---
translating user MYDOM\system to SID
MYDOM\system identity not mapped, falling back
fallback to search username in HKEY_USERS
defaulting Office version to 16
step 4: opening HKCU:\Software\Policies\Microsoft\Office\16.0\Common\Security\Trusted Protocols\All Applications\onemore:
install failed; error registering
System.ArgumentNullException
Message: Value cannot be null.
Parameter name: name
Source: mscorlib
StackTrace:    at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at Microsoft.Win32.RegistryKey.ValidateKeyName(String name)
   at Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   at OneMoreSetupActions.TrustedProtocolAction.Install()
   at OneMoreSetupActions.Program.Install()
TargetSite: [mscorlib] System.ThrowHelper::ThrowArgumentNullException()
```

**Comment by stevencohn** [comment]
> StackOverflow tells us "That error message indicates a failing custom action" - I'm sure you've found it too Steven but just in case [this is the link](https://stackoverflow.com/questions/57657674/there-is-a-problem-with-this-windows-installer-package-a-program-required-for-t).

@MikeJPelton Top answer here is the likely culprit. I attempted to clean up the installer by excluding unused components. I fixed it by reverting back to an older vdproj file and slowly bringing it back up to current. There are plenty of warnings during the build, but they're just warnings.

**Comment by MikeJPelton** [comment]
Hope you're sitting down @stevencohn - 6.0.1 on top of 6.0.0 fails too, the same way. Haven't tried reinstalling etc. We realise you probably have a day job and I for one love OneMore so pls enjoy the holidays, this can wait!

**Comment by stevencohn** [comment]
Yeah, I'm not going to fix that. In fact, not even sure it's possible. 

Uninstall 6.0. Install 6.0.1. Sorry I do have a day job :-)
