### ISSUE TITLE
Integrate with VSCode to automatically extract notes and todo items into OneMore Tasks

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#1223]
Leverage one of the well known VSCode extensions to extract ToDo notes from VSCode projects and aggregate them/Integrate them in the OneMore Todo/Tasks list.

Use case: I need to import my task list in OneNote where I keep my To Do list.
I also need a central place to store project notes and OneNote is just good for this but I want to be able to point to vscode:// URLs

**Comment by 1001QAdotNET** [comment]
The TODO tree extension would be my favorite, there is already an option to export the todo notes as a text containing an ASCII tree properly indented. What is needed here is to go over a folder and extract and centralize all the TODOs either exported or not from all the workspace subfolders in that folder

**Comment by stevencohn** [comment]
This would be a VSCode plugin project, not a OneMore project I believe.
