### ISSUE TITLE
Image pasted into an empty OneNote container is not found by OneMore

### ISSUE THREAD

**Issue by gpbicego** [stevencohn/OneMore#1225]
# Problem to Solve
If the OneNote container contains only the image, it is not resizable. 
OneMore version 5.9.0 was OK.
# Environment (if applicable)
 - OneMore Version 6.0.1 with OneNote 16.0.17029.20068
# To Reproduce
Paste an image into a new container, select it and from the popup menu choose "Resize and Adjust".
![image](https://github.com/stevencohn/OneMore/assets/22318088/6181d809-d32f-46b0-bdc1-f763e979d724)

**Comment by stevencohn** [comment]
Are you sure it's in a container? By default, a new page doesn't have a container until you start typing text. Pasting an image doesn't automatically create a container; it will become a background image instead.

If you type even just a space and then paste the image then the image will be inside a container and can be resized.

**Comment by gpbicego** [comment]
Ok, it's not a container, I was wrong. 
With the previous version of OneMore, I used to paste the image into a blank area, then resize it, cut it, and paste it into a table (to avoid table resizing).
Not a problem, I can insert a letter before pasting the image.
Thanks again for your great work.
