### ISSUE TITLE
##Hashtags a) Size of search results dropdown has to small width b) Coloring Hashtags

### ISSUE THREAD

**Issue by nhwCoder** [stevencohn/OneMore#1227]
# Feature request

a) (##Hashtags) Search result width
Size of search results dropdown has to small width (see attached image).

b) (##Hashtags) Coloring Hashtags
An OPTIONAL feature to color hashtags during scanning would be great, I do so with my tags to be able to see them in large text (see attached image),

# Environment (if applicable)
 OneMore Version: 6.0.1 64bit
 OneNote Version: Microsoft 365 MSO (Version 2311 Build 16.0.17029.20028) 64 Bit

![111 image](https://github.com/stevencohn/OneMore/assets/125078667/2a4a5e25-3f50-4159-92f1-31d2f774350c)

**Comment by stevencohn** [comment]
a) Yes
b) Not reasonably feasible

**Comment by nhwCoder** [comment]
a) Thanks for the improvement

b) Not reasonably feasible
If you already parse the ##Hashtags for indexing it would be the same matching-algorithm and you have the "text literal" to color already in a variable, 
So it is not totaly new code (but yes, another menu entry  'Color hashtags" with a color-picker to choose color or none in needed).

**Comment by stevencohn** [comment]
So I thought you were talking about a temporary and dynamic coloring like the built-in Search does, and then removes the highlighting once you're done with the Search. But you're talking about a more permanent "go and change the background highlighting of hashtags" and leave that highlighting forever. Which would imply a "go and unhighlight" command as well. Is that correct?

**Comment by nhwCoder** [comment]
#### Permanent
Yes, to change the text-color permanent.

#### Text-color vs. background-color
I think to set the text color is better (compared to background color).
Like in screenshot with number (2), so that you can see your defined ##hashtags in color immediately.

#### UI options
1. ~~MAYBE even one control called "Color hashtags" with a color picker in the current UI would be sufficient to change all ##hashtag colors.~~
1. ~~Or put it in the "..." menu (top right-side).~~
1. Or a new menu entry "Color hashtags" with a color-picker to choose one color or no color (none).

#### Scope
Since you have all ##hashtags in SqlLite I would propose to always change all ##hashtags if someone changes the color.
~~Maybe with the choice for page/section/notebook/all notebooks~~

#### Keyboard shortcut
Very important would be a keyboard shortcut.
- Use case: User adds a new ##hashtag and then presses the keyboard shortcut to have the ##hashtags colored.
- Tricky: Maybe to have one keyboard shortcut for "page" (faster and sufficient in this case) and one for "all notebooks".

COMMENT: 
##hashtags are a big advantage for Knowledge Management to find information faster.
Colored tags in the page help a lot to understand which parts have been tagged and for what reason.

Thanks for adding the ##hashtag feature!

**Comment by stevencohn** [comment]
@nhwCoder Would you mind please copying the above message to a new feature request? :-)
