### ISSUE TITLE
##Hashtags: Add keyboard shortcut to open "Search Hashtags" window

### ISSUE THREAD

**Issue by nhwCoder** [stevencohn/OneMore#1229]
# New Feature/Solution

##Hashtags: Add keyboard shortcut to open "Search Hashtags" window.

# Additional Context

Thanks in advance

**Comment by stevencohn** [comment]
Alt+F9

**Comment by nhwCoder** [comment]
Great it already exists.
Can you add this shotcut to the ScreenTip (see attached image).

![111_image](https://github.com/stevencohn/OneMore/assets/125078667/cf385f90-2cb7-4ebc-aa57-895456bf2e9b)

**Comment by stevencohn** [comment]
No. Keyboard shortcuts are purposely not added to the tooltips on menu items, at least at this time.

Note that you can modify the shortcut from the OneMore settings if you want to remap it to something else.

**Comment by nhwCoder** [comment]
I propose the "ScreenTip" and not the text.
This is also used for other menu entries like the avove "Search and Copy/Move" (see attached screenshot).

Would be very great if this can be displayed dynamically (even if the shortcute was changed).

![2 0 Test - Image](https://github.com/stevencohn/OneMore/assets/125078667/584c0662-ab95-4258-a960-8dc9285b1367)

**Comment by stevencohn** [comment]
No. There are three commands that have hard-coded tooltips which is a defect. If you override the mapping for these commands, that override will not be reflected in the tooltip.
