### ISSUE TITLE
##Hashtags Feature to open first hashtag match in "Find Hashtags" window

### ISSUE THREAD

**Issue by nhwCoder** [stevencohn/OneMore#1230]
# New Feature/Solution

##Hashtags Feature to open first hashtag match in "Find Hashtags" window.
Is is very time consuming to click first the match, then again on "Search" button (= maybe keybord shortcut for this button is a good idea also) if we know that there is only one possible match.

Proposal: Support shortcut for dropdown (see attached image)
* [Ctrl+Click]
* [Ctrl+Enter]
=> Open automatically page with first match.

## Screenshots
![111_image](https://github.com/stevencohn/OneMore/assets/125078667/81674d06-0108-4a18-8e9a-057d1a0c445c)

**Comment by stevencohn** [comment]
Something similar is planned.

**Comment by nhwCoder** [comment]
Sounds good :-)

**Comment by stevencohn** [comment]
### Enhancements
Single hash hashtags must not begin with a number. #a123 is valid but #1abc is not. This is to ensure OneMore differentiates between a hashtag and a numbered sequence like #1, #2, #3, etc. If you want a tag such as #123 then use two number signs, such as ##123.

If you are a programmer and tend to have HTML Hex colors, like #FFCC00, or have C# or C++ pragma directives, like `#include` or `#define`, then you'll want to exclude these patterns by checking the _Exclude_ box in Settings.

When search for hashtags using the Search Hashtags dialog, all pages that containing that hashtag will be displayed. The date shows the last date the page was updated. Hover over each contextual snippet to see when that paragraph was last updated. Click the page to navigate to the top of the page. Click a contextual snippet to navigate directly to that paragraph.

As you start typing a hashtag, a list of known tags is displayed. You can enter a partial hashtag or select a tag from the list. Tags can be combined with AND or OR logical operators; AND is implicit if not specified. Double ampersand, &&, is equivalent to AND, while double vertical bar, ||, is equivalent to OR. Precedence can be specified using parentheses. Use an asterisk as a wildcard; to search for abc and not abcdef, terminate the tag with a period such as abc. Some valid query expressions include:

* tag
* tag tag2
   * This is equivalent to `tag AND tag2`
* tag (#tag2 or tag3)
   * This is equivalent to `tag AND (#tag2 OR tag3)`
