### ISSUE TITLE
Hashtags - Feature to permanent "Color hashtags"

### ISSUE THREAD

**Issue by nhwCoder** [stevencohn/OneMore#1236]
###  New Feature/Solution

Propose a feature to be able to permanent "Color hashtags".
Colored hashtags in the page would help a lot to see immediately which parts have been tagged and for what reason (see attached screenshot (1) versus (2) ).
![11111111111111](https://github.com/stevencohn/OneMore/assets/125078667/7a31e17b-498f-48b9-b56f-27bf24607f69)

##### Text-color vs. background-color
I think to set the text color is better (compared to background color).
Like in screenshot with number (2), so that you can see your defined ##hashtags in color immediately.

#####  UI options
1. ~~MAYBE even one control called "Color hashtags" with a color picker in the current UI would be sufficient to change all ##hashtag colors.~~
1. ~~Or put it in the "..." menu (top right-side).~~
1. Or a new menu entry "Color hashtags" with a color-picker to choose one color or no color (none).

##### Scope
Since you have all ##hashtags in SqlLite I would propose to always change all ##hashtags if someone changes the color.
~~Maybe with the choice for page/section/notebook/all notebooks~~

#####  Keyboard shortcut
Very important: Adding a keyboard shortcut.

Use case: User adds a new ##hashtag and then presses the keyboard shortcut to have the ##hashtags colored.
Tricky: Maybe to have one keyboard shortcut for "page" (faster and sufficient in this case) and another for "all notebooks".

**Comment by PaulJamesTaylor** [comment]
- Highlight should be to the text and not the background for aesthetic reasons
- Obsidian just auto sets the tag to a default color, this works pretty well I think (user can define that color)
    - user shouldn't be required to set the color after creating the hashtag, it should be automatically colored (optional)

**Comment by stevencohn** [comment]
Added user setting to choose preferred hashtag styling

* None (will not remove styling from stylized hashtags because that may have been done manually)
* Red foregound
* Yellow background
* Or any of your user-defined custom styles of type Character

These styles are applied to _new_ hashtags as they are discovered by the background scanner or the on-demand menu item.
