### ISSUE TITLE
Number of pages in a section

### ISSUE THREAD

**Issue by onlytanmoy** [stevencohn/OneMore#1239]
Hi, merry Xmas wishes :)
I am new to OneMore so might not be familiar if such a feature already exists, so basically is there a way to count the number of pages in a particular section?

**Comment by stevencohn** [comment]
Added page count to File/Analyze Storage

<img width="561" alt="image" src="https://github.com/stevencohn/OneMore/assets/9964757/a21aed9d-0663-439b-be74-54e942ea91df">

**Comment by onlytanmoy** [comment]
> Added page count to File/Analyze Storage. Will be part of next release.

perfect! thanks a lot mate, happy holidays :)
