### ISSUE TITLE
Conflicting shortcuts 'ALT' + 'SHIFT' + ('+' or '-')

### ISSUE THREAD

**Issue by SlyTFox** [stevencohn/OneMore#124]
**Describe the bug**
The shortcut 'ALT' + 'SHIFT' + ('+' or '-') that you have for drawing horizontal lines is conflicting with the ones to expand/collapse text

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (if applicable):**

**Additional context**

**Comment by stevencohn** [comment]
There aren't a lot of key sequences left that make much sense. I'm inclined to just remove my bindings for these two commands so users have to use the menu to insert single and double lines.

**Comment by stevencohn** [comment]
https://github.com/stevencohn/OneMore/releases/tag/3.10.6
