### ISSUE TITLE
OneMore doesn't work after PC restart nor after repairing or reinstalling OneMore. 

### ISSUE THREAD

**Issue by DavideRedivaD** [stevencohn/OneMore#1242]
Hi,
I had been using OneMore for two months now, and it worked well.
Sometimes, the UI of OneMore inside OneNote didn't appear. To fix that, I reinstalled it to update the old files.
Last time, two or three weeks ago, this process didn't work, so I uninstalled it with Bulk Crap Uninstaller, an open-source tool, and reinstalled it from the OneMore website. This changed the installation folder (inside "Programs") from "River3" to "River".
This reinstallation worked well, but since yesterday, the OneMore UI hasn't appeared again. So I've tried to repair it. then to reinstall it, but nothing changed. So I'm not able to fix the problem alone anymore with those tricks.
What can I do? Can you fix it?

# To Reproduce

1. Open OneNote
2. I see OneMore UI didn't load, then I close OneNote
3. I try to repair it by downloading the installation file and running it
4. I hit the repair button
5. When the repair is done, I close the repair window
6. Then I run OneNote again
7. The OneMore UI stil didn't work, so I close it
8. Then I uninstall OneMore
9. After that I reinstall it with the downloaded installation file
10. When the installation is done, I open OneNote again
11. OneMore buttons still don't appear.
12. I uninstall OneMore
13. Then i check if I have other River folders inside my "C:\"
14. I found many folders containing the name "river" inside "C:\Windows\WinSxS\" with many different and long names and different dates

# Expected Behavior

I simply expect that OneMore works.

# Screenshots

![image](https://github.com/stevencohn/OneMore/assets/42168471/7d273d11-a681-492d-9cab-71cc96482efa)
![image](https://github.com/stevencohn/OneMore/assets/42168471/910251c9-f149-4403-ba3c-30a5c6d7d103)
![image](https://github.com/stevencohn/OneMore/assets/42168471/e35880d5-daaf-46d3-8ad3-3b5c99c2b0b8)

Environment (if applicable)

OneNote Version: Microsoft® OneNote® per Microsoft 365 MSO (Versione 2311 Build 16.0.17029.20028) a 64 bit 
OneMore Version: latest downloaded yesterday, the 6 version

# Additional Context

01| Starting dllhost 9404, 2100 Mhz, 32 MB, en-US/en-US, v5.9.0, OneNote 15.0, Office 16.0, 2023-12-11 09:17
01| ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.17029.20068)
03| ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
03| ..OneAddInsUpdate(custom[])
03| ..building ribbon
03| ..building ribbon colorizer commands
03| ..building ribbon language proofing commands
03| ..building ribbon groups
03| ..building context menu
01| ..OnStartupComplete(custom[])
01| ..starting command service
01| ..starting reminder service
01| ..starting navigation service
01| ..ready
10| Running command UpdateCommand
04| ..defined 45 hotkeys for input locale 1040
03| OnBeginShutdown(custom[])
03| ..shutting down UI
03| ..OnDisconnection(RemoveMode:ext_dm_HostShutdown,custom:[])
03| ..disposing 7 streams
03| ..closing log

01| Starting dllhost 13172, 2100 Mhz, 32 MB, en-US/en-US, v5.9.0, OneNote 15.0, Office 16.0, 2023-12-12 11:40
01| ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.17029.20068)
03| ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
03| ..OneAddInsUpdate(custom[])
01| ..building ribbon
01| ..building ribbon colorizer commands
01| ..building ribbon language proofing commands
01| ..building ribbon groups
01| ..building context menu
01| ..OnStartupComplete(custom[])
01| ..starting command service
01| ..starting reminder service
01| ..starting navigation service
01| ..ready
09| Running command UpdateCommand
04| ..defined 45 hotkeys for input locale 1040
18| Running command InsertCellsCommand
15| OnBeginShutdown(custom[])
15| ..shutting down UI
15| ..OnDisconnection(RemoveMode:ext_dm_HostShutdown,custom:[])
15| ..disposing 8 streams
15| ..closing log

01| Starting dllhost 18468, 2100 Mhz, 32 MB, en-US/en-US, v5.9.0, OneNote 15.0, Office 16.0, 2023-12-13 10:39
01| ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.17029.20068)
01| ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
01| ..OneAddInsUpdate(custom[])
01| ..building ribbon
01| ..building ribbon colorizer commands
01| ..building ribbon language proofing commands
01| ..building ribbon groups
01| ..building context menu
01| ..OnStartupComplete(custom[])
01| ..starting command service
01| ..starting reminder service
01| ..starting navigation service
01| ..ready
08| Running command UpdateCommand
03| ..defined 45 hotkeys for input locale 1040
14| OnBeginShutdown(custom[])
14| ..shutting down UI
14| ..OnDisconnection(RemoveMode:ext_dm_HostShutdown,custom:[])
14| ..disposing 2 streams
14| ..closing log

01| Starting dllhost 19304, 2100 Mhz, 32 MB, en-US/en-US, v5.9.0, OneNote 15.0, Office 16.0, 2023-12-15 08:49
01| ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.17029.20068)
01| ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
01| ..OneAddInsUpdate(custom[])
03| ..building ribbon
03| ..building ribbon colorizer commands
03| ..building ribbon language proofing commands
03| ..building ribbon groups
03| ..building context menu
01| ..OnStartupComplete(custom[])
01| ..starting command service
01| ..starting reminder service
01| ..starting navigation service
01| ..ready
05| Running command UpdateCommand
04| ..defined 45 hotkeys for input locale 1040
18| OnBeginShutdown(custom[])
18| ..shutting down UI
18| ..OnDisconnection(RemoveMode:ext_dm_HostShutdown,custom:[])
18| ..disposing 2 streams
18| ..closing log

01| Starting dllhost 1168, 2100 Mhz, 32 MB, en-US/en-US, v5.9.0, OneNote 15.0, Office 16.0, 2023-12-17 22:23
01| ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.17029.20108)
01| ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
01| ..OneAddInsUpdate(custom[])
03| ..building ribbon
03| ..building ribbon colorizer commands
03| ..building ribbon language proofing commands
03| ..building ribbon groups
03| ..building context menu
01| ..OnStartupComplete(custom[])
01| ..starting command service
01| ..starting reminder service
01| ..starting navigation service
01| ..ready
05| Running command UpdateCommand
04| ..defined 45 hotkeys for input locale 1040
18| ..downloading MSI from https://github.com/stevencohn/OneMore/releases/download/6.0.0/OneMore_6.0.0_Setupx64.msi
07| ..creating install script C:\Users\david\AppData\Local\Temp\OneMoreInstaller.cmd
07| ..starting installation process

01| Starting dllhost 6972, 2100 Mhz, 8 MB, it-IT/it-IT, v6.0.1, OneNote 15.0, Office 16.0, 2023-12-21 12:23
01| ..Windows 11 Professional, Version 23H2, Build 22621, 64 bit
01| ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.17029.20108)
03| ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
03| ..OneAddInsUpdate(custom[])
03| ..building ribbon
03| ..building ribbon colorizer commands
03| ..building ribbon language proofing commands
03| ..OnStartupComplete(custom[])
03| ..starting command service
03| ..starting reminder service
03| ..starting navigation service
03| ..starting hashtag service
03| ..ready
04| defined 46 hotkeys for input locale 1040
11| building hashtag database
11| hashtag database done
11| hashtag service scanned 15 pages in 10754ms
04| hashtag service scanned 15 pages in 315ms
05| hashtag service scanned 15 pages in 238ms
05| hashtag service scanned 15 pages in 243ms
05| hashtag service scanned 15 pages in 320ms
11| hashtag service scanned 15 pages in 166ms
11| hashtag service scanned 15 pages in 308ms
11| hashtag service scanned 15 pages in 209ms
05| hashtag service scanned 15 pages in 361ms
05| hashtag service scanned 15 pages in 262ms
11| hashtag service scanned 15 pages in 275ms
11| hashtag service scanned 15 pages in 222ms
11| hashtag service scanned 15 pages in 308ms
05| hashtag service scanned 15 pages in 242ms
05| hashtag service scanned 15 pages in 287ms
11| hashtag service scanned 15 pages in 376ms
11| hashtag service scanned 15 pages in 302ms
04| hashtag service scanned 15 pages in 302ms
05| hashtag service scanned 15 pages in 218ms
11| hashtag service scanned 15 pages in 605ms
05| hashtag service scanned 15 pages in 351ms
05| hashtag service scanned 15 pages in 238ms
05| hashtag service scanned 15 pages in 304ms
05| hashtag service scanned 15 pages in 140ms
11| hashtag service scanned 15 pages in 139ms
04| hashtag service scanned 15 pages in 308ms
11| hashtag service scanned 15 pages in 167ms
04| hashtag service scanned 15 pages in 181ms
04| hashtag service scanned 15 pages in 261ms
11| hashtag service scanned 15 pages in 114ms
05| hashtag service scanned 15 pages in 136ms
04| hashtag service scanned 15 pages in 161ms
11| hashtag service scanned 15 pages in 135ms
11| hashtag service scanned 15 pages in 139ms
05| hashtag service scanned 15 pages in 157ms
05| hashtag service scanned 15 pages in 194ms
04| hashtag service scanned 15 pages in 141ms
04| hashtag service scanned 15 pages in 162ms
11| hashtag service scanned 15 pages in 157ms
11| hashtag service scanned 15 pages in 194ms
04| hashtag service scanned 15 pages in 171ms
05| hashtag service scanned 15 pages in 177ms
03| hashtag service scanned 15 pages in 177ms
04| hashtag service scanned 15 pages in 136ms
03| hashtag service scanned 15 pages in 137ms
11| hashtag service scanned 15 pages in 1222ms
03| hashtag service scanned 15 pages in 570ms
04| hashtag service scanned 15 pages in 171ms
04| hashtag service scanned 15 pages in 2417ms
04| hashtag service scanned 15 pages in 150ms
04| hashtag service scanned 15 pages in 283ms
11| hashtag service scanned 15 pages in 820ms
11| hashtag service scanned 15 pages in 174ms
04| hashtag service scanned 15 pages in 182ms
11| hashtag service scanned 15 pages in 197ms
03| hashtag service scanned 15 pages in 319ms
03| hashtag service scanned 15 pages in 169ms
05| hashtag service scanned 15 pages in 141ms
03| hashtag service scanned 15 pages in 203ms
03| hashtag service scanned 15 pages in 148ms
04| hashtag service scanned 15 pages in 145ms
05| hashtag service scanned 15 pages in 146ms
11| hashtag service scanned 15 pages in 142ms
05| hashtag service scanned 15 pages in 144ms
05| hashtag service scanned 15 pages in 164ms
03| hashtag service scanned 15 pages in 174ms
03| hashtag service scanned 15 pages in 144ms
05| hashtag service scanned 15 pages in 112ms
05| hashtag service scanned 15 pages in 140ms
03| hashtag service scanned 15 pages in 737ms
05| hashtag service scanned 15 pages in 320ms
04| hashtag service scanned 15 pages in 313ms
05| hashtag service scanned 15 pages in 178ms
04| hashtag service scanned 15 pages in 224ms
05| hashtag service scanned 15 pages in 168ms
11| hashtag service scanned 15 pages in 178ms
03| hashtag service scanned 15 pages in 210ms
03| hashtag service scanned 15 pages in 161ms
04| hashtag service scanned 15 pages in 139ms
05| hashtag service scanned 15 pages in 152ms
03| hashtag service scanned 15 pages in 148ms
05| hashtag service scanned 15 pages in 144ms
11| hashtag service scanned 15 pages in 152ms
04| hashtag service scanned 15 pages in 142ms
05| hashtag service scanned 15 pages in 154ms
04| hashtag service scanned 15 pages in 145ms
05| hashtag service scanned 15 pages in 144ms
11| hashtag service scanned 15 pages in 151ms
04| hashtag service scanned 15 pages in 173ms
04| hashtag service scanned 15 pages in 139ms
04| hashtag service scanned 15 pages in 170ms
04| hashtag service scanned 15 pages in 179ms
03| hashtag service scanned 15 pages in 161ms
05| hashtag service scanned 15 pages in 145ms
03| hashtag service scanned 15 pages in 182ms
04| hashtag service scanned 15 pages in 173ms
04| hashtag service scanned 15 pages in 140ms
03| hashtag service scanned 15 pages in 164ms
11| hashtag service scanned 15 pages in 399ms
04| hashtag service scanned 15 pages in 930ms
05| hashtag service scanned 15 pages in 146ms
03| hashtag service scanned 15 pages in 282ms
05| hashtag service scanned 15 pages in 228ms
05| hashtag service scanned 15 pages in 468ms
03| hashtag service scanned 15 pages in 150ms
05| hashtag service scanned 15 pages in 136ms
05| hashtag service scanned 15 pages in 167ms
03| hashtag service scanned 15 pages in 755ms
04| hashtag service scanned 15 pages in 168ms
03| hashtag service scanned 15 pages in 126ms
04| hashtag service scanned 15 pages in 145ms
11| hashtag service scanned 15 pages in 1741ms
03| hashtag service scanned 15 pages in 205ms
03| hashtag service scanned 15 pages in 149ms
05| hashtag service scanned 15 pages in 333ms
04| hashtag service scanned 15 pages in 215ms
04| hashtag service scanned 15 pages in 224ms
04| hashtag service scanned 15 pages in 165ms
04| hashtag service scanned 15 pages in 181ms
03| hashtag service scanned 15 pages in 195ms
11| hashtag service scanned 15 pages in 187ms
05| hashtag service scanned 15 pages in 131ms
03| hashtag service scanned 15 pages in 142ms
04| hashtag service scanned 15 pages in 145ms
04| hashtag service scanned 15 pages in 165ms
05| hashtag service scanned 15 pages in 179ms
03| hashtag service scanned 15 pages in 158ms
04| hashtag service scanned 15 pages in 165ms
05| hashtag service scanned 15 pages in 162ms
05| hashtag service scanned 15 pages in 205ms
05| hashtag service scanned 15 pages in 153ms
05| hashtag service scanned 15 pages in 299ms
03| hashtag service scanned 15 pages in 138ms
05| hashtag service scanned 15 pages in 199ms
05| hashtag service scanned 15 pages in 291ms
04| hashtag service scanned 15 pages in 148ms
03| hashtag service scanned 15 pages in 342ms
03| hashtag service scanned 15 pages in 140ms
04| hashtag service scanned 15 pages in 141ms
04| hashtag service scanned 15 pages in 142ms
07| OnBeginShutdown(custom[])
07| ..shutting down UI
07| ..OnDisconnection(RemoveMode:ext_dm_HostShutdown,custom:[])
07| ..disposing 30 streams
07| ..closing log

01| Starting dllhost 18756, 2100 Mhz, 8 MB, it-IT/it-IT, v6.0.1, OneNote 15.0, Office 16.0, 2023-12-22 10:15
01| ..Windows 11 Professional, Version 23H2, Build 22621, 64 bit
01| ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.17029.20108)
01| ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
01| ..OneAddInsUpdate(custom[])
03| ..building ribbon
03| ..building ribbon colorizer commands
03| ..building ribbon language proofing commands
01| ..OnStartupComplete(custom[])
01| ..starting command service
01| ..starting reminder service
01| ..starting navigation service
01| ..starting hashtag service
01| ..ready
04| defined 46 hotkeys for input locale 1040
11| hashtag service scanned 15 pages in 1941ms
15| hashtag service scanned 15 pages in 187ms
15| hashtag service scanned 15 pages in 145ms
09| hashtag service scanned 15 pages in 178ms
18| hashtag service scanned 8 pages in 182ms
20| hashtag service scanned 10 pages in 168ms
20| hashtag service scanned 12 pages in 208ms
19| hashtag service scanned 12 pages in 208ms
07| hashtag service scanned 12 pages in 242ms
15| hashtag service scanned 10 pages in 838ms
03| hashtag service scanned 10 pages in 1433ms
03| hashtag service scanned 10 pages in 347ms
03| hashtag service scanned 10 pages in 515ms
16| hashtag service scanned 10 pages in 161ms
19| hashtag service scanned 10 pages in 212ms
17| hashtag service scanned 10 pages in 231ms
03| hashtag service scanned 10 pages in 238ms
01| hashtag service scanned 10 pages in 356ms
19| hashtag service scanned 10 pages in 390ms
15| hashtag service scanned 10 pages in 206ms
19| hashtag service scanned 10 pages in 176ms
15| hashtag service scanned 10 pages in 202ms
15| hashtag service scanned 10 pages in 166ms
09| hashtag service scanned 10 pages in 162ms
06| hashtag service scanned 10 pages in 171ms
16| hashtag service scanned 10 pages in 176ms
16| hashtag service scanned 10 pages in 157ms
01| hashtag service scanned 10 pages in 163ms
01| hashtag service scanned 10 pages in 191ms
03| hashtag service scanned 10 pages in 160ms
15| hashtag service scanned 10 pages in 277ms
03| hashtag service scanned 10 pages in 192ms
16| hashtag service scanned 10 pages in 186ms
06| hashtag service scanned 10 pages in 200ms
16| hashtag service scanned 10 pages in 275ms
17| hashtag service scanned 10 pages in 581ms
03| hashtag service scanned 10 pages in 343ms
16| hashtag service scanned 10 pages in 134ms
05| hashtag service scanned 10 pages in 245ms
17| hashtag service scanned 10 pages in 257ms
01| hashtag service scanned 10 pages in 247ms
04| OnBeginShutdown(custom[])
04| ..shutting down UI
04| ..OnDisconnection(RemoveMode:ext_dm_HostShutdown,custom:[])
04| ..closing log

01| Starting dllhost 5492, 2100 Mhz, 8 MB, it-IT/it-IT, v6.0.1, OneNote 15.0, Office 16.0, 2023-12-28 15:28
01| ..Windows 11 Professional, Version 23H2, Build 22621, 64 bit
01| ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.17029.20108)

01| Starting dllhost 17900, 2100 Mhz, 8 MB, it-IT/it-IT, v6.0.1, OneNote 15.0, Office 16.0, 2023-12-28 17:30
01| ..Windows 11 Professional, Version 23H2, Build 22621, 64 bit
01| ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.17029.20108)

01| Starting dllhost 14996, 2100 Mhz, 8 MB, it-IT/it-IT, v6.0.1, OneNote 15.0, Office 16.0, 2023-12-28 17:32
01| ..Windows 11 Professional, Version 23H2, Build 22621, 64 bit
01| ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.17029.20108)

01| Starting dllhost 9764, 2100 Mhz, 8 MB, it-IT/it-IT, v6.0.1, OneNote 15.0, Office 16.0, 2023-12-28 17:44
01| ..Windows 11 Professional, Version 23H2, Build 22621, 64 bit
01| ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.17029.20108)

01| Starting dllhost 8888, 2100 Mhz, 8 MB, it-IT/it-IT, v6.0.1, OneNote 15.0, Office 16.0, 2023-12-28 17:54
01| ..Windows 11 Professional, Version 23H2, Build 22621, 64 bit
01| ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.17029.20108)

**Comment by stevencohn** [comment]
Looks like it was working well until the last 5 runs and then just didn't load. I've been chasing this problem for quite some time with no luck sadly.

If you could, can you please follow these steps. The iq.ps1 script is harmless and only reads and locally reports information from the System Registry; it will not change or delete any data, nor will it report anything remotely. It is [documented here](https://onemoreaddin.com/developers/Scripts.htm)

1. Download the [iq.ps1 script from here](https://github.com/stevencohn/OneMore/blob/main/iq.ps1)
2. Open an administrative PowerShell terminal and `cd` to the download directory
3. Run the iq.ps1 script by typing the command

   ` .iq.ps1`

4. Attach the results here.

It should report all "OK" but if any "BAD" lines show up then that might be really helpful in diagnosing the issue so please attach the results here.

If there are "BAD" lines, then you might also try repairing it with the [setregistry.ps1 script](https://github.com/stevencohn/OneMore/blob/main/setregistry.ps1)

   `.\setregistry.ps1 -reset`

Either way, I'd be interested in the results. I've not been able to get my hands on one of these failing machines so it's been impossible to diagnose.

**Comment by stevencohn** [comment]
No it was my mistake. The command should have a backslash like this:

`.\iq.ps1`

**Comment by stevencohn** [comment]
```
Set-ExecutionPolicy -Scope CurrentUser RemoteSigned -Force -Confirm:$false;
Set-Executionpolicy -Scope CurrentUser -ExecutionPolicy Unrestricted -Force -Confirm:$false;
.\iq.ps1
```

**Comment by stevencohn** [comment]
Do you only have OneNote installed but not other Office apps like Excel? 

In the current state, it is reporting that OneMore is not installed at all. 

It was working and then it didn't work, correct? Looks like you have a 64-bit system. You used the latest 64-bit OneMore installer?

There's more here that I can look into. Thanks

**Comment by stevencohn** [comment]
It certainly sounds like it is related to OneNote itself rather than OneMore. 

I'm adding a couple of checks to OneMore.

1. The installer will validate the OneNote installation to check a couple of important registry settings before installing OneMore.
2. I'll make sure OneMore is more forgiving when it comes to machines that do not have other Office products installed. There are a few commands that rely on at least Excel being there.
