### ISSUE TITLE
Command to shift nav bar to show the notebook and section containing current page at the top (vertical tab mode)

### ISSUE THREAD

**Issue by JoanEliot** [stevencohn/OneMore#1262]
# Problem to Solve 

In the vertical tab view, the nav bar doesn't jump to show the current notebook when you activate a page. If you've scrolled the nav bar it stays where it is when you switch between pages in the same notebook, and likewise if you jump between pages in different notebooks via links or the back button. Finding the right notebook can be hard, since the nav bar doesn't auto expand to sections and since the highlighting is subtle. ["I'm always frustrated when I try to find the right spot where sibling pages are located, given how many notebooks I have."] In horizontal tab view, the notebook (and section group, if any) for the current page automatically show. 

Provide a clear and concise description of the problem, e.g. I'm always frustrated when...

# New Feature/Solution

Provide a clear and concise description of what you want to happen. 
A OneMore command to automatically 'focus' the nav bar, ie to shift it to show the notebook containing the current page at the top of the nav bar, with the notebook expanded to show the page's section group and section. (This applies to vertical tab mode). This is an option OneNote should provide but...

## Alternative Solutions
An option to see the breadcrumb/path for the current page when you hover over the page title or alternatively by right clicking and choosing a command. You'd still have to manually navigate in the nav bar but at least you'd know where you're headed. (OneNote has hover-over hints for the sections in the nav bar, showing more or less the full path to the section in question, but not for pages, weirdly.)

Or an option to insert the OneMore breadcrumbs on all existing and new pages automatically, and to update the breadcrumbs automatically every time you create or move/rename a page. [I guess this is a separate point, but could clicking a link in one of those inserted breadcrumbs be made to adjust the nav bar, if it can't be made to automatically focus with any page change.]  

Provide a clear and concise description of any alternative solutions or features you've considered.

# Additional Context
Many thanks for considering this request. 
Provide any other context or screenshots about the feature request here.

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
The OneNote API (used by addins like OneMore) does not provide this level of control over the OneNote UI. My recommendation would be to open a ticket with Microsoft. Yeah, I know that's often a black hole but, unfortunately, there's nothing OneMore can do to solve this.

As for on-page breadcrumbs, OneMore has the ability to insert breadcrumbs at the top of the current page. The ability to update those if the page is moved isn't something that I see as top priority any time soon. It could not be done automatically. So would need an additional command or dialog to ask which pages to update, e.g. all pages in the current section that have breadcrumbs. But that would be a NEW feature and not be backwards compatible with existing breadcrumbs.

**Comment by jasonjac2** [comment]
@JoanEliot if you do raise with MS - let us know where it is and we can up-vote it.  I just spent 5 mins going through my OneMore and Onenote notes and can't see where the best place to raise a ticket is.

@stevencohn I am sure you have given me the 1.2.3 of raising issues with MS, but I just can't find it.... sorry (maybe if I used Obsidian :-), I would be more organised ).

Possible workaround: if you press f11 - you flip to the view where the notebooks are top right in a dropdown, this seems to show you the correct place as highlighted?

Regards,
JAC.

**Comment by JoanEliot** [comment]
@stevencohn Thanks for the clarifications and in general, for the quick response. I've tried in the past to raise issues with Microsoft and a) had a hard time figuring out how to do so, and then didn't write down the steps; and b) got no comment or other response from them. 

Understood regarding the inserted breadcrumb updates. What about the idea though of a hint/tooltip that shows when you hover over the page title either on the page or in the page list? If that's something you'd consider I'd be happy to post it as a separate feature request. 

@jasonjac2 I'm aware of the F11 thing but given the visual disturbance and steps involved and my lazy ways, I generally first try just scrolling through the nav pane, hoping to find my spot there. Or using search. If I do post a request with Microsoft I will come back and say so.
