### ISSUE TITLE
Page Level Regular Expression Search

### ISSUE THREAD

**Issue by PaulJamesTaylor** [stevencohn/OneMore#1267]
# How can I help you?

I would like to be able to do a substring search at the page level and for some inexplicable reason Onenote can't do that.  For example, I was reviewing data from a SQL deadlock dump today, which is a very dense XML document, and I wanted to search for a stored procedure with a name that contained the sub string 'custom' so I had to copy the text into VScode and did the search there and found it no problem, but that is obviously a cumbersome workaround.  Is there any way of easily doing this with Onemore?  I see that there is a regular expression search/replace, but I don't need to replace any text, I just want it highlighted on the page.

**Comment by stevencohn** [comment]
Duplicate of https://github.com/stevencohn/OneMore/issues/1084
