### ISSUE TITLE
6.0.1 cause onenote crush!!!

### ISSUE THREAD

**Issue by Test-Acount** [stevencohn/OneMore#1268]
# Problem to Solve

since install 6.0.1, open onenote, about 5m later, onenote crush.

# To Reproduce

open and crush. open and crush...

# Expected Behavior

# Screenshots
![Screenshot 2024-01-19 201759](https://github.com/stevencohn/OneMore/assets/13340945/070de790-27cf-4e3f-9687-7eb2fc17cd47)

# Environment (if applicable)

→log↓

# Additional Context

01| Starting dllhost 3408, 2995 Mhz, 8 MB, en-US/en-US, v6.0.1, OneNote 15.0, Office 16.0, 2024-01-19 15:46
01| ..Windows 11 Core, Version 22H2, Build 23619, 64 bit
01| ..C:\Program Files\Microsoft Office\Root\Office16\ONENOTE.EXE (16.0.17315.20000)
01| ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
01| ..OneAddInsUpdate(custom[])
01| ..building ribbon
01| ..building ribbon colorizer commands
01| ..building ribbon language proofing commands
01| ..building context menu
01| ..OnStartupComplete(custom[])
01| ..starting command service
01| ..starting reminder service
01| ..starting navigation service
01| ..starting hashtag service
01| ..ready
03| defined 47 hotkeys for input locale 1033
08| building hashtag database
08| hashtag database done
08| updating tags on page /LAB/Market/
08| error getting page {C9717EE7-E7FC-0721-367C-D555766F37E2}{1}{E19475391419883260861520128866108150188179351}
08| System.Runtime.InteropServices.COMException
Message: The remote procedure call failed. (Exception from HRESULT: 0x800706BE)
Description: Unrecognized error code 0x800706BE
ErrorCode: 0x800706BE (-2147023170)
HResult: 0x800706BE (-2147023170)
Source: Microsoft.Office.Interop.OneNote
StackTrace:    at Microsoft.Office.Interop.OneNote.ApplicationClassCOM.GetPageContent(String bstrPageID, String& pbstrPageXmlOut, PageInfo pageInfoToExport, XMLSchema xsSchema)
   at River.OneMoreAddIn.OneNote.GetPage(String pageId, PageDetail detail)
TargetSite: [Microsoft.Office.Interop.OneNote] Microsoft.Office.Interop.OneNote.ApplicationClassCOM::GetPageContent()

**Comment by stevencohn** [comment]
@jasonjac2 The error code is a generic COM exception that I've seen when the OneNote Interop API is overloaded. That's really hard to track exactly where without having hands-on.

As for the performance of the Hashtag scanner, the quick fix I've made currently is to simply slow it down, adding a small delay in between each page scan. As I mentioned above, I have some ideas how to decouple it and avoid the problem altogether.

**Comment by Test-Acount** [comment]
@jasonjac2 @stevencohn im doing nothing, just open onenote, and wait and it crush like the screenshot.

**Comment by Test-Acount** [comment]
01| Starting dllhost 15276, 2995 Mhz, 8 MB, en-US/en-US, v6.0.1, OneNote 15.0, Office 16.0, 2024-01-20 15:56
01| ..Windows 11 Core, Version 22H2, Build 23619, 64 bit
01| ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.17315.20000)
01| ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
01| ..OneAddInsUpdate(custom[])
01| ..building ribbon
01| ..building ribbon colorizer commands
01| ..building ribbon language proofing commands
01| ..building context menu
01| ..OnStartupComplete(custom[])
01| ..starting command service
01| ..starting reminder service
01| ..starting navigation service
01| ..starting hashtag service
01| ..ready
03| defined 47 hotkeys for input locale 1033
18| updating tags on page /LAB/Market/
18| error getting page {C9717EE7-E7FC-0721-367C-D555766F37E2}{1}{E19475391419883260861520128866108150188179351}
18| System.Runtime.InteropServices.COMException
Message: The remote procedure call failed. (Exception from HRESULT: 0x800706BE)
Description: Unrecognized error code 0x800706BE
ErrorCode: 0x800706BE (-2147023170)
HResult: 0x800706BE (-2147023170)
Source: Microsoft.Office.Interop.OneNote
StackTrace:    at Microsoft.Office.Interop.OneNote.ApplicationClassCOM.GetPageContent(String bstrPageID, String& pbstrPageXmlOut, PageInfo pageInfoToExport, XMLSchema xsSchema)
   at River.OneMoreAddIn.OneNote.GetPage(String pageId, PageDetail detail)
TargetSite: [Microsoft.Office.Interop.OneNote] Microsoft.Office.Interop.OneNote.ApplicationClassCOM::GetPageContent()

18| hashtag service exception 0
18| System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: River.OneMoreAddIn
StackTrace:    at River.OneMoreAddIn.Commands.HashtagScanner.<ScanPage>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.Commands.HashtagScanner.<Scan>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at River.OneMoreAddIn.Commands.HashtagScanner.<Scan>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at River.OneMoreAddIn.Commands.HashtagService.<Scan>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.Commands.HashtagService.<<Startup>b__5_0>d.MoveNext()
TargetSite: [River.OneMoreAddIn] River.OneMoreAddIn.Commands.HashtagScanner+<ScanPage>d__11::MoveNext()

16| error instantiating OneNote IApplication after 0 retries
16| System.Runtime.InteropServices.COMException
Message: Retrieving the COM class factory for component with CLSID {D7FAC39E-7FF1-49AA-98CF-A1DDD316337E} failed due to the following error: 80080005 Server execution failed (Exception from HRESULT: 0x80080005 (CO_E_SERVER_EXEC_FAILURE)).
Description: Unrecognized error code 0x80080005
ErrorCode: 0x80080005 (-2146959355)
HResult: 0x80080005 (-2146959355)
Source: River.OneMoreAddIn
StackTrace:    at River.OneMoreAddIn.ApplicationFactory.CreateApplication()
TargetSite: [River.OneMoreAddIn] River.OneMoreAddIn.ApplicationFactory::CreateApplication()

16| navigation service exception 0
16| System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: River.OneMoreAddIn
StackTrace:    at River.OneMoreAddIn.OneNote.get_CurrentPageId()
   at River.OneMoreAddIn.Commands.NavigationService.<Scan>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.Commands.NavigationService.<<Startup>b__11_0>d.MoveNext()
TargetSite: [River.OneMoreAddIn] River.OneMoreAddIn.OneNote::get_CurrentPageId()

**Comment by stevencohn** [comment]
@Test-Acount  It looks like it's failing almost immediately. Please if you could answer this, have you used OneMore in the past and has it worked in the past? Have other commands worked?

Of course, OneMore should not fail catastrophically like this but I'm wondering, if this is a new installation and you are a new OneMore user. If so, I suspect there is a problem with your OneNote installation. Have you tried a OneNote repair instlal?

You could check this by disabling the Hashtag service. This can be done in the settings. But if OneNote is crashing before it lets you get there, you can also disable it by adding the `<disable>` item to the `<HashtagSheet>` entry in your `%appdata%\OneMore\Settings.xml file` like this:

```xml
  <HashtagSheet>
    <disabled>true</disabled>
  </HashtagSheet>
```

If there are other items in the HashtagSheet entry, don't worry, just leave them.

Start up OneNote and try to use other OneMore commands. If they work, then it's a problem with the Hashtag service. If they do not, then it's likely a problem with your OneNote installation.

That you very much for providing the additional information. I really do want to make this a great experience for everyone.

**Comment by Test-Acount** [comment]
@stevencohn it's not a new-installed OneNote and onemore. i use the 5.9v onemore before, and it totally worked very well. yesterday i updated onemore to 6.0.1v (cover install). and crushed...

**Comment by stevencohn** [comment]
Seeing the extended exception details that you posted, I was able to track down one spot where OneMore was not recognizing a null value. While I'm not sure why it can't load any specific page, it will at least ignore the exception and should keep going. This fix will be in the next release, this weekend.

**Comment by Test-Acount** [comment]
Looking forward to the new version. I'll keep feed back. Thanks.

**Comment by Test-Acount** [comment]
I disabled the Hashtag service, other function of onemore works fine.

**Comment by Test-Acount** [comment]
@stevencohn  I installed the new version 6.1.0. but sitll crush. same as 6.0.1.


```
01| Starting dllhost 2268, 2995 Mhz, 8 MB, en-US/en-US, v6.1.0, OneNote 15.0, Office 16.0, 2024-01-21 12:05
01| ..Windows 11 Core, Version 22H2, Build 23619, 64 bit
01| ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.17315.20000)
01| ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
01| ..OneAddInsUpdate(custom[])
01| ..building ribbon
01| ..building ribbon colorizer commands
01| ..building ribbon language proofing commands
01| ..building context menu
01| ..OnStartupComplete(custom[])
01| ..starting command service
01| ..starting reminder service
01| ..starting navigation service
01| ..starting hashtag service
01| ..ready
03| defined 48 hotkeys for input locale 1033
17| updating tags on page /LAB/FlowPath/
15| updating tags on page /LAB/Market/
16| error getting page {C9717EE7-E7FC-0721-367C-D555766F37E2}{1}{E19475391419883260861520128866108150188179351}
16| System.Runtime.InteropServices.COMException
Message: The remote procedure call failed. (Exception from HRESULT: 0x800706BE)
Description: Unrecognized error code 0x800706BE
ErrorCode: 0x800706BE (-2147023170)
HResult: 0x800706BE (-2147023170)
Source: Microsoft.Office.Interop.OneNote
StackTrace:    at Microsoft.Office.Interop.OneNote.ApplicationClassCOM.GetPageContent(String bstrPageID, String& pbstrPageXmlOut, PageInfo pageInfoToExport, XMLSchema xsSchema)
   at River.OneMoreAddIn.OneNote.GetPage(String pageId, PageDetail detail)
TargetSite: [Microsoft.Office.Interop.OneNote] Microsoft.Office.Interop.OneNote.ApplicationClassCOM::GetPageContent()



14| skipping null page {C9717EE7-E7FC-0721-367C-D555766F37E2}{1}{E1955639905259040862471991301791246528610941} '/LAB/Audit'
03| error getting page {C9717EE7-E7FC-0721-367C-D555766F37E2}{1}{E1955868234162353794751952051264730939457371}
03| System.Runtime.InteropServices.COMException
Message: The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)
Description: Unrecognized error code 0x800706BA
ErrorCode: 0x800706BA (-2147023174)
HResult: 0x800706BA (-2147023174)
Source: Microsoft.Office.Interop.OneNote
StackTrace:    at Microsoft.Office.Interop.OneNote.ApplicationClassCOM.GetPageContent(String bstrPageID, String& pbstrPageXmlOut, PageInfo pageInfoToExport, XMLSchema xsSchema)
   at River.OneMoreAddIn.OneNote.GetPage(String pageId, PageDetail detail)
TargetSite: [Microsoft.Office.Interop.OneNote] Microsoft.Office.Interop.OneNote.ApplicationClassCOM::GetPageContent()

03| skipping null page {C9717EE7-E7FC-0721-367C-D555766F37E2}{1}{E1955868234162353794751952051264730939457371} '/LAB/Audit'
04| error getting page {C9717EE7-E7FC-0721-367C-D555766F37E2}{1}{E1949072038624822886521999590051689962236251}
04| System.Runtime.InteropServices.COMException
Message: The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)
Description: Unrecognized error code 0x800706BA
ErrorCode: 0x800706BA (-2147023174)
HResult: 0x800706BA (-2147023174)
Source: Microsoft.Office.Interop.OneNote
StackTrace:    at Microsoft.Office.Interop.OneNote.ApplicationClassCOM.GetPageContent(String bstrPageID, String& pbstrPageXmlOut, PageInfo pageInfoToExport, XMLSchema xsSchema)
   at River.OneMoreAddIn.OneNote.GetPage(String pageId, PageDetail detail)
TargetSite: [Microsoft.Office.Interop.OneNote] Microsoft.Office.Interop.OneNote.ApplicationClassCOM::GetPageContent()

04| skipping null page {C9717EE7-E7FC-0721-367C-D555766F37E2}{1}{E1949072038624822886521999590051689962236251} '/LAB/Audit'
18| error getting page {C9717EE7-E7FC-0721-367C-D555766F37E2}{1}{E19497854245862437617220164239250275728754091}
18| System.Runtime.InteropServices.COMException
Message: The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)
Description: Unrecognized error code 0x800706BA
ErrorCode: 0x800706BA (-2147023174)
HResult: 0x800706BA (-2147023174)
Source: Microsoft.Office.Interop.OneNote
StackTrace:    at Microsoft.Office.Interop.OneNote.ApplicationClassCOM.GetPageContent(String bstrPageID, String& pbstrPageXmlOut, PageInfo pageInfoToExport, XMLSchema xsSchema)
   at River.OneMoreAddIn.OneNote.GetPage(String pageId, PageDetail detail)
TargetSite: [Microsoft.Office.Interop.OneNote] Microsoft.Office.Interop.OneNote.ApplicationClassCOM::GetPageContent()

18| skipping null page {C9717EE7-E7FC-0721-367C-D555766F37E2}{1}{E19497854245862437617220164239250275728754091} '/LAB/Audit'
15| hashtag service exception 0
15| System.Runtime.InteropServices.COMException
Message: The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)
Description: Unrecognized error code 0x800706BA
ErrorCode: 0x800706BA (-2147023174)
HResult: 0x800706BA (-2147023174)
Source: Microsoft.Office.Interop.OneNote
StackTrace:    at Microsoft.Office.Interop.OneNote.ApplicationClassCOM.GetHierarchy(String bstrStartNodeID, HierarchyScope hsScope, String& pbstrHierarchyXmlOut, XMLSchema xsSchema)
   at River.OneMoreAddIn.OneNote.GetSection(String id)
   at River.OneMoreAddIn.Commands.HashtagScanner.<Scan>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at River.OneMoreAddIn.Commands.HashtagScanner.<Scan>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at River.OneMoreAddIn.Commands.HashtagService.<Scan>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.Commands.HashtagService.<<Startup>b__5_0>d.MoveNext()
TargetSite: [Microsoft.Office.Interop.OneNote] Microsoft.Office.Interop.OneNote.ApplicationClassCOM::GetHierarchy()


```

**Comment by Test-Acount** [comment]
i think my OneNote data is all good. i use several devices. all notes are good. I'm gonna disabled the service and try the next version...

**Comment by Test-Acount** [comment]
@stevencohn  I'm trying to look at this issue. there is no section id {C9717EE7-E7FC-0721-367C-D555766F37E2} in my notebook /LAB section. Is there a way to find the section and page based on the id in the log?

**Comment by stevencohn** [comment]
You can use the OneMore Extras/XML Dialog. When the dialog is displayed, click any tab other than the Page tab; you'll see a _Lookup Object ID_ field at the top, paste the ID. Select the _Function_ and click the green arrow button. Results will be shown in the _Manual lookup_ tab.

<img width="370" alt="image" src="https://github.com/stevencohn/OneMore/assets/9964757/b660fd2e-9d0c-4f7d-acd8-b8d82890ba8a">

**Comment by Test-Acount** [comment]
> skipping null page {C9717EE7-E7FC-0721-367C-D555766F37E2}{1}{E1955868234162353794751952051264730939457371}

@stevencohn  thanks. I disabled  the Hashtag service. and I tried to lookup the id in log (skipping null page {C9717EE7-E7FC-0721-367C-D555766F37E2}{1}{E1955868234162353794751952051264730939457371}) as your method, and the onenote app crushed just like the screenshot! so what's going on?

**Comment by stevencohn** [comment]
To be honest, I've no idea. Never seen this before.

Maybe you can try to verify the page this way. Since it's reporting in the log that the suspect page is coming from the LAB section, open OneNote, navigate to any page in the LAB section and open the XML dialog. Click the Section tab. Now search for that ID.

If it exists then there's something wrong with the storage of that page that the Interop API cannot handle (maybe OneNote itself can read it fine but its API used by OneMore cannot.) 

If it does not exist then there's something wrong with the storage of the section index. Again, something that the API perhaps cannot handle well.

Either way, I'm adding extra logging and exception handling to OneMore to try to catch odd cases like this so hopefully I can understand it better in the future. Thank you for your help!

**Comment by Test-Acount** [comment]
@stevencohn finally. I got something. I locate the page(`skipping null page {C9717EE7-E7FC-0721-367C-D555766F37E2}{1}{E1955868234162353794751952051264730939457371}`). and the Hashtag service is disabled. when I open that page, OneNote crush. so something wrong with this page. and the OneNote tell me to disable my add-in, and I did it. I go to the web OneNote, copy the page content to a new page, and delete the old one. I open Onenote syn all. and I go to the new page, it's all good. next I enable OneMore and restart onenote, and go to the new page, and crush!!! I'm confused...

**Comment by stevencohn** [comment]
The OneMore Navigator service is trying to pick it up and running into the same problem.

Does the page have sensitive content? If not, would you mind sharing it? Could you please Export the page as `.one` file and attach it here?

If it is sensitive, but you'd be OK sharing just with me, let me know and we can connect via email. I really want to solve this!

**Comment by Test-Acount** [comment]
This note contains a lot of content, and it also has a lot of different formats, such as pictures, formulas, tables, marks, etc. I'll try to split this page to determine what the problem is. I'll share it with you if it's sure. Maybe I'll try it tomorrow.

**Comment by Test-Acount** [comment]
I analyzed the content of the wrong page. **The problem is in the formula part.**

This formula is a comment section that I accidentally copied in, and this section is hyperlinked. If you create a separate formula, you are not allowed to create a hyperlink, but you can copy one into the formula.

That's the problem. If you copy a page contains a formula with a hyperlink, OneNote will sometimes crash, but **not certainly.** This operation has nothing to do with other plugins, which is the reason for OneNote itself.

But the wrong page was created about two years ago, and there was no problem with previous access, so it **may be caused by some updates of OneNote**.

Back to this test page (attachment), if you enable OneMore (not about the Hashtag service) and then open this page, it will **crash 100%**.

About the Hashtag service, I deleted the hyperlink in the formula of that wrong page, and the Hashtag service scanned it again, there was no problem at all, everything back to normal.
`08| hashtag service scanned 1790 pages, updating 18, in 935120ms`

[TestPage.zip](https://github.com/stevencohn/OneMore/files/14017223/TestPage.zip)

**Comment by stevencohn** [comment]
That's great detective work and I'm very glad it's working back to normal for you now.
Thanks for the zip. I'll do a little digging myself and see what I can learn.
Thank you so much!
