### ISSUE TITLE
Dynamically Update Position Variable for Centered Editing

### ISSUE THREAD

**Issue by PaulJamesTaylor** [stevencohn/OneMore#1269]
# Problem to Solve

Option to dynamically update position variable for centered document editing.

# New Feature/Solution

For most notes the default position of 36 is fine, but there are some long form documents I would like to have centered on my wide monitor when I am in Full Page mode.  

Below is what the XML setting is when creating a new page without a template:

![image](https://github.com/stevencohn/OneMore/assets/22547745/ce483e52-b785-4c7e-8554-986124623e94)

## Alternative Solutions

1) Onetastic macro to update the variable (trying to deprecate this)
2) I can use the Onemore XML editor to just set  the position if I want to utilize the full screen mode and that works OK, but it would be a nice feature to be able to set it dynamically without Onetastic.

# Additional Context

Below is a screenshot of what it looks like after I manually edit the XML.  This works.  Seems like I just need this one variable updated.

![image](https://github.com/stevencohn/OneMore/assets/22547745/25eb19ea-0fb7-453b-9fb1-d2e64654f42a)

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
Can add an "indent" field to the Arrange Containers command.

**Comment by stevencohn** [comment]
<img width="279" alt="image" src="https://github.com/stevencohn/OneMore/assets/9964757/9e64aaa1-d3cf-4325-b652-01c27ec7b6b6">
