### ISSUE TITLE
Inconsistencies with recognizing images

### ISSUE THREAD

**Issue by goodloetb2** [stevencohn/OneMore#1273]
# Problem to Solve
Inconsistent recognition of images on a page. Can recognize initial image pasted onto page, but not subsequent images or repasted images after the previous image was deleted.

# To Reproduce
If I start a blank page, paste an image in, then right click on the image and click "Resize and adjust", the expected dialog box will appear. However, if I delete the image then paste it back in and repeat the steps, I'll receive the message "No images were found on this page."

# Expected Behavior
That pasted images are consistently recognized as images and that the "Adjust and resize" dialog will appear as expected.

# Screenshots

![image](https://github.com/stevencohn/OneMore/assets/156608528/2a32f6f4-6c48-432d-8fff-334570e90d4d)

# Environment (if applicable)

 - OneNote Version: Office 365, Windows 11 64-bit
 - OneMore Version: 6.0.1 with OneNote 16.0.17126.20132

# Additional Context

[OneMore.log](https://github.com/stevencohn/OneMore/files/13998931/OneMore.log)

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!
![image](https://github.com/stevencohn/OneMore/assets/156608528/a6b769a3-85e5-4e15-bb99-0d51d6565b59)

**Comment by stevencohn** [comment]
It will work as follows:

0. If there is one selected image, foreground or background, adjust that one only
1. If there are selected foreground images, adjust only those
2. else if there are selected background images, adjust only those
3. else if there are foreground images, adjust all of them
4. else f there are background images, adjust all of them

If more than one image is selected, the Adjust dialog will indicate how many and whether they are foreground or background images, like this:

<img width="265" alt="image" src="https://github.com/stevencohn/OneMore/assets/9964757/14a27e95-026e-48e7-a886-9f5576f326ae">

I'm stopping there, trying to keep it intuitive and not overly complicated.

**Comment by goodloetb2** [comment]
I don't really think this is addressing what I described. All I did was start a new page and paste a single image into it. I'm able to access the "adjust and resize" screen. But then if I delete the image and then simply repaste it back in, it then says there's no image. Would it be helpful if I recorded a quick video?

**Comment by stevencohn** [comment]
Like this?

![image-demo](https://github.com/stevencohn/OneMore/assets/9964757/7bcd6e60-7958-4083-817f-fee79915eedc)

**Comment by goodloetb2** [comment]
> Like this?
> 


Here I made a quick video to demonstrate. Don't mean to be a pain and my apologies if this is a known issue: [https://youtu.be/Kcmy-mvk9cA](https://youtu.be/Kcmy-mvk9cA)

**Comment by stevencohn** [comment]
Great video. You have a voice for radio ;-)

I keep trying to repro this but just can't.

The difference between the first paste and the other one that is positioned lower on the page is that you'll notice the first one is pasted into a "content container" which you can see by its gray outline. Images in these containers are considered foreground images and move in relation to the surrounding content and text.

In the second case, you're pasting onto the background of the page. Background images are absolutely positioned and do not move in relation to other content on the page. 

The Resize and Adjust command should work equally well in both cases. In fact, you'll notice that my GIF above first pastes an image into a "content container" and then it pastes a background image.

I've tried both right-click+paste and Ctrl+V to add the image with the same results. So, I'm afraid, I'm not sure what you're doing differently.

**Comment by goodloetb2** [comment]
> Great video. You have a voice for radio ;-)

Thanks! That's not the first time I've heard that. 🎙️😎
