### ISSUE TITLE
Navigator in Dark Mode

### ISSUE THREAD

**Issue by koppor** [stevencohn/OneMore#1285]
I am using auto switching on Windows. Dark mode in the night, light mode during the day. During night, the Navigator stays white:

![image](https://github.com/stevencohn/OneMore/assets/1366654/9e886d7f-1e76-49c3-ab0c-62907aae3a69)

Would it be possible to have a dark theme for the naviagor?

**Comment by stevencohn** [comment]
<img width="277" alt="image" src="https://github.com/stevencohn/OneMore/assets/9964757/2c0a5fe5-496e-4247-ae11-d98c1ff4cf0e">

**Comment by stevencohn** [comment]
Ha! My poor artistic choice I suppose. It's the new "Add to my reading list" button. No additional functionality yet I'm afraid. All OneMore windows and dialogs have had a makeover and can now run in either light or dark mode.
