### ISSUE TITLE
Allow Navigator window resizing by PowerToys' Fancy Zones

### ISSUE THREAD

**Issue by koppor** [stevencohn/OneMore#1286]
Microsoft PowerToys offers [FancyZones](https://learn.microsoft.com/en-us/windows/powertoys/fancyzones). One can drag'n'drop a Window into a zone, where the Window is resized to.

This does not work with the Navigator. The Navigator resizes after being dropped into a Zone.

My aim is to have OneNote Navigator on the side of OneNote:

![image](https://github.com/stevencohn/OneMore/assets/1366654/37eb84ad-77a5-446d-a9d3-e5a209f1c4b6)

For that, I configured a FancyZone layout "OneNote" with two areas: one for OneNote and one for the Navigator:

![image](https://github.com/stevencohn/OneMore/assets/1366654/b1d3cc21-45e3-416d-9c21-a2a7df261645)

However, I cannot drop the Navigator into Zone 2. Seems to have a special window property.

---

Maybe, a toggle button "Pin" would be a solution? That could enable the window being always on top - and disabling the toggle button leads the Navigator to behave like a normal window.

**Comment by stevencohn** [comment]
You'll be able to disable the navigator setting _Restrict the Navigator window to the active screen_ even when there is only a single screen. Available in the next release.
