### ISSUE TITLE
MySnippets Failing when I have Autohotkey running on my system

### ISSUE THREAD

**Issue by Wheathead** [stevencohn/OneMore#1294]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>

<div style='direction:ltr;border-width:100%'>

<div style='direction:ltr;margin-top:0in;margin-left:0in;width:6.7416in'>

<div style='direction:ltr;margin-top:0in;margin-left:0in;width:6.7416in'>

<div style='direction:ltr'>

#Problem   to solve | When I   attempt to save a new Snippet and my system has Autohotkey running any   script, the OneNote OneMore MySnippets functionality won't work.
-- | --
See   Image 1 | Adding a   new Snippet "AHK Code Block"
  |  
![image](https://github.com/stevencohn/OneMore/assets/68067387/856d2ba5-81e3-415f-a349-34c7fa4b434e)

No error | Selecting Text and using MySnippets to save it

Retrieve   Snippet via Expand from text using MySnippets Menu       

AHK Code   Block, select     (spaces   in name)       Menu   Expand Snippet From Name | OneMore       Could   not load snippet from   "C:\Users\jpmui\AppData\Roaming\OneMore\Snippets\AHK Code   Block.snp"       OK

Ok to   error, then close One Note and then reopen it. | My   experience has been that I have to close and reopen OneNote for the snippets   to show.
Snippet   is Showing in MySnippet Menu | See   Image 2
  |  
<img width="341" alt="2024-01-27 10_30_27-" src="https://github.com/stevencohn/OneMore/assets/68067387/06a8de62-8acd-446a-be6e-105c2cb7cac1">

Now   selecting AHK Code Block from menu | Same   Error   OneMore       Could   not load snippet from   "C:\Users\jpmui\AppData\Roaming\OneMore\Snippets\AHK Code   Block.snp"       OK

Retrieving   a different working  snippet from   MySnippet menu | No   error, just these numbers pasted into OneNote Page       02

Closing Autohotkey v2 scripts that are   running          Also closing and reopening OneNote |  
Retrieving   that same (different) snippet from menu | Works as   designed

Retrieving   the orginal MySnippet I named AHK Code Block | Works   perfectly

Retrieving   the orginal MySnippet I named AHK Code Block using the Menu by name | Works   perfectly

Restarting Autohokey script | Leaving   OneNote Open

Accessing   my original snippet named  AHK Code   Block using Snippet Menu | Result   is pasted text 02, no error          02

Accessing   my original snippet named  AHK Code   Block using Snippet Menu by name | Selecting   AHK Code Block     Menu by Name     Result: text removed and replaced with 02

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>

<div style='direction:ltr'>

Edition        Windows   10 Home   Version        22H2   Installed   on        ‎2/‎13/‎2022   OS   build        19045.3930   Experience        Windows   Feature Experience Pack 1000.19053.1000.0

Microsoft® OneNote® for Microsoft 365 MSO (Version 2312 Build 16.0.17126.20132) 64-bit 

OneMore Version 6.1.0 with OneNote 16.0.17126.20132

</div>

</body>

</html>

</div>

</div>

</div>

</div>

</body>

</html>

**Comment by stevencohn** [comment]
The OneNote Snippets commands emit a Ctrl+V key sequence to paste the snippet content. This is not going to change, certainly not any time in the foreseeable future.

I'm not an AHK user but I'm guessing it's intercepting the Ctrl+V and doing something else. Is there anything in AHK that might interfere with that key sequence?

**Comment by Wheathead** [comment]
I reviewed any Hotkeys or Hotstrings in use, none use Ctrl-V  but for now, I'm going to do a deep dive into my scripts to see which, if any might intercept Ctrl-V for any reason and report back and I expect you are right about that.  

OneNote GEM also uses Ctrl+V so I'm going to experiment some more by disabling that add-in as well.  

Thanks for the quick response

**Comment by Wheathead** [comment]
Thanks again Steve.
You can mark this one:  User configuration error interfering with MySnippet functionality.

I disabled a clipboard function in one of my scripts which I don't even use, so it shouldn't have interfered with anything because not of my scripts called that function and another script hotkey which pasted plain text, but alas, once disabled, OneMore worked perfectly as designed. I couldn't find any keyboard hooks that actually used Ctr+V, but anyway right now its all working well in OneMore land.  Great product by the way!
