### ISSUE TITLE
Crashing when OneMore installed

### ISSUE THREAD

**Issue by JRPX33** [stevencohn/OneMore#1296]
# Problem to Solve

I'm seeing OneNote crash multiple times per day when I have OneMore installed.   When I remove OneMore, the crashing stops.    

# To Reproduce

 There doesn't seem to be any particular activity that causes the crash, sometimes it happens when I'm away from the computer.  

After it happens I get this dialog : 
![image](https://github.com/stevencohn/OneMore/assets/123988676/43ac1455-5b7d-4af8-9413-cb5884d9f67a)

and it sticks on this forever until I either reboot or kill all the onenote processes.   

# Expected Behavior

Not Crashing

# Screenshots

Description

here's what shows in reliability monitor when it crashes.
```
Faulting Application Path:	C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE

Problem signature
Problem Event Name:	APPCRASH
Application Name:	ONENOTE.EXE
Application Version:	16.0.17029.20140
Application Timestamp:	65985446
Fault Module Name:	RICHED20.DLL
Fault Module Version:	16.0.17029.20000
Fault Module Timestamp:	653f3a78
Exception Code:	c0000005
Exception Offset:	0000000000240985
OS Version:	10.0.19045.2.0.0.256.48
Locale ID:	1033
Extra information about the problem
Bucket ID:	f90df1daf849afac0ec15284d7a68604 (2216143222150170116)
```
.
I've uploaded a log showing a bunch more of the event viewer app crash entries.  
[apperrors.txt](https://github.com/stevencohn/OneMore/files/14146179/apperrors.txt)

# Environment (if applicable)

I'm on Windows 10, OneNote version: 2311 (build 17029.20140)
Onemore: Version 6.1.0 with OneNote 16.0.17029.20140

# Additional Context
Seeing lots of errors in the OneMore log.  I've never looked at that before so not sure if it's typical.  

Here's a log from my current session before onenote crashes.  
[onemorelog.txt](https://github.com/stevencohn/OneMore/files/14146135/onemorelog.txt)

**Comment by stevencohn** [comment]
Check your Quick Notes for any #hashtags and remove those tags until the next release of OneMore is available. Sorry for the inconvenience. Another test case to add to my list...

**Comment by JRPX33** [comment]
If I make a new section for quicknotes will it only scan that one?  or will it scan everything that's ever been a quicknote.  That would be tough to remove them all.   Is there and older version I could revert to for now that won't have this issue?

**Comment by stevencohn** [comment]
The problem is that quick notes do not have titles and the Hashtag scanner tries to store the ID of the title but can't because it expects the value to exist. So a new section will not fix it.

**Comment by JRPX33** [comment]
Oh disabling the hashtag scanner is a win, I'll do that.  Thanks!

**Comment by davhuraven** [comment]
I had the same problem and @stevencohn tip of disabling the hashtag scanner fixed it for me too.
