### ISSUE TITLE
Resize and Adjust is enlarging images, even when "Do No Enlarge" is set

### ISSUE THREAD

**Issue by JRPX33** [stevencohn/OneMore#1297]
# Problem to Solve

When I run the Resize and Adjust command and set it to "Do No Enlarge Smaller images"  it still enlarges the smaller images.

# To Reproduce

Go to a page with multiple images, open the dialog, set it to not enlarge images.  The smaller images get enlarged.

# Expected Behavior

Should be not touching the smaller images.

# Screenshots

Page before:
![image](https://github.com/stevencohn/OneMore/assets/123988676/1c459fb5-6965-478b-8068-20da8e5ba088)

Command settings:
![image](https://github.com/stevencohn/OneMore/assets/123988676/806ddeaa-ab65-474f-b2ea-cfd44ee6483c)

Small images are enlarged:
![image](https://github.com/stevencohn/OneMore/assets/123988676/92312c23-3e4b-416b-be68-c6b52632112b)

# Environment (if applicable)

I'm on Windows 10, OneNote version: 2311 (build 17029.20140)
Onemore: Version 6.1.0 with OneNote 16.0.17029.20140

# Additional Context

I experienced this on multiple pages so I don't think it's something specific with one page.

**Comment by stevencohn** [comment]
I'll add this to my test cases to catch future regression. Sorry for the inconvenience. Thanks for the heads up
