### ISSUE TITLE
It doesn´t compile

### ISSUE THREAD

**Issue by GildedHonour** [stevencohn/OneMore#13]
I have over 100 compilation errors.

.net 4.6.1, vs 2015

I've tried C# 4-6

**Comment by GildedHonour** [comment]
I haven't run it Nuget. Most of the errors are unrelated to this.

What's the version of C# you built it with?

**Comment by stevencohn** [comment]
Latest VS2017. Can you zip up the error logs? Maybe there's a clue in there.

**Comment by GildedHonour** [comment]
VS2017 isn't the version of C#

**Comment by GildedHonour** [comment]
I can't install it now. The setup project won't load. 

I added manually the key in registry:

	HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\InprocServer32



And I created a item titled `CodeBase` of type RES_SZ with the  value: '

         {the full path}\River.OneMoreAddIn.dll


After I restart OneNote, the adding doesn't appear anywhere in it.

**Comment by stevencohn** [comment]
Microsoft OneNote 2016 32-bit installed locally?

**Comment by GildedHonour** [comment]
Yes, OneNote 2016 installed locally.  

x64 or 32-bit -- I don't know which one I have.

How should I change the code if it's x64?

**Comment by GildedHonour** [comment]
Where does `{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61` come from?

**Comment by GildedHonour** [comment]
Ok, but why doens't it appear in my OneNote? 

On which tab it should appear?

**Comment by stevencohn** [comment]
Try these two things

1. Save this to onemore.reg and then double-click that file. Change the paths accordingly.

Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}]
@="River.OneMoreAddIn.AddIn"
"AppID"="{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}"

[HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\Implemented Categories]

[HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\Implemented Categories\{62C8FE65-4EBB-45E7-B440-6E39B2CDBF29}]

[HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\InprocServer32]
@="mscoree.dll"
"ThreadingModel"="Both"
"CodeBase"="C:\\Github\\OneMore\\OneMoreAddIn\\bin\\x86\\Debug\\River.OneMoreAddIn.dll"
"Assembly"="River.OneMoreAddIn, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null"
"Class"="River.OneMoreAddIn.AddIn"
"RuntimeVersion"="v4.0.30319"

[HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\InprocServer32\0.1.0.0]
"CodeBase"="C:\\Github\\OneMore\\OneMoreAddIn\\bin\\x86\\Debug\\River.OneMoreAddIn.dll"
"RuntimeVersion"="v4.0.30319"
"Assembly"="River.OneMoreAddIn, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null"
"Class"="River.OneMoreAddIn.AddIn"

[HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\ProgID]
@="River.OneMoreAddin"

[HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\Programmable]
@=""

[HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\TypeLib]
@="{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}"

[HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\VersionIndependentProgID]
@="River.OneMoreAddIn"


2. In OneNote, open File/Options/Addins and check if you see the OneMore addin. If not you can add it manually by using this .reg file:

Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Office\OneNote\AddIns\River.OneMoreAddIn]
"LoadBehavior"=dword:00000003
"Description"="Extension for OneNote"
"FriendlyName"="OneMoreAddIn"


It should show up at the end of the Home tab.

**Comment by GildedHonour** [comment]
I've already said: my OneNote is x64. How should the reg file be changed?

**Comment by stevencohn** [comment]
I wish I could help you but I don't have OneNote x64. My only suggestion is to remove the Wow6432Node part from the Registry path. I wish you luck but you're very snippy and I've done nothing but try to be helpful. This is a hobby project and I can't dedicate time to someone who's unwilling to be cooperative.

**Comment by GildedHonour** [comment]
Go claim your mamy and dady
