### ISSUE TITLE
My Styles - heading styles, Calibri size 14 doesn't work

### ISSUE THREAD

**Issue by dowiew** [stevencohn/OneMore#1300]
I'm frustrated with the Heading 3 style. It's set to be Calibri 14, but when I apply the style, the text font size is always 12.
All the other font sizes work, except 14. I can see 14 in the edit box, but my heading text always becomes 12, when I apply the style.

OneNote 16.0.17231.20194, O365 version 2401, 64bit. Windows 10.
OneMore 6.1.0

**Comment by stevencohn** [comment]
Having trouble reproducing

**Comment by dowiew** [comment]
See a shared Notebook with the steps and screen recording embedded,
Font size 14.5 works. 14 doesn't - changes to 12.
[https://politechnikawroclawska-my.sharepoint.com/:o:/g/personal/wieslaw_dobrowolski_pwr_edu_pl/Elzd5dyupapMlC7KLIkMm-oBBhzjYEYHbkZ0WMUovF6Okw?e=ByRvsg](url)
