### ISSUE TITLE
Onemore not working

### ISSUE THREAD

**Issue by vandammer** [stevencohn/OneMore#1309]
Hi, thank you for developing this addin.

I followed all steps in "troubleshooting" but no Onemore (latest) in ON.
Reinstalled, rebooted.
win 11 x64 office 2016

Microsoft® OneNote® 2016 MSO (Version 2401 Build 16.0.17231.20194) 32-bit 

[OneMore.log](https://github.com/stevencohn/OneMore/files/14316290/OneMore.log)
[OneMoreSetup.log](https://github.com/stevencohn/OneMore/files/14316296/OneMoreSetup.log)

![image](https://github.com/stevencohn/OneMore/assets/159962096/ea56815c-5c80-484c-a20c-38d80b9ea321)

If you need more let me know please

Bob

# To Reproduce

# Expected Behavior

# Screenshots

# Environment (if applicable)

 - OneNote Version: [e.g. Office 2019, O365, also 32bit or 64bit?]
 - OneMore Version [e.g. 3.4 - from the About dialog or from the log file]

# Additional Context

Add any other context about the problem here. Attach page XML file or the app log file as appropriate. You can find the log file here: %localappdata%\temp\OneMore.log

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
Looks like your OneNote installation is suspect. You may need to install with the Repair option.

<img width="815" alt="image" src="https://github.com/stevencohn/OneMore/assets/9964757/1d397a05-5851-4b42-9703-6af1de1a8bea">

**Comment by stevencohn** [comment]
Were you shown a dialog during the installation that warned that the OneNote configuration might need updating?

**Comment by vandammer** [comment]
Hallo Steven,
 
No i wasn't.
 

vrijdag 16 februari 2024, 23:05:32, schreef u:


> Were you shown a dialog during the installation that warned that the OneNote configuration might need updating?
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.


-- 
Met vriendelijke groet,
knine                           ***@***.***

**Comment by vandammer** [comment]
Steven,
Thank you for responding.
Busy now but i will look into this repair option, after a thorough backup.

vrijdag 16 februari 2024, 23:05:32, schreef u:


> Were you shown a dialog during the installation that warned that the OneNote configuration might need updating?
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.


-- 
Met vriendelijke groet,
knine                           ***@***.***

**Comment by hanwantracters** [comment]
i met this problem too.
[OneMore.log](https://github.com/stevencohn/OneMore/files/14988131/OneMore.log)

**Comment by stevencohn** [comment]
@hanwantracters, your issue should be fixed in the next release.

@vandammer, if you can repair your OneNote installation and check OneMore again, then I can close this ticket. Thanks!
