### ISSUE TITLE
Add AI :-)) to OneMore: make it learn the most used comands and add them to the context menu

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#131]
**Is your feature request related to a problem? Please describe.**
Add AI to OneMore: make it learn the most used comands and add them to the context menu

**Describe the solution you'd like**
Add AI to OneMore: make it learn the most used comands and add them to the context menu
**Describe alternatives you've considered**
N/A
**Additional context**
I just realized Search and Replace would be something I would like to add to the context menu but there is no way to do that
A shourtcut could be used but then that breaks my flow, :-)) I only use one hand for all the operations , the other hand is used to rest my chin on it

**Comment by stevencohn** [comment]
So really what you need is a chin holder. LOL

It's easy enough to add the Search commands to the context menu settings panel.

A variation of this request that might be a good start is to do something similar to Photoshop which is always remember the last-used command and let you (optionally) show the last-used command in the context menu, regardless of what it was.

**Comment by stevencohn** [comment]
BUT, remember that the ribbon bar can't be changed on the fly without restarting OneNote, so I'm not sure this is worth it

**Comment by 1001QAdotNET** [comment]
I don't need it to do it on the fly
having an optimized context menu next day is fine

**Comment by 1001QAdotNET** [comment]
> So really what you need is a chin holder. LOL
> 
> It's easy enough to add the Search commands to the context menu settings panel.
> 
> A variation of this request that might be a good start is to do something similar to Photoshop which is always remember the last-used command and let you (optionally) show the last-used command in the context menu, regardless of what it was.

yes that is the spirit. AI was a figure of speech here

**Comment by stevencohn** [comment]
I added a Replay Last Command command. It's not a "deep" replay, meaning if the command displays a dialog asking for input, it won't do that silently - you'll still need to respond to the dialog. But it seems to work really well for most non-interactive commands like rotating highlighter, the Clean commands, Snippets, and others. Will be in the next release....

**Comment by stevencohn** [comment]
Deep replay coming for some dialog-based commands:

- Run Plugin
- Extras / Add icon to title page
- Extras / Insert Pronunciation

Maybe more...
