### ISSUE TITLE
Mini Toolbar Customization

### ISSUE THREAD

**Issue by Codewarriorx** [stevencohn/OneMore#1315]
Hi, I am new to using OneMore and OneNote. I enjoy the functionality OneMore adds but I wish some things like the "My Styles" could be added to the mini Toolbar that pops up when you select text. Is that currently possible?

**Comment by stevencohn** [comment]
Sadly, no. There is no provision available to add-ins such as OneMore to extend that mini-toolbar. You can, however, add OneMore controls to the right-click context menu: _OneMore > Settings > Context Menu_
