### ISSUE TITLE
Docs for #Hashtags

### ISSUE THREAD

**Issue by jasonjac2** [stevencohn/OneMore#1318]
# How can I help you?

Remedy my aging brain?
I just started testing hastags - I'll have suggestions, of course, but to begin with I wanted to really understand how they worked.

I understand the scanning etc etc.

It is the interface - I got 2 results for searching for a hastag, selected the checkbox and the index / copy / move came up.  I wanted to grab a copy of the pages (I must sound like a broken record wanting to be able to grab all the results from a search / favourites / history...)

I can't work out what index is supposed to do, so went hunting for the docs on hashtags and couldn't see it on the webpage or github docs.  Happy to write some, but wanted to check if there were any already.

I clicked index, a select a page / location dialogue came up, i selected
A blank page was created where I asked it to, but with no entries in it and ON seems to stutter for quite a few seconds.

So what is it supposed to do?

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
There is a quick blurb [on this page](https://onemoreaddin.com/commands/Search%20and%20Tag%20Commands.htm) under the Operations paragraph:

- The Index button will create a new page with an index of selected pages.
- The Copy button will copy the selected pages to another section or notebook.
- The Move button will move the selected pages to another section or notebook.

Feeling any younger?

**Comment by jasonjac2** [comment]
Just done a different # on on the same notebooks on a different machine and tried putting index in a different notebook and got the same blank page.  So I guess I need to know how to help track down the root cause od the problem.

**Comment by stevenmcohn** [comment]
It doesn't log for each scan unless either there are changes or it takes longer than one second to complete.
Yes, the first number is a thread ID.
The HTMLBlock message is interesting, I don't think I have a test case with an HTMLBlock on a page! 

I just tried to create an index page and, yep, it fails for me too 😢  But that's good because I finally have a bug I can reproduce! Happy days! 🥳

**Comment by stevenmcohn** [comment]
Although I just answered using the wrong account again. I need to stop doing that. 🙄

**Comment by jasonjac2** [comment]
It's a bit misleading on the hastag search screen with the old time on there, maybe have this on an info button, as I am sure it isn't too interesting to most.... "Last scan that took more than 1s:...... scans occur every n seconds"

**Comment by jasonjac2** [comment]
I'm also interested from anyone else how elaborately you are using hashtags?  I would love to use them with qualifiers, e.g. #Reviewed:240306.  there would be a standard argument delimeter, but the argument would mean different things to different hashtags.  I haven't experimented, but  I assume <space> , . : ; and any maybe _ marks the end of a hashtag. I know @stevencohn is waiting to get people using them before he elaborates or extends them further.

One (or two) other thing(s) would be to add:
-  "Near" or "samePara" in the search, for my long pages. and it would be an extension of AND.  It would need the DB to log instances of the hashtag and the para offset in the page.
- Count(hastag)><a number> so you can search for your big #FixThis pages.

**Comment by stevencohn** [comment]
Letters, numbers, hyphens and underscores can be used to specify a hashtag. Any other character will terminate.

Thanks for suggestions and I look forward to hearing what others are doing!
