### ISSUE TITLE
Export page to svg

### ISSUE THREAD

**Issue by intzaaa** [stevencohn/OneMore#1319]

**Comment by stevencohn** [comment]
Building an SVG library is a huge endeavor. There doesn't appear to be any freely available .NET libraries that provide what would be needed. This is currently beyond the scope of the OneMore project.

If you're a programmer, you may want to check out offerings from Grapecity or Aspose.NET. You would either need a translation layer to convert OneNote XML to SVG, or convert a page to HTML and then that HTML to SVG.
