### ISSUE TITLE
Shortcuts explorer: add a menu option that would display all the OneMore shortcuts and even the OneNote shortcuts

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#132]
**Is your feature request related to a problem? Please describe.**
It is annoying to have to Google this all the time
**Describe the solution you'd like**
click a ribbon button and see all the shortcuts grouped by category

**Describe alternatives you've considered**
Googling for the doc or having it somewhere in OneNote

**Comment by stevencohn** [comment]
Microsoft's page listing the OneNote shortcuts are linked to from my Wiki https://github.com/stevencohn/OneMore/wiki

But I've thought of the same thing honestly

**Comment by 1001QAdotNET** [comment]
The way this was implemented was not exactly what I had in mind but I guess it will help many other  users
As you noticed I focus on staying focused when reading so most of the features I requested have been on this note 
Applying the above to this I expected the shortcuts screen not page to pop up when I needed for a quick look and then disappear.
Having a onenote page for that is something that I already had and having to switch between docs was annoying hence my request

**Comment by stevencohn** [comment]
I understand but you see where I'm going with this, building an infrastructure to import and manage page template, something that OneNote can't do. It only allows you to create templates from existing pages.

**Comment by 1001QAdotNET** [comment]
hmm that sounds interesting, how would that be used ? (not syaing it can't but I would like to know the use case scenarios you have in mind)

**Comment by stevencohn** [comment]
If you look at OnenoteGem, it has a library of templates as .one files. These must be downloaded, the imported into OneNote, which opens them into a separate section, then you have to move the page from that section to the section you want.

OneMore will be able to download a template and import it as a new page into the current section immediately just like the Keyboard Shortcuts favorite does. But I'm envisioning a new dialog that lets you browse available templates, so only a couple of clicks. OneMore templates will be in both .xml and zipped .xml format. I'm also looking at a way to import .one files without the temporary section creation, but the OneNote API is fighting me.

**Comment by 1001QAdotNET** [comment]
that sounds like fun
above I meant the use case scenarios for templates
