### ISSUE TITLE
After importing word document, some letters are not recognized

### ISSUE THREAD

**Issue by daboshh** [stevencohn/OneMore#1321]
Hello!
If word document has latvian letters, like āšņūīļ etc., then after importing they show up as question mark.

**Comment by Alien0176** [comment]
I'm also having this issue with "quotation marks" and apostrophes, hyphens etc. when importing word documents.

**Comment by stevencohn** [comment]
The next release will force Unicode encoding when importing Word docs.

But you should be able to work around this now by changing the Save as/Web options in Word. Once set in Word, it will apply even when OneMore imports documents. (OneMore asks Word to save to HTML and then it injects that HTML onto your page)

This is from the _Save as_ dialog:

<img width="429" alt="image" src="https://github.com/stevencohn/OneMore/assets/9964757/af526681-80da-41b2-8210-881b7bfc93e4">

**Comment by Alien0176** [comment]
Thank you very much
