### ISSUE TITLE
How to use RegEx in Find/Replace (particularly to add space after paragraph breaks?"

### ISSUE THREAD

**Issue by Foxxsayy** [stevencohn/OneMore#1322]
MAy I ask how to get another line in after a paragraph break? A lot of my web material comes without spacing, and I can't seem to get Find/Replace to work with this. I believe the hidden characters are usually `CR` and `LF`, and it seems `\n` inserts a new line, but I can't get figure out how to get it to replace or insert after paragraph breaks.

**Comment by stevencohn** [comment]
There are a couple of ways to do this. You can use Shift

**Comment by stevencohn** [comment]
There are a couple of ways to do this. Pressing Enter will obviously create a new paragraph and create the default amount of space between the paragraphs. Pressing Shift-Enter will keep context within the same paragraph but simply insert a line break, similar to a `\n`.

A second option is to select one or more paragraphs and use the built-in OneNote _Paragraph Spacing Option_ command located in the Alignment drop-down button.

**Comment by stevencohn** [comment]
That should work if your page has lines separated by soft breaks created with `Shift+Enter`. It will not find hard line breaks created with just `Enter`.

For hard breaks, you'd need to select lines of text and then use the OneMore Edit/Join Paragraph command.

**Comment by Foxxsayy** [comment]
> For hard breaks, you'd need to select lines of text and then use the OneMore Edit/Join Paragraph command.

Perhaps that's it. I can find the join paragraph, but I can't seem to figure out where edit paragraph is?

![image](https://github.com/stevencohn/OneMore/assets/98929636/0638fb94-4ee5-4937-b734-171990b82727)

**Comment by ykurji** [comment]
did you find a solution to this? I am also trying to figure out how to remove line breaks from selected text

**Comment by stevencohn** [comment]
OneNote does not use CR, LF, or `\n` as line breaks. Internally, it's a binary format but through the API that OneMore uses, it's XML. As I mentioned above, however, there can be _hard breaks_ and _soft breaks_. Hard breaks, created when you press `Enter`, are ostensibly paragraphs. If this is what you have, then you can use the OneMore _Join Paragraph_ command, available on the OneMore _Edit_ menu; this is exactly what you found in your picture above.

Soft breaks, created when you press `Shift-Enter` are mid-paragraph line breaks. The OneMore Search and Replace dialog, as shown above, knows how to translate `\n` to these XML soft breaks and can eliminate them, effectively joining the broken lines.

If neither of these solutions work for you, then you may have another use case that I don't understand. So please add more details or an example if you can.

**Comment by ykurji** [comment]
I was copy-pasting from a PDF. I suppose those wore hard breaks as only the Join Paragraph option worked for me.

**Comment by ykurji** [comment]
On another note: when all the text is selected inside a display container, the option "Join Paragraphs" doesn't show up in the context menu.

**Comment by stevencohn** [comment]
By design. When you select the entire container, that's a different context menu; OneMore does not extend that context menu. Select just the text _within_ the container, but not the container itself.
