### ISSUE TITLE
Friendlier change page creation time

### ISSUE THREAD

**Issue by ACTom** [stevencohn/OneMore#1324]
# Problem to Solve

Onenote now change page to create time need to double click, and then in the pop-up calendar to select the date, if you need to change to the previous year, need to click many times, and the time can only be selected whole half hour, can not be to the specific hour and minute.

# New Feature/Solution

I would like to have a tool to change the page creation time in a more user friendly way, so that I can change the creation date and time by manually entering it.

**Comment by stevencohn** [comment]
I don't think this is a big enough use case for updating the time on a single page.

However, there may be a use case where you want to change the time on selected pages or all pages in a section or notebook. (Which means you could select a single page, by the way!) So perhaps....

**Comment by stevencohn** [comment]
Added Update Page Time command with #1702
