### ISSUE TITLE
Please add colorizing support for php

### ISSUE THREAD

**Issue by abtzero** [stevencohn/OneMore#1325]
**What a great Add-in! Can't live without it. Great job!**

CSS, HTML, XML, javascript are there, so very important: PHP is missing.

I tried to add by myself by adding php.png (16x16) and a php.json into Colorizer\Languages, restartet OneNote, but it doers not show up in the UI-list.
Needs it to be compiled?
Or  do I have to de-activate and activate the addin on OneNote first?

Anyway, I started with the csharp.json and replaced the list of keywords.
That is the only change I made. It might not be perfect

P.P.
I started with the selection "Feature request", but my post did not get this label, and I can't add it later on...

**Comment by stevencohn** [comment]
Check the %temp%\OneMore.log file. There may be a syntax error in the json??

**Comment by stevencohn** [comment]
There is a Themes folder adjacent to the Languages folder. Hopefully, there are enough classifications of colors in there already; they are all shared amongst the languages so if PHP has something specific, it would be best to create a new classification.

You can share changes here to submit a PR to this repo.

**Comment by abtzero** [comment]
Found it!

**Comment by stevencohn** [comment]
Hey @abtzero! If you have the php config files, feel free to open a pull request. Or attach them here and I'll include them in the next release.

**Comment by yuganglidemao** [comment]
@abtzero Can you provide php.json download, thank you!

**Comment by abtzero** [comment]
Here we are.

 

Best regards

Sven Rowoldt

Von: yuganglidemao ***@***.***> 
Gesendet: Montag, 8. April 2024 04:30
An: stevencohn/OneMore ***@***.***>
Cc: Sven Rowoldt ***@***.***>; Mention ***@***.***>
Betreff: Re: [stevencohn/OneMore] Please add colorizing support for php (Issue #1325)

 

@abtzero <https://github.com/abtzero>  Can you provide php.json download, thank you!
