### ISSUE TITLE
How to kick off the hashtag search engine?

### ISSUE THREAD

**Issue by seaspeak** [stevencohn/OneMore#1330]
# How can I help you?

My hashtag search engine seems to stop working. The keyword "*" always gives me three results. I tried "Scan Now" and confirm the "Last scan" time is changing. To stop the service and restart it in OneMore settings. I even rebuild the whole Windows search index. I also add #skiphashtags in the pages of the three. It still gives me the three results.

How do I check the status of the hashtag search engine to make sure it is really running?

**Comment by stevencohn** [comment]
Easiest way is to open OneMore Settings and choose Rebuild on next restart. Shutdown OneNote and reopen and it will rebuild the catalog. 

OneMore relies on its own SQLite database (OneMore.db); it does not use Windows Search.

This will be very different in the next release, and hopefully more robust as well.

**Comment by stevencohn** [comment]
Oh sorry, it's a hidden "experimental" feature. Go back to the General sheet and enable experimental features, restart OneNote, then go to the Hashtags sheet and choose Rebuild on restart.

**Comment by stevencohn** [comment]
I'm wrong again, this is version specific, not an experimental feature. Do you have the latest version?

Regardless, another way to do this is to simply delete the file %APPDATA%\OneMore\OneMore.db. Restart OneNote and it will rebuild the catalog.

**Comment by seaspeak** [comment]
I just upgraded to the latest version. Now I know I do have more than three hashtags. Thanks.
