### ISSUE TITLE
My Snippets has some bugs

### ISSUE THREAD

**Issue by liuyuqiangchn** [stevencohn/OneMore#1333]
My Snippets is a very useful tool. During my use, I found several bugs.

1：Style problem, the style will not be completely copied

For example, in the picture below, img1 is the original style, img2 is Save New Snippet, bug1 is that the table border is displayed, and bug2 is that the table length has changed.

![image](https://github.com/stevencohn/OneMore/assets/22015183/56dba6b9-d6c7-4111-b8ea-d8e9e3ea6767)

2：Heading problem, Heading1 is missing

For example, in the picture below, img1 is the original style, img2 is Save New Snippet,The title in img2 has lost the Heading1 style and cannot be displayed in the Navigator window.

![image](https://github.com/stevencohn/OneMore/assets/22015183/05acfdc0-9b39-4d09-9047-01e0ef9d7eaf)

3：This is not a bug, but a feature request. Every time you save a New Snippet or delete a Snippet, you need to close OneNote again before the New Snippet can be displayed. Can this be optimized?

Thank you again for creating such a great plugin！

**Comment by stevencohn** [comment]
Note to self: [This line is wrong](https://github.com/stevencohn/OneMore/blob/a25fa7528775d3333e70501effddcc7dc563ea00/OneMore/Commands/Snippets/SaveSnippetCommand.cs#L50)

**Comment by A-Nicoladie** [comment]
Hi !
I am currently encountering the same problem (table border displayed and length changed)

![image](https://github.com/user-attachments/assets/777df71e-18b9-4136-9604-12bc3190e95d)

On top the original model and at the bottom the result of the snippet.

Thanks for all !

---- 
**Config**
- Windows 11 (23H2)
- One More (Version 6.6.1 with OneNote 16.0.18025.20214)

**Comment by stevencohn** [comment]
OneMore "boxes" are just OneNote tables. No magic here. OneNote tables have some limitations and will grow/shrink per their own rules.

**Comment by A-Nicoladie** [comment]
Well... OK. But how do you recreate a "whatever" box, similar to the info box, via a snippet?

The info, notes and warning boxes are always the same lenght and don't display the border of their tables.

![image](https://github.com/user-attachments/assets/95b76ba5-2193-4715-bff4-bcb70e951749)

**Comment by stevencohn** [comment]
They're nested tables. If you place your text cursor inside the snippet, you'll see the Table tab in the ribbon and can turn on the hidden borders for the inner table. The snippet just replicates what you can do manually.

**Comment by A-Nicoladie** [comment]
Yes, I completely agree, and that's precisely my problem → the snippet doesn't exactly reproduce what I did manually.
As you can see in my first example, the table border is displayed and the length has changed compared to the model used to create this snippet.

(_Sorry if I'm not clear in my explanations_ 😅)
