### ISSUE TITLE
Please add a refresh option to Section Table of Contents (TOC)

### ISSUE THREAD

**Issue by JoeKays** [stevencohn/OneMore#1335]
# Problem to Solve
Thanks for adding Section TOC in #56. Unfortunately it seems that there is no way to update an existing TOC when pages are added/removed.

# New Feature/Solution
It would be great to have a refresh button to update the TOC, similar to the one already existing for the Headings TOC within a page.

Thank you so much for your work on this addin, it's great and has already saved me a ton of time and nerves!

**Comment by stevencohn** [comment]
Part 1 implementation completed, added section/notebook refresh and refactored page toc to prepare for part 2.
Part 2 will add more control of page TOC placement, especially when there are multiple outline containers on the page.

A new limitation will be added to restrict page TOCs to exactly one per page.

**Comment by jasonjac2** [comment]
Personally I create new Notebook ToCs and date them, then I can flick back through them over time and see what changed (e.g. copy and paste into excel and do a bit of excel magic) - having a refresh button would be cool as well.

**Comment by stevencohn** [comment]
This new implementation is smart enough to do either. You can add a section and/or notebook TOC page. When you try it again, it will ask if you want to update the existing one or add a new one.
