### ISSUE TITLE
Changing font of selected word with Ctrl+Alt+Shift+# changes entire line

### ISSUE THREAD

**Issue by JohnMarkHowell** [stevencohn/OneMore#1336]
# Problem to Solve

Create a paragraph in OneNote. 
Select a word inside the paragraph.
Use Ctrl+Alt+Shift+7 to change font of the selected word.

Expected:
- Font of selected word is changed and the rest of the paragraph remains in the same font.

Actual:
- Font of the entire paragraph is changed.

# Screenshots

// paragraph with selected word
![image](https://github.com/stevencohn/OneMore/assets/5066153/f70025d3-7ff0-4e5a-88e4-a144819a6cdd)

// What happens when I try to change the font of the selected word
![image](https://github.com/stevencohn/OneMore/assets/5066153/187946da-3557-4f02-9ddd-4a4c63fd80ce)

# Environment (if applicable)
Microsoft® OneNote® for Microsoft 365 MSO (Version 2403 Build 16.0.17425.20070) 64-bit
OS: Windows 11 Major 10, Minor 0, Build 22631, Revision 0

**Comment by stevencohn** [comment]
Styles are set with a type of either Character or Paragraph (or Heading, but that's similar to Paragraph). If the style is set to Paragraph, then regardless of selection, the entire paragraph will be affected when that style is applied. 

If the style is set to Character, then only the selected text is affected within the paragraph, or the entire paragraph is the selection length is zero.

Confirm that the 7th style in your list of custom styles is set to Paragraph or Character.
