### ISSUE TITLE
Add lexers for Json. YAML and Console to colorizer

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#134]
**Is your feature request related to a problem? Please describe.**
Add lexers for Json. YAML and Console to colorizer

**Describe the solution you'd like**
Jason and Yaml are two data structures that are very often seen in code or documentation
It would also be nice to have a terminal colorizer (black background yellow or green foreground with a console font)

**Describe alternatives you've considered**
manual formatting sucks :-)

**Comment by stevencohn** [comment]
JSON is the same as JavaScript so you can choose JavaScript for JSON content

I can ad YAML and... I suppose you mean BATCH script in the DOS console?

**Comment by 1001QAdotNET** [comment]
no, I mean telnet or ssh console

**Comment by stevencohn** [comment]
So something like Linux bash? You can telnet to any OS that has the telnet service running so it could be different languages

**Comment by 1001QAdotNET** [comment]
This could be done via Styles selecting Courier 10pt or Lucida Console 9 fonts with the colors mentioned above.
The problem is that you need to go to the Styles button instead of right clicking and pick the colorizer 
You might not feel like it is saving much but if not for convenience at least it could save a Style slot

**Comment by stevencohn** [comment]
Is the built-in Code style not sufficient?

**Comment by 1001QAdotNET** [comment]
yes that is what I need and instead of Code I should in the header it should be Terminal output
Also when I press that button I would expect the selected lines to be replaced by the snippet and the code inserted in the snippet

**Comment by 1001QAdotNET** [comment]
The things indicated as new in the last release do not show up there
I am not seeing YAML colorizer option and neither the Page context menu... 
I think you linked the previous binaries in this release

**Comment by stevencohn** [comment]
What version is shown on the About dialog?

**Comment by 1001QAdotNET** [comment]
3.11.1

**Comment by stevencohn** [comment]
Oops, forgot to add the yaml files to the Setup project. All set. I added "b" installers to the same 3.11.1 release.

I double-checked the context menus and they're all there. There are two page context menus that show up in the Page navigation panel - the panel that docks to the right side of the OneNote window.

**Comment by 1001QAdotNET** [comment]
Sorry I was calling page context menu the menu that shows up when you right click on the page
I am now realizing that you are talking about the context that shows up when you right click on a page in the page navigation section; I never checked that one not using it much, I will start looking into how I can use these in my workflow

**Comment by stevencohn** [comment]
Thanks. FYI, I do not intend on making those context menus customizable. It was just an opportunity to add OneMore commands where they made sense as a convenience rather than going to the OneMore menu.

**Comment by 1001QAdotNET** [comment]
That is ok for me
I am more interested in the option to register predefined plugin combinations, pair command/ argument, as they show up in the plugin dialog

**Comment by CLITrees** [comment]
Hey Steve thanks for this, I also noticed the change in the way the code snippet works that could get me close to what I needed for console, use a yellow on black style and then use the code snippet, thank you

**Comment by 1001QAdotNET** [comment]
Hey Steve thanks for this, I also noticed the change in the way the code snippet works that could get me close to what I needed for console, use a yellow on black style and then use the code snippet, thank you
