### ISSUE TITLE
Preview Markdown, project NoteWidget integration?

### ISSUE THREAD

**Issue by seaspeak** [stevencohn/OneMore#1341]
# Problem to Solve

Write OneNote with pure Markdown language.
OneNote is adept at messing up font formatting and sizes, and in the end, I can only Ctrl-Alt-0 to restore all the formatting. But doing so also reverts the bold and source code highlighting. Writing markdown in OneNote eliminates worries about formatting issues.

# New Feature/Solution

I found a project NoteWidge, that would open a markdown preview window: https://github.com/efreykongcn/NoteWidget
I stopped using it because it was buggy. But I like the idea a lot.
It also has export functionality, which overlaps with the OneMore functionality.

## Alternative Solutions

# Additional Context

**Comment by stevencohn** [comment]
Added Preview Markdown command to open a new window, showing converted markdown content as OneNote format.
