### ISSUE TITLE
legal considerations

### ISSUE THREAD

**Issue by ankiman1** [stevencohn/OneMore#1343]
Hi, i would like to install the add-in . But i have a question, is it legal (to install the add-in) if I have the One-Note License by the university? 

Sorry for the (probably) dumb question but i do not know if there are some legal terms that forbid to "manipulate" the product that your university give to you.

**Comment by jasonjac2** [comment]
It would only be an issue if your terms and conditions with the university prohibited it, or I guess a law of the country you are in.  Also, if you are installing it one someone elses computer, that may be an issue.  The add-in is open source and free, so I am (not being a lawyer) pretty sure there will be no restrictions from this end.

**Comment by stevencohn** [comment]
Jason is right. Speaking for the add-in itself, it doesn't alter OneNote in any regard. It uses the standard, well-defined plug-in architecture for Office products to register itself as an add-in. So, unless your university has a policy against it, you should be safe.

**Comment by ankiman1** [comment]
Ok, thank you.
