### ISSUE TITLE
Snippet Date (Ctrl+Shift+D) causes OneNote crasch

### ISSUE THREAD

**Issue by seaspeak** [stevencohn/OneMore#1344]
# Problem to Solve
Inserting Date by (Ctrl+Shift+D) into a two row table causes OneNote to crash.

# To Reproduce

1. Insert a two row table
2. Insert the date by Ctrl+Shift+D into the first row
3. insert the date by Ctrl+Shift+D into the second row
4. crash!

# Expected Behavior

No crash

# Screenshots

# Environment (if applicable)

 - OneNote Version: [e.g. Office 2019, O365, also 32bit or 64bit?]
 - OneMore Version [e.g. 3.4 - from the About dialog or from the log file]

# Additional Context

Add any other context about the problem here. Attach page XML file or the app log file as appropriate. You can find the log file here: %localappdata%\temp\OneMore.log

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
Can you please provide a more specific example. I can't repro this.

I simply created a new page, inserted a two-row (one-col) table.
Ctrl+Shift+D in first cell OK
Ctrl+Shift+D in second cell OK

What else do you have on your page? Export the page as a .one file or .xml file and attach it here.

**Comment by seaspeak** [comment]
The table was inserted right after the whole new page created.
It happened randomly. I still can reproduced it once a while, but couldn't find the pattern. I will update if I find anything new.
This reminds me of the same unstable behavior of Ctrl+Shift+V (paste plain text). It also crashes randomly. Also can't restart OneNote without a reboot/sign out.

**Comment by stevencohn** [comment]
Next time it crashes, can you please try to grab %TEMP%\OneMore.log and attach it here?

**Comment by seaspeak** [comment]
I can create one exception, but it is not the crash I mentioned.

The Exception:

The key point is to remove the text input point: 
1. Add a new page.
3. Click the page in the page navigation pane.
4.  3. Click another section and then click the section containing the page.
5.  4. Ctrl+Shift+D.

Again, this is Not what I reported here. Ctrl+Shift+V/Ctrl+Shift+D all causes ramdon crashes. So I thought it might be related to the after-selection or the input focus. This exceptoin is just a sick trial.

[OneMore.log](https://github.com/stevencohn/OneMore/files/15149642/OneMore.log)
![2024-04-29_210407](https://github.com/stevencohn/OneMore/assets/8821870/3eb13db8-6121-4a6f-bdc4-95bf85cef25f)

**Comment by stevencohn** [comment]
Hm, I can't repro that either. This gif shows what I think you outlined above:

![DateStamp](https://github.com/stevencohn/OneMore/assets/9964757/cc1bbd59-e5b0-4259-b777-1abf6f5c8823)

Regardless, I will certainly look into tightening up the code for that command.

**Comment by seaspeak** [comment]
> Hm, I can't repro that either. This gif shows what I think you outlined above:
I missed the step two here. Here is the updated steps, 100% successful:

1. Add a new page.
2. Click the page content/Press Enter (to let the cursor blinking in the page content, not in the title)
3. Click the page in the page navigation pane.
4. Click another section tab and then click the section tab containing the page.
5. Ctrl+Shift+D.

**Comment by stevencohn** [comment]
Like this? Seems to work.

![DateStamp2](https://github.com/stevencohn/OneMore/assets/9964757/4c3eda08-8feb-444d-aacc-760b0b86f822)

**Comment by seaspeak** [comment]
You forgot the step3 "Click the page in the page navigation pane"?

**Comment by stevencohn** [comment]
Yep I did forget that but still...

![DateStamp](https://github.com/stevencohn/OneMore/assets/9964757/56656fb9-1dee-42a9-80e2-0203a721f5f0)

**Comment by seaspeak** [comment]
Notice the difference: I totally get rid of the input cursor before Ctrl+Shift+D.
my Office version is OneNote 2021, is yours 360?

https://github.com/stevencohn/OneMore/assets/8821870/65468993-8a10-40a8-820b-6d7973be16cc

**Comment by stevencohn** [comment]
I have two machines:
* Microsoft® OneNote® 2021 MSO (Version 2403 Build 16.0.17425.20176) 64-bit 
* Microsoft® OneNote® for Microsoft 365 MSO (Version 2402 Build 16.0.17328.20282) 32-bit 

And they both behave the same.

**Comment by seaspeak** [comment]
Mine is Microsoft® OneNote® LTSC MSO (16.0.14332.20678) 64-bit. Yours is newer? But I can't find a new update.

**Comment by stevencohn** [comment]
You can either try updating from the OneNote File/Account menu, or you can try installing [the latest from here](https://onemoreaddin.com/get-started/How%20to%20Install%20OneNote.htm)

**Comment by seaspeak** [comment]
10|10:47:19.906| Running command InsertDateCommand
15|10:47:23.052| ..RPC error, retrying in 500ms
RPC error, retrying in 500ms
System.Runtime.InteropServices.COMException
Message: The remote procedure call failed. (Exception from HRESULT: 0x800706BE)
Description: Unrecognized error code 0x800706BE
ErrorCode: 0x800706BE (-2147023170)
HResult: 0x800706BE (-2147023170)
Source: Microsoft.Office.Interop.OneNote
StackTrace:    at Microsoft.Office.Interop.OneNote.ApplicationClassCOM.GetHierarchy(String bstrStartNodeID, HierarchyScope hsScope, String& pbstrHierarchyXmlOut, XMLSchema xsSchema)
   at River.OneMoreAddIn.OneNote.<>c__DisplayClass52_1.<GetSection>b__0()
   at River.OneMoreAddIn.OneNote.<InvokeWithRetry>d__32.MoveNext()
TargetSite: [Microsoft.Office.Interop.OneNote] Microsoft.Office.Interop.OneNote.ApplicationClassCOM::GetHierarchy()

System.Runtime.InteropServices.COMException
Message: The remote procedure call failed. (Exception from HRESULT: 0x800706BE)
Description: Unrecognized error code 0x800706BE
ErrorCode: 0x800706BE (-2147023170)
HResult: 0x800706BE (-2147023170)
Source: Microsoft.Office.Interop.OneNote
StackTrace:    at Microsoft.Office.Interop.OneNote.ApplicationClassCOM.UpdatePageContent(String bstrPageChangesXmlIn, DateTime dateExpectedLastModified, XMLSchema xsSchema, Boolean force)
   at Microsoft.Office.Interop.OneNote.ApplicationClass.UpdatePageContent_AutoBusyRetry(String bstrPageChangesXmlIn, DateTime dateExpectedLastModified, XMLSchema xsSchema, Boolean force)
   at Microsoft.Office.Interop.OneNote.ApplicationClass.UpdatePageContent(String bstrPageChangesXmlIn, DateTime dateExpectedLastModified, XMLSchema xsSchema, Boolean force)
   at River.OneMoreAddIn.OneNote.<>c__DisplayClass57_0.<Update>b__0()
   at River.OneMoreAddIn.OneNote.<InvokeWithRetry>d__32.MoveNext()
TargetSite: [Microsoft.Office.Interop.OneNote] Microsoft.Office.Interop.OneNote.ApplicationClassCOM::UpdatePageContent()

completed successfully after 1 retries
completed successfully after 1 retries
