### ISSUE TITLE
Problem to Solve: import multiple files

### ISSUE THREAD

**Issue by gikillu** [stevencohn/OneMore#1353]
For [File commands](https://onemoreaddin.com/commands/File%20Commands.htm)
Function: Import MSWord, PowerPoint, Markdown and others into the current page or a new page

I found it that it can only import single file (like *.md) at one time well, but it can not import multiple files at the same time.
Could you consider adding a function about that in the future?

**Comment by stevencohn** [comment]
Duplicate of #1278
