### ISSUE TITLE
Table of contents not working?

### ISSUE THREAD

**Issue by Henk-2001** [stevencohn/OneMore#1354]
# Problem to Solve
Hello! I'm so happy with your add on, but it seems like the Table Of Contents function is not working for me? I want to have a TOC on top of the page that visualizes all headings, with links. But When I try to add it nothing happens? The TOC of the full notebook does work. I tried to change all headings to the specific OneMore headings, but that also doesn't do the trick. I'm a bit new to GitHub so I'm sorry if I am missing some hashtags or something else on this post.

# To Reproduce

1. Go to page with headins 1 and 2. (I numbered the headings with OneMore aswell)
2. Click on 'snippets'
3. Scroll down to and click on 'Table of Contents'
4. Select the first option and "add link". Leave everything else as default.
5. Click "Ok"
6. See error, nothing happens.

# Expected Behavior
Insertion of a TOC with all headings at the top of the page.

# Screenshots
![image](https://github.com/stevencohn/OneMore/assets/145294105/ec71ab0c-152d-4722-b5a3-cf62c7a4252e)

# Environment (if applicable)

 - Microsoft® OneNote® for Microsoft 365 MSO (Version 2401 Build 16.0.17231.20290) 64-bit
 - OneMore Version 6.1.0 with OneNote 16.0.17231.20290

# Additional Context

Add any other context about the problem here. Attach page XML file or the app log file as appropriate. You can find the log file here: %localappdata%\temp\OneMore.log
Here's the log file from just a few seconds ago:
[OneMore.log](https://github.com/stevencohn/OneMore/files/15076836/OneMore.log)

Thankyou a lot!!! :)

**Comment by stevencohn** [comment]
Hi, sorry this is happening. From your log file, it appears that OneMore is trying to set an invalid width to the Outline (the gray box that contains your content). I'm unable to reproduce this myself but I'll look into the code and see if there's a fix I can add.

Meanwhile, you may be able to work around it by adjusting the width of the Outline before adding the TOC. Also, does also fail on on a new page with a couple of simple headings?

**Comment by Henk-2001** [comment]
Hello! 

Thankyou for your (super quick!!) reply. Someeeehow if I make a page in another notebook, the TOC does work...? 

One note styled headings on another page:
![image](https://github.com/stevencohn/OneMore/assets/145294105/bf59a716-0158-45f8-b468-c3c3da0038ab)

I tried copying this page to my currect notebook and the TOC does work, but as soon as I make a new page with headings it doesn't work anymore? It seems like something is wrong with the OneMore styles or something? Because if i only use a few simple OneMore styles, it does work? But as soon as anything else in normal text it doesn't anymore? 

It does recognize it when there are no headings. So that's nice:)
![image](https://github.com/stevencohn/OneMore/assets/145294105/77c2e056-0e3b-464e-adeb-464c0af4565b)

I hope this made sense to you because it does not to me.

**Comment by Henk-2001** [comment]
After some tweaking I figured out it's indeed the page text box size width thing...

Short text works, as long as I do not change the page box size prior to creating the TOC.
![image](https://github.com/stevencohn/OneMore/assets/145294105/3fe52245-c2fd-408a-a63a-756f943aab89)

Longer strings of text (when the initial page box size is changed) prevent the TOC creations. This does not work:
![image](https://github.com/stevencohn/OneMore/assets/145294105/f021e7b8-24d3-47c2-a77c-88beb57cc7c5)
