### ISSUE TITLE
Copy as Text command cann't work now!

### ISSUE THREAD

**Issue by mengxin523** [stevencohn/OneMore#1356]
I set the shortcut to Ctrl+C, it worked fine in the previous version, but it won't work after 6.2! 
Occasionally, but most of the time, you can't paste anything

**Comment by stevencohn** [comment]
Seems to have affected Copy as Markdown as well :-(
Very sorry. I'll look into it asap.

**Comment by mengxin523** [comment]
Oh thank you !
I update the version to 6.2.1 , and this issue is fixed now !!
