### ISSUE TITLE
the plugin will copy the entire page

### ISSUE THREAD

**Issue by mengxin523** [stevencohn/OneMore#1359]
I set copy as a text shortcut, and a lot of times when I copy the header text of the OneNote page, the plugin will copy the entire page, but I just need to copy the header text

**Comment by stevencohn** [comment]
Wouldn't just a normal Ctrl+C work in that case?

**Comment by mengxin523** [comment]
> Wouldn't just a normal Ctrl+C work in that case?

Normal Ctrl+C is working fine, but this is what happens when you Copy As a text

**Comment by stevencohn** [comment]
Ok good. It's a case of "working as designed" doesn't match user expectation. I'll make it match ;)

**Comment by stevencohn** [comment]
Fixed.
* If the cursor is position in the page title or body and the length of the selection range is zero (insertion text cursor) then the entire page is copied
* If content is selected then only that content is copied, regardless of whether it is in the page title or body of the page
