### ISSUE TITLE
A New pane to show TOC as MSWord

### ISSUE THREAD

**Issue by valuex** [stevencohn/OneMore#137]
**Is your feature request related to a problem? Please describe.**
Current TOC for a page is inserted at the page top, which is not convenient for quick navigation, especially for long pages.

**Describe the solution you'd like**
Suggest to add an new pane docked on the right to automatically exhibit the TOC as MSWord style.

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by stevencohn** [comment]
While this is an excellent suggestion, unfortunately there is no way to create a new side panel in OneNote. Sorry.

**Comment by CLITrees** [comment]
how about a pop out window, floating window etc ?

**Comment by valuex** [comment]
In Gem for ONENOTE, there is a pane acting as a pdf viewer. Got no idea how that is implemented. Probably this information would be helpful for you.  Thanks.

**Comment by stevencohn** [comment]
Gem uses SumatraPDF viewer which is a very different thing. There's not much to learn there that OneMore doesn't already do with its own dialogs such as the Search dialog and Tagging dialog that allow you to navigate to found pages by clicking on them from the dialog.

Just in case you didn't notice, the TOC command does let you add a hyperlink next to each heading that jumps back to the top of the page. I know that's not perfect but it's at least a workable alternative. 

Meanwhile, I consider this.
