### ISSUE TITLE
https://onemoreaddin.com/ broken link

### ISSUE THREAD

**Issue by jasonjac2** [stevencohn/OneMore#1376]
# Problem to Solve
https://onemoreaddin.com/

So come along with me on this journey. If you have ideas of how to make OneNote better, how to enhance the knowledge management experience and utility, [let me know](http://127.0.0.1:8080/contact.htm).

Points to: **127.0.0.1:8080/contact.htm**

# To Reproduce

# Expected Behavior

# Screenshots

# Environment (if applicable)

 - OneNote Version: [e.g. Office 2019, O365, also 32bit or 64bit?]
 - OneMore Version [e.g. 3.4 - from the About dialog or from the log file]

# Additional Context

Add any other context about the problem here. Attach page XML file or the app log file as appropriate. You can find the log file here: %localappdata%\temp\OneMore.log

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
Thank you
