### ISSUE TITLE
Is OneMore possible for OneNote Online?

### ISSUE THREAD

**Issue by Cossackx** [stevencohn/OneMore#1377]
# Problem to Solve
- OneMore is amazing and would be incredible to be used on mobile devices. 

Provide a clear and concise description of the problem, e.g. I'm always frustrated when...
- OneNote for Ipad has limited functionality natively but using the onenote.com opens up options. Being able to use OneMore via web would be game changing.

# New Feature/Solution
Add-in vs. Plug-in? I'm unsure if it's even possible. (I'll ask ChatGPT)

Provide a clear and concise description of what you want to happen.

## Alternative Solutions

Provide a clear and concise description of any alternative solutions or features you've considered.

# Additional Context

Provide any other context or screenshots about the feature request here.

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
I have no plans at this time of trying to migrate OneMore functionality to OneNote on the Web. I haven't spent much time researching, but it's my understanding that that would be an entirely new endeavor and very little, if any, could be reused from the OneMore desktop code base.
