### ISSUE TITLE
Dynamic Connectors between Objects/Containers needed

### ISSUE THREAD

**Issue by Cossackx** [stevencohn/OneMore#1378]
# Problem to Solve
Dynamic connectors between containers/objects. In would allow users to connect objects, containers, and embeds similar to Obsidian Canvas, Scrintal, Heptabase, and Miro. This does not even exist in Whiteboard, only Visio.

2011 called. They said they wanted Visio back.

Provide a clear and concise description of the problem, e.g. I'm always frustrated when...
ON has a drawing tool but no connectors between containers/objects. If a container is moved, the line drawing remains static. 

# New Feature/Solution
Dynamic connectors like those in Visio between objects and containers in ON.

Provide a clear and concise description of what you want to happen.
![image](https://github.com/stevencohn/OneMore/assets/121278003/fcad3af2-53ee-4f92-b2a7-48cf2215479b)
![image](https://github.com/stevencohn/OneMore/assets/121278003/6dc2c3c9-5bb4-4936-95cb-0a0a76575085)

## Alternative Solutions
None exists

Provide a clear and concise description of any alternative solutions or features you've considered.

# Additional Context
None exists

Provide any other context or screenshots about the feature request here.

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by Cossackx** [comment]
I used opensourced excalidraw to make this image

**Comment by Cossackx** [comment]
![image](https://github.com/stevencohn/OneMore/assets/121278003/8ca5165e-3de2-4100-b337-bf969ebdd87f)

**Comment by stevencohn** [comment]
Dynamic connectors are not possible in OneNote. It does not have (or at least expose any means to manage) the data structures and UI interactivity necessary to implement them.

Long live Visio!
