### ISSUE TITLE
Install issue.  Screen shot of error message, attached Log and screen shot of ON version #  

### ISSUE THREAD

**Issue by bigbillsds** [stevencohn/OneMore#1383]
Install problem.  Wondering if I need a different one note version?  Does this require the paid version of one note?  Running on Win 11 Pro Laptop. x64 

![image](https://github.com/stevencohn/OneMore/assets/133987502/0d8bfcfd-a436-419a-bc6e-d59a1695b3a1)
![image](https://github.com/stevencohn/OneMore/assets/133987502/09669011-c1b0-4f18-a40c-96389ccd6285)
Log file
[OneMoreSetup.log](https://github.com/stevencohn/OneMore/files/15209980/OneMoreSetup.log)

I read the log, missing quite a few things.  Not sure how to get them and then reinstall.  

Thanks, Bill Connell

**Comment by stevencohn** [comment]
The OneMore installer is reporting that OneNote is not installed on your machine. 

Are you installing over OneNote Desktop edition or OneNote for Windows app? Those are two different products and OneMore only supports the Desktop edition.

**Comment by bigbillsds** [comment]
Ok I am having a hard time figuring out where to get the desktop version.  It seems to say it comes with office 2019, and that is where I believe I installed it from.  I will see what I can do.   Makes no sense there are two versions of the same thing.  Freaking MS.
