### ISSUE TITLE
System.FormatException with Czech locale

### ISSUE THREAD

**Issue by VladanZ** [stevencohn/OneMore#1386]
# Problem to Solve

Cannot insert Snipets when with Czech locale (cs-CZ/cs-CZ), exception thrown:

```
10|11:22:20.660| Running command InsertCodeBoxCommand
10|11:22:20.687| Error running command InsertCodeBoxCommand
10|11:22:20.687| System.FormatException
Message: Vstupní řetězec nemá správný formát.
Source: mscorlib
StackTrace:    v System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   v System.Double.Parse(String s)
   v River.OneMoreAddIn.Commands.InsertBoxCommand.CalculateWidth(XElement cursor, XElement root)
   v River.OneMoreAddIn.Commands.InsertBoxCommand.<Execute>d__6.MoveNext()
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   v River.OneMoreAddIn.Commands.InsertBoxCommand.<Execute>d__6.MoveNext()
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   v River.OneMoreAddIn.CommandFactory.<Run>d__5.MoveNext()
TargetSite: [mscorlib] System.Number::ParseDouble()
``` 

# To Reproduce

1. set Windows region to Czech (cs-CZ/cs-CZ locale)
2. Insert Code Box or Text Box from Snipets menu

# Expected Behavior

Code Box or Text Box inserted instead of System.FormatException

# Screenshots

# Environment (if applicable)

```
01|11:13:15.168| Starting dllhost 79896, 4701 Mhz, 31 MB, cs-CZ/cs-CZ, v6.3.0, OneNote 15.0, Office 16.0, 2024-05-06 11:13
01|11:13:15.169| ..Windows 11 Professional, Version 23H2, Build 22621, 64 bit
01|11:13:15.180| ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.17425.20176)
01|11:13:15.190| ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
```

**Comment by stevencohn** [comment]
Appears that it might only be a problem when adding a Box inside of a table. 
A workaround might be to create the box outside of a table and then cut/paste that box into the table.
Will be fixed in the next release.

**Comment by VladanZ** [comment]
> Appears that it might only be a problem when adding a Box inside of a table. A workaround might be to create the box outside of a table and then cut/paste that box into the table. Will be fixed in the next release.

For me the same exception is thrown in empty document without any table. Placing cursor in a an empty note and clicking Snippets / Code Box or Text Box. I did not try putting Snippet inside of a table.

**Comment by stevenmcohn** [comment]
Should be fixed. No problem.
