### ISSUE TITLE
Timer window doesn' t show

### ISSUE THREAD

**Issue by Adlsr** [stevencohn/OneMore#1388]
# Problem to Solve

Timer window is not showing

# To Reproduce

1. Go to 'Plus → Extra'
2. Click on 'Start timer'
3. See that nothing happen

# Expected Behavior

The timer window should show in the top right corner

# Environment (if applicable)

 - OneNote Version: O365, V 2403 Build 17425.20176
 - OneMore Version 6.3.0

# Additional Context

In the log, this is what i see : 

```
05|12:42:37.565| SaveToMRU skipping TimerWindowCmd, method not found
20|12:45:46.591| Running command TimerWindowCommand
20|12:45:46.721| SaveToMRU skipping TimerWindowCmd, method not found
20|12:45:49.072| Running command TimerWindowCommand
20|12:45:49.084| SaveToMRU skipping TimerWindowCmd, method not found
05|12:45:52.885| Running command TimerWindowCommand
05|12:45:53.016| SaveToMRU skipping TimerWindowCmd, method not found
05|12:46:22.981| Running command TimerWindowCommand
22|12:46:23.646| SaveToMRU skipping TimerWindowCmd, method not found
05|12:48:16.415| Running command AboutCommand
```

Thank you for your help !
[OneMore.log](https://github.com/stevencohn/OneMore/files/15234451/OneMore.log)

**Comment by stevencohn** [comment]
Hi, Sorry it's not working for you. Were there other things going on before this? Is there something higher up in the logs?

The "method not found" errors, while wrong and are something I need to fix, actually only run _after_ the timer command completes. So there may be something else interfering.

**Comment by stevencohn** [comment]
![z](https://github.com/stevencohn/OneMore/assets/9964757/dfc26fe0-80bc-4022-8de8-0ef68fd671e9)

**Comment by stevencohn** [comment]
I found a machine where I can reproduce this. Thanks. I'll investigate.

**Comment by Adlsr** [comment]
Thank you :)
