### ISSUE TITLE
Small question

### ISSUE THREAD

**Issue by aap4ixx** [stevencohn/OneMore#14]
Hi,

1) Big thanks for you example. It is work.
2) Can you write small manual, I do not understand how I can run debug mode to debug code. At this moment studio config only DLL. but i not understood ho i can run normal debug for it.

**Comment by stevencohn** [comment]
Actually, there is a small note in the readme under the OneMoreAddin subfolder that explains the easiest way to debug is to add the System.Diagnostics.Debugger.Launch() command into the code where you want it to break. This will cause VS to load the "attach debugger" dialog.

**Comment by aap4ixx** [comment]
Yes thanks, i found it.

But if i use  System.Diagnostics.Debugger.Launch(), opening new studio :(

**Comment by stevencohn** [comment]
Isn't there a checkbox for that somewhere? I thought when the dialog opens, you can choose to use existing or open new?

**Comment by aap4ixx** [comment]
Every time open new example of visual studio. But i thing first i need again all recheck. And i will write you later.
Thanks for your assist.

**Comment by stevencohn** [comment]
This should just be a Visual Studio setting. I'm closing this because there's nothing I can do about someone's environment.
