### ISSUE TITLE
Odd hashtag search results

### ISSUE THREAD

**Issue by cspotcode** [stevencohn/OneMore#1405]
# Problem to Solve

Adding hashtags, searching for pairs of hashtags, and re-scanning while re-submitting my search query to see updated results, seems to get search results into a confusing state.

I've created 4 lines with different combinations of hashtags on a page, shown in screenshot below.  At first I tried searching for `#foo #bar` to verify that search would *only* show me the line with both hashtags, not the lines with a single hashtag.

Then I added the line with `#baz`, re-ran the scan, and searched for `#baz`.  This screenshot shows the search results.  The red arrows show which paragraph is highlighted when clicking each search result.

# To Reproduce

1. Add to a document:
```
#foo
#bar
#foo bar
```
2. Scan for hashtags.
3. Search for `#foo #bar`
4. Append to document:
```
#baz
```
6. Scan for hashtags.
7. Search for `#baz`

# Expected Behavior

I was hoping that searching for `#foo #bar` would show a single search result: the paragraph with both hashtags #foo and #bar.

I expected that searching for `#baz` would show a single search result: the paragraph with the hashtag #baz.

I expected that the hashtags shown in search results would match those on the page.  But instead I see the link to the `#bar` paragraph showing `#foo #bar` in the search results pane.

# Screenshots

![image](https://github.com/stevencohn/OneMore/assets/376504/495e2054-42fc-4d3f-8212-f30eabc51e6f)

# Environment (if applicable)

 - OneNote Version: O365 64bit 16.0.17531.20152
 - OneMore Version 6.3.1

# Additional Context

Add any other context about the problem here. Attach page XML file or the app log file as appropriate. You can find the log file here: %localappdata%\temp\OneMore.log

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by cspotcode** [comment]
This might be two bugs in one issue, and sorry the issue title isn't more descriptive, I wasn't entirely sure how to describe this behaviour.

**Comment by stevencohn** [comment]
I'm unable to reproduce the mix-matched links to paragraphs but otherwise, it's working as intended.

Hi. Hashtags and searching for them is described [on the onemoreaddin.com wiki here](https://onemoreaddin.com/commands/Search%20and%20Tag%20Commands.htm).

Search for `#foo #bar` is the same as `#foo and #bar`. You can use the `or` operator as well.

When it finds a page with your hashtags, it will also show all other hashtags on that page. It highlights direct hits in blue and "other" hashtags in gray, making it easy to find associations.

**Comment by stevencohn** [comment]
Hi @cspotcode, aside from possibly being able to order the sub-results better (showing inline sub-results in document-order), I'm unable to reproduce what you show in your screenshot - multiple sub-results of "#foo #bar" pointing to lines that don't have either #foo or #bar.

<img width="252" alt="image" src="https://github.com/user-attachments/assets/8f016dc7-aca4-49e3-94bd-4ce9b31b54ee">

Please let me know if this is still an ongoing issue or if you have further steps that might help clarify how to reproduce. Thanks!

**Comment by cspotcode** [comment]
Thanks, I'm not sure how it happened, I think I was manually triggering the
hashtag reindex a lot while I was experimenting, so maybe I got the indexer
into a weird state.  I haven't been using the hashtag feature lately and
don't think I'll have time to attempt another reproduction.  We can close
this if you want.  Thanks again for taking a look.

**Comment by stevencohn** [comment]
I'll keep it open to look into the ordering of sub-items. Thanks!
