### ISSUE TITLE
Sort Notebook Sections by Date Created

### ISSUE THREAD

**Issue by flannan-h** [stevencohn/OneMore#1406]
# Problem to Solve

For running, chronological daily/weekly notes (say where one section = 1 unit of time), there does not seem to be an easy way to sort sections by date created. The only solution on [Microsoft docs](https://support.microsoft.com/en-us/office/rearrange-section-tabs-and-page-tabs-in-onenote-for-windows-92edb8cf-eee3-4310-b85f-06e1c25ab79f) seems to be manually dragging sections notes around within the notebook UI or file explorer - which becomes when attempting to organize for years worth of notes.

# New Feature/Solution

OneMore's sort functionality for includes sorting by Name and Date Modified. If it's possible and useful to others, adding sort functionality for Date Created would be awesome! 

![image](https://github.com/stevencohn/OneMore/assets/48101853/3e849f2d-56b3-416d-9621-6f4a637acd21)

Apologies if there is a duplicate request out there. And thanks for building/maintaining a very useful tool!

--Flannan

**Comment by stevencohn** [comment]
OneNote does not retain the creation date of sections. That's why that option is grayed out.

**Comment by flannan-h** [comment]
Thank you for the quick response, @stevencohn! Makes sense then re: inability to filter on creation data.

I'll probably make a one-off script for my use case based on each file's ctime (creation time for path on Windows OS). This code excerpt is in Python, but wonder if [File.GetCreationTime()](https://learn.microsoft.com/en-us/dotnet/api/system.io.file.getcreationtime?view=net-8.0) could be used in C#

```
import os.path
import datetime as dt

createDate = os.path.getctime('10-18.one')
createDate_dt = dt.datetime.fromtimestamp(createDate)
print(createDate_dt)

2021-10-17 16:14:05.869137
```


Cheers,
Flannan

**Comment by stevencohn** [comment]
That would work, you could also use OneMore's plugin capability. See [bottom of this page](https://onemoreaddin.com/commands/File%20Commands.htm). Basically, it hands you XML, you much around with it, and then give it back to be saved on your behalf.

Another alternative is to prefix each section name with a date stamp yyyy-mm-dd making it sortable by name.
