### ISSUE TITLE
Find Tag Page Operation Corrupted

### ISSUE THREAD

**Issue by toppinglift** [stevencohn/OneMore#1408]
Find Tagged Page worked properly before update to release 6.3.1  After downloading and installing new release, Find Tagged Page would not find specified tags, instead giving unfiltered response of all the pages in the Section/Notebook

# To Reproduce

1. Go to Search and Tag--->Find Tagged Pages--->Select Tag---Search

# Expected Behavior:

Call up of pages which contained that tag.  When pages begin to appear, the text in the lower window appears to overwrite itself dozens of times confining the text to one line (which you cannot read) and then it expands properly and becomes readable 

# Screenshots
![image](https://github.com/stevencohn/OneMore/assets/63881713/21e5903f-1f67-4a8b-a4a3-55c26f7bee50)
![image](https://github.com/stevencohn/OneMore/assets/63881713/02ac511d-d01a-474c-8ef0-94780589b588)

# Environment (if applicable)

 - OneNote Version: Microsoft® OneNote® for Microsoft 365 MSO (Version 2404 Build 16.0.17531.20152) 64-bit 
 - OneMore Version: 3.6.1

**Comment by stevencohn** [comment]
Page tags are deprecated and it is highly recommended that you upgrade page tags to Hashtags. This was explained in the [release notes for 6.2.1](https://github.com/stevencohn/OneMore/releases/tag/6.2.1) and [on the wiki](https://onemoreaddin.com/commands/Search%20and%20Tag%20Commands.htm).

The problem that you mention above is one of the reason page tags is being deprecated and will be removed in a future version of OneMore. No page tags will be lost; they will all be converted to #hashtags and you'll be able to find the using the new Find Hashtags command.
