### ISSUE TITLE
Action chaining or workflows based on OneNote and OneMore actions (record a macro?)

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#141]
**Is your feature request related to a problem? Please describe.**
I need to execute multiple actions in sequence to bring the text to the format I need

**Describe the solution you'd like**
I would like to be able to predefine sequences like this
With the selected text to the following:
-remove spaces and empty lines
-reduce the paragraph spacing to 0 (in my case) 
-indent the paragraphs marked (outline formatting)

or
apply a custom style to the text
make that a code snippet
remove character X and replace Y with Z 

Recording a macro of actions and applying that to the selected text would probably be ideal

(this will probably take OneMore/OneNote to the next level of productivity up :-) )

**Comment by stevencohn** [comment]
may be possible to combine OneMore commands but I have no way of invoke built-in OneNote commands

**Comment by 1001QAdotNET** [comment]
worst case: I could use https://www.autohotkey.com/ which I am familiar with

**Comment by stevencohn** [comment]
I could emit key sequences easy enough - I already do this for the Paste RTF command. I'll play, but no promises....

**Comment by G2G2G** [comment]
Add me to the list of people who’d love the ability to chain link OneMore commands, perhaps with some user variables. The more I use this add in the more I appreciate its functionality.
