### ISSUE TITLE
Resize all images "larger than"

### ISSUE THREAD

**Issue by Adlsr** [stevencohn/OneMore#1413]
# Problem to Solve

Can't Resize all image "larger than" a number of pixel to the specified pixel number

# New Feature/Solution

Resize all image larger than NNNpx to NNNpx.
NNN being a pixel number you can set by default or adjust it when using the functionality if needed

# Additional Context

I use another addon's macro that gives me a dialog box where i can chose a width or height to resize all the image larger than this width/height to the specified width/height.

This functionality is important for me because i do tutorial with screenshots all day, and i always resize the screenshots larger than 800px to 800px to fit Email viewed on laptops. I thought that it could be useful to add it.

I'm currently testing OneMore and didn't find such a functionality.

Thank you in advance for considering this request.
Hope it is not to complicated.

**Comment by stevencohn** [comment]
OneMore does have such functionality. First, select two or more images or ensure no images are selected to consider all images in the page. In the OneMore menu, under Images, and then Resize and Adjust.

Once the dialog is opened, you'll see _Constraint_ field at the top.

**Comment by Adlsr** [comment]
Hi, thank you for aswering.

Sadly, i don't see any _Constraint_ field as you can see on the screenshot below :

![image](https://github.com/stevencohn/OneMore/assets/131651168/e56e10d2-914d-4fb4-b29b-a3d640bec966)

**Comment by stevencohn** [comment]
You _must_ select two or more images - or - you _must_ have two or more images on the page and ensure that _none_ of them are selected. 

The dialog you show above is displayed when working against a single image. When you're working against multiple images, this is shown:

<img width="268" alt="image" src="https://github.com/stevencohn/OneMore/assets/9964757/bc3e1309-3fd3-4f2a-8f7a-ef35fde15e74">

**Comment by Adlsr** [comment]
Ho, right, i didn't saw that !  
Sorry for wasting your time

Thank you very much for your help.

**Comment by stevencohn** [comment]
No worries. Glad I could help.
