### ISSUE TITLE
Is it possible for OneMore to be an “Add-on?” (MS Store)

### ISSUE THREAD

**Issue by Cossackx** [stevencohn/OneMore#1417]
# How can I help you?
![IMG_2267](https://github.com/stevencohn/OneMore/assets/121278003/ce19dd16-102d-427f-a25e-a9599dca2aa8)

Is it possible for OneMore to be in the Add-On “Store?” If so, wouldn’t OneMore then be available on any platform, I.e. iOS?

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by Cossackx** [comment]
That's the beauty of it. When using onenote.com there is no Mac vs. ios vs. Windows. It's all web based which supports the MS appstore add-ons.

**Comment by stevencohn** [comment]
Sorry, you're right. But again, that's a completely new add-in, a new rewrite.
