### ISSUE TITLE
Search and Replace using regular expressions ?

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#142]
**Is your feature request related to a problem? Please describe.**
I need to replace a certain marker (ex 📖) with the same + "\n" 
**Describe the solution you'd like**
I would like to be able to replace text with text plus the symbols that are not visible like "\n" or "\r"
If possible using regular expression would be great but I might be asking for too much
**Describe alternatives you've considered**
N/A

**Comment by 1001QAdotNET** [comment]
were you already working on this ? Cool!

**Comment by stevencohn** [comment]
It's quite easy to replace "\n" with '\n'. I'm not sure other sequences make sense though.

**Comment by 1001QAdotNET** [comment]
I want to add a line break after a marker like 📖

**Comment by stevencohn** [comment]
Sorry, what is that marker? How did you add it?

**Comment by 1001QAdotNET** [comment]
Tagging paragraphs that contain a marker or a keyword would also be cool
I am using ditto and shortcuts and predefined "Quick paste"

**Comment by 1001QAdotNET** [comment]
Using these http://www.alanwood.net/demos/webdings.html

**Comment by stevencohn** [comment]
yeah, no problem. still wicked easy

**Comment by 1001QAdotNET** [comment]
no the other regex things are not that much needed
if I get there I will use a plugin script for that

**Comment by 1001QAdotNET** [comment]
This works thank you for this new release
Re: uploading this to github-it is doable via the plugins so not a problem
