### ISSUE TITLE
can not use one more in onenote2016

### ISSUE THREAD

**Issue by kiko1412** [stevencohn/OneMore#1426]
# Problem to Solve

when i install one more，there is no plug in onenote2016
![image](https://github.com/stevencohn/OneMore/assets/150658170/f25efdc5-e335-4e6f-ba7e-8ae451be2b5d)

# To Reproduce

1. install one more 
2. open onenote 

# Expected Behavior

one more is working in onenote

# Screenshots

# Environment (if applicable)

pc environment：
![image](https://github.com/stevencohn/OneMore/assets/150658170/f64a66e8-7a43-48f2-8c75-a9e2b1503ffc)

![image](https://github.com/stevencohn/OneMore/assets/150658170/811d9ad6-8b13-497c-9961-62d9219744a8)

![image](https://github.com/stevencohn/OneMore/assets/150658170/1222a24a-d853-427a-be09-893b84afe694)

# Additional Context

[OneMore.log](https://github.com/user-attachments/files/15613649/OneMore.log)

**Comment by stevencohn** [comment]
I'm very sorry but my only guess is that you're in China, where maybe(?) TPM2.0 encryption chips are not allowed by the US government. This might be why you're seeing exception like this in your log file, mentioning FIPS and Cryptography services

```
System.Reflection.TargetInvocationException
Message: 调用的目标发生了异常。
Source: mscorlib
StackTrace:    在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Object[] args)
   在 System.Security.Cryptography.MD5.Create()
   在 River.OneMoreAddIn.Models.Page.ComputeHashes(XElement root)
   在 River.OneMoreAddIn.Models.Page..ctor(XElement root)
   在 River.OneMoreAddIn.OneNote.<GetPage>d__48.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 River.OneMoreAddIn.OneNote.<GetPageInfo>d__51.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 River.OneMoreAddIn.Commands.NavigationProvider.<Resolve>d__17.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 River.OneMoreAddIn.Commands.NavigationProvider.<Resolve>d__17.MoveNext()
TargetSite: [mscorlib] System.RuntimeMethodHandle::InvokeMethod()
  -- inner exception at depth 1 ---------------
  Message: 此实现不是 Windows 平台 FIPS 验证的加密算法的一部分。
  Source: mscorlib
  StackTrace:    在 System.Security.Cryptography.MD5CryptoServiceProvider..ctor()
  TargetSite: [mscorlib] System.Security.Cryptography.MD5CryptoServiceProvider::.ctor()
```

And, if this is the case, I'm not sure I have a workaround. I suspect you will not have any luck regardless of the version of OneNote.

**Comment by stevencohn** [comment]
While investigating #1428, I learned that some computers have a FIPS Registry setting enabled even though the computer chips don't allow FIPS algorithms.

So here's the same comment I added to $1428

Please check the Enabled property under this Windows System Registry key:

`HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa\FipsAlgorithmPolicy`

1. Close OneNote
2. Set the Enabled property to 0
3. Restart OneNote
4. Try commands

**Comment by kiko1412** [comment]
i have tried the way，it works，thank you！！
