### ISSUE TITLE
"Unable to create a Bidirectional link"

### ISSUE THREAD

**Issue by yjcaaaaaaaa** [stevencohn/OneMore#1427]
# Problem to Solve

 "Unable to create a Bidirectional link"

# To Reproduce
![image](https://github.com/stevencohn/OneMore/assets/143862871/8f1bee0a-1886-401f-ad76-4ce445a09703)
which has been mentioned in #1424 often Bidirectional linking errors, is the superscript not able to be used as a starting anchor? The superscript link in the diagram is actually a bit wrong, the superscript first needs to be on a single line to execute the Bidirectional linking correctly, I first linked, and then deleted the line, but then the connection can't come back
![image](https://github.com/stevencohn/OneMore/assets/143862871/bf9de7a5-33ba-4ec4-8c1e-a4256cb0dfdc)
Not only that, for example, the other one in the diagram cannot execute the Bidirectional linking command, it is just a random number of characters

# Expected Behavior

# Screenshots

# Environment (if applicable)

 - OneNote Version: [e.g. Office 2019, O365, also 32bit or 64bit?]
 - OneMore Version [e.g. 3.4 - from the About dialog or from the log file]

# Additional Context

Add any other context about the problem here. Attach page XML file or the app log file as appropriate. You can find the log file here: %localappdata%\temp\OneMore.log

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
Getting closer, although certainly not perfect. Needed to make concessions around which OneMore windows can be properly TopMost window, meaning the Navigator window can no longer be TopMost??

**Comment by stevencohn** [comment]
There are two separate problems here.

The first problem, linking between two paragraphs from superscript text is fixed and will be available in the next release.

The second problem involves concatenated text consisting of multiple languages. Although you may select only part of the string, OneNote seems to have a bug in that it's telling OneMore that the entire paragraph is selected. There's nothing I can do to fix that use case.
