### ISSUE TITLE
GIF Support in OneNote

### ISSUE THREAD

**Issue by Nutpsy** [stevencohn/OneMore#1430]
Hi, could you consider adding support for displaying GIFs in OneNote through OneMore? It would be a great enhancement.

Thank you!

**Comment by stevencohn** [comment]
OneMore provides a way of manipulating OneNote content; it is limited by the OneNote data models so can't do anything that OneNote can't do natively.

A best alternative is to attach the GIF as a link, then you can open it up in the browser by double-clcking.

**Comment by Nutpsy** [comment]
> OneMore provides a way of manipulating OneNote content; it is limited by the OneNote data models so can't do anything that OneNote can't do natively.
> 
> A best alternative is to attach the GIF as a link, then you can open it up in the browser by double-clcking.

Thank you！
