### ISSUE TITLE
[Feature request] Dynamic linking in OneNote template

### ISSUE THREAD

**Issue by bangwoo4** [stevencohn/OneMore#1431]
# Problem to Solve

When using the **"Copy link to paragraph"** function to link items in the current section, then export the current section as a template, other sections created from that template will have links leading to the original section instead of themselves. 

# New Feature/Solution
Can you make the address in the link to instead point to the first address (which is in the section that makes up the template), it will point to the newly created section (the section to which the template is applied)?

For example: I have a section "a":
_<1>
...
<1/>_
Then export section "a" as a template.

Then I create a section "b" and apply that template, then section "b" will also have the form
_<1>
...
<1/>_
But when clicking "<1> in section b, instead of pointing to "<1/> in section b itself, it points to <1/> in section a. Is it possible to make it point to section b and not to the original section?

**Comment by stevencohn** [comment]
I do not think this is possible. OneMore does _add_ anything to OneNote that OneNote can't already do. It just makes things easier, automated. In this case, any links on a page to another page is implemented by OneNote as a standard absolute URI - similar to a full https Web URL. These URIs cannot be relative.
