### ISSUE TITLE
How can I help with translations?

### ISSUE THREAD

**Issue by luaotix** [stevencohn/OneMore#1434]
I recently discovered OneMore and I really like it. 

I noticed that it comes with a Chinese translation, making it more convenient to use. However, I have noticed that the Chinese translations seem to be machine-generated and have some errors. 

I am willing to help improve the translation. Can you please let me know how I can help with the translation process?

**Comment by stevencohn** [comment]
Instructions [are here](https://onemoreaddin.com/developers/Language%20Translations.htm). The [Chinese hints file is here](https://github.com/stevencohn/OneMore/blob/main/OneMore/Properties/Resources.zh-CN-hints.xml). Thank you.
