### ISSUE TITLE
#Tagging Pages - Setting, Searching and Maintaining whole Page #Tags to Aid Information Management

### ISSUE THREAD

**Issue by martin-dunban** [stevencohn/OneMore#1435]
# Problem to Solve

This feature request proposes improvement of the current functions for setting and searching #Tags to enable the easy identification, setting and searching of previously used #Tags. 

The present (soon to be deprecated) Page Tagging feature provided a powerful feature for setting and searching Tags for whole  OneNote pages. This is a useful feature for overall Information Management of OneNote book content. One of the key features of the previous Page Tagging feature was the the display of a pop-up panel showing already used/recently used Page Tags from which Page Tags could be selected and new Tags set. This aided easy identification and selection of previously used Page Tags so ensuring a consistency in setting of subject tags across different pages and a mechanism for identifying Page Tags for searching.

# New Feature/Solution

It is proposed that the #Tag feature for setting #Tags should be extended to include a pop-up information panel  showing previously used #Tags.

To aid searching #Tags it is proposed that when initiating a search a pop-up panel should be displayed showing previously used #Tags from which those #Tags to be searched can be selected.

## Alternative Solutions

AFAIK there is no existing functionality within OneNote or currently avaiable functionality in OneMoreAddIn that would fulfil this requirement.

**Comment by stevencohn** [comment]
An "Insert Tag" dialog box is certainly possible for the next release.

Note that the Find Hashtags dialog already includes a popup with known hashtags as shown here

<img width="499" alt="image" src="https://github.com/stevencohn/OneMore/assets/9964757/ab117445-fb21-4ce2-9702-b6005c45b71a">

**Comment by martin-dunban** [comment]
Thanks Steve. Yes, I picked up the list available when searching hashtags. When setting a #tag it would be useful to have a page showing already used #tags enabling. This would help in ensuring consistency of tags across pages when coding new page content. I think this feature was partially available in the old 'page tagging' function?

**Comment by stevencohn** [comment]
Prototype:

<img width="341" alt="image" src="https://github.com/user-attachments/assets/1c36f38f-03da-48ae-9508-4e24fb77c55f">

**Comment by Meh-S-Eze** [comment]
Would it be possible to make the Find Hashtags box look/function more like the new create hashtags dialogue box.

**Comment by stevencohn** [comment]
Can you ask that in a new ticket please?

**Comment by Meh-S-Eze** [comment]
Will do.

**Comment by Gr-Nobel** [comment]
@stevencohn is this issue fixed?
please push the next update solving this issue. 
![image](https://github.com/user-attachments/assets/2757d037-17ff-46be-8e24-40d7798d8656)

**Comment by stevencohn** [comment]
It will be fixed in the next release. There is another critical issue I'm try to fix as well. Next week or two. Apologies for the delay.
