### ISSUE TITLE
Feature Request - add the ability to always use a specific template (custom template) for notebooks and partition groups.

### ISSUE THREAD

**Issue by ningdu0** [stevencohn/OneMore#1436]
# Problem to Solve

In Insert>>Page Templates>>Always use a specific template (Custom Templates) option, you can only use templates for partitions, and you have to reset the template every time you create a new partition.

# New Feature/Solution

In Insert>>Page Templates>>Always use a specific template option, add the ability to always use a specific template (custom template) for notebooks and partition groups.

**Comment by stevencohn** [comment]
As far as I know, there is no way to control this other than through the OneNote Templates side panel. The technical details of this  feature seems to be undocumented.

You can set the default, per section, to any existing template, either custom or predefined.

**Comment by ningdu0** [comment]
> As far as I know, there is no way to control this other than through the OneNote Templates side panel. The technical details of this feature seems to be undocumented.
> 
> You can set the default, per section, to any existing template, either custom or predefined.

Okay,thanks for your reply!
