### ISSUE TITLE
Add a command launcher input box to find and excute command quickly

### ISSUE THREAD

**Issue by valuex** [stevencohn/OneMore#144]
**Is your feature request related to a problem? Please describe.**
In office 365, there is a search edit input that locates at the center of the title bar.  
User can input the command name, then hit enter to excute corresponding command.
Hope OneMore can add such a feature.
The other reason I raise this feature request is that  there is no such search input box in OneNote 2016, and in office 365, the search box can NOT find the commands implemented by OneMore.

**Describe the solution you'd like**
- It'd be better that the searching behavior likes launchers, i.e., can find commands by inputing limited letters and can recoord user's high-frequecy commands
- The command search box can indexing the OneNote commands

**Describe alternatives you've considered**
/

**Comment by stevencohn** [comment]
sorry not possible

**Comment by 1001QAdotNET** [comment]
run a plugin can be leveraged for that with no modifications
