### ISSUE TITLE
Duplicate Page command started giving error

### ISSUE THREAD

**Issue by ykurji** [stevencohn/OneMore#1445]
# Problem to Solve
The duplicate page command was working fine and has recently started giving error. It create the new page but doesn't duplicate the contents to the new page.

# To Reproduce

Not sure about the exact steps to reproduce as it just started happening one day. I am a frequent user of this command. Here is the screenshot of the error:

<img width="378" alt="dllhost_2024June30_410" src="https://github.com/stevencohn/OneMore/assets/140761612/202b9438-8572-4262-b7de-41cd231c8c22">

Here are the relevant error logs:

`14|10:22:18.496| System.ArgumentNullException
Message: Value cannot be null.
Parameter name: input
Source: System
StackTrace:    at System.Text.RegularExpressions.Regex.Match(String input)
   at System.Text.RegularExpressions.Regex.Match(String input, String pattern)
   at River.OneMoreAddIn.Commands.DuplicatePageCommand.SetUniquePageTitle(XNamespace ns, XElement section, Page page)
   at River.OneMoreAddIn.Commands.DuplicatePageCommand.<Execute>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at River.OneMoreAddIn.Commands.DuplicatePageCommand.<Execute>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.CommandFactory.<Run>d__6.MoveNext()
TargetSite: [System] System.Text.RegularExpressions.Regex::Match()`

# Expected Behavior

An exact duplicate page will be created with the contents copied.

# Environment (if applicable)

 - OneNote Version: O365, Version 2405 (Build 17628.20144)
 - OneMore Version: Version 6.4.0 with OneNote 16.0.17628.20144

**Comment by ykurji** [comment]
Restarting the system completely resolved this issue. I'm still not sure why this started happening in the first place.

**Comment by stevencohn** [comment]
Hi. Could you please provide the full title of the page that you're trying to duplicate where this error occurs. It's failing trying to parse the page title so it can generate a new uniquely numbered page title. Thanks.

**Comment by ykurji** [comment]
Ah, you are correct. I had the page title hidden (Review -> Hide Page title) because I did not need that field in my notes. So, there was no entry in the page title field. When I enabled it, it created a duplicate page successfully.

I suppose this can be easily fixed.

**Comment by stevencohn** [comment]
I was able to fix the command so that it will duplicate a page with a hidden title. However, the caveat is that the duplicate page will have a visible title. The OneNote API does not let me create the title block of a page.

**Comment by ykurji** [comment]
Thank you :)
