### ISSUE TITLE
Release Notes - Section for "experimental features"

### ISSUE THREAD

**Issue by jasonjac2** [stevencohn/OneMore#1447]
# Problem to Solve
I was just in settings and noticed a new checkbox - experimental features.  I checked it :-).  But I don't know what the experimental features are in this release. 

# New Feature/Solution

Add a new sections to the release notes.

## Alternative Solutions

Add in a popup when you hover / click the checkbox.

# Additional Context

Provide any other context or screenshots about the feature request here.

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
At the moment, this enables two small things. It shows the SQL used to search for hashtags and adds the ability to search/replace raw XML in the Search and Replace dialog.

_I DO NOT ADVISE USERS TO ENABLE THE EXPERIMENTAL FEATURE AT THIS TIME. I do not guarantee they work or won't lose data!

**Comment by stevencohn** [comment]
Closing this for now. I will add a section to the Release Notes when there are experimental features that I want the public to know about and try. Currently, everything is diagnostic or high risk (internal, just for me)

**Comment by stevencohn** [comment]
https://onemoreaddin.com/developers/Experimental%20Features.htm
