### ISSUE TITLE
Table of Content - index of Sections / Index of Pages - Add Created, Last  Modified, Last Visited as options

### ISSUE THREAD

**Issue by jasonjac2** [stevencohn/OneMore#1448]
# Problem to Solve
I do a ToC of all my notebooks (all 10K pages) every month.
I take these ToCs and load them up into a spreadsheet for ultimate filtering and housekeeping workflows.
I would like to be able to know how "fresh" the pages are.
Adding an optional bit onto the links to each page would aid this:
C: <date> M: <Date> LV:  <Date>
They could be persistent checkboxes in the ToC dialogue so I can set and forget them.

Icing on the cake would be able to run one command to do all this for all my notebooks, which would save me 15 mins a month.

**Comment by stevencohn** [comment]
How about just an option on the Table of Contents dialog to export directly to Excel, and not generate a new page at all? Or do you want both?

**Comment by jasonjac2** [comment]
It would be great for it to go directly to Excel.  I would probably still produce the ToC's as pages monthly as we often jump into them when working.  But... yes, saving directly to Excel would be amazing, especially if you can have some way of conveying the Section Group / Section / Page / Sub Page as well.  Currently I just reply on the indentation, but it can be a bit inconsistent.

So you would be adding columns for the additional data items?

Thank would be great and I would use that a lot.

Tangent: the final piece for me is my concept of parent - which is distinct (although often aligned) with the actual notebook layout. i.e. every page should have a parent and we denote that by the first line of the first container being "parent:" ><link to page>

**Comment by jasonjac2** [comment]
Do you think you will do the Excel version?

How close are you to a release :-). ?

The Excel option would be even better if it could be a OneMore: link as well, so you can do the command and in the command have a "copy command with settings", then I can paste it into a page OR any other editor I have and it would be one click.
I realise allowing oneMore: commands comes with a bit of a risk, but I would be happy for them to be extended OR maybe have a file with allowed ones that you can turn on / off.

Examples: "Search for a specific  hasthag" & create a page with the results.
Resize and adjust all images on this page to these constraints

**Comment by stevencohn** [comment]
Hi @jasonjac2. It seemed correct to implement this as a plugin. I've extended the capabilities of the OneMore Plugin feature to accommodate this, adding new hierarchy scopes and a user arguments field where you can specify the output path. It will look like this:

<img width="406" alt="image" src="https://github.com/user-attachments/assets/48cbaa20-5fed-47c0-a16c-9b0ddc65b112">

Running this plugin will create an Excel .CSV file with the columns

`Notebook | Section | Page | Created | Modified`

Note, OneNote doesn't keep track of lastViewed; the script could be enhanced to incorporate info from Navigator.json but that was a bit of a stretch for this exercise; I hope you don't mind.
