### ISSUE TITLE
Hashtags not discovered in shared notebooks if scanned during initial sync

### ISSUE THREAD

**Issue by jasonjac2** [stevencohn/OneMore#1449]
# Problem to Solve

I couldn't work out why my hashtags weren't showing up in my search till I opened the OneMore.DB.

It looks like it only scans My notebooks (personal or Work) and not ones shared with me.

It is really important that it scans all ones I have access to (as in opened on this PC) OR at least gives me the option.  5 of us own our own notebooks, but share them and I started using hashtags as reviewer comments etc #TODO_JAC:2407:JAC:02/07/2024 Great page.

When users action them they coment and change them to #Done_JAC.
So we have a workflow of someone creates todo's and someone clears them once all actioned.

I thought it was a bug, but it looks like it is by design.  Can it be changed?

**Comment by jasonjac2** [comment]
Also for clarity, does the hastag_notebook table hold all notebooks scanned or only ones where there is 1 or more hit?
I would actually be interested in a build of OM that logged all notebooks, section and pages to a) check performance and b) give me a really cheap / poor mans inventory of pages.

**Comment by stevencohn** [comment]
Hi Jason. Were the shared notebooks added to your open collection after the initial hashtag scan? The scanner does not implicitly include new notebooks that you've added because of the new scheduling feature that tries to defer load on the system until off-hours. So you can schedule a scan (or immediately) to include these new notebooks.

If the notebooks have always been open in your instance of OneNote, then yes, it may be something that needs investigating.

**Comment by jasonjac2** [comment]
- Notebooks open after initial scan: I don't think so, this was a new laptop and I think I opened them all up before the initial scan had a chance to run.  It seems too much of a coincidence that they are all ones that are shared with me that are missing.
- I've just set the scan running now and will see what it comes back with.
- I noticed a typo on the run scan (san).
- Also on this Dell running at 100% scaling 1920 x 1080, the box at the bottom with the notebooks has some scrolling drawing redrawing issues (corruption of the writing).

**Comment by jasonjac2** [comment]
- hashtag search - I need to do more checking, it might be that since i swapped over from TODO_ to #TODO_ that there aren't any  in those other Notebooks.  I just added one to one of the shared ones, did scan now just for their notebook and it found it. 
- More research required.
- scrolling back up in the schedule hashtag
![image](https://github.com/stevencohn/OneMore/assets/68282090/c0b904b8-61df-445a-83b7-224f87d1f363)

- Additional - when I did a search, selected all, clicked index.  The last opened ON form disappeared and i thought it has crashed that ON.  about a minute later it popped up with the screen to select where to put the new page.  I assume it is becuase I have a lot of notebooks, sections - can you maybe not remove the search screen till the destination screen is built.

**Comment by jasonjac2** [comment]
Just for clarity.  There is the initial scan after install of OneMore, then does it do a full scan every so often or from then on it is every few minutes, but it will only check pages that have been modified since the last scan?

What are the rules on which notebooks get scanned on the incremental scan?
- if a new notebook
- If I open a notebook I haven't opened for a while / ever
- if someone else changes a notebook I have had open.....

**Comment by stevencohn** [comment]
Hi @jasonjac2. A quick update. In my testing, a newly added shared notebook is locked during its initial sync, preventing OneMore from reading it. While it records the notebook in the hashtag_notebooks table, it can't scan for tags. After the sync completes, manually updating any page containing a tag will allow OneMore to discover the tags on that page on subsequent scans. So at least this part is working as designed.

The hashtag_notebook table is used to track _known_ notebooks. The HashtagScanner uses this to identify and ignore new notebooks, allowing the user to decide when to explicitly pull it in with a requested scheduled scan. Also note that hashtag_scanner table records the last time any tag was added or removed from any known notebook. This helps improve performance by checking each page's lastModified time against lastScanTime.

The solution then is to add a lastModified column to hashtag_notebooks, allowing HashtagScanner to consider that value (is lastModified blank or filled) in addition to the hashtag_scanner.lastScanTime on normal subsequent scans. This is in development as I type...
