### ISSUE TITLE
Typos (website and app)

### ISSUE THREAD

**Issue by jasonjac2** [stevencohn/OneMore#1458]
# Problem to Solve
https://onemoreaddin.com/developers/Design%20-%20Command%20Service.htm
mesasge  -> message 

In App:
Hashtag Search -> Schedule Hashtag Scanning "Run the san now", -> scan.

I thought a had a list of more, I should have made a list.

Clearly not mission critical!

**Comment by stevencohn** [comment]
Documentation will be updated on next release too
