### ISSUE TITLE
Is my hashtag indexing working correctly?

### ISSUE THREAD

**Issue by bombledmonk** [stevencohn/OneMore#1461]
I'm on Version 6.4.0 with OneNote 16.0.16731.20716 
I've had OneMore running for several days on what looks to be about 3k pages across 5 notebooks and no hashtags are showing up when I try to search.   I was wondering if this is an appropriate message to see in the logs after several days ( installed on 7/3).  The laptop has been suspended several times in these days, but it's been up and running without interruptions all day today (8 hours) and there's no visible evidence of progression in being able to search tags.  

```
19|12:55:02.200| hashtag service waiting, Scanning
19|12:56:02.439| hashtag service waiting, Scanning
07|12:57:02.623| hashtag service waiting, Scanning
18|12:58:02.827| hashtag service waiting, Scanning
19|12:59:03.001| hashtag service waiting, Scanning
11|01:00:03.162| hashtag service waiting, Scanning
07|01:00:05.144| Running command HashtagCommand
10|01:01:03.318| ..hashtag service waiting, Scanning
08|01:02:03.467| ..hashtag service waiting, Scanning
09|01:03:03.681| ..hashtag service waiting, Scanning
05|01:04:03.876| ..hashtag service waiting, Scanning
19|01:05:04.102| ..hashtag service waiting, Scanning
06|01:06:04.332| ..hashtag service waiting, Scanning
19|01:07:04.526| ..hashtag service waiting, Scanning
15|01:08:04.714| ..hashtag service waiting, Scanning
07|01:09:04.899| ..hashtag service waiting, Scanning
10|01:10:05.129| ..hashtag service waiting, Scanning
06|01:11:05.279| ..hashtag service waiting, Scanning
10|01:12:05.424| ..hashtag service waiting, Scanning
08|01:13:05.646| hashtag service waiting, Scanning
15|01:14:05.857| hashtag service waiting, Scanning
18|01:15:06.072| hashtag service waiting, Scanning
18|01:16:06.276| hashtag service waiting, Scanning
```

I have a tag in my notes and it's not showing up.  
![image](https://github.com/stevencohn/OneMore/assets/4141691/43262abf-e961-48d7-b569-291fa467fe60)

Is there a reason why it says "Last Scan: 6:00 PM"?   Is there tips on troubleshooting if things aren't working as expected.   If the answer is wait longer, I'm ok with that, I was just looking through various issues and seeing a variety of times of  than 8 hours.

If I click on the Schedule Rebuild thing in the settings, it says 
![image](https://github.com/stevencohn/OneMore/assets/4141691/c2dc4b70-fcaa-461e-bd36-2da48804d7c7)

**Comment by jasonjac2** [comment]
Did it finish and how long has it been running. From what you describe, it does look like it is actively doing its first scan.

**Comment by stevencohn** [comment]
If it's gotten itself stuck into a weird state, close OneNote, then delete the file `%appdata%\OneMore\HashtagScanner.json`. Restart OneNote and you'll be able to schedule a new scan or search for tags.

The _Last scan_ status at the bottom of the Find Hashtags dialog does not account for scheduled scan; it presumes operation as normal, scanning every two minutes. Reflecting a schedule scan in that status is a bit of _incremental delivery_ that hasn't been done yet.

**Comment by bombledmonk** [comment]
Deleting HashtagScanner.json did the trick.  Thanks for the help.
