### ISSUE TITLE
Copy and Move Selection to New Page

### ISSUE THREAD

**Issue by bombledmonk** [stevencohn/OneMore#1465]
# Problem to Solve
I often have notes that come in from other sources, like emails, meetings, feedback from a web form, interview notes or a series screenshots representing many ideas that are captured in a single note for expediency's sake.  I would otherwise like to pull out the ideas/sections content into a new page.   I'd like to make the process of splitting the ideas/items in these pages out faster.  

# New Feature/Solution
There's probably several ways to get there, but I'd fundamentally like have a feature that is the equivalent of :
1. Select a some text/content in a notebook
2. right click
3. Have 2 features in the context menu  a. Move Selection to New Page  b. Copy Selection to New Page  (this could also be hotkeys)

## Alternative Solutions

Realistically, this is possible by going through the constant steps of copy/cut, new page, paste and going back, but I'd really appreciate a feature to speed up the process and it seems like a decent fit for the feature set of OneMore.

# Additional Context

I've been thinking about whether it would switch focus to the new page on the operation, and I'm leaning towards no because then you'd have to keep switching back.   If this is otherwise doable, I'd much appreciate pointers on how to get there.

**Comment by stevencohn** [comment]
Hi. OneMore has a [Split Page command](https://onemoreaddin.com/commands/Page%20Commands.htm) that lets you split up a page based on Heading1 headings. Would that work?

**Comment by bombledmonk** [comment]
I looked at Split Page, but the pages do not have any form of headings in them so if I wanted to use that it'd require me to go add them.  This certainly isn't a burning request or anything, but I've already had several times I've wished for the feature in my couple week stint with OneMore.
