### ISSUE TITLE
Is basic diagramming something you would consider adding to OneMore?

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#148]
**Is your feature request related to a problem? Please describe.**
Allow the user to replace the standard set of geometry like shapes with custom shapes
I am not sure what format is required for these shapes but importing and using Visio shapes would be a dream
The other option would be to allow the user to use his/her own custom icons (stored in a folder etc)

**Comment by stevencohn** [comment]
I would be easy to create Visio shapes or even diagrams to PNG files and present a catalog to import onto your page. However, Microsoft is protecting their intellectual property by not exposing an API to export shapes into a resizable vector drawing or preferably an InkDrawing used by OneNote. The result is a small image that ends up being ugly an grainy if you try to enlarge it at all.

Unless there's a magic API that I'm not ware of, I don't think this is reasonable.

**Comment by 1001QAdotNET** [comment]
There is a ing to visio shapes and back convertwr written by a russian guy
What dormat do you need to be able to replace the default shapes

**Comment by stevencohn** [comment]
Visio to PNG is built into the Vision API already. What I was looking for was a Vision to Ink converter.

**Comment by 1001QAdotNET** [comment]
I think this is theone https://sourceforge.net/projects/vdxtosvg/

**Comment by stevencohn** [comment]
Visio API can save SVG natively as well. This doesn't help. Need Windows.Ink format for WPF. I believe that's compatible with OneNote's InkDiagram syntax.

**Comment by stevencohn** [comment]
Closing this for now. I don't think there is a viable solution.

**Comment by 1001QAdotNET** [comment]
I agree please close it
