### ISSUE TITLE
Request for the Ability to Apply Onenote Template on Existing Pages of Section or Notebook

### ISSUE THREAD

**Issue by BeeboTaylor** [stevencohn/OneMore#1483]
# Problem to Solve

I have a couple of thousand pages which were created using a particular template.  That template is no longer valid so I created a new template for pages I create in the future but I don't have the ability to apply that template to existing pages.

# New Feature/Solution

I would like to be able to apply a newly created template to existing pages.  Say, for example, I have copied the characteristics of an existing template to a new template but I have changed the font of the new template, I would like the ability to apply this new template to all of the existing pages in a section or notebook.

## Alternative Solutions

Onetastic macro can apply changes to existing pages

# Additional Context

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
This is not possible. OneNote doesn't support the ability to apply a template to an existing page; you can only create a new page from a template.
