### ISSUE TITLE
Favorites - You can't just type, i.e. list has focus and no hotkey to select filter (V6.5)

### ISSUE THREAD

**Issue by jasonjac2** [stevencohn/OneMore#1489]
# Problem to Solve
I used to "alt+f" wait for 0.25s and type to filter the fav's.  
AFAICS the "Go" button has focus AND the list.  
Invoke, then tab moves through the list (name -> location -> next name down)
Invoke, then shift+tab makes the "go" lost focus, I am not sure where it goes.

THANK YOU SO MUCH FOR YOUR EFFORT ON THE ONEMORE TOOL!

Viva le Keyboard-Warriors!

# To Reproduce
Invoke favorites and just type any letters.  no filtering occurs.

# Expected Behavior
Invoke: then type characters = entered into Search box.
Left and right arrows navigate in search box 
up & down navigate in fav list
Enter always hits the "go" button

# Environment (if applicable)
Version 6.5.0 with OneNote 16.0.17726.20160 64 bit.

# Workaround
invoke, Shift tab, tab

**Comment by jasonjac2** [comment]
Just another thing and not sure if it is new or not.  If you invoke Fav's using hotkeys and then press escape, the instance / windows of ON you were on loses focus, I can see the caret flashing, but typing doesn't do anything.

ON still has focus as pressing Alt - shows the accelerators.

So to abandon the fav's, you need to press escape, alt, escape and you will be able to move the caret / type into the ON page.

**Comment by stevencohn** [comment]
Sorry man. It'll be fixed in next release.

**Comment by jasonjac2** [comment]
No worries, all good and looking forward to testing the rest of it out.
