### ISSUE TITLE
Option to have hashtags as case-insensitive.

### ISSUE THREAD

**Issue by jasonjac2** [stevencohn/OneMore#1492]
# Problem to Solve

Loving hashtags.  But when people put them in , sometimes it is all caps, mixed, lower, and any other variation.  This brings up lots of permutations in the search dialogue.

# New Feature/Solution

Have a setting / option to log all hashtags as upper / lower.

## Alternative Solutions

# Additional Context

![image](https://github.com/user-attachments/assets/6b90ab31-7b8e-442c-ad87-61c8d17ca0b7)

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by jasonjac2** [comment]
I think maybe when you select one it is case insensitive, eventhough the dropdown has all the permutations that exist, is that right?
Follow up: Is there any house keeping, i.e. when there are no more of a particular hashtag, it gets removed from the dropdown?

**Comment by stevencohn** [comment]
Yes, whenever you remove/modify/add hashtags from a page, the scanner will notice when the page is updated, and remove/modify/add those in the database accordingly. 

The drop-down is global, so if a tag appears on more than one page, it will remain until all occurrences of it are removed.

It was implemented as case-insensitive to keep it simple (it's also the default mode for SQLite) as most general users may be confused why they can't find their "DOG" when looking for their "dog". I'll see how complicated it would be though.

**Comment by jasonjac2** [comment]
Just to be clear - I am *very* happy the match is case-insensitive (as I think it is now).
So my request becomes, in the dropdown, show case insensitive entries
ToDoJason; todoJason; TODOJASON => one entry in the dropdown.

Thanks,
