### ISSUE TITLE
Ability to Dock the Navigator as a Side Panel

### ISSUE THREAD

**Issue by BeeboTaylor** [stevencohn/OneMore#1494]
# Problem to Solve

I use the Navigator to search through large note files with lots of headings.  Its a really useful utility but in its current form it is a little bit inconvenient having to popup a separate window to do this - I typically have it open as an icon in the task bar, click on it when I need it, and then minimize it.  I use a similar feature in VSCode to navigate headings in Markdown files but its a side panel I can just open with a keyboard command.  Looks like this:

![image](https://github.com/user-attachments/assets/0577754d-efea-4eb8-bab0-c8576536e223)

Is it possible to have the navigator docked like the page panel in Onenote, rather than having it as a separate Window?

# New Feature/Solution

Dock navigator like the page panel or tag panel with easy access using keyboard shortcut or command.

## Alternative Solutions

Maybe use the tag panel and Heading level tags?  I haven't tried this but seems like it would lack hierarchy and order.

# Additional Context

Obsidian has something very similar.  At the end of the day that application can't replace Onenote but it has some nice features Onenote should be adopting.

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
Sadly, this is not possible. Microsoft has not expose an API to add custom side panel within OneNote.

**Comment by BeeboTaylor** [comment]
OK, thanks for the update!
