### ISSUE TITLE
OneMore resizes the container when inserting the TOC

### ISSUE THREAD

**Issue by gpbicego** [stevencohn/OneMore#1498]
OneMore v6.5.0 resizes the container when inserting the TOC.

# To Reproduce
![image](https://github.com/user-attachments/assets/2c74adf6-485a-442a-92a1-5c5082f56d88)
![image](https://github.com/user-attachments/assets/867a0ad6-74da-4f96-954f-b1be693306c6)
![image](https://github.com/user-attachments/assets/28168fbf-4608-49df-9c52-9e4c4df71acc)

# Environment (if applicable)

 - Version 6.5.0 with OneNote 16.0.17726.20160
 - OneMore Version [e.g. 3.4 - from the About dialog or from the log file]

# Additional Context
Thanks so much Steven

**Comment by jasonjac2** [comment]
Aside: I put my ToC on a separate container, that way, when you refresh or insert it, it doesn't mess about with the "edited by" information for the main containers on the page.

Looking at the XML, it looks like the ToC is made of a table with 1 column.
<one:Column
              index="0"
              width="360.0"
              isLocked="true" />

I can't see how to change that in the ON user interface, but when I changed it in the XML the container re-sized (deleted the isLocked).

Sorry, not a solution, just observations.

**Comment by gpbicego** [comment]
Could you try with this page https://docs.github.com/en/get-started/using-github/github-flow:
![image](https://github.com/user-attachments/assets/aecd1721-79f7-4d47-8885-dc2dfed8eb57)
the result after entering the TOC is::
![image](https://github.com/user-attachments/assets/bd67aa68-5e79-45a6-9e64-c0aafbf752b3)

**Comment by stevencohn** [comment]
Seems to work as expected. Is there additional content you can detect on your imported page?

I used the OneNote Web Clipper from Edge, immediately inserted a ToC, and then margins remained where they were. I've highlighted the ToC Table in this picture:

<img width="519" alt="image" src="https://github.com/user-attachments/assets/2ae649d4-5937-4218-b4ef-1ef66edf7bb5">

**Comment by gpbicego** [comment]
I also used the OneNote Web Clipper from Edge, immediately inserted a TOC, but the margin became enormous.
How can I install the older version 6.4.0 of OneMore on my PC to see if the problem persists?

**Comment by stevencohn** [comment]
Uninstall OneMore from Installed Apps (Right click the Start button and then click Installed Apps)

Download 6.4.0 from here https://github.com/stevencohn/OneMore/releases/tag/6.4.0

**Comment by gpbicego** [comment]
I also encountered the problem with OneMore 6.4.0:
![image](https://github.com/user-attachments/assets/9cfad66a-df45-4290-9b73-9af460e658be)

Maybe it's related to my region settings?
![image](https://github.com/user-attachments/assets/0751d71d-dfdc-4486-b51d-a43b6250fda0)
![image](https://github.com/user-attachments/assets/58ccf08b-e30e-4f0f-b26b-a3e080dc8ed4)
Can I do other tests? Otherwise that's fine too, I can live with that. Thanks again

**Comment by stevencohn** [comment]
I'll investigate. Thanks for the region info. It may be misinterpreting decimal/thousands-separator in floating point numbers. (comma vs period). That would be an easy fix....

**Comment by stevencohn** [comment]
Unfortunately, that wasn't it. Setup up my laptop with Country=Italy, Region=Italian, started OneNote, clipped that page, added ToC, and it worked fine. But I'll keep this open as a bug

**Comment by gpbicego** [comment]
I think there is a problem here:
![image](https://github.com/user-attachments/assets/05a93208-95be-4389-ba7e-8318e1620d79)

**Comment by jasonjac2** [comment]
what was watt.value at line 218 / 219?
Excited to see others debugging code.

**Comment by stevencohn** [comment]
It shows it to the right `[width='540.0']` which tells me that it is, in fact, may be a regional issue, that adds an order of magnitude! Thanks for the screenshot

**Comment by jasonjac2** [comment]
I think your float.tryparse is using the "Digital grouping symbol" as "."

**Comment by stevencohn** [comment]
float.TryParse is a built-in .NET Framework API that relies on the culture of the current thread, which it gets from the Windows settings you show above. So in your example, it should treat 540.0 as "540". 

@jasonjac2 are you able to repro this?

**Comment by stevencohn** [comment]
@gpbicego If you could, please change that TryParse to be:

`float.TryParse(watt.Value, out float width, CultureInfo.InvariantCulture)`

It should have been that anyway! But give it shot to confirm since I'm having trouble reproducing it myself. (I really do want to take a trip to Italy someday :-) )

**Comment by jasonjac2** [comment]
@stevencohn nope couldn't reproduce. Swapped the Decimal Symbol to , and the decimal grouping to ., rebooted.  New NB. Still worked as expected.

**Comment by gpbicego** [comment]
@stevencohn the fix works on my computer:
![image](https://github.com/user-attachments/assets/5a36869c-f610-49ef-9c1f-c94ef5307f56)
thanks Steven (you are welcome in Italy, there are lots of things to see and taste :-))
