### ISSUE TITLE
Error `Setup (incompatible)

### ISSUE THREAD

**Issue by it19862** [stevencohn/OneMore#15]
**I use:**
Win-7x64
VS - 2019

How to fix the error `Setup (incompatible)?
![2020-02-08_00-27-30](https://user-images.githubusercontent.com/18245828/74067290-f98ab680-4a09-11ea-9c7c-da4d07004cd1.png)

**Comment by stevencohn** [comment]
Add this extension to Visual Studio:
https://marketplace.visualstudio.com/items?itemName=visualstudioclient.MicrosoftVisualStudio2017InstallerProjects

**Comment by it19862** [comment]
I installed the extension.
The error did not resolve.

I did not write in the last message, but I still have an error
"Cannot find metadata file" C: \ 01 \ fl \ OneMoreAddIn \ bin \ x86 \ Debug \ River.OneMoreAddIn.dll "."
![2020-02-08_10-09-56](https://user-images.githubusercontent.com/18245828/74081020-4185f980-4a5b-11ea-9777-37bb9f09eeeb.png)

**Comment by stevencohn** [comment]
I'm closing this because it should just work and may be an environmental issue on the workstation that I have no control over
