### ISSUE TITLE
Request Chorded Keybindings

### ISSUE THREAD

**Issue by BeeboTaylor** [stevencohn/OneMore#1503]
# Problem to Solve

I have configured Onemore to trigger some functions using key combos, but it appears that the current requirement is to use simultaneous key combinations like "ctrl+alt+shift+1".  Is it possible to configure an emacs/vscode style key chord like "ctrl+k 1"?  

# New Feature/Solution

Request ability to configure keybindings to key chords

## Alternative Solutions

Instead of using complex key combinations I just use the command palette which works well, but is a little less efficient.

# Additional Context

I don't have much background knowledge of the design principles on this.  I've only used three applications intensively enough to even be concerned about it, so I don't know if it is common in applications or not.  I used Emacs many years where this was standard, but then switched to Obsidian where it requires a plugin to implement, but does work with that plugin.  Its standard in vscode where I use it quite a bit.  Might be a bit overkill for Onenote, but might be useful for some power users.

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
This is ostensibly available already as a built-in feature of Office ribbons. You start a chord by pressing and releasing the `Alt` key.

For example, pressing `Alt` followed by `H` will show the next keys in sequence, similar to the following (may differ depending on ribbon customizations)

<img width="827" alt="image" src="https://github.com/user-attachments/assets/9aad4b26-a0f3-409f-91b6-4302424ffc19" />
