### ISSUE TITLE
Slow and laggy after update

### ISSUE THREAD

**Issue by lwellers** [stevencohn/OneMore#1506]
After upgrading to version 6.5 OneNote reacts really slow and is laggy. After uninstalling the addon everything works fluently.

**Comment by jasonjac2** [comment]
@lwellers a bit more detail would be good..... all ON, when using OneMore.... which version of OneNote, which version of windows?  When OM installs there is a bunch of scanning that gets done, (hashtag searching).  How long did you leave it and what was laggy?

**Comment by lwellers** [comment]
Sorry, here you are:
Everything in OneNote is laggy, sometimes it needs 2 to 10 seconds to react. This even happens if I click on another existing page or a menu. After a couple of minutes everything works fluently and again after some minutes everything is laggy again. I have no problem at all with OneMore deinstalled.
I am using the latest desktop-version on windows 11 Pro 23H2
OneNote was running several hours. I did a restart, reinstall

**Comment by lwellers** [comment]
I deactivated the hashtag-service in options. Everything works fine now.

**Comment by stevencohn** [comment]
Since its initial release, the Hashtag service scans for updates to hashtags once every two minutes. This is typically less than 0.2 seconds and shouldn't be noticeable. When everything is normal, the upgrade should pick up right where it left off. 

If a scan was active when you upgraded, there is a chance it was left in a weird state. Similar to [the note at the bottom of the 6.5.0 release notes](https://github.com/stevencohn/OneMore/releases/latest), you can reset the scanner from the OneMore Settings dialog. You'll then be able to reschedule a scan during off-hours. Worst case, you can delete `%appdata%\OneMore\OneMore.db` and `%appdata%\OneMore\HashtagScanner.json` and restart OneNote - OneMore will recognize the missing db and automatically schedule a scan for midnight.

Once the full catalog is built, it will settle down again you shouldn't notice any lags.

If possible, I would be interested in your `%temp%\OneMore.log` file. Zip it up and attach it here.

**Comment by lwellers** [comment]
[OneMore.zip](https://github.com/user-attachments/files/16399005/OneMore.zip)

I did a reset of the scanner now and enabled hashtags. I will see if the scan at midnight is sucessful and report again tomorrow.

**Comment by cburr** [comment]
I have the same issue after upgrading. I performed the reset, enabled the hashtag service and the issue is still present. Had to disable the service.

**Comment by cspotcode** [comment]
I reset my scanner -- followed the instructions here https://github.com/stevencohn/OneMore/issues/1520#issuecomment-2266282348  -- and as far as I can tell, the scan hasn't finished.

The scan started an hour ago, at the time I'd scheduled it.  But it's still running.  My `HashtagScanner.json` is: (for comparison, at time of writing it is 
`2024-08-05T23:55:01.539Z`

```
{
  "notebooks": [],
  "startTime": "2024-08-05T22:45:00Z",
  "state": "Scanning",
  "shutdown": true
}
```
The right-click menu for my tray icon seems to agree:
![image](https://github.com/user-attachments/assets/8a69715d-20d2-4908-88f2-9bfcfc4c2443)

I'll wait a few more hours, but my gut tells me I don't have that many notes / my PC is fast enough that the scan would have finished by now.

**Comment by KunjanChauhan** [comment]
I can confirm running OneMore v6.6.1 on OneNote 16.0.18129.20158 with OneMore default settings and no other add-ons in OneNote, the whole of OneNote is painfully laggy.  

Speed is back to normal after disabling hashtag service.  

I will re-enable and set it to run a hashtag scan through the night.

Steven, if you need any tests or logs from my side, please ask. TY.

**Comment by stevencohn** [comment]
Thank you @KunjanChauhan. It would be helpful if you could zip up and attach your log file `%temp%\OneMore.log`, which would be something like `C:\Users\steven\AppData\Local\Temp\OneMore.log'

Also, it would be helpful if you could try to characterize your notebooks, sections, pages. In other words. how many of each? Do they have lots of handwriting?

**Comment by KunjanChauhan** [comment]
> Thank you @KunjanChauhan. It would be helpful if you could zip up and attach your log file `%temp%\OneMore.log`, which would be something like `C:\Users\steven\AppData\Local\Temp\OneMore.log'
> 
> Also, it would be helpful if you could try to characterize your notebooks, sections, pages. In other words. how many of each? Do they have lots of handwriting?

Hi Steven,  I have attached the log file.  Some stats on my usage at this point in time, based on using the Analyse command:

1. Total of about 2gb worth of OneNote pages. 
2. ~19 Notebooks open at any one time.
3. ~1000 pages
4. no handwriting, but max 10 pages of drawings, mostly test and text based tables, not so many external pointing hyperlinks
5. but I do have a lot of screenshots with text and numbers in the images and I suspect that OneNote tries to OCR them as they crop up in text searches!

[OneMore.zip](https://github.com/user-attachments/files/17935990/OneMore.zip)

I hope this helps. Rgds.

**Comment by stevencohn** [comment]
This is the page that looks like OneMore is having trouble loading

/Kunjan @ Global PMI Partners/Quick Notes

Perhaps you can investigate that Quick Notes section or even delete it. It's trying to load a page from there, failing, and then retrying. It retries three times as shown from these logs:

```
09|02:33:22.922| error 80042005 The page does not exist (HResult 80042005), retyring in 250ms with new Application object
18|02:33:23.186| error 80042005 The page does not exist (HResult 80042005), retyring in 500ms with new Application object
17|02:33:23.706| error 80042005 The page does not exist (HResult 80042005), retyring in 750ms with new Application object
```

Meanwhile, I see if there's a better way that OneMore can handle this situation and try to have it improved by next release.
