### ISSUE TITLE
Hashtag scanner doesn't work

### ISSUE THREAD

**Issue by yukilikespie** [stevencohn/OneMore#1507]
# Problem to Solve

I installed OneMore on a fresh Windows 11 install. I had tried to run the hashtag scan multiple times, I even left it overnight, and it's stuck at scanning. My 2 notebooks don't have that many pages, maybe 1k or less.

# To Reproduce

1. Run Hashtag scanner.

# Expected Behavior

Hashtag scanner should work and complete scanning.

# Screenshots

OneMoreTray it's stuck at "Scanning" the hashtags:
![image](https://github.com/user-attachments/assets/0bdffe98-2d6b-4998-a5ea-8dc8c05d19b6)

When trying to use "Find Hashtags" to check if anything was processed, clicking on the search icon doesn't do anything.

# Environment (if applicable)

 - OneNote Version: Microsoft® OneNote® for Microsoft 365 MSO (Version 2407 Build 16.0.17830.20056) 64-bit 
 - OneMore Version: Version 6.5.0 with OneNote 16.0.17830.20094

# Additional Context
I have attached the logs here:
* [OneMore.log](https://github.com/user-attachments/files/16398972/OneMore.log)
* [OneMoreTray.log](https://github.com/user-attachments/files/16398973/OneMoreTray.log)

I noticed that in `OneMoreTray.log`, right after starting scanning, it gives this db error multiple times:
```
06|12:09:17.704| dropping table hashtag_notebook
06|12:09:17.704| error writing tags
06|12:09:17.704| DROP table IF EXISTS @n
06|12:09:17.704| System.ArgumentOutOfRangeException
Message: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Source: mscorlib
StackTrace:    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Data.SQLite.SQLiteParameterCollection.GetParameter(Int32 index)
   at System.Data.SQLite.SQLiteParameterCollection.GetParameter(String parameterName)
   at System.Data.SQLite.SQLiteParameterCollection.get_Item(String parameterName)
   at River.OneMoreAddIn.Commands.HashtagProvider.<>c__DisplayClass7_0.<DropDatabase>g__Drop|0(String type, IEnumerable`1 names)
TargetSite: [mscorlib] System.ThrowHelper::ThrowArgumentOutOfRangeException()
```

Things I have tried:
* Reset from Settings > Hashtag and rerun the scan
* Repairing OneMore
* Deleting both `HashtagScanner.json` and` OneMore.db` from `%AppData%\OneMore` (suggested [here](https://github.com/stevencohn/OneMore/issues/1461) and [here](https://github.com/stevencohn/OneMore/issues/1506))

**Comment by dnbrv** [comment]
I have the same issue. I also can't type custom hashtags in this dialogue. I can only select from the list of common words on the page. The screenshot is from a copy of Halo walkthrough for a generic example.
![image](https://github.com/user-attachments/assets/76352594-8bff-46eb-8b8b-b14f29e1e7ee)

**Comment by stevencohn** [comment]
The initial design of this dialog is to be just a picker, not to accept custom hashtags. It's not a bug, it's an incremental implementation.
