### ISSUE TITLE
Suggestion: Mobile / Non-Desktop Friendly Tagging (Plaintext)

### ISSUE THREAD

**Issue by G2G2G** [stevencohn/OneMore#151]
Hi, 

First off, thank you for a great add in !

The tagging feature is great, however it can really only be easily used to add or search for tags in the 2016 desktop version of Onenote. It is my understanding that it uses the special custom tag icon when it searches for tags.

What I propose instead is to use a specific unique, not typically used, combination of letters to define tags. This would make adding and finding tags easy on any type of platform, and will also make automating tag entry via keyboard automation possible. 

E.g. I use three letters "l" in front of tag descriptor:

lllFollowUp
lllFile

etc. 

This way, searching for "lll" would show me all tagged entries, and searching for e.g. lllFile would show me all entries tagged with that tag, but omit just the word "file".

The advantage of this method is also that it can be used across multiple applications. E.g. I can forward an email that requires action to me@onenote.com and append lllAct (action) and lllProjectABC to the subject, and the record will already be tagged in Onenote. Or, I can create an Outlook task from Onenote text, and it will already have the tags in its subject. I could then search in Onedrive for lllProjectABC and get the Onenote result, the Outlook email, the Outlook task, and any other document tagged with this project in one list. (Unfortunately, Windows Indexing seems unable to find Onenote results on the desktop anymore...)

The add in could be set up to use the same approach, and add more features to it by allowing to create a summary of tagged pages, similar to the Onenote's own Tags Search.

**Comment by G2G2G** [comment]
Any comment ? 

Let me try & explain it better.

The page tagging feature in OneMore is great but tagging only works from Onemore. Any tags added elsewhere (e.g. iPad) aren't noticed. (Although tags added in Onemore can be searched from other devices as long as they are unique enough).

I suggest using a unique letter combination to define page tags (e.g. I use triple "L" which will not appear anywhere else in regular text) and having a way to manually invoke Onemore to parse notes for tags and convert them to Onemore tags.

E.g. (using lll as tag indicator)

- I add "lll1234 lllABC" to the  title of a page on some device that doesn't have Onemore installed (or when sending email to me@onenote).  So the title looks like "Title of a page lll123 lllABC"

- At some later point, I run the "Convert page tags" command in Onemore, it parses note titles across notebooks for text starting with "lll", if it finds an instance, it converts it to Onemore tag and deletes the original text starting with "lll".  So now that page title is "Title of a page" and the page has tags lll123 and lllABC.

**Comment by stevencohn** [comment]
Sorry I need to time to think about this. My day job is priority.

**Comment by G2G2G** [comment]
Understood. Just wanted to expand on this idea some more.

Thank you

On Feb 2, 2021, at 12:57 PM, Steven <notifications@github.com> wrote:

﻿

Sorry I need to time to think about this. My day job is priority.
