### ISSUE TITLE
New Colorize: Bash

### ISSUE THREAD

**Issue by MichiFr** [stevencohn/OneMore#1516]
# New Feature/Solution

Can you please implement a new Colorize option to format a bash command line or shell script?

Thanks,
Michael

**Comment by stevencohn** [comment]
Not complete coverage by any means, but a good start. For example, it would be nice to figure out a regex that parses embedded variables inside a string.

But it does recognize some known Bash variables and differentiates those from others, including 

* `$$`
* `$#` 
* `$@` 
* `$*` 
* `$0` 
* `$HOME`
* `$HOSTNAME`
* `$NAME`
* `$LINENO`
* `$PATH`
* `$PWD`
* `$SHELL`
* `$USER`
* `$UID`
