### ISSUE TITLE
Compress/reduce file size of pictures

### ISSUE THREAD

**Issue by andyylin** [stevencohn/OneMore#152]
My colleagues like to insert photos from their smartphones into our shared notebooks, but the image sizes are at full resolution and are quite large. OneNote doesn't have a way to compress pictures like in Word.

I've upvoted this feature request on OneNote Uservoice, but in the meantime, is this something that could be written into OneMore?

My current very time-consuming workaround is to use my iPad and copy the original image, run it through an iOS Shortcut I wrote to reduce resolution, then paste the image back in. Very time consuming.

**Comment by stevencohn** [comment]
OneMore already has the ability to resize images. It isn't specifically compression but may get you most of the way there. You could resize it using OneMore and then use the built-in OneNote feature to drag/scale the image to dimensions you want on the page.

Let me know how that works. If you think it needs more, I can look into incorporating a Quality entry box in OneMore's Image Resize dialog box; this would not only let you resize (or keep the same size) but also change the Quality level, thereby compressing it. This of course would be a lossy change but I imagine that would be OK

**Comment by stevencohn** [comment]
https://github.com/stevencohn/OneMore/releases/tag/3.12.3

See notes in release or on Wiki page to understand how this works in OneNote. Image quality can very quickly and easily degrade, so for best results: change the width and height, untick the _Preserve original size_ checkbox and leave the quality at 100%.

**Comment by andyylin** [comment]
> https://github.com/stevencohn/OneMore/releases/tag/3.12.3
> 
> See notes in release or on Wiki page to understand how this works in OneNote. Image quality can very quickly and easily degrade, so for best results: change the width and height, untick the _Preserve original size_ checkbox and leave the quality at 100%.

This is a sweet update!

I'm wondering if it's possible to set the image to be displayed at the same size, but to set a max resolution? 

For example, the image might be 200 x 300 on the page, I don't want to change how it appears on the page, but maybe it's original size is 2000 x 3000. So if I can set "resize original but preserve display size" and set a max resolution of say 600 x 900, if later on I need to zoom in I can still see a larger image with more details, but the image size is 800kB instead of 10MB.

Does that make sense?

**Comment by stevencohn** [comment]
No sorry it doesn't really make sense. But here's the deal. Having put this out there, I've now had a chance to rethink how this dialog works. I was originally trying to hide the fact that the rendered size is different than the physical size but now realize that's too restricting. So I may redesign the dialog again to let you play with both at the same time.

By _resolution_, I think you mean pixel resolution or dots-per-inch. Adjust that at the same time I think may be overkill for what most people actually need. I'm not trying to build a full-fledged image editor but just provide a couple of convenient operations that help streamline the workflow and data use of OneNote.

**Comment by andyylin** [comment]
I figured out a workable workflow yesterday, maybe this will help you think about how you'd like to adjust the dialog box.

I'll call "current size" the dimensions of the image as displayed on the page
I'll call "original size" the actual dimensions of the stored image

Workflow to reduce image file sizes on page (i.e. reduce original size) but preserve current sizes:

1. To speed things up, I try to find images with similar current sizes (e.g. width 320)
2. To figure out what the current size is, I select one image and open the Resize dialog box and note down the current size (dimensions given at the top)
3. I multi-select the images I want to resize
4. Set Preset to the width I want (e.g. 1024), and uncheck "Preserve original size"
5. After re-sizing, I go back into the Resize dialog box and this time set Preset to the width of the original current size (in this example, 320)

Ideally, I'd like to multi-select many different sizes of images or even simply select a page, and re-size all images: I can set a maximum dimension for the "original size" (e.g. 1024 x 768), a quality setting (e.g. 100%), while keeping current display sizes (current size) for each image.

Hope that makes more sense! Thanks again!
