### ISSUE TITLE
Table of Contents - configurable heading depth

### ISSUE THREAD

**Issue by BlueMM75** [stevencohn/OneMore#1521]
# Problem to Solve

The ability to create a Table of Contents and also being able to refresh it is fantastic. But sometimes when I have a lot of headings and also a lot of depth to those headings (say Heading 1 to Heading 6), the TOC becomes huge and not easy to navigate.

# New Feature/Solution

Provide the ability in the Table of Contents dialog, to specify the heading depth desired.
An example usage would be a user picking the depth (say a dropdown with each of the heading levels specified), selecting "2" and the TOC is generated with only Heading 1 and Heading 2 styles from the page.
Refreshing would also take into account the configuration of the TOC.
Bonus points would be for also taking into account the Title style, which I have seen before and sometimes use as a higher-level outline (the equivalent of Heading 0). So in the example above, the TOC would use all Title, Heading 1 and Heading 2 styles to outline. Happy to spin this off into a separate request if that's better.

## Alternative Solutions

None that I can think of.

# Additional Context

Similar to how MS Word works when inserting a TOC, the ability to only show levels to a certain depth:
![image](https://github.com/user-attachments/assets/c45cd8a7-6081-45da-a439-4539ddbc977d)

**Comment by oapy123** [comment]
I also find it difficult to read the ToC when there are a lot of headings and levels.  I think this would be a useful option to have.  I also would like to have the ability to format the ToC to match the heading styles of the sections contained in the ToC (If not an exact formatting match, at least maybe adjust the formatting in some way - like Heading 1 levels would be largest font, Heading 2 slightly smaller, etc).  I feel like this would make it easier to read and distinguish between each organizational level.
