### ISSUE TITLE
Fail to insert hashtags for a page

### ISSUE THREAD

**Issue by sylvialinyz** [stevencohn/OneMore#1522]
# Problem to Solve
I installed v5.8.1 first and the tag function works well until I upgraded it to v6.5.0.
The Insert Hashtags dialog pops up but I can't add any tags to the Tags box.

# To Reproduce

1. Go to 'OneMore'
2. Click on 'More' --> Search and Tag --> Insert Hashtags.

# Expected Behavior
Tags can be added to the page and searchable using "Searh Hashtags" feature.

# Screenshots
![image](https://github.com/user-attachments/assets/810657c2-656a-4e34-898e-f8c007717551)

# Environment (if applicable)

Version 6.5.0 with OneNote 16.0.17830.20138

# Additional Context

Add any other context about the problem here. Attach page XML file or the app log file as appropriate. You can find the log file here: %localappdata%\temp\OneMore.log

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
See the [comment here](https://github.com/stevencohn/OneMore/issues/1507#issuecomment-2264088976). The original request was from [this ticket](https://github.com/stevencohn/OneMore/issues/1435) and implemented by [this pull request](https://github.com/stevencohn/OneMore/pull/1485).

This is not a bug. It is currently as-designed. It may evolve and be enhanced as time goes on. I'll leave this here as a feature-request

**Comment by stevencohn** [comment]
Following up as part of #1575
