### ISSUE TITLE
Add ability to colorize completed tasks when using StrikeoutTasksCommand

### ISSUE THREAD

**Issue by PodyNoo** [stevencohn/OneMore#1528]
# Problem to Solve

When i'm using StrikeoutTasksCommand on long list of tasks, at first glance, completed tasks can be difficult to differentiate from tasks still to be done.

# New Feature/Solution

If we could also colorize text of completed tasks while using StrikeoutTasksCommand, remaining tasks would be more visibles.

# Additional Context

![image](https://github.com/user-attachments/assets/586f7806-b07e-4210-8273-12c044ada991)
![image](https://github.com/user-attachments/assets/d2f78dc4-6eb3-4809-b21a-192b865011e3)

**Comment by PodyNoo** [comment]
I have something working here, if you are interested (translations are missing) : https://github.com/PodyNoo/OneMore/commit/025f10afd40a6bd052b034491cfd1a1ccdc782ad?diff=split&w=1

**Comment by stevencohn** [comment]
Looks good. Consider using OneMore's `ThemeManager` class to get theme-based colors.

* `ThemeManager.Instance.GetColor("ControlText")` - could be used for the default color for text, replacing hard-coded "#000000".
* `ThemeManager.Instance.GetColor("GrayText")` - could be used as the default for your color picker on the settings sheet.

**Comment by stevencohn** [comment]
Is this true? Given indented tasks as you show above, the color is inferred from the parent. So if you override the setting with Red for example, the children are colored Red when you use the Strike-through command, ignoring the setting of Gray?

I understand it may continue a visual "categorization" of related tasks. But wonder if that is a nuance that is needed?

Also, you can use the StyleAnalyzer and Stylizer classes to avoid parsing the CSS attributes.

**Comment by stevencohn** [comment]
Decided to combine into the Horizontal Lines sheet, renaming it to `ColorsSheet`

<img width="580" alt="image" src="https://github.com/user-attachments/assets/c99e5e11-8d16-41d0-a3bb-32dfcee7dc20">

Also found that there were a few logic errors in the original `StrikeoutTasksCommand` code so had to refactor it rather than adopting your commit directly. 

So, thank you for the request. It will be available in the next release.

**Comment by PodyNoo** [comment]
Oh, thanks a lot for this !

**Comment by PodyNoo** [comment]
If it can be useful, i did push my code that i modified yesterday to use Stylizer / StyleAnalyzer / Theme-based colors as you advised : https://github.com/stevencohn/OneMore/compare/main...PodyNoo:OneMore:1528-colorize-strikeout-tasks-command

The only thing not working is, in dark mode, when i'm using ThemeManager.Instance.GetColor("ControlText").ToRGBHtml() instead of "#000000" i does not reset the color on task that goes from completed to to-do tasks.

To make it work, i needed to modify Merge() method from Style that was missing a property. (https://github.com/PodyNoo/OneMore/commit/a37500f2915751381dd91a0d09bf5eb87ccc3e04)

I also needed to modify CollectStyleProperties() from XElementExtensions to reverse the order of css properties parsing, because my OE/T nodes always had 2 colors properties (style="color:#000000;margin:0in;font-family:Calibri;font-size:12.0pt;&#xA;color:#969696"), and the wrong one was add in my StyleProperties. (https://github.com/PodyNoo/OneMore/commit/67bc93220f3a33f3acb8a72a05438e9674dbbea5)

Maybe I didn't quite fully understand how it works, so i might be wrong, but if not this might cause trouble elsewhere in the future.

**Comment by stevencohn** [comment]
In my excitement, I led you astray on using the ThemManager, which is intended only for UI controls, not on-page content. Content is handled entirely [with the Style family of classes](https://github.com/stevencohn/OneMore/blob/03fe4cafc0112677d4ae507f2f6d7d198b2f4b6d/OneMore/Commands/Reminders/StrikeoutTasksCommand.cs#L122). Compare your code to mine. I'm only use the `Style` class and its default values to make decisions.

The OET relationship with the CDATA style is a transient projection when the text insert cursor/caret is position in the OE paragraph, so a small adjustment is needed there only [when adding stirkethrough](https://github.com/stevencohn/OneMore/blob/03fe4cafc0112677d4ae507f2f6d7d198b2f4b6d/OneMore/Commands/Reminders/StrikeoutTasksCommand.cs#L136).

**Comment by stevencohn** [comment]
Regarding your last two commits. I'm afraid you may have broken a few other commands across OneMore . The `Style` and `XElementExtensions` are used extensively throughout and need to be tested for all use cases.

Yes, there can be two color values in a `style` attribute., most often when the text cursor interrupts the CDATA. The first is color I believe is the default text color for the page. The second color is tagged with the special sequence `&#xA; which indicates the actual color to apply to the run.

In these cases, we don't really care. If adding strikeout, we want to apply the chosen color to the entire line, overwriting any manual changes along the way. If removing strikeout, we can only revert back to the default page color. Attempting to preserve any manual color changes within the run is impractical and can result in no visual changes to color for the whole paragraph if the whole paragraph was customized.

**Comment by PodyNoo** [comment]
Thanks for the explanations, have a nice day 🙂 !
