### ISSUE TITLE
"Insert QR Code" Command Fails to Insert QR Code

### ISSUE THREAD

**Issue by forestail** [stevencohn/OneMore#1534]
# Problem to Solve

The "Insert QR Code" command fails to insert a QR code. This issue occurs because the Google API used to generate QR codes has been deprecated.

# Screenshots

![image](https://github.com/user-attachments/assets/4c3661ca-ae39-4176-83eb-ca4aca079fd1)

# Environment (if applicable)

 - OneMore Version: Version 6.5.0 with OneNote 16.0.17830.20138

**Comment by stevencohn** [comment]
Fixed on 1-Aug-2024 as part of [this commit](https://github.com/stevencohn/OneMore/commit/fb55de967d5a6a5ed67a1cf1086d5d33be4dfa52#diff-e7a242a271212009abb305a7500142d30ddfef079450f7eacd7c3a6b37f12bdb)

Will be available in next release.
