### ISSUE TITLE
Note Snippet Default Cursor Focus

### ISSUE THREAD

**Issue by infinitelyintrigued** [stevencohn/OneMore#1539]
Hi, I use the Note snippet very often. Is there a way to set the default cursor focus on "Your content here..." so I can immediately overtype it and start typing my notes? Right now, the cursor focus is positioned above the note box. I have to select "Your content here..." to delete and start typing.

**Comment by stevencohn** [comment]
Should apply to the other box snippets as well - Code, Text, Info, Notes, and Warning.
If you're wrapping existing content, the cursor should be positioned at the end of the content, inside the box.

**Comment by infinitelyintrigued** [comment]
Yes, thank you. It's just that it's more natural for me to create a note box first. It'd be great if you could add this feature to a future version of OneMore.
