### ISSUE TITLE
Page Map - for tall pages...... to easy navigation - nice

### ISSUE THREAD

**Issue by jasonjac2** [stevencohn/OneMore#1544]
# Problem to Solve
On long pages with lots of screenshots I often find myself zooming out to about 10 - 15% to get an overview of the page.  It would be great if you could render an image of the page as a floating window (or maybe as an option on Navigate) and so you can click on the image and goto that part of the page.  

It is a common feature in a lot of Developer IDE's 

Ideally be able to hover mouse and scroll wheel to zoom in and out based on the mouse pointer position in the map and hotkeys as well. I don't mean zoom in to see the actual text ext, but be able to zoom in and out to see the normal page level detain (i.e. no 100%, but between Whole page and maybe 30%).

![image](https://github.com/user-attachments/assets/49ab9db7-3f28-4184-a129-c29dac82243c)

# New Feature/Solution

Provide a clear and concise description of what you want to happen.

## Alternative Solutions

Provide a clear and concise description of any alternative solutions or features you've considered.

# Additional Context

Provide any other context or screenshots about the feature request here.

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
I answered [a similar question on reddit last week](https://www.reddit.com/r/OneNote/comments/1ekd6ee/comment/lhc0yzp/).

My answer was:

> Likely not. The OneNote APIs available to add-ins do not let add-ins interact directly with the UI, which means they can't force the page to scroll horizontally or vertically.
> It can be done with some very tedious Windows API hocus pocus but I'm guessing no one has ventured down the long and dusty path.
