### ISSUE TITLE
Batch import of MD does not import images

### ISSUE THREAD

**Issue by yxiaous** [stevencohn/OneMore#1549]
First, thanks for the hard work you put in on this wonderful addin that dramatically expands the functionality of OneNote.

I've tried to batch import markdown files, the import has been successful for texts but it does not import embedded images. Can this function be added? Many thanks.

**Comment by yxiaous** [comment]
I'm sorry: it appears importing directly from Obsidian md files doesn't include images, which could be due to Obsidian's own format for embedding images. Importing from a generic md file is fine with images.

**Comment by yxiaous** [comment]
I'm sorry: it appears importing directly from Obsidian md files doesn't include images, which could be due to Obsidian's own format for embedding images. Importing from a generic md file is fine with images.

**Comment by stevencohn** [comment]
The next release should enable importing Obsidian markdown files containing wikilink image references. However, the path to those files must not contain any spaces. OneNote has a problem dereferencing images from paths containing spaces.
