### ISSUE TITLE
Keyboard shortcut for the clock widget

### ISSUE THREAD

**Issue by Adlsr** [stevencohn/OneMore#1552]
# Problem to Solve

There is no keyboard shortcut to reset or stop the timer

# New Feature/Solution

Ability to assign keyboard shortcut to reset or stop the timer

# Additional Context

Hi and thank you for reading this request.
I'm obviously talking about the timer widget witch is great and i use it all day in my work.

I would love to have the ability to use shortcut for each one of the 2 buttons showing in the timer widget :
![image](https://github.com/user-attachments/assets/f830008d-8e9d-4900-871e-a90e94a6b6ce)

I know about the alt+F2 and F2 to start and insert it but is there anyway i can have shortcut to reset or stop the timer ?
Thank you :)

**Comment by jasonjac2** [comment]
I started using this a while ago, but i kept accidentally closing it.
+ shortcut to copy the timer. 
I can't get f2 to stop it - does it have to have focus.

It feels like a really useful tool if it just had a few more bits:
- history of timers - every time you reset put into a history you can click to copy.
- keyboard shortcuts to stop / start / restart / copy
- Maybe a text box that is copied when you copy the timer - what was I timing :-).

**Comment by stevencohn** [comment]
<img width="329" alt="image" src="https://github.com/user-attachments/assets/8beb916f-fc0d-44ea-9c85-864e3101c981" />

**Comment by Adlsr** [comment]
Great ! Thank you !
