### ISSUE TITLE
Change pen cursor

### ISSUE THREAD

**Issue by ankiman1** [stevencohn/OneMore#1553]
# Problem to Solve

It would be interesting if you could change the cursor for the pen. 
# New Feature/Solution

In onenote there is this cursor:
![cursor onenote](https://github.com/user-attachments/assets/3f256724-5684-44d9-9f5f-238cc825488a)

in paint: 
![cursor paint](https://github.com/user-attachments/assets/a4bcc475-79ca-44de-a9fe-f540e931b782)

## Alternative Solutions

Provide a clear and concise description of any alternative solutions or features you've considered.

# Additional Context

there is already an option to do this? 

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
Unfortunately, no this is not possible.
OneMore is limited by the API functionality exposed by Microsoft.
