### ISSUE TITLE
Font style corrupts page causing Onenote to crash

### ISSUE THREAD

**Issue by Gabry-Cmd** [stevencohn/OneMore#1554]
# Problem to Solve
Applying a font style on a heading corrupts the page. When the page is corrupted visualizing it causes Onenote to crash after a couple of seconds. 

# To Reproduce
OneMore plugin must be on for the crashes to occur, otherwise Onenote keeps going fine.

1) Write some text in a new text container and apply a font style on it with CTRL+ALT+SHIFT+2 or CTRL+ALT+SHIFT+3.
2) Onenote crashes.

Have a look at the screenshot below for further info. I have the same Onenote page to share with you, it is a minimal example with two containers with text and equations (latex like Onenote feature), there is an empty page on top of the section so you can land there before trying to crash it.

# Expected Behavior
I expect it not to crash.

# Screenshots
![image](https://github.com/user-attachments/assets/0d6ec086-cf68-4d0e-aca8-a761e3ba6907)

# Environment (if applicable)

- Microsoft® OneNote® for Microsoft 365 MSO (Version 2407 Build 16.0.17830.20166) 64-bit 
- Windows 10 Pro 64 bit, Version 22H2, Build 19045.4780
- OneMore version: 6.50 (look down for 6.40 and 4.90!)

# Additional Context
<details>
<summary>Event Viewer crash report  (OneMore 6.50)</summary>

```
Faulting application name: ONENOTE.EXE, version: 16.0.17830.20166, time stamp: 0x66b7a8df
Faulting module name: RICHED20.DLL, version: 16.0.17830.20056, time stamp: 0x668f315c
Exception code: 0xc0000005
Fault offset: 0x0000000000230035
Faulting process ID: 0x162c
Faulting application start time: 0x01daf3f46456ce57
Faulting application path: C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE
Faulting module path: C:\Program Files\Microsoft Office\root\vfs\ProgramFilesCommonX64\Microsoft Shared\Office16\RICHED20.DLL
Report ID: 0d005fc0-3ac0-4ee2-98e4-ed4ea30b677d
Faulting package full name: 
Faulting package-relative application ID: 
```

</details>

<details>
<summary>OneMore.log (6.50)</summary>

```01|08:02:48.893| Starting dllhost 3080, 2611 Mhz, 8 MB, en-GB/en-GB, v6.5.0, OneNote 15.0, Office 16.0, 2024-08-21 20:02
01|08:02:48.893| ..Windows 10 Pro, Version 22H2, Build 19041, 64 bit
01|08:02:48.893| ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.17830.20166)
01|08:02:48.909| ..OnConnection(ConnectionMode:ext_cm_AfterStartup,custom[1:Int32])
01|08:02:48.909| ..OneAddInsUpdate(custom[])
01|08:02:48.940| ..building ribbon
01|08:02:48.956| ..building ribbon colorizer commands
01|08:02:49.226| ..building ribbon language proofing commands
01|08:02:49.241| ..building context menu
04|08:03:11.243| ..RPC error, retrying in 500ms
System.Runtime.InteropServices.COMException
Message: The remote procedure call failed. (Exception from HRESULT: 0x800706BE)
Description: Unrecognized error code 0x800706BE
ErrorCode: 0x800706BE (-2147023170)
HResult: 0x800706BE (-2147023170)
Source: Microsoft.Office.Interop.OneNote
StackTrace:    at Microsoft.Office.Interop.OneNote.ApplicationClassCOM.GetPageContent(String bstrPageID, String& pbstrPageXmlOut, PageInfo pageInfoToExport, XMLSchema xsSchema)
   at River.OneMoreAddIn.OneNote.<>c__DisplayClass48_1.<GetPage>b__0()
   at River.OneMoreAddIn.OneNote.<InvokeWithRetry>d__35.MoveNext()
TargetSite: [Microsoft.Office.Interop.OneNote] Microsoft.Office.Interop.OneNote.ApplicationClassCOM::GetPageContent()


05|08:03:15.439| ..Starting dllhost 3080, 2611 Mhz, 8 MB, en-GB/en-GB, v6.5.0, OneNote 15.0, Office 16.0, 2024-08-21 20:03
05|08:03:15.440| ..Windows 10 Pro, Version 22H2, Build 19041, 64 bit
05|08:03:15.450| ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.17830.20166)
05|08:03:15.466| ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
05|08:03:15.466| ..OneAddInsUpdate(custom[])
04|08:03:19.253| ..RPC error, retrying in 750ms
System.Runtime.InteropServices.COMException
Message: The remote procedure call failed. (Exception from HRESULT: 0x800706BE)
Description: Unrecognized error code 0x800706BE
ErrorCode: 0x800706BE (-2147023170)
HResult: 0x800706BE (-2147023170)
Source: Microsoft.Office.Interop.OneNote
StackTrace:    at Microsoft.Office.Interop.OneNote.ApplicationClassCOM.GetPageContent(String bstrPageID, String& pbstrPageXmlOut, PageInfo pageInfoToExport, XMLSchema xsSchema)
   at River.OneMoreAddIn.OneNote.<>c__DisplayClass48_1.<GetPage>b__0()
   at River.OneMoreAddIn.OneNote.<InvokeWithRetry>d__35.MoveNext()
TargetSite: [Microsoft.Office.Interop.OneNote] Microsoft.Office.Interop.OneNote.ApplicationClassCOM::GetPageContent()

04|08:05:19.294| ..error instantiating OneNote IApplication after 0 retries
System.Runtime.InteropServices.COMException
Message: Retrieving the COM class factory for component with CLSID {D7FAC39E-7FF1-49AA-98CF-A1DDD316337E} failed due to the following error: 80080005 Server execution failed (Exception from HRESULT: 0x80080005 (CO_E_SERVER_EXEC_FAILURE)).
Description: Unrecognized error code 0x80080005
ErrorCode: 0x80080005 (-2146959355)
HResult: 0x80080005 (-2146959355)
Source: River.OneMoreAddIn
StackTrace:    at River.OneMoreAddIn.ApplicationFactory.CreateApplication()
TargetSite: [River.OneMoreAddIn] River.OneMoreAddIn.ApplicationFactory::CreateApplication()

04|08:05:20.058| ..error invoking action, aborting retries
System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: River.OneMoreAddIn
StackTrace:    at River.OneMoreAddIn.OneNote.<>c__DisplayClass48_1.<GetPage>b__0()
   at River.OneMoreAddIn.OneNote.<InvokeWithRetry>d__35.MoveNext()
TargetSite: [River.OneMoreAddIn] River.OneMoreAddIn.OneNote+<>c__DisplayClass48_1::<GetPage>b__0()
```
</details>

# I've tried to...
I also successfully compiled and installed the application and tried to attach with a debugger by injecting a breakpoint as described on the [OneMore Debugging wiki](https://onemoreaddin.com/developers/Debugging%20OneMore.htm). I saw that the dllhost doesn't crash as opposed to Onenote.

I had this problem since a couple of days before 6.50 came out, I had 6.40 at that time.
I tried to reinstall different versions of OneMore, 6.40 does the same as described up, 4.90 doesn't crash unless I tap onto its button in the dropdown menu (triple dots on the Home section).

I can copy the offending page on another section and notebook and make Onenote crash, this makes me think the page is corrupted.

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
Thank you for the detailed description and trying to debug.
May be related to #1128 

I'll take a look asap

**Comment by Gabry-Cmd** [comment]
Here's the link to the example page i mentioned: [example page](https://1drv.ms/o/s!AhPEkoHBvVCjamaK0jl7MjG_zWw).
I tried the following:
- I reproduced the #1128 on a clean page but no crashes occured.
- By cutting and pasting the bottom container (in the screenshot) the crash occurs.

**Comment by Gabry-Cmd** [comment]
I found out that the problem are links with equations in their title. It triggers when OneMore is enabled and I change the page and come back so I might have thought it was something else, should I create a new issue and mark this as closed?

**Comment by stevencohn** [comment]
A new ticket may help elucidate the issue more clearly. Yes please.

**Comment by Gabry-Cmd** [comment]
Substituted by the more specific issue #1556. This issue does not subsists as removing a link from the example page fixes the problem. I was mislead because you need to go back an forth between pages before OneNote first crashes and I applied the OneMore heading fonts in between.
