### ISSUE TITLE
Do you support macos?

### ISSUE THREAD

**Issue by zsy619** [stevencohn/OneMore#1558]
# Problem to Solve

Provide a clear and concise description of the problem, e.g. I'm always frustrated when...

# New Feature/Solution

Provide a clear and concise description of what you want to happen.

## Alternative Solutions

Provide a clear and concise description of any alternative solutions or features you've considered.

# Additional Context

Provide any other context or screenshots about the feature request here.

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
No, OneMore does not include a framework to run user-defined macros. The OneMore commands are "hard-coded".

However, OneMore does have a "plug-in" capability that allows some simple access to individual pages and to the page notebook/section structure. It's for advanced users who understand a bit about programming and manipulating XML. If you're interested, you can find out more information [on the OneMore Wiki here](https://onemoreaddin.com/commands/File%20Commands.htm).
