### ISSUE TITLE
The Setup doesn't have any reference to the php language colorizer files...

### ISSUE THREAD

**Issue by d-faure** [stevencohn/OneMore#1561]
...therefore, the language isn't available on a fresh install.

**Comment by stevencohn** [comment]
Will fix this in next release.

Meanwhile, you can download `php.png` and `php.json` [from here](https://github.com/stevencohn/OneMore/tree/main/OneMore/Colorizer/Languages) and copy the file into this folder `C:\Program Files\River\OneMoreAddIn\Colorizer\Languages`
