### ISSUE TITLE
image resize not working 

### ISSUE THREAD

**Issue by intox-ai** [stevencohn/OneMore#1567]
when using Resize and Adjust image nothing applies on the image (resize, brightness, etc) at all .

 - OneMore Version 
Version 2408 (Build 17928.20114) 64 bit
latest onemore version

**Comment by stevencohn** [comment]
Can you please give more information, steps to reproduce? I resize images often and do not see any issues. Are there certain cases? Thanks

**Comment by intox-ai** [comment]
i seriously don't know what went wrong it is a fresh windows 11 install and after installing onenote and onemore i just can't resize images but i still can on my labtop

**Comment by intox-ai** [comment]
actully i think it was the .net framework i updated and problem solved regarding the resizing but still other stuff like brightness, saturation, contrast these don't work at all
