### ISSUE TITLE
Exe name for favourites (favorites) and other dialogues - for other UI tools

### ISSUE THREAD

**Issue by jasonjac2** [stevencohn/OneMore#1569]
# Problem to Solve

So I use: Autohotkey and also stupidly recently bought a loupedeck device.  In addition I have written a kind of timesheet app that notices when you change applications.  All of these are sensitive to the exe name of the running processes. 

For the modeless dialogues of OM these are dllhost.exe.  This means that none of the above apps can do context sensitive things - well, not easily.  I can scrape the title bar (but loupedeck can't).

I realise, very minor in the grand scale of things, but I have set loupedeck up to offer actions when OneNote is up and running and would like to do the same when the add-ons have focus.

# New Feature/Solution
Wrap these dialogues that means they are EXE's in their own right, so i can pick up on when they are foreground.

**Comment by stevencohn** [comment]
dllhost.exe is a generic service host wrapper that is part of Windows and employed by Microsoft Office to enable its add-in architecture. OneMore plays in that architecture and there is no alternative that can be used to integrate OneMore with OneNote. You can [read about that on the OneMore Wiki here](https://onemoreaddin.com/developers/TechNote%20-%20COM%20Surrogate.htm).

If you can query the command line of the dllhost.exe process, you can look for the one that has `/Processid:{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}` as a parameter, as described on that page.

**Comment by jasonjac2** [comment]
Don't re-open this ticket, but I just to conclude this.... I went back to LoupeDeck and they don't seem keen to do filtering based on CommandLine etc.  I am a bit disappointed as it isn't easy to use their interface to switch (rather than launch am app).  To this end I will be asking for a oneMore: command to goto instances of OneNote.

I will add the "command line" to my "startOfTimesheet" app that tries to work out what you are up to while you are working.  I have no idea how expensive it is to ask Windows.
