### ISSUE TITLE
Due Date in Reminder Notification Message

### ISSUE THREAD

**Issue by infinitelyintrigued** [stevencohn/OneMore#1571]
# New Feature/Solution

I like the reminder notification feature. A notification shows the start date and the title. I would also like to see the due date and how many days are left until the due date in boldface. I will help me to prioritize when there are multiple notifications.

**Comment by stevencohn** [comment]
https://github.com/stevencohn/OneMore/commit/afc928626a5927f84da63065b568cd1acc6ad643
