### ISSUE TITLE
Create an Embed Box / block

### ISSUE THREAD

**Issue by ElenaPalma** [stevencohn/OneMore#1573]
# Problem to Solve

Supposedly, OneNote already supports embeding for other services like Spotify, however it seems to not be working since I dont see the playable song or playlist pop up when i paste the link. 
Apparently this has been an issue for a while since i saw someone else post about it on reddit a while ago and there have not been any solutions. 
I even tried using the web version of it, and it still didnt work. 

# New Feature/Solution

Maybe add an option to add an Embed Box like the boxes on the snippets. 
Or have it as an option on the Reference Menu so that you can paste either the embed code on a text box or just the link, as an alternative, so when you finish it, hit Ok or Accept and the embed 'thing' will appear on a block. 

# Additional Context

![image](https://github.com/user-attachments/assets/cb047c20-07e8-467f-8135-79c2f9bca8d3)

Link where it specifies that spotify is embeddable: https://support.microsoft.com/en-us/office/embed-content-in-onenote-fd5abf7d-abd4-4902-8e5f-93088c45b11d

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
This appears to be an internal OneNote feature that can't be accessed, reproduced, or emulated using the Interop APIs relied upon by OneMore.

When an "embeddable" URL is pasted into OneNote, it uses that URL to download a thumbnail image and overlays that with a "Play" icon when you hover over the image. That hover behavior is not specified on the page, but rather inferred by OneNote at run time.
