### ISSUE TITLE
Fuzzy matching in the command palette

### ISSUE THREAD

**Issue by tridian-tn** [stevencohn/OneMore#1581]
# Problem to Solve

When searching for commands in the command palette, it is ideal to be able to type quickly, select the command and move on. There are two cases I've come across where the speed of selection could be improved.

## First character of each word
Some commands lend themselves toward an ability to search by the first character of each word. The one that sticks out for me is "Table of Contents": when writing markdown I often add a table to the top of the document by typing `[toc]`, so muscle memory for me now is to type `toc` into the OneMore command palette without thinking.

Another example is "Apply Style 1", "Apply Style 2" etc. If search supported the first character of each word then "as1" or "as2" would be valid terms to quickly type into the Command Palette.

## Whitespace
It would also be helpful to search without considering spaces, to forgive some sloppiness in the searching. In the example above, typing "Style 2" matches "Apply Style 2", but "Style2" currently doesn't. Similarly, typing "tableof" currently doesn't match "Table of Contents".

# New Feature/Solution

Proposal: When the Command Palette matches the input text to the list of commands, it doesn't just match consecutive letters in command names. It also looks for the first character of each consecutive command name word.

Also, it is more forgiving of omitted whitespace in the search term.

Examples:

1. "Table of Contents" can be found using "tab" or "cont" but also "toc", "to" or "oc"
2. "Table of Contents" can be found using "table of" but also "tableof"
3. "Apply Style 1" can be found using "style 1" but also "as1", "s1" or "style1"

## Alternative Solutions

None, other than typing consecutive character matches as currently implemented.

# Additional Context

Provide any other context or screenshots about the feature request here.

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
There is an alternative. You can add command aliases in the Settings dialog. So you can define "toc" as an alias for Table of Contents and it will show up in the Command Palette.

Note, there is also a Quick Palette that includes custom styles, font colors, and highlight colors. This is accessible by pressing Ctrl-comma. The Quick Palette doesn't allow aliases but is sometimes quicker than using the mouse or remembering exactly what "Apply Style 1" means.

Are those sufficient?

**Comment by tridian-tn** [comment]
It's enough for my use case, thanks @stevencohn. Much obliged!
