### ISSUE TITLE
Slight delay opening OneMore dropdown menus in ribbon

### ISSUE THREAD

**Issue by G2G2G** [stevencohn/OneMore#160]
**Describe the bug**
There's about 1 second delay between clicking on the down arrow and menu opening. This only impacts OneMore menus. This has just started to happen recently. I have restarted the laptop to make sure it wasn't due to some hanging process.

**Environment (if applicable):**
 - OneNote Version: 2016 64-bit v 16.0.135.30.20376
 - OneMore Version 3.14

**Comment by stevencohn** [comment]
The longer and more complex the current page is, the slower those menus will be.
