### ISSUE TITLE
Since Update to Windows 11, OneMore does not show up anymore

### ISSUE THREAD

**Issue by NoYogurt8380** [stevencohn/OneMore#1601]
# Problem to Solve

I'm unable to find any indication in OneNote, that the Addon is installed. Only change to the system was the Windows 11 Update.

# To Reproduce

I re-installed the addon multiple times, restarted the computer, restarted OneNote.

# Expected Behavior

I would like to continue to use the great addon with Windows 11.

# Screenshots

![Screenshot 2024-10-04 235626](https://github.com/user-attachments/assets/f95f7ddd-2abb-4374-b89c-a99b390efa05)

# Environment (if applicable)

 - OneNote Version: O365, 64bit
 - OneMore Version 6.5.2
 
# Additional Context

Is there anything I have to do after running the installer? Thank you very much for your support!

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
Tracking this in #1602
