### ISSUE TITLE
Hashtags not indexed, if new notebook is added

### ISSUE THREAD

**Issue by nhwCoder** [stevencohn/OneMore#1606]
# Problem to Solve

Hashtags not indexed suddenly (after last Office update).
The only difference I see/imagine is the last Office update (maybe I am wrong, but that seems to be the difference at my PC)

# To Reproduce

1. Add "##Test" any page
2. Wait until hashtag indexer was run
3. Hashtag not indexed and see in log file that 0 page was scanned
        ..scanned 0 pages, updating 0, in 23ms

# Environment (if applicable)
- OneNote 16.0.18025.20140
- OneMore Version 6.5.2

**Comment by nhwCoder** [comment]
INFO
- Restart of Windows did not change/improve
- Manually running "Scan Now" also doesn't index hashtags anymore

**Comment by stevencohn** [comment]
Please attach your log file located at `%appdata%\onemore.log`

**Comment by nhwCoder** [comment]
I discovered the following

### VARIANT-01: NOT working
- Alt+F9 = Open "Search Hashtags"
- Click button "..."
- Choose Scan now
RSULT: Hashtags not found/not indexed

### VARIANT-02: WORKING
- Using "Schedule Hashtag Scan"
- Select "Run the scan now"
- Click OK
RESULT: Hashtags found & indexed  

### AN NOW - VERY CONFUSING - IT WORKS AGAIN
- After I did run VARIANT-01 "Schedule Hashtag Scan" once
- Now VARIANT-02 is working fine again...

**Comment by nhwCoder** [comment]
Log file
[OneMore.log](https://github.com/user-attachments/files/17357533/OneMore.log)

**Comment by nhwCoder** [comment]
## MAYBE I found the problem

- Open dialog "Schedule Hashtag Scan"
  - All notebooks are selected for indexing 
- Add a new notebook
- Open dialog "Schedule Hashtag Scan"
  - *NOT* all notebooks are selected for indexing
  - Have to select all notebooks by hand

**Comment by stevencohn** [comment]
No, that's just for the scan that you're about to schedule. The unselected notebooks are assumed to be known. Your selections would be either to rescan a known notebook or add a new notebook.

**Comment by stevencohn** [comment]
So yes, this is by design, and why the Schedule feature exists. If a new notebook is added, it may actually be a large notebook and scanning might take some time and interrupt your daytime work, making OneNote unresponsive or sluggish. 

What it could do is crack open the notebook and decide that the notebook is small enough to just scan automatically, or notify you that you must manually schedule a scan. I could define "small enough" maybe at 100 pages, that way a brand new notebook is just automatically included.

**Comment by jasonjac2** [comment]
I think to be consistent it should notice a new notebook and the UI should say "I've noticed you have opened a new notebook, I can scan it now (if it large, this may cause problems) OR add it on the next schedule.....

**Comment by stevencohn** [comment]
Yep, that's the plan. Something like this:

<img width="496" alt="image" src="https://github.com/user-attachments/assets/7fa41131-a8c4-4f97-bf46-9f6b04a22d75">

**Comment by stevencohn** [comment]
If it's small enough, it will auto-scan. If it's too large, you'll see that notice in the Find Hashtags dialog
