### ISSUE TITLE
Add keyboard shortcut for hashtag function "Scan Now"

### ISSUE THREAD

**Issue by nhwCoder** [stevencohn/OneMore#1607]
# New Feature

- Add keyboard shortcut for hashtag function "Scan Now".
Reason: See immediately after writing a hashtag if it was written and indexed correctly

**Comment by stevencohn** [comment]
You can use the _Schedule Hashtag Scan_ command and assign a key sequence to it. This opens a dialog. Choose the option _Run the scan now_ and click OK.

**Comment by nhwCoder** [comment]
Yes, BUT this needs UI interactions and clicks.
A keytip just running the scan for the current page and one to run a full scan would be very useful.

**Comment by stevencohn** [comment]
Sorry I wasn't clear. I wasn't saying no. For now, you can bind a key to the Schedule Hashtag Scan to get you closer. Meanwhile, I'll expose the Scan Now command. :-)

**Comment by nhwCoder** [comment]
Thanks!
