### ISSUE TITLE
Status bar like Word or Notepad++

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#161]
**Is your feature request related to a problem? Please describe.**
Status bar like Word or Notepad++

**Describe the solution you'd like**
should indicate indentation level, number of words selected (if text is selected) ,current style and whatever else you might consider useful

![image](https://user-images.githubusercontent.com/17384308/105388328-84959a00-5be4-11eb-82d7-fd8bb72ec2d0.png)

**Comment by stevencohn** [comment]
Unfortunately, the OneNote API doesn't provide that level of interactive detail. So this isn't possible.
