### ISSUE TITLE
Pressing "Enter" inside text and code boxes sometimes adds horizontal lines or moves the box down

### ISSUE THREAD

**Issue by cspotcode** [stevencohn/OneMore#1613]
# Problem to Solve

_I'm not sure if this is a OneMore bug, or simply a OneNote limitation that cannot be avoided._

When pressing "Enter" on the first line of a Code box, OneNote inserts a new table cell with a horizontal line.

![image](https://github.com/user-attachments/assets/dc00c33b-809c-48d7-9d02-2349c89e6452)
![image](https://github.com/user-attachments/assets/eebfe897-1874-4fde-9646-fe6a992808de)

Doing the same on the first line of a Text box moves the box down, creates a blank line above it.
![image](https://github.com/user-attachments/assets/7b651358-97e4-4347-b8c6-2c15c7ae29bb)
![image](https://github.com/user-attachments/assets/7a597c61-e3f4-4990-a7da-c4650578a417)

Highlighting text, putting it in a text box, then pressing "Enter" creates another table cell.
![image](https://github.com/user-attachments/assets/7ff2d516-020b-4203-beb5-9435dd5a787b)
![image](https://github.com/user-attachments/assets/c57a709d-d23f-4e20-93df-06dda48d482b)
![image](https://github.com/user-attachments/assets/e8d5b8e8-31d9-4218-b18d-bbb0108eb180)

# To Reproduce

Hopefully screenshots above are clear, but I'm be happy to add detailed steps if they'll help.

# Expected Behavior

Pressing enter inside the code or text box would ideally expand the box, never shift it or create new table cells.

These aren't the end of the world; I can learn to press Shift+Enter to avoid it.  Is this an unavoidable limitation, because the only way to put a border around text is to make a table?

# Screenshots

Included above.

# Environment (if applicable)

 - OneNote Version: OneNote 16.0.18025.20140
 - OneMore Version 6.5.2

**Comment by stevencohn** [comment]
The "box" commands are nothing more than a way to insert tables, sometimes single cell tables. This is just OneNote being OneNote.

**Comment by cspotcode** [comment]
Ok, thanks for confirming.  I'll build muscle memory for Shift+Enter.
