### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by Znajomykacper** [stevencohn/OneMore#1631]
# Problem to Solve

cant instal

# To Reproduce

# Expected Behavior

In half of instalation progres, this appears 

# Screenshots

![image](https://github.com/user-attachments/assets/112db538-ee7b-4628-bc62-13c638cddd5f)

# Environment (if applicable)

 - OneNote Version:  O365 ]64Bit, Version 16001
 - OneMore Version 6.5.2 64bit

# Additional Context

======================================================================
starting action: --install .. 25.10.2024 12:17:32
OneMore installer running as user ZARZĄDZANIE NT\SYSTEM (S-1-5-18) elevated
on behalf of WORKGROUP\system

CheckBitnessAction.Install ---
Installer architecture (x64), OS architecture (x64), requesting (x64)

Register... version 6.5.2

CheckOneNoteAction.Install ---
VerifyOneNoteApplication()
... error finding HKCR:\OneNote.Application

ShutdownOneNoteAction.Install ---
dllhost process not found
ONENOTE process not found

ProtocolHandlerAction.Install ---
step 0: opening HKLM:\Software\Classes\onemore
step 1: creating HKLM:\Software\Classes\onemore
step 2: setting properties of HKLM:\Software\Classes\onemore
step 3: opening HKLM:\Software\Classes\onemore\shell\open\command
step 4: creating HKLM:\Software\Classes\onemore\shell\open\command
step 5: setting properties of HKLM:\Software\Classes\onemore\shell\open\command
verified: key created HKEY_LOCAL_MACHINE\Software\Classes\onemore\shell\open\command

TrustedProtocolAction.Install ---
translating user DESKTOP-O9JTNTP\arma2 to SID
registering trusted protocol for user DESKTOP-O9JTNTP\arma2 (S-1-5-21-2416391718-2824816598-2750968737-1001)
defaulting Office version to 16
step 6: opening HKCU:\Software\Policies\Microsoft\Office\16.0\Common\Security\Trusted Protocols\All Applications\onemore:
step 7: creating HKCU:\Software\Policies\Microsoft\Office\16.0\Common\Security\Trusted Protocols\All Applications\onemore:
key created HKEY_USERS\S-1-5-21-2416391718-2824816598-2750968737-1001\Software\Policies\Microsoft\Office\16.0\Common\Security\Trusted Protocols\All Applications\onemore:

EdgeWebViewAction.Install ---
WebView2 Runtime is already installed
install completed successfully

--------------------------------------------------
direct action: --install-registrywow .. 25.10.2024 12:18:17
OneMore installer running as user ZARZĄDZANIE NT\SYSTEM (S-1-5-18) elevated
on behalf of WORKGROUP\system

RegistryWowAction.Install --- x64:True
1st chance, could not read CLSID or key missing
2nd chance, could not read CLSID or key missing
OneNote application path not found; continuing optimistically
step 0: deleting CLSID clone
step 1: cloning CLSID
step 2: copying from HKEY_CLASSES_ROOT\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61} to HKEY_CLASSES_ROOT\WOW6432Node\CLSID
created clone HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}
clone property  = River.OneMoreAddIn.AddIn (String)
clone property AppID = {88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61} (String)
created subkey HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\Implemented Categories
created subkey HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\Implemented Categories\{62C8FE65-4EBB-45E7-B440-6E39B2CDBF29}
created subkey HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\InprocServer32
clone property  = mscoree.dll (String)
clone property ThreadingModel = Both (String)
clone property Assembly = River.OneMoreAddIn, Version=6.5.2.0, Culture=neutral, PublicKeyToken=null (String)
clone property CodeBase = C:\Program Files\River\OneMoreAddIn\River.OneMoreAddIn.dll (String)
clone property Class = River.OneMoreAddIn.AddIn (String)
clone property RuntimeVersion = v4.0.30319 (String)
created subkey HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\InprocServer32\6.5.2.0
clone property RuntimeVersion = v4.0.30319 (String)
clone property Assembly = River.OneMoreAddIn, Version=6.5.2.0, Culture=neutral, PublicKeyToken=null (String)
clone property Class = River.OneMoreAddIn.AddIn (String)
clone property CodeBase = C:\Program Files\River\OneMoreAddIn\River.OneMoreAddIn.dll (String)
created subkey HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\ProgID
clone property  = River.OneMoreAddin (String)
created subkey HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\Programmable
clone property  =  (String)
created subkey HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\TypeLib
clone property  = {88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61} (String)
created subkey HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\VersionIndependentProgID
clone property  = River.OneMoreAddIn (String)

--------------------------------------------------
direct action: --install-activesetup .. 25.10.2024 12:18:17
OneMore installer running as user ZARZĄDZANIE NT\SYSTEM (S-1-5-18) elevated
on behalf of WORKGROUP\system

ActiveSetupAction.Install ---
opening key HKLM:\Software\Microsoft\Active Setup\Installed Components\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}
replacing '6.5.2' with '6,5,2'

======================================================================

**Comment by stevencohn** [comment]
At the top of the log, these lines tell me that OneNote is not installed, or not installed property. 

```
VerifyOneNoteApplication()
... error finding HKCR:\OneNote.Application
```

OneMore only works with the OneNote desktop edition. It will not work with the OneNote app.

You can find full instructions and download links here https://onemoreaddin.com/get-started/How%20to%20Install%20OneNote.htm

**Comment by mikinis111** [comment]
I'm facing the same issue. I have the 2409/16.0.18025.20160 version of OneNote, and my log file looks similar. It might be worth noting, that I've activated the Office 365 package via 3rd party activator software. I hope it doesn't make me unable to use this addin.
[OneMoreSetup.log](https://github.com/user-attachments/files/17547790/OneMoreSetup.log)

**Comment by stevencohn** [comment]
@mikinis111 You're install log also shows a problem verifying the OneNote installation:

`... error finding HKCR:\OneNote.Application`

That is the path of a system Registry entry that it can't find, under HKEY_CURRENT_USER. Are you sue OneNote was installed as part of your O365 package and that you're not, in fact, using _OneNote for Windows_ instead of _OneNote Desktop_?

I would recommend an install or _repair_ install of _OneNote Desktop_ edition.
