### ISSUE TITLE
Please add R colorizer

### ISSUE THREAD

**Issue by Random-x-1** [stevencohn/OneMore#1633]
Thank you all for developing such excellent plugin for onenote, could you please add a colorizer for R language? Thanks.

**Comment by jasonjac2** [comment]
Or even better, do a vid walk through with someone like me to add one (Pascal in my case) and then we can add our own.  I did try adding Pascal using C# as a base, but I can't remember why I failed.  I think I ended up going code -> VSCode -> ON.
