### ISSUE TITLE
Search Hashtags - Display "Incremental search" always sorted

### ISSUE THREAD

**Issue by nhwCoder** [stevencohn/OneMore#1638]
# Feature

Currently the display for Search Hashtags "Incremental search" is unsorted (e.g. just to enter "*").
Please display this "Incremental search" always sorted.

![image](https://github.com/user-attachments/assets/7940b346-1d94-4c0d-82c1-72fec41d43f4)

PS:
For sure for "This section" (and for "This page", which is a feature request just some time before).
If possible also for "This notebook" (if this is not to time intensive, but then it would be consistent for all searches).

**Comment by stevencohn** [comment]
Technically, that is sorted (hyphen is ordinally after underscore), but I get your point.

**Comment by nhwCoder** [comment]
Sorry the real issue is caused by a refresh problem, I first did not understand it fully. See https://github.com/stevencohn/OneMore/issues/1639

You can close this ticket as irrelevant.
