### ISSUE TITLE
Search Hashtags - Display "Incremental search" shows double entries

### ISSUE THREAD

**Issue by nhwCoder** [stevencohn/OneMore#1639]
# Problem

Search Hashtags - Display "Incremental search" shows double entries

# To Reproduce

1. Create new page
2. Add these tags as text
#Test_Tag_01
#Test_Test_aaa
#Test_Tag_02
#Test_Tag_bbb
#Test_Tag_03
#Test_Tag_ccc
4. Wait until indexed.
Open "Search Hashtags"
Select "This section" for dropdown (Before "This notebook")
5. See two entries for "#Test_Test_aaa". Where the last entry is wrong and has a " " empty space in front.
BEFORE
![image](https://github.com/user-attachments/assets/07850291-37bb-4f7c-875a-b1f4b7ff4706)
7. Hover with mouse over this dropdown area.
From last up to first entry over the text line entries and when I hover over the entries they ALL step by step get updated/changed and corrected. 
AFTER
![image](https://github.com/user-attachments/assets/8b658c01-7a74-4781-b2f6-ad83d3179ee1)

I can close "Search Hashtags" and reopen it and can reproduce the same behavior every time again and again.

**Comment by jasonjac2** [comment]
![image](https://github.com/user-attachments/assets/41e324a2-842a-4a6c-8a15-6444507f66f8)

I can't reproduce and I have tried a few times over the last 15 mins.  I do find the fact that case differences are shown, but then when you select any of them, they all come back in the results.  My preferred would be for it to be case insensitive, but dedupe in the dropdown to only one version of it.

**Comment by nhwCoder** [comment]
INFO: I updated/improved the "To Reproduce" steps above (to make it more precise)
=> I can reproduce it every time.


@jasonjac2 Can you please try again? Can you also test with exactly proposed tags above?

#### Versions
I am using the newest versions.
OneMore Version 6.5.2
OneNote 16.0.18025.20160
Win11 24H2

**Comment by stevencohn** [comment]
I can reproduce it but with the extra steps:

1. Open Search Hashtags, keeping All notebooks as the scope
1. Type * in search box
1. Change the scope to "This section"
1. Immediately, the duplication appears.
1. Moving the mouse over the drop-down forces a redraw of each item

Which tells me it's find and returning the right data. It's just a UI redraw problem... I'll investigate.
