### ISSUE TITLE
Remove line breaks and spaces in text (concatenate selected lines)

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#164]
**Is your feature request related to a problem? Please describe.**
Concatenate the selected lines and replace multiple consecutive spaces with one space

**Describe the solution you'd like**
Copy some text from this page https://tools.ietf.org/html/rfc6749#section-2.1
and try to concatenate the lines. You will get the idea. It is practically text artificially formatted as column

**Comment by 1001QAdotNET** [comment]
Thank you! I will test it and get back here if anything needs fixing

**Comment by stevencohn** [comment]
https://github.com/stevencohn/OneMore/releases/tag/3.15.1

**Comment by 1001QAdotNET** [comment]
This one also works OK.
