### ISSUE TITLE
Search and replace across all notes in notebook

### ISSUE THREAD

**Issue by hollowheights** [stevencohn/OneMore#1646]
# Problem to Solve

It seems to me the search and replace function will only affect the note currently open?

I have a custom tagging format that I now need to modify to use hashtags - because I've found OneMore which supports these. But doing it for now note at a time is a huge limitation in terms of speed.

# New Feature/Solution

The search and replace could have an option to specify which notebook segments to affect.

**Comment by hollowheights** [comment]
Is this likely to be added in the next few weeks or a long-term thing?
I'm just trying to decide if I should go through a few hundred notes and change the tags manually :)

**Comment by stevencohn** [comment]
As a native OneMore command? Not any time soon.

Are you a programmer? It could be done using OneMore's plug-in feature. That allows you to write a program or script to process the current page, pages within a section, a notebook, or all notebooks. It could be written as a PowerShell script or script or exe of your choice. More info here: https://onemoreaddin.com/commands/File%20Commands.htm

**Comment by stevencohn** [comment]
There are a couple of examples here https://github.com/stevencohn/OneMore/tree/main/Plugins
