### ISSUE TITLE
hashtag - Index option to include page and on-page links

### ISSUE THREAD

**Issue by jasonjac2** [stevencohn/OneMore#1649]
# Problem to Solve
Have the index option produce the full list of links, similar to the way it is shown in the search dialogue

My usecase is .... litter with a particular hashtag of items to review / act upon in this episode of work.

some pages have one item, some have 10. 
The search shows context for all of them ,  which is great.
I want to save that list , so use the index option.
I want to add a checkbox to the link to all occurances, so that I can work through them methodically and also make notes on the index page.

as you only get the page link, it makes this a bit more combersome.

I think it should  be a checkbox, or a new button (index and index all occurances).

**Comment by stevencohn** [comment]
I know this is an extra step, but what about just selecting all items in the list and then clicking the To Do Tag button?
