### ISSUE TITLE
Out of memory error with Resize image function

### ISSUE THREAD

**Issue by andyylin** [stevencohn/OneMore#165]
I'm running Resize on images a few megapixels and roughly 15 MB in size. After running the Resize command just a few times, I can no longer run it and the [OneMore.log](https://github.com/stevencohn/OneMore/files/5866872/OneMore.log) indicates an out of memory issue.

**Environment (if applicable):**
 - OneNote Version: O365 32 bit
 - OneMore Version 3.14

**Comment by stevencohn** [comment]
I tried the same with a 20MB file and watched the working set size of the dllhost.dll process and the OneNote process, both of which reset back to their original values prior to opening the resize dialog repeatedly. 

Are you doing anything specifying in that resize dialog?

**Comment by andyylin** [comment]
Yes, I'm setting Absolute dimensions to the same as the "Current size" and unchecking "Preserve original size" at 100% quality to force file size smaller.

I just tried this on a 17.1MB image, and it took about 20 seconds to resize.

**Comment by stevencohn** [comment]
I'll keep trying but can't seem to repro no matter what I do.

The slowness is due to the way the OneNote API works. It's just slow when you have very large images on a page; also when you have very long tables on a page. But the image resizing itself take just a little over a second for a 20MB image.

**Comment by andyylin** [comment]
Weird, I continued to use it and it seemed to work fine for other images on the page. Maybe there are some edge cases with the images being imported into OneNote. I suppose this issue could be closed.

**Comment by stevencohn** [comment]
Would you be willing to attach the suspect image to this ticket? Otherwise, I'll close this until we have more information.

**Comment by andyylin** [comment]
> Would you be willing to attach the suspect image to this ticket? Otherwise, I'll close this until we have more information.

How about I attach the .one page itself? But it's 172MB, I think I might need to use a public Dropbox link or something.

**Comment by andyylin** [comment]
Here's a Dropbox link: https://www.dropbox.com/s/xhofvmvnt34hegz/2021125.zip?dl=0

**Comment by stevencohn** [comment]
Yes, that a large page and I can reproduce the problem. Thanks

**Comment by andyylin** [comment]
Haven't seen this issue lately, closing for now. Thanks!
