### ISSUE TITLE
I want the keyword hit in the search results page to automatically have a yellow background

### ISSUE THREAD

**Issue by mengxin523** [stevencohn/OneMore#1657]
The new search function is good, and I hope to achieve better functions:
Refer to Onenote's built-in search function, when you click the search result list, you can automatically mark the hit search words on the open page, and use yellow as the background
This can quickly identify the location of the hit

For example, the following search 6684, then the search page inside the hit text will automatically have a yellow background：
![ShareX-2024-11-05 14-28-03 4446](https://github.com/user-attachments/assets/4a0af10e-47da-475e-9920-6cdce71f7e61)
![ShareX-2024-11-05 14-22-35 4444](https://github.com/user-attachments/assets/1ae41620-98b4-457f-8eb5-6b93c5d1de6c)

Thank you so much!

**Comment by stevencohn** [comment]
The search result highlighting capabilities are not exposed to OneMore and not customizable.

**Comment by mengxin523** [comment]
Have you already solved this problem, or will this function be added in the next version?
Thanks！

**Comment by stevencohn** [comment]
Marked as "not possible"

**Comment by mengxin523** [comment]
It's really a pity. Why not make a suggestion to Microsoft official?
