### ISSUE TITLE
Insert calendar indented under month header

### ISSUE THREAD

**Issue by G2G2G** [stevencohn/OneMore#166]
Currently, calendar is inserted right under the month name (header). 
If the calendar was indented to the right of month name, it could then be collapsed / expanded as needed. 
This can be easily done manually, but it's probably useful enough to be a default setting.

![Screenshot 2021-01-25 100515](https://user-images.githubusercontent.com/77124824/105723522-e1e75f00-5ef4-11eb-92a6-6929d86acd34.png)

**Comment by stevencohn** [comment]
Must capture your handwriting as a font!
