### ISSUE TITLE
No administrator permissions

### ISSUE THREAD

**Issue by Jeffrey-1949** [stevencohn/OneMore#1666]
Hello, I have a request, can you cancel the requirement of administrator permissions to install the package? I appreciate your efforts in developing this software, because I can't get administrator permissions on my work computer, and I believe others may encounter the same problem. If you can, thank you very much.

**Comment by stevencohn** [comment]
No, because it need to write to the Windows System Registry to register the COM add-in for OneNote.

**Comment by Jeffrey-1949** [comment]
but some other add-in for OneNote does n’t need admin permission.for example: https://onemark.neuxlab.cn/发自我的 iPhone在 2024年11月11日，19:40，Steven ***@***.***> 写道：﻿
No, because it needs to write to the Windows System Registry to register the COM add-in for OneNote.

**Comment by stevencohn** [comment]
OneMore does quite a bit more than OneMark. Part of OneMore's registration is to set up a trusted onemore:// protocol for each user on the machine so embedded custom URLs on a page can invoke OneMore commands, such as refreshing table of contents and other commands. These types of registrations can only be done from an elevated installer.

**Comment by Jeffrey-1949** [comment]
I get it! Thanks so much!







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "stevencohn/OneMore"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月13日(星期三) 晚上7:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [stevencohn/OneMore] No administrator permissions (Issue #1666)





 
OneMore does quite a bit more than OneMark. Part of OneMore's registration is to set up a trusted onemore:// protocol for each user on the machine so embedded custom URLs on a page can invoke OneMore commands, such as refreshing table of contents and other commands. These types of registrations can only be done from an elevated installer.

**Comment by godgglyp** [comment]
I have this situation, how can I install this plugin.

**Comment by Jeffrey-1949** [comment]
There seems to be no way.Part of OneMore's registration is to set up a trusted onemore:// protocol for each user on the machine so embedded custom URLs on a page can invoke OneMore commands, such as refreshing table of contents and other commands. These types of registrations can only be done from an elevated installer.发自我的 iPhone在 2024年11月27日，21:07，godgglyp ***@***.***> 写道：﻿
I have this situation, how can I install this plugin.
