### ISSUE TITLE
[Hashtag] Hashtag style false applied, if next hashtags follow after just one space

### ISSUE THREAD

**Issue by nhwCoder** [stevencohn/OneMore#1669]
# Problem to Solve

Hashtag style false applied, if next hashtags follows after just one space. 
But if there are two spaces then the style is correct applied.

# To Reproduce

1. Add these two tags with exact this text and between one space: #one #one
1. Add in next line these two tags with exact this text and between two spaces: #two  #two

1. Create a style with background color blue and apply it as hashtag style in Settings\Hashtags for “Apply custom style”.
1. Use “Scan hashtags” [Ctrl+Shift+F9]

RESULT
* For “#one #one” the space is FALSE set to background color blue.
* For “#two  #two” the spaces are correct NOT set to background color blue.

#### Version
OneMore Version 6.6.1 with OneNote 16.0.18129.20158

**Comment by stevencohn** [comment]
Corrected by #1663
