### ISSUE TITLE
Invert the current selection

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#167]
**Is your feature request related to a problem? Please describe.**
On a page with selected text invert the selection
**Describe the solution you'd like**
I would like to be able to select text (multiple lines in the current page -this currently possible) and then click on a OneMore button to inverse the selection

**Comment by stevencohn** [comment]
This feels like an extremely special case but it's an interesting problem to solve so I may take a look at it to satisfy my own curiosity. Low priority though

**Comment by 1001QAdotNET** [comment]
It is not that special
If I select all the headings and I change the style (bulk operation) then by inverting the selection I can change the text styling by inverting the selection and applying the style again. Saves a lot of work

**Comment by 1001QAdotNET** [comment]
This one seems to work properly
