### ISSUE TITLE
[Hashtag] “Run the scan now” => Not updating hashtags in current open page

### ISSUE THREAD

**Issue by nhwCoder** [stevencohn/OneMore#1670]
# Problem to Solve

“Run the scan now” => Not updating hashtags in current open page.

# To Reproduce

•	Open a page with some or many hashtags
•	Change style of hashtag in Settings\Hashtags for “Apply custom style”
•	Open “Schedule Hashtag Scanning” and Click “Select All” and select “Run the scan now”
•	Click “OK”
•	Wait until message “Scan completed” appears
•	RESULT: Styles of hashtags on current open page are NOT updated

#### Version
OneMore Version 6.6.1 with OneNote 16.0.18129.20158

**Comment by stevencohn** [comment]
Working as designed. The hashtag scanner will only modify a page if the page was changed in any way since the last scan. This is intentional so that every scan doesn't attempt to update every page containing hashtags which could be time consuming and create lag in the OneNote UI.

**Comment by nhwCoder** [comment]
Then I strongly propose to add a feature
* "[Shift+Alt+F10] Scan Hashtags (current page)"
that will update all hashtags of current page ONLY but always rescans it (not only if page was changed)
(even if nothing was changed and e.g. only the style was changed in Settings\Hashtags)

Advantages
* Much faster as "[Shift+Alt+F9] Scan Hashtag"
* See immediate result in page (can control if added hashtags are correct written)
* Proposal: Rename "[Shift+Alt+F9] Scan Hashtags" to "[Shift+Alt+F9] Scan Hashtags (all pages)"
