### ISSUE TITLE
Command Palette – Add incremental search (with C# source code)

### ISSUE THREAD

**Issue by nhwCoder** [stevencohn/OneMore#1680]
### Overview

OneMore provides the great feature "command palette" (thanks for implementing it!).

Every product providing such a command palette (e.g. VSCode, products on Web/macOS/Linux/Windows) implements incremental search instead of strict search for the command palette (have never seen anything different, except OneMore).

Below a description and working C# source code.

PS: Improved & corrected feature request for https://github.com/stevencohn/OneMore/issues/1677

### Incremental search - DESCRIPTION
Allows you to find commands even if your input only partially matches the command names
Sample entry: ‘Open File Word’
• Match: o
• Match: f
• Match: w
• Match: ofw
• Match: open wo
• Match: open fi wo
etc.

### Incremental search - SOURCE CODE (C# source code for NETFramework 4.x console app)

> [!NOTE]
>  Hope with this C# source code it is worth the climb :-)

#### Program.cs
```
using System;
using System.Collections.Generic;

// EVALUATE: Command palette "incremential search" like in Visual Studio Code
// - Enter characters included in commands = result matches

class Program
{
    static void Main()
    {
        var commands = new List<Command>
        {
            new Command("Open File"),
            new Command("Open File Word"),
            new Command("Open File Excel"),
            new Command("Open File Power Point"),
            new Command("Save File"),
            new Command("Close File"),
            new Command("Exit"),
            new Command("Find"),
            new Command("Replace")
        };

        Console.WriteLine("Enter command:");
        string input = Console.ReadLine();

        var matches = CharacterSearch.GetMatches(input, commands);

        Console.WriteLine("Did you mean:");
        foreach (var match in matches)
        {
            Console.WriteLine(match.Name);
        }
    }
}
```

#### Command.cs
```
public class Command
{
    public string Name { get; set; }
    public Command(string name)
    {
        Name = name;
    }
}
```

#### CharacterSearch.cs
```
using System;
using System.Collections.Generic;
using System.Linq;

public class CharacterSearch
{
    public static List<Command> GetMatches(string input, List<Command> commands)
    {
        return commands
            .Where(command => IsMatch(input, command.Name))
            .ToList();
    }

    private static bool IsMatch(string input, string command)
    {
        int inputIndex = 0;
        foreach (var ch in command)
        {
            if (inputIndex < input.Length && char.ToLower(ch) == char.ToLower(input[inputIndex]))
            {
                inputIndex++;
            }
        }
        return inputIndex == input.Length;
    }
}
```

**Comment by stevencohn** [comment]
Thank you for the code sample

**Comment by stevencohn** [comment]
Not sure I totally like it. Seems counter-intuitive to me. I may include it but make it an option to disable/enable

<img width="356" alt="image" src="https://github.com/user-attachments/assets/29b1a4f7-8bb3-4f7e-86f6-5cff82e3eace">

**Comment by nhwCoder** [comment]
Hi Steven

To have an option "Search mode" with "incremental match" vs. "exact string match" would be best/great.

PS: >TBH, I never really liked it in VSCode either.
First I hated it, step by step I understood the force.

(e.g. in your above example you get same as "exact string match" first and below more...).
(e.g. 'the force be with you']© when you type e.g. "a foo" or "atb" and have a lighting-fast match in many hundreds)

BUT its not about like/dislike
==> DE-FACTO every other command palette has this implemented, so to have an option to configure would be great.

**Comment by nhwCoder** [comment]
BTW: Visual Studio 2022 uses also "incremental search" for their command palette [Ctrl+Shift+P]
