### ISSUE TITLE
OneMore causing OneNote to fail to open and giving errors when it does open....

### ISSUE THREAD

**Issue by DudeThatsErin** [stevencohn/OneMore#1681]
# Problem to Solve

I keep getting these messages:
![image](https://github.com/user-attachments/assets/d1d5df12-46c2-4512-9c90-92ef4af7caa1)

When OneNote does open, I get the following error:
![image](https://github.com/user-attachments/assets/99d740df-80f9-4c07-a635-7f6ff784c12d)

I haven't done anything crazy with my notes lately. Nothing out of the ordinary and nothing changed in my notes.

# To Reproduce
1. Don't have onenote open
2. Put your computer to sleep
3. Wake it back up
4. Attempt to open onenote and you get the first screenshots above.

I generally put my computer to sleep every night and then wake it up in the morning and then restart it/shut it down about 1-2x a week.

I have to reboot my computer and before I open OneNote, uninstall OneMore. Then OneNote functions correctly. With OneMore installed if I put my computer to sleep and wake it back up, it doesn't open.

I'm having to keep OneMore uninstalled until this is fixed. I updated it and latest version has this issue.

~~I have zero clue what is causing this but I do know that~~ I cannot even uninstall OneMore...
![image](https://github.com/user-attachments/assets/f3736ee0-2273-4057-8736-93725a244205)
![image](https://github.com/user-attachments/assets/a099c3a1-b4b9-4b3f-a046-5f9c09ee0837)

I tried twice. I am the only user with admin privileges.
```
======================================================================
starting action: --uninstall .. 11/22/2024 2:43:15 PM
OneMore installer running as user NT AUTHORITY\SYSTEM (S-1-5-18) elevated
on behalf of WORKGROUP\system

Unregister... version 6.5.2

ShutdownOneNoteAction.Uninstall ---
dllhost process not found
stopping process ONENOTE, pid 4568
uninstall failed; error unregistering
System.ComponentModel.Win32Exception
Message: Access is denied
Source: System
StackTrace:    at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.Kill()
   at OneMoreSetupActions.ShutdownOneNoteAction.StopOneNote()
   at OneMoreSetupActions.ShutdownOneNoteAction.Uninstall()
   at OneMoreSetupActions.Program.Uninstall()
TargetSite: [System] System.Diagnostics.ProcessManager::OpenProcess()


======================================================================
starting action: --uninstall .. 11/22/2024 2:46:30 PM
OneMore installer running as user NT AUTHORITY\SYSTEM (S-1-5-18) elevated
on behalf of WORKGROUP\system

Unregister... version 6.5.2

ShutdownOneNoteAction.Uninstall ---
dllhost process not found
stopping process ONENOTE, pid 4568
uninstall failed; error unregistering
System.ComponentModel.Win32Exception
Message: Access is denied
Source: System
StackTrace:    at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.Kill()
   at OneMoreSetupActions.ShutdownOneNoteAction.StopOneNote()
   at OneMoreSetupActions.ShutdownOneNoteAction.Uninstall()
   at OneMoreSetupActions.Program.Uninstall()
TargetSite: [System] System.Diagnostics.ProcessManager::OpenProcess()
```

# Expected Behavior

To be able to uninstall and/or use OneNote.

# Environment (if applicable)

 - OneNote Version: O365 latest version
 - OneMore Version ~~6.5.2~~ 6.6.1 -> Updated during the troubleshooting process.
 - Windows 11 latest version

Computer is older with only 16gb RAM. Could this be a memory issue? Doesn't seem like onenote is using a lot of ram. Edge uses more RAM than it by a long shot.

**Comment by jasonjac2** [comment]
Hi, what happens if you reboot your pc, leave it settle (as in everything that automatically launches does so), then you launch OneNote assuming it didn't auto start?
Sleeping won't generally change the state of running programs, BUT Onenote does have this nasty habit of not closing properly and that error you are seeing is what happens when it has stalled when closing and you try to start a new instance.
The callback issue seems to be an issue if you have an instance of onenote running and you start a new one using the taskbar rather than the "in onenote command" for a new window 
![image](https://github.com/user-attachments/assets/5265d7a7-0064-47cb-976a-e77c6945c727)
ctrl+m.

**Comment by stevencohn** [comment]
Is it possible that the most recent page that you updated and OneNote is trying to display when it first loads, includes a link to a paragraph containing an equation? https://github.com/stevencohn/OneMore/issues/1556

If so, then start OneNote without OneMore, delete that linked paragraph or delete the page, then reinstall OneMore

**Comment by DudeThatsErin** [comment]
Nope I don’t have any links on that page.
Sent from my iPhone

On Nov 23, 2024, at 7:37 AM, Steven ***@***.***> wrote:

﻿

Is it possible that the most recent page that you updated and OneNote is trying to display when it first loads, includes a link to a paragraph containing an equation? #1556<https://github.com/stevencohn/OneMore/issues/1556>

If so, then start OneNote without OneMore, delete that linked paragraph or delete the page, then reinstall OneMore

**Comment by DudeThatsErin** [comment]
When I reboot and open OneNote it works fine. The issue only occurs after I “end the task” for OneNote, put my PC to sleep, then try to open OneNote. Without OneMore installed OneNote opens fine with no issues after sleeping, with OneMore installed, it does not.

Sent from my iPhone

On Nov 23, 2024, at 4:08 AM, Jason Chapman ***@***.***> wrote:

﻿

Hi, what happens if you reboot your pc, leave it settle (as in everything that automatically launches does so), then you launch OneNote assuming it didn't auto start?
Sleeping won't generally change the state of running programs, BUT Onenote does have this nasty habit of not closing properly and that error you are seeing is what happens when it has stalled when closing and you try to start a new instance.
The callback issue seems to be an issue if you have an instance of onenote running and you start a new one using the taskbar rather than the "in onenote command" for a new window
image.png (view on web)<https://github.com/user-attachments/assets/5265d7a7-0064-47cb-976a-e77c6945c727>
ctrl+m.

**Comment by stevencohn** [comment]
Yeah, don't do that! 😉. OneMore runs in a secondary process, separate from OneNote. This is how OneNote add-ins work. If you close OneNote, as you should, it will close that secondary process automatically. Or just leave OneNote running and put the computer to sleep.

**Comment by DudeThatsErin** [comment]
Good to know. Just reinstalled and tested by just using the X and it seems to open up just fine now.

Thanks!
