### ISSUE TITLE
My Style "default" - False name "Orange" instead "Default" [With solution]

### ISSUE THREAD

**Issue by nhwCoder** [stevencohn/OneMore#1689]
# Problem to Solve

My Style "default" - False name "Orange" instead "Default"

### Solution
File: "C:\Users\<username>\AppData\Roaming\OneMore\Themes\Default.xml"

FROM: <Theme key="Default" name="Orange" 
TO: <Theme key="Default" name="Default"

**Comment by stevencohn** [comment]
This is not true. The default.xml file is used to record the last style you've used. This is different than the Standard.xml file that replicates the built-in OneNote styles.

**Comment by stevencohn** [comment]
This is not true. The default OneMore styles are orange.

**Comment by nhwCoder** [comment]
The default set colors can be now orange (OR: red/gold/blue/etc OR: green-background).
BUT would it not be still better to call it "default" because it is the "default" style and even the filename is "default.xml".

PS:  Maybe in two years the new hyped default-color is "puple-red" in every UX and then 5 years later "grey" as default.
PSS: There is an "orange.xml", here the name "orange" is correct. That was the original reason for my confusion, because I saw "orange" and was thinking the file "orange.xml" is opened but it was "default.xml".

**Comment by stevencohn** [comment]
The file in source code is called DefaultStyles.xml. But the contents is what you see as the Orange theme.

It's been like this for years. Leave it.
