### ISSUE TITLE
Suggestion: Custom names for favorites

### ISSUE THREAD

**Issue by G2G2G** [stevencohn/OneMore#169]
Currently there seems to be no way to give custom names to the entries in Favorites.

This is an issue when using a notebook template & ending up with multiple pages with same names across different notebooks (e.g. "Action Items").

**Comment by stevencohn** [comment]
temp workaround, hover over the item in the menu and it will show you the full path of the page

**Comment by valuex** [comment]
I think the final solution would be an-embedded launcher, that user can visit the favorite page just by a few letter, and the frequency is also recoorded.
