### ISSUE TITLE
Colors on Calendar are Inverted

### ISSUE THREAD

**Issue by DudeThatsErin** [stevencohn/OneMore#1694]
# Problem to Solve

When you use the Snippet to create a monthly calendar, the colors are inverted in dark mode. I exclusively use Dark Mode and I just tested light mode for this video and light mode is fine, it is just dark mode that has the issue.

# To Reproduce

1. Click on File
2. Click on Account
3. Set Theme to Light Theme
4. Go to your Note
5. Click on Snippets
6. Click on Calendar
7. Click on the color
8. Choose a dark color
9. Press Ok to create calendar - You should see the correct color
10. Click on File
11. Click on Account
12. Set Theme to any dark theme (I use black)
13. See error in note. Immediately the color inverts.

# Expected Behavior
The color to stay the same regardless of theme choice. I don't see a reason to invert the color.

# Screenshots
Video: https://imgur.com/KRYIPkC

# Environment (if applicable)

 - OneNote Version: O365 64-Bit
 - OneMore Version Latest version - just updated recently.

**Comment by stevencohn** [comment]
This is not a bug. It's the way OneNote works. It's the same effect when you click the View/Switch Background button on the ribbon. OneNote "inverts" the colors, although not exactly an RGB or HSL inversion. I wrote [an article on it here](https://onemoreaddin.com/developers/TechNote%20-%20Colors.htm).

**Comment by DudeThatsErin** [comment]
Thanks!
