### ISSUE TITLE
great Tool it's a pity not availible for MAC OS

### ISSUE THREAD

**Issue by StefanRudat** [stevencohn/OneMore#1697]
# Problem to Solve

Provide a clear and concise description of the problem, e.g. I'm always frustrated when...

# New Feature/Solution

Provide a clear and concise description of what you want to happen.

## Alternative Solutions

Provide a clear and concise description of any alternative solutions or features you've considered.

# Additional Context

Provide any other context or screenshots about the feature request here.

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
I do not have a MAC so am unable to developer or publish for apps for the MAC. Sorry.

**Comment by Doublonmousse** [comment]
Is there any documentation out there to develop plugins for onenote on mac ? I know there's at the very least ways to do plugin on word for mac (zotero), but for onenote I'm not sure it's possible (?).

I'm not sure how different the api is for developing a plugin between word and onenote (be it on windows or mac)
