### ISSUE TITLE
Camera Images

### ISSUE THREAD

**Issue by Andreas-Kainz** [stevencohn/OneMore#1698]
# Problem to Solve

add camera images with onenote android and want to export all images (with gps coordinates) of one page.

# New Feature/Solution

export all images with all image informations (gps coordinates) so that I can store the images in OneNote, but I can have the origin files also on an external hard drive.

**Comment by stevencohn** [comment]
The quick testing I've done indicates that OneNote removes many EXIF properties, including GPS coordinates, whenever that image is stored on a OneNote page.

So I do not think this information survives a round-trip into and out of OneNote.

**Comment by Andreas-Kainz** [comment]
Thanks for the Feedback. Good to know. And sad that the information wasn't Stores.
