### ISSUE TITLE
Clarification needed on OneMore Wiki page about arguments in the "Run Plugin" dialog.

### ISSUE THREAD

**Issue by GrantRobertson** [stevencohn/OneMore#1699]
This is primarily a request for improved documentation. Once we figure out the exact answer, I can suggest better wording for that documentation. The page in question is: https://onemoreaddin.com/commands/--%20Plugins.htm

I am not quite clear on the meaning of the various "Arguments" fields in that dialog, and the order in which they will be applied when launching the user-written program. 

## Issue 1.
Step 1, in the workflow, says to:
> Create a plugin program that accepts **one** command line argument; the argument will specify the path to a file containing the page XML.  (Emphasis mine.)

And yet, the [Export-PageInfo.ps1 PowerShell script, in this repo](https://github.com/stevencohn/OneMore/blob/main/Plugins/Export-PageInfo.ps1) clearly accepts **two** arguments. It seems to me that the documentation should say that the program/PowerShell-Script/whatever _should_ always accept the path to the OneNote .XML file as the **first** argument. Currently, the documentation kind of implies that there can only ever be only **one** argument.

## Issue 2.
Step 2, in the workflow, says to:
> Run the Plugin command, specifying the path to the program and **any other arguments**.

Besides the fact that Step 1 said that there would only be **one** argument, this statement is incredibly vague. Where do I enter those "any other arguments"? In the "User Arguments" field? At the end of the "Arguments" field? What happens if I put an additional argument in either of those locations? What if I put an argument at the beginning of the "Arguments" field?

## Issue 3.
It seems that what the documentation needs is an explanation as to the full order of where all the arguments placed **where** in all the fields. 

## My Conjecture:
(Based upon how I would have designed it, if I was anywhere near as smart as you. 😜)

### The "Command" field:
- This can be a full path to an executable file. Or it can be just the name of the executable as one would type it on the command line, if said executable file is on the path, as specified in any of the Windows PATH environment variables.
- One can simply type the command, or full path to the command in the field. Or one can click the [...] button to open a file selector dialog to find and choose the executable.
- Normally, this would be the command to launch PowerShell or Python or some other scripting environment, just as one would type it on a command line. However, it is also entirely possible to have written and compiled a whole executable program to implement the desired functionality. In which case, this field will contain the path to that custom executable. Said executable program must be able to be launched directly from the command line.
- No other arguments can be placed in this field. Only the path to the script launching command or the executable program. All arguments will either be automatically entered by OneMore, or will be entered in subsequent fields.

### The "Arguments" field:
- Normally, this would be the argument(s) that need to be passed to the above command/executable in order to get it to find and launch the script that the command is supposed to execute. 
-- For instance: For a PowerShell script, one needs to enter the -file or -f flag, plus the full path to the PowerShell script to be executed, as shown in the example dialog.
-- It is also possible to insert other arguments **before** this -file flag and argument pair, if the script executing command (like PowerShell or Python) requires them. That is very rare.
-- When used in this manner, there _should_ be no other arguments after the argument that specifies the path to the script file. This is because OneMore will then insert the full path to the OneNote .XML file after the end of the contents of this field. (Now, one _could_ have designed one's script to accept the full path to the .XML file as the second or third argument. But that would just lead to inconsistencies in one's scripts that would become unmanageable. It is best to just always design one's scripts to accept the full path to the OneNote .XML file as the script's first argument.)
- However, if the user has compiled an independent executable program, which is specified in the "Command" field, then this field may not be required, depending upon the design of said executable program and what arguments it may accept.
- Essentially, the arguments in this field are inserted in the command line, just after whatever is in the "Command" field, and just before where OneMore inserts the full path to the actual OneNote .XML file, as described next.

### The full path to the OneNote .XML file is inserted here.
- OneMore always inserts the full path to the OneNote .XML file, into the full command line, here.
- (_I am not sure if OneMore always inserts a regular Windows path name or an XML XPATH, or some combination thereof.  This also needs to be clarified._)

### The "User Arguments" field:
- Normally, this would be any additional arguments that the script is designed to accept. Naturally, one would have to have written the script to accept these arguments. 
- These will always be inserted **after** the full path to the OneNote .XML file. 
-- That's the main reason to always design your scripts to accept the path to the .XML file as the first argument, then accept these arguments after that. This method just makes it easier to logically separate your different sets of arguments. (Can you mix things up and insert other script arguments at the end of the "Arguments" field. Sure, But why in the world would you want to give yourself that pain. Just stick to the normal plan. Your life will be easier.)

## Possible dialog redesign:
A slight redesign of the dialog would make almost all of this very intuitive. Rather than fields named "Arguments" and "User Arguments," you could change the names to "Command Arguments" and "Script Arguments." Or simply make the dialog look like this:

> Command: ____________________[...]
> Argument Set 1: ____________________
> **Path to the OneNote .XML file is inserted here.**
> Argument Set 2: ____________________

This would clarify that all that is really happening is that OneMore is simply building a command line statement, while inserting the path to the OneNote .XML file somewhere in the middle. Then, the documentation could simply be altered to describe the details around that.

## For context:
I am the guy who made [this post on Reddit about OneNote breaking links when we move pages and section groups around in OneNote](https://www.reddit.com/r/OneNote/comments/19at4j7/warning_do_not_create_links_to_specific/). I deleted the Reddit account that I used to make that post, because I had far too many super snarky comments using my real name as my user name. Let's just say that I did not want to start attracting troll armies. So I decided to create a few, more anonymous, Reddit accounts. (And, I've decided to be less snarky.)

**Comment by stevencohn** [comment]
Hi @GrantRobertson. Thanks for the feedback. I made some changes.

**Comment by GrantRobertson** [comment]
So, no fundamental flaws with my basic conjecture?

**Comment by stevencohn** [comment]
You got it right
