### ISSUE TITLE
WPF?

### ISSUE THREAD

**Issue by theClueless** [stevencohn/OneMore#170]
**How can I help you?**
Hi, first of all great project!
I want to start and enhance onenote to better fit my GTD practices, OneMore has some much great reference.
I was wondering if it is possible to add WPF controls instead of winforms into onenote and if so wondering why onemore is using winforms?

THE FINE PRINT
This is a hobby project that I started for myself. I'm happy to take requests and will promise to consider each one carefully but offer no guarantees that I will ultimately agree to their usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
Yes, WPF can be used. I started using WinForms simply because I'm more familiar with it and it gets the job done

**Comment by theClueless** [comment]
Thanks :)
