### ISSUE TITLE
Docs improvement - Snippet ToC

### ISSUE THREAD

**Issue by jasonjac2** [stevencohn/OneMore#1702]
When refreshing the Section and Notebook ToCs.....
By experimenting I realised that the Section and Notebook ToC's allow you to have containers that don't get wiped. 
I had originally thought it recreated the page, but then realised the Date doesn't get updated (which I think it should).

So docs: state that once the page is created, if you click refresh:
- Only the container with the ToC gets refreshed - other content can remain (which is great)
- the page date doesn't get update
Are there any other rules or observations (like it has to be the 1st container......)

Thanks for all your hard work as always.

**Comment by jasonjac2** [comment]
Thanks for the clarification.  I actually update the date on screen when I do my monthly refresh of them all.

I guess the reason I hadn't realised about the other containers not getting deleted was that initially I was creating new pages everytime and only recently hit the refresh button.

**Comment by stevencohn** [comment]
Maybe it would be better (more flexible) to add a command to update the dateTime that you could bind to a key sequence? That would still be a couple of actions to update the ToC and the time, but would be slightly faster and could be used in other scenarios??

**Comment by jasonjac2** [comment]
" a command to update the dateTime" 
that would be great,
