### ISSUE TITLE
Remove leading dots from page links in TOC

### ISSUE THREAD

**Issue by G2G2G** [stevencohn/OneMore#171]
The leading dots prevent TOC from acting as an outline - i.e. links to the lower level pages can't be collapsed under upper levels.

Having that ability would be very useful for a quick navigation in a TOC of a section with many similar pages (lecture notes, diary, project, etc.)

Perhaps this could be done as an option ?

**Comment by stevencohn** [comment]
It's not the dots. It's about indentation. And the layout of the outline represents the notebook or section structure. So what you may be seeing is a bold line, immediately followed by another line on the same indentation level; this is a section group followed by its first section name. It seemed to make sense to indent them this way to avoid overly indented outlines that scroll off the right hand edge of the page
