### ISSUE TITLE
Weird behavior when trying to remove leading dots

### ISSUE THREAD

**Issue by G2G2G** [stevencohn/OneMore#172]
Tried to use "Search and replace" to remove leading dots from TOC.

I put two dots in the "Find what" field and left the "Replace with" field blank.

The desired result was getting rid of leading dots (which are done in the multiples of two) while preserving periods in page names. 

The outcome was... well they say a picture is worth a thousand words...
<img width="320" alt="Screenshot 2021-01-29 204256" src="https://user-images.githubusercontent.com/77124824/106343346-e0aa8f00-6272-11eb-9468-b515d8221d00.png">
<img width="301" alt="Screenshot 2021-01-29 204330" src="https://user-images.githubusercontent.com/77124824/106343351-e43e1600-6272-11eb-841a-d989a1ba6c05.png">
<img width="128" alt="Screenshot 2021-01-29 204440" src="https://user-images.githubusercontent.com/77124824/106343354-ea33f700-6272-11eb-9f98-eb3b1baa3d21.png">

**Comment by stevencohn** [comment]
https://github.com/stevencohn/OneMore/releases/tag/3.15.1
