### ISSUE TITLE
Is it possible to enable detailed debugging with some explicit time stamps?

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#173]
I am experiencing some serious slowness when using the rolling over highlighter.
It is true that these are rather large pages but I am hopping that this might give you a clue where things could be improved if there is any point where they can be improved. 

What I am seeing is a lag between the time when I use the shortcut (Alt+1, the highlighter is the first tool on my quick access bar) and the time when it actually reacts in any way (which is by showing a spinning wheel) and then like a half of that time spent till it renders the change (10 sec in total)

**Comment by stevencohn** [comment]
Yes, I can easily add logging around the loading, action, saving of commands....

**Comment by stevencohn** [comment]
This shows the times for the highlighter command on a sizable page, running it three times in a row

```
13456:1] Running command HighlightCommand
13456:1] ..highlight - loaded page @ 00:00.63
13456:1] ..highlight - in-memory page modified @ 00:00.00
13456:1] ..highlight - saved page @ 00:06.18
13456:1] Running command HighlightCommand
13456:1] ..highlight - loaded page @ 00:00.57
13456:1] ..highlight - in-memory page modified @ 00:00.00
13456:1] ..highlight - saved page @ 00:06.48
13456:1] Running command HighlightCommand
13456:1] ..highlight - loaded page @ 00:00.60
13456:1] ..highlight - in-memory page modified @ 00:00.00
13456:1] ..highlight - saved page @ 00:06.80
```

You can see that loading the page is pretty quick, about half a second
Updating the content is very fast, less than a millisecond
Saving the page is over 6 seconds. This last step is using the OneNote Interop API directly so there's nothing I can do to optimize this call. It is what it is I'm afraid.

**Comment by 1001QAdotNET** [comment]
ok great I can use it to make a decision regarding the tipping point when I should create a new doc because the whole thing becomes slow. If I do the same (highlight) manually using the context menu option that is very fast. Where is the difference ? Are they not using the same API?

**Comment by stevencohn** [comment]
No, the context menu highlight is built-in functionality within OneNote itself so doesn't go through an Interop hop at all. OneMore doesn't even know it's happening.
