### ISSUE TITLE
Remove Inks does not work all the time

### ISSUE THREAD

**Issue by yang-james** [stevencohn/OneMore#1730]
I am using OneNote 2016. I need to remove all the inks on the page. When I use the "Remove Ink" command, it does not remove the all the inks. I notice that it removes the inks that I add freshly, not the ones already on the page before I install OneMore.

**Comment by stevencohn** [comment]
Can you please export the page as XML or .one and attach it here (do not embed the XML as Github will corrupt it)

**Comment by yang-james** [comment]
Here the the .one file zipped.
[Exercise 4.zip](https://github.com/user-attachments/files/18255151/Exercise.4.zip)
I also tried the Gem addin. It has a "Remove All Inks" button under the "Objects" tab actually works.
