### ISSUE TITLE
Bugs in coloring python code

### ISSUE THREAD

**Issue by hello-ning** [stevencohn/OneMore#1732]
When coloring python code, triple-quote comments will cause all subsequent code coloring to fail; here's an example:

![test](https://github.com/user-attachments/assets/b371239b-1e54-485f-991a-5a258a65d911)

**Comment by stevencohn** [comment]
Work-around until fixed - as a second step, select the code from `if n == 2...` down to the bottom and colorize just that separately.

**Comment by hello-ning** [comment]
Okay, thanks for the reply.
