### ISSUE TITLE
Custom Heading Styles Don't Honor Font Size 11

### ISSUE THREAD

**Issue by dwillis77** [stevencohn/OneMore#1738]
# Problem to Solve

Strange issue - it seems that if we create a custom style, of type "heading" with a font size 11, it will ignore the font size. We can set other attributes, such as bold and italic and those are honored but the font size is not.

The strange part is what it _does_ use as the font size instead - I haven't quite figured that out yet. In one test it used font size 14, in another it did 12. The best I can tell, it seems like it might be using the font size of the heading "in front" of it (meaning the heading one spot higher in the list), because the test I did that resulted in font size 12 had a heading above it with font size 12, and the one that resulted in font size 14 had a heading above it w/ font size 14. That part is a total guess though.

# To Reproduce

1. Create a custom style, either from some existing text or from scratch. Make sure to set type as "Heading - include in TOC". Reorder as necessary to put it at the top of the list or wherever you want it in relation to the other heading styles. Configure the other attributes of the heading the way you want, but make sure font size is set to 11.
2. Apply the new custom style to some text.
3. See that all the attributes are properly applied except the font size - font size will be something other than 11 (as noted above, I haven't figured out exactly where it gets the size that it does use from, but my hypothesis is above).

# Expected Behavior

The style should apply all configured attributes to the selected text, including font size.

# Environment (if applicable)

 - OneNote Version: Office 365 version 2402 (build 17328.20648) semi-annual channel, 64-bit
 - OneMore Version 6.6.1

**Comment by stevencohn** [comment]
I could no reproduce this, trying a bunch of ways.
I've created a style as shown here, ordered just after Heading 6

<img width="340" alt="image" src="https://github.com/user-attachments/assets/faf8cb13-0e28-4591-b085-e833e148f8ce" />

And then tried to make it break:

![1738-demo](https://github.com/user-attachments/assets/a53d4967-6a9e-433b-80cf-f0aa386416a3)

**Comment by dwillis77** [comment]
In your screenshot it shows font size 16 though - from what I've seen this only applies to heading styles with font size 11. Any other font size is honored properly. Only font size 11 is not.

**Comment by stevencohn** [comment]
Ah yes, it seems to be whatever your default font size is. My default font size is 11.5 (because I'm wicked old!) So if I set the size of the heading to 11.5, it gets rendered as 20. I'll check it out. Thanks.
