### ISSUE TITLE
Characters in paragraph style applies to whole paragraph

### ISSUE THREAD

**Issue by SnowSteve98** [stevencohn/OneMore#174]
Hi, I have an issue with custom styles.
If I set the style to "Character - word in paragraph", select just some words from a paragraph and apply the style it gets applied to those words only (which is the desired behavior). 
Problem is that as soon as I apply any other style to any other part of the page the style applied before extends to the whole paragraph instead of staying only on the selected words.
Also it would be nice to be able to use custom fonts
![image](https://user-images.githubusercontent.com/78382187/106512120-78a5b400-64d1-11eb-8ca1-4dc1fe79c22f.png)
![image](https://user-images.githubusercontent.com/78382187/106512156-852a0c80-64d1-11eb-8aa6-ee27bff12f2a.png)

(If you look at the images above you can see that the first line is only partially styled, but when I apply the style after, the whole paragraph changes)

**Comment by stevencohn** [comment]
I can't seem to reproduce this. Trying to replicate what you did, I applied the style to the first word in the first line:

![image](https://user-images.githubusercontent.com/9964757/106890559-7ef58500-66b7-11eb-88fb-16e1aa7a2a62.png)

And then applied it the second main bullet but it didn't change the first line:

![image](https://user-images.githubusercontent.com/9964757/106890682-acdac980-66b7-11eb-80be-2e614731cd3e.png)

What do you mean "custom fonts". You can choose a font for each style.

**Comment by SnowSteve98** [comment]
Ok so first of all thank you very much for your answer!
Secondly i don't know why but today all of the problems I mentioned seem to have disappeared. 
I already tried to reboot multiple times and it didn't work so I don't know what fixed it, but the good thing is that it's now working great.
Thank you again
