### ISSUE TITLE
Crop window opens with top beyond the screen

### ISSUE THREAD

**Issue by G2G2G** [stevencohn/OneMore#175]
**Describe the bug**
When I open Crop, the top part of the window is pushed beyond the boundaries of the screen. Pulling on the lower right corner to resize it forces the window to "jump" in place.
This is happening on two separate computers.
<img width="960" alt="Screenshot 2021-02-01 195229" src="https://user-images.githubusercontent.com/77124824/106536790-1647b600-64c7-11eb-8987-5cfb45a37976.png">

**Comment by andyylin** [comment]
This happens to me too, at least for large images. Also, when I try to use the selection tool to crop, every time I start selecting the image jumps back to the top left, making it impossible to select the region I want to crop.

**Comment by stevencohn** [comment]
https://github.com/stevencohn/OneMore/releases/tag/3.15.1
