### ISSUE TITLE
Make Search and replace remember the last search and replace options

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#177]
**Is your feature request related to a problem? Please describe.**
Make Search and replace remember the last search and replace
**Describe the solution you'd like**
Make Search and replace remember the last search and replace
Or even better add history to this feature
I don't think that this needs any further explaining but the Notepad++ Search and replace can be used as an example for many features that can be added

**Comment by stevencohn** [comment]
https://github.com/stevencohn/OneMore/releases/tag/3.15.1

**Comment by stevencohn** [comment]
This may be a known problem, trying to track it down... Let me know if anyone notices that the Ctrl-H keypress doesn't work the first time. But if Search and Replace is invoked from the menu then Ctrl-H will work after that.

**Comment by 1001QAdotNET** [comment]
yes I have been experiencing that for a while but got too lazy (or too busy) to report it and it was on and off not consistent
Restarting onenote seems to ameliorate the symptoms for a while

**Comment by 1001QAdotNET** [comment]
yeah that bug is still there ...I just hit it again

**Comment by 1001QAdotNET** [comment]
here are the log errors after restarting.
Still refusing to work
```
9064:11] Running command SearchAndReplaceCommand
9064:11] Error running command SearchAndReplaceCommand
9064:11] System.ComponentModel.Win32Exception
Message: The handle is invalid
Source: System.Windows.Forms
StackTrace:    at System.Windows.Forms.Control.GetSafeHandle(IWin32Window window)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at River.OneMoreAddIn.Commands.SearchAndReplaceCommand.<Execute>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.CommandFactory.<Run>d__5`1.MoveNext()
TargetSite: [System.Windows.Forms] System.Windows.Forms.Control::GetSafeHandle()


9064:13] Running command SearchAndReplaceCommand
```

**Comment by 1001QAdotNET** [comment]
I could see the dialog for a fraction of a second and then it disappeared ..I think it is somewhere hidden and it holds the focus for the app you cant escape it

**Comment by 1001QAdotNET** [comment]
Error when loading onenote
Second restart worked fine

9064:8] ..Starting dllhost 9064, en-US/en-US, v3.15.2, OneNote 15.0, Office 15.0
9064:8] ..OnConnection(ConnectionMode:ext_cm_Startup,1)
9064:8] ..OneAddInsUpdate(custom[]:0)
9064:12] ..building ribbon
9064:12] ..building ribbon colorizer commands
9064:12] ..building ribbon groups
9064:12] ..building context menu
9064:12] ..building context menu search engines
9064:12] ..RibbonLoaded()
9064:12] ..OnStartupComplete(custom[]:0)
9064:12] ..OneNote backup folder:: C:\Users\1001qa\AppData\Local\Microsoft\OneNote\15.0\Backup
9064:12] ..OneNote default folder: C:\Users\1001qa\Documents\OneNote Notebooks
9064:12] ..OneNote unfiled folder: C:\Users\1001qa\Documents\OneNote Notebooks\My Notebook\Quick Notes.one
9064:12] ..defining hotkeys
9064:12] ..error starting add-on
9064:12] ..System.InvalidOperationException
Message: Invoke or BeginInvoke cannot be called on a control until the window handle has been created.
Source: System.Windows.Forms
StackTrace:    at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at River.OneMoreAddIn.HotkeyManager.RegisterHotKey(Action action, Keys key, Hotmods modifiers)
   at River.OneMoreAddIn.AddIn.RegisterHotkeys()
   at River.OneMoreAddIn.AddIn.OnStartupComplete(Array& custom)
TargetSite: [System.Windows.Forms] System.Windows.Forms.Control::MarshaledInvoke()

9064:12] OnBeginShutdown(0)
9064:12] ..shutting down UI
9064:12] ..OnDisconnection(RemoveMode:ext_dm_HostShutdown,0)
9064:12] ..disposing 5 streams
9064:12] ..closing log

**Comment by stevencohn** [comment]
Thanks for this. I'll take a look
