### ISSUE TITLE
Add button for SQL syntax highlighting

### ISSUE THREAD

**Issue by 2thankyous** [stevencohn/OneMore#179]
It looks like you have [SQL defined as a language for syntax highlighting](https://github.com/stevencohn/OneMore/blob/master/OneMore/Colorizer/Languages/sql.json), but there is no button in the ribbon. Can this button be added? 

Just found your project today and kicking the tires on it. Thanks for sharing!

**Comment by stevencohn** [comment]
Click the OneMore menu
Click Edit
Click Colorize
Click SQL

**Comment by 2thankyous** [comment]
It's not there for me. OneMore 3.15.1 OneNote 16.0.13628.20330 64-bit
![image](https://user-images.githubusercontent.com/65001522/107154541-757f4d80-6941-11eb-9f10-3e6b6275ebb3.png)

**Comment by stevencohn** [comment]
Oh my! You're right. I'll have another release later today

**Comment by 2thankyous** [comment]
Thanks for adding! I've not used OneNote add-ins other than Onetastic on occasion. I don't like the subscription model so I'm not a fan. A friend at work had just shown me a different syntax highlighting add-in on GitHub. I didn't like how it worked so I set off looking for other add-ins. Gem is a mess. Yours is the best out there. Keep up the awesome work. I'll be kicking the tires for a bit and then will likely try out that donate button. Thanks again!
