### ISSUE TITLE
Update bug ?

### ISSUE THREAD

**Issue by G2G2G** [stevencohn/OneMore#180]
I tried to install this twice already...

<img width="518" alt="Screenshot 2021-02-06 183336" src="https://user-images.githubusercontent.com/77124824/107132111-3e119200-68aa-11eb-8e4b-d34d533f46f9.png">

**Comment by stevencohn** [comment]
It the right software but I just set the version incorrectly. I'll release a patch but you can still use this release

**Comment by stevencohn** [comment]
New installer is available for 3.15. The About box should show 3.15 after you install
