### ISSUE TITLE
Adding OneMore to Quick access toolbar make OneNote lagging

### ISSUE THREAD

**Issue by jakkaas** [stevencohn/OneMore#181]
**Describe the bug**
If I add complete OneMore or few commands of OneMore to Quick Access toolbar, OneNote becomes lagging. Especially typing in OneNote Lags.

**To Reproduce**
1. Go to 'OneMore Icon on Home Tab'
2. Right Click on 'OneMore'
3. Click add to Quick Access toolbar
4. Type in OneNote and the typing lags

**Expected behavior**
The typing shouldn't be lagging

**Screenshots**

**Environment (if applicable):**
 - OneNote Version: O365, also 32bit
 - OneMore Version 3.15.2

**Additional context**
Add any other context about the problem here. Attach page XML file or the app log file as appropriate. You can find the log file here: %localappdata%\temp\OneMore.log

**Comment by stevencohn** [comment]
I've investigated this in the past and tried once again here. Do to the limitations in the way the OneNote interop APIs work there's nothing I can do unfortunately. The API doesn't provide the events or calls needed to make this more efficient.

The only alternative is to pop up a dialog box whenever you invoke a command that doesn't have the correct focus on the OneNote UI for that command to work properly. This would very quickly become annoying and I'd receive lots of tickets with people complaining about that instead.

I'm sorry I can't provide a better answer than this. It frustrates me too.
