### ISSUE TITLE
Table Related options

### ISSUE THREAD

**Issue by jakkaas** [stevencohn/OneMore#185]
It would be great if you provided table related option in OneMore, especially. Split, merge, Insert etc like Word/Excel.

Thanks.

You are doing wonderful job. Thank you for helping us out in using OneNote more effectively.

**Comment by stevencohn** [comment]
Split is a command I'd like to add. 

Merge isn't needed because you can simply delete the space between two tables and they are merged automatically, provided they have the same number of columns; anything beyond that I need to consider effort vs reward

**Comment by stevencohn** [comment]
By the way, OneMore also has an Insert Cells command https://github.com/stevencohn/OneMore/wiki/Extra-Commands

**Comment by jakkaas** [comment]
Thank you so much
