### ISSUE TITLE
Export Notebooks and Sections as web pages with attachments

### ISSUE THREAD

**Issue by G2G2G** [stevencohn/OneMore#189]
Expand export page functionality to notebooks and / or sections.

**Comment by stevencohn** [comment]
As mentioned in #153 this is already in development

**Comment by stevencohn** [comment]
v3.17 adds context-menu Archive command to both notebooks and sections, archives to a zip file including attachments. Also fixes cross-page hyperlinks for pages included in the archive so the archive can stand on its own as a directory of HTML files.
