### ISSUE TITLE
Make Invert the selection select only the visible text in case there is collapsed sections or paragraphs

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#191]
**Is your feature request related to a problem? Please describe.**
When inverting the selection select only the visible text, do not extend that to what is collapsed and not visible
**Describe the solution you'd like**

If I have all the heading collapsed with only H1 and H2 visible and I selected H1 change the formatting then when I click on invert the current selection I would like to select only H2 headers or whatever else is not collapsed (for a more generic case)
Currently this function selects everything else

**Comment by stevencohn** [comment]
Is this more about selecting things with similar styles or just ignoring collapsed content regardless?

**Comment by 1001QAdotNET** [comment]
It is about ignoring the collapsed content. I have a diff request for selecting things with the same style

**Comment by 1001QAdotNET** [comment]
Thank you! I will test and get back to you if I see any issues
