### ISSUE TITLE
How can I sync my snippets and profile, between my PC?

### ISSUE THREAD

**Issue by Roscript** [stevencohn/OneMore#192]
**How can I help you?**
The custom snippet is an awesome function. I added a lot of snippets.
How can I sync my snippet and profile, between my PCs (onenote2016@win10)?
If there have a configure file, I can use Onedrive to sync it.
Or is there have some way to sync it better?

**Comment by stevencohn** [comment]
All OneMore configuration is stored under %appdata%\OneMore

Currently, this cannot be changed. So you'll need to copy it manually or some utility to set up a sync job

**Comment by Roscript** [comment]
Thx. It's helpful.
