### ISSUE TITLE
Selected Text as a title for expand and collapse

### ISSUE THREAD

**Issue by jakkaas** [stevencohn/OneMore#193]
I would like a feature where if I select a text and then select expand/collapse function than the text should be selected as title for the expand/collapse text box. It would be more useful if you could provide a symbol such as 
![image](https://user-images.githubusercontent.com/43289832/108787855-a47dfc00-759c-11eb-9418-da6b30c4a101.png) (as in notion) in front of text and when we click on it, it can expand or collapse. 

Thanks.

**Comment by stevencohn** [comment]
Unfortunately, the API provided by OneNote doesn't allow that level of interaction. Any actions must be invoked from a ribbon bar button, menu, or context menu. The API doesn't provide events for changes in content.

**Comment by jakkaas** [comment]
Thank you for answering. I get it.
There is another request for Expand and collapse. I shall put it here but if you want, I will create another post. Thank you for hearing me out. Is there any way I can quickly expand and collapse all text in a page? If not, I would like to have this feature and thus add it as a request. Thanks.

**Comment by stevencohn** [comment]
That can be done

**Comment by 1001QAdotNET** [comment]
Add memory to that, in the sense that OneMore should be able to remember the status of the page (what is collapsed and what not) and switch between expand and collapsed view of the paragraphs
