### ISSUE TITLE
Merging notes pages containing more than one bucket.

### ISSUE THREAD

**Issue by yosso** [stevencohn/OneMore#195]
**Describe the bug**

When merging pages and one of the pages contains a separate bucket, none of the pages after that page will be merged into the first page.

**To Reproduce**
Select the pages to be merged.
Merge the pages.

**Expected behavior**
The extra buckets be merged in the page?  

Note, more of a problem on my end (i.e. the user)  When I practiced proper OneNote, the pages would merge properly.

Just wanted to send the log file.
[OneMore.log](https://github.com/stevencohn/OneMore/files/6043541/OneMore.log)

**Environment (if applicable):**
OneNote for Microsoft 365, 64-bit (Version 2101)
Windows 10 Pro OS Build 19041.804

**Additional context**
Add any other context about the problem here. Attach page XML file or the app log file as appropriate. You can find the log file here: %localappdata%\temp\OneMore.log

**Comment by stevencohn** [comment]
By "buckets" do you mean outlines? I'm trying to reproduce this but I don't think I have enough information to understand the problem.
