### ISSUE TITLE
How can I compile and use this ? Do you have the binaries somewhere ?

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#20]
Hi Steven

Thank you so much for writing this.
Do you have any doc that can guide a non C# programmer to compile this project?
Do you have the binaries anywhere we can download them from?

thank you
1K1

**Comment by stevencohn** [comment]
No need to compile. You can download an installer here https://github.com/stevencohn/OneMore/releases

**Comment by 1001QAdotNET** [comment]
Great thank you!
Please if you could add it to the readme.md for ppl with technical blindness (read: do not know where to check) like me :-)

Do you take suggestions for new features ?
If yes here is one: a markdown implementation would probably be greatly appreciated. Not sure if this is covered by Styles but one thing that I would like to be able to do is to use some sort of markup language that would help with formatting (ex: if add ### somewhere in the text I would like to be able to apply a certain style to the text from that point to the end of the sentence or to the text between two consecutive "###"
Also cleaning the styles of copied and pasted text would help. I have attempted the above using REST APIs but the REST implementation for onenote is poor and limited (to put it mildly)
There is no support for it, it looks like they are abandoning it, I can't understand the lack of reaction from MS Graph OneNote APIs

**Comment by stevencohn** [comment]
So first, you mention REST APIs. I can only presume that you're talking about the REST APIs for OneNote online. This plugin is for the desktop version only (although if you're syncing with OneDrive then you're notes are online too so those will be affected by this plugin, albeit indirectly.)

Anyway, you can remove all styling from a selected bit of text using OneNote's built-in Clear All Formatting command (Ctrl+Shift+N).

I've considering Markdown->OneNote conversion. There are already plugins to import/export markdown. But I think you're talking about inline markdown notation and conversion to real styles. I'm not sure I see the point of that since OneNote is a WYSIWYG editor (what you see, is what you get) already and has plenty of rich formatting features built-in.

Thanks for the suggestions though. I do consider all of them and will implement as I have time and believe in their usefullness.

**Comment by 1001QAdotNET** [comment]
Yes I do get that (REST is for onedrive stored notebooks -consumer use) and I do realize your addon can change both (testing it as we speak)

Here are my use case scenarios:
-I copy and paste lots of text and then while learning I use collapsible paragraphs (hit tab to indent the paragraph) and at the top I leave the tile and one quick conclusion . I usually like to keep the formatting of the original text (saves time and improves readability) but I want to have a clear distiction between the original text and my conclusions or the abstract of the paragraph. TO achieve that I use a smaller font and let's say the blue color. Doing that formatting is time consuming (and requires you to select the entire text you just typed. Currently using rest APIs I am able to start my conclusions or comments or the abstract with ### and I keep going till I finish all the text. At the end I run a script and that converts the above marked text (between ### and the end (</p>) by removing the "###" and they adding styling (color:blue font-size:10.5pt) to the text delimited by ### and the next <p> Very easy and convenient excepting these:
-MS's APIs are screwing he position o the <p>...</p> sometimes updating the doc by moving the paragraph see this https://stackoverflow.com/questions/62054620/why-is-onenote-graphapi-not-updating-the-target-tag-correctly-introducing-top

-the other thing that bothers me is that the html text I am copying and pasting has bottom-margin and top margin set to not zero values in which case after I collapse a pargraph you need to remove the above in order to have a decently looking doc (otherwise you are left with one liners -title and a short conclusion added like above- and sometimes large empty spaces between these which look awful) So ideally I would like to be able to clear this and style I like from all or from specific tags by just using a shortcut

**Comment by stevencohn** [comment]
Which version of OneNote (desktop) are you using?

**Comment by 1001QAdotNET** [comment]
I am using a shared notebook -this is the one I am experiencing the above problems with
@work OneNote 2016 x64
@home OneNote 2010 and 2016 both x86

Most of the work is done from the work laptop even when I am home
The work account is different that the home account, the home account is the owner of the shared notebook and the work account (enterprise account) is accessing the shared notebook via a link that I shared from one account to the other

**Comment by stevencohn** [comment]
Added markdown request to issue #22
