### ISSUE TITLE
Remove paragraph spacing not working for bulleted or numbered lists

### ISSUE THREAD

**Issue by geoff-B** [stevencohn/OneMore#201]
**Describe the bug**
The Remove paragraph spacing feature does not work for bulleted or numbered lists.

**To Reproduce**
1. Create a bulleted/numbered list.
2. Add paragraph spacing (before or after)
3. Run "Remove paragraph spacing"

**Expected behavior**
For the spacing between the list entries to be removed.

**Environment (if applicable):**
 - OneNote Version: O365
 - OneMore Version: 3.18.3

I could also try to fix it myself if you point me in the right direction.

**Comment by stevencohn** [comment]
https://github.com/stevencohn/OneMore/releases/latest
