### ISSUE TITLE
Not All Installed Fonts Available in Style Editor

### ISSUE THREAD

**Issue by sweet00th** [stevencohn/OneMore#202]
Hi,

Some installed fonts in Windows 10 are not showing up in style editor, I'm missing both TTF & OTF fonts. 

1. Go to "Custom Styles"
2. Go to "Edit Styles"
3. either start a new style or edit an existing style
4. under "font", I can't find some of the ttf & otf fonts

**Expected behavior**
I was expecting all fonts to be available as they are available natively in OneNote

**Environment (if applicable):**
 - OneNote O365
 - OneMore v3.18.3

**Comment by stevencohn** [comment]
I can reproduce the problem for OTF font but it seems to work fine for TTF. I'll take a closer look. Thanks

**Comment by stevencohn** [comment]
Actually, are you sure they're missing? The filename of the font is not always the same of the displayed family name.

**Comment by stevencohn** [comment]
https://github.com/stevencohn/OneMore/releases/latest
