### ISSUE TITLE
SearchAndReplaceCommand error when running from end of bulleted list at the end of a page

### ISSUE THREAD

**Issue by geoff-B** [stevencohn/OneMore#203]
**Describe the bug**
The SearchAndReplaceCommand throws an error when activated when the text cursor as at the bottom of a bulleted list, at the end of page, like in the below screenshot.

**To Reproduce**
1. Go to any page.
2. Make a bulleted list at the end of the page
3. Type something in the first bullet
4. Press enter to go down
5.  Activate Search and replace
6. Error is thrown.

**Expected behavior**
The search and replace window should show up as normal.

**Screenshots**
![image](https://user-images.githubusercontent.com/38046772/112349017-fabe8780-8c8d-11eb-85d9-c0ea36cb953b.png)

**Environment (if applicable):**

- OneNote Version: O365
- OneMore Version: 3.18.3

**Additional context**
Log file:
```19036:9] Error running command SearchAndReplaceCommand
19036:9] System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: River.OneMoreAddIn
StackTrace:    at River.OneMoreAddIn.XCDataExtensions.EndsWithWhitespace(XCData cdata)
   at River.OneMoreAddIn.Models.Page.EditSelected(Func`2 edit)
   at River.OneMoreAddIn.Models.Page.GetSelectedText()
   at River.OneMoreAddIn.Commands.SearchAndReplaceCommand.<Execute>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.CommandFactory.<Run>d__5`1.MoveNext()
TargetSite: [River.OneMoreAddIn] River.OneMoreAddIn.XCDataExtensions::EndsWithWhitespace()
```

**Comment by stevencohn** [comment]
Good catch. Thanks for the detail

**Comment by stevencohn** [comment]
https://github.com/stevencohn/OneMore/releases/latest
