### ISSUE TITLE
To TitleCase feature request

### ISSUE THREAD

**Issue by geoff-B** [stevencohn/OneMore#204]
**Describe the solution you'd like**
A TitleCase function to be added to the existing ToCase functions.

**Describe alternatives you've considered**
A similar function is available in Microsoft Word, along with sentence case (which is less important).

**Additional context**
The [TextInfo.ToTitleCase(String) Method](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.textinfo.totitlecase?redirectedfrom=MSDN&view=net-5.0#System_Globalization_TextInfo_ToTitleCase_System_String_) could be used to accomplish this.

**Comment by stevencohn** [comment]
https://github.com/stevencohn/OneMore/releases/latest

**Comment by geoff-B** [comment]
The TitleCase command works great, but it is not listed in the context meny options.

**Comment by stevencohn** [comment]
next release
