### ISSUE TITLE
Tags (Labels) placement with long page title

### ISSUE THREAD

**Issue by sbennett18** [stevencohn/OneMore#211]
**Describe the bug**
If the page title is long enough that the title gets line-wrapped, or for some reason you have a new-line in the title (Shift+Enter will do it), the tag line gets placed behind the title text.

**To Reproduce**
1. Create a new sheet with a long title or manually add a new-line to the title
2. Add a Tag (Label) to the page using OneMore

**Expected behavior**
I would expect the tag line to be placed inline with the page date and time like it does with single-line page titles, but the position of the tag line does not change with the number of lines in the title.

**Screenshots**
![image](https://user-images.githubusercontent.com/1417401/112903849-b1b36c80-90ad-11eb-91fd-d74149371373.png)

**Environment (if applicable):**
 - OneNote Version: O365, 64bit
 - OneMore Version 3.19.1

**Additional context**
N/A

**Comment by stevencohn** [comment]
Unfortunately, there's not much I can do here. There's not enough information in OneNote and its API to determine the font size, window size, wrapping and ultimate position of where the tag box should go. 

The workaround is to click on the tag box (it's quite easy even with a very long overlapping title) and drag it down the page to position wherever you want.

**Comment by sbennett18** [comment]
Understood.  Thanks for the quick response!
