### ISSUE TITLE
Re-Enable Spelling Check

### ISSUE THREAD

**Issue by sweet00th** [stevencohn/OneMore#212]
**Is your feature request related to a problem? Please describe.**

I appreciate the disable spell check option, but can we please have a "re-enable" option to bring spell check back if disabled by accident? 

currently my workaround to restore spell back is by creating a "custom" ribbon group, add "set proofing language" then select the entire page, change language from "yoruba" back to "English".

**Describe the solution you'd like**
a simple "re-enable spell check" will do.

**Describe alternatives you've considered**

**Additional context**

THE FINE PRINT
This is a hobby project that I started for myself. I'm happy to take requests and will promise to consider each one carefully but offer no guarantees that I will ultimately agree to their usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around then I will probably reject the request - you've been warned!

**Comment by sweet00th** [comment]
Hi, appreciate the quick release. But Disable Spell Check does not work, it does not change the page to "youruba". The new "Enable spell check" works fine (I tested by manually set page language to "youruba").

Would appreciate a fix release. Thanks!

**Comment by stevencohn** [comment]
I can't repo this. It works as expected in all my tests. What exactly are you seeing? Can you look at the <one:Page> tag itself - it should have a lang="yo" attribute

**Comment by sweet00th** [comment]
mine says "lang=en-US" after clicking disable spell check.

I will try reinstall later to see if it was just an odd update issue.

**Comment by sweet00th** [comment]
> I can't repo this. It works as expected in all my tests. What exactly are you seeing? Can you look at the one:Page tag itself - it should have a lang="yo" attribute

How do I check for one:Page tag? Sorry I'm not a programmer.

**Comment by stevencohn** [comment]
Closing this. Following defect in #214
