### ISSUE TITLE
Option to remove line/paragraph breaks from selected text

### ISSUE THREAD

**Issue by geoff-B** [stevencohn/OneMore#213]
**Describe the solution you'd like**
An option to remove line/paragraph breaks from selected text. It could include the option of keeping line breaks preceded by an end mark (.?!).

**Describe alternatives you've considered**
Macros that do this exist in Onetastic; copying and pasting the text into the Chrome omnibar also does the job.
[gImageReader](https://github.com/manisandro/gImageReader) has an implementation seen [here, beginning line 134](https://github.com/manisandro/gImageReader/blob/master/gtk/src/OutputEditorText.cc).

**Comment by stevencohn** [comment]
See the Edit/Join Paragraph command

**Comment by geoff-B** [comment]
Thanks, I didn't know that feature existed. However it is not available in the context menu options, unless the entire edit menu is chosen.
