### ISSUE TITLE
Disable Spell Check Does Not Work in New Release

### ISSUE THREAD

**Issue by sweet00th** [stevencohn/OneMore#214]
**Describe the bug**
Disable Spell Check does not change page language to "youruba". The new "Enable spell check" works fine (I tested by manually set page language to "youruba").

**To Reproduce**
1. new note page in English, write some misspelled words
2. Click on "disable spell check", either in edit menu or via contextual menu
3. nothing changes, still red underline highlighting spelling error

**Expected behavior**
Was expecting red underlines to go away and page language set to "youruba" instead of English or whatever default.

**Screenshots**

**Environment (if applicable):**
 - OneNote Version: [e.g. Office 2019, O365, also 32bit or 64bit?]
 - OneMore Version [e.g. 3.4 - from the About dialog or from the log file]

**Additional context**
Add any other context about the problem here. Attach page XML file or the app log file as appropriate. You can find the log file here: %localappdata%\temp\OneMore.log

**Comment by stevencohn** [comment]
Please check the XML of the page after choosing Edit/Disable Spell Check command and look for the lang="yo" attribute on the top one:Page element

**Comment by sweet00th** [comment]
Hi, I just did a clean install of the latest OneMore version (including removing OneMore folder from roaming), disable spell check still does not work. What is even more weird is the old "no spell check" function no longer work even after reinstalling v3.19.1. 

Basically, as of right now. clicking on disable function does nothing to change language proofing setting, I can see language is still being set to "us-EN" in XML. 

Please note that test were being done in both existing notebook and a new notebook created just for testing for this particular bug. I would appreciate any help on this as disable spelling check is now non-functional in both the current release and the previous version from old download.

**Comment by sweet00th** [comment]
Okay, I found the cause of the bug. Microsoft pushed out an Office update today 3/31. My main laptop had updates installed this afternoon, and when I installed OneMore update this evening, disable spell check stopped working. I just tested it on spare laptop which had an earlier version of the Office 365, new OneMore update disable spell check worked perfectly fine but once I installed the newest Office update, it stopped working. 

My Outlook is the desktop version of Microsoft 365 personal subscription. The OneNote version your latest update worked was 16.0.13801.20288 64-bit), the newest OneNote version in which your update does not work is 16.0.13901.20276 64-bit).

If you update your Office version, you will mostly see this bug. Look forward to a fix. Thanks!

**Comment by stevencohn** [comment]
I'm trying to upgrade to that version which isn't as easy as you might think! Meanwhile, can you please use the Export command to export the page as XML and attach it to this thread? Click the angle-bracket icon here in the comment editor to insert code and paste the XML into that.

**Comment by sweet00th** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<one:Page xmlns:one="http://schemas.microsoft.com/office/onenote/2013/onenote" ID="{98D28F61-7949-EB0C-15F0-AF9F74FB57B7}{1}{E1946778189569732023591942577067723088226651}" name="Disable Spell Check Test" dateTime="2021-04-01T19:18:39.000Z" lastModifiedTime="2021-04-01T19:20:50.000Z" pageLevel="1" isCurrentlyViewed="true" lang="en-US">
  <one:QuickStyleDef index="0" name="PageTitle" fontColor="automatic" highlightColor="automatic" font="Ropa Sans" fontSize="20.0" spaceBefore="0.0" spaceAfter="0.0" />
  <one:QuickStyleDef index="1" name="p" fontColor="automatic" highlightColor="automatic" font="Ropa Sans" fontSize="12.0" spaceBefore="0.0" spaceAfter="0.0" />
  <one:PageSettings RTL="false" color="automatic">
    <one:PageSize>
      <one:Automatic />
    </one:PageSize>
    <one:RuleLines visible="false" />
  </one:PageSettings>
  <one:Title lang="en-US">
    <one:OE author="sweetooth" authorInitials="ST" authorResolutionID="&lt;resolutionId provider=&quot;None&quot; hash=&quot;XNz5g59J8vMlNw0PtIcVrA==&quot;&gt;&lt;localId name=&quot;sweetooth&quot;/&gt;&lt;/resolutionId&gt;" lastModifiedBy="sweetooth" lastModifiedByInitials="ST" lastModifiedByResolutionID="&lt;resolutionId provider=&quot;None&quot; hash=&quot;XNz5g59J8vMlNw0PtIcVrA==&quot;&gt;&lt;localId name=&quot;sweetooth&quot;/&gt;&lt;/resolutionId&gt;" creationTime="2021-04-01T19:18:43.000Z" lastModifiedTime="2021-04-01T19:20:38.000Z" objectID="{4DB49B03-71E3-4417-AF7A-7DADA23B8C21}{15}{B0}" alignment="left" quickStyleIndex="0">
      <one:T><![CDATA[Disable Spell Check Test]]></one:T>
    </one:OE>
  </one:Title>
  <one:Outline author="sweetooth" authorInitials="ST" lastModifiedBy="sweetooth" lastModifiedByInitials="ST" lastModifiedTime="2021-04-01T19:20:47.000Z" objectID="{4DB49B03-71E3-4417-AF7A-7DADA23B8C21}{29}{B0}">
    <one:Position x="36.0" y="86.4000015258789" z="0" />
    <one:Size width="464.8499755859375" height="133.9933776855469" />
    <one:OEChildren>
      <one:OE authorResolutionID="&lt;resolutionId provider=&quot;None&quot; hash=&quot;XNz5g59J8vMlNw0PtIcVrA==&quot;&gt;&lt;localId name=&quot;sweetooth&quot;/&gt;&lt;/resolutionId&gt;" lastModifiedByResolutionID="&lt;resolutionId provider=&quot;None&quot; hash=&quot;XNz5g59J8vMlNw0PtIcVrA==&quot;&gt;&lt;localId name=&quot;sweetooth&quot;/&gt;&lt;/resolutionId&gt;" creationTime="2021-04-01T19:18:51.000Z" lastModifiedTime="2021-04-01T19:20:38.000Z" objectID="{4DB49B03-71E3-4417-AF7A-7DADA23B8C21}{30}{B0}" alignment="left" quickStyleIndex="1">
        <one:T><![CDATA[This is a test for OneMore &quot;Disable Spell Check&quot; function in newly updated Office 365 OneNote desktop version. ]]></one:T>
      </one:OE>
      <one:OE authorResolutionID="&lt;resolutionId provider=&quot;None&quot; hash=&quot;XNz5g59J8vMlNw0PtIcVrA==&quot;&gt;&lt;localId name=&quot;sweetooth&quot;/&gt;&lt;/resolutionId&gt;" lastModifiedByResolutionID="&lt;resolutionId provider=&quot;None&quot; hash=&quot;XNz5g59J8vMlNw0PtIcVrA==&quot;&gt;&lt;localId name=&quot;sweetooth&quot;/&gt;&lt;/resolutionId&gt;" creationTime="2021-04-01T19:19:30.000Z" lastModifiedTime="2021-04-01T19:20:38.000Z" objectID="{4DB49B03-71E3-4417-AF7A-7DADA23B8C21}{35}{B0}" alignment="left" quickStyleIndex="1">
        <one:T><![CDATA[]]></one:T>
      </one:OE>
      <one:OE authorResolutionID="&lt;resolutionId provider=&quot;None&quot; hash=&quot;XNz5g59J8vMlNw0PtIcVrA==&quot;&gt;&lt;localId name=&quot;sweetooth&quot;/&gt;&lt;/resolutionId&gt;" lastModifiedByResolutionID="&lt;resolutionId provider=&quot;None&quot; hash=&quot;XNz5g59J8vMlNw0PtIcVrA==&quot;&gt;&lt;localId name=&quot;sweetooth&quot;/&gt;&lt;/resolutionId&gt;" creationTime="2021-04-01T19:19:32.000Z" lastModifiedTime="2021-04-01T19:20:38.000Z" objectID="{4DB49B03-71E3-4417-AF7A-7DADA23B8C21}{32}{B0}" alignment="left" quickStyleIndex="1">
        <one:T><![CDATA[Here are some deliberately mis-spelled words.]]></one:T>
      </one:OE>
      <one:OE authorResolutionID="&lt;resolutionId provider=&quot;None&quot; hash=&quot;XNz5g59J8vMlNw0PtIcVrA==&quot;&gt;&lt;localId name=&quot;sweetooth&quot;/&gt;&lt;/resolutionId&gt;" lastModifiedByResolutionID="&lt;resolutionId provider=&quot;None&quot; hash=&quot;XNz5g59J8vMlNw0PtIcVrA==&quot;&gt;&lt;localId name=&quot;sweetooth&quot;/&gt;&lt;/resolutionId&gt;" creationTime="2021-04-01T19:19:43.000Z" lastModifiedTime="2021-04-01T19:20:38.000Z" objectID="{4DB49B03-71E3-4417-AF7A-7DADA23B8C21}{41}{B0}" alignment="left" quickStyleIndex="1">
        <one:T><![CDATA[]]></one:T>
        <one:OEChildren>
          <one:OE authorResolutionID="&lt;resolutionId provider=&quot;None&quot; hash=&quot;XNz5g59J8vMlNw0PtIcVrA==&quot;&gt;&lt;localId name=&quot;sweetooth&quot;/&gt;&lt;/resolutionId&gt;" lastModifiedByResolutionID="&lt;resolutionId provider=&quot;None&quot; hash=&quot;XNz5g59J8vMlNw0PtIcVrA==&quot;&gt;&lt;localId name=&quot;sweetooth&quot;/&gt;&lt;/resolutionId&gt;" creationTime="2021-04-01T19:19:47.000Z" lastModifiedTime="2021-04-01T19:20:38.000Z" objectID="{4DB49B03-71E3-4417-AF7A-7DADA23B8C21}{38}{B0}" alignment="left" quickStyleIndex="1">
            <one:List>
              <one:Bullet bullet="2" fontSize="12.0" />
            </one:List>
            <one:T><![CDATA[Cattch ]]></one:T>
          </one:OE>
          <one:OE authorResolutionID="&lt;resolutionId provider=&quot;None&quot; hash=&quot;XNz5g59J8vMlNw0PtIcVrA==&quot;&gt;&lt;localId name=&quot;sweetooth&quot;/&gt;&lt;/resolutionId&gt;" lastModifiedByResolutionID="&lt;resolutionId provider=&quot;None&quot; hash=&quot;XNz5g59J8vMlNw0PtIcVrA==&quot;&gt;&lt;localId name=&quot;sweetooth&quot;/&gt;&lt;/resolutionId&gt;" creationTime="2021-04-01T19:19:55.000Z" lastModifiedTime="2021-04-01T19:20:38.000Z" objectID="{4DB49B03-71E3-4417-AF7A-7DADA23B8C21}{45}{B0}" alignment="left" quickStyleIndex="1">
            <one:List>
              <one:Bullet bullet="2" fontSize="12.0" />
            </one:List>
            <one:T><![CDATA[Lammp]]></one:T>
          </one:OE>
          <one:OE authorResolutionID="&lt;resolutionId provider=&quot;None&quot; hash=&quot;XNz5g59J8vMlNw0PtIcVrA==&quot;&gt;&lt;localId name=&quot;sweetooth&quot;/&gt;&lt;/resolutionId&gt;" lastModifiedByResolutionID="&lt;resolutionId provider=&quot;None&quot; hash=&quot;XNz5g59J8vMlNw0PtIcVrA==&quot;&gt;&lt;localId name=&quot;sweetooth&quot;/&gt;&lt;/resolutionId&gt;" creationTime="2021-04-01T19:20:03.000Z" lastModifiedTime="2021-04-01T19:20:38.000Z" objectID="{4DB49B03-71E3-4417-AF7A-7DADA23B8C21}{49}{B0}" alignment="left" quickStyleIndex="1">
            <one:List>
              <one:Bullet bullet="2" fontSize="12.0" />
            </one:List>
            <one:T><![CDATA[Doddlle]]></one:T>
          </one:OE>
          <one:OE authorResolutionID="&lt;resolutionId provider=&quot;None&quot; hash=&quot;XNz5g59J8vMlNw0PtIcVrA==&quot;&gt;&lt;localId name=&quot;sweetooth&quot;/&gt;&lt;/resolutionId&gt;" lastModifiedByResolutionID="&lt;resolutionId provider=&quot;None&quot; hash=&quot;XNz5g59J8vMlNw0PtIcVrA==&quot;&gt;&lt;localId name=&quot;sweetooth&quot;/&gt;&lt;/resolutionId&gt;" creationTime="2021-04-01T19:20:21.000Z" lastModifiedTime="2021-04-01T19:20:38.000Z" objectID="{4DB49B03-71E3-4417-AF7A-7DADA23B8C21}{64}{B0}" alignment="left" quickStyleIndex="1">
            <one:T><![CDATA[]]></one:T>
          </one:OE>
        </one:OEChildren>
      </one:OE>
      <one:OE authorResolutionID="&lt;resolutionId provider=&quot;None&quot; hash=&quot;XNz5g59J8vMlNw0PtIcVrA==&quot;&gt;&lt;localId name=&quot;sweetooth&quot;/&gt;&lt;/resolutionId&gt;" lastModifiedByResolutionID="&lt;resolutionId provider=&quot;None&quot; hash=&quot;XNz5g59J8vMlNw0PtIcVrA==&quot;&gt;&lt;localId name=&quot;sweetooth&quot;/&gt;&lt;/resolutionId&gt;" creationTime="2021-04-01T19:20:24.000Z" lastModifiedTime="2021-04-01T19:20:47.000Z" objectID="{4DB49B03-71E3-4417-AF7A-7DADA23B8C21}{67}{B0}" alignment="left" quickStyleIndex="1">
        <one:T><![CDATA[Note that &quot;disable spell check&quot; has been engaged but has no effect.]]></one:T>
      </one:OE>
    </one:OEChildren>
  </one:Outline>
</one:Page>`

**Comment by stevencohn** [comment]
Is there anything interesting in the OneMore log file? You can open it from the OneMore About box.

First click the Clear Log link
Then run the commands
Then open the log and see if there are any exceptions, paste it here

**Comment by sweet00th** [comment]
Here it is, log says spell check disable but it was not. pretty darn sure new o365 update broke it.

10552:1] Log restarted
10552:1] Running command SpellCheckCommand
10552:1] ..spell check disabled @ 00:00.06
10552:1] Running command AboutCommand

**Comment by stevencohn** [comment]
I have no access to that version unfortunately.
Any other commands not working?

**Comment by sweet00th** [comment]
so far this is the only one I've found not working after new update. enable spell check is fine if I manually set proofing to yoruba to force stop spell check, just whatever ms has done to the new update is now completely ignoring the way you've written to get around it. hopefully you'll be on new o365 soon.

**Comment by stevencohn** [comment]
My installation of Office updated this morning to 16.0.13901.20366 and enable/disable spell check still works as expected. I'm keeping this as no-repro

**Comment by sweet00th** [comment]
Hmm...yes this is the version I have as well. Just curious, is your installation part of Microsoft 365 subscription? If you're on standalone perpetual license version, some of the updates MS has done for 365 will not be available for standalone even if the version numbers are identical. Can't think of another reason why it doesn't work on mine on 2 separate machines while it works on yours.

**Comment by stevencohn** [comment]
I have two machines, one with a perpetual instance and one with a corporate 365 subscription. They both act the same, both work as expected

**Comment by stevencohn** [comment]
Good news... I think? I have a page where I was able to reproduce the problem. There are no exceptions so I'm not sure why it's not accepting the modifications but at least I have a test case to narrow it down.

**Comment by stevencohn** [comment]
As far as I can tell, Microsoft broke it! I may try to open a ticket with them but I'm worried I won't get a good response.

**Comment by sweet00th** [comment]
So you've same 365 version on different machines but was able to produce this bug on one but not another? that's kind of weird. FWIW, all my machines are on windows 10 version 20H2, still think its that minor O365 update that broke it. Good luck getting an answer from Microsoft, fingers crossed for a fix.

**Comment by stevencohn** [comment]
Not related to my inquiries to Microsoft, this problem seems to have corrected itself with the latest release of OneNote:

Microsoft® OneNote® 2016 MSO (16.0.13929.20206) 32-bit 

Disabling/Enabling spell check now works in all of my testing with this latest version

**Comment by sweet00th** [comment]
Yup, the problem has gone away after I updated to v16.0.13929.20360 64-bit. Guess it was indeed a bug introduced by MSFT, glad it fixed itself. 

I forgot to mention that even before spelling check bug came about, there's this little bug involving font. My default font for note is a custom one (Ropa Sans size 12), if I disable spell check, clipped note from website(via OneNote add extension) reverts back to default Calibri size 11. It only happens if the note is a clipped one, does not affect normal notes. Not a big deal but kind of annoying.

**Comment by stevencohn** [comment]
Was that just a straight Paste or did you try "Keep Text Only"?

**Comment by sweet00th** [comment]
Straight clip from Microsoft OneNote extension for Edge/Chrome. It's not just spell check function that changes the font, basically any editing function in OneMore will somehow change either the font or font size. Here is my steps to reproduce.

1. find an article from Bloomberg.com(note the article on website is in some kind of serif font, use official OneNote clipper extension(Edge), choose clip "article"
2. go back to OneNote desktop app and view the note without doing any editing, OneNote automatically shows a different font - verdana 12 in my case
3. choose a random editing function from OneMore(in my case, spell check), verdana font stays but size is now 11

Note if I choose to edit the font from whatever font it was clipped from, say from Verdana to Ropa Sans, then use OneNote editing function like spell check, then the font changes to Calibri size 11.

**Comment by stevencohn** [comment]
I believe this is a discrepancy between the XML schema used by OneNote online vs how the OneNote COM API used by OneMore automatically reworks the XML. The Webclipper is generating XML for the page that OneNote will happy maintain. But once it's pumped through the COM API, it is "cleansed" in ways that I can't control. This has been the root of frustration for quite a few features of OneMore and unfortunately is likely something that we simply need to live with.
