### ISSUE TITLE
Dragging image crop handle after scrolling down scrolls back to top

### ISSUE THREAD

**Issue by geoff-B** [stevencohn/OneMore#217]
**Describe the bug**
When cropping an image that is larger than the crop window, scrolling is required to see the whole image. However, when a handle on the cropping region is dragged while scrolled down, the whole window is scrolled back to the top, the cropping handle being moved along with it.

**To Reproduce**
1. Crop a large image
2. Make a crop selection of any size
3. Scroll down in the crop window
3. Click and drag any of the handles
4. Image scrolls back to top

**Expected behavior**
The scroll position should be preserved when dragging the handles.

**Screenshots**
![scroll](https://user-images.githubusercontent.com/38046772/114761285-81aad100-9d1d-11eb-81e5-c38f62e71094.gif)

**Environment (if applicable):**
 - O365
 - OneMore Version 3.19.3

**Comment by stevencohn** [comment]
Yes a known issue since I originally wrote it but didn't have the time or honestly the interest to fix it right. Was hoping someone with better experience in graphics programming would help out here ;-)

I'll keep this open of course and try to return to it
