### ISSUE TITLE
What Visual Studio 2019 Components are needed?

### ISSUE THREAD

**Issue by ooze90** [stevencohn/OneMore#219]
After reading the pre-reqs for your extension, I downloaded Visual Studio Community 2019 from https://visualstudio.microsoft.com/vs/community/. When the installer downloaded, there are a multitude of options to choose from. However, I don't see an option for "Microsoft Visual Studio 2019, C# 7" (screenshot attached).
![Screenshot 2021-04-18 082627](https://user-images.githubusercontent.com/82738995/115147257-cc7b6000-a01f-11eb-947c-31706a638018.png)

 Which components do I need to select for Visual Studio Community 2019 in order to make your extension work?

**Comment by stevencohn** [comment]
Minimum is C# and if you want to build the installer then Visual Studio 2019 Installer Projects extension
