### ISSUE TITLE
Plugins requirements should accompany the plugin

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#220]
**Is your feature request related to a problem? Please describe.**
not that much of a future request but rather a suggestion regarding the way we document and submit plugins
There should be an install.txt or requirements.txt that should be submitted with the plugin

I know I promised I will share some. I hope that I would get there, I am starting a new certification campaign, this time I don't have to beat the clock so I will use some of my time to write the plugins I would like and share them here, I did not forget I promised to share ...

**Comment by stevencohn** [comment]
If the plug-in is a single file (hope it would be) then intro/setup comments at the top of the file (and good comments throughout) should satisfy that too

**Comment by 1001QAdotNET** [comment]
true but many user might not be able to read sources or figure out that the instructions are there
