### ISSUE TITLE
Importing PDFs and PowerPoint to OneNote as editable content not as pictures

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#221]
**How can I help you?**
Is there an option to import PowerPoint slides to OneNote as editable content (text and images)
Same question for PDFs

thanks you
1k1

**Comment by stevencohn** [comment]
It may be possible to import PP text along with the slide image, most likely would be ugly - similar to the existing feature of right-clicking a picture and choosing Copy Text from Picture

I have no interest in importing PDFs as that would pull in all kinds of baggage and complexity that I don't want to manage. I suspect this is why no one else has done it yet either

**Comment by 1001QAdotNET** [comment]
PDFs can (in some instances) be exported to docx or html and copied from there
PPTs...not that much ...
