### ISSUE TITLE
Convert linked image URL to image

### ISSUE THREAD

**Issue by andyylin** [stevencohn/OneMore#226]
I have a script that sends cell changes to Google Sheets via LINE and OneNote (through email feature). Is it possible to write something that would convert linked images in the form of an URL into an embedded image? 

I see a feature to convert links to webpage titles, but in my case I'd like OneNote to download the linked image.

**Comment by stevencohn** [comment]
Will be in next release

**Comment by andyylin** [comment]
Awesome, thank you!

**Comment by stevencohn** [comment]
This entirely replaces the URL. Would it be helpful to keep the URL as a citation or subtitle below the image?

**Comment by andyylin** [comment]
> This entirely replaces the URL. Would it be helpful to keep the URL as a citation or subtitle below the image?

Yes, it would be helpful. What if it were made an option? Not sure if that’s difficult to do.

**Comment by stevencohn** [comment]
done

**Comment by andyylin** [comment]
Awesome! Usage is a bit unintuitive. It seems like I need to have my cursor in the page title. If I have my cursor any where on the page, even next to the link I want to download, it doesn't work.

Also, it seems to put images in an odd place, at least with the pages I tested it on. These have URLs located within tables. It puts the image at the top of the table cell, not where the original URL was.

I'm attaching a section with an example. The first page is the original. The second page is after I click in the title area and run the macro.
[20210628.zip](https://github.com/stevencohn/OneMore/files/6763430/20210628.zip)

Thanks again!

**Comment by stevencohn** [comment]
So the cursor needing to be on the title, I haven't experienced this and have tested it with the cursor pretty much anywhere on the page with success. Thanks for the attachment, I'll take a look.

Yes, it will some times place the image oddly. If the URL is in the middle of some text, it doesn't know how to break the line into two so instead places the image above the text line that contained the URL. I do want to enhance this but.... fireworks! I had to watch fireworks and drink and eat too much so....

**Comment by andyylin** [comment]
> So the cursor needing to be on the title, I haven't experienced this and have tested it with the cursor pretty much anywhere on the page with success. Thanks for the attachment, I'll take a look.
> 
> Yes, it will some times place the image oddly. If the URL is in the middle of some text, it doesn't know how to break the line into two so instead places the image above the text line that contained the URL. I do want to enhance this but.... fireworks! I had to watch fireworks and drink and eat too much so....

Odd, maybe the cursor-on-title thing is specific to the page structure I've been testing this on. Maybe because of the tables?

Seems pretty intelligent, it ignored URLs that didn't contain images.

Haha, forgot that it's the 4th of July back in the US! Happy 4th!

**Comment by stevencohn** [comment]
Fixed the positioning of the image so it correctly splits the content. But can't reproduce the cursor location issue. Anyway, the first fix will be in the next release.

**Comment by andyylin** [comment]
Cool, thanks, the cursor bug is a minor issue. Looking forward to the release. Thanks again!
