### ISSUE TITLE
How do I import an HTML page in OneNote? 

### ISSUE THREAD

**Issue by it19862** [stevencohn/OneMore#228]
There is a link to the site page or an HTML file that is located on the local computer.
How to import an HTML page in OneNote with or without saving styles?

Sorry if the question is not within your competence... I
will be grateful for any ideas, links...

**Comment by stevencohn** [comment]
There is no built-in command to do this. The easiest way is to do this

1. Open the local .html file in your browser
2. Select all by pressing Ctrl-A and copy by pressing Ctrl-C
3. Create a new page in OneNote
4. Paste content into new page

It's not going to be perfect in all cases but is generally pretty good.

**Comment by it19862** [comment]
@stevenmcohn 
I want to make sure that you understand me correctly.  
 If I understand you correctly, you are talking about the commands that are part of the OneNote menu  
 
 I know a little bit of C#, and I've done a little bit of work with the OneNote API.
 So I would like to try writing an application that can solve my problem.
  
 `OneMore` can `Export the current page or selected pages as HTML, PDF, MSWord, or as raw OneNote XML`
 I thought that it is probably possible to do `HTML, PDF, MSWord, raw OneNote XML` - > `OneNote page` in the opposite direction
  
  
  How to do this by writing an application in C#?
  Maybe an intermediate file is required?
  **For example:** 
     HTML -> MSWord - > OneNote page
or 
	HTML - > XML - > OneNote page

Or is there no way to do it at all?

**I use**
- Win-7x64;
- OneNote - 2016.

**Comment by stevencohn** [comment]
OneMore already has a command to import MSWord files. So if you can automate the step to convert HTML > Word then you can leverage my function to import Word from there.

Alternatively, there is a way to paste HTML programmatically onto a page. I do this for the Paste Rich Text command. You can take a look at that code for hints too.

**Comment by it19862** [comment]
@stevencohn 
Maybe you have the ability to allocate in a separate application the methods necessary to import HTML into OneNote... (if I understand you correctly..)
I try to do this, but I have a lot of errors..
Many classes are linked.
I don't have much experience.

**Comment by 1001QAdotNET** [comment]
You could use the run a plugin option and https://pandoc.org/  simply redirecting the output 
There are certain limitations regarding what output format you can redirect or not to the format (see thishttps://github.com/jgm/pandoc/issues/2677) BUT we are interested in Markdown like output here

Also Pandoc has APIs https://pandoc.org/using-the-pandoc-api.html
This could be leveraged for importing various formats and conversions

**Comment by it19862** [comment]
@stevencohn 
I figured out how it works...
the question is closed.
