### ISSUE TITLE
Is it possible to add import/export for Mardown?

### ISSUE THREAD

**Issue by osman1963** [stevencohn/OneMore#229]
Hi,
Thanks for the awsome add-in
I was just wondering if it is possible to add Markdown format to the list of import/export formats already in teh add-in
Thanks in advance

**Comment by stevencohn** [comment]
You're not the first to ask so.... maybe

**Comment by stevencohn** [comment]
Have a working prototype of importing. Not so sure about exporting yet

**Comment by osman1963** [comment]
That's awesome. You'll publish it soon?
