### ISSUE TITLE
Feature request - Ability to Merge OneNote Pages

### ISSUE THREAD

**Issue by coderxyz** [stevencohn/OneMore#23]
OneNote Gem has an excellent to merge individual pages. What’s the idea?

When you clip a link, OneNote creates a separate page for each link. If you’re researching on a particular concept, having your links in a single page helps to consolidate ideas and notes. Is it possible to append links in a single OneNote page. 

https://www.onenotegem.com/a/documents/gem-for-onenote/gem-tab/2019/1124/1044.html

Is it possible to bring this feature?

**Comment by stevencohn** [comment]
I'll add this to the Requested Features issue
