### ISSUE TITLE
Remove plug in time-out. 

### ISSUE THREAD

**Issue by eclcomputing** [stevencohn/OneMore#230]
**Is your feature request related to a problem? Please describe.**
We are trying to write plug-ins with a GUI which asks user questions in a form, replacing many useful macros in Onetastic, as well as creating many functions that Onetastic simply can't handle at all. Your 20 second time-out simply does not allow users enough time to enter data in forms.

**Describe the solution you'd like**
Either remove the time-out completely or allow the user to specify a time-out for each plug-in.

**Describe alternatives you've considered**
Nothing else we can think of to ask for user inputs other than using a GUI program.

**Additional context**
Your project is wonderful. We write plug-ins to perform custom business functions. We would like to contribute our generic  plug-ins to your project. Is there an organized way for we or everyone else to do that, just like Macroland? 

THE FINE PRINT
This is a hobby project that I started for myself. I'm happy to take requests and will promise to consider each one carefully but offer no guarantees that I will ultimately agree to their usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
Will consider how to make the timeout configurable.

There is a Plugins folder in this project. Submit a pull request to add your own plugins.

**Comment by stevencohn** [comment]
https://github.com/stevencohn/OneMore/releases
