### ISSUE TITLE
Feature request: prepend created date to title

### ISSUE THREAD

**Issue by tridian-tn** [stevencohn/OneMore#234]
**Is your feature request related to a problem? Please describe.**
When a notebook section contains a number of pages of dated correspondence or notes, where the date of creation is critical, it can be time consuming going into each note to find out when it was created.

**Describe the solution you'd like**
An option to prepend the created date to the title of a note, in a locale-agnostic yyyy-mm-dd format.

e.g. My Note created on the 27th June 2021 becomes "2021-06-27 My Note"

**Describe alternatives you've considered**
Editing each title manually, but it takes time and patience to do it to every note (existing and new)

**Comment by stevencohn** [comment]
https://github.com/stevencohn/OneMore/releases/latest

**Comment by tridian-tn** [comment]
Brilliant, thanks Steven
