### ISSUE TITLE
Horizontal/Double Horizontal Line custom lenght.

### ISSUE THREAD

**Issue by chinook77** [stevencohn/OneMore#238]
Hi, is there a way to change the default length of the Horizontal/Double Horizontal Line separator? 

Thanks in advance.

**Comment by stevencohn** [comment]
Added page to Settings dialog to set default color and length of horizontal lines.
Will be available in next release.

**Comment by chinook77** [comment]
> 
> 
> Added page to Settings dialog to set default color and length of horizontal lines.
> Will be available in next release.

Thanks for your work.

**Comment by stevencohn** [comment]
Released - https://github.com/stevencohn/OneMore/releases
