### ISSUE TITLE
Slow reaction speed of the OneMore plugin

### ISSUE THREAD

**Issue by tyePhDCandy** [stevencohn/OneMore#24]
Thanks for your work! Good one.

I tried the plugin on the onenote 2016, windows 10 version 1909 computer. But, the reaction speed of the plugin buttons is a little slow. After I click on "more" button, the content menu will appear after at least approximately 3 -- 6 seconds.  I wonder if there is a solution for improvement of the reaction speed. Thank you again.

I noticed the first known issue in the "known issues" . But, I do not know if it is connected with my observation of slow reaction speed of the plugin.

> The OneNote Application COM object times out if not used within a reasonable window (somewhere around a minute mabe?) and, regardless of whether you've wrapped the call in a try/catch, OneNote will abort the call, display a dialog, and maybe leave OneNote in an unusable state. As far as I know, there is no way around that other than killing the process and restarting. In my opinion, this was an oversight by the Microsoft engineers who didn't properly decouple the internal mechanisms from the COM API, and I'm sure they never will for the desktop because they're moving towards O365 and Office online... However, OneMore makes every effort to minimize how long it holds on to an Application instance, which may mean recreating it multiple times for a single OneMore operation.

**Comment by stevencohn** [comment]
Hi. The menu slowness is not related to the COM wrapper per se. It's more due to the fact that some of the menu items check your current focus to make sure those items are applicable and enables/disables them accordingly. I'm looking into speed this up a bit. But, yeah, on slower computers especially, it will appear a little slow.

**Comment by tyePhDCandy** [comment]
@stevencohn 
OK. Thanks for your reply and good work.

**Comment by stevencohn** [comment]
Try out the latest release 2.6.... https://github.com/stevencohn/OneMore/releases/tag/2.6

**Comment by tyePhDCandy** [comment]
@stevencohn 
Updated the add-in. No obvious improvement on the slow reaction speed problem. But, still good work. Thanks.

**Comment by tyePhDCandy** [comment]
@stevencohn 
The menu-popup reaction speed is exactly three Mississippi ( or seconds).

**Comment by stevencohn** [comment]
Could you please let me know the clock speed of your CPU?

**Comment by tyePhDCandy** [comment]
Processor: Intel(R) Core(TM)i5-8300H CPU @ 2.30GHz 2.30 GHz （4 cores, turbo boost frequency should be around 3.8GHz）
Installed memory(RAM):32.0 GB(31.7 GB usable)
System type:64-bit Operating System,x64-based processor

It should not be the problem of cpu. The reaction speed is also slow on my another computer, which uses i7-6700K, 3.8GHz cpu. This reaction speed have not been measured, which could be done when convenient.

**Comment by stevencohn** [comment]
Oh wow. I have smaller machines that those and see the menu open in about a second on the first try. Hmph. I'll have to look deeper.

**Comment by stevencohn** [comment]
It's definitely slower on pages with more content. I'll see if I can make it quicker. If not, all commands do have  catch-all logic that prevents the command from continuing if the context is not appropriate

**Comment by tyePhDCandy** [comment]
The reaction time on my i7-6700k computer is about 2 seconds.

The reaction time of built-in popup menus in onenote 2016 is trivial (less than 0.1-0.3? second). I don't know how microsoft managed to achieve that.

**Comment by stevencohn** [comment]
So it's only because OneMore is querying for the page content on every menu item to check if the context is appropriate for that item. On longer pages, it becomes much more obvious. As an example, for an empty page, the OneMore menu opens in less than half a second. I can disable that entirely, as I said, because each command then checks it again after invocation. I'm limited by what the OneNote API gives me.

**Comment by stevencohn** [comment]
I've released v2.6.1 to optimize the performance of the More menu and its submenus. It now only checks the page once for all items while the More menu itself will be slightly slower on larger pages, the submenus should appear immediately.

I know the Styles menu is still slow on its initial opening. I'll look at that later and separately.

**Comment by tyePhDCandy** [comment]
The test of v2.6.1 on my i7-6700k computer confirmed all your descriptions. The only issue here seems to be the relatively slower speed of style menu when the contents on the page is considerably large.

Thanks.
