### ISSUE TITLE
assign an arbitrary command to double click on selected text

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#241]
**Is your feature request related to a problem? Please describe.**
Make it possible to execute  a shortcut combination or a any menu action when double clicking on a selected piece of text (collapsed or not paragraphs or whatever is selected)

**Describe the solution you'd like**

Double click is not used in any way when a text is selected and you double click on it so I guess this could be a good use of it

**Comment by 1001QAdotNET** [comment]
Hmm not sure why now when I double click the text gets unselected but I did have an example on the screen that did not work this way.  Can't reproduce it anymore but the idea is worth exploring
Maybe adding a Ctr+Double click or something of this sort but still make the above possible

**Comment by stevencohn** [comment]
When I double-click text it first selects that text on word boundaries.
A second double-click will keep it reselect the same text (watch closely and the first click seems to deselect and the second click reselects but OK)

Regardless, I'm not exactly sure what you're asking. If you mean, invoke an action automatically immediately after the double-click, I have no way of knowing that you just double-clicked and selected text. OneNote provides no event notifications for either double-click or text selection.

**Comment by 1001QAdotNET** [comment]
Yes that is what I meant.
How about Ctrl+Click ?

**Comment by stevencohn** [comment]
I like your optimism. No.

**Comment by 1001QAdotNET** [comment]
OK What can I say :-|
