### ISSUE TITLE
Save and restore the collapsed/uncollapsed state of each outline element

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#243]
if I have a doc where many OE are collapsed and I do a search in that document OneNote is uncollapsing the OE to show me the results. 
I would like to be able to save and restore the previous to the search state of the collapsed Outline Elements in one shot.
Ideal there should be some sort of repository or DB where this state should be maintained and updated by the user or automatically if the user configures that in the settings

**Comment by 1001QAdotNET** [comment]
Closed this by mistake sorry for that

**Comment by 1001QAdotNET** [comment]
grr ignore the comment regarding the search; it seems that after you close the search OneNote collapses back the sections by itself
However saving a preferred state of collapsed OE could be useful

**Comment by stevencohn** [comment]
This is closely related to the Edit/Expand and Collapse Outlining commands. Those implemented a special use case (probably too special) where the Expand command would remember which OEs where expanded, and the Collapse command would collapse those OEs only.

Ideally, those should be Expand All and Collapse All, without any additional smartness. And then there should be a two commands to record the current state of the page and then reapply that state later on.

**Comment by 1001QAdotNET** [comment]
yes this extends that functionality that I use a lot as I hate to see a wall of text when I study so I hide all I can behind the headings

**Comment by stevencohn** [comment]
OK, I think those existing commands should be replaced with the four I mentioned as they would be applicable to a wider audience. I need to consider this generally.
