### ISSUE TITLE
Feature request: Bidirectional Link text between Pages and add references as footnote

### ISSUE THREAD

**Issue by jakkaas** [stevencohn/OneMore#246]
Hello

I would like to have further Enhancement of link reference to this page feature.

In the "link reference to this page" feature, the current page and pages that reference this page by its title.

But I would like a manual reference between two pages.

For Eg If I select  a text for eg "XYZ" from page "A" create a link and link it to text "MNO" From Page "B"

Then if I click "XYZ" it will take me to "MNO" and if I click "MNO" It would take me to "XYZ".

To add more functionality to this feature, the option should create footnote-like references after the text from the page title from which it is linked.

![image](https://user-images.githubusercontent.com/43289832/127744700-d198c2fd-454e-4701-8f80-5240171bfe0f.png)

This would be very useful for research writing.

If I am taking content from certain websites /research papers, I would take the web clip of the reference material from the website into OneNote.

After that from whatever position of the OneNote page I am taking the material, I will link it to the content which I am creating and also creating footnotes of the title from which it is linked (I can also move bidirectionally between two linked text on clicking). Now, I can link many different OneNote Pages of different titles into the content which I am creating, with each part having being linked to the original source and with a footnote of all those pages from which it is linked

Hope it is clear

Thanks

**Comment by stevencohn** [comment]
Release along with v3.28.

This does not include the footnotes option. This makes the command a little less generic in my opinion. But it may be added as an option in the future.

**Comment by jakkaas** [comment]
Thank you :)
