### ISSUE TITLE
Creating a figure style

### ISSUE THREAD

**Issue by edogd** [stevencohn/OneMore#25]
Great Add On!
It's great that someone has been able to start an open source Add On to extend OneNote.  This has lot's of potential!

I would like to help, by creating a picture style.  It would an image that was pasted resize it, move it to the 1st row of a 1x2 table, and  setup the 2nd row cell to contain a caption.
It's not easy size pictures or images pasted in to OneNote consistently, especially if they are coming from screen shots or external files.  Also, OneNote has no concept of figure captions that stick with the picture as it is moved around the page.

I'd like to help by trying to make such a macro.  Can you suggest a good starting point in your code that I could use as a template?

**Comment by stevencohn** [comment]
That's a good idea. How would you "consistently" resize the images? Does that mean, make them smaller to fit in the current margins if they're too big, while not resizing them if they already are small enough to fit? Or something smarter? ;-)

**Comment by edogd** [comment]
So I used to take design notes in Power point and what I did there was use macro to change the size to a fixed picture size.  So for example I would insert a .png image, select the image, and click on the macro run (or hot key).  The picture would change to a fixed size and a fixed location.

In the context of OneNote, my first goal would be to size the picture to a fixed size to it fits within set margins.  Even the concept of margins is fuzzy in OneNote.  For me that concept is that text at 12pt should be readable along side the re-scaled image.

**Comment by stevencohn** [comment]
I added two new commands to resize images and to add a caption to an image. See the home page readme for more information.

**Comment by edogd** [comment]
I just tested it out.  

The Resize image function works well.  However, I can only get itto operate on just 1 image even when I select multiple images.

I tried the caption command too, but it seems not to do anything.  No table is created.

Let me know what I can do to help debug.

**Comment by stevencohn** [comment]
So the resize will affect all images on the page if none of them are selected. Otherwise you can only select one. I can enhance it to what you describe though no problem. 

The caption command adds a table with hidden borders. You should at least see the word "Caption" below the image. Again you have to select exactly one image for this command to work.

**Comment by stevencohn** [comment]
Release 2.7.2 will let you select one image, select many images, or no images in which case the resize applies to all.

**Comment by edogd** [comment]
v 2.7.2 multiple resize works great!

As for the caption feature, it still does nothing.  There is not even the word Caption.

**Comment by stevencohn** [comment]
Silly bug. Fixed here: https://github.com/stevencohn/OneMore/releases/tag/2.7.3

**Comment by stevencohn** [comment]
I'm glad it worked. Sorry for not testing it fully; I should have caught that.

As for Images outside of Outlines, that's a limitation of the OneNote XML schema. An Image can be in a Page or in an Outline. A Table, however, can only be in an Outline. So I could replace the stand-alone Image with a new Outline to hold the Table and Image and position it at the same location so it should ostensibly look the same. That should be pretty easy to do. I can do that tonight.

**Comment by stevencohn** [comment]
https://github.com/stevencohn/OneMore/releases/tag/2.7.4

**Comment by edogd** [comment]
It works great!
Thanks for working on this!
