### ISSUE TITLE
Applying any custom style resets font face to Calibri

### ISSUE THREAD

**Issue by rdx711** [stevencohn/OneMore#251]
The majority of my notes in OneNote have been imported from Evernote. The default font in OneNote 2016 is Calibri. After I imported my notes from Evernote to OneNote, I formatted all my notes [title and body] with my preferred font face [Verdana] and font size and cleaned up excess space using OneMore add-in and another macro software. All my notes are in Verdana [title and body].

I have customized the main custom styles [Headings 1,2,3 and Normal] in OneMore to be in Verdana. But when I apply the OneMore custom style [e.g. Heading 3] to a line of text in the body of the note, the page title changes to Calibri. Sometimes this also changes the text line to Calibri while changing the other properties [like font size and font colour] appropriately for Heading 3. Sometimes, applying Heading 3 to one line will change the font face of another random line in the page to Calibri. This happens not just to Heading 3 or Verdana; it happens with any custom style with any font face/size/colour I apply.

I can make the font resetting problem to go away by selecting the whole note [title and body] and removing formatting. Then the OneMore custom styles apply correctly to page body. It is only the imported notes that face this issue. The newly created notes/pages do not face any problem at all. This makes me think the problem may partly be with OneNote or how it imported the notes from Evernote. In which case I would appreciate any help how to prevent this from happening without resetting the formatting for all my notes [over 2000 of them].

🤟 Thanks for such an amazing add-in.

💬 A suggestion : to make a sub-reddit to engage with a wider user base.

**Comment by stevencohn** [comment]
Could you possibly take a minute to do this:

1. Import a page from Evernote that you know would demonstrate this behavior. Don't make any modifications yet.
2. Save the page as XML and attach it here

Thanks

**Comment by rdx711** [comment]
After importing from Evernote to OneNote last year, I had uninstalled Evernote. To import a page again, I reinstalled the same version of Evernote and used the same tool from Microsoft to import but it did not import and gave an error:

>We couldn’t import the following notes because An unexpected error was encountered. Please try again later. Try copy and pasting them into OneNote manually.
>        Stories > All notes
>session id:  {**********}

I tried deleting all credentials from Windows, signed in again in the tool, but same error. I exported a notebook as .enex file and tried importing again, but same error. I tried running the tool as administrator, but same error. So I guess I cannot do what you asked. I can instead attach the .xml of the following 3 types of pages:

- Imported from Evernote > Changed title and body font face to Verdana > Cleaned using OneMore [The_99_Club.xml]
- Imported from Evernote > Changed title and body font face to Verdana > Cleaned using OneMore > Remove formatting from title and body [An_Old_Cherokee_Tale_of_Two_Wolves.xml]
- Created a new page and no changes made [.xml]

I can also provide you with the .enex file for a notebook that I exported from Evernote. It is a notebook with just 5 notes which are some short stories collected from internet. This way maybe you can try importing it yourself to see if it works for you and whether there is something wrong in my Evernote content.

[Temporary.zip](https://github.com/stevencohn/OneMore/files/7015814/Temporary.zip)

**Comment by stevencohn** [comment]
Sorry, until I get a repeatable use case, I won't be able to fix this so closing this for now
