### ISSUE TITLE
Let us configure the calendar´s week start

### ISSUE THREAD

**Issue by JonAnder83** [stevencohn/OneMore#258]
**Is your feature request related to a problem? Please describe.**
Nope, not related to any problem: It's a functional improvement suggestion

**Describe the solution you'd like**
A settings option where we can set wether we want the week to start on monday or sunday

**Describe alternatives you've considered**
There's another plugin that does so, but I like the formatting this plugin applies way better.

**Additional context**

THE FINE PRINT
This is a hobby project that I started for myself. I'm happy to take requests and will promise to consider each one carefully but offer no guarantees that I will ultimately agree to their usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
Thanks for the idea

**Comment by stevencohn** [comment]
Latest release 4.1.1 https://github.com/stevencohn/OneMore/releases

**Comment by JonAnder83** [comment]
That was fast! That was exactly what I meant. Thank you!!!
