### ISSUE TITLE
Can't Edit Keyboard Shortcuts under Favorites

### ISSUE THREAD

**Issue by OhMyDawg** [stevencohn/OneMore#259]
Hey, I'm seeing a problem when I try to access Favorites-.OneNote Keyboard Shortcuts. I get a "Could not download or import template" error.

Here's what I see in the logs.

3128:16] Running command ShowKeyboardShortcutsCommand
3128:16] ..downloading template
3128:6] ..extracting C:\Users\xxxxx\AppData\Local\Temp\tmpB404.tmp
3128:6] ..error extracting template
3128:6] ..System.IO.InvalidDataException
Message: End of Central Directory record could not be found.
Source: System.IO.Compression
StackTrace: at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
at System.IO.Compression.ZipArchive..ctor(Stream stream)
at River.OneMoreAddIn.Commands.ShowKeyboardShortcutsCommand.ExtractTemplate(String path)
TargetSite: [System.IO.Compression] System.IO.Compression.ZipArchive::ReadEndOfCentralDirectory()

That tmp file is not found when I look in the folder. I'm thinking it's looking in the wrong place for that template file?

BTW, this app makes Onenote so much more useful. Thanks for providing it.

**Comment by stevencohn** [comment]
Thanks for pointing this out. Will be fixed in the next release.

**Comment by stevencohn** [comment]
Latest release 4.1.1 https://github.com/stevencohn/OneMore/releases
