### ISSUE TITLE
Feature Request: Apply a consistent formatting in all OneNote containers

### ISSUE THREAD

**Issue by coderxyz** [stevencohn/OneMore#26]
Thank you for creating the Merge Command feature. When the pages gets merged, individual page gets it own container. For some reasons, the formatting of the container doesn’t respect the font type and size. Is there any way to implement it?

Also sometimes, OneNote itself forgets the formatting when creating a new content (different container) in a page. I have to select that container and choose my font type + size. 

So is there any way, where I can select all the containers and apply a consistent font type and size? 

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by stevencohn** [comment]
It was designed to preserve formatting and the easiest way was to copy and append the outlines as is. 

Merging styles would possible loose important formatting and make the other 50% of people unhappy ;-). But seriously I could consider this as a future option.

**Comment by stevencohn** [comment]
Merging containers when all pages each contain exactly one container. Otherwise, containers are collected and added to the target page as originally designed. See issue #111
