### ISSUE TITLE
Snippets -> Code Block : Monospace font?

### ISSUE THREAD

**Issue by JonAnder83** [stevencohn/OneMore#261]
**Is your feature request related to a problem? Please describe.**
Not a problem but what I think might be an enhancement.

**Describe the solution you'd like**
How about code blocks have a monospace font configuration? Code is usually represented like this to make it more readable.

**Describe alternatives you've considered**
I can always manually format it afterwards

**Additional context**
None particularly.

THE FINE PRINT
This is a hobby project that I started for myself. I'm happy to take requests and will promise to consider each one carefully but offer no guarantees that I will ultimately agree to their usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
Actually it already does have a monospace font. The default text you see when you first create a code block, "Your code here...", is set as Consolas/10 which is monospace. If you paste rich text or HTML into that directly, it will use the format of what you paste. But if you use OneNote's Paste with _Keep Text Only_ function_ then it will retain the Consolas/10 font. 

![image](https://user-images.githubusercontent.com/9964757/131836227-8102d90d-8714-4651-9653-abd15f3859ba.png)

**Comment by stevencohn** [comment]
Additionally, if you have selected code on a page, you can "capture" it inside a code block by running the Code Block snippet. It will retain whatever font and color treatment already applied to the text
