### ISSUE TITLE
Update to Link Reference functionality

### ISSUE THREAD

**Issue by MehsEzeerf** [stevencohn/OneMore#263]
I would like to pull references to the page that was referenced so that something like this 

![image](https://user-images.githubusercontent.com/66741217/132013455-5585ddc2-e01f-4866-a83a-0e1b11945e36.png)

will show up like this on the page that was referenced.  In this case CLL

![image](https://user-images.githubusercontent.com/66741217/132013586-34a363df-2cb3-4be1-ae7b-fb6f99b42b16.png)

**Comment by stevencohn** [comment]
I'm not exactly sure what I'm looking at. Can you explain what you're trying to achieve?

**Comment by MehsEzeerf** [comment]
I will try to record a video

**Comment by stevencohn** [comment]
No response. If you have more info, please submit a new ticket with detailed information
