### ISSUE TITLE
Resize images bug: Preset width on 1 image

### ISSUE THREAD

**Issue by andyylin** [stevencohn/OneMore#269]
**Describe the bug**
In the Resize Image function, if I only have one image selected and choose "Preset" option, and uncheck "Preserve original size", the image's "current size" is reduced to the preset width but still retains the original size.

**To Reproduce**
1. Select an image
2. Resize Image
3. Select Preset, choose a width
4. Uncheck "Preserve original size", click OK
5. Image's current size matches preset, but "Original size" is still the same

**Expected behavior**
Expect "Original size" to shrink down to the Preset width

**Environment (if applicable):**
 - OneNote Version: Microsoft 365
 - OneMore Version 4.3

**Additional context**
7852:17] Running command ResizeImagesCommand
7852:17] ..resized image @ 00:01.09
7852:17] ..resized image @ 00:01.16
7852:17] Running command AboutCommand

**Comment by stevencohn** [comment]
Fixed. Will be available in next release.
