### ISSUE TITLE
Breadcrumb doesn’t handle slashes “/“ properly

### ISSUE THREAD

**Issue by andyylin** [stevencohn/OneMore#272]
**Describe the bug**
Creating a breadcrumb where a title has slashes will cause the title to be partially included in the breadcrumb

**To Reproduce**
1. Have a title with a "/" character in it
2. Create breadcrumb

**Expected behavior**
Should still exclude the page title

**Screenshots**
![image](https://user-images.githubusercontent.com/51783311/133023045-842c87d5-fd93-4b03-b2df-3079480dd4c6.jpeg)

**Comment by stevencohn** [comment]
The breadcrumb command should NOT be including any part of the page name at all. I don't seem to be able to reproduce this.

**Comment by stevencohn** [comment]
This is duplicated by #273. I'll fix this.

**Comment by stevencohn** [comment]
Extension of #273, in which the notebook name was not included if the page was more than one level deep under a section group. Pending release fixes #272 and #273
