### ISSUE TITLE
Word Count of Selected Text

### ISSUE THREAD

**Issue by Raquo116** [stevencohn/OneMore#277]
Kudos to your work.
As of now, the word count feature tells all words on the whole page. I have one request regarding the word count of selected text. 
Is it possible to implement this feature? 
Helpful for people writing a thesis/summary in a definite word limit.

**Comment by stevencohn** [comment]
Yes, will be in the next release.

**Comment by Raquo116** [comment]
Can you pls add this in the Context Menu Option ?? Easy to click...... by selecting the text and then right-clicking to get the result.

**Comment by stevencohn** [comment]
Will be in the next release
