### ISSUE TITLE
Add Timer to onemore

### ISSUE THREAD

**Issue by disipp** [stevencohn/OneMore#279]
Hello
Would you please add a timer to onemore?
You can press everytime you want to insert the timer. Useful for taking notes while recording the lecture.

**Comment by stevencohn** [comment]
I'm not sure what I could do that would be more effective than many countdown timers already available. The Windows App Store has quite a few for free

**Comment by 1001QAdotNET** [comment]
Sounds like a very good idea
He wants to be able to corelate his notes with a recording. When in class probably he is using Windows to record the class but he would like to take notes and correlate that with the recording 
I guess ideally it would be nice to start any new note by inserting a time stamp given by the timer that he started when the class begun.

**Comment by stevencohn** [comment]
The OneNote Insert ribbon has buttons to insert TIme or Date+Time. Is that what you mean?

**Comment by 1001QAdotNET** [comment]
nope that is the current date/time
He needs the time lapsed since the recording of the class started

**Comment by stevencohn** [comment]
Got it! Thanks
