### ISSUE TITLE
Add the binary type to the About dialog

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#286]
in this About dialog it would be nice to have the binary type (ex x86 or x64) 
I always forget if I am use x64 or x86 and I am using this on three computers with different OneNote versions so it would be nice to be able to find out quickly what binary I need to install 

Update: I am now seeing that check for updates does this automatically but it could still be nice to have the info there

**Comment by stevencohn** [comment]
The OneNote About dialog shows this. 

OneMore isn't specifically x86 or x64; it is compiled as "Any" which means it assumes the architecture of its host, in this case OneNote. So OneNote is really what you want to look at, not OneMore

**Comment by stevencohn** [comment]
.... There are two OneMore installers but that's just the installer itself - both installers drop exactly the same OneMore binaries on the disk

**Comment by 1001QAdotNET** [comment]
Ok then what I wanted to know is if I am running x86 or x64 so there could be a line saying:
"for manual installation use the x86/x64 installer" 
I will probably use the update options since I now know it does that for me but sometimes if there is a bug you won't know which older version to use to revert if this info is not there

**Comment by stevencohn** [comment]
I can put the info there but it absolutely doesn't matter unless you have an x86 machine. Only in that case do you always need to use the x86 installer.

If you have an x64 machine, you can use either installer. And in fact, you can install v1 with x64, v2 with x86, v3 with x64, etc. It doesn't matter. The binaries are the same. The ONLY difference is that the x86 installer buts the binaries under Program Files (X86) and the x64 installer puts the binaries under Program Files. That's all.

**Comment by 1001QAdotNET** [comment]
Got it, ok I did not realize that the installer will fail if the machine type is not correct , please close this one
