### ISSUE TITLE
Are you watching the Discussions section for featurr requests?

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#287]
I jus posted there today but so farno feedback
Should I contimue to post here?

**Comment by stevencohn** [comment]
I saw it. Please remember, this is a hobby project. I try to stay as attentive as possible but do have other things I need to attend to as well. :-) I may not respond in a day or two but will...

**Comment by 1001QAdotNET** [comment]
Oh O did know that but it would make more senee to encourage posting things there and move them over here when you decide they are going to be implemented. Since I saw more traffic here I started tobsuspect that the section slid innto shadow and it is not watched that much

**Comment by stevencohn** [comment]
LOL! You posted yesterday. I didn't respond within 18 hours... that's sliding into the shadows? hehehe

But seriously, I expected the discussions to take off slowly, if they take off at all. Realistically, OneMore has a pretty small user community - a couple of hundred stars but that doesn't mean that many active users. If discussions don't gain any traction, I'll just shut it down. No biggie. For now, post either there or here. I'll keep an eye on both. But don't be surprised if I don't react to either for a couple of days depending on how stressful my real job or the real world gets.

**Comment by stevencohn** [comment]
FWIW, you're entry about task scheduling is perfect for the discussion area. If ideas like that start to gain clarify then they can become issue tickets to track the work. So thanks!

**Comment by 1001QAdotNET** [comment]
Yes that is why I posted there. I l know what you mean ...I went on a tangent since we spoke about having a scripts repository and I am still far away from what I was doing...planing to return to that but things keep popping up
