### ISSUE TITLE
How do I connect an add-in for OneNote?

### ISSUE THREAD

**Issue by it19862** [stevencohn/OneMore#29]
**Question.**
How do I connect an add-in for OneNote?
When I add an add-in to OneNote I get an error: "This is not a valid Office Add-in"
 
**Description.**
I am using the project: "Class Library (.NET Framework)".
I have created an add-on.
I added libraries:
   -   "Extensibility";
   -   "Microsoft.Office.Interop.Excel" (version 16);
   -   "System.Windows.Forms";
   -   COM: Microsoft Office 16.0 Object Library.

I added a class: MyConnect.cs.
I added a file: Ribbon.xml.
I added the add-on to the registry.
I am adding an add-in to OneNote
**Result:** 
Error:
_C:\test\AddinOneNoteClassLibrary01\p01\AddinOneNoteClassLibrary01.dll "is not a valid Office add-in._
 
**Used.**
  - .NET Framework 4.7.2
  - win 7x64
  - MS Office 2016
  - OneNote 2016 x64 for Office 365 MSO (16.0.12527.20986) (Version 2002 (Build 12527.20988))

**RegKeysImport.reg**
`Windows Registry Editor Version 5.00
 
[HKEY_CLASSES_ROOT\AppID\{C33CAD6D-E14D-45D5-94E5-6A9861061129}]
"DllSurrogate"=""
 
[HKEY_CLASSES_ROOT\AddinOneNoteClassLibrary01.MyConnect\CLSID]
"(Default)"="{C33CAD6D-E14D-45D5-94E5-6A9861061129}"

[HKEY_CLASSES_ROOT\CLSID\{C33CAD6D-E14D-45D5-94E5-6A9861061129}]
"AppID"="{C33CAD6D-E14D-45D5-94E5-6A9861061129}"

[HKEY_CLASSES_ROOT\WOW6432Node\AppID\{C33CAD6D-E14D-45D5-94E5-6A9861061129}]
"DllSurrogate"=""

[HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{C33CAD6D-E14D-45D5-94E5-6A9861061129}]
"(Default)"="AddinOneNoteClassLibrary01.MyConnect"
"AppID"="{C33CAD6D-E14D-45D5-94E5-6A9861061129}"
 
[HKEY_CURRENT_USER\Software\Classes\AppID\{C33CAD6D-E14D-45D5-94E5-6A9861061129}]
"DllSurrogate"=""
 
[HKEY_CURRENT_USER\Software\Classes\AddinOneNoteClassLibrary01.MyConnect\CLSID]
"(Default)"="{C33CAD6D-E14D-45D5-94E5-6A9861061129}"

[HKEY_CURRENT_USER\Software\Classes\WOW6432Node\CLSID\{C33CAD6D-E14D-45D5-94E5-6A9861061129}]
"(Default)"="AddinOneNoteClassLibrary01.MyConnect"
"AppID"="{C33CAD6D-E14D-45D5-94E5-6A9861061129}"

[HKEY_CURRENT_USER\Software\Classes\CLSID\{C33CAD6D-E14D-45D5-94E5-6A9861061129}]
"AppID"="{C33CAD6D-E14D-45D5-94E5-6A9861061129}"
 
[HKEY_LOCAL_MACHINE\Software\Classes\AppID\{C33CAD6D-E14D-45D5-94E5-6A9861061129}]
"DllSurrogate"=""
 
[HKEY_LOCAL_MACHINE\Software\Classes\CLSID\{C33CAD6D-E14D-45D5-94E5-6A9861061129}]
"AppID"="{C33CAD6D-E14D-45D5-94E5-6A9861061129}"
 
[HKEY_LOCAL_MACHINE\Software\Microsoft\Office\OneNote\AddIns\AddinOneNoteClassLibrary01.MyConnect]
"Description"="Description - AddinOneNoteClassLibrary01 MyConnect"
"FriendlyName"="AddinOneNoteClassLibrary01"
"LoadBehavior"=dword:00000003`

**MyConnect.cs**
`namespace AddinOneNoteClassLibrary01
{   

    [System.Runtime.InteropServices.ProgId("ExcelCOMAddin.MyConnect")]
    [System.Runtime.InteropServices.ComDefaultInterface(typeof(IMyConnect))]
    // [System.Runtime.InteropServices.Guid("DE3911A1-C82F-42F1-BEFB-F3802E1B6D34")]
    [System.Runtime.InteropServices.Guid("C33CAD6D-E14D-45D5-94E5-6A9861061129")]
    [System.Runtime.InteropServices.ClassInterface(
        System.Runtime.InteropServices.ClassInterfaceType.None)]
    [System.Runtime.InteropServices.ComVisible(true)]
    public class MyConnect : IMyConnect
    {
        Microsoft.Office.Interop.OneNote.Application _ApplicationObject;
        Microsoft.Office.Core.COMAddIn _AddinInstance;

        public void OnConnection(
            object Application,
            Extensibility.ext_ConnectMode ConnectMode,
            object AddInInst,
            ref Array custom)
        {
            this._ApplicationObject = (Microsoft.Office.Interop.OneNote.Application)Application;

            if (this._AddinInstance == null)
            {
                this._AddinInstance = (Microsoft.Office.Core.COMAddIn)AddInInst;
                this._AddinInstance.Object = this;
            }

            System.Windows.Forms.MessageBox.Show("onConnection");
        }
        public void OnDisconnection(
            Extensibility.ext_DisconnectMode RemoveMode,
            ref Array custom)
        {
            this._ApplicationObject = null;
            this._AddinInstance = null;
        }
        public void OnAddInsUpdate(ref Array custom)
        { }
        public void OnStartupComplete(ref Array custom)
        { }
        public void OnBeginShutdown(ref Array custom)
        { }

        //public string GetCustomUI(string RibbonID)
        //{
        //    return "";
        //}

        public string GetCustomUI(string RibbonID)
        {
            return GetResourceText("COMExcelModelCover.Ribbon.xml");
        }

        private static string GetResourceText(string resourceName)
        {
            System.Reflection.Assembly asm = System.Reflection.Assembly.GetExecutingAssembly();
            string[] resourceNames = asm.GetManifestResourceNames();

            for (int i = 0; i < resourceNames.Length; ++i)
            {
                if (string.Compare(resourceName, resourceNames[i], StringComparison.OrdinalIgnoreCase) == 0)
                {
                    using (System.IO.StreamReader resourceReader = new System.IO.StreamReader(asm.GetManifestResourceStream(resourceNames[i])))
                    {
                        if (resourceReader != null)
                        {
                            return resourceReader.ReadToEnd();
                        }
                    }
                }
            }
            return null;
        }

        public void Button_One_Click(Microsoft.Office.Core.IRibbonControl control)
        {
            System.Windows.Forms.MessageBox.Show("Button_One_Clicked");
        }

        public void Button_Two_Click(Microsoft.Office.Core.IRibbonControl control)
        {
            System.Windows.Forms.MessageBox.Show("Button_Two_Clicked");
        }

    }`

**Ribbon.xml**
```
<?xml version="1.0" encoding="utf-8" ?>
<customUI xmlns="http://schemas.microsoft.com/office/2006/01/customui">
	<ribbon>
		<tabs>
			<tab id="MyNewRibbonTab"
					  insertBeforeMso="TabInsert"
					  label="BETTER">
				<group id="Group_ID_One" label="MyGroup">
					<button id="Button_ID_One"
								  imageMso="Help"
								  onAction="Button_One_Click"
								  label="Button 1"
								  size="large"/>
					<separator id="Separator_ID_One"/>
					<button id="Button_ID_One"
								  imageMso="Help"
								  onAction="Button_One_Click"
								  label="Button 1"
								  size="large"/>
				</group>
			</tab>
		</tabs>
	</ribbon>
</customUI>
```

**Picture-1**
![2020-08-15_16-06-59](https://user-images.githubusercontent.com/18245828/90315719-4e156e00-df26-11ea-8da6-1c02d42c8619.png)

**Picture-2**
![2020-08-15_18-22-05](https://user-images.githubusercontent.com/18245828/90315723-58376c80-df26-11ea-94c0-2c5d24fe03c9.png)

**Picture-3**
![2020-08-15_18-24-16](https://user-images.githubusercontent.com/18245828/90315725-5c638a00-df26-11ea-9246-5a4a3f2550be.png)

**Picture-4**
**HKEY_CURRENT_USER\Software\Microsoft\Office\Excel\Addins\AddinOneNoteClassLibrary01.MyConnect**
![2020-08-15_18-27-14](https://user-images.githubusercontent.com/18245828/90315728-608fa780-df26-11ea-9c85-adcf7166ace2.png)

**Picture-5**
![2020-08-15_18-28-34](https://user-images.githubusercontent.com/18245828/90315734-67b6b580-df26-11ea-9c9a-f467421873e0.png)

**Comment by stevencohn** [comment]
I recommend starting with Microsoft's Vanilla example https://github.com/OneNoteDev/VanillaAddIn

**Comment by it19862** [comment]
@stevencohn  
I understand that I should ask questions about `OneNoteDev / VanillaAddIn` in the project` OneNoteDev / VanillaAddIn`
But could you answer, I'm afraid that I will wait a long time for their answer.
Thank

**The instructions say:**
1.replace all "VanillaAddIn" strings;
2.replace ProductCode, PackageCode, and UpgradeCode in .vdproj.

**Questions.**

1. What strings is said in item 1?
    Where are `strings` found?
2. p.2 .vdproj is ..\Setup\Setup.vdproj?
3. Where to get the data for ..\Setup\Setup.vdproj ProductCode line 3023?
   Just segment an arbitrary GUID?
4. Where can I get data for ..\Setup\Setup.vdproj PackageCode?
    Just segment an arbitrary GUID?
5. Where can I get data for ..\Setup\Setup.vdproj UpgradeCode?
   Just segment an arbitrary GUID?

**Comment by stevencohn** [comment]
Add the "Microsoft Visual Studio Installer Project" extension to visual studio. This will manage all those values for you and build the .vdproj

**Comment by stevencohn** [comment]
You seem to have been able to rebuild the setup project in issue #30. Closing this for now
