### ISSUE TITLE
Bidirectional Link Error

### ISSUE THREAD

**Issue by disipp** [stevencohn/OneMore#297]
Hello. I want to use Bidirectional link in one page. sometimes I see this error when I try to add link to some words. when I select another word it works correctly also when I go to another page or section it works correctly without any error. I dont why some words cant be linked?
![image](https://user-images.githubusercontent.com/90924203/134895321-fb5432b3-d0c9-4c2b-bc98-b8defef9d5c8.png)

**Comment by stevencohn** [comment]
You cannot link two ranges of text within the same paragraph.

**Comment by disipp** [comment]
there arent in the same paraghraph

**Comment by disipp** [comment]
I use persian language for typing. I dont know it is important or not

**Comment by stevencohn** [comment]
I may need an example then. I don't have a use case that reproduces this

**Comment by disipp** [comment]
when I open two onenote window (Ctrl+M) then I click on bidirectional link  I see this error sometimes.
