### ISSUE TITLE
Batch web page imports

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#300]
The import web page feature is great.
If you agree I would like to see that taken one notch up, and here is how I see it:
OneMore--> Batch Web Page Import --> the current link from clipboard gets added to the next dialog --> offer the user to filter the links that will be automatincaly extracted from that page (ex from this page  https://math.hws.edu/javanotes/ I would like to only get the links that contain the keyword javanotes) 
In the next step, if no keyword or filtering (regex wouyld be nice) was provided then show the user a list of links that are on the target page and again the posibility to filter the list by keyword and/or to manually select which links to be imported
This should use the existing functionality of the current Import Web page command (create new page, child pages etc) and add -"Merge all the above in one page" with page titles and links as paragraph headings

This will help tremendously with importing online books into OneNote for further reading and annotations

**Comment by stevencohn** [comment]
@1001QAdotNET  This is not exactly what you described but it's close. Instead of starting with a URL, you start with a page that contains URLs (like a previously imported index page from the Web.) It will present a dialog from which you select the URLs you want to import. Each will be imported as a sub-page of the current page.

There's still some refinement to do, such as filtering out URLs that are Web assets rather than Web pages for example. But it should be functional for what you want to do.

**Comment by 1001QAdotNET** [comment]
Right in time. I hope that starting with this week I will resume my learning activities.  I will definitelly use this. I did not mention this but maybe I should have....will it be possible to handle authentication if required?

**Comment by 1001QAdotNET** [comment]
I did not forget about this but I got dragged into other things. I was going to literarily start tomorrow

**Comment by 1001QAdotNET** [comment]
Ok I just attempted to test this and it does nothing
After checking the logs I am seeing this
```
24124:3] Running command ImportWebCommand
24124:14] ..importing web page https://math.hws.edu/javanotes/
24124:15] ..Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
24124:15] ..System.DllNotFoundException
Message: Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
Source: Microsoft.Web.WebView2.Core
StackTrace:    at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateCoreWebView2EnvironmentWithOptions(String browserExecutableFolder, String userDataFolder, ICoreWebView2EnvironmentOptions options, ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler environment_created_handler)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at River.OneMoreAddIn.UI.WebViewWorkerDialog.<StartWorkLoaded>d__4.MoveNext()
TargetSite: [Microsoft.Web.WebView2.Core] Microsoft.Web.WebView2.Core.CoreWebView2Environment::CreateCoreWebView2EnvironmentWithOptions()

```
