### ISSUE TITLE
Sorting for bullet points in text

### ISSUE THREAD

**Issue by kaipingqi** [stevencohn/OneMore#302]
Hi there, it would be nice to have a text sorting function for bullet points. Would be super useful. :)

**Comment by stevencohn** [comment]
Interesting

**Comment by kaipingqi** [comment]
It's quite a big pain-point for me, this feature was also already requested by a lot of random folks on the internet but never got implemented, check here:
[Is it possible to alphabetize lists in OneNote?](https://login.live.com/login.srf?wa=wsignin1.0&rpsnv=13&ct=1633122716&rver=6.7.6643.0&wp=MBI_SSL&wreply=https:%2F%2Fanswers.microsoft.com%2Fen-us%2Fsite%2Fcompletesignin%3Fsilent%3DFalse%26returnUrl%3Dhttps%253A%252F%252Fanswers.microsoft.com%253A443%252Fen-us%252Fmsoffice%252Fforum%252Fall%252Fis-it-possible-to-alphabetize-lists-in-onenote%252F746d1734-7513-4ce3-8c88-3d8ca8391547%253Fauth%253D1&id=273572&aadredir=1)
