### ISSUE TITLE
OneMore failed to connect to OneNote

### ISSUE THREAD

**Issue by derekvof** [stevencohn/OneMore#307]
**Describe the bug**
On launch, I get an error message after installation of the latest version 4.8.1 of OneMore

I have read the troubleshooting post. I've tried to uninstall/reinstall OneMore, Repair Office (both fast and online method), removed the data folder under AppData. Still no luck.

**To Reproduce**
1. Start OneNote
2. Get error

**Expected behavior**
Expect it to start up.

**Screenshots**
![image](https://user-images.githubusercontent.com/50592102/136602292-52df1761-d233-4207-9078-e8623f1abd76.png)

**Environment (if applicable):**
 - OneNote Version: Office 365 Version 2102 (Build 13801.20960)
 - OneMore Version 4.6.1 x64 install

**Additional context**
Log attached
[OneMore.log](https://github.com/stevencohn/OneMore/files/7313350/OneMore.log)

**Comment by stevencohn** [comment]
Just noting what's in the error log here....

```
7544:1] Starting dllhost 7544, CPU=1803Mhz, en-US/en-US, v4.8.1, OneNote 15.0, Office 16.0
7544:1] ..OnConnection(ConnectionMode:ext_cm_Startup,1)
7544:1] ..OneAddInsUpdate(custom[]:0)
7544:1] ..building ribbon
7544:1] ..building ribbon colorizer commands
7544:1] ..OnStartupComplete(custom[]:0)
7544:1] ..error starting add-on
7544:1] ..System.InvalidCastException
Message: Unable to cast COM object of type 'Microsoft.Office.Interop.OneNote.ApplicationClass' to interface type
'Microsoft.Office.Interop.OneNote.IApplication'. This operation failed because the QueryInterface call on the COM component for
the interface with IID '{452AC71A-B655-4967-A208-A4CC39DD7949}' failed due to the following error: Interface not registered
(Exception from HRESULT: 0x80040155).
Source: mscorlib
StackTrace:    at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean&
pfNeedsRelease)
   at Microsoft.Office.Interop.OneNote.IApplication.GetSpecialLocation(SpecialLocation slToGet, String& pbstrSpecialLocationPath)
   at River.OneMoreAddIn.OneNote.GetFolders()
   at River.OneMoreAddIn.AddIn.OnStartupComplete(Array& custom)
TargetSite: [mscorlib] System.StubHelpers.StubHelpers::GetCOMIPFromRCW()
```

**Comment by stevencohn** [comment]
This looks to be a problem with the installation of OneNote itself and the registration of its COM interface. This should have been fixed when you reinstalled OneNote or repaired Office. I've not seen this before. I'll need to see if I can get my hands on that specific version of Office 365 but I don't have general access to all versions so we'll see.

OneMore relies on this COM interface existing but has no control over whether it exists.

**Comment by stevencohn** [comment]
Some older versions of the install (I think prior to 4.7.1) didn't fetch the correct installer, x86 or x64. I think that is fixed but needs verifying.

Also considering whether to continue support of x86 at all. Don't know how many people still have x86 installs of Office

**Comment by stevencohn** [comment]
@1001QAdotNET are you still running a previous version? The installer should allow a pure upgrade path, meaning you can run a newer installer directly without first uninstalling a previous version. Give that a try to upgrade to 4.10.1.

Currently the OneMore/About/Upgrade option will first uninstall the old and then install the new but I'm going to change that to simply upgrade without uninstalling. That may help settle things down for all.

**Comment by 1001QAdotNET** [comment]
Yeah I just tried that and it worked, not sure why it did. I never uninstall manually. all good now

**Comment by 1001QAdotNET** [comment]
BTW, related to this an upgrade done via OneMore `check for an update` failed on my work laptop 
Maybe you can include the option to elevate the permissions 
https://i.imgur.com/B4QIhkl.png

**Comment by 1001QAdotNET** [comment]
hmmm that was strange -I think it was because of some timeout (I was doing something else on another computer)
After I ACKed the dialogs the install continued and succeede

**Comment by stevencohn** [comment]
OK good, the installer should elevate itself where it needs to be elevated, unless your work laptop has a group policy that specifically prevents you from installing SOUP (software of unknown provenance)
