### ISSUE TITLE
[Top of page] added every time I clicked on refresh.

### ISSUE THREAD

**Issue by tbelbek** [stevencohn/OneMore#309]
When I added a in-page TOC with [Top of page] links, inserting very well. But when I click refresh, the [Top of page] link is being added to headers every time I click refresh on the index.

- Add a page TOC with [Top of page] option selected.
- Refresh the TOC with the link on the header.

I expect to only refresh, not the addition of the links again and again.

Onenote 2021
Onemore 4.8

**Comment by stevencohn** [comment]
Ooops! LOL. Yeah, that's not good.
