### ISSUE TITLE
Import a list of meetings from Outlook

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#318]
I keep my To do list in Outlook
I would like to be able to use OneMore to automatically import a list of meetings from Outlook
I would see it working this way:
    -I place the cursor at a specific position on the page
    -if there is an outline there that is the current outline where I want the meetings imported as a list
    -if there is no outline one should be created
    -if the outline exists and it already has content (let's say previous meetings were imported the day before) then I want the content of the outline wiped out an updated meeting list will be inserted (see below)
    -when the user clicks on "**Insert or update upcoming meeting list**" (let's say this is what we call this feature)  then the user should be presented with a month calendar and allowed to pick the day for which the meetings will be imported
    -when the meetings are inserted in the outline they will be listed like below
                     -Date
                          start time-end time   Meeting Name or topic
                                         participants
                                         meeting description 

Thank you
1001qa

**Comment by stevencohn** [comment]
With the addition of #295 (OneMore reminders) and #349 (Import Outlook tasks), I'm closing this ticket.
