### ISSUE TITLE
Merge Pages

### ISSUE THREAD

**Issue by piyush1908** [stevencohn/OneMore#32]
1. Sir can we merge pages using your extention (that's what I've been looking for so long)
2. Will you add wild cards for search and replace in future

**Comment by stevencohn** [comment]
1. Yes, there is a Merge Pages command
2. I haven't considered wildcards for search and replace that but that's interesting... thanks for the suggestion

**Comment by piyush1908** [comment]
Sir Merge pages, TOC in extras tab is not working

![image](https://user-images.githubusercontent.com/12750186/90668397-ae314a80-e26d-11ea-9665-fe46c5c2f48f.png)

**Comment by stevencohn** [comment]
So it looks like you didn't click on the body of the page. Those menu items only activate once the focus is on the body of your page.

I can't speak to that message dialog box you showed; that looks like a policy issue set by your company, presuming this is a work device.

**Comment by piyush1908** [comment]
- Sir I know it accepts regular expression, What I wanted was special type of search and replace as in Microsoft Word (which starts with Ctrl + H)
- Regarding merger of pages: 
1. OneMore doesn't allow a page to be merged if it has no content under it). Also If try to merge 5 pages and if in between there is 1 page which doesn't have content, Function will not run at all.
2. Page title are gone when pages are merged (I wish Titles are retained)
3. It takes time to merge pages, which is natural (So if there be a green bar which indicates, that pages are being merged, I would be relieved that ok, app is running fine)
4. Also when pages are merged, can a way be devised that they all come under single text box, What happens is If 4 pages have been merged, 4 new text boxes are created, I have to cut and paste in word, then paste back in OneNote

- Regarding table of content
1. Onenote hangs when I try to add new heading style or try to create table of content

**My overall assessment of App (5/5), Its most awesome and comprehensive app I've ever seen**

Certain Suggestion for future app development can be
1. Allow bullets to be hidden (If I completed that task or have revised that bullet)
2. Allow rotation of Image by slight angle (like in powerpoint)
3. Allow export to HTML (Currently only mht which doesn't include images)
4. Print as very long single page pdf 
5. Allow image to be edited in paint
6. Allow scanned images contrast to corrected (Like what Camscanner app does)
7. Slideshow like in evernote
8. Tagging system like in evernote
9. Allow google voice typing (Currently I use unified remote on my android which allows me to voice type on Onenote)

![image](https://user-images.githubusercontent.com/12750186/91143961-f2d73e80-e6d0-11ea-8f90-d11bf4a4af7e.png)
![image](https://user-images.githubusercontent.com/12750186/91144546-cff95a00-e6d1-11ea-87f0-286170407c81.png)
![image](https://user-images.githubusercontent.com/12750186/91144789-223a7b00-e6d2-11ea-9845-b43bf1634843.png)
![image](https://user-images.githubusercontent.com/12750186/91145270-cfad8e80-e6d2-11ea-9df8-a6846fdae56b.png)

**Comment by stevencohn** [comment]
Hi, wow, this is pretty extensive. Thanks for that.

**Search and replace** - Ctrl-H is implemented and allowed Match Case and regular expression so covers almost all of the checkboxes in the dialog you show from Word, with the exception of the language-specific options.

**Merge** - You're not the first to ask about that and I'm looking into it because apparently it's important to people

**Hangs** - I can't reproduce, if you could provide the XML of a page on which this happens, that would be helpful

**Other** - I like some of those

**Comment by piyush1908** [comment]
Search and replace- If you could allow search and replace of
1) graphic/images
2) line breaks, page breaks, white spaces 
3) search replace of peculiar font style, size with another (as in word)

Tagging
1) Try evernote (you will see, how well tagging system is

**Comment by piyush1908** [comment]
Sir One Most important feature- Anchor ink to image plz if you can make it

**Comment by stevencohn** [comment]
"Anchor link to image"? Do you mean add a hyperlink to an image, so click and image and it activates a hyperlink?

**Comment by piyush1908** [comment]
No i mean e-ink to stick on image and be treated as one pbject whilst I
move ghe object

**Comment by stevencohn** [comment]
OneNote doesn't allow this and there is insufficient support in its API to write this as an addin unfortunately.

**Comment by piyush1908** [comment]
Merge Pages
1. Any way to remove line breaks and timestamps after I merge pages
2. Secondly I added your extension to quick access, it stays grayed out even when I select pages, It becomes active only when I open 1more menu

![image](https://user-images.githubusercontent.com/12750186/91542391-68dede00-e93b-11ea-9d26-d456aab7fd43.png)
![image](https://user-images.githubusercontent.com/12750186/91542411-72684600-e93b-11ea-9158-8211d922a7b8.png)
![image](https://user-images.githubusercontent.com/12750186/91542495-9592f580-e93b-11ea-9380-e5d06830bea4.png)
![image](https://user-images.githubusercontent.com/12750186/91542586-b4918780-e93b-11ea-8381-d133a20cb51d.png)
![image](https://user-images.githubusercontent.com/12750186/91542887-f02c5180-e93b-11ea-87be-02afeb204db2.png)

**Comment by stevencohn** [comment]
line breaks and timestamps - No, not going to add those features
quick access - I have no control over quick access
anchor ink - I have no idea how gem does that and OneMore is not trying to be gem

**Comment by stevencohn** [comment]
Too many different features mention in this ticket. If you want, submit a feature request for:
1. tagging - please explain a bit of the features you think OneNote is missing (more than just "look at evernote!")
2. anchor ink... I'm not sure if this is doable but I'll take a look

**Comment by stevencohn** [comment]
Note that Save as HTML is now implemented. Will be available in after v2.9

**Comment by piyush1908** [comment]
👍

**Comment by piyush1908** [comment]
Can you provide customisable onemore, I mean I only needmerge page, search
n replace most of the time

Secondly can u make floating pen bar

**Comment by stevencohn** [comment]
Only need merge page? Can you explain?

Search and replace most of the time? Do you mean a more interactive experience where it jumps from one instance to the next and you can choose to replace or skip? 

Floating pen bar? Don't think so, there are no APIs to control which pen is currently active.

**Comment by piyush1908** [comment]
Allow us to choose which fuctions to run, In one more I use merge page for
like 90% times and search and replace 5% I don't need rest or would need
them sometimes not always

**Comment by stevencohn** [comment]
You can customize the ribbon bar yourself, add a new group with just those two buttons

**Comment by piyush1908** [comment]
I didn't want entire onemore to load, only selected features

**Comment by stevencohn** [comment]
It's all very lightweight anyway, won't save you much

**Comment by piyush1908** [comment]
Thankyou for allowing to be exported as html

Please can you allow entire section as one html like is avialble for mht
format and can there be an option of exporting to very long single page pdf
