### ISSUE TITLE
Just installed the latest release -no errors but ...it is gone from the ribbon

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#325]
Hi Steven
Just installed the latest release (4.10) -no errors but ...it is gone from the ribbon
any idea where I can look for a log or anything ?

thanks
1k1

**Comment by 1001QAdotNET** [comment]
Well not sure about that, I just installed the latest version and it is gone again
I have tried all the permutations of x64, x86 and install for me only or for the entire system 
the OneMore.log is not being generated
The %AppData%/OneMore was renamed but it is not being created 
the addon shows as available but not trusted (unchecked)



Am I having a low caffeine morning again ?

**Comment by 1001QAdotNET** [comment]
Protocol Handler log

`
Register... version 4.10.1
running as user NT AUTHORITY\SYSTEM (S-1-5-18) elevated
step 0: opening HKLM:\Software\Classes\onemore
step 1: setting properties of HKLM:\Software\Classes\onemore
step 2: opening HKLM:\Software\Classes\onemore\shell\open\command
step 3: setting properties of HKLM:\Software\Classes\onemore\shell\open\command
verified: key created HKEY_LOCAL_MACHINE\Software\Classes\onemore\shell\open\command
translating user THEBRAIN\cristi to SID
registering trusted protocol for user THEBRAIN\cristi (S-1-5-21-2324714714-4207804683-2689708552-1001)
defaulting Office version to 16
step 4: opening HKCU:\Software\Policies\Microsoft\Office\16.0\Common\Security\Trusted Protocols\All Applications\onemore:
key already exists
completed successfully

Unregister... version 4.10.1
step 0: deleting HKLM:\Software\Classes\onemore
key deleted
translating user THEBRAIN\cristi to SID
unregistering trusted protocol for user THEBRAIN\cristi (S-1-5-21-2324714714-4207804683-2689708552-1001)
defaulting Office version to 16
step 1: deleting HKCU:\Software\Policies\Microsoft\Office\16.0\Common\Security\Trusted Protocols\All Applications\onemore:
warning deleting trusted protocol
System.UnauthorizedAccessException
Message: Cannot write to the registry key.
Source: mscorlib
StackTrace:    at System.ThrowHelper.ThrowUnauthorizedAccessException(ExceptionResource resource)
   at Microsoft.Win32.RegistryKey.EnsureWriteable()
   at Microsoft.Win32.RegistryKey.DeleteSubKey(String subkey, Boolean throwOnMissingSubKey)
   at OneMoreProtocolHandler.Program.UnregisterTrustedProtocol()
TargetSite: [mscorlib] System.ThrowHelper::ThrowUnauthorizedAccessException()

completed with warnings

Register... version 4.10.1
running as user NT AUTHORITY\SYSTEM (S-1-5-18) elevated
step 0: opening HKLM:\Software\Classes\onemore
step 1: creating HKLM:\Software\Classes\onemore
step 2: setting properties of HKLM:\Software\Classes\onemore
step 3: opening HKLM:\Software\Classes\onemore\shell\open\command
step 4: creating HKLM:\Software\Classes\onemore\shell\open\command
step 5: setting properties of HKLM:\Software\Classes\onemore\shell\open\command
verified: key created HKEY_LOCAL_MACHINE\Software\Classes\onemore\shell\open\command
translating user THEBRAIN\cristi to SID
registering trusted protocol for user THEBRAIN\cristi (S-1-5-21-2324714714-4207804683-2689708552-1001)
defaulting Office version to 16
step 6: opening HKCU:\Software\Policies\Microsoft\Office\16.0\Common\Security\Trusted Protocols\All Applications\onemore:
key already exists`

The OneMore.log is not being created

**Comment by stevencohn** [comment]
Honestly I totally agree 100% But it's impossible for me to improve it without being able to reproduce these errors and even with six different machines and combinations of Win10/Win11 and versions of Office, I just can't make it break like this. This is the biggest challenge.

**Comment by stevencohn** [comment]
I'm curious, do you always manually uninstall, download, reinstall? Do you let OneMore upgrade itself from the About box?
