### ISSUE TITLE
LaTeX support

### ISSUE THREAD

**Issue by Svk1190** [stevencohn/OneMore#328]
Firstly, thanks a lot for this excellent tool. 

Is it possible to use LaTeX commands to insert equations? For example:

- \llbracket is a LaTeX command for ⟦ symbol, 
- \rrbracket is a LaTeX command for ⟧ symbol,
- \frac{3}{4} is a LaTeX command for ¾ symbol. 

We can select a block of text, and click on the OneMore LateX button, and then OneMore can check the selected text and replace all LaTeX code with the corresponding symbols. 

Lastly, it would be useful if we can define some personal LaTeX commands, for example
\newcommand{\braopket}[3]{\langle #<span/>1 | #<span/>2 | #<span/>3\rangle}
such that when we write \braopket{a}{b}{c} and click on the OneMore LaTeX button, 
it should replace the LaTeX code with ⟨a|b|c⟩. 

Have a great day!

**Comment by stevencohn** [comment]
There is some limited support for LaTeX in OneNote as described here https://docs.microsoft.com/en-us/archive/blogs/murrays/latex-math-in-office

**Comment by Svk1190** [comment]
Thanks! This is a great link. 

The Maths Autocorrect functionality is helpful for new math symbols.  

The custom LaTeX command is something that would probably not be achievable without macros, because the command doesn't map to a variable, but rather the variable is enclosed within some other symbols. 

It would be great if we can define our own commands. It can be helpful not only for LaTeX, but also for Markdown.
