### ISSUE TITLE
Bug feedback, many functions of onemore are invalid

### ISSUE THREAD

**Issue by zhongguocn** [stevencohn/OneMore#329]
**Describe the bug**
some plug-in reference page functions are invalid. Occasionally it succeeds, and running the command again is invalid.

**To Reproduce**
1. Go to '参考文献'》“嵌入页面”、“更新嵌入页面”、“将引用映射到此页面”、“刷新页面参考”等等
2. See error
some plug-in reference page functions are invalid. Occasionally it succeeds, and running the command again is invalid.

**Expected behavior**
many plug-ins reference page functions are invalid.

**Screenshots**

**Environment (if applicable):**
 - OneNote Version:  win10, win11, 64 bit, office 2021 x64, office 365 x64
 - OneMore Version：4.10.1 x64

**Additional context**

14876:1] Starting dllhost 14876, CPU=2701Mhz, zh-CN/zh-CN, v3.19.4, OneNote 15.0, Office 16.0
14876:1] ..OnConnection(ConnectionMode:ext_cm_Startup,1)
14876:1] ..OneAddInsUpdate(custom[]:0)
14876:1] ..OneAddInsUpdate(custom[]:0)
14876:3] ..building ribbon
14876:3] ..building ribbon colorizer commands
14876:3] ..RibbonLoaded()
14876:3] ..OnStartupComplete(custom[]:0)

**Comment by stevencohn** [comment]
I think it may be different cases per function, not a common problem.
I have found a problem with the Embed Page and Update Embedded Page commands that I can fix. I'm not sure if this is the same problem you've seen.

If you have a chance, when a command fails, copy and paste the bottom of the log file; it should have some error information there. Thanks

**Comment by zhongguocn** [comment]
Thank you for your reply. Thank you for developing a plug-in tool like onemore.

Because I use the Chinese version, I don't know the corresponding English version.
I found a bug in 3 commands：
1.References》embedded page
2.References》Map references to this page

The command can be used once or twice when OneNote is first started. The third time you use it, the command is invalid and you don't see a prompt.After you exit OneNote, reopen it, and these commands can be used once or twice. Then they can't be used anymore and click without any results.

3.Reminders
If you manually delete the text on the OneNote page after you create a reminder using onemore, the reminder will always be saved in onemore and cannot be deleted or completed.


In addition, some command words in the Chinese version are translated incorrectly. I can help if necessary。

======================================
14876:1] Starting dllhost 14876, CPU=2701Mhz, zh-CN/zh-CN, v3.19.4, OneNote 15.0, Office 16.0
14876:1] ..OnConnection(ConnectionMode:ext_cm_Startup,1)
14876:1] ..OneAddInsUpdate(custom[]:0)
14876:1] ..OneAddInsUpdate(custom[]:0)
14876:3] ..building ribbon
14876:3] ..building ribbon colorizer commands
14876:3] ..RibbonLoaded()
14876:3] ..OnStartupComplete(custom[]:0)

**Comment by stevencohn** [comment]
I would appreciate help correcting the translations. I only use Google Translate but I do have a way of overriding that easily. Please at your convenience, send a list of English strings and their proper Chinese translations. Thank you!

**Comment by zhongguocn** [comment]
The OneMore plug-in is very useful. I like it very much.Thank you！ It's my pleasure to help.

I need you to provide the English name of each menu command so that I can translate it into Chinese.
It would be better if you could provide the installation file in English without Chinese language pack.

My e-mail:   kv9100@outlook.com

**Comment by zhongguocn** [comment]
The OneMore plug-in is very useful. I like it very much.Thank you！ It's my pleasure to help.

I need you to provide the English name of each menu command so that I can translate it into Chinese.
It would be better if you could provide the installation file in English without Chinese language pack.

My e-mail:   kv9100@outlook.com
