### ISSUE TITLE
Add a "Check for updates option and download if a new release is available"

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#33]
Any chance you could add a "Check for updates  and download if a new release is available" option?

**Comment by stevencohn** [comment]
Yes. There is a chance ;-)

**Comment by 1001QAdotNET** [comment]
I feel like I won the lottery

**Comment by stevencohn** [comment]
Implemented and checked in. It will be in the next release.

**Comment by 1001QAdotNET** [comment]
I won the lottery 

Should I take a ticket for the feature request for indenting paragraphs that do not contain a certain character mark ? That should not be that complicated :-) 
You have to admit that the use case scenario I explained you makes total sense and saves a lot of work

thank you

**Comment by stevencohn** [comment]
No don't worry about a ticket. It does make sense although I suspect there may not be many others that want exactly the same functionality. And it's surprisingly more difficult than you might guess.

Regardless, I have a plan for implementing it. Stay tuned.

**Comment by 1001QAdotNET** [comment]
Thanks a lot
I have tried to implement this using their REST APIs but you can't handle the indentation in these
I was able to change the format for my headings using REST API and beautifoulsoup and css styles ...
All I was doing was to traverse the paragraphs and to search for the marker ...then I knew that I have to change the style for that div containing the marker. 
What is the challenging part , the indenting ?

**Comment by stevencohn** [comment]
This plugin is for the desktop version, not the internet version. It works directly against the OneNote XML schema which guarantees offline use.

**Comment by 1001QAdotNET** [comment]
yeah probably working with XML could be more complicated

**Comment by stevencohn** [comment]
Check for Updates and Indentation now available in release 2.9
