### ISSUE TITLE
Bulk "add tagg" works -there is no bulk "remove tag"

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#332]
Maybe I am  missing something here but it is possible to bulk add tag (and reminders) but the reverse is not possible.
Is that something that you would consider adding ?

**Comment by stevencohn** [comment]
Please clarify.

Regarding tags, are you talking about OneMore page tags? You can add or remove multiple tags using the dialogs.

Regarding reminders, you can only add and remove one reminder at a time. Bulk operations exist neither for add nor remove.

**Comment by 1001QAdotNET** [comment]
re tags:  no, I am talking about onenote tags 

re bulk reminders -understood although I think it could be achieved (I have short to do items listed, no longer than lets say 64 characters and those could automatically become titles for the reminders. 
If more longer lines are selected at he same time then the first 64 characters should be taken to create a reminder for each <one> element (don't remember exact the XML tags used for a line)

**Comment by stevencohn** [comment]
OK bulk removing onenote tags would be an entirely new OneMore _Clean_ feature. It would be easy to do.

When you create a reminder, it automatically takes the first 40 characters from the paragraph and uses that for the reminder subject. Could add a feature to auto-gen reminders from all tags on a page but I think this would be rarely used by most folks and I'd classify it as pretty low priority

**Comment by 1001QAdotNET** [comment]
ok you know the priorities better...it if is possible it would be great ...if not not a big deal
