### ISSUE TITLE
Is it possible that the Reminder summary report page automatically creates could have a date attached to the tile?

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#333]
It is either that or simply overwrite the page there is no point in having the page with the same title created over  and over again every day

**Comment by stevencohn** [comment]
Are you running 4.10.1? This version attempts to find an existing report and, if one exists, asks if you want to reuse that page or create a new one. If you want to reuse the page then having automatically annotated the title with a date may not make sense - in fact would be redundant to the date stamp on the page just beneath the title.

So I considered it but purposefully did _not_ include a date in the title.

**Comment by 1001QAdotNET** [comment]
no I am on 4.10 ..let me update to that one and look at it again, thank you for the tip

**Comment by 1001QAdotNET** [comment]
Here we go again, not the best thing that it could happen at 9-10AM when you start your day
https://github.com/stevencohn/OneMore/issues/325#issuecomment-957638045
