### ISSUE TITLE
When generating the summary report is it possible to add grouping and filtering options?

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#334]
Sorting is already there. I think the best way to achieve this would be to add  filtering capabilities to OneNote tables but I think that is not possible.  

It could probably be done as an option when the user presses the Reminder summary report button or when the report is generated maybe an Excel spreadsheet could be used instead of the native table object

**Comment by stevencohn** [comment]
Possible.... but I did change the sort order in 4.10.1 to a more reasonable sort. It first sorts by year, then week of year, and then priority within that week. In other words, it sorts by planned due date and groups by week of year. This seems the most generic approach. Beyond that, you can use OneNote's built-in sort-by-table-column feature to sort by priority, for example.

I chose not to use Excel to fully support those who may not have Excel installed.
