### ISSUE TITLE
OneMore ribbon commands are not displayed

### ISSUE THREAD

**Issue by gpbicego** [stevencohn/OneMore#336]
**Describe the bug**
OneMore ribbon commands are not displayed with settings attached.

**To Reproduce**
Use the attached "Settings.xml": [Settings.zip](https://github.com/stevencohn/OneMore/files/7466702/Settings.zip)

**Environment (if applicable):**
*OneMore.log*:
7968:1] Starting dllhost 7968, CPU=2592Mhz, it-IT/en-US, v4.10, OneNote 15.0, Office 16.0
7968:1] ..OnConnection(ConnectionMode:ext_cm_Startup,1)
7968:1] ..OneAddInsUpdate(custom[]:0)
7968:1] ..building ribbon
7968:1] ..building ribbon colorizer commands
7968:1] ..building language proofing commands
7968:1] ..building context menu
7968:1] ..OnStartupComplete(custom[]:0)
7968:1] ..OneNote backup folder:: E:\BK\OneNote\16.0\Backup
7968:1] ..OneNote default folder: D:\Users\gbice\Documents\OneNote Notebooks
7968:1] ..OneNote unfiled folder: D:\Users\gbice\Documents\Blocchi appunti di OneNote\Blocco appunti\Note rapide.one
7968:1] ..OneNote process module: C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.14527.20234)
7968:1] ..defining hotkeys for input locale 1040
7968:1] ..ready

*OneMoreProtocolHandler.log*:
error writing 'onemore://ReportRemindersCommand/refresh'
System.TimeoutException
Message: The operation has timed out.
Source: System.Core
StackTrace:    at System.IO.Pipes.NamedPipeClientStream.Connect(Int32 timeout)
   at OneMoreProtocolHandler.Program.SendCommand(String arg)
TargetSite: [System.Core] System.IO.Pipes.NamedPipeClientStream::Connect()

**Comment by stevencohn** [comment]
Was this immediately after an upgrade or did it just show up out of the blue?

**Comment by gpbicego** [comment]
It happens after changing "Context menu options":
![image](https://user-images.githubusercontent.com/22318088/140082491-0d405803-892b-4aa8-94c5-d08bac4b584e.png)

**Comment by stevencohn** [comment]
Needs a fix. I'll get right on it.

Meanwhile, you can edit your Settings.xml file by removing either ribProofingMenu or ribEditMenu from the ContextMenuSheet element. They are conflicting with each other. 

Similar to the Edit/Colorize menu, if you choose a menu and its submenu, it should place the submenu as a top-level context menu item and remove it from its parent menu in the context menu (that's a lot of "menus", I hope you followed it)
