### ISSUE TITLE
Error running command ReportRemindersCommand

### ISSUE THREAD

**Issue by gpbicego** [stevencohn/OneMore#337]
**Describe the bug**
System.IndexOutOfRangeException
Message: Index was outside the bounds of the array.
Source: River.OneMoreAddIn
StackTrace:    at River.OneMoreAddIn.Commands.ReportRemindersCommand.ReportInactiveTasks()
   at River.OneMoreAddIn.Commands.ReportRemindersCommand.<Execute>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.CommandFactory.<Run>d__6.MoveNext()
TargetSite: [River.OneMoreAddIn] River.OneMoreAddIn.Commands.ReportRemindersCommand::ReportInactiveTasks()

![image](https://user-images.githubusercontent.com/22318088/140061436-6fe7a512-d587-4de9-b050-fb45fea994fd.png)

**Comment by stevencohn** [comment]
Any idea how you got there? How many reminders did you create? Did you delete any? Did you delete any paragraph containing reminders without deleting the reminders? (You shouldn't need to worry about that but just asking.)

Any information you can provide that may help me reproduce the problem would be greatly appreciated

**Comment by gpbicego** [comment]
Sorry, it was a problem with my build (Enviroment.NewLine is default CRLF in my Visual Studio):
Resources.resx uses LF as a newline, so Split() doesn't work correctly for me:
`	statuses = Resx.RemindDialog_statusBox_Text
					.Split(new string[] { Environment.NewLine }, StringSplitOptions.RemoveEmptyEntries)`

**Comment by stevencohn** [comment]
So is there still a problem I need to address?

**Comment by gpbicego** [comment]
Is it possible to use:
`new string[] { "\r\n", "\r", "\n" }`
instead of:
`new string[] { Environment.NewLine }`
to split strings, so I don't have to change my Visual Studio settings if I want to build the project?
Thanks

**Comment by stevencohn** [comment]
I can. But I'm curious as to why your settings are different. What culture is your environment set to?

**Comment by gpbicego** [comment]
I'm using Windows default CRLF for newline, but OneMore 'Resources.resx' use LF (Unix style).

**Comment by stevencohn** [comment]
Hm, I'm not seeing that in my source files. They all have CRLF. Not sure what's happening to them on your end!

**Comment by stevencohn** [comment]
But I added the suggested fix regardless

**Comment by gpbicego** [comment]
![image](https://user-images.githubusercontent.com/22318088/140095784-5f03f712-6078-46ca-b300-d8913eb52f26.png)
![image](https://user-images.githubusercontent.com/22318088/140095830-75824bea-e724-453d-9bf3-f79cc8d2a8dd.png)
![image](https://user-images.githubusercontent.com/22318088/140095937-e5df3ca0-c30c-408c-a01d-dd0dce80a813.png)

**Comment by stevencohn** [comment]
Definitely Github's fault! They must be generating those zip files in a linux container.

If you use "git clone" then it downloads the files properly untouched.

**Comment by stevencohn** [comment]
https://stackoverflow.com/questions/17347611/downloading-a-zip-from-github-removes-newlines-from-text-files

Looks like I may be able to override that with a .gitattributes setting

**Comment by stevencohn** [comment]
Yup that appears to have fixed it. Thanks for helping diagnose this.

**Comment by gpbicego** [comment]
Thanks to you for this very useful OneMore
