### ISSUE TITLE
Setting language 

### ISSUE THREAD

**Issue by zhousodo** [stevencohn/OneMore#34]
Can you add a new function to set Chinese and English fonts separately,    thanks

**Comment by stevencohn** [comment]
Yes, this is important. It will automatically switch language based on your Windows setting. Of course, I'll need a translator ;-)

**Comment by zhousodo** [comment]
> 是的，这很重要。它将根据您的Windows设置自动切换语言。当然，我需要翻译器;-)
wow, amazing.  but  the onenote2016  has a big bug for setting language   ,  english it always to be setted carlibr  auto , it is very confused me. when i writting using chinese and english . i find a lot of people have the questions ,  can you get it or  writting a add-in . thanks very much .
https://answers.microsoft.com/zh-hans/msoffice/forum/all/onenote%E9%BB%98%E8%AE%A4%E5%AD%97%E4%BD%93/4c1aceb0-6f12-40ce-8fcd-db615c2a7e7a

**Comment by stevencohn** [comment]
Most of the work is complete with release 2.9 but I don't have any translations yet

**Comment by stevencohn** [comment]
I added Chinese translation using Google's Translator. I hope they're all correct!
