### ISSUE TITLE
Create Page Map - not working?

### ISSUE THREAD

**Issue by javathehunt** [stevencohn/OneMore#341]
New to using Onemore and when using References / Create Page Map it seems to only work under two of the three options; # 2 & 3. 

So if I choose 1) All notebooks and hit OK it runs for a few seconds indicates processing 1465 page references then it stops with no pages generated. If I hit either 2) All sections in the current notebook & 3) The current section it runs and does generate what appears to be the appropriate content. But when choosing #2 or #3 and also selecting the box "Include cross notebook reference - it does the same as checking #1 it runs for a few second shows processing then produces zero result. Any idea why? Am I doing it wrong?

Using the other linking features ; Bidirectional Linking and Link References to this Page they both work fine.

The linking that I have between pages / section / notebooks are all a combination of links generates using the Onemore Bidirectional Linking feature as well as links generated thru [[page name]] where I might create the page adjacent then move it elsewhere. When using the Link References to this Page feature it is able to pull in links to all other notebooks ok.

Using desktop Onenote 2016.
Thanks

**Comment by stevencohn** [comment]
Can you please look for the file %temp%/onemore.log and attach it here?

I don't have notebooks that large. I guess I need to generate some for testing....

**Comment by stevencohn** [comment]
Never mind, I can reproduce the error myself.
