### ISSUE TITLE
Custom Snippet doesn't work with Unicode

### ISSUE THREAD

**Issue by osman1963** [stevencohn/OneMore#346]
First of all, thank you so much for the great efforts

I would like just to report a small bug in the custom snippet. It doesn't work with Arabic, I suppose other RTL languages too.
When highlighting a text then saving it using Favorites--> My Custom Snippets --> Save Custom Snippets.. it saves it. But when inserting it later on it inserts the letter 'v' instead of the snippet.
I'm using OneNote 365 (2016) on Windows 10
Thanks in advance

**Comment by stevencohn** [comment]
I've tested this a few different ways but can't seem to reproduce it. Is your default Windows language set as Arabic too?

**Comment by osman1963** [comment]
No, my default language is English US. Is there a shortcut for inserting
the snippet? if so, may be it works with the shortcut.

**Comment by osman1963** [comment]
Found the cause of the problem and the solution. It has to do with the
font. The default font was Times New Roman. I tried changing it to
Traditional Arabic, which is one of the fonts made first and foremost for
Arabic, and it works just fine.
I was wondering if you could help with the following: I faced a similar
problem with Zim and was solved in this same way (It rendered Heading 3 and
5 as garbled squares). So my question is:
- What aspect of the programming language/ rendering is responsible for
this? I know Zim uses Python and CSS to render the markup text (Doku Wik
markup), but don't know how text is rendered in OneNote. Any clarification
or pointers is highly appreciated, as I'm trying to go back to programming
these days (was a programer some 25 years ago, used C++, Delphi (pascal),
Oracle Database - Java and JavaScript were still infants those days), so I
could really use such info.

Thanks in advance :)

**Comment by stevencohn** [comment]
Good debugging. This will help me come up with a solution. It should have captured the font of the snippet and then just reapplied it when pasting it back in but apparently there's a bug in that logic. So this gives me a good starting point.

OneNote content is described by XML governed by a specific schema. These are all referenced on the [Developer Notes](https://github.com/stevencohn/OneMore/wiki/~-Developer-Notes) page.

OneMore is really nothing more than a C# library that manipulates the XML of the pages and notebook/sectiongroup/section hierarchy.

**Comment by osman1963** [comment]
ٍI don't know what happened, but the same problem came back again, even
after changing the font. I even uninstalled and re-installed OneMore, and
no changes. , I deleted the AppData too before re-installing. Before this,
just after I sent you my last email, I noticed that the new snippets
behaved strangely: when saving it replaces the selection with 'c', and when
inserting it just inserts 'v'., however the old snippets worked fine after
changing the font as I told you. Could this be related also to the new
updates of OneNote and the whole Microsoft 365 family?. It appeared on my
machine just yesterday.

**Comment by stevencohn** [comment]
I don't think so, I'm using Office 2021, which should be the same as the latest 365.

In fact, I'm still having trouble reproducing this. I've set my default font to Time New Roman and saved a snippet that was written in Traditional Arabic. When I add the snippet back in, it works fine regardless of the font/text on which the cursor is positioned.

Can you please open your \AppData\Roaming\OneMore\Snippets folder and attach the .snp file containing the snippet you're trying to insert?

**Comment by osman1963** [comment]
I'm attaching two snippet fils. One in English and one in Arabic. Now, I
noticed that when using Taditonal Arabic for Enligsh or Arabic snippets, it
doesn't work for either, in both cases it removes the selection and replace
it with 'c', and doesn't even open the save dialogue.
When I changed to font to Arial, it worked fine with Engilsh text. However,
with Arabic text it created the snippet, but didn't insert it, it inserts
'v' instead.

**Comment by osman1963** [comment]
I'm attaching part of the log file. Guess it might help figuring out the cause of the problem. 
Also, I'm sure I Installed the x64 version of the OneMore, but it points here to 'IWin32Window'. Is that normal?

16212:10] Running command InsertTocCommand
16212:18] Running command AboutCommand
16212:7] Running command SaveSnippetCommand
16212:1] Error running command SaveSnippetCommand
16212:1] System.ComponentModel.Win32Exception
Message: The handle is invalid
Source: System.Windows.Forms
StackTrace:    at System.Windows.Forms.Control.GetSafeHandle(IWin32Window window)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at River.OneMoreAddIn.Commands.SaveSnippetCommand.<Execute>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.CommandFactory.<Run>d__6.MoveNext()
TargetSite: [System.Windows.Forms] System.Windows.Forms.Control::GetSafeHandle()

**Comment by stevencohn** [comment]
It is normal. The exception is not. So this gives me a little more evidence.

I never did see those two attachments. Did you drag and drop them onto the message?

**Comment by osman1963** [comment]
I sent the snippets by email. 
Anyways here is the content of one

Version:1.0
StartHTML:0000000105
EndHTML:0000000753
StartFragment:0000000616
EndFragment:0000000707

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=ar-EG style='font-family:"Traditional Arabic";font-size:12.0pt'>

<p style='margin:0in;font-family:Arial;font-size:12.0pt;text-align:right'><span
style='direction:rtl;unicode-bidi:embed' lang=ar-EG>اللغة العربية</span></p>

</body>

</html>


**And another one**

Version:1.0
StartHTML:0000000105
EndHTML:0000000684
StartFragment:0000000626
EndFragment:0000000638

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=ar-EG style='font-family:"Traditional Arabic";font-size:12.0pt'>

<p style='margin:0in;font-family:"Traditional Arabic";font-size:12.0pt'
lang=en-US>this is good</p>

</body>

</html>

**Comment by osman1963** [comment]
```
Version:1.0
StartHTML:0000000105
EndHTML:0000000684
StartFragment:0000000626
EndFragment:0000000638

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=ar-EG style='font-family:"Traditional Arabic";font-size:12.0pt'>

<p style='margin:0in;font-family:"Traditional Arabic";font-size:12.0pt'
lang=en-US><!--StartFragment-->this is good<!--EndFragment--></p>

</body>

</html>

```

**Comment by osman1963** [comment]
```
Version:1.0
StartHTML:0000000105
EndHTML:0000000753
StartFragment:0000000616
EndFragment:0000000707

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=ar-EG style='font-family:"Traditional Arabic";font-size:12.0pt'>

<p style='margin:0in;font-family:Arial;font-size:12.0pt;text-align:right'><!--StartFragment--><span
style='direction:rtl;unicode-bidi:embed' lang=ar-EG>اللغة العربية</span><!--EndFragment--></p>

</body>

</html>

```

**Comment by stevencohn** [comment]
What language is your input keyboard set to?

The way the snippet command works is that it reads the .snp file, extracts the HTML fragment, copies that to the Windows clipboard, and then signals Ctrl+V key sequence to paste the clipboard contents onto the page.

I'm wondering if the Ctrl+V key sequence is not getting interpreted correctly.

**Comment by osman1963** [comment]
My keyboard is bilingual. The Ctrl+V key sequence works in both languages
as expected, in all apps, including OneNote
Something stranger happened a while ago.
I created new snippets and tried inserting them, in both languages, they
worked fine.
After a few minutes I tried doing it again, it didn't work. After selecting
a text, and trying to save it, the 'snippet name dialogue opens', but the
text itself disappears and is replaced by 'c' ( part of executing the Ctrl
+ C command ??)
My guess is that there might be something that goes wrong with the
container of the links to the snippets (linked list, array?) as a result of
some call.

**Comment by stevencohn** [comment]
There's a big warning notice on the SendKeys.Send managed API that I guess I never paid any attention to before.

> If your application is intended for international use with a variety of keyboards, the use of Send could yield unpredictable results and should be avoided.

But I think there's an alternative that I can investigate. Give me a few days

**Comment by stevencohn** [comment]
Confirmed. Fix will be in next release.

**Comment by stevencohn** [comment]
As a workaround, temporarily set your keyboard language to English, insert the snippet, then set it back to Arabic

**Comment by osman1963** [comment]
Wow, that's great news :) Thanks
