### ISSUE TITLE
Tags are still found on page after they are removed

### ISSUE THREAD

**Issue by foxxxyfoxxx** [stevencohn/OneMore#348]
**Describe the bug**
After removing a tag from a page through the tag-page it still appears when searching for it on Find-Tagged-pages. 

**To Reproduce**
1. Go to 'Tag-Page'
2. Assign a Tag (e.g. TASK) to a page
3. Click OK
4. Go to 'Find-Tagged-pages'
5. Make a test search 
6. Close 'Find-Tagged-pages'
7. Go to 'Tag-Page'
8. Remove previously created Tag (e.g. TASK) from page
9. Click OK
10. Go to 'Find-Tagged-pages'
11. Search the previously removed Tag

**Expected behavior**
The page with the removed tag should no longer appear in the search on Find-Tagged-pages'

**Screenshots**
<img width="681" alt="Screenshot 2021-11-26 062649" src="https://user-images.githubusercontent.com/49116853/143531430-0c2b5f40-f200-484e-82f9-84d9b7a0676c.png">

**Environment (if applicable):**
 - OneNote Version: O365 64bit
 - OneMore Version 4.11

**Additional context**
NONE

**Comment by stevencohn** [comment]
This is not a bug. OneNote's indexing is a background task that can take seconds, minutes, even longer to scan all your notebooks and update search results. Similarlly, adding a tag or making other changes may not be picked up immediately by the search action. There' nothing OneMore can do to provoke OneNote from updating its cache faster.

**Comment by foxxxyfoxxx** [comment]
Thanks for the info. I will see if clearing the cache can solve the problem. Great work btw.
