### ISSUE TITLE
Import tasks from outlook or microsoft to-do and synch the status

### ISSUE THREAD

**Issue by idoru2k** [stevencohn/OneMore#349]
I plan my tasks with microsoft to-do and outlook. They are automatically synched between them.
I know i can create an outlook task for onenote, but the tasks created otherwise i could't see in onenote.

It would be very helpful to import a list of tasks from outlook to an onenote page and automatically
keep it synched (atleast if it is done or not). The list in onenote should have hyperlinks to the task in outlook and/or to-do.

The selection of the tasks should be manually or by folder in outlook (because lists in to-do are reprensented by folders in outlook) or
by outlook category. 

Thanks for thinking about it.
OneMore is great project!

**Comment by MehsEzeerf** [comment]
This will be amazing!

**Comment by stevencohn** [comment]
This is close to release but there are some caveats.

There is a known issue where OneNote loses its connection to a task if that task is not in the top-level Tasks folder. You can still import it but it's status flag will not get updated automatically. Tasks in the top-level Tasks folder should still work fine.

The new function in OneMore will import tasks from Outlook; in fact, it requires Outlook. It will create either a list or a table of tasks. The list options includes task summaries, similar to what OneNote/Outlook integration does. The table option will include due dates, creation dates, importance, etc, which can be refreshed by clicking a Refresh link; this will show these details for sub-folder tasks as well, again although their status flags won't be "live"

References
- https://techcommunity.microsoft.com/t5/microsoft-to-do/microsoft-todo-outlook-tasks-onenote-doesn-t-work-folders/m-p/386310
- https://answers.microsoft.com/en-us/msoffice/forum/all/onenote-loses-outlook-task-if-task-isnt-in-default/380922a0-8f4a-42c9-93a0-6b0dbcdccd0f?auth=1

**Comment by idoru2k** [comment]
Hi Steven,
thanks for your approach even regarding the caveats. I have to say, that i am no native speaker, so 
please consider this, if i use wrong expressions. Sorry for that. I really appreciate what you are doing.
I think Microsoft will develop To-Do as the new central task manager in 365, so the Outlook Tasks will be replaced
with To-Do. Therefor i think it would be more sustainable to realize the function with the To-Do API.
The built in Outlook-Task Integration is as you pointed out limited. If the function could import tasks from To-Do (e.g. a certain list in To-Do = a subfolder in outlook) and it has a refresh button or perhaps would refresh autmatically on loading the page or the notebook would be great.
I am looking forward to test the new function.

Thanks Alex

**Comment by stevencohn** [comment]
OneNote cannot bind to tasks without Outlook. It does not yet have any ability to bind to To-Do items without the Outlook interop API

**Comment by G2G2G** [comment]
First, thank you for a great add-in and this new functionality.

I ran into an issue where if I import a task from Outlook and then modify it in Onenote and accidentally break the link, I can no longer select it even if I delete the task from Onenote. 

Can there be a way to manually break the link so that a new one could be created ?

**Comment by stevencohn** [comment]
Yes, I realized this might be a problem and probably need to create a link to repair orphaned tasks.

Until then, the easiest solution may be to view the old version of your page that contains the linked text and copy/paste it into the new version; or revert the page to that old version. Of course, this presumes you have page versioning enabled in OneNote.

**Comment by stevencohn** [comment]
The next release will include a hyperlink on the Import Outlook Tasks dialog that lets you reset any Outlook tasks that were orphaned by deleting the reference paragraph from OneNote
