### ISSUE TITLE
Does this work for OneNote 2013?

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#35]
Hi Steven

Yesterday I stayed up till 4AM due to the incompentents at Microsoft who pushed an update for my Office 2013 which made the license unusable.  The new installer gets in conflict with OneNote 2016 and you can't have OneNote 2016 and Office 2013 on the same computer anymore. This is what I learned by solving the problems myself after 6-7h  calls and allowing 4 incompetent technical support ppl at M$ to touch my computer. 

So now I am stuck with Office 2013 and OneNote 2013 and I noticed that OneMore is not there anymore. 
Does OneMore x86 work with OneNote2013 x86?

thank you

**Comment by stevencohn** [comment]
I haven't tried but I think I can start up a VM and give it a go. I'll let you know what I find. May take a few days, I do have a day job!

**Comment by 1001QAdotNET** [comment]
So do I ...I wish I could make M$ pay for what they did to me

**Comment by stevencohn** [comment]
Well I had 15 minutes so... I set up a new VM Windows 10 64-bit, with OneNote 2013 32-bit. Activated OneNote and closed. Installed OneMore 2.7. Ran OneNote and the OneMore menu appears.

I know that's not what you want to hear :-( 

First, did you uninstall OneMore and try to reinstall it after the MS fiasco?

Second, maybe it did register but just isn't enabled. In OneNote, go to File, Options, Add-ins. First confirm that OneMoreAddIn is listed. If it is then choose Disabled items in the Manage drop down at the bottom and click Go... Then enable the add-in. If it isn't showing up, then, umm, I'm not sure

**Comment by 1001QAdotNET** [comment]
Hmm I have the same issue with both, OneNote 2010 and 2013
This is what I am seeing
https://i.imgur.com/mzmuKa0.png

**Comment by stevencohn** [comment]
32bit or 64bit OneNote?

**Comment by 1001QAdotNET** [comment]
32bit

**Comment by 1001QAdotNET** [comment]
Quick update: this morning I reinstalled a demo copy of Onetastic
Apparently that did something and now I am seeing OneMore there
Not seeing the check for updates button though

**Comment by stevencohn** [comment]
That's good! 
Check for Updates is on the About dialog. It was added in v2.9

**Comment by 1001QAdotNET** [comment]
you are right I was still on 2.9.
Not sure if the initial bug that I noticed when I opened this issue is still there with 2.9
