### ISSUE TITLE
(Footnote) Reference Commands

### ISSUE THREAD

**Issue by qamah** [stevencohn/OneMore#354]
Hey man, first of all ,thanks for your outstanding effort to do this.
      I want to ask you all ,have you ever met this problem? When using the Reference Commands,I insert new footnotes **one by one**, but it shows **[1][2][2][2][2][2]**,and in the reference section ,the order of the number is also mixed.I have tried to change my Cinese words,English words, change the fonts(times new roma,calibri), re-install the plugin,but it all doesn’t work,either.

![Picture_2021-12-02-14-58-36](https://user-images.githubusercontent.com/80671885/144373738-06ea061b-37c0-43ec-a947-bb0f0e7f1a5c.png)

![Picture_2021-12-02-14-58-09](https://user-images.githubusercontent.com/80671885/144373853-35f97b10-886c-4f0c-8fdc-b99c9b8d271a.png)
Hoping your reply

**Comment by stevencohn** [comment]
I have not see this. What happens if you click the Refresh link at the top of the footnote section?

**Comment by qamah** [comment]
By the way ,   It both changes nothing, after I click the Refresh link at the top of the footnote section and the Refresh link in the Reference Commands .
