### ISSUE TITLE
Circular Linked References

### ISSUE THREAD

**Issue by javathehunt** [stevencohn/OneMore#355]
When using the - Link Reference to this Page - feature it pulls from not just free-standing text but also the reference links on other pages. 

The Link Reference to this Page feature will create a link to any other pages 1) where the current page title shows up in the text of that page and 2) where the current page title shows up as a link on that other page;  effectively creating circular references. So If A includes text B and a references is run on page B a link to A will show up in B since text B is on A. If a reference is run on page A then a link to B will show up since A appears in B as a link that was created in the previous reference link.

Maybe when creating these link references an option can be shown to exclude other reference links from the search result.

Edited for clarity.

**Comment by stevencohn** [comment]
Will investigate

**Comment by stevencohn** [comment]
I took a look and didn't see any problems. It is working as designed.

It's supposed to generate circular references between the current page and all other pages that reference it. If you then go to one of those pages and the original page also references this new page by title and you run the command there, yes, it will do the same thing from the new page's perspective.

**Comment by javathehunt** [comment]
I guess the circular reference can be considered a form of outgoing or forward link. I have not used it enough yet to appreciate that part I saw it as unnecessary clutter but I guess there can be value to it. Thanks.

**Comment by stevencohn** [comment]
For further information, please see the Wiki (although most is covered in this thread already :-/ )

Thanks for using OneMore!
