### ISSUE TITLE
Add context to Linked References

### ISSUE THREAD

**Issue by MehsEzeerf** [stevencohn/OneMore#356]
When using linked references it currently makes a list of locations where the page is mentioned.  However, to find the page that is most relevant in the moment it requires navigating to each page individually.  Would it be possible to have the content around the mention pulled to the Linked References section. 

Example of desired future state
![image](https://user-images.githubusercontent.com/66741217/145428160-595130c1-794d-4b08-9074-003fa04f5ba6.png)

When pulling in the OPA data Linked Reference if the content of the container that as the reference could be added to the linked references section that would be great.

Like this
![image](https://user-images.githubusercontent.com/66741217/145428430-e6aabfb3-2fb1-412e-a6ff-13d1e0a0f7ea.png)

**Comment by stevencohn** [comment]
It is possible if there is textual content on the page. Will investigate

**Comment by MehsEzeerf** [comment]
Nice!
