### ISSUE TITLE
map references  command be used only once,It still happens in the new version V4.11

### ISSUE THREAD

**Issue by zhongguocn** [stevencohn/OneMore#358]
When the mapping page changes, the "Refresh" command of the page reference list can only be used once. clicking again will not work.

There is nothing added in the log file.It's like I didn't click the refresh command.

**Comment by stevencohn** [comment]
I haven't been able to reproduce this.

**Comment by zhongguocn** [comment]
1．Copy the link of page A and paste it to page B.

2．Use the command to insert a page reference into page A.

3．In page A，the link of page B will appear in the page reference list.

4．Copy the link of page A and paste it to page C.

5．In page A，Click the "Refresh" command above the page reference, the page reference list will not be updated, and the link of page C will not appear.

6．Close OneNote and restart. In page A，Click the "Refresh" command above the page reference, the page reference list will be updated, and the link of page C will appear.

7．Copy the link of page A and paste it to page D.

8．In page A，Click the "Refresh" command above the page reference, the page reference list will not be updated, and the link of page D will not appear.

9．Generally speaking, When the mapping page changes, the "Refresh" command of the page reference list can only be used once. clicking again will not work.

**Comment by zhongguocn** [comment]
It's my pleasure to help you. 

It's my pleasure to help you. I should thank you for developing such a useful plug-in.
