### ISSUE TITLE
Keyboard shortcuts for custom styles

### ISSUE THREAD

**Issue by stevencohn** [stevencohn/OneMore#36]
Add keyboard shortcuts for the custom styles. This could be difficult without adding an entirely new bit of UI that allows users to press key sequences and record those; it's not as simple as saying H1 will always be this key sequence because the custom style names are, well, custom.

**Comment by stevencohn** [comment]
So I decided to simply implement it as CtrlAltShift+1..9 where 1 applies to the first custom style, 2 applies to the second, and so on.
Will be available in next release.

**Comment by osman1963** [comment]
It is a great ide and very practical. I just downloaded your awsome add-in yesterday, and it literally made my day. Thank for the great work man.
I check this feature but it is not working. Is there smoething I'm missing?

**Comment by stevencohn** [comment]
Sorry it's not release yet... soon!

**Comment by stevencohn** [comment]
The code is checked in, you think you can download and compile it yourself. Otherwise, I upload a new release in the next couple of days.

**Comment by stevencohn** [comment]
OK OK, just for you: https://github.com/stevencohn/OneMore/releases/tag/2.17.1
