### ISSUE TITLE
WebView2 Runtime installation - just check availability

### ISSUE THREAD

**Issue by berlihingen** [stevencohn/OneMore#360]
**Is your feature request related to a problem? Please describe.**
Downloading and installing took over 2 minutes while installed the same version that was here before. Edge itself updates WV2 significantly quicker. 

**Describe the solution you'd like**
Maybe skip this step for Windows 10/11 where this runtime is pretty much inevitable as much as Edge?

**Describe alternatives you've considered**
 I have a few apps that use WV2, but they obviously just check for availability/version.

**Comment by stevencohn** [comment]
Thanks for this. Confirmed it works. Will be in next release.

**Comment by berlihingen** [comment]
Great. And huge thanks for OneMore.
