### ISSUE TITLE
Export without underscores?

### ISSUE THREAD

**Issue by john-catalano** [stevencohn/OneMore#366]
Is there config file I can tweak so that exports do not substitute underscores for spaces in the file names?

As it is, a page named...
Templates - Email templates in Outlook

will Export as...
Templates_-_Email_templates_in_Outlook

I just want it exported as...
Templates - Email templates in Outlook

**Comment by stevencohn** [comment]
I'll make it an option in the Export dialog, frankly because I don't remember why I did it in the first place - but it must have been important!
