### ISSUE TITLE
set the font for Chinese and English separately

### ISSUE THREAD

**Issue by elfmedy** [stevencohn/OneMore#367]
Here is a link to this question

https://answers.microsoft.com/en-us/msoffice/forum/all/default-font-of-chinese-and-english/e15de7fe-0a90-4837-a6e7-83456343cd84

**Comment by stevencohn** [comment]
Hi,

I sincerely wish I could help you. I'm not a Microsoft employee and have no influence on the internals of OneNote or how they work. I only have access to the add-on API that Microsoft publishes and am constrained by its limited functionality.

Best Regards,
Steven
