### ISSUE TITLE
Clicking reminder alert - "You'll need a new app to open this onemore link"

### ISSUE THREAD

**Issue by john-catalano** [stevencohn/OneMore#369]
When I click the Windows notification that is generated by the OneMore reminder feature, I receive a cryptic pop-up notice:

"You'll need a new app to open this onemore link"
(https://imgur.com/a/nu6GIcB)

I assume that, when I click the Windows notification, that OneNote will open to the reminder. But, OneNote doesn't even open/come to focus when the pop-up disappears.

**Comment by stevencohn** [comment]
Sounds like it didn't install successfully or completely. Try to either reinstall OneMore or register the app that is supposed to handle onemore:// links by doing this:

1. Open an administrative PowerShell window (run as administrator)
2. Enter the command:

   `. 'C:\Program Files\River\OneMoreAddIn\OneMoreSetupActions.exe' --install`

**Comment by stevencohn** [comment]
Closing this ticket. Related work will be done under #438 which likely solves this as well.
