### ISSUE TITLE
Improved Copy and Paste into OneNote

### ISSUE THREAD

**Issue by MehsEzeerf** [stevencohn/OneMore#370]
**Is your feature request related to a problem? Please describe.**
When I import text from a PDF document it holds the word count per line rather then a fluid line of text which adjusts with the size/shape of the container the text is held in.

**Describe the solution you'd like**
I would like to be able to highlight the text and select a function similer to the way that the remove whitespace function works.

**Describe alternatives you've considered**
Manually removing the line breaks.

**Additional context**
On the right of the screen shot is the text I copied from a pdf.  The top lines of text on the left is how it copies in to onenote natively.  The text at the bottom represents how I would like the text to look.
![image](https://user-images.githubusercontent.com/66741217/148255774-ab562131-5372-4878-9ef9-ca9124592455.png)

**Comment by stevencohn** [comment]
I think you're talking about the OneMore Edit / Join Paragraph command. 

1. Paste the text into OneNote
2. Select the text
3. From the OneMore Edit menu, click Join Paragraph

OneMore should remove the line breaks and format the text into a single running paragraph.

**Comment by stevencohn** [comment]
closing this for now
