### ISSUE TITLE
Purpose of WebView2?

### ISSUE THREAD

**Issue by MehsEzeerf** [stevencohn/OneMore#371]
**How can I help you?**
I am getting OneMore added to my corporate software store and they are wanting to understand the purprose of the webview2 component.  Looks like this is for page embed's?   The asked me if there is a source of more information but wasn't finding anything when I looked over the GitHub.  Very likely I just missed it.

**Comment by stevencohn** [comment]
First of all, wow! Thanks for pushing it to corporate. I'm honored and humbled that you think OneMore is that useful.

Second, webview2 is only employed currently in one use case, which is to work as a headless browser when running the Import Web Page command. The browser loads the page and saves it as HTML where OneMore picks it up and imports it. I am thinking of other ways of using it such as how to visualize customer user-defined snippets. Regardless, it is all open source and readily available for review here in Github.

Note that webview2 is the engine behind Microsoft Edge and in fact is pre-installed on Windows 11. So installing OneMore on Windows 11 will skip the webview2 installation step.

**Comment by MehsEzeerf** [comment]
This great super helpful. I already have several people that have installed
it. The way it works is that you become the software “owner” at my
organization if you request it be added.

I will be testing the latest version for packaged install tomorrow.  I
truly deeply appreciate your work on the amazing tool.
