### ISSUE TITLE
Search and Replace does not appear to work on $ symbol

### ISSUE THREAD

**Issue by varnk** [stevencohn/OneMore#372]
Tried Search and Replace on my OneNote page and it doesn't appear to find $ symbol.  Tried to search for $ and replace with @.  It could not find $ even though it was on the page in several places.  Regular Expressions option was not selected.

**Comment by stevencohn** [comment]
Thanks for this.

As a workaround you can enable regular expression and search for \$

**Comment by stevencohn** [comment]
It's a quick fix that will be available in the next release.
