### ISSUE TITLE
One More calendar -add the option to filter out the empty days when in list mode

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#374]
In oneMOre Calendar, when I am in list mode I would like to be able to filter out the days when nothing was created
Also it could be useful to be able to export the results in CSV or Excel format

**Comment by stevencohn** [comment]
I can always count on you to come up with new feature suggestions! ;-)

I'll consider them. Regarding hiding empty days, I considered that but it seemed harder to "see" the month, if that's important to people. So we'll see...

As for exporting, how do you think this would be useful?

**Comment by 1001QAdotNET** [comment]
Good suggestions come from working a lot with OneNote
I am resuming my learning activities so you will probably continue to see a lot of these and maybe, finally some contributions for the scripts we discussed. 

Re: exporting to CVS or Excel -if you use onenote to document projects exporting this info can easily help you to generate a work log and a progress log or a report 

The export could include info like Date, title, tags, attachment list
