### ISSUE TITLE
Add the capability to automatically detect if OneNote is installed for all the users or just for the current one and remove that from the OneMore installer

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#375]
It drives me crazy when I am upgrading (I keep doing that manually and today I am in trouble, issue coming next) when I see the question: install this for the current user of for everybody, because I can never remember how it was installed
From what I am reading this can be detected programmatically ...maybe it could be eliminated from the installer

**Comment by stevencohn** [comment]
It should default to Everyone. Leave it at that.

**Comment by stevencohn** [comment]
I can hide that
