### ISSUE TITLE
'Unhandled exception' error when trying to update context menu settings

### ISSUE THREAD

**Issue by maribaka** [stevencohn/OneMore#380]
Hello! I've been using OneMore for a little while, and I've come across a couple bugs I haven't seen anyone talk about yet. (Also, I'm both new to github and I don't know anything about programming.)

One of the bugs is pretty simple, but: I've set up my own group of commands in the ribbon, and ONLY when the "table" menu is in the 3-by-3 list of them, the smaller icon for it doesn't show. The large icon shows if the command is on its own, and the smaller icon shows in the list if I reset the ribbon so that OneMore's ribbon is the default setup. (I believe this bug started shortly after the switch to WebView2.)

The title bug is a bit bigger:

**Describe the bug**
I don't change the settings too much, but I came across an error related to the "context menu" page only. Whether I have any items set to display in the context menu or not, whether I've tried to add any or not, I get the same popup (below). I even once unintentionally tried to save other settings while still open on the "context menu" page (I've been trying to reinstall/redo my settings from the beginning again) and it still came up. Not sure if it's related but I keep "dynamic menu context settings" unchecked in the general options. Also, sometimes, it causes the other commands in the ribbon to show only icons, until I close and reopen OneNote.

**To Reproduce**
1. Go to OneMore Settings
2. Click on Context Menu
3. Click save (whether checking any of the boxes in the page or not)
4. Popup comes up.

**Expected behavior**
Settings should save and/or ask for a relaunch of OneNote.

**Screenshots**
![image](https://user-images.githubusercontent.com/97633332/149218131-f666cb91-ed0e-4cc8-81aa-f48470e5e142.png)

**Environment (if applicable):**
 - OneNote Version: Office 365, Preview Channel: Version 2201 (Build 14827.20060), 64-bit
 - OneMore Version: I have OneMore Version 4.13.2, but I think this problem has been around since maybe 4-6 updates ago? (I've tried to uninstall and reinstall slightly older versions to figure out when it started, and I'm pretty sure it was before the switch to WebView2.)

**Additional context**
This is what the popup box says:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: InvalidArgument=Value of '46' is not valid for 'index'.
Parameter name: index
   at System.Windows.Forms.CheckedListBox.GetItemCheckState(Int32 index)
   at System.Windows.Forms.CheckedListBox.GetItemChecked(Int32 index)
   at River.OneMoreAddIn.Settings.ContextMenuSheet.CollectSettings()
   at River.OneMoreAddIn.Settings.SettingsDialog.OK(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4420.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
River.OneMoreAddIn
    Assembly Version: 4.13.2.0
    Win32 Version: 4.13.2
    CodeBase: file:///C:/Program%20Files/River/OneMoreAddIn/River.OneMoreAddIn.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4435.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Web.Extensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4330.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Web.Extensions/v4.0_4.0.0.0__31bf3856ad364e35/System.Web.Extensions.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4330.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
Microsoft.Office.Interop.OneNote
    Assembly Version: 15.0.0.0
    Win32 Version: 15.0.4420.1017
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.Office.Interop.OneNote/15.0.0.0__71e9bce111e9429c/Microsoft.Office.Interop.OneNote.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by stevencohn** [comment]
Thanks for this.

Regarding the ribbon problem, I think you're talking about this, where the icon is not shown:

<img width="81" alt="image" src="https://user-images.githubusercontent.com/9964757/149235524-9cb6a9d3-5ac3-4f52-aa6a-5887c6a2dda3.png">

I'll check it out but not sure I know what's going on there. It may be internal to OneNote. Most likely unrelated to Webview2

Regarding the context menu settings, I've made some updates to that and will make it available in the next release. Hopefully that will hard the way it loads and saves those settings to avoid that failure. I appreciate you mentioning it.

**Comment by maribaka** [comment]
Yeah, in my own ribbon group, it looks like this:
![image](https://user-images.githubusercontent.com/97633332/149235912-0c8a6b0a-127d-44b9-b6ff-0ae3d808f5ae.png)
But anywhere else the icon is shown, it's fine. I didn't think it was related to Webview2, I just wanted to point that out because it was probably started from the first update where you switched to it, as far as I can remember.

The thing is, when I copied my settings file from before redoing it, where it showed which commands I'd added to the context menu, it showed them as checked in the settings and they work like normal. It's only when I attempt to add/remove any from the menu and save it that this popup happens.

And that sounds good! Thank you. :) I was waiting for a while to see if anyone noticed it, because I was nervous about mentioning it, but I finally got myself to do it, haha.

**Comment by stevencohn** [comment]
<img width="88" alt="image" src="https://user-images.githubusercontent.com/9964757/149238372-06a1ad7f-cebf-49f6-8cce-f121137307d4.png">

**Comment by stevencohn** [comment]
I believe I fixed the unhandled exception but also wasn't able to actually reproduce it so please let me know if there are still issues.

**Comment by maribaka** [comment]
Looks like it's working again! I've been able to turn context menu options on/off without any problems. :D Thank you so much!

**Comment by patrickenfuego** [comment]
I can confirm this fixed the issue as well. Excellent work!

**Comment by stevencohn** [comment]
Great. Closing this then.
