### ISSUE TITLE
FEATURE: Settings\Language dropdown

### ISSUE THREAD

**Issue by digitalAssetStore** [stevencohn/OneMore#384]
# Feature
Can you add a feature to set a fix UX language for OneMore?

# Proposal
At "OneMore\Settings" a "Language" dropdown containing entries like
- Automatic (default)
- English
- Spain
- Portuguese
- Mexican
- French
- German
- etc.

# Background
I work with users with different default languages,
but need to be able to set  a standard UX language for OneMore
(instead of  frustrating auto-detect).

**Comment by stevencohn** [comment]
closed accidentally

**Comment by stevencohn** [comment]
will be available in next release

**Comment by digitalAssetStore** [comment]
steven, thanks a lot.
fast, professional response and code enhancement.
