### ISSUE TITLE
Add and modify shortcut key function

### ISSUE THREAD

**Issue by lun9090** [stevencohn/OneMore#394]
能新增修改快捷键功能吗，它和我使用的其他插件快捷键有冲突。
Can I add new shortcut key function? It conflicts with other plug-in shortcuts used by me.

**Comment by MehsEzeerf** [comment]
It would be great to be able to update the bindings or add new ones to existing functions.

**Comment by MehsEzeerf** [comment]
I was considering asking to get pointed in the right direction to try an create my own binding for the bi-direcitonal linking so I could use it as  a "starter project" lol.  I am like the person who can pick out understanding from another foreign language but can't speak it.
