### ISSUE TITLE
Favorites feature does not jump to notebook only the section and page

### ISSUE THREAD

**Issue by javathehunt** [stevencohn/OneMore#395]
Favorites feature does not jump to notebook only the section and page

Using the Favorites function jumps the user to the bookmarked section or page but it does nothing for locating the notebook that the page is in. So when working in notebook 1 and I use the Favorites to jump to a page or section in notebook 5 the section / page in notebook 5 opens (to the right in my instance) but in my list of notebooks in the left column I am still in notebook 1. I need to manually scroll down the list of notebooks then navigate thru the sections and sub-groups to match up the notebook on the left with the open page to the right if I want to work in that notebook which more often than not is the case. I need access to the surrounding sections. Consider 20 notebooks with 40 sections. There are too many sections to make use of the horizontal section layout so the vertical layout is the only way to work and easily navigate. After jumping to a page I then need to manually navigate to that page making the Favorites feature not as useful as needed. Adding a Breadcrumb to the bookmarked page makes navigating thru the notebooks more efficient but still there is manual navigation necessary. I think the issue is the same using the search function built into Onenote as well as the Onemore search it will not open up the relevant notebook only the section or page. And I think the Onetastic macro had the same limitation so maybe this is a limitation of Onenote. It would be a big improvement if there was a way to jump to the  notebook of the associated page.

**Comment by stevencohn** [comment]
I'm afraid I'm not able to reproduce this myself. Whenever I open a Favorite in another notebook, OneNote highlights that notebook and selects the notebook containing the favorite page. It does not expand the notebook if it is collapsed. But if I do expand it, it will show that the correct section is highlighted as well.

What OneNote doesn't do is scroll the notebook into view in the left hand panel. This is internal OneNote functionality that OneMore doesn't have access to unfortunately. It should still highlight the notebook; it just won't scroll automatically.

**Comment by javathehunt** [comment]
Yeah it does highlight on mine. But that does not help when you have two dozen notebooks and few hundred sections. The highlight is great if you know where to look for it. As I mentioned clicking on a favorite doesn’t necessarily tell what notebook that is in, I often need to click on the favorite and when i get there then execute the breadcrumb to see the address of the page and then go to the left pane and navigate to the notebook. Either way whether the exact notebook and section is known or if i need to use a breadcrumb to figure it out, it still required the user to manually navigate to the notebook / section and once there the highlighted section is visible. I assumed maybe it was not possible to make happen but figured i would ask. It is one of two roadblocks I have using Onenote daily. The other issue is the possibility of having an automatic update to “Refresh page references” instead of having to manually click on the Refresh link in each page or the button on the toolbar, but I figure if that was possible you would have already incorporated that in already. Would be nice for an auto update option. Thanks.

**Comment by stevencohn** [comment]
That's correct. I have no control over that. Microsoft has not exposed an API that allows me to scroll the notebook into view.

Regarding the page reference updates, please submit a new ticket an explain what you mean. What page references? How were they created? What would you expect to happen? What changes do you expect to be captured and refreshed?
