### ISSUE TITLE
Installation Error: "A new guard page for the stack could not be created"

### ISSUE THREAD

**Issue by AlbusPercivalDumbledore** [stevencohn/OneMore#397]
Hi, @stevencohn! I'm having trouble installing OneMore, with the installer showing error: "A new guard page for the stack could not be created"

Running: Windows 10 Enterprise LTSC v1809, 64 bit
MS Office Mondo 2016, v2112

Log:

```
OneMore installer running as user NT AUTHORITY\SYSTEM (S-1-5-18) elevated

Register... version 4.14

ShutdownOneNoteDeployment.Install ---
stopping process ONENOTE, pid 5548
process termination confirmed

ProtocolHandlerDeployment.Install ---
step 0: opening HKLM:\Software\Classes\onemore
step 1: setting properties of HKLM:\Software\Classes\onemore
step 2: opening HKLM:\Software\Classes\onemore\shell\open\command
step 3: setting properties of HKLM:\Software\Classes\onemore\shell\open\command
verified: key created HKEY_LOCAL_MACHINE\Software\Classes\onemore\shell\open\command

TrustedProtocolDeployment.Install ---
translating user DESKTOP-M8M6PCU\harsh to SID
registering trusted protocol for user DESKTOP-M8M6PCU (S-1-5-21-345151178-3446141315-3058972111-1001)
defaulting Office version to 16
step 4: opening HKCU:\Software\Policies\Microsoft\Office\16.0\Common\Security\Trusted Protocols\All Applications\onemore:
key already exists

EdgeWebViewDeployment.Install ---
error registering
```

**Comment by AlbusPercivalDumbledore** [comment]
UPDATE: Was able to install OneMore v4.11. 

Versions >= 4.12 use EdgeWebView2, and Edge HTML wasn't updated to Edge Chromium in Windows LTSC 2019 Edition

**Comment by stevencohn** [comment]
EdgeWebView2 is supported on Windows LTSC 2019 Edition as stated here https://docs.microsoft.com/en-us/microsoft-edge/webview2/#supported-platforms

But I'm suspicious of the MS Office Mondo 2016, v2112 pre-release you have. I don't have access to that version so can't test but a few users have raised issues running OneMore with pre-release versions of Office.

I'm sorry you're having difficulties but as a "hobby" project, I can't practically support all permutations of Office+Windows.

**Comment by AlbusPercivalDumbledore** [comment]
No problem, v4.11 has all the features I was looking for. Thanks for your work!
