### ISSUE TITLE
Resize the image to 100%, the size is wrong.

### ISSUE THREAD

**Issue by gpbicego** [stevencohn/OneMore#401]
**To Reproduce**
1. Resize the image to 50%
2. Resize the image to 100%

**Expected behavior**
Size of image should be as the original image 'Current size' or 'Original size'. 

**Screenshots**
![image](https://user-images.githubusercontent.com/22318088/150950491-51bf925b-6cf1-442c-a80a-2cdca1f851d0.png)

**Environment (if applicable):**
 - Microsoft® OneNote® for Microsoft 365 MSO (Version 2112 Build 16.0.14729.20254) 64-bit 
 - OneMore Version 4.15 commit 399 image resize (#400)

**Comment by stevencohn** [comment]
Yes, this is a defect.

The "Current size" is the viewed size of the image, whereas "Original size" is the actual size of the stored image. I'm going to change these labels as well to make that more clear.

So, this is how it _should_ work, once it is fixed: 
1. Set the size to 50%. This will change the view size from 232x137 to 116x68
2. Set the size to 200%. This will restore the view size back to 232x136 (note the math)

As long as "Preserve original size" is ticked, the storage size will not change; only the view size will change.

**Comment by gpbicego** [comment]
I think your solution is clearer than mine.

**Comment by stevencohn** [comment]
I gave the Resize dialog some urgently needed TLC but also went a little overboard adding new features that I've been wanting for myself for quite some time.

**Comment by gpbicego** [comment]
Thanks again
