### ISSUE TITLE
Automaticially generate A4 pages to write on

### ISSUE THREAD

**Issue by Gashans** [stevencohn/OneMore#403]
Some people don't really want infinite pages, and getting custom sized pages is a big hassle...
would it be possible to just add a button that appends a page in a predefined format onto the current document?
I think this would fix oneNote for a lot of people, since Microsoft doesnt seem to bother ;D
Thanks

**Comment by stevencohn** [comment]
"appends a page in a predefined format onto the current document"

Each OneNote page (document) has a single format and is a single page. You cannot combine formats in one OneNote page.

But what I could do quite easily is add a button or command that sets the size of the current page to a preferred dimension, like A4. I agree the default OneNote steps are tedious.

**Comment by gpbicego** [comment]
You could use background images as suggested in this topic: 
["How to have multiple A4 pages and print the pdf without cutting the pages"](https://www.reddit.com/r/OneNote/comments/jxofvb/guide_how_to_have_multiple_a4_pages_and_print_the/) 
to simulate multiple page.
