### ISSUE TITLE
Embedded files

### ISSUE THREAD

**Issue by Macca20** [stevencohn/OneMore#407]
When exporting onenote pages, enbedded files  (docx, pdf, etc) are not exported
Only images such as jpgs are exported.

Ideally all would be exported to a media folder and hyperlinked in the exported document

The alternative is to export each embedded file one at a time or use the "onenote>file>send>email page" which inserts all embedded documents as attachments that allows for a bulk save to a folder.

THE FINE PRINT
This is a hobby project that I started for myself. I'm happy to take requests and will promise to consider each one carefully but offer no guarantees that I will ultimately agree to their usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
They are included when you use OneMore's export as HTML feature or the export as Markdown feature but you have to tick the option to _Include attachments_ as shown here

<img width="316" alt="image" src="https://user-images.githubusercontent.com/9964757/151660134-cdc0e4c4-f69d-48d7-8062-f2fe831bbcd6.png">

**Comment by stevencohn** [comment]
I did find an error where it will fail if the specified export folder does not exist but that's unrelated to how it manages attachments. I'll fix the missing folder problem.

**Comment by stevencohn** [comment]
So I'm also updating it so you can export attachments with Word and XML exports too
