### ISSUE TITLE
Increase / decrease font size resets fonts to 'Calibri'

### ISSUE THREAD

**Issue by adamm0373** [stevencohn/OneMore#409]
**Describe the bug**
Increase / decrease font size resets fonts to 'Calibri'

**To Reproduce**
- Click on +1 More icon on Home ribbon
- Edit > Increase Font Size, or Decrease Font Size
- Various page font gets reset to Calibri - some retain original font, most get set to Calibri
- Applying Custom Styles also produces similar issues, despite having set the fonts manually in Edit Styles.

**Expected behavior**
- I expect my font choices on the page to be unchanged. 
- Similarly, applying custom styles - I expect it to follow the font settings I chose from Edit Styles.

**Screenshots**
I think this is self-explanatory.

**Environment (if applicable):**
 - Microsoft® OneNote® for Microsoft 365 MSO (Version 2112 Build 16.0.14729.20254) 64-bit 
 - OneMore Version 4.15

**Additional context**
N/A

**Comment by stevencohn** [comment]
It would be helpful to see an example. And what did you do to change the font? For instance, did you change the font of the built-in headings or did you copy/paste an article from the Web or something else?

**Comment by adamm0373** [comment]
I have removed OneMore for the moment. I don't have any screenshots.  This happens with any form of notes. 

Create a custom style (or edit an existing one) to use another font (such as Segoe UI Variable, in my case).  Try to apply it.   Fonts won't change, but some fonts will 'reset' to Calibri 11.

**Comment by stevencohn** [comment]
I'm having trouble reproducing this. I'll close this in a few days if I can't find steps to repo

**Comment by adamm0373** [comment]
I gave you the steps.  I worked around it - with pages that have mixed style content (with your OneNote application set to a different Default page font from the Page's own default font -- for example, when it was created).  It will reset to that default font.  I found a work around, which was to select the affected area and Clear Formatting, then that will "reset" that block ... and applying custom styles work properly again.

**Comment by stevencohn** [comment]
Here's what I did to try to repro:

1. Create a page containing all standard styles: all heading styles, all paragraph styles, in various sequences and combinations, including bold and italics within paragraphs. Apply Styles works as expected.
2. Create page containing all standard styles, changed the OneNote default font in the Options dialog. Apply Styles works as expected.
3. Create a page containing all standard styles, modified some of the content with custom overrides - using OneNote's text format functions on the ribbon bar. Apply Styles works as expected.
4. Copied content from a web page. Apply Styles works as expected.

If there's a very specific case you can describe that is highly repeatable then I can correct it. But I can't until I have a pattern that demonstrates the issue.

**Comment by stevencohn** [comment]
Regarding applying styles, this is probably fixed by #418 which was released as part of [4.15.1](https://github.com/stevencohn/OneMore/releases/tag/4.15.1)

**Comment by stevencohn** [comment]
Oops... re #418 I did find a small issue there with strangely embedded fonts that I will fix. But still trying to repro the resize issue...

**Comment by adamm0373** [comment]
I'm not seeing this issue anymore, and I'm unable to reproduce it now - I think it's because some of my notes have phantom font settings applied to it.   Or it could have been fixed in 4.15.1!  Thanks!
