### ISSUE TITLE
Strikethrough/grey-out completed task-tagged lines

### ISSUE THREAD

**Issue by tridian-tn** [stevencohn/OneMore#41]
A feature request, if it's useful to others! A few of the Onetastic macros offer a command to strikethrough/grey-out text next to completed task tags on the current page. It makes it much easier to scan through a page of tasks and see what's left.

e.g.
![image](https://user-images.githubusercontent.com/10810780/92248428-93dbab80-eec0-11ea-8034-e376cff90a91.png)

It would be great if OneMore offered this. Thanks for the addin, btw. It's really really useful.

**Comment by stevencohn** [comment]
Added strikethough functionality. Did not yet gray out text but will consider it later. 
This will be available in the next release.

**Comment by tridian-tn** [comment]
Brilliant thank you
