### ISSUE TITLE
Colorizing JavaScript code failed

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#410]
Here is the log
`11016:17] Running command ColorizeCommand
11016:17] ..error wrapping /<span
style='font-family:Calibri' lang="en-US">var links = [/
11016:17] Error running command ColorizeCommand
11016:17] System.Xml.XmlException
Message: The 'span' start tag on line 1 position 9 does not match the end tag of 'cdata'. Line 2, position 57.
Source: System.Xml
StackTrace:    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowTagMismatch(NodeData startTag)
   at System.Xml.XmlTextReaderImpl.ParseEndElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XElement.ReadElementFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XElement.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XElement.Parse(String text, LoadOptions options)
   at River.OneMoreAddIn.XCDataExtensions.GetWrapper(XCData cdata)
   at River.OneMoreAddIn.Commands.ColorizeCommand.<Execute>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.CommandFactory.<Run>d__6.MoveNext()
TargetSite: [System.Xml] System.Xml.XmlTextReaderImpl::Throw()

11016:17] Running command AboutCommand
`

and here is the text that caused that 

<one:Page xmlns:one="http://schemas.microsoft.com/office/onenote/2013/onenote" ID="{xxxxxxxxxxxxxxxxxxxx}" name="var nodes = [" dateTime="2022-01-31T13:43:16.000Z" lastModifiedTime="2022-01-31T13:44:24.000Z" pageLevel="1" isCurrentlyViewed="true" selected="partial" lang="en-US">
  <one:QuickStyleDef index="0" name="PageTitle" fontColor="automatic" highlightColor="automatic" font="Calibri Light" fontSize="20.0" spaceBefore="0.0" spaceAfter="0.0" />
  <one:QuickStyleDef index="1" name="p" fontColor="automatic" highlightColor="automatic" font="Calibri" fontSize="10.0" spaceBefore="0.0" spaceAfter="0.0" />
  <one:PageSettings RTL="false" color="automatic">
    <one:PageSize>
      <one:Automatic />
    </one:PageSize>
    <one:RuleLines visible="false" />
  </one:PageSettings>
  <one:Title lang="en-US">
    <one:OE alignment="left" quickStyleIndex="0">
      <one:T><![CDATA[]]></one:T>
    </one:OE>
  </one:Title>
  <one:Outline selected="partial">
    <one:Position x="36.0" y="86.4000015258789" z="0" />
    <one:Size width="474.300048828125" height="124.2676467895508" />
    <one:OEChildren selected="partial">
      <one:OE alignment="left" quickStyleIndex="1" selected="partial" style="font-family:Calibri;font-size:10.2pt">
        <one:T selected="all"><![CDATA[var nodes = [<br>
  {&quot;id&quot;: &quot;Alice&quot;},<br>
  {&quot;id&quot;: &quot;Bob&quot;},<br>
  {&quot;id&quot;: &quot;Carol&quot;}<br>
];]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="1" selected="partial" style="font-size:10.2pt">
        <one:T selected="all"><![CDATA[<span style='font-family:Calibri' lang=en-US>var links = [<br>
  {&quot;source&quot;: 0, &quot;target&quot;: 1}, // Alice </span><span style='font-family:"Cambria Math"' lang="x-IV_mathan">→</span><span style='font-family:Calibri' lang=en-US> Bob<br>
  {&quot;source&quot;: 1, &quot;target&quot;: 2} // Bob </span><span style='font-family:"Cambria Math"' lang="x-IV_mathan">→</span><span style='font-family:Calibri' lang=en-US> Carol<br>
];</span>]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="1" selected="partial">
        <one:T selected="all"><![CDATA[]]></one:T>
      </one:OE>
    </one:OEChildren>
  </one:Outline>
</one:Page>

**Comment by stevencohn** [comment]
Hi, I'm not sure the page XML pasted correctly, but I do see this which looks strange:

```
{"id": "Alice"},
{"id": "Bob"},
{"id": "Carol"}
];]]>
```

I'm guessint the ;]] at the end is the result of the XML missing the CDATA element within the T; probably a result of bad pasting.

But the line it's complaining about is this:

```
var links = [
{"source": 0, "target": 1}, // Alice → Bob
{"source": 1, "target": 2} // Bob → Carol
];]]>
```

But I seem to be able to colorize it OK

<img width="132" alt="image" src="https://user-images.githubusercontent.com/9964757/151806343-785f3ca4-ed9a-46ce-8be3-750fd8496961.png">

Is the page XML above missing some things? Maybe you can post the .xml file somewhere that I can grab?

**Comment by 1001QAdotNET** [comment]
Excepting the XXXXXXXX string I did not change anything there 
the 1000 works picture
[https://i.imgur.com/ENQr4qc.png](url)

**Comment by stevencohn** [comment]
Got it thanks.

A workaround while I fix it...

1. Select the text
2. Press Ctrl-N to reset to normal font
3. Choose OneMore/Edit/Proofing language and set to English (or your default language)
4. Colorize

That should clean it up enough to properly colorize it.
