### ISSUE TITLE
Why do some web pages lose headers information when imported into OneNote?

### ISSUE THREAD

**Issue by gpbicego** [stevencohn/OneMore#413]
For example, I import this page: 
https://www.home-assistant.io/integrations/modbus/
the headers are lost (even if I copy and paste in Word or OneNote or use "Clip to OneNote").
As a workaround I use OneMore "Select text with similar formatting" and then manually I set each header type.
The problem also arises using OneMore "Import Web Page".
Thanks, OneMore is great.

**Comment by stevencohn** [comment]
Marking as a duplicate of #411
