### ISSUE TITLE
Hoping to Add function of supporting customizing the name of Style

### ISSUE THREAD

**Issue by codercplus** [stevencohn/OneMore#414]
When adding a new style to the plug-in, the default style name is 'style-XXXX' and cannot be modified. The name automatically generated by the system is not conducive to distinguish and identify what we want among so many styles.

So, hoping to add support for **style renaming**,Including styles that already exist in the system, such as 'heading 1-6' and so on.

**Comment by stevencohn** [comment]
Looking into it. Note this is only an issue in the Edit Styles dialog. 

If you use the Create Style from Selection command, you can modify the name. Maybe that would be a good workaround for you until I enhance the Edit Styles dialog.
