### ISSUE TITLE
In some occasion, Style doesn't go into effect entirely.

### ISSUE THREAD

**Issue by codercplus** [stevencohn/OneMore#418]
**Describe the bug**
If I apply different styles to the same paragraph and then apply another style to it, the effect of the last applied style may be incomplete. Some formats remain unchanged. 

**To Reproduce**

1. Create a new document and enter a English paragraph.
2. Click on 'Custom Styles'→'Edit Styles'→'New Style' , and set the Style Type to '**Paragraph - entire paragraph**', and the font-size to 20. The other options remain default. Clike 'OK (Save) ' to exit the dialog.（Suppose the new style name is Style-1234）
3. Select the previous paragraph, and apply it to the Style of 'Heading 6' and ‘Quote’ in turn . We will see that the font of the paragraph has become Italic. So far, everything is normal.
4. Then we apply the paragraph to the Style of 'style-1234'. We can see the text still remains Italic. However, we clearly set it to non Italic in the step2. This shows that the application of the new style is incomplete.

**Expected behavior**
The effect of the style should be consistent with the setting.

**Screenshots**

![Snipaste_2022-02-03_20-26-11](https://user-images.githubusercontent.com/63757163/152346563-d2fa3d20-19c7-4d4e-b3b1-0fb52ac2ac2a.png)

**Environment (if applicable):**
 - OneNote Version: O365, 64bit
 - OneMore Version:4.15

**Comment by stevencohn** [comment]
Thanks for the instructions. I can easily reproduce this.
