### ISSUE TITLE
Switch Background Button

### ISSUE THREAD

**Issue by itsjoel** [stevencohn/OneMore#42]
This is a bit of a weird request, but I'd like to be able to quickly switch between dark and light mode. I know this covers a lot of the same area as Set Page Color, but it would be really useful as a workaround for NoteHighlight2016.
[NoteHighlight2016 works extremely poorly in Dark Mode.](https://github.com/elvirbrk/NoteHighlight2016/issues/109#issue-549194412) I have tried to fix this by manually adding dark themes, but these behave ever more weirdly, showing up with a white highlight if the background is listed as a dark color in the theme file, and muted colors if the background is listed as white in the theme file.
[It used to be possible to work around this using the Switch Background option](https://github.com/elvirbrk/NoteHighlight2016/issues/109#issuecomment-619917722), but this has disappeared in newer versions of OneNote. If you could add this button back in, it would be really useful, as development on NoteHighlight2016 seems to have halted.

**Comment by stevencohn** [comment]
So setting the page background action and the apply theme action are separate. Setting the background doesn't affect the colors on the page (mostly - OneNote will do its own thing which is sometimes hard to understand). I could enhance the set background action to also apply a chosen dark theme at the same time.... let me think about that.
