### ISSUE TITLE
CustomStyles is not overriding all attributes when it should

### ISSUE THREAD

**Issue by zhongguocn** [stevencohn/OneMore#427]
**Describe the bug**
Set the paragraph text font style in the page content to normal and use [custom styles] > [apply styles to page]. The Normal font style is still the default font style and has not been updated to the custom style.

Other font styles are updated to custom styles, except normal。

**Comment by stevencohn** [comment]
note to self: this is due to multiple definitions of the "p" quick style on the page; will affect first elements bound to first quick style but not subsequent

**Comment by zhongguocn** [comment]
Sorry, I didn't catch your meaning. Is this the wrong way I use it? What is the correct method of use?

**Comment by stevencohn** [comment]
No no. this was just a note to myself as a reminder of how to fix it! I'll update this ticket once I do.

**Comment by zhongguocn** [comment]
got it.

I tested the font style on many pages and found that some pages can set normal style successfully, while others can't. 

I didn't find the reason. I'm sorry I can't help.
