### ISSUE TITLE
How to fix custom styles so URLs don't become black like regular text? 

### ISSUE THREAD

**Issue by adamm0373** [stevencohn/OneMore#428]
Hi, I'd like to make sure that when I apply my custom styles that the URLs don't get colored like normal text (it's currently making it black, so the only way I can differentiate a link is from an underline.  Is there a style option for links? 

Btw great job with this add-in.. I am learning C#.. any tips or advice on making add-ins? ?

**Comment by stevencohn** [comment]
Unfortunately, this is a well-known issue with the OneNote interop API. There is no known solution.

**Comment by adamm0373** [comment]
That's.. unfortunate.   Do you or have other users found a work-around?

**Comment by stevencohn** [comment]
No. I've investigated in the past but alas...

**Comment by adamm0373** [comment]
I know this is only your side thing, and I appreciate the hard work you do with this!   

I can fix this myself manually, by selecting the link and applying the "Normal" style.  This style already contains the font I want from the OneNote setting (my font of choice currently is "Segoe UI Variable Display".  When I do apply 'Normal' from OneNote's default Styles, this apparently creates a new entry (Thank you for adding the Show XML option):

`<one:QuickStyleDef index="3" name="p" fontColor="automatic" highlightColor="automatic" font="Segoe UI Variable Display" fontSize="12.0" spaceBefore="0.0" spaceAfter="0.0" />`

Comparing the difference, it looks like quick style index=1 applies a color of 000000 and quick style index=3 applies a color of automatic (shouldn't that be what "default fonts" should be, right?)

Can it be possible to add a style option or toggle, to apply an "automatic" coloring instead of forcing it to be black?

**Comment by stevencohn** [comment]
No. Believe me, I've tested all the possibilities. The problem lies within the Interop API that OneNote exposes for addins like OneMore. That Interop API "sanitizes" incoming XML in ways that don't always make sense. 

You can prove this by using the OneNote XML window to edit the XML directly (you have to untick the top two checkboxes) and try to save the page. There's no combination I've found that either works at all or works in all cases. Remember, I'm trying to support a matrix of light mode vs dark mode vs background color vs styles.

**Comment by adamm0373** [comment]
(you caught me editing my previous comment, so here's a new comment instead)

For the time being, I can edit the style XML directly and change #000000 to automatic for the 'Normal' font, load the style and it does what I want. I don't know what issues doing this might introduce (hopefully none) on my end, and I realize that it doesn't solve the actual problem at hand:

_Set "Normal" to any other color in the Styles, then it will change Link colors too, and I get that._  
 
But, I want to apply 'automatic' coloring to 'Normal' so my links show up the way it should.
