### ISSUE TITLE
Applying dark background styles turns bullets black

### ISSUE THREAD

**Issue by itsjoel** [stevencohn/OneMore#43]
Applying default styles to a page that has a dark background turns bullets and the numbers on numbered lists black, making them very hard to see.

**Comment by stevencohn** [comment]
As I mentioned in your other ticket #42, page background and themes are two separate actions. So if you set the background, you must then also set the theme. I'll consider combining these into a single action....

**Comment by stevencohn** [comment]
Combining with #42
