### ISSUE TITLE
Add caption to attachment icons

### ISSUE THREAD

**Issue by G2G2G** [stevencohn/OneMore#431]
Onenote truncates the text in attachment names, making it hard to distinguish between multiple files with similar names. You have to move the cursor over the file and read the tooltip.

Suggesting adding a command that would automatically copy file name and insert as text under the attachment.

**Comment by stevencohn** [comment]
For which output format?

**Comment by G2G2G** [comment]
In Onenote itself
________________________________

**Comment by stevencohn** [comment]
Oh sorry I misunderstood. OK. I'll mark this as an enhancement.
