### ISSUE TITLE
Installation Question

### ISSUE THREAD

**Issue by MichiFr** [stevencohn/OneMore#438]
Hi!

I'm running OneNote 365 (x32) on Windows 10 (x64). I've chosen the x86 installer which prompts me to add my administrator credentials short after starting the installer. My current user does not have admin privileges, though.

The installation with the x86 exe went smooth and after a restart of OneNote - nothing happens, no menu items or any sign of OneMore. The readme.md says:
_Run the installer
    If OneNote is installed for all users then you must install OneMore for all users as well_

I do not know if OneNote has been installed for all users. Nor do I know how to force the installer to do so and to check if this is the reason why it does not show up in ON at all.

So could you please assist and give some hint how to check if anything is correctly installed? Btw, the program folder has a new subfolder River with all of those necessary files for running OneMore. At least I assume the installation went fine.

**Comment by stevencohn** [comment]
The installer does need admin rights to write to the Window Registry. OneNote addins are registered as COM components and that can only be done by using the Windows Registry.

OneMore does install for all users so you could log in as an amin and then run the installer. Alternatively, you can invoke it from your normal user account (provided you have the user name and password of an admin account) by opening a command prompt window and entering this command:

`runas /user:steve "msiexec /i <path>\OneMore_4.14_Setupx64.msi"`

where <path> is the full path to the installer. For example, if the msi is in C:\tools then the full command would be:

`runas /user:steve "msiexec /i C:\tools\OneMore_4.14_Setupx64.msi"`

There should be no spaces in the path. If the msi is in a folder that has a space in its name, move it another folder.

**Comment by stevencohn** [comment]
Although I admit I think I just found a problem with the command line approach! I'll take a look

**Comment by stevencohn** [comment]
OK I think I finally have a good understanding of what's happening now. This may help solve all installer issues that have been reported previously so thank for the ticket. I'll work on finding a solution.

**Comment by stevencohn** [comment]
Yes I believe so and have a fix... will take a few days

**Comment by stevencohn** [comment]
### Please Read...

There are new install instruction on the [home page](https://github.com/stevencohn/onemore#install).

Installing from a user account without admin rights or from an admin account on a machine shared by and on behalf of non-admin users requires all non-admin users to sign out and then sign in again after installation.

**Comment by stevencohn** [comment]
Why did you chose x86? Use that only if you have a 32 bit windows machine.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MichiFr** [comment]
I've used it because I'm running 32bit Office O365. 
I thought this is the correct way to install OneMore for x86 MSOffice on my Win x64...

**Comment by stevencohn** [comment]
Please try the x64 installer

**Comment by MichiFr** [comment]
Yes, did already and it worked, at least the install process. 
I'll report back shortly when another task finished and I could log out my current user...

**Comment by stevencohn** [comment]
I will investigate adding a prerequisite check and display a more friendly message to the user in this case. There have been too many users confused by this and it's my fault for not providing a more helpful installer.

**Comment by MichiFr** [comment]
> Please try the x64 installer
SUCCESS! OneMore is up and running in my OneNote (using my current non-admin user).

**Comment by MichiFr** [comment]
Thanks for you comprehensive help and for this great add-in, of course!
