### ISSUE TITLE
Paragraph Spacing

### ISSUE THREAD

**Issue by piyush1908** [stevencohn/OneMore#44]
Can you please introduce paragraph spacing with automatic all 0. 
I use it alot

![image](https://user-images.githubusercontent.com/12750186/92641396-503bd400-f2fc-11ea-81cf-e52b2ee8268a.png)

**Comment by stevencohn** [comment]
Can you please explain this further? I don't know what you mean.

**Comment by piyush1908** [comment]
See I have to open paragraph spacing again n again, choose 0, then click
ok, Can u give shortcut so that I don't have to this exercise, like a
function which automatically sets paragraph spacing to 0, (like you have a
function to delete all empty paras, a, simple function like that)

**Comment by stevencohn** [comment]
So I could add a command that simply removes paragraph spacing throughout the page or a selected region of the page. I think it should apply only to simple paragraphs, not headings.

**Comment by 1001QAdotNET** [comment]
+1 vote for this feature. 
So far I have not used a lot but I have been lucky because the content I am using does not use a lot of that

**Comment by stevencohn** [comment]
Done. It will be available in the next release.
This is the dialog box that shows, with all options ticked by default:

![image](https://user-images.githubusercontent.com/9964757/92763309-62039280-f361-11ea-90ee-5220eb5a4b73.png)

**Comment by 1001QAdotNET** [comment]
thank you
