### ISSUE TITLE
Is there a way to group objects

### ISSUE THREAD

**Issue by pyzhangxiang** [stevencohn/OneMore#442]
Hi, is there a way to group text blocks and shapes permanently like the word?

**Comment by stevencohn** [comment]
No, there is no way to do that in OneNote. It's been a topic of discussion both here for OneMore and also other utilities like OneNoteGem and Onetastic. While text blocks can be grouped using OneNote's built-in outline boxes, shapes and hand drawings are bound to the page, not to any individual outline box.

It may be possible to create a two-step function that first, records the position of selected shapes in relation to the current outline and second, moves those shapes to that relative position after an outline is moved. In my opinion this would be rather clunky and not really much better than manually dragging shapes to a desired position.
