### ISSUE TITLE
Error running the update command

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#446]
Reporting a bug and asking for advice

Here is the bug, shows up when you use the About dialog and Check for update
What do I do to get the new Batch import capable release? Do I install manually? 

11996:1] Starting dllhost 11996, CPU=3600Mhz, en-US/en-US, v4.13.1, OneNote 15.0, Office 15.0
11996:1] ..OnConnection(ConnectionMode:ext_cm_Startup,1)
11996:1] ..OneAddInsUpdate(custom[]:0)
11996:3] ..building ribbon
11996:3] ..building ribbon colorizer commands
11996:3] ..RibbonLoaded()
11996:1] ..OnStartupComplete(custom[]:0)
11996:1] ..OneNote backup folder:: C:\Users\1001QA\AppData\Local\Microsoft\OneNote\15.0\Backup
11996:1] ..OneNote default folder: C:\Users\1001QA\Documents\OneNote Notebooks
11996:1] ..OneNote unfiled folder: C:\Users\1001QA\Documents\OneNote Notebooks\My Notebook\Quick Notes.one
11996:1] ..OneNote process module: C:\Program Files\Microsoft Office 15\root\office15\ONENOTE.EXE (15.0.5233.1000)
11996:1] ..defining hotkeys for input locale 1033
11996:1] ..ready
11996:1] Running command AboutCommand
11996:1] ..Running command UpdateCommand
11996:1] Error running command UpdateCommand
11996:1] System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: River.OneMoreAddIn
StackTrace:    at River.OneMoreAddIn.Commands.UpdateDialog.FormatDate(String value)
   at River.OneMoreAddIn.Commands.UpdateDialog..ctor(IUpdateReport info)
   at River.OneMoreAddIn.Commands.UpdateCommand.<Execute>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.CommandFactory.<Run>d__6.MoveNext()
TargetSite: [River.OneMoreAddIn] River.OneMoreAddIn.Commands.UpdateDialog::FormatDate()

**Comment by stevencohn** [comment]
FYI, batch import will be available in the next release; or you can clone and compile the main branch yourself

**Comment by stevencohn** [comment]
I've added some additional error checking to the suspect code in hopes of more gracefully handling issues but the root cause is still unclear.
