### ISSUE TITLE
Sanitize the logs to remove PID -remove username and computer name at least

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#447]
I am suggesting that the personal data should be removed from the logs
You could put and MD5 hash instead for strings like User name and Computer name

**Comment by stevencohn** [comment]
Removing the three folders reported at startup; these will be reported when dumping diagnostics to the log using the Shift-F8 key.

I don't think I intentionally dump user or machine names anywhere else...?

**Comment by 1001QAdotNET** [comment]
Will check every time I look at the logs 
Also I am not sure if the noebook IDs should be masked because some ppl share the pages or the notebooks with "everyone who has the link" and then the link to the notebook can be guessed from logs or from the XML viewer when shared here
