### ISSUE TITLE
Feature request: More programing languages to syntax highlighting

### ISSUE THREAD

**Issue by yqwu905** [stevencohn/OneMore#452]
I want to insert some cpp code into onenote, but onemore colorize does not support cpp syntax.
Is it possible to add support for cpp syntax highlight? Or even more programing language?

**Comment by stevencohn** [comment]
It is extensible. Colorize with C# for now, that will get you close but I'll look into C++ as well

**Comment by stevencohn** [comment]
Are there other languages you need?

**Comment by yqwu905** [comment]
Well, I still write wolfram language (aka Mathematica).
And great thanks to your work.
