### ISSUE TITLE
Export to Word (.docx) feature

### ISSUE THREAD

**Issue by Peauline** [stevencohn/OneMore#459]
**Describe the bug**

If a file path contains symbols from a non-Latin alphabet (in my case, mostly from the Russian alphabet, which uses Cyrillic characters), 2 bugs occur:

1. When exporting to docx with attachments using OneMore, links to the attachments in the exported file become broken (screenshots 1 and 2). 

2. When exporting rather short pages to docx, using OneMore is fine even if there are non-Latin symbols in the directory name, but if a page is long (more than 20-30 A4 pages) and I use OneMore export feature, along with OneMore window OneNote opens another window showing that OneNote is trying to save something to my temp folder (screenshot 3). A few seconds later OneNote ceases to respond at all. The first time this happened I tried to wait for a while to see if export could be finished and the windows would be closed automatically, but after half an hour nothing happened, so I had nothing to do but to force OneNote to shut down (after the shut-down OneMore shows a window saying export was finished, but in fact the exported file is completely blank). Whenever I try to run OneNote after this happens, OneNote does not open. Instead, there is a window showing that "OneNote is cleaning up from the last time it was open." (screenshot 4). When this bug occurs, I can successfully run OneNote only after I delete everything in my temp folder or use FixOne (http://www.onenotegem.com/a/addins/fix-one.html) to solve the problem. 
This bug is a bit similar to that of Gem for OneNote. Whenever I install some of their add-ins, use it at least once and then close OneNote, OneNote does not open until I delete everything in my temp folder or use FixOne to solve the problem. 

Interestingly, I also noticed that if a file path contains a folder with a Chinese name, only the 1st bug occurs (i. e. I can save my exported file with attachments to a folder with a Chinese name, but the link in the docx file will be broken. If a file path contains letters from a Cyrillic alphabet and a page is rather long, I can neither save it to the selected folder nor open the link in an exported file).

**Environment (if applicable):**
 - OneNote Version: Office 2019, 64bit (版本 2201 Build 16.0.14827.20186)
 - OneMore Version 4.6

**Additional context**
Log file: [OneMore log.txt](https://github.com/stevencohn/OneMore/files/8109357/OneMore.log.txt)

**Screenshots**

1

![Link](https://user-images.githubusercontent.com/99823829/154953279-8f9d4630-1a53-48cc-b2a6-7337746b52c8.jpg)

2

![Word window](https://user-images.githubusercontent.com/99823829/154953299-4d11f90f-35ac-432a-bd21-a0f0e10b4107.png)

3

![2022-02-21_15-07-09](https://user-images.githubusercontent.com/99823829/154953469-9d6cff3f-97f7-4ff9-9a47-7c587e382ee1.png)

4

![2022-02-21_15-03-06](https://user-images.githubusercontent.com/99823829/154953506-9da72c63-0b98-4581-923f-fffa464c72da.png)

**Comment by stevencohn** [comment]
Would it be possible for you to translate the Chinese in these dialogs for me?

Typically when OneNote won't start and displays the "is cleaning up..." message, then either it is still running or the OneMore process is still running.

The OneNote process is easy to find as it's name is always ONENOTE.EXE. 

The OneMore process is run under the name "dllhost.exe" of which there are usually many. To determine the instance that is running OneMore, look in the OneMore log file here: %TEMP%\onemore.log. The process ID is always displayed as the first number of every line in the log

<img width="255" alt="image" src="https://user-images.githubusercontent.com/9964757/154967144-b8685f03-4ac6-4b23-9bfd-78f052889365.png">

**Comment by Peauline** [comment]
Oh, sure, sorry for inconvenience
1 screen - push on CTRL and click on the link to access the file
2 screen - unable to open the file (the button under the message = Ok)
3 screen - saving to... (the button down in the right corner = cancel)
4 screen - Sorry, OneNote is cleaning up from the last time it was open. Please, wait.

As for cleaning up, do you mean that I can try to shut down OneNote / the dllhost of OneMore if this happens again?

**Comment by stevencohn** [comment]
The first case is addressed in release 4.17.

The second case is still under investigation.

**Comment by stevencohn** [comment]
I investigated a bit more after implementing #518, allowing you to export with embedded attachments rather than linked attachments.

This second issue appears to be a problem with Word itself when the path of a linked attachment includes mixed character sets.

It works if you choose to embed the attachment. The caveat here is that the embedded attachment is now no longer associated with an external file at all, and it makes the docx file larger, but that may be OK.

**Comment by stevencohn** [comment]
Not much more I can do.
