### ISSUE TITLE
Feature Request - (per section defaults)

### ISSUE THREAD

**Issue by piyush1908** [stevencohn/OneMore#46]
1. Set default font and size for 
a) entire section 
b) single page in section

2. Show/Hide timestamp for 
a) entire section

3. Remove screen clipping watermark 
(when we use Windows + S, to send to a section, it leaves a, grey coloured screen clipped from text, I need to remove it from all the pages)

Thanks for lovely software

**Comment by stevencohn** [comment]
1. Don't think there is a way to set the default font for a section/page. However, for a page, use custom styles to apply fonts to an existing page. Not great, but better than nothing.

2. Done. Will be available in next release.

3. This is image processing that would involve quite a bit of programming. I'm sure there are image editors out there that can do it much better than I ever could.
