### ISSUE TITLE
OneMore keyboard shortcuts => Collide with defaults in OneNote (german)

### ISSUE THREAD

**Issue by digitalAssetStore** [stevencohn/OneMore#465]
Hi Steven

Many Keyboard shortcuts collide/are the same as in OneNote (german)
- OneMore: Highlight selected text using a rotating array of colors (Ctrl + Shift + H)
  ==> OneNote (de) = highlight
- OneMore: Change selected text to UPPERCASE (Ctrl+Shift+Alt+U), lowercase (Ctrl+Shift+U), Or Title Case
   ==> OneNote (de) = underline

Can you provide a means of changing/adjusting YOUR default OneMore keyboard shortcuts, to not collide with the official MICROSOFT OneNote defaults?

Thanks in advance

**Comment by stevencohn** [comment]
Already done. Open OneMore Settings, go to the Keyboard page and customize all you want!

**Comment by digitalAssetStore** [comment]
Thanks for your update.
Just great!
