### ISSUE TITLE
highlighter is not working consistently

### ISSUE THREAD

**Issue by jdsource** [stevencohn/OneMore#466]
First of all, thank you for a great product. I'm very impressed with your work.

One functionality is very annoying for me as for a heavy user of One Note - the way how the rotation of highlighter work. I find it inconsistent and thus highly annoying as it cause me more clicks to get expected behaviour.

Pls check the screen below:
![image](https://user-images.githubusercontent.com/41386759/156922288-964836df-7bf1-4f5c-bb1f-227d63e63611.png)

After moving the cursor the highlighter should reset and start from the first color. Howevery it's not the case.

Also, it would be good if the color of highlighter button is changing so i know which color I will be using now.
![image](https://user-images.githubusercontent.com/41386759/156922372-1ef5f367-def9-4ddb-89ea-2866b2db4ca0.png)

Happy to provide any further clarifications if needed.

Finally, It would be good to have an option in settings to recover the original way of working for highlighter.

**Comment by stevencohn** [comment]
The rotating highlighter is designed to work in side-by-side with the built-in OneNote highlighter, not repalce it. It rotates through yellow-cyan-pink-blue. It does this per-page and is intended to make it easier to separate contiguous text as shown here:

<img width="404" alt="image" src="https://user-images.githubusercontent.com/9964757/156924238-30b392eb-3274-4f79-9dfa-631840385f5e.png">

so resetting it whenever you move the cursor defeats the purpose of the command. The built-in OneNote highlighter does exactly what you're describing by staying at a specific color.

I will check whether I can change the command icon to indicate the current color (or next color?). The OneNote API is sometimes limiting especially regarding dynamically updating the ribbon so this may not be possible.

**Comment by jdsource** [comment]
ok, makes sense but how to use standard OneNote highligter? The shortcut "Ctrl+Shift+H" is taken by the _Rotator_. Can I use different shortcuts for both types of highlighters?

**Comment by stevencohn** [comment]
Ctrl-Alt-H is the standard keyboard shortcut for the highlighter in OneNote

**Comment by stevencohn** [comment]
You may be interested in this as well...

1. Open OneMore settings
2. Click Favorites in the list on the left
3. Enable the checkbox Include reference to keyboad shortcuts page
4. Click OK
5. Open the OneMore Favorites menu and choose OneNote keyboard shortcuts.

This will create a page in the current section showing the default OneNote and OneMore keyboard shortcuts. This page is created only once so the next time you reference this favorite, it jumps back to the same command.

**Comment by jdsource** [comment]
Oh, so then it's perfect :) Thx a lot for the explanations. I'm crossing my fingers for next updates!
