### ISSUE TITLE
Straight highlight of text (ideal also for underline/bold/text-color)

### ISSUE THREAD

**Issue by digitalAssetStore** [stevencohn/OneMore#467]
FEATURE: Straight highlight of text like in MS Word
* Click/Enable "Highlight text" symbol in ribbon
* Can then mark several times text that gets highlighted

e.g. In OneMore menu at position: OneMore\Edit\Straight Highlighter

Would be ESSENTIAL to speed up highlighting long texts.
Nearly every serious editing app/program has such a feature!

Thanks in advance!

PS: Ideal to have this later also for underline/bold/text-color.

**Comment by stevencohn** [comment]
The OneNote API doesn't provide mouse event handling like this. All commands have to be invoked via the menu or keyboard shortcuts.

OneNote does let you select multiple spans of text (provided they're in different paragraphs) and then applying a style to them all. This works with the OneMore custom character-specific styles as well.

(Note, responding to mouse events and similar dynamic responsiveness can be done but affects performance and your experience using OneNote in general so I've specifically avoiding such attempts. This can be seen in other addins that react dynamically as you type; the performance is visibly sluggish.)

**Comment by digitalAssetStore** [comment]
Thanks for the fast answer.

The current implementation makes highlighting/bolding/underlining long text extremely time consuming, nealry useless.
(e.g. The following MS apps even doing it exaclty as I proposed to be faster: OneNote WebClipper, MS Edge with PDF, Word, Excel, PowerPoint, Outlook ).

Do you have a C# code sample how to implement it? Maybe I give it a try.

**Comment by stevencohn** [comment]
This is the implementation of my rotating highlighter to give you an idea
https://github.com/stevencohn/OneMore/blob/main/OneMore/Commands/Edit/HighlightCommand.cs

Note that that command itself looks simple but there is a ton of code behind that, starting with the Page.EditSelected method

**Comment by digitalAssetStore** [comment]
Thanks!
