### ISSUE TITLE
Menu description truncated or removed

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#47]
I don't think I have done anything special to get this
https://i.imgur.com/C1FHhqq.png
I was working with OneNote 2013 on some materials and when I wanted to use the indentation based on tags option I got the above
Restarting OneNote fixed the issue

**Comment by stevencohn** [comment]
What default language is your machine set to?

**Comment by 1001QAdotNET** [comment]
English but I do switch the keybord to a code page/layout/key mapping that I customized and for which I replaced some of the standard keys with some custom characters that I insert in my text 
I did not pay attention to see if that caused the issue
Switching the keybord to something that does not seem to trigger that... not sure what was the situation when it happened

**Comment by stevencohn** [comment]
Unfortunately, I believe this is when the COM addin fails for some reason and OneNote doesn't know how to reload it. There is no event I can monitor that tells me that it has failed either. The only way to resolve it is to restart OneNote. 

So the best course of action is try to recognize what was happening when you see a COM failure dialog box and I'll do my best to reproduce it and fix it in the addin.

**Comment by 1001QAdotNET** [comment]
Don't worry about it it happens once in a blue moon, I think I have seen that two or three times since I started using OneMore
Just focus on pushing out the next version :-) I do need that indentation fix

**Comment by stevencohn** [comment]
closing this for now
