### ISSUE TITLE
Insert Relative link for file and path on disk. Feature request ^v^

### ISSUE THREAD

**Issue by yyangdid** [stevencohn/OneMore#470]
**Is your feature request related to a problem? Please describe.**
Insert Relative link for file and path on disk.

**Describe the solution you'd like**
The default storage location of my notebook is set to `D:\OneNote\Notes`, 
I have many large and small files stored in `D:\OneNote\Videos\` or `D:\OneNote\Music\` or `D:\OneNote\Others\` and more.

Now, I just can insert link use Ctrl+k, it's absolute link.

When I move `D:\OneNote` to `E:\OneNote` or `D:\Work\OneNote`, all links fail.

So, if I can insert relative link, relative to notebook, then I can move my directory at will.

And thank you for this very nice software. 👍

**Comment by stevencohn** [comment]
OneNote does not allow relative file attachments like that because it actually manages a copy of all attachments in its own cache directory. When you open an attachment, it's actually opening that copy in the cache, not the original.

Here's an example of how an attachment is described on a page natively:

```xml
<one:InsertedFile
   pathCache="C:\Users\steve\AppData\Local\Microsoft\OneNote\16.0\cache\00000BAI.bin"
   pathSource="C:\Users\steve\Downloads\Proficiency Masterclass.docx"
   preferredName="Proficiency Masterclass.docx" />
```

An alternative might be to add a command that "re-roots" all attachments, replacing a given root path like "C:\OneNote\Notes" with "E:\OneNote\Notes"... or in this case just replacing "C:\" with "E:\" !!

**Comment by yyangdid** [comment]
I mean, insert a file or path link, just like http link, not file attachments. 

![1](https://user-images.githubusercontent.com/10922667/157240424-df537190-8f72-47e3-b83f-6ad3e4a34977.png)
![2](https://user-images.githubusercontent.com/10922667/157240452-060317c8-4e73-4f0b-b117-b1b0f47da880.png)
![3](https://user-images.githubusercontent.com/10922667/157240458-b68e38b0-61f6-48e6-95bb-4b694af716af.png)

When I click the link to open this file in OneNote, I can edit and save this file, just like open it from Explorer.

This method is more flexible than using attachments, I can management and edit my file, and when I open and edit the file directly from Explorer, I can see that the file modification is consistent from OneNote.

The file attachments do not achieve this effect.

**Comment by stevencohn** [comment]
Sorry I missed the Ctrl-K part!

Unfortunately, no. OneNote doesn't like relative paths here either. In fact, it requires an absolute URL. In this case, it would look similar to

```xml
<one:T selected="all">
  <![CDATA[<a href="file://C:/Users/steve/Downloads/Complex.docx">Complex</a>]]>
</one:T>
```

It may be possible to add a OneMore command that changes all absolute references on a page but let me think about it

**Comment by yyangdid** [comment]
Thank you.

**Comment by stevencohn** [comment]
I think this is the same as using the build-in command Open Original as shown here

<img width="144" alt="image" src="https://user-images.githubusercontent.com/9964757/174312417-c063515a-3214-4801-98c9-f813d5f4f8aa.png">
