### ISSUE TITLE
This is amazing!

### ISSUE THREAD

**Issue by SmartBoy84** [stevencohn/OneMore#472]
This is an amazing project, my guy! 
The amount of effort put into creating a free product that could easily be sold and willingly bought for a decent sum of money is admirable. I wish I could donate but I'm currently too young for a credit card, so hopefully, my praise is sufficient to show how my love.

I wanted to inquire about what would happen if I was to uninstall the add on. Does it include any features that once used are only displayed on the page if the extension is installed? Like excel spreadsheets for example (if that is a thing).
If so, do I risk data loss by deleting the extension?

Edit: Heck, this should've been tagged a question - sorry!

**Comment by stevencohn** [comment]
Hi. Thanks for the comments.

No, you wouldn't lose anything if you uninstall the addin.

**Comment by SmartBoy84** [comment]
Ok, cool!
