### ISSUE TITLE
Image wrapping

### ISSUE THREAD

**Issue by SmartBoy84** [stevencohn/OneMore#473]
**Describe the solution you'd like**
I would like for something similar to text wrapping around images in other office apps

**Describe alternatives you've considered**
Currently, I use a crude method of placing the image and text in a table in order to get them to appear beside each other in the same text box.

**Comment by stevencohn** [comment]
Unfortunately, this is not allowed in OneNote

**Comment by SmartBoy84** [comment]
Unfortunate :(
