### ISSUE TITLE
Is the Remove spacing supposed to remove the space between lines in this page ?

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#475]
My expectation is that the `Remove spacing` command should help exactly in situations like below
I selected everything and I clicked on Remove spacing but nothing happened 

`<one:Page xmlns:one="http://schemas.microsoft.com/office/onenote/2013/onenote" ID="{xxxxxxxxxxxx}" name="4 Concurrent web requests" dateTime="2022-03-13T05:17:22.000Z" lastModifiedTime="2022-03-13T05:18:45.000Z" pageLevel="1" isCurrentlyViewed="true" selected="partial" lang="en-US">
  <one:QuickStyleDef index="0" name="PageTitle" fontColor="automatic" highlightColor="automatic" font="Calibri Light" fontSize="20.0" spaceBefore="0.0" spaceAfter="0.0" />
  <one:QuickStyleDef index="1" name="p" fontColor="automatic" highlightColor="automatic" font="Calibri" fontSize="10.0" spaceBefore="0.0" spaceAfter="0.0" />
  <one:PageSettings RTL="false" color="automatic">
    <one:PageSize>
      <one:Automatic />
    </one:PageSize>
    <one:RuleLines visible="false" />
  </one:PageSettings>
  <one:Title lang="en-US">
    <one:OE alignment="left" quickStyleIndex="0">
      <one:T><![CDATA[]]></one:T>
    </one:OE>
  </one:Title>
  <one:Outline selected="partial">
    <one:Position x="36.0" y="86.4000015258789" z="0" />
    <one:Size width="254.7500152587891" height="378.4173278808594" />
    <one:OEChildren selected="partial">
      <one:OE alignment="left" quickStyleIndex="1" selected="partial">
        <one:T selected="all"><![CDATA[4 Concurrent web requests]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="1" selected="partial">
        <one:T selected="all"><![CDATA[]]></one:T>
        <one:OEChildren selected="partial">
          <one:OE alignment="left" quickStyleIndex="1" selected="partial">
            <one:T selected="all"><![CDATA[4.1 Introducing aiohttp]]></one:T>
          </one:OE>
          <one:OE alignment="left" quickStyleIndex="1" selected="partial">
            <one:T selected="all"><![CDATA[]]></one:T>
          </one:OE>
          <one:OE alignment="left" quickStyleIndex="1" selected="partial">
            <one:T selected="all"><![CDATA[4.2 Asynchronous context managers]]></one:T>
          </one:OE>
          <one:OE alignment="left" quickStyleIndex="1" selected="partial">
            <one:T selected="all"><![CDATA[]]></one:T>
            <one:OEChildren selected="partial">
              <one:OE alignment="left" quickStyleIndex="1" selected="partial">
                <one:T selected="all"><![CDATA[Making a web request with aiohttp]]></one:T>
              </one:OE>
              <one:OE alignment="left" quickStyleIndex="1" selected="partial">
                <one:T selected="all"><![CDATA[]]></one:T>
              </one:OE>
              <one:OE alignment="left" quickStyleIndex="1" selected="partial">
                <one:T selected="all"><![CDATA[Setting timeouts with aiohttp]]></one:T>
              </one:OE>
            </one:OEChildren>
          </one:OE>
          <one:OE alignment="left" quickStyleIndex="1" selected="partial">
            <one:T selected="all"><![CDATA[]]></one:T>
          </one:OE>
          <one:OE alignment="left" quickStyleIndex="1" selected="partial">
            <one:T selected="all"><![CDATA[4.3 Running tasks concurrently, revisited]]></one:T>
          </one:OE>
          <one:OE alignment="left" quickStyleIndex="1" selected="partial">
            <one:T selected="all"><![CDATA[]]></one:T>
          </one:OE>
          <one:OE alignment="left" quickStyleIndex="1" selected="partial">
            <one:T selected="all"><![CDATA[4.4 Running requests concurrently with gather]]></one:T>
          </one:OE>
          <one:OE alignment="left" quickStyleIndex="1" selected="partial">
            <one:T selected="all"><![CDATA[]]></one:T>
            <one:OEChildren selected="partial">
              <one:OE alignment="left" quickStyleIndex="1" selected="partial">
                <one:T selected="all"><![CDATA[Handling exceptions with gather]]></one:T>
              </one:OE>
            </one:OEChildren>
          </one:OE>
          <one:OE alignment="left" quickStyleIndex="1" selected="partial">
            <one:T selected="all"><![CDATA[]]></one:T>
          </one:OE>
          <one:OE alignment="left" quickStyleIndex="1" selected="partial">
            <one:T selected="all"><![CDATA[4.5 Processing requests as they complete]]></one:T>
          </one:OE>
          <one:OE alignment="left" quickStyleIndex="1" selected="partial">
            <one:T selected="all"><![CDATA[]]></one:T>
            <one:OEChildren selected="partial">
              <one:OE alignment="left" quickStyleIndex="1" selected="partial">
                <one:T selected="all"><![CDATA[Timeouts with as_completed]]></one:T>
              </one:OE>
            </one:OEChildren>
          </one:OE>
          <one:OE alignment="left" quickStyleIndex="1" selected="partial">
            <one:T selected="all"><![CDATA[]]></one:T>
          </one:OE>
          <one:OE alignment="left" quickStyleIndex="1" selected="partial">
            <one:T selected="all"><![CDATA[4.6 Finer-grained control with wait]]></one:T>
            <one:OEChildren selected="partial">
              <one:OE alignment="left" quickStyleIndex="1" selected="partial">
                <one:T selected="all"><![CDATA[]]></one:T>
              </one:OE>
              <one:OE alignment="left" quickStyleIndex="1" selected="partial">
                <one:T selected="all"><![CDATA[Waiting for all tasks to complete]]></one:T>
              </one:OE>
              <one:OE alignment="left" quickStyleIndex="1" selected="partial">
                <one:T selected="all"><![CDATA[]]></one:T>
              </one:OE>
              <one:OE alignment="left" quickStyleIndex="1" selected="partial">
                <one:T selected="all"><![CDATA[Watching for exceptions]]></one:T>
              </one:OE>
              <one:OE alignment="left" quickStyleIndex="1" selected="partial">
                <one:T selected="all"><![CDATA[]]></one:T>
              </one:OE>
              <one:OE alignment="left" quickStyleIndex="1" selected="partial">
                <one:T selected="all"><![CDATA[Processing results as they complete]]></one:T>
              </one:OE>
              <one:OE alignment="left" quickStyleIndex="1" selected="partial">
                <one:T selected="all"><![CDATA[]]></one:T>
              </one:OE>
              <one:OE alignment="left" quickStyleIndex="1" selected="partial">
                <one:T selected="all"><![CDATA[Handling timeouts]]></one:T>
              </one:OE>
              <one:OE alignment="left" quickStyleIndex="1" selected="partial">
                <one:T selected="all"><![CDATA[]]></one:T>
              </one:OE>
              <one:OE alignment="left" quickStyleIndex="1" selected="partial">
                <one:T selected="all"><![CDATA[Why wrap everything in a task?]]></one:T>
              </one:OE>
            </one:OEChildren>
          </one:OE>
        </one:OEChildren>
      </one:OE>
    </one:OEChildren>
  </one:Outline>
</one:Page>`

**Comment by 1001QAdotNET** [comment]
I suspect I know why this is happening, there are some "space" characters on those lines
I guess this command needs one more option: remove lines with spaces or tabs only

**Comment by stevencohn** [comment]
There are two different commands. 

- **Remove paragraph spacing**, the command you mention, will remove extra margin space applied to all selected paragraphs. This clears the adjustment made by the built-in OneNote _Paragraph Spacing Options_ command.

- **Remove empty paragraph and headers** will remove _extra_ empty lines between paragraph, preferring to leave one standard blank line between paragraphs. This works regardless of whether these lines contain whitespace characters.

**Comment by 1001QAdotNET** [comment]
True, but none of them seem to care about my empty lines :-)

**Comment by stevencohn** [comment]
The XML you provided has single empty lines in between paragraphs. OneMore does not remove ALL empty lines between paragraphs; it will replace _multiple empty lines_ with a single empty line in between paragraphs.

**Comment by 1001QAdotNET** [comment]
Hmm that is bad for me. 
Any change we could add that option (remove empty lines)?
I am going to open a feature request

**Comment by stevencohn** [comment]
addressed by #477, closing this pending new release
