### ISSUE TITLE
Select text with similar formatting does not seem to work

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#476]
It always says that the focus must be on the body of the page (which is probably not because you must click on the button to run the command)

**Comment by stevencohn** [comment]
There is a known problem (known by me at least) where this command doesn't recognize that you're on a hyperlink. Is that the case here? 

Otherwise, I do believe the command works fine.

**Comment by 1001QAdotNET** [comment]
No that is not the case
You can see it in action [here](https://imgur.com/a/2b9SL2k)

**Comment by stevencohn** [comment]
You cannot select a region of text. You must place the cursor in one spot over the style you want to choose.

**Comment by 1001QAdotNET** [comment]
OK I will try that
this could be added to the message shown in the above animated gif.

**Comment by stevencohn** [comment]
Changed warning message
