### ISSUE TITLE
Add the option indent empty lines to the same level as the previous non empty line

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#478]
I like to organize my text by collapsible paragraphs
When importing content some times the empty lines that delimit the paragraphs that do not have heading by themselves. 
These paragraphs, if indented properly they should collapse under the first heading above them
Very often the imported empty lines are not indented with the text of the paragraph above them and this requires manual work

Would it be possible to add such an option to the Clean group of commands ?
Option: Indent empty lines like the previous paragraph

**Comment by stevencohn** [comment]
This is already built into the Remove Empty Paragraphs command. As it removes duplicate empty lines, it also aligns the remaining empty lines with the previous paragraph so they can be collapsed together.
