### ISSUE TITLE
Feature request-implement the option to add one or any arbitrary number of  OneMore commands to the context menu

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#48]
Hi Steven

Is it possible to implement the option to add one or an arbitrary number of OneMore commands to the context menu (the menu that shows up when you select text and right click) 

I dealy it would be nice to have a custom field there and you could select any of the ribbon or quick access bar buttons/commands that could be added there (in my case Paragrah spacing or remove Paragraph or Line spacing)

This will minimize the actions the user has to take in order to do certain things with a selected text. Currently you need to select the text and then to go to the OneMore ribbon or to use the quick access bar for that

**Comment by stevencohn** [comment]
Yes I think it is possible. It would require a restart to update the context menu whenever you made a change but it is possible....

**Comment by 1001QAdotNET** [comment]
Great thank you. Please let us know if we should stop coming up with these, I know that at some point this could become annoying :-)

**Comment by stevencohn** [comment]
Prototype context menu with hard-coded entries for now, available https://github.com/stevencohn/OneMore/releases/latest

**Comment by 1001QAdotNET** [comment]
Wow   thank you again I hope it was not difficult or time consumming....

**Comment by 1001QAdotNET** [comment]
HI Steve

I had a quick look at this and here is my user feedback. Of course it will be up to you do decide how it is better
-having a nested option there defeats the purpose, you need two clicks to get to the tool you want -in my case **Clean** and  then **Remove pragrah spacing**   If this stays like this it is more convenient to reach to the Quick access bar icon where I currently have the icon for this,  The idea is to make the workflow fluid and have the reader take his eyes from the paragraph as little as possible.

-this is a nice to have but from what I red it is not possible as far as I remember. When you select thext in one not an automatic context menu shows up allowing you formatting and adding some tags . It would be nice if we could customize that and add the above to that one ... 

You did add the option where I initially suggested, thank you. This above comment is a suggestion for an improvement

**Comment by stevencohn** [comment]
Sure I have no problem with the first.

Regarding the nice-to-have, I'm not sure I understand what you wrote. Can you expand upon it a little more?

**Comment by 1001QAdotNET** [comment]
yes I am referring to this context menu that shows up instantly and automatically as soon as you select the text 
(it does not require a right click)
https://i.imgur.com/vJXItSs.png

**Comment by stevencohn** [comment]
Oh. There's no API to change that. :-(

**Comment by 1001QAdotNET** [comment]
yes I remember reading somewhere that it is impossible to change that

**Comment by stevencohn** [comment]
Done 
https://github.com/stevencohn/OneMore/releases/tag/3.6
