### ISSUE TITLE
Glitch when collapsing outline 

### ISSUE THREAD

**Issue by SmartBoy84** [stevencohn/OneMore#483]
Allow excluding certain parts of the page from being collapsed when page > collapse outlining is clicked.

**Comment by stevencohn** [comment]
That's basically what the _Save Collapsed Outline_ and _Restore Collapsed Outline_ commands do. First, manually expand and collapse sections of the page as you desire. Then use the Save command to remember this state. When you use the Restore command, it will expand and collapse sections to that saved configuration.

If I were to interpret your request literally, there would need to be some way of tagging sections as "collapse" or "don't collapse" and that would be unnecessarily complex and get messy quickly I think.

**Comment by SmartBoy84** [comment]
I agree, I didn't see those options - thanks.

Another glitch in regards to collapsing outlining is that it failed to do so if one of the "children" is an image or if the parent is an image.

**Comment by stevencohn** [comment]
Images should collapse OK if they are indented from the header or paragraph above

**Comment by SmartBoy84** [comment]
Yes, but if they are the parent object (below which other text is indented) then collapsing doesn't work.
Can you test to see if it works for you when a paragraph contains an image?

**Comment by stevencohn** [comment]
> Yes, but if they are the parent object (below which other text is indented) then collapsing doesn't work. Can you test to see if it works for you when a paragraph contains an image?

OneNote does not allow collapsing indented content below an image.
