### ISSUE TITLE
Quick Action menu like Outlook - move page

### ISSUE THREAD

**Issue by rcheli32** [stevencohn/OneMore#484]
**Is your feature request related to a problem? Please describe.**
Drag and drop is too slow/hard with really big OneNote sections

**Describe the solution you'd like**
A button on the ribbon that when clicked will move the current page to a different section the user has chosen, without any further clicks or prompts.

**Describe alternatives you've considered**
I've looked at another add in but it was too complex and seemed to lack page move options.

**Additional context**

THE FINE PRINT
This is a hobby project that I started for myself. I'm happy to take requests and will promise to consider each one carefully but offer no guarantees that I will ultimately agree to their usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
Let me make sure I understand your request. Do you want to move an entire section (to another notebook or section group) or just a page within the section to another section?

Did you know you can right-click on a page (or even on a section) and choose Move or Copy... ?

This is a built-in OneNote command.

**Comment by rcheli32** [comment]
It is like the right click option to move a page to a new section, just looking for minimum clicks.... But I'll take a look at the right click menu.

**Comment by rcheli32** [comment]
I tried out the right click menu, the problem being that you still have to choose a target section (among the many I have), plus then it is really slow to do the move. We probably can't do anything about the speed of the move, but we should be able to eliminate the target prompt if the person is like me and always has a "done" section they move meeting notes to.
