### ISSUE TITLE
Multiline C++ comments fail to highlight correctly

### ISSUE THREAD

**Issue by akshaykhadse** [stevencohn/OneMore#486]
**Issue**
Multiline C++ comments fail to color correctly because of keywords 'and' and 'this'. Text post these words is black instead of green. Not sure if there are more. See the following
![onemore](https://user-images.githubusercontent.com/18427356/161194961-57fe6712-65e8-467d-9498-0a2880879b95.jpg)

**To Reproduce**
1. Write C++ code that has more than 5 lines of multiline comment. Make sure that your comment uses the word 'and'.
2. Click on OneMore > Edit > Colorize > C++
3. See that the text after first 'and' is not colored.
4. This behavior happens for all 'and' and 'this' words in the comment text. Perhaps some issue with the lexer.

**Expected behavior**
All comment text should be green. See below:
![pygments](https://user-images.githubusercontent.com/18427356/161195085-c8c512fc-9c74-4778-85be-43af16de05b5.jpg)

**Environment (if applicable):**
 - OneNote Version: Office 365 64bit
 - OneMore Version: 4.17

**Comment by stevencohn** [comment]
#487 asked: how does colorizing work in OneMore?

Each language is defined by is its [own file here](https://github.com/stevencohn/OneMore/tree/main/OneMore/Colorizer/Languages). C++ multiline comments are [defined here](https://github.com/stevencohn/OneMore/blob/ddde1f2b54eec7a1dd94e22f2dd00ba140690e6e/OneMore/Colorizer/Languages/cpp.json#L22).

These files are used by the Parser class implemented in Colorizer/Parser.cs. The current scope (state) is maintained using the language.Scopes array and the scopeOverride local variable. These are passed back to the caller's report Action which maps to a color by the language Theme. The scopeOverride _should_ track scopes across multiple lines. Apparently, this is where the bug exists...
