### ISSUE TITLE
I noticed that the replacement function only support regular expressions in find box but not in replace box . Am I doing something wrong?

### ISSUE THREAD

**Issue by Amikacin666** [stevencohn/OneMore#488]
I noticed that the replacement function does not support regular expressions in the "replace with" box. Am I doing something wrong?

**Comment by stevencohn** [comment]
No that's exactly right. You can search on a regular expression but need to add a fixed replacement string.

There is a ticket here about enhancing the functionality https://github.com/stevencohn/OneMore/issues/233

I'll close this one as a "duplicate" of that.
