### ISSUE TITLE
Screen Clipping

### ISSUE THREAD

**Issue by piyush1908** [stevencohn/OneMore#49]
![image](https://user-images.githubusercontent.com/12750186/93822532-fb924480-fc7d-11ea-8c0f-d01bac547880.png)

Sir thankyou for timestamp
Please can you give function to remove screen clipping also + Print without page numbers (My paper is next sunday,lots of printout needed)

**Comment by stevencohn** [comment]
1. OneNote uses the Citation style for screen clipping reference (and the "From URL" references when pasting from a Web browser), so I can add an option to remove citations from a page that contain the word "clipping" or are of the form "From: URL"

2. I can't control the print output at all, so not possible.

Good luck on your paper!

**Comment by stevencohn** [comment]
Remove Citations command available in release 2.14

**Comment by piyush1908** [comment]
Sir you've such a warm personality, I really love the way you respond, It
feels like I'm talking to someone I know :), Thankyou for wishes.
