### ISSUE TITLE
Auto-resizing

### ISSUE THREAD

**Issue by SmartBoy84** [stevencohn/OneMore#490]
OneNote autoresizes page containers on different viewports by default however this no longer occurs once it has been manually resized.
I assume this is a simple tag in the XML so it shouldn't be that difficult to implement an option which resets this property after a container has been resized?

**Comment by SmartBoy84** [comment]
It seems to be
`    <one:PageSize>
      <one:Automatic />
    </one:PageSize>`
this tage.
Can you add an option which recursively goes through the pages of a notebook and adds this tag?

**Comment by stevencohn** [comment]
Unfortunately no. Even using the API, OneNote doesn't let you remove the one:Size element, remove the isSetByUser attribute, or change the value of that attribute to false. 

You can prove this by using OneMore's Show XML command, untick the two checkboxes, edit, and click OK

<img width="211" alt="image" src="https://user-images.githubusercontent.com/9964757/162615720-046232f4-1018-449f-b6c2-28cadc8f9223.png">

**Comment by SmartBoy84** [comment]
Would it not be possible to make another "container" with the same dimensions, copy the text to that new container and move it in place of the old container?

**Comment by stevencohn** [comment]
What's the use case? Why are you interested in this?

**Comment by SmartBoy84** [comment]
> What's the use case? Why are you interested in this?

For **many** of my pages I've accidentally resized the container so it no longer automatically resizes according to screen size
This makes it difficult to review notes on mobile

**Comment by stevencohn** [comment]
I take it back. I can remove the isSetByUser attribute.

OneNote doesn't let you remove it unless the width and height values have changed; so they just need to be altered by _any_ amount and voila. I'll change this to "enhancement"

**Comment by SmartBoy84** [comment]
Weird, should I be able to remove it via your XML editor? Also, is removing it enough to return it to its auto-resizable state?

**Comment by stevencohn** [comment]
That's how I was able to discover it.
And yes, OneNote should redraw it properly from there.

**Comment by SmartBoy84** [comment]
In the meanwhile, I've found a hacky solution to resize the box without ruining dynamic resize as well.
If you make a single-celled table then you can freely resize it which, when nearing the box's bounds, also resizes the box's width.
