### ISSUE TITLE
Auto paragraph spacing? 

### ISSUE THREAD

**Issue by SmartBoy84** [stevencohn/OneMore#491]
Sorry for bombarding you with feature requests, questions and issues.

Is it possible to implement a function which increases paragraph spacing for every page of a notebook?

For example,
![image](https://user-images.githubusercontent.com/12468102/162740630-17c198e7-330b-4875-9583-672bb709dbc1.png)
this would so, so much easier to digest at a glance if the paragraphs were spaced a bit better. It seems I can't set a default paragraph spacing so for now I have to manually go through each page and set the spacing myself.

**Comment by stevencohn** [comment]
OneMore has a plugin feature that could theoretically support a batch utility like _that other_ addin. This may be something I entertain in the future.

Oh, and please keep the questions and suggestions coming!
