### ISSUE TITLE
List collapse state not persisting?

### ISSUE THREAD

**Issue by SmartBoy84** [stevencohn/OneMore#492]
For some reason the onenote developers (fairly it seems) [decided](https://answers.microsoft.com/en-us/msoffice/forum/all/onenote-2013-doesnt-remember-outline-collapsed-and/481d0d5f-f3d1-4159-a0eb-f15cf8f61270) not to make the content collapse state persistent.
However, as per the article I've linked above, collapsing the content and then adding a letter to the page somewhere and then removing it is enough to make the collapsed state persist.

Could you check to see if this is state which can be forcibly enabled without having to do this weird trick for every page?

**Comment by stevencohn** [comment]
This is the purpose of OneMore's Page/_Saved Collapsed Outline_ and _Restore Collapsed Outline_ commands.
