### ISSUE TITLE
Installer Issue - OneNote 2016 + OneMore 4.1.7

### ISSUE THREAD

**Issue by tjcst** [stevencohn/OneMore#493]
**Describe the bug**
I am having an issue installing the 64-bit version of this plug-in. I previously had two versions of OneNote installed in tandem by accident (one was 2016, I believe the other was O365) and I was able to install OneMore to the O365 version. It worked fine I have since uninstalled that version and am strictly going to be using the Office 2016 version but I cannot get OneMore installed for it.

I have attempted to troubleshoot this issue on my own for a couple of days, including checking for excess files leftover from old install or any reg keys, but have had no luck. The logs seem to indicate it is failing during EdgeWebViewAction install and I have tried to address that too with no progress. Any help in the right direction would be lovely.

**To Reproduce**
1. Install OneMore_4.1.7_Setupx64.msi
4. Error: There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.

**Screenshots**

**Environment (if applicable):**
 - OneNote Version: Office Professional Plus 2016 - OneNote 2016 (16.0.5014.1000) MSO (16.0.5173.1000) 32-bit
 - OneMore Version: 4.1.7

**Additional context**
Log file has been attached with my username redacted. My user is an admin user.
[OneMoreErrorLog.txt](https://github.com/stevencohn/OneMore/files/8523801/OneMoreErrorLog.txt)
[OneMoreMSILog.txt](https://github.com/stevencohn/OneMore/files/8523817/OneMoreMSILog.txt)

Thank you in advance for your help.

**Comment by stevencohn** [comment]
Which version of Windows is this?

**Comment by DendrocoposMajor** [comment]
I've seen the very same error message. 
I am on Windows 10 Enterprise, 21H2 OS Build 19044.1645
There are two notable entries in the attached logfile, namely lines 24 and 26 both referring to .Net framework.
Some really interesting stuff starts on line 96 continuing to 157.  That group of errors seem to be related to fonts?!#
With that said, there are 1205 lines of logging goodness in the file, hopefully something is useful.
[OneMore-Install_logfile.txt](https://github.com/stevencohn/OneMore/files/8762932/OneMore-Install_logfile.txt)
.

**Comment by valuex** [comment]
I also run into the same problem for V4.1.7 for OneNote 64bit on Win 10 (20H2, 19042.1466)

**Comment by stevencohn** [comment]
Will continue investigation under #458
