### ISSUE TITLE
Onemore Add-in style conflicts with Onenote's own style

### ISSUE THREAD

**Issue by codercplus** [stevencohn/OneMore#496]
**Describe the bug**
When a text already have been applied to a Onenote's own  Style, and then be applied to a OneMore Add-in Style, some unexpected results may occur, such as invalid execution or even errors.

**To Reproduce**
Here are two examples.

(1) Enter text 'H1 title'  in the first line, and then enter text 'a remark' in the same line. Type two paragraphs in the next line.
Select the whole first line and apply it to the system style 'Heading 1'(Ctrl+alt+1). 
Select 'H1 title' and apply it to a style((Temporarily call it Custom style 1) . 
Select 'a remark' and apply it to a style((Temporarily call it Custom style 2) . 
Then apply a OneMore Style(Temporarily call it Custom style 3) only to the brownish-red part. Unexpectedly, after execution, the pink text in the first line  becomes larger. It shouldn't have changed

![动画1](https://user-images.githubusercontent.com/63757163/165480803-20e5136c-ed7d-41f5-9e16-5fce977d44eb.gif)

(2) Then I select the pink text that has been changed by mistake, and applie it  to OneMore's Style 'Intense Emphasise'.Unexpectedly, the result is wrong again.——Because the font size of 'Intense Emphasise' Style is 11, but the  execution result is 16, as large as System's style Heading one.  

![动画2](https://user-images.githubusercontent.com/63757163/165481187-4a527bcb-b95b-43df-b9b6-3a5a3af0c9f4.gif)

----------
All styles details I mentioned below:
Heading 1(from Onenote) :     font-size:16pt      color:dark blue.
Custom Style 1 (from OneMore):    font-size:26pt    color:blue    Style-type:character
Custom Style 2 (from OneMore):    font-size:11pt    color:pink    Style-type:character
Custom Style 3 (from OneMore):    font-size:11pt    color:black    Style-type:paragraph
Intense Emphasise(from OneMore):    font-size:11pt     Style-type:character

**Environment (if applicable):**
 - OneNote Version: O365, 64bit
 - OneMore Version : 4.17

**Additional context**
OneMore.log
[OneMore.log](https://github.com/stevencohn/OneMore/files/8570505/OneMore.log)

**Comment by stevencohn** [comment]
I can't seem to reproduce this. I do know that some times a soft-break (using shift-enter instead of enter) will cause funny things to happen when you apply a style. But this doesn't seem to be the case.

The log errors look unrelated to this and can be caused by timeout interactions with the OneNote COM APIs.

I'll keep looking though

**Comment by codercplus** [comment]
> I can't seem to reproduce this. I do know that some times a soft-break (using shift-enter instead of enter) will cause funny things to happen when you apply a style. But this doesn't seem to be the case.
> 
> The log errors look unrelated to this and can be caused by timeout interactions with the OneNote COM APIs.
> 
> I'll keep looking though

Hello, I Re-uploaded a more detailed animation. I hope it can help confirm the problem.
By the way , I did not use any soft-break (shift-enter).
![animition](https://user-images.githubusercontent.com/63757163/166104656-fe51edd3-6398-4092-8f16-f4f411c1fc4b.gif)
