### ISSUE TITLE
Allow the user to change the OneMore Shortcuts

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#504]
Not sure if I am missing this and it is already there but if this is not it would be great to have it
Reason: while reading I use the mouse to navigate and select, I use the left hand to perform actions on the selected text
Some of the shortcuts I use require some contortionism skills in order to use them with a single hand or at most require you to move you body on the chair a little in order to reach the keys you want with one hand
To see what I mean try to use the shortcut for the rotating highlighter (Ctrl+Shift+H) using a single hand

**Comment by stevencohn** [comment]
It's the "Keyboard" page in the settings dialog.

**Comment by 1001QAdotNET** [comment]
Thank you I was looking for "Shortcuts" I thought that could be the Keyboard layout and Code page and all that
