### ISSUE TITLE
Unable to install OneMore addin

### ISSUE THREAD

**Issue by StephenMSmith** [stevencohn/OneMore#505]
I've been trying every release for a few months now but I still can't get OneMore to work within OneNote.  Error is below.  I've followed all the steps on the troubleshooting page -- reinstalling and repairing Office, etc.  I've search through the registry looking for this GUID and just find a few entries w/ProxyStub and TypeLib.  Was hoping to find some file name somewhere that might be the problem.  Any ideas?

16640:1] Starting dllhost 16640, CPU=3600Mhz, en-US/en-US, v4.17, OneNote 15.0, Office 16.0
16640:1] ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.15128.20224)
16640:1] ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
16640:1] ..OneAddInsUpdate(custom[])
16640:1] ..building ribbon
16640:1] ..building ribbon colorizer commands
16640:1] ..OnStartupComplete(custom[])
16640:1] ..error starting add-on
16640:1] ..System.InvalidCastException
Message: Unable to cast COM object of type 'Microsoft.Office.Interop.OneNote.ApplicationClass' to interface type 'Microsoft.Office.Interop.OneNote.IApplicationCOM'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{452AC71A-B655-4967-A208-A4CC39DD7949}' failed due to the following error: Error loading type library/DLL. (Exception from HRESULT: 0x80029C4A (TYPE_E_CANTLOADLIBRARY)).
Source: mscorlib
StackTrace:    at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Office.Interop.OneNote.ApplicationClassCOM.get_Windows()
   at River.OneMoreAddIn.OneNote.get_WindowHandle()
   at River.OneMoreAddIn.AddIn.OnStartupComplete(Array& custom)
TargetSite: [mscorlib] System.StubHelpers.StubHelpers::GetCOMIPFromRCW()

16640:6] OnBeginShutdown(custom[])
16640:6] ..shutting down UI
16640:6] ..OnDisconnection(RemoveMode:ext_dm_HostShutdown,custom:[])
16640:6] ..disposing 1 streams
16640:6] ..closing log

**Comment by stevencohn** [comment]
Will continue investigation under https://github.com/stevencohn/OneMore/issues/458
