### ISSUE TITLE
Add-in crashing Onenote app

### ISSUE THREAD

**Issue by billyray098** [stevencohn/OneMore#506]
This is the first time I've installed the add-in. When I clicked on the "+1 more" option, the app crashed and closed. After a couple of attempts, I was able to see all of the features but after clicking on the add in, I cannot select anything in the app - other options, text, drawings etc. It's making Onenote laggy overall which is something I've never experienced before.

1. Go to Onenote, home tab
2. Click on "onemore" option

**Expected behavior**
App crashes and closes/minimises the window or lags for a few seconds until I'm able to use other features or even scroll down the page

**Environment (if applicable):**
 - OneNote Version:  Office 2021, 64bit
 2204, build 15128.20248

**Comment by stevencohn** [comment]
I know this was a while ago but can you still reproduce this and, if so, please try to share the log %TEMP%\OneMore.log.

**Comment by stevencohn** [comment]
Closing as stale
