### ISSUE TITLE
problems met when importing docx files

### ISSUE THREAD

**Issue by mail4zc** [stevencohn/OneMore#508]
first, thanks a lot for your work to enable us to have such a wonderful add-in.

**Describe the bug**
when i try to import a docx file into onenote, only english words in the file are right , while the chinese characters are all strange symbols. 
Also, it seems that i can only import one docx file a time. Hoping that it can import a batch files. that would be much more convenient and marvellous!
 Thanks again!

**Screenshots**
![image](https://user-images.githubusercontent.com/106293120/170411130-7b9eb980-35d8-4f14-b2bd-0d00a318c226.png)

**Environment (if applicable):**
 - OneNote Version: O365, also 32bi
 - OneMore Version: 4.17

**Comment by mail4zc** [comment]
OS: window 7 -64bi, and Win 10 64bi

**Comment by stevencohn** [comment]
My tests work OK.
Is there an example doc you can attach here that I can try?

**Comment by mail4zc** [comment]
This is the test file. Thanks a lot!

[https://res.cdn.office.net/assets/mail/file-icon/png/docx_16x16.png]test file.docx<https://1drv.ms/w/s!AmCimwKJGYzigRFXxeJaA-Dm69fk>
________________________________
发件人: Steven ***@***.***>
发送时间: 2022年6月26日 0:43
收件人: stevencohn/OneMore ***@***.***>
抄送: mail4zc ***@***.***>; Author ***@***.***>
主题: Re: [stevencohn/OneMore] problems met when importing docx files (Issue #508)


My tests work OK.
Is there an example doc you can attach here that I can try?

―

**Comment by stevencohn** [comment]
I downloaded your test file and imported it without issue, at least the Chinese characters loaded correctly even if the picture wasn't imported. So unfortunately, I still cannot reproduce this.

<img width="275" alt="image" src="https://user-images.githubusercontent.com/9964757/186238157-4f362201-ce81-45a5-a912-9aa08b0d6aab.png">

**Comment by stevencohn** [comment]
No-repro and stale
