### ISSUE TITLE
Won't install, but not like #458 - first time install

### ISSUE THREAD

**Issue by jasonjac2** [stevencohn/OneMore#509]
**Describe the bug**
Installer runs and then ends with: 
![image](https://user-images.githubusercontent.com/68282090/170881015-e67d658d-b261-4bd7-97a9-6caae2be12b9.png)

Thanks for your time.

**To Reproduce**
DL OneMore_4.17_setupx86.msi, 
Close ON
Run the msi.
You get the Welcome, license, location to install, UAC, and it is running the install and then you get the error "There is a problem with this Windows Installer Package. A program run as part of the set up did not finish as expected.  Contact....."
And then it unwinds.

You can see from the log that I ran it twice.

**Expected behavior**
Install to complete :-).

**Screenshots**
![image](https://user-images.githubusercontent.com/68282090/170881015-e67d658d-b261-4bd7-97a9-6caae2be12b9.png)

**Environment (if applicable):**
Microsoft® OneNote® for Microsoft 365 MSO (Version 2205 Build 16.0.15225.20028) 32-bit 
 - OneMore Version  4.17 x86 MSI installer.

**Additional context**
Add any other context about the problem here. Attach page XML file or the app log file as appropriate. You can find the log file here: %localappdata%\temp\OneMore.log
OneMore installer running as user NT AUTHORITY\SYSTEM (S-1-5-18) elevated

Register... version 4.17

ShutdownOneNoteAction.Install ---
ONENOTE process not found

ProtocolHandlerAction.Install ---
step 0: opening HKLM:\Software\Classes\onemore
step 1: creating HKLM:\Software\Classes\onemore
step 2: setting properties of HKLM:\Software\Classes\onemore
step 3: opening HKLM:\Software\Classes\onemore\shell\open\command
step 4: creating HKLM:\Software\Classes\onemore\shell\open\command
step 5: setting properties of HKLM:\Software\Classes\onemore\shell\open\command
verified: key created HKEY_LOCAL_MACHINE\Software\Classes\onemore\shell\open\command

TrustedProtocolAction.Install ---
translating user JAC-PRECISION1\jason to SID
registering trusted protocol for user JAC-PRECISION1\jason (S-1-5-21-<LongNumber Removed>)
defaulting Office version to 16
step 6: opening HKCU:\Software\Policies\Microsoft\Office\16.0\Common\Security\Trusted Protocols\All Applications\onemore:
step 7: creating HKCU:\Software\Policies\Microsoft\Office\16.0\Common\Security\Trusted Protocols\All Applications\onemore:
key created HKEY_USERS\S-1-5-21-<LongNumber Removed>\Software\Policies\Microsoft\Office\16.0\Common\Security\Trusted Protocols\All Applications\onemore:

EdgeWebViewAction.Install ---
WebView2 Runtime is already installed
completed successfully
OneMore installer running as user NT AUTHORITY\SYSTEM (S-1-5-18) elevated

RegistryWowAction.Install --- x64:True
OneNote application path note found; continuing optimistically
deleting CLSID clone
cloning CLSID
OneMore installer running as user NT AUTHORITY\SYSTEM (S-1-5-18) elevated

ActiveSetupAction.Install ---
OneMore installer running as user NT AUTHORITY\SYSTEM (S-1-5-18) elevated

Register... version 4.17

ShutdownOneNoteAction.Install ---
ONENOTE process not found

ProtocolHandlerAction.Install ---
step 0: opening HKLM:\Software\Classes\onemore
step 1: setting properties of HKLM:\Software\Classes\onemore
step 2: opening HKLM:\Software\Classes\onemore\shell\open\command
step 3: setting properties of HKLM:\Software\Classes\onemore\shell\open\command
verified: key created HKEY_LOCAL_MACHINE\Software\Classes\onemore\shell\open\command

TrustedProtocolAction.Install ---
translating user JAC-PRECISION1\jason to SID
registering trusted protocol for user JAC-PRECISION1\jason (S-1-5-21-<LongNumber Removed>)
defaulting Office version to 16
step 4: opening HKCU:\Software\Policies\Microsoft\Office\16.0\Common\Security\Trusted Protocols\All Applications\onemore:
key already exists

EdgeWebViewAction.Install ---
WebView2 Runtime is already installed
completed successfully
OneMore installer running as user NT AUTHORITY\SYSTEM (S-1-5-18) elevated

RegistryWowAction.Install --- x64:True
OneNote application path note found; continuing optimistically
deleting CLSID clone
cloning CLSID
OneMore installer running as user NT AUTHORITY\SYSTEM (S-1-5-18) elevated

ActiveSetupAction.Install ---

**Comment by jasonjac2** [comment]
Checking Event Viewer: Application: OneMoreSetupActions.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at OneMoreSetupActions.ActiveSetupAction.Install()
   at OneMoreSetupActions.Program.Main(System.String[])

and then
Product: OneMoreAddIn -- Error 1722. There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  Action _92AF78F8_2EBA_4DB2_B799_F8741DC7E4C6, location: C:\Program Files (x86)\River\OneMoreAddIn\OneMoreSetupActions.exe, command: --install-activesetup 
...
Windows Installer installed the product. Product Name: OneMoreAddIn. Product Version: 4.17. Product Language: 1033. Manufacturer: River. Installation success or error status: 1603.

**Comment by stevencohn** [comment]
You're right this is not exactly like #458. There are currently two known (although I'm not sure entirely unrelated) installer bugs with OneNote.

The first is that it needs .NET Framework 4.8. This can be overcome by manually installing it first but many users don't know how to do this and I'd like to bake it into the installer when I get time.

The second is the failure you see here and is sometimes related to WebView2, whether pre-installed or not. But I have very limited data to demonstrate what's going wrong.  Again, I'm hoping life lets me get back to this soon so I can solve these issues.

**Comment by jasonjac2** [comment]
Looks like I don't have the correct .net version.
![image](https://user-images.githubusercontent.com/68282090/170936588-6afe94e6-8f38-4224-bfcf-91c03f47db80.png)
 ok, so I'll DL 4.8 and install and see if that helps.

**Comment by jasonjac2** [comment]
Is this usual though?
![image](https://user-images.githubusercontent.com/68282090/170937464-266632d7-3e64-4b28-a6b6-448c3193f3b2.png)

**Comment by jasonjac2** [comment]
Is there anything else I can help with, procmon, sysinternals, eventlog?

**Comment by jasonjac2** [comment]
Do you have manual instructions to install?  I am going to install on another machine with a fresh copy of OneNote Desktop - do you recommend 32 or 64 bit (I normally install 32 office).
