### ISSUE TITLE
Feature request: Add the option to add tags like attributes to any artbitrary selected piece of text

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#51]
The tag feature is great in OneNote
Unfortunately it can be added to paragraphs only <p>
Would it be possible for you to implement the option to select text and add an attribute to the selected text?  
There is a surrogate solution for this by using background colors but then you need one more step to map the color to a certain tag, it is a little bit convoluted and not very flexible

Related to the above -this could be implemented with the new plugin option IF the OneMore end could also pass as a second parameter the selected text. Not sure how that cab be done.  After that the plugin I would write would look for that fragment in the file and I would process it myself. 
Probably a creative way to do that is to mark the text with a designated color -that would create a <span> with that specific color as attribute -assuming it will be unique and that is nowhere else in the file then a plugin could look for that and change it into an attribute 
It will be very convoluted since I need to mark the text and then press the plugin button....

**Comment by stevencohn** [comment]
No that is not possible because the Tag element can only be applied to an OE which is the paragraph element in the XML. It can't be applied to an individual T element which is a text run.

Note that the page XML indicates selected text so your plugin should be able to find it without passing it as a second parameter.

**Comment by 1001QAdotNET** [comment]
`**Note that the page XML indicates selected text so your plugin should be able to find it without passing it as a second parameter.**`
OK that is good enough I did not know that, I will try to handle that at my end
