### ISSUE TITLE
Page Updates and Plugin Page Updates

### ISSUE THREAD

**Issue by jasonjac2** [stevencohn/OneMore#510]
**How can I help you?**
So I use Gem & OneTastic and am trying to install this tool.  I use OneNote all day every day and am a developer (but haven't automated ON at all). I noticed that the other tools edit the whole page when they edit anything on a page, i.e. if I run anything that adds to a page, the page all gets "edited" at that time.  Unfortunately this is a real show stopper for me as 4 of collaborate on all pages and rely on who last touched a part of a page (down to the paragraph).

I wanted to see how your project worked with this and also the plug-in (as I am completely intrigued by this allowing me to write plugins cheaply).

is it a real constraint of ON or just easiest to just completely re-write the page.

For your plugins, do you think it might be possible to decorate the XML to just insert or overwrite part of a page?

Thanks for your time and I look forward to using the tool.

THE FINE PRINT
This is a hobby project that I started for myself. I'm happy to take requests and will promise to consider each one carefully but offer no guarantees that I will ultimately agree to their usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
Hi, The OneNote API is the only viable interface I know that effectively lets you integrate an add-in into OneNote and modify content. Individual parts of a page, down to complete paragraphs (represented by the one:OE element) all have unique GUIDs and the supposedly you can update just the elements that you want instead of the entire page.

Unfortunately, in dozens if not hundreds of tests and trials, I've had only limited success using that approach. This is why OneMore (and Gem and 'Tastic) update the entire page. Sadly, Microsoft hasn't really thrown any TLC on the OneNote add-in API in many years. I'm keeping my fingers crossed that they've cleaned up some of these things in the forthcoming unified OneNote release later this year - but I'm not holding my breath. :-/

**Comment by jasonjac2** [comment]
I hadn't seen this reply and created a new issue - very sorry.

**Comment by jasonjac2** [comment]
... have you looked at the MSGraphAPI as a test.  I am not a C# dev and so was going to start looking at the MSGraphAPI to see if i could update online and let changes propogate through.  
Most of the things I really really want relate to crawling pages to check they have certain links and are part of organised ToC pages based on things like text Tag: Scratchpage
As I said in my other post, we have just under 6K pages and at the moment  I have been using OneTastic to do a ToC page per notebook, copy and paste into word and then copy and paste into Excel (I think) as a quicker / better way of finding pages by page title.  MS ON search is so bad as to be unusable.

**Comment by jasonjac2** [comment]
Oher thoughts: 
- copy the resulting text to the clipboard, then I can use the ON GUI to paste it.
- Have a favourite Target scratch page and update that, then I can go there, copy is and back and paste it.

Both are nowhere near as slick as in place insert whilst protecting the page.

"Unfortunately, in dozens if not hundreds of tests and trials, I've had only limited success using that approach. "
What happens / goes wrong?

"Microsoft hasn't really thrown any TLC on the OneNote add-in API in many years. I'm keeping my fingers crossed that they've cleaned up some of these things in the forthcoming unified OneNote release later this year "
Is there a place where I can add my weight to the lobby for a fix.  I know there are MS WishLists.

Thanks again for your time with this.

**Comment by stevencohn** [comment]
I've tried the scratch page concept as well. The problem there with the API is that in order to muck around with any page, OneNote has to bring it into view, so you end up seeing ON flicker between pages. And it really slows you down if you repeat this in a regular workflow.

**Comment by stevencohn** [comment]
I'm going to close this. There's not much I think we can do without drastically affecting performance.
