### ISSUE TITLE
Add tool  tip to OneMore/OneNote

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#512]
I am not sure if this is something that can be done
I would like to be able to have a text displayed when hovering over text on which this feature was used 
Just hover over a link on any wikipedia page to see what I am thinking of

**Comment by stevencohn** [comment]
This falls under the category of dynamic mouse and keyboard monitoring which, as other add-ins have demonstrated, are often performance sinks, making OneNote largely unusable.

There's nothing in the OneNote API that enables this or make it less than complex and fragile.
