### ISSUE TITLE
Why does anything that adds to a page (e.g. breadcrumb) "edit" the whole page?

### ISSUE THREAD

**Issue by jasonjac2** [stevencohn/OneMore#514]
**How can I help you?**
This is a problem with OneTastic / Gem and now I discover with OneMore.
So I finally installed the add-in after not reading your excellent install  instructions!
4 of use use OneNote and edit each others pages.  We have 5.6K pages spread over 5 notebooks.  I also rely a lot of the editor stamps when looking at my own notes (i.e. right click to see who edited this like last).
After running something like "insert breadcrumb" the whole page seems to be edited by me that second.
Why is this?

This is a real blocker to using such fantastic features.
I don't think there is an explanation in the wiki.  
How much effort would it take to have a finer grain change?
I would definitely sponsor this and would invest in installing C# to help (I am not a C# developer).

THE FINE PRINT
This is a hobby project that I started for myself. I'm happy to take requests and will promise to consider each one carefully but offer no guarantees that I will ultimately agree to their usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
This is a duplicate of #510

**Comment by jasonjac2** [comment]
So sorry, that's the problem when I dip in and out of things.
