### ISSUE TITLE
Do you think setting up a discourse / slack / support forum would be a good idea

### ISSUE THREAD

**Issue by jasonjac2** [stevencohn/OneMore#517]
**How can I help you?**
I actively contribute to a number of groups for dev companies and run a use group. It feels a bit polluting to fill this place with Q&A.

Just a thought.

Also, are you prepping for a release?

THE FINE PRINT
This is a hobby project that I started for myself. I'm happy to take requests and will promise to consider each one carefully but offer no guarantees that I will ultimately agree to their usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
I've tried it before with not much success. I don't mind the Q&A here. I try to label appropriately which makes filtering easy

**Comment by stevencohn** [comment]
I'll probably have a patch release in the next month or so, time permitting.
The bigger release will be coming next which I hope will come with a new installer.
