### ISSUE TITLE
Export with attachments

### ISSUE THREAD

**Issue by Peauline** [stevencohn/OneMore#518]
When exporting onenote page with attachments to docx, the attachment is saved in the same directory as the page itself, and the link to it is given. But if the user changes the directory of the attachment then the link will become broken until the user manually fixes it. It would be great if there was a way to avoid this problem. Probably it would be possible to:
1. Add the option allowing to export the page with attachments providing the link to a relative, not absolute, path
2. Add the option to export the attachment not as a file in the same directory but as a file in the exported docx itself. I use MS Word 2019, which allows the user to drag files into the docx and locate them there. Alternatively, the user can go to the Insert and choose "Object" to achieve the same goal (https://support.microsoft.com/en-us/office/embed-or-link-to-a-file-in-word-8d1a0ffd-956d-4368-887c-b374237b8d3a). This way the user can still open all the files right from the docs. It looks like this:

![Files in docx](https://user-images.githubusercontent.com/99823829/174494663-6dbfa0a1-8070-4091-96df-8757c026b505.jpg)

P.S. Thanks for fixing the issue of broken links with non-Unicode characters and for such a great add-in to OneNote :)

**Comment by Peauline** [comment]
Here am I again... I gave it a try a couple of days ago, and everything was just right. However, recently I have completed the reinstallation of my OS (Win10) and reinstalled OneNote with OneMore, and since then it only rarely embeds files - mostly, there are absolute links instead (I am not sure if this reinstallation has something to do with it, it just seems strange to me given that before everything was ok). As it follows from your explanation, this happens when it can't find an associated OLE automation application registered. I wonder if there are certain instances that can prompt such behaviour.
OneNote: 2205 (15225.20288, click to run) 64x
OneMore: 4.18, 64x

**Comment by stevencohn** [comment]
Sorry you're having problems again. It does sound like your assessment is right. Do you have an app installed that opens these files by default?

I think it would be super annoying to prompt for every attachment that doesn't have a default app installed. Of course I could make that a preference but then again, why would you have attachments that you can't open?!?!

**Comment by Peauline** [comment]
Yes, I have default apps for these files. I have just tried to export a page with files both with and without default apps and the result was the same, i.e. all these files were exported as absolute links.

**Comment by stevencohn** [comment]
What is the app?

**Comment by Peauline** [comment]
Word, Excel, PowerPoint (defaults for docx, excel sheets, ppts, respectively) and tar.gz archive with no default app
