### ISSUE TITLE
Table of Contents

### ISSUE THREAD

**Issue by Joe202206** [stevencohn/OneMore#524]
Hi, thanks for your powerful OneMoreAddIn. Today I meet a problem with "Table of Contents", and I dont know how to solve it.

The situation is like: 
First, I change the style for Headings in OneMore. I rename the headings 1 to 6, change font size, color and paragraph space. Then when I click "Table of Contents" in a new page, the table will contain all the contents of this page. e.g. this table contains Heading 1 and then all other normal style contents will  show under Heading 1. 
Then the OneNote will lag for a while.
![image](https://user-images.githubusercontent.com/108169444/175761286-ac669949-6061-47fc-a4c2-d0b4830b64bc.png)
Hope for your reply!

Best, Joe

**Comment by Joe202206** [comment]
The heading font 1-6 must be larger than the normal word! otherwise the TOC will show wrong label

**Comment by stevencohn** [comment]
You closed this. Is it still an issue?

**Comment by Joe202206** [comment]
Dear Steven,


I have solved it as I said in the comments. The TOC error is because that I set the Heading 6 font just equal to normal style word.&nbsp;
So the TOC need all heading font larger than normal right?


Thanks again for your powerful OneMore!


Best, Joe



---Original---
From: ***@***.***&gt;
Date: Sat, Jun 25, 2022 18:41 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [stevencohn/OneMore] Table of Contents (Issue #524)




 
You closed this. Is it still an issue?

**Comment by stevencohn** [comment]
OK yes. The "custom styles" created by OneMore are not separate entities like the built-in OneNote styles. So if you create a style that duplicate the properties of another then OneMore can't tell the difference between them.

I'll update the Wiki pages to make this clear. Thanks
