### ISSUE TITLE
Sort columns in OneNote table by clicking column name 

### ISSUE THREAD

**Issue by gui28347** [stevencohn/OneMore#527]
**Is your feature request related to a problem? Please describe.**
When creating tables in onenote, there is no way how sort, only import an excel into onenote.

**Describe the solution you'd like**
Clicking in the column in name in OneNote table it sort the data in columns A-Z or Z-A

**Describe alternatives you've considered**
Using excel.

**Comment by stevencohn** [comment]
OneNote has a built-in sort by column feature under the Table tab as shown here

<img width="197" alt="image" src="https://user-images.githubusercontent.com/9964757/175810101-10c814c2-f69b-4a94-b0ca-282ec2bec9e0.png">
