### ISSUE TITLE
Disabled by onenote

### ISSUE THREAD

**Issue by EdwardYu9999** [stevencohn/OneMore#528]
**How can I help you?**
I really enjoy OneMore, but I got a problem 2 days ago.
the Addin has been disabled by the app.
I have tried to remove and install it again but it still does not work.

attached is the screenshot for this.

THE FINE PRINT
This is a hobby project that I started for myself. I'm happy to take requests and will promise to consider each one carefully but offer no guarantees that I will ultimately agree to their usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around then I will probably reject the request - you've been warned!

![微信截图_20220628130133](https://user-images.githubusercontent.com/52403990/176096715-5d3ca850-9c85-46fd-a7a0-e1b252cd27a5.png)

**Comment by stevencohn** [comment]
Ref #622
