### ISSUE TITLE
When using rich text paste, the spaces in the original text will disappear

### ISSUE THREAD

**Issue by bladetin** [stevencohn/OneMore#529]
**Describe the bug**
When copying code from idea series IDE and pasting it to OneNote, the default paste format of OneNote does not contain spaces, but has color information and font information. 
![image](https://user-images.githubusercontent.com/92976987/176140589-b8370648-ff4d-4f20-b368-4ca6fd52d4b1.png)
After checking online, I found that installing a plugin can solve this problem. The "Paste Rich Text" feature in gem for onenote plugin can solve this problem perfectly, keeping spaces and retaining color and font information (but the interface of this software is not as good as OneMore and the fee is very high). 
![image](https://user-images.githubusercontent.com/92976987/176140920-94341a68-a120-4984-a41e-e3c539c49722.png)
OneMore plug-in also has "Paste Rich Text" function, but it can't keep spaces, and the default format of OneNote paste is the same.
![image](https://user-images.githubusercontent.com/92976987/176141019-bab36138-49de-4fad-9468-54afa01aff5b.png)

**To Reproduce**
1. Go to 'more'
2. Click on 'edit'
3. Click on 'Paste Rich Text'

**Expected behavior**
Paste rich text and keep spaces when pasting.

**Screenshots**
As shown in the above diagram.

**Environment (if applicable):**
 - OneNote Version: 2021 MSO (version 2205 Build 16.0.15225.20278) 64 bit
 - OneMore Version: 4.18

**Additional context**
<one:Page xmlns:one="http://schemas.microsoft.com/office/onenote/2013/onenote" ID="{C4854877-D194-0423-27E5-FAE3AA437DF2}{1}{E19461629569653830105420144520017367855963141}" name="issue" dateTime="2022-06-28T09:16:35.000Z" lastModifiedTime="2022-06-28T09:21:37.000Z" pageLevel="2" isCurrentlyViewed="true" selected="partial" lang="zh-CN">
  <one:QuickStyleDef index="0" name="PageTitle" fontColor="automatic" highlightColor="automatic" font="Cascadia Code" fontSize="20.0" spaceBefore="0.0" spaceAfter="0.0" />
  <one:QuickStyleDef index="1" name="p" fontColor="automatic" highlightColor="automatic" font="Cascadia Code" fontSize="12.0" spaceBefore="0.0" spaceAfter="0.0" />
  <one:QuickStyleDef index="2" name="p" fontColor="automatic" highlightColor="automatic" font="Cascadia Code" fontSize="12.0" spaceBefore="0.0" spaceAfter="0.0" />
  <one:PageSettings RTL="false" color="automatic">
    <one:PageSize>
      <one:Automatic />
    </one:PageSize>
    <one:RuleLines visible="false" />
  </one:PageSettings>
  <one:Title selected="partial" lang="en-US">
    <one:OE alignment="left" quickStyleIndex="0" selected="partial">
      <one:T><![CDATA[issue]]></one:T>
      <one:T selected="all"><![CDATA[]]></one:T>
    </one:OE>
  </one:Title>
  <one:Outline>
    <one:Position x="36.0" y="86.4000015258789" z="0" />
    <one:Size width="540.0" height="529.225830078125" />
    <one:OEChildren>
      <one:OE alignment="left" quickStyleIndex="1" style="font-family:'Microsoft YaHei';font-size:12.0pt">
        <one:T><![CDATA[<span
lang=en-US>the correct paste (using paste rich text) (</span><span lang=zh-CN>ideal situation</span><span
lang=en-US>) :</span>]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="2" style="font-family:'Cascadia Code';font-size:12.0pt;color:#8C8C8C" lang="en-US">
        <one:T><![CDATA[]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="2" style="font-family:'Cascadia Code';font-size:12.0pt" lang="en-US">
        <one:T><![CDATA[<span style='color:#0033B3;background:white'>create table </span><span style='color:black;background:white'>student</span><span style='color:#080808;
background:white'>(</span>]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="2" style="font-family:'Cascadia Code';font-size:12.0pt" lang="en-US">
        <one:T><![CDATA[<span style='color:#080808;background:white'>    </span><span style='color:#871094;
background:white'>id </span><span style='color:#0033B3;background:white'>int auto_increment primary key comment </span><span style='color:#067D17;background:white'>''</span><span style='color:#080808;
background:white'>,</span>]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="2" style="font-family:'Cascadia Code';font-size:12.0pt" lang="en-US">
        <one:T><![CDATA[<span style='color:#080808;background:white'>    </span><span style='color:#871094;
background:white'>name </span><span style='color:#0033B3;background:white'>varchar</span><span style='color:#080808;background:white'>(</span><span style='color:#1750EB;
background:white'>10</span><span style='color:#080808;background:white'>) </span><span style='color:#0033B3;background:white'>comment </span><span style='color:#067D17;
background:white'>''</span><span style='color:#080808;background:white'>,</span>]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="2" style="font-family:'Cascadia Code';font-size:12.0pt" lang="en-US">
        <one:T><![CDATA[<span style='color:#080808;background:white'>    </span><span style='color:#871094;
background:white'>no </span><span style='color:#0033B3;background:white'>varchar</span><span style='color:#080808;background:white'>(</span><span style='color:#1750EB;
background:white'>10</span><span style='color:#080808;background:white'>) </span><span style='color:#0033B3;background:white'>comment </span><span style='color:#067D17;
background:white'>''</span>]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="2" style="font-family:'Cascadia Code';font-size:12.0pt" lang="en-US">
        <one:T><![CDATA[<span style='color:#080808;background:white'>) </span><span style='color:#0033B3;
background:white'>comment </span><span style='color:#067D17;background:white'>''</span><span style='color:#080808;background:white'>;</span>]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="2" style="font-family:'Cascadia Code';font-size:12.0pt" lang="en-US">
        <one:T><![CDATA[<span style='color:#0033B3;background:white'>insert into </span><span style='color:black;background:white'>student </span><span style='color:#0033B3;
background:white'>values </span><span style='color:#080808;background:white'>(</span><span style='color:#0033B3;background:white'>null</span><span style='color:#080808;
background:white'>,</span><span style='color:#067D17;background:white'>''</span><span style='color:#080808;background:white'>,</span><span style='color:#067D17;
background:white'>'2808100101'</span><span style='color:#080808;background: white'>),(</span><span style='color:#0033B3;background:white'>null</span><span style='color:#080808;background:white'>,</span><span style='color:#067D17;
background:white'>''</span><span style='color:#080808;background:white'>,</span><span style='color:#067D17;background:white'>'2000108102'</span><span style='color:#080808;background:white'>),(</span><span style='color:#0033B3;
background:white'>null</span><span style='color:#080808;background:white'>,</span><span style='color:#067D17;background:white'>''</span><span style='color:#080808;
background:white'>,</span><span style='color:#067D17;background:white'>'2000100103' </span><span style='color:#080808;background:white'>) ,(</span><span style='color:#0033B3;
background:white'>null</span><span style='color:#080808;background:white'>, </span><span style='color:#067D17;background:white'>''</span><span style='color:#080808;
background:white'>,</span><span style='color:#067D17;background:white'>'2000100104'</span><span style='color:#080808;background:white'>);</span>]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="2">
        <one:T><![CDATA[]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="2" style="font-family:'Cascadia Code';font-size:12.0pt" lang="en-US">
        <one:T><![CDATA[<span style='color:#0033B3;background:white'>create table </span><span style='color:black;background:white'>course</span><span style='color:#080808;
background:white'>(</span>]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="2" style="font-family:'Cascadia Code';font-size:12.0pt" lang="en-US">
        <one:T><![CDATA[<span style='color:#080808;background:white'>    </span><span style='color:#871094;
background:white'>id </span><span style='color:#0033B3;background:white'>int auto_increment primary key comment </span><span style='color:#067D17;background:white'>''</span><span style='color:#080808;
background:white'>,</span>]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="2" style="font-family:'Cascadia Code';font-size:12.0pt" lang="en-US">
        <one:T><![CDATA[<span style='color:#080808;background:white'>    </span><span style='color:#871094;
background:white'>name </span><span style='color:#0033B3;background:white'>varchar</span><span style='color:#080808;background:white'>(</span><span style='color:#1750EB;
background:white'>10</span><span style='color:#080808;background:white'>) </span><span style='color:#0033B3;background:white'>comment </span><span style='color:#067D17;
background:white'>''</span>]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="2" style="font-family:'Cascadia Code';font-size:12.0pt" lang="en-US">
        <one:T><![CDATA[<span style='color:#080808;background:white'>) </span><span style='color:#0033B3;
background:white'>comment</span><span style='color:#067D17;background:white'>''</span><span style='color:#080808;background:white'>;</span>]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="2" style="font-family:'Cascadia Code';font-size:12.0pt" lang="en-US">
        <one:T><![CDATA[<span style='color:#0033B3;background:white'>insert into </span><span style='color:black;background:white'>course </span><span style='color:#0033B3;
background:white'>values </span><span style='color:#080808;background:white'>(</span><span style='color:#0033B3;background:white'>null</span><span style='color:#080808;
background:white'>,</span><span style='color:#067D17;background:white'>'Java'</span><span style='color:#080808;background:white'>),(</span><span style='color:#0033B3;
background:white'>null</span><span style='color:#080808;background:white'>,</span><span style='color:#067D17;background:white'>'PHP'</span><span style='color:#080808;
background:white'>),(</span><span style='color:#0033B3;background:white'>null</span><span style='color:#080808;background:white'>,</span><span style='color:#067D17;
background:white'>'MySQL'</span><span style='color:#080808;background:white'>),(</span><span style='color:#0033B3;background:white'>null</span><span style='color:#080808;
background:white'>,</span><span style='color:#067D17;background:white'>'Hadoop'</span><span style='color:#080808;background:white'>);</span>]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="2" style="font-family:'Microsoft YaHei';font-size:12.0pt" lang="en-US">
        <one:T><![CDATA[]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="2" style="font-family:'Microsoft YaHei';font-size:12.0pt" lang="en-US">
        <one:T><![CDATA[]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="2" style="font-family:'Microsoft YaHei';font-size:12.0pt">
        <one:T><![CDATA[<span
lang=en-US>the onenote and onemore (using paste rich text) d</span><span
lang=zh-CN>id not reach the ideal state</span><span lang=en-US>, b</span><span
lang=zh-CN>ecause the spaces in the original text were not retained</span><span
lang=en-US> :</span>]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="2" style="font-family:'Microsoft YaHei';font-size:12.0pt" lang="en-US">
        <one:T><![CDATA[]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="1" style="font-family:'Cascadia Code';font-size:12.0pt">
        <one:T><![CDATA[<span style='color:#0033B3;background:white'>createtable</span><span style='color:black;background:white'>student</span><span style='color:#080808;
background:white'>(</span>]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="1" style="font-family:'Cascadia Code';font-size:12.0pt">
        <one:T><![CDATA[<span style='color:#871094;background:white'>id</span><span style='color:#0033B3;
background:white'>intauto_incrementprimarykeycomment</span><span style='color:#067D17;background:white'>''</span><span style='color:#080808;
background:white'>,</span>]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="1" style="font-family:'Cascadia Code';font-size:12.0pt">
        <one:T><![CDATA[<span style='color:#871094;background:white'>name</span><span style='color:#0033B3;
background:white'>varchar</span><span style='color:#080808;background:white'>(</span><span style='color:#1750EB;background:white'>10</span><span style='color:#080808;
background:white'>)</span><span style='color:#0033B3;background:white'>comment</span><span style='color:#067D17;background:white'>''</span><span style='color:#080808;
background:white'>,</span>]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="1" style="font-family:'Cascadia Code';font-size:12.0pt">
        <one:T><![CDATA[<span style='color:#871094;background:white'>no</span><span style='color:#0033B3;
background:white'>varchar</span><span style='color:#080808;background:white'>(</span><span style='color:#1750EB;background:white'>10</span><span style='color:#080808;
background:white'>)</span><span style='color:#0033B3;background:white'>comment</span><span style='color:#067D17;background:white'>''</span>]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="1" style="font-family:'Cascadia Code';font-size:12.0pt">
        <one:T><![CDATA[<span style='color:#080808;background:white'>)</span><span style='color:#0033B3;
background:white'>comment</span><span style='color:#067D17;background:white'>''</span><span style='color:#080808;background:white'>;</span>]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="1" style="font-family:'Cascadia Code';font-size:12.0pt">
        <one:T><![CDATA[<span style='color:#0033B3;background:white'>insertinto</span><span style='color: black;background:white'>student</span><span style='color:#0033B3;background: white'>values</span><span style='color:#080808;background:white'>(</span><span style='color:#0033B3;background:white'>null</span><span style='color:#080808;
background:white'>,</span><span style='color:#067D17;background:white'>''</span><span style='color:#080808;background:white'>,</span><span style='color:#067D17;
background:white'>'2808100101'</span><span style='color:#080808;background: white'>),(</span><span style='color:#0033B3;background:white'>null</span><span style='color:#080808;background:white'>,</span><span style='color:#067D17;
background:white'>''</span><span style='color:#080808;background:white'>,</span><span style='color:#067D17;background:white'>'2000108102'</span><span style='color:#080808;background:white'>),(</span><span style='color:#0033B3;
background:white'>null</span><span style='color:#080808;background:white'>,</span><span style='color:#067D17;background:white'>''</span><span style='color:#080808;
background:white'>,</span><span style='color:#067D17;background:white'>'2000100103'</span><span style='color:#080808;background:white'>),(</span><span style='color:#0033B3;
background:white'>null</span><span style='color:#080808;background:white'>,</span><span style='color:#067D17;background:white'>''</span><span style='color:#080808;
background:white'>,</span><span style='color:#067D17;background:white'>'2000100104'</span><span style='color:#080808;background:white'>);</span>]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="1">
        <one:T><![CDATA[]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="1" style="font-family:'Cascadia Code';font-size:12.0pt">
        <one:T><![CDATA[<span style='color:#0033B3;background:white'>createtable</span><span style='color:black;background:white'>course</span><span style='color:#080808;
background:white'>(</span>]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="1" style="font-family:'Cascadia Code';font-size:12.0pt">
        <one:T><![CDATA[<span style='color:#871094;background:white'>id</span><span style='color:#0033B3;
background:white'>intauto_incrementprimarykeycomment</span><span style='color:#067D17;background:white'>''</span><span style='color:#080808;
background:white'>,</span>]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="1" style="font-family:'Cascadia Code';font-size:12.0pt">
        <one:T><![CDATA[<span style='color:#871094;background:white'>name</span><span style='color:#0033B3;
background:white'>varchar</span><span style='color:#080808;background:white'>(</span><span style='color:#1750EB;background:white'>10</span><span style='color:#080808;
background:white'>)</span><span style='color:#0033B3;background:white'>comment</span><span style='color:#067D17;background:white'>''</span>]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="1" style="font-family:'Cascadia Code';font-size:12.0pt">
        <one:T><![CDATA[<span style='color:#080808;background:white'>)</span><span style='color:#0033B3;
background:white'>comment</span><span style='color:#067D17;background:white'>''</span><span style='color:#080808;background:white'>;</span>]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="1" style="font-family:'Cascadia Code';font-size:12.0pt">
        <one:T><![CDATA[<span style='color:#0033B3;background:white'>insertinto</span><span style='color: black;background:white'>course</span><span style='color:#0033B3;background: white'>values</span><span style='color:#080808;background:white'>(</span><span style='color:#0033B3;background:white'>null</span><span style='color:#080808;
background:white'>,</span><span style='color:#067D17;background:white'>'Java'</span><span style='color:#080808;background:white'>),(</span><span style='color:#0033B3;
background:white'>null</span><span style='color:#080808;background:white'>,</span><span style='color:#067D17;background:white'>'PHP'</span><span style='color:#080808;
background:white'>),(</span><span style='color:#0033B3;background:white'>null</span><span style='color:#080808;background:white'>,</span><span style='color:#067D17;
background:white'>'MySQL'</span><span style='color:#080808;background:white'>),(</span><span style='color:#0033B3;background:white'>null</span><span style='color:#080808;
background:white'>,</span><span style='color:#067D17;background:white'>'Hadoop'</span><span style='color:#080808;background:white'>);</span>]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="1" style="font-family:'Microsoft YaHei';font-size:12.0pt" lang="en-US">
        <one:T><![CDATA[]]></one:T>
      </one:OE>
    </one:OEChildren>
  </one:Outline>
</one:Page>

-----------------------------------------------------------------------
Looking forward to your reply, your software is of high quality.

**Comment by stevencohn** [comment]
This is a problem with the way IDEA copies rich content as HTML to the clipboard. Indeed, I can demonstrate that by using my [ClipboardRtfToHtml](https://github.com/stevencohn/ClipboardRtfToHtml/releases) converter which first dumps out all content formats stored in the Windows clipboard. This shows that IDEA writes significant whitespace chars as unwrapped "text" elements within the HTML instead of embedded in strings wrapped by SPAN elements. 

This is acknowledged by JetBrains [here](https://intellij-support.jetbrains.com/hc/en-us/community/posts/4867150134674-Copy-paste-to-OneNote-loses-all-spaces) and [here](https://youtrack.jetbrains.com/issue/IDEA-185049?_gl=1*1swt8ra*_ga*MTg5OTgwMDY1LjE2NTY0MTEyODg.*_ga_9J976DJZ68*MTY1NjQxMTI4OC4xLjEuMTY1NjQxMjA4Ny4w&_ga=2.226320602.1962523911.1656411289-189980065.1656411288)

When you paste into OneNote using the built-in Paste function or Ctrl-V, OneNote first looks for HTML formatted content on the clipboard (before it looks for RTF formatted content) and inserts that. OneMore does the same.

There are a couple of solutions

1. As a workaround, you can Paste as Plain Text and then use OneMore's Colorize command.
2. I can change OneMore's search order to first look for RTF contents on the clipboard before it looks for HTML content. I'll have to think more about this since I'm not sure of the ramifications.
3. I can try to preserve significant spaces between SPANs. Quite honestly, the Paste to Rich Text command is one that I've been meaning to "clean up" for some time. Perhaps now is the time!

**Comment by bladetin** [comment]
Thank you very much for your patient response! Thank you!
