### ISSUE TITLE
feature request: Add contextual menu -Search the selected text with a search engine like Google or Bing 

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#53]
It would be nice to have the option to select text and then right click and select a search engine to search that text
This should be in the context menu

**Comment by stevencohn** [comment]
Isn't that what the Lookup command does on the context menu? It should open the Research side panel.

**Comment by 1001QAdotNET** [comment]
If you want to do something cool make ir with an option to search scholars.google.com, books.google.com, regular google.com OneNote is or should be an academic tools

**Comment by stevencohn** [comment]
Done. Check out version 2.16 or a later release. Also look at the description on the home page.

**Comment by 1001QAdotNET** [comment]
Thank you!

**Comment by 1001QAdotNET** [comment]
It is not working for me
Adding the below creates the context menu but when I select a word and I click the Google context menu icon nothing happens
The log is empty
I am on OneNote 2013x86 win10
![image](https://user-images.githubusercontent.com/17384308/94770992-1c485180-0384-11eb-9e01-876ac9cbe782.png)

**Comment by stevencohn** [comment]
The URL Pattern needs to be exactly:

https://www.google.com/search?q={0}

The "{0}" bit will be replaced with the selected word or phrase

**Comment by 1001QAdotNET** [comment]
Even with that it is not launching the browser or opening a browser and nothing is logged to the logger

**Comment by stevencohn** [comment]
Did you restart OneNote?

**Comment by 1001QAdotNET** [comment]
yes with the initial link (the wrong one)
changed that and I did not restart 
I just restarted and it is working now ..thanks for the tip and for implementing this It will help a lot

**Comment by stevencohn** [comment]
Good. I wish I could have found a way of dynamically reloading the context menu but there's doesn't seem to be a way.

Let me know if you find anything else.

**Comment by 1001QAdotNET** [comment]
Will continue to test
I hope to get more free time next week, I can't wait to start toying with the run a plugin option
