### ISSUE TITLE
Send regular emails with random notes from selected sections

### ISSUE THREAD

**Issue by Aulline** [stevencohn/OneMore#532]
**Is your feature request related to a problem? Please describe.**
Most of the time, we tend to write a lot of things into our notebooks and then simply forget about their existence, never revisiting them for further reflection/implementation. Revisiting notes might also be helpful for those who keep study notes in OneNote.
 
**Describe the solution you'd like**
I think it would be great if there was a feature that allows the user to regularly send themself emails with random notes from a notebook/section for a review. It might look like this
1. The user chooses the name for a new newsletter. There can be several newsletters with different settings.
2. The user specifies the email address to which notes are to be sent.
3. The user schedules the sending of emails (e.g. one email daily, 3 emails per week, etc)
4. The user defines the scope from which random notes are to be selected (e.g. from the whole notebook, certain sections, from a subsection).
5. The user sets how many notes are to be sent per one email (e.g. 3, 8, 20, etc). These notes should be selected randomly.

THE FINE PRINT
This is a hobby project that I started for myself. I'm happy to take requests and will promise to consider each one carefully but offer no guarantees that I will ultimately agree to their usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around then I will probably reject the request - you've been warned!

**Comment by 1001QAdotNET** [comment]
Doesn't this overlap with tasks and reminders functionality ? It could be an extension of those features
