### ISSUE TITLE
Calendar (BETA) strange Repaint as you move your mouse around the "Page" Column

### ISSUE THREAD

**Issue by jasonjac2** [stevencohn/OneMore#534]
**Describe the bug**
When I look at the Calendar in List Mode the Page column text changes as you move over it once you have scrolled down (you need more than one screen full)

**To Reproduce**
Bring up the Calendar (BETA) screen
![image](https://user-images.githubusercontent.com/68282090/177327073-3b3fc12d-2ce3-4f4b-a855-866dd0d03642.png)
I have all my notebooks (13) checked
It opens for july 2022
1st screen is fine, I hoved over a page entry and click, it works as expected - an instance of ON goes to that page.
![image](https://user-images.githubusercontent.com/68282090/177327425-311e8257-aeb9-473f-94bd-628dc2be9b26.png)

but as soon as I page down / scroll at all...
As you move the mouse over the 1st visible row of "Page" column  (which should now be say row 5 of actual data), it repaints as if it is row 1 and if you click it takes you to the page that was at row 1.

**Expected behavior**
Rows stay visually in sync.

**Screenshots**
The actual top row (before scrolling)
![image](https://user-images.githubusercontent.com/68282090/177328238-1e875127-6ddc-4b10-b2d3-8e594cdf4de3.png)

The top row once I have scrolled
![image](https://user-images.githubusercontent.com/68282090/177328298-dcecb8c6-5736-403a-860b-5783eff9414c.png)

No more scrolling, but as I move my mouse over the 1st row
![image](https://user-images.githubusercontent.com/68282090/177328437-1275d87d-5a98-4f55-82d8-073b314a9d96.png)

The page it takes me to (correct as per what was shown, but this was the wrong row)
![image](https://user-images.githubusercontent.com/68282090/177328550-78064f82-bfd2-4ed8-9cac-8acfad1a35b2.png)

**Environment (if applicable):**
 - OneNote - 32 bit - Version 2206 Build 16.0.15330.20196 Click to Run)
 - OneMore  Calendar Version [e.g. 4.18 (BETA)

**Additional context**
Add any other context about the problem here. Attach page XML file or the app log file as appropriate. You can find the log file here: %localappdata%\temp\OneMore.log

**Comment by jasonjac2** [comment]
Have you been able to reproduce this or do I need to re-test / provide more detail?

**Comment by stevencohn** [comment]
I have seen it. I've been focusing a little on the Calendar lately so I'll take a closer look at this too.

**Comment by jasonjac2** [comment]
Yes, I saw the checkin, so thought I would give this a nudge :-).

**Comment by stevencohn** [comment]
Fixed. In next release.

However, this uncovered an issue with OneNote. Submitted [here](https://answers.microsoft.com/en-us/msoffice/forum/all/onenote-interop-api-navigatetourl-fails-if-called/1f4b6ba7-0410-4b44-b8c0-978c146ddd82)
