### ISSUE TITLE
Copy Breadcrumb Trail

### ISSUE THREAD

**Issue by jasonjac2** [stevencohn/OneMore#535]
**Is your feature request related to a problem? Please describe.**
I love the new feature, so not, not a problem.

**Describe the solution you'd like**
but would it be possible to have it as:
Link to Notebook > Link to Tab > Link to Section > Link to Page > Link to para on page
i.e. the text is great, but it is one link, whereas ideally I would like it to be a link at each section?

**Describe alternatives you've considered**

**Additional context**
There is a slight problem though, if the page title has a date in it, it turns the slash into an arrow.

THE FINE PRINT
This is a hobby project that I started for myself. I'm happy to take requests and will promise to consider each one carefully but offer no guarantees that I will ultimately agree to their usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
To be clear, the way this will work - because this is how OneNote works - is that clicking the link to the notebook, section group, or section, will open the most recently viewed page under that scope; this might not be the page at the end of the breadcrumb. Only clicking on the page or paragraph at the end of the breadcrumb will open that up.

The behavior will be the same as if you click a notebook, section group, or section in the OneNote navigation panel.

**Comment by jasonjac2** [comment]
1st - Amazing that you have had time to do a new release.

Just checked out the new feature and it is great (4.19(.  The only V minor point is the entry (the page) isn't a link.  I know a link to itself doesn't seem logical, but when I have templated sections of pages that are self referencing, e.g.  a template at the top of a page that you copy to a new page and at it will have something like
Parent: <you fill this in>
Template: be the breadcrumb trail.

Also: I tried on one of my pages as it seemed to whir away for about 30s where ON becomes unresponsive and then comes back with no change.  I did the ToC on the same page and it worked.  

Did you want me to raise as 2 x "issues"

**Comment by stevencohn** [comment]
Sorry I don't fully understand your problem with the page part not being hyperlinked. There are multiple other ways to do this including ToC which allows you to add "Jump to top" links to each heading or Insert Link to Page or Link to Paragraph which I realize I need to update to hyperlink individual parts like we did here with the Breadcrumb command.

As for the unresponsive page, please open a new ticket and if you could attach the page exported as a .one file or an .xml file

**Comment by jasonjac2** [comment]
"Sorry I don't fully understand your problem with the page part not being hyperlinked" 
Don't worry about it, the "copy link to para" and "copy link to page" more that satisfy my needs.  
On reflection, the Breadcrumb trail I use on my wiki's etc don't actually have "this page" included in it, they just have the parents.  So all is good :-).

On the unresponsive page, I will raise a ticket on it. 
Thanks again for a great product.

**Comment by jasonjac2** [comment]
Yes, perfect.

sent from my mobile, please excuse typos
________________________________
