### ISSUE TITLE
Feature Request: Set default container width (per page?)

### ISSUE THREAD

**Issue by PNG-pyro** [stevencohn/OneMore#537]
I'd like an option to set a default width for new containers. Being able to adjust it on a page-by-page basis through templates or styles would be ideal, but a global option would work for me.

Here's my use-case; I like to use OneNote as a kinda corkboard. I make little text boxes, put my ideas in them, and shuffle them around. However, to make them feel like cards, I either need to shrink the width of each container manually copy/paste a premade one.

If I could set container width, I could simply click and start typing for a new 'card'. 

Combining this with styles/templates/snippets somehow would be perfect, so I could make a 'corkboard' template that automatically limited the width and dropped a snippet into each new container. Then I could add a header/icon, and a cell for border/color, like the Info snippet. 

Anyways, I have no idea how feasible this is, seeing as how even vanilla OneNote seems to have skipped the option; I just thought I'd ask in the off-chance you find it worth your time. Thank you for this amazing add-on and for making it free(!) for use. You're awesome!

**Comment by stevencohn** [comment]
Inspiring. Brain is churning.

**Comment by stevencohn** [comment]
Have you taken a look at the OneMore/Page/Arrange Containers command? It's not exactly what you're asking for but gives you the ability to resize all containers on a page to a desired size and next to each other.

**Comment by julie777** [comment]
> Have you taken a look at the OneMore/Page/Arrange Containers command? It's not exactly what you're asking for but gives you the ability to resize all containers on a page to a desired size and next to each other.

I had not see this command. It sounds very cool.

**Comment by stevencohn** [comment]
Closing as stale. Assuming the Arrange Containers command is sufficient.
