### ISSUE TITLE
Enhancement to Excel Preview

### ISSUE THREAD

**Issue by NoralK** [stevencohn/OneMore#538]
**Describe the solution you'd like**
It would be nice if the Excel Preview had the ability to set the columns/range to preview, this would be per sheet.

An alternative would be to use the Set Print Area in the Excel worksheet(s).

Cheers

**Comment by stevencohn** [comment]
Unfortunately, there doesn't seem to be any way to do this. Even updating Set Print Area in the worksheet doesn't appear to have any effect on what is displayed in OneNote.

**Comment by NoralK** [comment]
I did find out that if I his everything it achieved my goal.

Thanks,
Noral
