### ISSUE TITLE
There is a problem with the installer package.

### ISSUE THREAD

**Issue by munish259272** [stevencohn/OneMore#539]
**Describe the bug**
Cannot install, see the screenshot of the error

**Screenshots**
![image](https://user-images.githubusercontent.com/834673/178148428-e828f628-e98c-402d-b4da-c4f79b966e05.png)

**Environment (if applicable):**
 - OneNote Version: [O365 64bit)
 - OS : Windows 10 pro  64 bit (21H2)

**Comment by stevencohn** [comment]
Duplicate of #545
