### ISSUE TITLE
Feature request: Rolling highlighter  colors

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#54]
Not sure if this is of a large interest but I am submitting this request anyway. Like all the requests I am making the intention for this one is to speed up the active reading process and making it more fluid

When I read I highlight text. I do not use color codes for it I just need to rotate the colors I use for highlighting in order to obtain contrast between adjacent highlighted pieces of text
Having that said I think it would be nice if I could pick let's say 5 colors from the color palette an add them to a set of colors that OneMore will loop through and use them to change the current highlighter color. That way any time when I select a text the short menu context pops up with the next color in the loop selected and the user does not need to bother with alternating the colors when highlighting (if this is needed)

**Comment by stevencohn** [comment]
Sounds rather specific. Wouldn't be hard to do but I'll leave this open for a while to see if it gets any up votes.

**Comment by stevencohn** [comment]
I actually like this idea but think the context menu is already getting too crowded. I think a Preferences UI may be warranted first.

**Comment by CLITrees** [comment]
I am glad you liked it because that is something that I do need and use a lot

**Comment by 1001QAdotNET** [comment]
I am glad you liked this because I do need it and I would use this on a regular basis

**Comment by stevencohn** [comment]
https://github.com/stevencohn/OneMore/releases/tag/3.6

**Comment by 1001QAdotNET** [comment]
this works as expected, thank you. It would be great to offer the user to select a custom palette 
The fade palette is exactly what I use so I personally don't need the custom one but if it is easy why for you not...
thank you again, great work

**Comment by stevencohn** [comment]
It may be worth it for color-blindness but I'll see if these pallets are OK for everyone.... thanks for the input! On to other features.
