### ISSUE TITLE
Every command that updates a page, have an option to copy to clipboard - workaround for page edit issue

### ISSUE THREAD

**Issue by jasonjac2** [stevencohn/OneMore#540]
**Is your feature request related to a problem? Please describe.**
When oneMore edits a page it has to update the whole page and for me this means I can't use them because I need to keep the editor history of who edited which paragraphs.

**Describe the solution you'd like**
A good solution would be to have a top level option that you can easily turn on and off and when you turn it on, instead of it updating the page when it would normally insert something, it just copies it to the clipboard.
When invoked you could get a popup (as in a non-modal, hint) saying "copied to clipboard"

**Describe alternatives you've considered**
- Run the command, copy the insert, undo the insert, paste the insert
- Ask to get these updates done via a more reliable vector - GraphAPI
- Get more detail on the issue, so I can lobby MS via the forums to fix the problem.

**Additional context**

THE FINE PRINT
This is a hobby project that I started for myself. I'm happy to take requests and will promise to consider each one carefully but offer no guarantees that I will ultimately agree to their usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
OneMore doesn't use the GraphAPI. It only relies on the COM API provided by the desktop edition of OneNote. It does this so the user doesn't have to be online or use MFA to get it working in the desktop app.

Regardless, it's not really possible to copy "changes" to the clipboard. These would be expressed in OneNote's 2013 XML schema which is not directly compatible with the GraphAPI which would be a complete rewrite of OneMore... and an entirely different app in the end.

**Comment by jasonjac2** [comment]
Thanks Steven for the explanation on why it won't work by using Graph API.  That was my "Describe alternatives you've considered".  My main request was to be able to copy the changes to the clipboard. 

"Regardless, it's not really possible to copy "changes" to the clipboard. These would be expressed in OneNote's 2013 XML schema which is not directly compatible with the GraphAPI which would be a complete rewrite of OneMore... and an entirely different app in the end."

Are you saying the changes you make via the COM interface couldn't be copied to the clipboard and then me interactively paste them where I want?
I thought it would work because you already have items where you copy stuff to the clipboard that I can paste directly into ON pages.

If that is the case, then I guess the only other 2 options are:
- Have a scratch page target that is a kind of "instead of injecting into the page, inject onto the scratch page"
- Have an "after command" hack like I do - select change, copy, undo, click where you want it, paste.
-  Have you or anyone logged the issue with MS, i.e. somewhere I can +1 and lobby for MS to fix it.

**Comment by stevencohn** [comment]
So I'm not going to extend every command in OneNote to provide the option to work off of a scratch pad regardless of the implementation. This vastly complicates not only the code but also the user's workflow. 

If we go back to your original concern of tracking users, is it about basic auditing, tracking who made what changes? Doesn't the built-in page history tracking solve this already? When you enable page version history, all changes are tracked by OneNote itself and you can always go back and view historical changes along with who made those changes.

**Comment by jasonjac2** [comment]
"So I'm not going to extend every command in OneNote to provide the option to work off of a scratch pad regardless of the implementation. This vastly complicates not only the code but also the user's workflow."
I totally get that.  I was hoping there may have been a generic  "updated" method that could be intercepted.

"go back to your original concern of tracking users," 
Not really for audit, but all our valuable pages have evolved over time and the who le page is rarely reviewed in one go.  So there is the timeliness of the information, e.g. I'll be looking at a page on "resizing a disk" and there is a process and the page has been improved.  I'm reading and wonder when it was edited, so I right click and can see that the zyx step was last edited by bob 8 years ago or 1 week ago - it changes how I react / perceive the relevance of the data.
"When you enable page version history,"
This is turned on by default, but suddenly there is a lot of friction to find out when and who and so you don't use it all the time.

What I would normally want to do is: goto a page, update the ToC immediately to know I am can see the scope of the content, then read relevant sections or as I am reviewing, just add a back and forward link to another part of the ON notebook.  I can't do that with an add-on without doing my Invoke, copy, undo, paste.

I am coming to realise that the way I / we use ON must be pretty unique and it may be that pages are used for years and bits and pieces are updated.

Thanks for considering it though :-).  As I think I posted here or elsewhere, even the GraphAPI seems to break pages on "replace".

**Comment by jasonjac2** [comment]
@stevencohn I just want to revisit this within the context of adding new commands (that are identical to existing commands), that instead of updating a page, copy the content they create to clipboard.  This was the request I raised.   I just want to get a feel for how much effort it would be. This would be copying it to the clipboard in a format that could be pasted into a oneNote page.  I am not so familiar with the clipboard formats used, but I realise there is a plain text; html; and probably a ON native.

So the commands:
- "Insert ToC to this page" - identical to current, but instead to adding / replacing content on the page, just copies the result to the clipboard.
- Colorize - instead of replacing the selected text, copy and transform the text onto the clipboard, so it can be pasted back and overwrite the original
- Breakcrumb
Those are the ones I do the... action, copy, undo, paste to get the effect I need.

I know you said "low priority / won't do", but I just want to get a feeling of effort and then I can see if I can sponsor it; get someone to help me get up to speed with c# to the point I can or "UpWork" it :-).

Hope you are well!

**Comment by stevencohn** [comment]
Some commands may be quite easy while others may be very difficult. Most commands loads the page (OneNote hands over XML), edits one or more elements of the XML, and then updates the page by sending back the modified XML of the entire page or at least the modified Outline(s).

An Outline (the graphical boxes that surround your content and can be moved around the page) is the smallest unit that can be saved by OneNote. So, if a page has one Outline but is really large, it needs to save the entire page even if you only update one word.

The problem is that not all commands specifically keep track of which elements are updated within an Outline; they blissfully walk the XML hierarchy and poke at elements as they go along their merry way. 

With little effort, entire Outlines can be copied to the clipboard, perhaps given some trigger like while holding down the Shift key... not sure that's feasible, but just as an example. But it may be a much larger effort to refactor commands to keep track of which elements were updated so only those can be copied independently.

On a similar note, I was contemplating (very loosely) whether it would be possible to create a Compare Pages command. Maybe an inkling of a related idea that could serve two purposes....? However, that too, isn't trivial :-)

**Comment by jasonjac2** [comment]
That all makes sense.
OK, so when do my (After running the command)
ctrl+a (one or more times)
ctrl+c
what is actually loaded up into the clipboard?
HTML / XML?
I know you pointed me to a clipboard viewer, but I am not sure I got as far as decoding all of the data.

You do have me thinking though.  Maybe my standard page should have 2 x containers / outlines.  The top one with the ToC / Breadcrumb, Link to parent... and then the body outline with everything else.

So for ToC to have  a checkbox "copy to Clipboard" - which actually does have more use cases (I don't want a ToC on this page, I want to grab a ToC for this page to put on another page).... "Couple of lines of code" :-) or is it in hours, days or weeks of effort :-). Did I mention I'ld be a taxi service if ever you came to the north west UK.


Finally - so you don't have something that will XML -> HTML?

**Comment by jasonjac2** [comment]
Just to be clear "Maybe my standard page should have 2 x containers / outlines." is so that when you update the ToC or add it to the topmost outline it won't "update" the authors of the main body.

**Comment by jasonjac2** [comment]
also, if you were going to add a checkbox - having the ToC remember your selected options for heading font (which could also include No Heading) and location would be great.  I forget to set them to "Heading 1" & "Current Location" about 1 in every 4 times I do it :-).

**Comment by stevencohn** [comment]
If we're just talking about the ToC command, that one might be one of the _easy_ ones! It generates the ToC separately and then injects it at the chosen location on the page, so it has the isolated contents of what could be copied. That's with the caveat that the "Refresh" hyperlink would need to be rewritten if it's going to point to another page.

A separate Outline could certainly work too if your goal to work around the author update problem.

Note that when you click the Refresh link, that has the choices like Heading and location encoded in that hyperlink. So just clicking Refresh should do it without having to remember to set the options.

**Comment by stevencohn** [comment]
I can default the dialog options based on any existing ToC on the page too. I'll add that to the list.

**Comment by stevencohn** [comment]
FYI, a simplified version of [my ClipboardViewer is here](https://github.com/stevencohn/ClipboardViewer/releases/tag/1.0.0)

Copying OneNote content will place a number of formats on clipboard, based on whether there are binary elements or just text elements. They may include

* OneNote 2016 Internal
* HTML Format
* UnicodeText
* TExt
* DeviceIndependentBitmap
* others...

**Comment by stevencohn** [comment]
Sorry, to answer your last question, XML -> HTML, no I do not have a routine to do that directly since it's massively complicated. What I've done in a couple of instances is either emulate a Ctrl+C to copy selected content to the clipboard and then pull the HTML Format entry off the clipboard or export the page as HTML and digest the .html file.

**Comment by stevencohn** [comment]
@jasonjac2 I take back what I said about enhancing the dialog... it's already there! It looks for the arguments on the Refresh hyperlink and sets fields in the dialog. Are you deleting the title line and the Refresh link? That would cause the dialog to revert to its defaults.

**Comment by jasonjac2** [comment]
Refresh: I tend to just copy the table / box that just has the ToC and not the heading.  I had looked at the format of the URI before and saw it holds the "here", but hadn't appreciated it held the other arguments as well.  I'll  use that from here on in.
