### ISSUE TITLE
References | Create Map - Doesn't log all pages.

### ISSUE THREAD

**Issue by jasonjac2** [stevencohn/OneMore#541]
**Describe the bug**
There are 85 pages in a section and when I ask it to:  Create Page Map | The current Section | 
unchecked: include cross-notebook.
The subsequent page has top level links to 14 pages and indented under them are links to pages in the notebook (i.e. links on the page it is indexing).

So I was expecting 85 pages, but got 14.  I have done this on 2 installs on 2 PCs looking a the same section.

I have looked in the log and there are a bunch of ... not found in scopy {guid} on Todo/JAC TODO / JAC
which I assume are pages outside this notebook and looking at one of them and the XML of the page, I can see that.

**To Reproduce**
1. Go to OneMore Button
2. Click on References | Create Map Page
3. in dialogue, select "section" and ensure "include cross-notebook"
4. Run it.
5. 

**Expected behavior**
1 page with 85 top level links to the pages in the section. 

**Screenshots**
The Graph Page
![image](https://user-images.githubusercontent.com/68282090/179502806-13040f1b-541c-455f-81bb-411533e64ab9.png)
The actual Structure
![image](https://user-images.githubusercontent.com/68282090/179502877-f8465e1e-fa44-4291-9e2c-af716a78031a.png)

**Environment (if applicable):**
OneNote - 32 bit - Version 2206 Build 16.0.15330.20196 Click to Run)
OneMore 4.18

**Additional context**
I thought it might be becuase I hadn't visited those pages on that install, but 2 x installs generates the same outcome.

**Comment by jasonjac2** [comment]
Anna (JAC) has a link to an external page, but it is outside this notebook, to that end, it is "interesting".  

I would have thought leaf pages even without links would still be "interesting", but I completely take it on board about your snippets | ToC tool being enough.  A page with no links out of it is interesting becuase it is more likely to be "orphaned"

**Comment by jasonjac2** [comment]
Just to keep this alive and to answer your point:
- yes, an option to include boring / leaf pages is a good idea
- Also a scope and I would say it would be: This Notebook / All Notebooks

**Comment by stevencohn** [comment]
Working as designed. The map is intended to report only inter-page links within the given scope and I it is doing precisely that. The scope limits the _links_ not the pages themselves. If you want to see more then broaden the scope.

**Comment by jasonjac2** [comment]
Sorry, replied without re-reading my thread.  Would it be an option to include initial pages, regardless of whether they have links out of them or not.  So back to my initial post where I only got 14 pages rather than the 85 I expected?

Again, sorry for wasting a round trip in the discussion by being lazy, I jumped back in to ensure you weren't waiting for me for anything.  

"Perhaps an option to include these interesting/boring pages would help ;-)"
Yes please.
