### ISSUE TITLE
Create page Map without including links to links on those page, i.e. a ToC 

### ISSUE THREAD

**Issue by jasonjac2** [stevencohn/OneMore#542]
**Is your feature request related to a problem? Please describe.**
So I need tables of contents for each of my notebooks AND to be able to further use those as lists of links.

**Describe the solution you'd like**
The Create Page Map is kind of it (aside from the bug: #541 ), but it:
- has an indented list for links on those pages - this is great as long as it is optional, so add a checkbox for that on the invocation dialogue.
- Ideally would be able to be in a format that lends itself to being copied to be used outside onenote, but keep the links.
e.g. have options for output (
-indentation to match ONs sub pages; one - per indent"
- use a character for the indent, so you can pull it into excel and use that character
- show tags in line on the output
- include last updated date
- optionally have the caption as the relative page Section \ parent page \ page

**Describe alternatives you've considered**
Gem / OneTastics ToC
Edit: Just looking at OneTastics ToC macro seems to give pretty good output.  I would like more control over the layout, but it is pretty good.  As you may be getting, I am looking for something very flexible. 

**Additional context**
Well, just a thank you for your continued support and work.

THE FINE PRINT
This is a hobby project that I started for myself. I'm happy to take requests and will promise to consider each one carefully but offer no guarantees that I will ultimately agree to their usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
You want the Snippets / Table of Contents command

<img width="419" alt="image" src="https://user-images.githubusercontent.com/9964757/179515308-89f8eb42-abe2-4cde-b13f-0de59704de00.png">

**Comment by stevencohn** [comment]
It doesn't have all of the features you're looking for but gets you most of the way there

**Comment by stevencohn** [comment]
I've been thinking the ToC command should be split into two. One snippet that inserts a ToC in the current page. And another on the References menu for the second two options to generate ToC pages

**Comment by jasonjac2** [comment]
Unfortunately anything that edits the current page for me is a no-no for #514 reason.

I think a Mega ToC that has the options to do a full map of pages, links out, links back, options to look at all your notebooks for links back, create page, create "output" e.g. HTML / XML / Excel would be amazing.  It could have a "crawl and do it while the PC is not being used option" as I think it would probably take a very long time.
