### ISSUE TITLE
Anchoring ink to text

### ISSUE THREAD

**Issue by Raquo116** [stevencohn/OneMore#543]
**Is your feature request related to a problem? Please describe.**
Is there any way to anchor ink to a body of text? For example, I circle a word, and highlight some others:
https://stackoverflow.com/questions/49816164/anchoring-ink-to-text
can you do something about it? This is the most IMPORTANT feature for someone making notes with both text and ink.

**Describe the solution you'd like**
http://www.onenotegem.com/a/documents/gem-for-OneNote/Link_Tab/2019/1124/1039.html
maybe something like this.
or 
![sample1](https://user-images.githubusercontent.com/13005473/179834754-61f406ab-398f-400b-bdc6-f069e46870c6.png)

![sample2](https://user-images.githubusercontent.com/13005473/179834770-e68042f6-6f8b-4a34-9f03-054566a0ffa3.png)

This is actually in Microsoft WORD which can do it without any problem.
**Additional context**
No matter how many times I have requested any feature, you are the one I look up to. Kudos and Thank you for putting so much effort.

**Comment by Raquo116** [comment]
is there any plug-in to solve this issue ? @stevencohn

**Comment by stevencohn** [comment]
So there's not really a good way for OneNote to do this. It positions ink absolutely relative to the page, not anchored to other objects on the page.

Gem, in my understanding, uses a dynamic peek/polling technique to estimate positioning. In my experience, this is clunky at best and breaks down easily.

I know of no other addins that solve this. There have been many feature requests to Microsoft on it.

**Comment by Raquo116** [comment]
So there is no other option but to wait for Microsoft to fix this (which I know won't do anything) ?
Do you know any other note-making app which can fulfill this functionality? (Apart from Microsoft Word which does that efficiently)?

**Comment by stevencohn** [comment]
I was going to say Microsoft Word 😞
