### ISSUE TITLE
As shown in the figure, solve

### ISSUE THREAD

**Issue by CH00CMJ** [stevencohn/OneMore#544]
![Snipaste_2022-07-21_19-49-59](https://user-images.githubusercontent.com/109736641/180207033-8c967597-b519-4f35-a778-4328d7192c55.png)

**Comment by stevenmcohn** [comment]
I'm sorry I don't know what's happening here. Can you please translate it to English?

**Comment by stevencohn** [comment]
I'm sorry I don't know what's happening here. Can you please translate it to English?

**Comment by CH00CMJ** [comment]
@stevencohn OK, I'm sorry, too. Forgive me for being thoughtless.
It pop-up prompt👇：
**OneNote cannot connect to OneNote. Please refer to the log file for exception details.**

**Comment by stevencohn** [comment]
Was it working previously? Did you leave a OneMore dialog open for a long time without interacting with it? 

If you restart OneNote, does it start working again?

**Comment by CH00CMJ** [comment]
No, it was like this at the beginning.I tried everything I could think of,Still can't let it work normally.

**Comment by stevencohn** [comment]
Can you send me the log file? It should be here %TEMP%\OneMore.log

**Comment by CH00CMJ** [comment]
[OneMore.log](https://github.com/stevencohn/OneMore/files/9160176/OneMore.log)
OK, I found it.

**Comment by stevencohn** [comment]
First I noticed that you're using an old version of OneMore 4.11.

The latest version is 4.18 [available here](https://github.com/stevencohn/OneMore/releases/latest)

I would also suggest patch-installing OneNote/Office. Your machine seems to be missing an interface required by OneMore

**Comment by CH00CMJ** [comment]
Yes, I have just installed the new version. How should I solve the interface problem?

**Comment by CH00CMJ** [comment]
Yes, it's mine.I have administrator access.
I'm trying to repair Office.
![image](https://user-images.githubusercontent.com/109736641/180244501-b339d138-ab32-4783-ab61-12b47fb3b21f.png)

**Comment by CH00CMJ** [comment]
The problem has been solved because other versions of office software have been installed and the registry file is too messy. After uninstalling office, clean the registry and reinstall it again. Now, not only onemore, but also other plug-ins can be used.

I'm very happy.Thank you very much.
