### ISSUE TITLE
Install error on latest version

### ISSUE THREAD

**Issue by NCJADCoder** [stevencohn/OneMore#545]
Getting this error on the latest installer.
![Error-OneMore](https://user-images.githubusercontent.com/13773476/180264434-458907bd-6da9-4bfa-aef8-a0956ffe4d7e.png)
[OneMoreSetup.log](https://github.com/stevencohn/OneMore/files/9161040/OneMoreSetup.log)

**Comment by jasonjac2** [comment]
which installer vs os version are you using.  64 bit installer for 64 bit OS - do not match the installer against the OneNote bitness.

**Comment by NCJADCoder** [comment]
The install error occurred during an upgrade of the already installed add-in leading to the product uninstalling itself.  Using the 64-bit installer today, originally retried the 32-bit download, has resolved the issue.

**Comment by stevencohn** [comment]
Closing this since use the right installer seems to have resolved the issue.
