### ISSUE TITLE
Upload all the images in the selected text or in the current page to imgur.com (or similar) and replace them with linked images if possible or add links to them

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#547]
This feature can be easily leveraged when the OneNote content is exported or processed by third party scripts.
One of the major challenges you have when you do that is that the pictures are individual objects which have to be retrieved by themselves, you do not have them locally.
I see this working like this:
-select the text that contains the pictures you want uploaded
-click on an Onemore button and upload all the pictures in the selected text (or in the page if nothing was selected)) to imgur.com or something similar
-add their respective imgur.com links to the images like so
 <one:Image hyperlink="https://i.imgur.com/pe2hgFlo7.png">
                      <one:Size width="432.0" height="183.0" />
                      <one:CallbackID callbackID="{5156BEC9-71C2-4342-8C65-BA6B34561693}{165}{B0}" />
 </one:Image>
There is an app called ShareX that has a list of the most popular upload destinations
![image](https://user-images.githubusercontent.com/17384308/180887499-f94ea36d-1da2-4ef7-b201-4658a4378e92.png)

**Comment by stevenmcohn** [comment]
What are you trying to accomplish? This is a bit of work so please help me understand the real value here.

**Comment by stevencohn** [comment]
What are you trying to accomplish? This is a bit of work so please help me understand the real value here.

**Comment by 1001QAdotNET** [comment]
I often need to export content from OneNote to HTML and I need to be able to link the images in the text
if I can have them uploaded to a third party and then just link them back in the exported HTML then that would save the work required to retrieve the image (via a script) and then save it locally as a jpg/gif etc and then upload it to a third part and then link it in the exported text
It is practically a way to simplify the export to HTML and to make the exported HTML independent of the location where the HTML sits (you do not need to move the images and the HTML together which could be lots of files. I know there is embedded HTML but that is not something you should upload on a webserver)

**Comment by 1001QAdotNET** [comment]
I am now seeing that I can export the page as HTML with all the images ...I think I can work with that
