### ISSUE TITLE
Keyboard Shortcuts for Favourites and More for Keyboard Warriors

### ISSUE THREAD

**Issue by jasonjac2** [stevencohn/OneMore#548]
**Is your feature request related to a problem? Please describe.**
You have crammed some great commands in "More" Ribbon, but AFAICS you have to use to mouse to invoke them

**Describe the solution you'd like**
Programmable keyboard shortcuts for the 3 Ribbon buttons + good keyboard nav once you have clicked them.

**Describe alternatives you've considered**

**Additional context**
I am using your copy link to page etc more and more, but hate using the mouse (I am a developer)

Also - it would be great if the dialogue box "copied to clipboard" when you use link to page and link to para was optional, it is an extra audio ping and enter I don't need.
Also - the copy link to page and copy to para menuitems are not enabled when you are in the title of the page (at the top), the copy link to page really should be.

Keep up the GREAT work.

THE FINE PRINT
This is a hobby project that I started for myself. I'm happy to take requests and will promise to consider each one carefully but offer no guarantees that I will ultimately agree to their usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
Cannot bind keyboard shortcuts to the three main More ribbon buttons; the ribbon doesn't work that way. But many of the common commands have shortcuts including the custom styles. Go to More/Settings/Keyboard to see them.

I can add placeholders for more commands including the Copy Link to Page/Paragraph commands. They will appear in the Keyboard list but be unassigned until you assign them. Better to allow the user to decide which sequences they want to use than try to make up sequences which are in short supply.

The dialog box and "ping" (I like that name for it) is there so you know you did something. I'll try to come up with a less intrusive way but, well, this works. It's simply using Forms.MessageBox.Show()

As for the Copy Link to XX commands not enabled when cursor is in the page title - fair point.

FWIW, as a developer... I know devs that love all the shortcuts and then there are those like me that remember a select few but normally use the mouse. This is why OneMore grows slowly - to suite my feeble mind.
