### ISSUE TITLE
Requirements to Build  Add-In..

### ISSUE THREAD

**Issue by jasonjac2** [stevencohn/OneMore#549]
**How can I help you?**
I don't currently have VS installed.  I want to be able to build, mod, feedback and so could do with some notes in the Dev pages or here relating to build environments that work.

It would be the community edition of VS I think.

I will try and keep my VS questions to a minimum I promise.  I have other communities I can ask those in.
But ideally, notes on valid set ups that a "dummy" non VS developer can follow and get to a successful build.

TIA.

THE FINE PRINT
This is a hobby project that I started for myself. I'm happy to take requests and will promise to consider each one carefully but offer no guarantees that I will ultimately agree to their usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
There is a list of minimum prerequisites on the home page here https://github.com/stevencohn/OneMore#minimum-prerequisites-for-development

**Comment by jasonjac2** [comment]
Thank you, I didn't find that when I was looking earlier this AM.  I will probably start working on this next week.

**Comment by jasonjac2** [comment]
I am downloading and installing VS 2022 community, should I stick to 2019?

**Comment by stevencohn** [comment]
2022 should be good
