### ISSUE TITLE
Feature Request: Add to the context menu the option Move or Append the selected text  to a new or existing page (same or different section)

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#55]
I often have to read documents that have mixed content (belong to different topics I am researching) .

I would like to be able so select text on a page, right click and say: send the selected text as a new page either in within the current section or in another section, or append to an other existing page within the same section or in a different section

**Comment by stevencohn** [comment]
With the number of clicks that would be required, I'm not sure if this is much different than just cut and paste
