### ISSUE TITLE
Storage analysis doesn't show backup copies if their location has been customized

### ISSUE THREAD

**Issue by julie777** [stevencohn/OneMore#551]
**Describe the bug**
I have set my backups for OneNote to be stored in a subdirectory of the Notebooks directory. OneMore doesn't find them to add to storage report.

**To Reproduce**
Change location of backups and run storage report.

**Expected behavior**
I would like my backups to be analyzed

**Screenshots**

**Environment (if applicable):**
 - OneNote Version: O365 32bit running locally on Windows 10 64bit
 - OneMore Version: 4.18

**Additional context**
I suspect that this is because OneNote does not provide access to the location of backups.
Adding a setting to OneMore for location would be an easy fix.

Note: I am one of those people who hates the Windows way of burying everything in AppData. I change many of the default locations for apps to make things accessible. (Yes, I am a developer)

**Comment by julie777** [comment]
I forgot to mention that in the storage report for sections, I was initially confused by "# of copies". I think changing the column name to "# of backups" would be more obvious.

**Comment by julie777** [comment]
I did some more digging and I am now more confused. At the top of the Storage Analysis it shows the notebook location and the backup location. The backup location show is my custom location and the link takes me there. I have many backups in that location, so it is a mystery why there are no backups shown in the summary.

Locations:
![image](https://user-images.githubusercontent.com/5090005/182203688-9b12ad30-c99c-491e-af79-88205391ca21.png)

Directory listing:
![image](https://user-images.githubusercontent.com/5090005/182203779-dd97d925-2c1d-44ad-912a-e1e0ac548b32.png)

Section Output:
![image](https://user-images.githubusercontent.com/5090005/182203833-6b376de4-492e-4f2d-a008-dda905361671.png)

You can see the backup copies missing from the section output for Notebook: Development, Section: General

**Comment by stevencohn** [comment]
I assume this says "2" since you seem to have two copies of each section

<img width="347" alt="image" src="https://user-images.githubusercontent.com/9964757/182932463-65f2b434-228c-4e72-b783-525b46be4336.png">

**Comment by stevencohn** [comment]
Unfortunately, I haven't been able to reproduce this. I've repeated your steps, setting my backup location beneath the default notebook location, ran a new backup from the Options dialog, and generated a new report and it worked fine.

Make sure your custom backup path does not include the "16.0\Backups" portion of the path; OneNote will append this automatically even if you have it there, e.g. you may end up with 16.0\Backups\16.0\Backups" and that may be confusing it.

**Comment by julie777** [comment]
Here are my settings

![image](https://user-images.githubusercontent.com/5090005/190703256-8a48aa83-13db-4b45-8424-3f6321bbb0bb.png)


I just installed the new update and ran it again. I only see # of copies for notebooks stored on onedrive.
I am not adding the 16.0 as you can see in the screen capture. It has been added to the actual directory and there are a variable number of backups for each notebook section in that directory.

**Comment by stevencohn** [comment]
Closing as stale. Not reproducible
