### ISSUE TITLE
Storage Analysis incorrectly labels closed notebooks as Orphaned 

### ISSUE THREAD

**Issue by julie777** [stevencohn/OneMore#553]
**Describe the bug**
Those of us who have many notebooks often have some closed. A local notebook that is found in the notebooks directory should be considered closed and not orphaned.

**To Reproduce**
1. Close a local notebook
2. Run Storage analysis

**Expected behavior**
Closed notebooks should be shown in the list of notebooks.

I do understand that if there are backups of notebooks that are not open and not in the local notebook folder there is no way to know if they are closed online notebooks or actually orphaned.

**Screenshots**

**Environment (if applicable):**
 - OneNote Version: [e.g. Office 2019, O365, also 32bit or 64bit?]
 - OneMore Version [e.g. 3.4 - from the About dialog or from the log file]

**Additional context**
There are many reasons that a user might not have all notebooks open. This should be taken into account.

Note: I really like that OneMore has the ability to actually identify and list closed notebooks. (Onetastic does not have this ability.)
With OneMore I could, for example, generate a table of contents for "all" notebooks, including closed ones. The option to include closed notebooks would be very handy for other tasks as well.

**Comment by stevencohn** [comment]
Working as intended so not a bug. But classified as an enhancement.
