### ISSUE TITLE
[Feature Request] How to navigate history of viewing, not edition?

### ISSUE THREAD

**Issue by pytkr** [stevencohn/OneMore#555]
I'm always frustrated when viewing page in onenote and want to go back to another page with Alt+Left/Right, because, that page needs pressing too many times of the shortcut to arrive.

**Describe the solution you'd like**
so better solution is like chrome navigation buttons.

**Comment by jasonjac2** [comment]
I didn't realise in chrome that if you click and hold the nav buttons, that you see the history (I assume of that tab). In ON, I know you can ask the COM & Graph API for a list based on edit stamp - I am not sure you can for the Navigation.  to this end I think you would have to either be able to subscribe to an event or just set a timer and observe what page you are on and keep the list internally within the tool.

Also, then you have to deal with multiple instances (I always have 4 or 5 instances up).  I like the idea though for sure.  I have a similar kind of app running that observes what app is upmost every second and what the title bar says, it helps when I forget to set billing and need to go back and work out what I was doing.

**Comment by jasonjac2** [comment]
@pytkr I notice @stevencohn hasn't tagged this yet, but has others.  Did you raise it using the "New Issue" -> "Feature Request"?

**Comment by stevencohn** [comment]
Not sure this possible because OneNote doesn't provide navigation events that OneMore can monitor.
