### ISSUE TITLE
TOC in current Section

### ISSUE THREAD

**Issue by coderxyz** [stevencohn/OneMore#56]
Really excited to see the Insert Calendar feature. I think with few more updates, I can uninstall Onetastic from OneNote 

1. TOC in current section - Creates a new page with table of contents of the current section. I use this macro quite a lot to create TOC without linking each page manually. 
2. Text to table - Converts selected text into table. (see issue #57 )
3. Sort table - Sorts selected table by selected column (see issue #58 )

**Comment by stevencohn** [comment]
Renamed from "Bring these macro features from Onetastic" to "TOC in current Section" and move 2 and 3 to their own tickets.

**Comment by stevencohn** [comment]
TOC now supports a) headings on page, b) pages in section, and c) sections in notebook. 
https://github.com/stevencohn/OneMore/releases/tag/2.18

**Comment by stevencohn** [comment]
Text to Table #57 completed and available in release 2.19 https://github.com/stevencohn/OneMore/releases/tag/2.19

**Comment by stevencohn** [comment]
Regarding your sort request, OneNote already has a built-in sort feature for tables. Place the cursor in any cell in a column and click the Sort button in the Data group of the Table ribbon. I should have remembered that before creating ticket #58 ; I'm going to reject that ticket.
