### ISSUE TITLE
Keyboard shortcuts and context menu option for custom snippet(s)

### ISSUE THREAD

**Issue by vfxturjo** [stevencohn/OneMore#560]
**Is your feature request related to a problem? Please describe.**
Although custom snippets make life better,
going to the (Favourites -> My Custom Snippets -> "Snippet name") is cumbersome. 
I saw the ability to add keyboard shortcuts for builtin snippets, also the context menus.

**Describe the solution you'd like**
Please add ability to use custom snippets with:
- custom keyboard shortcut
- right mouse button context menu option

**Comment by stevencohn** [comment]
Will address as part of #548
