### ISSUE TITLE
where are created Custom Styles supposed to be seen?

### ISSUE THREAD

**Issue by rd836** [stevencohn/OneMore#572]
I'm using OneMore Add-in for Oneote 2016, Version 4.18. Portion of log file:
47668:1] Starting dllhost 47668, CPU=3200Mhz, en-US/en-US, v4.18, OneNote 15.0, Office 16.0
47668:1] ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.15427.20210)
47668:1] ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
47668:1] ..OneAddInsUpdate(custom[])

When I have some text highlighted to attempt to create a Custom Style from, by "Custom Styles", then "Create Style from Selection" I get the "New Custom Style" dialog box, for a "Character - words in paragraph" Style Type, and hit "OK", the spinning blue circle spins for a while, but I can't find _where_ the style went to ever use.

How can I find it to actually use it?
Is there some portion of the log file I should post or attach to see what is happening?
[OneMore.log](https://github.com/stevencohn/OneMore/files/9417890/OneMore.log)

**Comment by stevencohn** [comment]
The spinner is concerning but it should define the style. When defining your custom style, give it a unique name, something like this

<img width="345" alt="image" src="https://user-images.githubusercontent.com/9964757/186490629-aede093c-ef1c-4ff8-9d44-dccc5149402a.png">

Then it should show up in the OneMore Style Gallery like this

<img width="172" alt="image" src="https://user-images.githubusercontent.com/9964757/186490766-20e13499-2f23-4f10-91c7-179d782aa22b.png">

**Comment by rd836** [comment]
I tried several times, some giving my own name to the style, and others leaving the default Style-1234 type name, but they never showed up anywhere. There was no failure message, just nothing new showing up in the Gallery. My question was in case it would show up somewhere else than the Gallery.

Meanwhile, I set an option to "Check for OneMore updates when OneNote starts", and also "Context Menu Options" for the Edit Menu for UPPER case and lower case, but then the whole side menu just shrunk to icons, with no text at all. I couldn't see how to the normal side menu back, so uninstalled the program to wait for the next release to try my luck again.

**Comment by stevencohn** [comment]
I'm sorry to hear that. I'll keep an eye out for problems in this area and update this thread if I find anything.

**Comment by rd836** [comment]
I wonder if having tried the two well known commercial add-in packages left any remnants behind after their being uninstalled that could possibly have interfered with OneMore.

Your package is the most promising of the three, and I'll look into contributing, as it gets further along.

**Comment by stevencohn** [comment]
I spent some time today looking into this. My suspicion is that it can't write to your AppData\Roaming\OneMore\Themes folder or the XML files in there are corrupt. I'm adding more error checking to the code that reads and writes those files.

**Comment by stevencohn** [comment]
Closing as no-repro
