### ISSUE TITLE
Start Timer

### ISSUE THREAD

**Issue by geirgramvik** [stevencohn/OneMore#586]
The CountDownWindow is ONLY shown/visible when the active OneNote window is on the PRIMARY screen.

If I use OneNote on a screen that is not defined as the primary screen in windows settings, the CountDownWindow will not be displayed in the top right hand corner of the OneNote window. I can see on the task bar that the CountDownWindow has started, and I can see that the timer is running when I hover over the task bar icon, but the CountDownWindow itself is not displayed on any screen.

**Comment by jasonjac2** [comment]
I just found this feature today and had a thought: It says countdown, when it is a count up.

**Comment by stevencohn** [comment]
> I just found this feature today and had a thought: It says countdown, when it is a count up.

which only shows up when you hover the mouse over the taskbar icon. You people are too observant!

**Comment by jasonjac2** [comment]
What you need it more sponsorship :-). I have Soooo many features and tweaks,.....

**Comment by stevencohn** [comment]
Is your primary screen larger than the screen hosting OneNote? It's probably using the geometry of the screen hosting OneMore but displaying it on the primary screen so, if it's larger, then the window will be off-screen. I can fix that.

Note you can right-click the taskbar icon and choose Move then click down and move your mouse to bring it into view.

**Comment by geirgramvik** [comment]
Thanks for your follow-up.

 

Screen details: 

*	Screen 1: Microsoft Surface Laptop Studio. Integrated. Resolution 2400x1600 (recommended)
*	Screen 2: HP  Z27qG3. Rsolution 2560x1440 (default)

 

Screen 1 is typically the primary. 

 

When I right-click on the taskbar icon (countdownwindow), the only option I get is “close all windows”

 

/g

**Comment by stevencohn** [comment]
Windows 11? You'd need to Shift-RightClick to see the old style menu with the Move command

**Comment by stevencohn** [comment]
Any, if you're running OneNote on screen 2, the timer window may in fact be out of bounds on screen 1 since it is smaller. I'll do what I can to make sure it shows up on the correct screen or isn't lost.
