### ISSUE TITLE
Non indexed search - background crawler

### ISSUE THREAD

**Issue by jasonjac2** [stevencohn/OneMore#589]
**Is your feature request related to a problem? Please describe.**
It appears that any search that leverages ONE or windows search is flawed.  I just search for an IP address 10.0.0.14 and got 0 hits and 10.0.0.135 and got a bunch of hits, but I know the .14 exists!

**Describe the solution you'd like**
So I want a search that you can select a bunch of notebooks or all and kick off a full-non indexed search.  A better long term option would be to have a crawler and indexer, so maintain your own, but to start with:
- search criteria
- crawl
- Some useful notification when done.
I guess as a separate process if it would interfere with general operation.
Save results to HTML / a new page.
Cancellable / restart
Set a priority to decide how aggressive it will be with processor etc.

At the end of the search I can be confident I have a clickable output with ALL the occurrences that match.

**Describe alternatives you've considered**

**Additional context**

THE FINE PRINT
This is a hobby project that I started for myself. I'm happy to take requests and will promise to consider each one carefully but offer no guarantees that I will ultimately agree to their usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
OneNote uses Windows Search behind the scenes as its own internal crawler. If your searches are not finding text then consider rebuilding your Windows Search index. There are plenty of articles explaining how to do this.

OneMore's search relies on OneNote's integration with Windows Search. I have no interest at this time in building my own.

**Comment by jasonjac2** [comment]
"I have no interest at this time in building my own."
I completely understand - thank you.

"If your searches are not finding text then consider rebuilding your Windows Search index. There are plenty of articles explaining how to do this."
I think Gem has a crawler type service and it would definitely be one of my pet projects to develop one.  The problem is they you don't know what isn't found, e.g. it finds 50 occurances of a term, but infact there are 55 and you need to update all 55. 

My experience of the MS Indexing engine is it great when it is working, but you always get that nagging doubt.

Gem has a concept of "unindexed pages", when you use their search, but I can't really work out what that actually means and what you should do to get them indexed, other than tell Windows to re-index all (which BTW means my outlook searches etc are really poor for the next 24 hours).

As always your time is much appreciated.

**Comment by stevencohn** [comment]
I'd be interested in what you do, especially if your solution will handle multiple languages (parsing Chinese, Japanese, Korean into words will likely require a third-party translator/transliterator like GTranslate)

**Comment by jasonjac2** [comment]
Ha :-).  I struggle with English.  Unfortunately, having written all my systems for English and British market, I am way behind the curve and see unicode and multi-lingual as a dark art.
