### ISSUE TITLE
Feature request: the ability to Copy (not move) section groups between notebooks and inside the same notebook too

### ISSUE THREAD

**Issue by osman1963** [stevencohn/OneMore#59]
Currently we can only 'move' a section group, however lots of users (me included of course) need to copy the section group to other locations, while keeping the original one in place.
That would be really helpful.
And thanks again for the awsome work you are doing 👍 👍

**Comment by stevencohn** [comment]
Released - https://github.com/stevencohn/OneMore/releases

**Comment by osman1963** [comment]
Thanks a million man, works like a charm :)
