### ISSUE TITLE
Footnotes with empty / blank lines will be split / screwed up by inserting the next footnote.

### ISSUE THREAD

**Issue by geirgramvik** [stevencohn/OneMore#592]
See attachment for example.
[Footnote bug.pdf](https://github.com/stevencohn/OneMore/files/9484900/Footnote.bug.pdf)

**Comment by stevencohn** [comment]
This is not a bug but admittedly is not well documented. A footnote must be a single paragraph, which in OneNote is a block of text without any hard carriage returns. A hard carriage return is when you simply press the Enter key. 

You can overcome this by using software carriage returns which is done by holding down Shift while pressing Enter. Any subsequent footnotes will then appear in the proper sequence.

I'll update the [Wiki page](https://github.com/stevencohn/OneMore/wiki/Reference-Commands#add-footnote-ctrl--alt--f) to explain this better.
