### ISSUE TITLE
Discussion about regular review of notes

### ISSUE THREAD

**Issue by yxiaoa** [stevencohn/OneMore#593]
First of all, thanks for this great tool!

For my part, I like to review my notes regularly. However, it's difficult to navigate to pages that haven't been reviewed in a long time, as they may have different review intervals. So I've added some features to satisfy this, and I wonder if others have the same requirement.

Feature:
Last review date and review interval are added as meta data to the page xml and an outline is added to the page showing the review information.
Mark page reviewed: set last review date to today
Set page review info: update the meta data from the outline
Go to page need review: navigate to the page with the minimum number of days left between today and the next review date.

This is just my case, is there any other way to review notes regularly?

Thanks again!

![image](https://user-images.githubusercontent.com/46472086/188846189-eefe358c-89d8-4f8d-a678-e5988c4a06a7.png)

**Comment by jasonjac2** [comment]
"So I've added some features to satisfy this, and I wonder if others have the same requirement." you mean you have forked the code and added the feature - if so very cool.

I have a similar requirement, but I would be happy to have it as an on page tag only as I would possibly manually edit it.
As we have 1000's of pages, I would add the ability to produce a report / page / excel spreadsheet with a to-review with the key information - page link / name, last review, interval etc.

**Comment by stevencohn** [comment]
This is one of the reasons why I started OneMore, to both inspire others and learn from others.

Your fork doesn't have any changes or feature branches. I guess you haven't committed them yet. If you'd like to submit a pull request on my repo, I'll take a look.

**Comment by yxiaoa** [comment]
> "So I've added some features to satisfy this, and I wonder if others have the same requirement." you mean you have forked the code and added the feature - if so very cool.
> 
> I have a similar requirement, but I would be happy to have it as an on page tag only as I would possibly manually edit it. As we have 1000's of pages, I would add the ability to produce a report / page / excel spreadsheet with a to-review with the key information - page link / name, last review, interval etc.

Glad to see the same requirement!

I added the feature but haven't committed yet as it's pretty rough now. A summary table generated as a page is also under consideration.  However, I found it quite slow to read each page's review information. Let me see if there is any way to speed this up.

"as an on page tag only" - do you mean don't set addtional meta data to xml? Actually, the outline generated in the image can be editted and loaded when "Set page review info" is pressed.

**Comment by yxiaoa** [comment]
> This is one of the reasons why I started OneMore, to both inspire others and learn from others.
> 
> Your fork doesn't have any changes or feature branches. I guess you haven't committed them yet. If you'd like to submit a pull request on my repo, I'll take a look.

OneMore saved my OneNote and make it possible for me to add the feature. Frankly speaking, this is my first time developing on C#, and I'm not sure if it is necessary to send pull request. So I added this issue.
Since this feature is under development and pretty rough, I would like to make some improvements before sending the pull request.

I'm realy thankful to you and OneMore!

**Comment by stevencohn** [comment]
Hint: page meta elements are also added to the hierarchy XML. You can search these pretty quickly using River.OneMoreAddIn.OneNote.[SearchMeta](https://github.com/stevencohn/OneMore/blob/4f9b641cb18b55026aca3dcdbb7b5f50177805b0/OneMore/OneNote.cs#L1258)() - _click the link to see the source_

**Comment by jasonjac2** [comment]
_"as an on page tag only" - do you mean don't set addtional meta data to xml? Actually, the outline generated in the image can be editted and loaded when "Set page review info" is pressed._

I like to be able to edit things in plain sight as well as with menus etc, so I have things like
TODO_JAC:2209:JAC:02/09/2022: This is a todo for Jason.
And so you can look and interact with this without actually needing the add-in (e.g. if I am using on the web or shared with someone who doesn't have oneMore.

It is jus the old coder in me, where you just have text resources and nothing else.  So I would come up with a syntax
REVIEW: Last: dd/mm/yyyy Next: dd/mm/yyyy Code: <> Score:  <> Comment: <>.

You have inspired me to continue to install C# and get coding. I started, but got waylaid by work.

& yes, thank you for OneMore Steven

**Comment by stevencohn** [comment]
@jasonjac2 that certainly makes sense and, as a fellow old schooler, I like the idea. I wrote OneMore however to get away from the Onetastic approach that was fragile and unapproachable to too many non-programmers. Having text meta data surfaced right on the page is convenient, but makes it easy to break such that the subsequent automated functions no longer recognize it.

@yxiaoa Yes, the Page model has extra logic that you don't need in this case and can be circumvented for performance sake.

**Comment by stevencohn** [comment]
@jasonjac2

> REVIEW: Last: dd/mm/yyyy Next: dd/mm/yyyy Code: <> Score: <> Comment: <>.

What might be in the Code and Score fields?

**Comment by jasonjac2** [comment]
Hi Steven, you've been busy :-). 
Code: Outcome code e.g.: complete / in progress / needs work (see score) / No Longer Of Use / Not Going to Review / Scratch Page complete
Scratch Page complete => it is a quick page, doesn't follow the standards and anything valuable has been taken off of it.
Score: 0 - ..... The higher the number the better the quality.

**Comment by jasonjac2** [comment]
" I wrote OneMore however to get away from the Onetastic approach that was fragile and unapproachable to too many non-programmers. Having text meta data surfaced right on the page is convenient, but makes it easy to break such that the subsequent automated functions no longer recognize it."
I understand and that makes sense.  I didn't really know about extra meta data against each page, but of course, it makes sense.  So maybe an export / visualiser of meta data would be the answer / compromise.  Again, I'm prompted to complete my install of C#.  I don't suppose you would fancy doing a talk for our user group (mainly Delphi, but a good proportion of them are also C# devs - 20 - 25 on a zoom call :-) ).

**Comment by stevencohn** [comment]
may implement as part of #793

**Comment by yxiaoa** [comment]
> may implement as part of #793

I tried the navigator function and it seems that it cannot find which pages need to be reviewed. So, I send a PR about my changes.
The page review feature gives me what I need. But it is just personal requirements and maybe not suitable to be merged.
So, I think it for reference only and thank you again for OneMore!
