### ISSUE TITLE
Can't export VCF files

### ISSUE THREAD

**Issue by Cristian9828** [stevencohn/OneMore#598]
When exporting file in html in specific folder, it works for images but doesn't take out the included VCF file.
I use Microsoft Lens. It saves business cards scanned in OneNote. Is there a way to export all the vCards created?

**Comment by stevencohn** [comment]
It should export VCF files without issue. You need to check the _Include attachments_ box

<img width="223" alt="image" src="https://user-images.githubusercontent.com/9964757/189922646-f185f50e-59fb-4adc-b4a0-43a18c7cfe1a.png">

Here's I've used Lens to import a card (redacted to protect the innocent)

![image](https://user-images.githubusercontent.com/9964757/189923338-7ca271b5-166a-4d2a-a817-ce7ba6f37392.png)

The VCF file will be exported to the same folder as the HTML file

![image](https://user-images.githubusercontent.com/9964757/189923657-5d8a181f-2657-4e76-8c7a-feb0d91af2db.png)

**Comment by Cristian9828** [comment]
![image](https://user-images.githubusercontent.com/51407503/189934508-0edfff5e-e00c-4302-a35b-935fd6086e41.png)
Done the same operations, exactly like you did, but this is the result. I don't see the vcf file!
Do I need any setting or something similar?

Thank you

**Comment by stevencohn** [comment]
I think I need more info. If you're willing to share, could you export the file as a OneNote file (.one) and attach it here.

**Comment by Cristian9828** [comment]
Already tried with another file and it worked! The only difference I can see between the two files, is the dimension. For the rest they are simply two VCFs, exactly the same.
Can be the file dimension the answer? 200Kb (works) vs 301Kb (doesn't work) in my case.
