### ISSUE TITLE
Bug in the 'Favorites'

### ISSUE THREAD

**Issue by osman1963** [stevencohn/OneMore#60]
When trying to add a page with a non-latin title to the favorites, it first added a blank link (it added the page to the list but without showing the title), then it stopped working alltogether (clicking on favorites opens a tiny blank list). This occured with an Arabic page title. I tried removing then reinstallign the add-in, but nothing changed, same behaviour.
But as always, thanks for the awsome work 👍

**Comment by stevencohn** [comment]
I have a fix and will release it in the next day or two. 
Meanwhile, you can restore the Favorites menu by either deleting or modifying (if you dare) this file: %APPDATA%\OneMore\Favorites.xml

**Comment by stevencohn** [comment]
Fixed in release 2.18
https://github.com/stevencohn/OneMore/releases/tag/2.18

**Comment by osman1963** [comment]
You are the man 👍 👍 
Thanks a million
