### ISSUE TITLE
Reopen #411: Revisiting the import options or the copy and paste options

### ISSUE THREAD

**Issue by gpbicego** [stevencohn/OneMore#602]
[#411](https://github.com/stevencohn/OneMore/issues/411)
I have found that using Microsoft Edge's "Web Select" feature you can create a copy of the web page that is very close to the original.
Is it possible to use this Edge feature in OneMore "Import Web Page"?
Thanks again for your great work.
![image](https://user-images.githubusercontent.com/22318088/190369959-6ad13415-9da0-4334-b682-1cebd65b7458.png)

**Comment by stevencohn** [comment]
This Edge feature copies text and images to the clipboard. You can then paste them into a OneNote page.

Beyond that, what are you envisioning?

**Comment by gpbicego** [comment]
Edge "Web select" copies the page as viewed from the browser, for example if I copy the source code from GitHub, the color and format are preserved.
![image](https://user-images.githubusercontent.com/22318088/190431191-9dec3295-556e-4d54-be1e-2b7b278e6e12.png)

**Comment by stevencohn** [comment]
Not exactly. I'm already using the WebView2 control which is ostensibly the core of Microsoft Edge. It doesn't have a way to access the _Web Select_ function directly but there is a more effective way that I can copy the content of a page into OneNote.

There's some additional magic that _Web Select_ is doing that I'm unaware of

**Comment by gpbicego** [comment]
> There's some additional magic that _Web Select_ is doing that I'm unaware of

For me the most important feature of "Web select" is that it allows you to copy a web page containing **source code** while maintaining the **color and format**.
Microsoft is not very explicit about all ["Web select" features](https://microsoftedgetips.microsoft.com/en-us/collections/workfeatures/55?form=MA13DX):
![image](https://user-images.githubusercontent.com/22318088/190579213-f515bf73-6cb9-476f-9ea2-18c9826baf7a.png)

**Comment by stevencohn** [comment]
Yeah would be nice to have access to this feature but alas, I can only use what they make available.
