### ISSUE TITLE
x64 msi installer does not work in preview or beta version of o365. uninstlled and reinstalled

### ISSUE THREAD

**Issue by BrianPassante** [stevencohn/OneMore#605]
no joy.  a warning message pops that says installer did not complete normally.

onenote version 2209  build 15629.20070

options says oneMOre is installed, but no menu ribbon for OneMore appears

**Comment by BrianPassante** [comment]
I should also mention that oneMore does recognize the 5.0 version upgrade is available, and downloads, but fails to install properly and leaves oneMore non-functional

**Comment by stevencohn** [comment]
As far as I can tell this is from the Insider Program Beta Channel. I cannot support beta versions as I do not have access to them.

**Comment by stevencohn** [comment]
Closing as unsupported.

**Comment by stevencohn** [comment]
Ref #622
