### ISSUE TITLE
Apply custom style to paragraph is very slow

### ISSUE THREAD

**Issue by julie777** [stevencohn/OneMore#606]
**Describe the bug**
When I apply a custom style such as heading 2 to a paragraph it is so slow that at first I didn't think it did anything.

**To Reproduce**
1. Click in a paragraph
2. On the OneMore custom styles menu choose a style, such as heading 2
3. There is a noticable delay before the style is applied

There was enough time for me to capture a screenshot
![image](https://user-images.githubusercontent.com/5090005/190916815-8ec61e6c-86f7-4c03-85e5-04649a897bf4.png)
before the change happened
![image](https://user-images.githubusercontent.com/5090005/190916829-4086e090-74e2-4ff7-bc2f-aed4e4ec10ce.png)

**Expected behavior**
I would expect the style change to appear immediately like it does with builtin OneNote styles.

**Environment (if applicable):**
 - OneNote Version: O365 32bit
 - OneMore Version: 5.0.0

**Additional context**
I love that OneMore applies the style to the current paragraph containing the cursor instead of requiring selecting the entire paragraph like some other add-ons do.

**Comment by stevencohn** [comment]
Is it a large page? For moderate size pages, updates should be fairly quick.

**Comment by stevencohn** [comment]
This demonstrates how fast it should work

![fiddle-faddle](https://user-images.githubusercontent.com/9964757/191614618-93c7d865-b725-47c1-963f-d10432e92aba.gif)

**Comment by stevencohn** [comment]
No repo and haven't heard back. Closing for now.
