### ISSUE TITLE
Feature request: select scribbles and consolidate them in one picture

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#61]
Consider you have a page with a diagram created using the Ink/pen feature.
It would be nice to find a way to aggregate user selected scribbles in a picture
Concrete situation , a diagram hand written.I can provide examples if needed

**Comment by stevencohn** [comment]
Do you mean capture selected scribbles as a single image? Like a png or jpg? Similar to a screen clipping?

**Comment by 1001QAdotNET** [comment]
Yes something like that
Capturing or any other way that is easy for you
All that is needed is an image that will replace the scribbles. This will then allow you to take that image and insert it in a paragraph....this is not possible with scribbles thay are an overlay I think

**Comment by stevencohn** [comment]
Did you know you can select drawings and scribbles, copy them by pressing Ctrl-C, and the paste them as an image from the Paste ribbon button? It's not as quick as what you want but it's a good workaround.

**Comment by CLITrees** [comment]
NO I guess that could work if you do not plan to add this enhancement to OneMore
Thanks for the tip, I did know about this but I never thought about using it in this situation :-)

**Comment by 1001QAdotNET** [comment]
I did not realize I could do it that way, thank for reminding me
If you do not plan to add this to one more it is fine, I can use this trick

**Comment by stevencohn** [comment]
Closing this with accepted alternative solution
