### ISSUE TITLE
Can OneMore 5.0 be applied in onenote 2019 v1808?

### ISSUE THREAD

**Issue by archonwang** [stevencohn/OneMore#612]
I tried it in OneNote 2016, but it can't works. as I used OneMore 4.X, It could be applied. Anyone knows why? Thanks.

**Comment by stevencohn** [comment]
How did you try to install OneMore? Are you using the right installer for your computer? Please see the [installation instructions here](https://github.com/stevencohn/OneMore#install) for complete information.

**Comment by archonwang** [comment]
Yes, just do as the installation instructions. But It failed. As I open the shell list in Onenote, It's installed and used. Sorry for that I used Onenote 2019  v1808, not 2016, my mistake.

**Comment by archonwang** [comment]
just now, I reinstall 4.19 and it works. But v5 doesn't work. Or any log file I can check ? Thanks.

**Comment by stevencohn** [comment]
After running the installer, you should find the file %TEMP%\OneMoreSetup.log. Please attach it here when you have a chance.

**Comment by archonwang** [comment]
[OneMoreSetup.log](https://github.com/stevencohn/OneMore/files/9613240/OneMoreSetup.log)
The log file

**Comment by stevencohn** [comment]
There's a line in the log file: (the word "note" should be the word "not")

`OneNote application path note found; continuing optimistically`

which tells me that there's a problem with your OneNote installation. I recommend reinstalling or repairing-installing OneNote. Then trying to install OneMore again.

**Comment by archonwang** [comment]
Thanks, I will try it later.

**Comment by stevencohn** [comment]
closing as stale
