### ISSUE TITLE
Allow the user to add "Comments" to the Reminders/tasks when they are set. Allow the user to double click on a task to open it and to update it

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#618]
When you add a reminder you are allowed to set a couple of things 
It would be nice if there would be a filed called Comments which could be where we can add notes to read later about these tasks/"to do"s/reminders
I often find myself wondering what that reminder is for. The subject line is not always enough and you would want to read more in a multiline field. 
Also connected to this -it would be nice if could click on a reminder/task and this would open the reminder so we can edit it

**Comment by stevencohn** [comment]
The quickest way to view/edit a reminder is to click on the associated paragraph and press F8 to open the Reminder dialog. Since a OneMore reminder is really just a OneNote tag with a little metadata behind the scenes, there's nothing clickable in that construct.

**Comment by 1001QAdotNET** [comment]
OK that works for me, I don't need to necessarily click on it
How about the comment field ?

**Comment by stevencohn** [comment]
No on the comments. It becomes a storage issue.
