### ISSUE TITLE
Goto the object that is stopping me from reducing the width of the page

### ISSUE THREAD

**Issue by jasonjac2** [stevencohn/OneMore#620]
**Is your feature request related to a problem? Please describe.**
We put a lot of screenshots in a page. Normally the page is pretty linear, headings, text, screen shots.  When a page is too wide it is a pain as you have to scroll to see the text. On a page with no images, you can move the right margin and the text just wraps sooner.  If it is constrained by: images or a table then you have to deal with that first (e.g. shrink / crop).  For long pages this is a pain.  It would be good to be able to "goto the widest fix thing on the page" and then I can repeatedly do that until  I can make the page narrow enough.

Alternatively give me a setting to restrict the page width for a page (but I am not sure  what would happen to a page that was wider than the entry you set.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

THE FINE PRINT
This is a hobby project that I started for myself. I'm happy to take requests and will promise to consider each one carefully but offer no guarantees that I will ultimately agree to their usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around then I will probably reject the request - you've been warned!

**Comment by stevenmcohn** [comment]
So there is a OneMore feature to resize all images on a page to a specific width in a single command. The _Images/Resize and Adjust_ command can act on a single selected image but, if you have no images selected then it applies to all images on the page.

Does that help?

**Comment by stevencohn** [comment]
So there is a OneMore feature to resize all images on a page to a specific width in a single command. The Images/Resize and Adjust command can act on a single selected image but, if you have no images selected then it applies to all images on the page.

Does that help?

**Comment by stevencohn** [comment]
There is an option in that dialog that I would like to add which is "Do not enlarge small images" or, similarly, "Do not shrink..." This way, if an image is smaller (or larger) than the target size, it will leave it alone.

**Comment by jasonjac2** [comment]
> There is an option in that dialog that I would like to add which is "Do not enlarge small images" or, similarly, "Do not shrink..." This way, if an image is smaller (or larger) than the target size, it will leave it alone.

It would work for the vast majority of cases.  I would just set a rule that wide screenshots must be on a line on their own and not embedded in tables.    Thank you.
