### ISSUE TITLE
Error found in Custom UI XML of "OneMoreAddin":

### ISSUE THREAD

**Issue by John-Deaux** [stevencohn/OneMore#626]
I have downloaded, uninstalled and reinstalled OneMore three times, but when I try to install it I get error messages such as this: Error found in Custom UI XML of "OneMoreAddin":

![image](https://user-images.githubusercontent.com/114317167/192121418-3b5f5e6c-0313-432b-a1f9-890d956211ce.png)

MORE:
 
- ![image](https://user-images.githubusercontent.com/114317167/192121934-75c55a89-9b2e-4383-942a-cab8ed2b576d.png)
- 
- ![image](https://user-images.githubusercontent.com/114317167/192121943-abd7471c-909f-4d8c-9384-74302a993a88.png)
- 
- ![image](https://user-images.githubusercontent.com/114317167/192121958-b7ec55d3-3a2d-48aa-80a8-c27cad14ce0c.png)
- 
- ![image](https://user-images.githubusercontent.com/114317167/192121967-42701bbf-5dc4-427a-b4b2-7de70e449bad.png)

I have up-to-date Windows 10 Home on a Dell G5 Gaming Desktop with a 2TB Samsung 970 Evo SSD.

Is there something anyone can suggest that might help me out?

John Deaux

**Comment by stevencohn** [comment]
Did you have an older version of OneMore installed prior to this? If so, then delete this file and try the install again.

`%appdata%\OneMore\Settings.xml`

**Comment by John-Deaux** [comment]
Closed as completed? Not as far as I am concerned. Yes, I was slow to respond, but...

**Comment by John-Deaux** [comment]
I will plow ahead and see what happens. To answer the question about what version of OneMore I have, it is the latest one that I tried to download and install, as I indicated above.

**Comment by jasonjac2** [comment]
@John-Deaux I've found the installer to be pretty good as well as updates (other than the 5.0 which is fixed in 5.1), so hopefully just a blip for you.

**Comment by stevencohn** [comment]
Sounds like we went to the same school and have all the same degrees.

**Comment by John-Deaux** [comment]
Yah, but I finished last in my class. Sigh. 8-)
