### ISSUE TITLE
Enabling Context Menu Options Causes Buttons to Disappear

### ISSUE THREAD

**Issue by megamorphg** [stevencohn/OneMore#628]
**Describe the bug**
Enabling any Context Menu Options causes button to disappear and context menu options not to show either. Have to delete settings to have button show up again.
![image](https://user-images.githubusercontent.com/1782353/192430367-67a58d0c-875c-4e2e-9eb2-46e895ea644c.png)

**To Reproduce**
1. Enable any or all context menu settings.
2. Restart

**Expected behavior**
Enabled context menu is added and OneMore button stays in same place.

**Screenshots**
n/a

**Environment (if applicable):**
 - OneNote Version: O365
 - OneMore Version 5.1 64x

**Additional context**

**Comment by stevencohn** [comment]
Workaround until this is fixed: do not enable the "Snippets Menu" item. 
All others should work
