### ISSUE TITLE
OneMore Action List Keyboard Shortcut

### ISSUE THREAD

**Issue by megamorphg** [stevencohn/OneMore#629]
**Is your feature request related to a problem? Please describe.**
I use OneNote in the mini-view most of the time (banners and buttons all hidden).
Without knowing the keyboard shortcuts for each action, since there are too many to memorize, I have to make several clicks in order to trigger any OneMore action.

**Describe the solution you'd like**
Just like there is a "Favorites" menu which can be called via a shortcut, have a "OneMore Action List" trigger which either:
 - simply triggers the main OneMore button
 ![image](https://user-images.githubusercontent.com/1782353/192431233-f8936146-ccbe-437a-9599-11bf744e1c37.png)
- gives a searchable list with all the OneMore actions that can be applied to the highlighted text or page(s). Can simply type in this search and then press enter to trigger the action.

**Describe alternatives you've considered**
Adding the OneMore button to Quick Access Menu and then calling it with the keyboard shortcut sequence: unfortunately this is too many key presses. I want to have a simple keyboard shortcut I can set like "Alt + W".

**Comment by stevencohn** [comment]
Try pressing Alt+H then type Y4

<img width="192" alt="image" src="https://user-images.githubusercontent.com/9964757/192543159-8be9b0c5-7c48-49e8-80a3-460c22357b46.png">

To my knowledge, the Office fluent ribbon doesn't allow direct accelerator keys to elements within a tab without first selecting that tab. So you need to select the Home tab with Alt+H and then select the element you want - in this case, OneNote is automatically assigning the key sequence "Y4" to the OneMore menu.

There is supposedly a way to override Y4 with something custom like MM but this mechanism doesn't appear to work unfortunately.

**Comment by stevencohn** [comment]
Will assign accelerators as shown here

<img width="176" alt="image" src="https://user-images.githubusercontent.com/9964757/192599967-81424942-c6f1-4b3c-a558-269b485a74c7.png">

**Comment by stevencohn** [comment]
Can't believe I didn't think of that. Create a Ctrl-P for OneMore. Interesting idea.

**Comment by stevencohn** [comment]
Next release will include a command pallett

<img width="338" alt="image" src="https://user-images.githubusercontent.com/9964757/192908108-3a44e586-e73c-47db-8457-4918a32e3424.png">

**Comment by jasonjac2** [comment]
This is so exciting - thank you.  Will it be "Starting with" or "containing"

**Comment by stevencohn** [comment]
Start with - to start. It's a control built into Windows so I went cheap this time just to get it out
