### ISSUE TITLE
Specified Cast is not Valid When Doing Sum Formula

### ISSUE THREAD

**Issue by megamorphg** [stevencohn/OneMore#630]
**Describe the bug**
There is an issue when I do a simple formula calculation like this and I get "Cast is not valid error" when doing sum(C2:C6)
![image](https://user-images.githubusercontent.com/1782353/192439262-38f56c14-1d7c-4d3d-ab67-a682456aa934.png)
![image](https://user-images.githubusercontent.com/1782353/192439471-7800c2b3-ff08-4838-8962-87a6aa8827c6.png)
![image](https://user-images.githubusercontent.com/1782353/192440327-1b42a8aa-a805-4914-957d-06992dafca48.png)

**To Reproduce**
1. Create table as above
2. Create formula on 3rd column as shown.

**Expected behavior**
Sum formula should work with simple numbers. Would be even better if can do a column formula like sum(C:C) so can keep adding rows without changing the formula

**Screenshots**
Sum formula does not work with simple numbers

**Environment (if applicable):**
 - OneNote Version: O365
 - OneMore Version 5.1

**Additional context**

**Comment by stevencohn** [comment]
Temporary workaround until this is released - enter zero in the empty cells. Not great, I know, but will get you going.
