### ISSUE TITLE
Filter Paragraphs which INCLUDE MULTIPLE TAGS. (One note gem macro)

### ISSUE THREAD

**Issue by Raquo116** [stevencohn/OneMore#64]
Is it possible to have this functionality in your 
<img width="542" alt="Tags" src="https://user-images.githubusercontent.com/13005473/95855577-429fc100-0d76-11eb-94a1-d5e609d89f6a.png">
ONEMORE add-in

**Comment by stevencohn** [comment]
So what the actual request? You want to find all paragraph with multiple tags across all pages (or selection sections/notebook) and then do what with that information?

**Comment by stevencohn** [comment]
So it's just a way of finding content with a combination of tags. And you want to click something to navigate to that content then I presume?

**Comment by Raquo116** [comment]
> So it's just a way of finding content with a combination of tags. And you want to click something to navigate to that content then I presume?

yes absolutely

**Comment by stevencohn** [comment]
closing as stale. may feed into nav panel suggestion ref #793
