### ISSUE TITLE
MSI Installer Installation Folder Incorrect & Does Not Close Existing Windows

### ISSUE THREAD

**Issue by megamorphg** [stevencohn/OneMore#642]
**Is your feature request related to a problem? Please describe.**
When running the installer to update, it does not populate the folder that OneMore is currently installed to correctly. For example, below the updater is populating the default C drive but I have it installed to an F drive:
![image](https://user-images.githubusercontent.com/1782353/193283545-207f974d-336d-45ec-8dce-9f80f0a6896f.png)

Additionally, when running the installer normally installers close existing dependencies. It would be great to offer this as an option because I have 10 OneNote windows open at any time. 😅
No need to re-open the closed windows, as I have a macro for that.

**Describe the solution you'd like**
Populate current installation folder
Offer to close existing windows

**Describe alternatives you've considered**
Remember drive installed to and create another macro for closing existing OneNotes

**Additional context**

**Comment by stevencohn** [comment]
That should only happen when you run the installer manually outside of OneNote. Try running the Update command from the OneMore Abou box instead.

This won't get fixed until I switch over to a WiX installer from the old vdproj format. The installer checks dependencies before any custom actions are run so I don't have a chance to stop the process first. If you run the Update command from the OneMore About box then it should work fine.

**Comment by gpbicego** [comment]
The installer tries to shut down itself:

![image](https://user-images.githubusercontent.com/22318088/207362216-827db451-6887-4b5c-af16-b4d22b104ef7.png)

**Comment by stevencohn** [comment]
@gpbicego  please see the comment above about the WiX installer. This is a long-term goal. Until then, please shut down OneNote and then run the installer if you're having difficulties or running it as a different user than is currently running OneNote.
