### ISSUE TITLE
Interface launguage is mixing with CN and EN

### ISSUE THREAD

**Issue by valuex** [stevencohn/OneMore#657]
**Describe the bug**
I've set the OneMore with English.    
But actually in the setting interface, there are still some Chinese characters in the command name.
This causes that I can not use English keywords to excute command in the command pellette.

**To Reproduce**
1. Setting OneNote in Chinese
2. Setting OneMore in English
3. Open setting in OneMore

**Screenshots**
![image](https://user-images.githubusercontent.com/3627812/194756337-7f8783b9-1840-4fd2-839f-87bd97ae84f6.png)

**Environment (if applicable):**
 - OneNote Version: **Office 2019**
 - OneMore Version: V5.1.2

**Comment by stevencohn** [comment]
Is your Windows machine also set to Chinese by default?

**Comment by valuex** [comment]
Yes, both the OS and MS office is set to Chinese.
//

Oh. After restarting two times, this problem disappeared. So please disregard it. 
That is to say, the user can independently set OneMore's launguage no matter the OS or MS office interface launguage is. Great feature. Thanks.👍
