### ISSUE TITLE
Great work of command palette, and more feature needed

### ISSUE THREAD

**Issue by valuex** [stevencohn/OneMore#658]
What a great feature that **command palette** is!
I am supper glad to see that the command pallette feature has been emplemented.
It's really a great feature to improve the efficiency in OneNote.
Like two years ago, I raised the feature request here (https://github.com/stevencohn/OneMore/issues/144#issue-777011317).
And expected it for a long time. And now we get **command pallett**  here, the commands in OneMore can be launched by typing a few letters.
And after the exciting moment, I would like to add some suggestions here. And over-all speaking, the  feature of command pallette is suggested to be like the command launcher, [Almrun](https://github.com/chenall/ALMRun), [WoX](https://github.com/Wox-launcher/Wox),  [FlowLaucher](https://github.com/Flow-Launcher/Flow.Launcher), etc.
So the below suggestion is listed:
1. Hide the main window of command pallette when the **command pallett** windows lose focus [user setting option]
2. support incremental search (fuzzy search) , that is to say, input 'olf' to search 'Open Log File', or even 'oge' can be used to search 'Open Log File'.   
3. User can set different search mode [user setting option], like:

- strict mode: `open` match input word from start
- fuzz mode:  `o.*l.*f`  regex match
- First letter match mode
- **Chinese Yinyin** support. 
4. list the recently excuted items, or top 10 most-frequently excuted items.  

Thanks again for continiously actively developing  new features of OneMore.

**Comment by stevencohn** [comment]
Agreed! I use it much more than even I thought I would myself. And fuzzy match or middle-substring matching would make it easier to find commands. See ticket #649 which lets you create your own aliases for each command, to be released soon.

I'd like to get it closer to what Microsoft has done with the VSCode command pallett:

<img width="461" alt="image" src="https://user-images.githubusercontent.com/9964757/194764511-0dfe0227-495e-44d1-933f-bebf4ff6afc5.png">

**Comment by valuex** [comment]
That's great to know the feature for user defined alias. 
Is it possible to support OneNote internal command execution by define alias and its corresponding shortcut? For example:
**Alias** or **Command name**: Set as to do item
**Command**: SendKeys Alt+H+B

Also for the **command pallett**, will it support using one leading char like `/` to enter into different operation mode?
-  `/` : search page by substring of section or page title and visit that section or page

**Comment by stevencohn** [comment]
Unfortunately, I cannot drive built-in OneNote commands. This is a feature users have wanted for a while but the APIs that Microsoft publishes doesn't give me that level of control.

I'll investigate things like using `/` to activate certain commands.

**Comment by jasonjac2** [comment]
... plus include Favourites in the search - then it is a one stop shop for things you care about. 
I like seeing the hotkeys as well as it teaches you as you go (from your screenshot of VSCode)

**Comment by stevencohn** [comment]
Command Palette will include recently used commands and keystroke hints.

This version will not include additional `/` functionality, searching or favorites. I may or may not address that in the future.

**Comment by stevencohn** [comment]
<img width="354" alt="image" src="https://user-images.githubusercontent.com/9964757/195988777-41b3e5b4-61d2-4e23-a4c3-1b5ebf6996e7.png">
