### ISSUE TITLE
Good job! Theme for syntax highlighting also needed

### ISSUE THREAD

**Issue by Seeds-in-Winter** [stevencohn/OneMore#659]
When using Dark background in OneNote, number looks dim. Also, I personally love Monokai in VS Code. Is there any possibility in developing color themes?

**Comment by stevencohn** [comment]
I'm not sure what you mean "number looks dim". 

As for themes, this is what the OneMore Custom Styles lets you do. Then you can apply that "theme" to a page. It has to be applied manually and can't be done automatically as you type. The OneNote APIs don't allow that.

Notice that OneMore comes with a few pre-defined themes including themes for dark backgrounds. You can load them from the Custom Styles menu as shown here

<img width="249" alt="image" src="https://user-images.githubusercontent.com/9964757/194817006-fd55df52-519d-49a3-9f9b-ef4f9643b0ab.png">

**Comment by stevencohn** [comment]
Oh I think I just realized what you meant.

If you colorize some code while the page background is white then the Colorize command will apply appropriate colors. If you then switch to a dark background, those color will not look right. You'll then need to rerun the Colorize command to apply syntax highlighting for the dark background. OneMore is smart enough to recognize the background of the page when applying syntax highlighting but can't recognize when you switch the background automatically.
