### ISSUE TITLE
Feature Request: word count for pages

### ISSUE THREAD

**Issue by osman1963** [stevencohn/OneMore#66]
It would be great to have this feature, either as a context menu or otherwise. It really helps alot, especially in determining the approximate time for reading in the case of clippings, and writings too.
Thanks in advance !

**Comment by stevencohn** [comment]
Adding now. Will be in next release. It uses whitespace as a delimiter. MSWord uses a slightly different algorithm and counts about 10% more than I do. Good docs uses an even different algorithm and counts about 40% more! 

So just consider it a relative number to other pages and don't rely on it for anything exact.
