### ISSUE TITLE
Command Pallett window jumps from position A to B when it is activated

### ISSUE THREAD

**Issue by valuex** [stevencohn/OneMore#661]
**Describe the bug**
Command Pallett window doesn't show directly at the final position (OneNote window's center?), instead it jumps from position A  to B when it is activated. The time for jumping is very short, but long enough to be sensed.

WinOS: win 11
OneNote: 2016
OneMore: 5.1.2

**Comment by stevencohn** [comment]
Yes, most of the OneMore dialogs do that. It's by design although I may be able to set the location before it is initially shown....
