### ISSUE TITLE
Copy page or selected content to clipboard as markdown or other format

### ISSUE THREAD

**Issue by bayeslearner** [stevencohn/OneMore#663]
I use onenote as the universal note-taking tool, but occasionally, when I need to create documents for other people, I need the content in a different format. For instance, while I'm writing something in obsidian or typora, I want to paste out some selection from a segment of selected onenote content or a single onenote page.   It would be very helpful if there is a customizable shortcut for that.   

This will be built upon the ability to export as other formats,  I assume.

**Comment by stevencohn** [comment]
Added a Copy as Markdown command. This is the only format that makes sense.

Copy as HTML is natively supported by OneNote.
Copy into Word is handled by the native HTML support
Copy as PDF, XML or OneNote.one file doesn't make sense
