### ISSUE TITLE
Custom snippets and templates

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#666]
Is it possible to make the snippets (including the custom ones) to work as some of the formatting features do?
By that I mean that the selected text or content should be included (embedded) in the snippet when the respective snippet button is clicked and there is selected text.

**Comment by stevenmcohn** [comment]
Some of them do already. For example, Code Block and Text Box can both wrap selected text.

Any others you're referring to?

**Comment by stevenmcohn** [comment]
It would be simple enough to enhance custom snippets like this: If it contains a known placeholder, say something like {CONTENT}, then it will replace that with any selected content on the page.

**Comment by stevencohn** [comment]
Some of them do already. For example, Code Block and Text Box can both wrap selected text. It would be simple enough to enhance custom snippets like this: If it contains a known placeholder, say something like {CONTENT}, then it will replace that with any selected content on the page.

Any others you're referring to?

**Comment by stevencohn** [comment]
re my comment on "it would be simple enough..." I may regret saying that! :-)

**Comment by 1001QAdotNET** [comment]
I used the info as template to create a terminal output snippet. That one does not work as mentioned above 
Where do I add the {CONTENT} markup you are mentioning above?

**Comment by stevencohn** [comment]
I was suggesting that could be a future enhancement. It's not implemented.

**Comment by 1001QAdotNET** [comment]
Got it, ok then I guess that is what I am asking for,

**Comment by stevencohn** [comment]
So it gets real complicated real fast. But what I can do in relatively short order is to enhance the Info and Warning block snippets to wrap selected text if there is any, just like Code Block and Text Box do.

**Comment by 1001QAdotNET** [comment]
thanks for implementing this! I will test it in the coming days
