### ISSUE TITLE
Using References Backlinks with "#" symbol in page title

### ISSUE THREAD

**Issue by JoPe72** [stevencohn/OneMore#676]
Hi All..

I am trying to use the functon "Link References to this page" which as far as I understand will create links on the page to all pages linking to this page. Is it correct if this only work if I namually "Copy and paste" the link. I have mulpiple linked pages where the links are created either by using Ctrl + K or by using wiki syntax (aka [[ ]]) and the function does not pick up these links.

Is this on the roadmap?

/Johan

THE FINE PRINT
This is a hobby project that I started for myself. I'm happy to take requests and will promise to consider each one carefully but offer no guarantees that I will ultimately agree to their usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
Please see the description of this command [in the Wiki here](https://github.com/stevencohn/OneMore/wiki/Reference-Commands#link-references-to-this-page).

It searches for the title of the page as mentioned on other pages. It does not search for links to this page.

**Comment by JoPe72** [comment]
That is strange...

I have a page called #dataevents and I have pages where I have the text #dataevents as a link and when I click that link I go to the page called #dataevents. If I click edit link I can see that it is a correctly formatted onenote: link that works but the actual link is not address is not visible on the page

**Comment by stevencohn** [comment]
In fact, that is a bug! Thanks for the explanation. I'll get right on it.

**Comment by JoPe72** [comment]
Great... Nice to be able to help :-)
