### ISSUE TITLE
Feature request: under Show XML offer the option to visualize the XML hierarchy as a collapsible tree

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#68]
This idea was inspired by this utility which I came across yesterday
http://taoffi.isosoft.org/post/2018/04/21/OneNote-Explorer
In my case such a view will help me to understand how the paragraphs are indented and it will make the programming with XML easier

**Comment by stevencohn** [comment]
There are plenty of XML and XSD viewers out there. This is a huge ask with little ROI in my opinion.

**Comment by 1001QAdotNET** [comment]
_There are plenty of XML and XSD viewers out there._
Any one you could recommend that could show the tag as note and the attributes as leafs ?
I am using Notepad++ but it collapses everything and it is not showing the DOM tree as it should

**Comment by stevencohn** [comment]
XMLPad is probably the best https://appuals.com/the-5-best-free-xml-editors/
