### ISSUE TITLE
Error found in Custom UI XML - Error Code ox80004005 

### ISSUE THREAD

**Issue by Jcloghesy** [stevencohn/OneMore#680]
Hi All,

As this is the first time I am writing and I want to brief moment to applaud the efforts of  Steven and all the other contributors to this project!  I have been using the OneMoreAddIn for a while now and found that the add-in has been a huge help to me and others to whom I have recommended it.   The aesthetic and the additional functionality added to OneMore is absolutely fantastic.  Thank you!   

The reason I am writing is that I am hoping that you will be able to assist me with resolving the issue I have been experiencing for a little while now that is completely preventing me from accessing/using OneMoreAdd. 

Any advice you can provide will be greatly appreciated.

Cheers,

J
 
ISSUE
Unfortunately, when I start OneNote Desktop I am presented with a dialogue box citing an error with OneMoreAddin that allows me to use OneNote, but not access any of the functionality OneMoreAddin. 
   

DIALOG BOX 
>         Custom UI Runtime Error in OneMoreAddln 
> > >     Error found in Custom UI XML of "OneMoreAddln": 
> > >     Line: 1 
> > >     Column: 38256 
> > >     Error Code ox80004005 
> > >     " violates minLength constraint of '1 
> > >     The attribute •tag' with value " failed to parse.      
>            OK           OK to All

  
- I am able to clear the dialogue box by selecting "OK" or  "OK to All" 
- Once selecting and clicking on "OK to All", the dialogue box disappears and I am to use OneNote.
- However, I am completely unable to access/use OneMoreAddin because all of the Commands (i.e., icons or buttons) usually available in OneNote's Ribbon are missing.
- the OneMoreAddIn continues to automatically update itself 
- Also it shows in as an active Add-In when 
  File (Tab) ->Options (Dialog Box opens)-> Add-In (Menu Item to display Add-ins Screen)
   OneMoreAddIn shows under the Active Application Add-in section 

I have search for and tried several fixes related to the Error Code 0x80004005 as it relates to windows updates and other  Microsoft Office components without any luck. 

Environment
 - OneNote Version: 
      Microsoft 365, 64bit  Version 2210 (Build 15726.20096 Current Channel (Preview) 
 - OneMore Version:
      I have experienced problem with the last three versions, current version installed is 5.2.1

**Comment by stevencohn** [comment]
First thing, if you wouldn't mind, please delete this file: %appdata%\OneMore\Settings.xml
Then restart OneNote and see if that helps.

**Comment by Jcloghesy** [comment]
That worked!!!  I really should have written earlier (really missed using OneMore).  Thanks again!  
J
