### ISSUE TITLE
Initial instance ON window brought to front when a dialogue is instantiated

### ISSUE THREAD

**Issue by jasonjac2** [stevencohn/OneMore#683]
**Describe the bug**

Very Very Very minor, really just an observation.  Any interaction with OneMore dialogues bring up and keep up the 1st instance of ON.

I have about 5 ON windows open spread over 2 monitors. I segment each monitor into a left and right (1,2,3,4 refer to left most to right most area of screen). 1 = ON, 2=ON. 

**To Reproduce**
Open ON (1) 
and another instance ON (2)
bring up word in position 1, and in ON (2),
Focus on ON (2)
Alt+F to bring up favourites.  

ON (1) comes to the front and Word (1) goes to back.
I select an item from the favourites and that page appears in ON (2) as expected.
ON (1) still topmost and word (1) still background.

**Expected behavior**
ON(1) shouldn't come up at all
OR ON (1) should realise its Z order and revert it back once the command has been issued.

**Screenshots**

**Environment (if applicable):**
OneNote 15.0, Office 16.0, C:\Program Files (x86)\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.15601.20148) 
- OneMore Version 5.2.1

**Additional context**

As an aside, it would be SO GOOD if the about dialogue pulled out the ON Version and bitness :-).  Call me lazy - my wife does.

**Comment by stevencohn** [comment]
I agree this is a bug.
Also....

<img width="364" alt="image" src="https://user-images.githubusercontent.com/9964757/197364993-b143b860-0518-43e7-85d2-827c884fc257.png">
