### ISSUE TITLE
Add the option to select a picture, edit it in an external editor (configurable) and save it back

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#684]
The default OneNote options to edit a picture are rather limited. 
Not sure if this was requested before and if this is possible but it would be nice to add the option to select a picture, edit it in an external editor (configurable) and save it back

**Comment by stevencohn** [comment]
What, OneMore's image tools aren't good enough!? I'm offended.

No I'm just kidding. Yes, I've thought about this one too. I often use paint.net as a lightweight but powerful editor. The only catch is the "... and save it back" part of your request. The only way to actually get it back into OneNote is to copy paste it from your external editor, overwriting the original image.

**Comment by 1001QAdotNET** [comment]
Ok great, yes I too use paint.net

**Comment by 1001QAdotNET** [comment]
It should be possible to automatically insert the new picture if the user hits Ctrl+A and Ctrl+C while in paint.net (or any combination of keys that copies the edited image to clipboard)
After that OneMore could be able to see when the child process closes (can it see it?) and when that is done access the clippboard programmatically and paste the image in place.
Does this work ?

**Comment by 1001QAdotNET** [comment]
well you do not replace the image edited
just paste it below it and let the user delete the old one if he or she is happy with the new one

**Comment by stevencohn** [comment]
You've already pressed Ctrl+A/Ctrl+C... it's just a Ctrl+V keypress away! :-)

There's quite a bit of coding, error checking required here. The climb isn't worth the view IMO

**Comment by 1001QAdotNET** [comment]
` The climb isn't worth the view`  I love the metaphor 
OK what you implemented is good enough, I will start using it and report back here if I see any issues. No news good news you can close this one if you wish and I can report bugs separately

**Comment by stevencohn** [comment]
Cheers
