### ISSUE TITLE
Does onemore support cell merging?

### ISSUE THREAD

**Issue by yslhzj** [stevencohn/OneMore#685]
Does onemore support cell merging?
As shown in the following figure
![image](https://user-images.githubusercontent.com/29890756/197110747-557f214c-2c28-49df-bf9c-cce7f7a820b8.png)

**Comment by stevencohn** [comment]
No because this is a limitation of OneNote. Many people have submitted feature requests directly to Microsoft regarding this.

**Comment by stevencohn** [comment]
Duplicate of #671
