### ISSUE TITLE
Why are the characters in the style blurred?

### ISSUE THREAD

**Issue by actforjason** [stevencohn/OneMore#687]
Is it the high resolution screen？
![image](https://user-images.githubusercontent.com/57058325/197342428-16e100f2-0a41-4b76-b5c2-5a36ccc46572.png)

**Comment by stevencohn** [comment]
What is your display scaling factor? It's in Windows Settings as shown here;

<img width="718" alt="image" src="https://user-images.githubusercontent.com/9964757/197342769-598adf1a-8993-4e1a-a99e-2af7b518dc7b.png">

**Comment by actforjason** [comment]
125%, it works fine for other apps.

**Comment by sstoilovABLE** [comment]
I've submitted a duplicate issue #783 by mistake. I have the same question. My display scaling is 175%

![image](https://user-images.githubusercontent.com/20355843/205443833-04c1fe61-d15a-4c69-b912-e4c6235cb7e5.png)

**Comment by stevencohn** [comment]
@sstoilovABLE  no worries, thanks for the additional info

**Comment by stevencohn** [comment]
Prior to update
<img width="242" alt="image" src="https://user-images.githubusercontent.com/9964757/205451708-e41ba19e-36fd-4322-b84c-2b3dbe5f5ea8.png">

After removing antialiasing
<img width="248" alt="image" src="https://user-images.githubusercontent.com/9964757/205451712-591c891b-e146-4bcd-bf39-d4a0268b0b05.png">

and
<img width="243" alt="image" src="https://user-images.githubusercontent.com/9964757/205451718-1ca6f96c-a1e3-42dd-bd9b-0cf662bf79c9.png">
