### ISSUE TITLE
Apply OneMore page style for new page

### ISSUE THREAD

**Issue by actforjason** [stevencohn/OneMore#690]
OneMore page style（gray background）:
![image](https://user-images.githubusercontent.com/57058325/197397123-e928bc1c-dfb2-473e-915d-1bfd9180aafc.png)

For new page, it doesn't apply the OneMore page style but the default page style of OneNote.
![image](https://user-images.githubusercontent.com/57058325/197397344-aa354da6-e7de-4725-bcae-de9fd393d00d.png)

**Comment by stevencohn** [comment]
Unfortunately, this is not possible given the OneNote APIs that I have available to me. OneMore can't detect when a new page is being created.

**Comment by actforjason** [comment]
OK. There is still a problem，SELETED OneMore style will change for new page.
SELETED style
![image](https://user-images.githubusercontent.com/57058325/197398236-d21fdb74-e2ea-4bc0-8c17-ca0ab621aae3.png)
change to the initial state
![image](https://user-images.githubusercontent.com/57058325/197398454-90cb4fd2-953c-4a0e-9492-dff959d2fceb.png)

**Comment by stevencohn** [comment]
No this is by design. It's supposed to represent the styles as they would appear on the current page since each page can have a different background.

**Comment by actforjason** [comment]
An option to keep the selected style will be very welcome.🙏

**Comment by stevencohn** [comment]
To be clear, one your first comment regarding applying the page background to a new page, this is not possible.

Regarding your observation on the background color shown on the style menu, this is by design - but it does not change the background color of a style when you apply it. 

This is all working as-designed and will not be changed.

**Comment by actforjason** [comment]
Remembering the selected style can help to apply style to a new page with one click without additional configuration.

**Comment by stevencohn** [comment]
Got it. Forgive me for not understanding. Will investigate.

**Comment by stevencohn** [comment]
So the Change Page Theme dialog that you first posted (with the Custom selection) does remember which color you've chosen the last time. If that isn't saving that setting, let me know.

Are you talking about another setting?

**Comment by actforjason** [comment]
I chose the setting on the first picture myself, not OneMore remembered.

**Comment by stevencohn** [comment]
That dialog will remember its own setting. It should at least.

That does NOT apply to new pages. There is no way possible for that to apply to new pages. New pages will always be created with a white background unless you change your default page template in OneNote using the Page Templates panel.

There is NOTHING OneMore can do to change this.

<img width="232" alt="image" src="https://user-images.githubusercontent.com/9964757/197505334-f98ff34b-e6fa-491a-b86b-588fa10cb9cd.png">

**Comment by actforjason** [comment]
This is exactly what I want. Thank you.
