### ISSUE TITLE
An error was encountered during installation after packaging

### ISSUE THREAD

**Issue by actforjason** [stevencohn/OneMore#697]
Configuration Manager：
![image](https://user-images.githubusercontent.com/57058325/198505457-3b037744-f714-4a58-8ae5-58f9c678dc68.png)
Event Viewer：

> Error 1722. There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  Action _67AC4AD8_6F00_4853_A52D_C3B81180AEFA, location: C:\Program Files\River\OneMoreAddIn\OneMoreSetupActions.exe, command: --install --x86 
=== Logging stopped: 2022/10/28  12:46:43 ===

OneMoreSetup log：
> ======================================================================
> starting action: --install .. 2022/10/28 12:46:40
> Installer architecture (x86), OS architecture (x64), requesting (x86)
> Installer architecture (x86) does not match OS (x64) or request (x86)

**Comment by actforjason** [comment]
Windows x64, Office x32

**Comment by actforjason** [comment]
Build successfully using the build.ps1 script.

**Comment by stevencohn** [comment]
I'm not sure I understand what you're saying here.

The configuration manager is not correct. It should remain at x86. This is for regular development on either a 32 or 64 bit machine with 32 or 64 bit office. 

The purpose of the build.ps1 script isn't just convenience. It surgically changes the configuration specifically for both a 32 bit build and then for a 64 bit build. It then restores the configuration back to x86 for regular development again.

It's the installer that's important here. As stated on the OneMore home page:
* Use the x86 installer only if you are running on a 32-bit Windows machine; it has nothing to do with the bitness of Office itself.
* Use the x64 installer when running on a 64-bit Windows machine for either 32-bit or 64-bit Office.

The log excerpt that you include looks to be doing exactly what it's designed to do.

**Comment by actforjason** [comment]
As it says here，I follow method 1 but set TargetPlatform to x64 and configuration as follows, finally installed error
![image](https://user-images.githubusercontent.com/57058325/198585607-35b1bb03-bee0-4b42-aa42-fff3dab23e40.png)
![image](https://user-images.githubusercontent.com/57058325/198586180-f119ad46-4614-4460-b922-334707f04539.png)

error installation
> Installer architecture (x64), OS architecture (x64), request (x86)
Installer architecture (x64) does not match OS (x64) or request (x86)

Method 2, build with .\build.ps1, install successfully.
if success，the requesting in installation info is x64, but using method 1 to build results in error request (x86). Then where to change request (x86) to request (x64) for method 1？

**Comment by actforjason** [comment]
The error log is printed here.
https://github.com/stevencohn/OneMore/blob/51735ed342df687b49276a62c25a25e7f89706ec/OneMoreSetupActions/Program.cs#L129-L134

the Boolean `x64` is obtained from `args`, how to set the `args`?
https://github.com/stevencohn/OneMore/blob/51735ed342df687b49276a62c25a25e7f89706ec/OneMoreSetupActions/Program.cs#L25

**Comment by stevencohn** [comment]
OK, so I'll update the docs. But stop using method 1. ;-)

The best approach is to leave the configuration alone, at its default x86 for the OneMore project and don't touch the installer project properties (it should reference x86 throughout)

Use only the build.ps1 script. It takes command line arguments:
* .\build.ps1 86
* .\build.ps1 64
* .\build.ps1 -both

I hope that helps

**Comment by actforjason** [comment]
I know what's going on！
This is related to `microsoft visual studio project installer` project structure. When click `Setup` project，there will be a hidden menu：
![image](https://user-images.githubusercontent.com/57058325/198686082-96a38e69-5d13-46d4-a210-ef34200562bc.png)

here can set Install Arguments. Changing x86 to x64 works fine.
![image](https://user-images.githubusercontent.com/57058325/198685714-aa6c9878-559c-43ca-b385-bab74b833ba3.png)

**Comment by stevencohn** [comment]
That's right. This is what the build.ps1 script manages behind the scenes. All by design. All why you need to use build.ps1

**Comment by actforjason** [comment]
learn a lot
