### ISSUE TITLE
Reading queue and a reading queue management

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#698]
My workflow includes a step where I come across info that I would like to read later and when that happens, I save the articles, books, links or whatever I am interested in, in a designated section called **Reading queue**. I save the info by using "Send to OneNote" from Outlook or Office apps, or from web browsers. Sometimes I do that from Android. There is little control over the section where the saved content lands and it is a time wasting task to go back and find the info and then move it to the reading queue. 
I would like to be able to shorten those steps by using a OneMore feature that would allow me to right click on a OneNote page and send it to the section that was designated as **Reading Queue**, preferably with a priority and some tagging that could be set. The existing OneMore **Task scheduler** could be leveraged for scheduling and priority setting 
Is that something that you think it would improve OneMore and benefit other users too ?

PS: the feature should work across multiple notebooks. Also it would be nice to be able to search for pages tagged it a certain tag that are not in the reading queue yet and the group select them and move them to that section
There is a builtin move or copy option, I know about that one but this is taking that one to a new level

**Comment by stevencohn** [comment]
may implement as part of #793

**Comment by 1001QAdotNET** [comment]
Thank you
I will report any bugs via a new issue if I come across any

**Comment by 1001QAdotNET** [comment]
How do I use this feature, I can't find the way to use it.
Was it really implemented, or it was closed because it was connected with another issue?

**Comment by stevencohn** [comment]
See note above; will be implemented as part of #793. I just added the duplicate label in hopes of avoiding confusion in the future.

**Comment by 1001QAdotNET** [comment]
somehow I thought it was implemented since it was closed
