### ISSUE TITLE
[Development Environment] Can't run OneMoreCalendar after redirecting the registry entries

### ISSUE THREAD

**Issue by actforjason** [stevencohn/OneMore#699]
According to the preparation of the development environment, click OneMoreCalendar but did not respond.
https://github.com/stevencohn/OneMore/wiki/~-Developer-Notes#development-environment
Maybe because OneMoreCalendar.exe is not in the specified path `OneMore\bin\x86\Debug\`.

**Comment by stevencohn** [comment]
Yeah, I could improve this. It's hard-coded (for my own dev env) at the moment in the file OneMore\OneMore\Commands\Tools\CalendarCommand.cs

```csharp
if (location.StartsWith(@"C:\Github\OneMore"))
{
    location = @"C:\Github\OneMore\OneMoreCalendar\bin\Debug";
}
```

I can make that more intelligent but for now, you can simply change it to your own path.

**Comment by stevencohn** [comment]
I just updated the code with this https://github.com/stevencohn/OneMore/pull/700/files

**Comment by actforjason** [comment]
Good，it works well.
