### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by liuzeji** [stevencohn/OneMore#701]
the install program prompted that it failed to install.
by the way, i cant connect it to onenote when i  am using the older one.
（forgive me for my poor english）

**Comment by tahmajor** [comment]
> the install program prompted that it failed to install. 

Have maybe the same Problem. The Popup Message is "There is a problem with this Windows Installer Package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor."

**Comment by stevencohn** [comment]
Are you sure you're using the right package? Use the x64 package.

Only use the x32 package if you're running on a 32-bit Windows machine. 

There is likely a log message here: %temp%\OneMoreSetup.log

**Comment by tahmajor** [comment]
> Are you sure you're using the right package? Use the x64 package.
> 
> Only use the x32 package if you're running on a 32-bit Windows machine.
> 
> There is likely a log message here: %temp%\OneMoreSetup.log

Nope, I´m not. I missunderstood which package to choose. Thought it depends on Office

Thanks, now it´s running.

**Comment by stevencohn** [comment]
Cool. I wish I could change that dialog message but that will require a new installer which I've been putting off....

**Comment by liuzeji** [comment]
I'm sure i used the x64 package foy my 64-bit system, but the error remains.
----- 原始邮件 -----
发件人：Steven ***@***.***>
收件人：stevencohn/OneMore ***@***.***>
抄送人：liuzeji ***@***.***>,  Author ***@***.***>
主题：Re: [stevencohn/OneMore] Failed to install (Issue #701)
日期：2022年11月03日 21点01分


Are you sure you're using the right package? Use the x64 package.
Only use the x32 package if you're running on a 32-bit Windows machine.
There is likely a log message here: %temp%\OneMoreSetup.log

&mdash;

**Comment by stevencohn** [comment]
@liuzeji Do you have a OneMoreSetup.log file that you can attach here?

**Comment by liuzeji** [comment]
> @liuzeji Do you have a OneMoreSetup.log file that you can attach here?

  no,i ffound nothing.
i downloaded the package again and thai did the trick...
maybe something wrong whit the package i downloaded before.
thanks for your reply:)

**Comment by stevencohn** [comment]
Cool. Closing for now

**Comment by RandyR34** [comment]
Please see my post [here](https://github.com/stevencohn/OneMore/issues/941#issuecomment-2083182784) for a solution.
