### ISSUE TITLE
Removing duplicate items from a list without sorting

### ISSUE THREAD

**Issue by Virility** [stevencohn/OneMore#702]
Would be nice to use to save time instead of sorting and going down a list

**Comment by Virility** [comment]
or instead perhaps merging the duplicates among (underneath, by order of instance found) the first instance?

**Comment by stevencohn** [comment]
https://github.com/stevencohn/OneMore/commit/00d7173512fbe9eadb544fd78d58901d98ff0ce5

**Comment by Virility** [comment]
awesome! thanks for the update
