### ISSUE TITLE
"Update Page" changes nothing

### ISSUE THREAD

**Issue by actforjason** [stevencohn/OneMore#703]
I replace the xml of first pic with second pic that is from empty page，but nothing has changed after clicking "Update Page" button，. I unchecked "Hide edited-by-attributes".
![image](https://user-images.githubusercontent.com/57058325/199887913-61a47112-41dc-45c4-b3c7-3c4dd13dcf7d.png)
![image](https://user-images.githubusercontent.com/57058325/199887994-8b8a49b8-56e1-49d2-ac76-d7b93d382773.png)

**Comment by stevencohn** [comment]
Exactly what changes did you make? I can't repro this using a picture of XML

It's likely not a bug or problem with the XML Dialog but rather OneNote post-processing the XML and wiping out your changes that it considers irrelevant.

**Comment by actforjason** [comment]
There are two pages，I copy the xml of second picture that is empty to cover the xml of first picture，but nothing changes after Update Page.
![image](https://user-images.githubusercontent.com/57058325/199971708-fd797273-818d-4efd-b17d-da1683e1734c.png)
![image](https://user-images.githubusercontent.com/57058325/199971738-35f325ab-6ef7-4338-8086-1608913f2548.png)

**Comment by stevenmcohn** [comment]
It is updating... but it's updating the page of the second picture!

It updates based on the page ID. So unless you've also changed that to the be the same as the first page's ID then you're updating the wrong page.

**Comment by stevencohn** [comment]
It is updating... but it's updating the page of the second picture!

It updates based on the page ID in the XML. So unless you've also changed that to the be the same as the first page's ID then you're updating the wrong page.
