### ISSUE TITLE
Can the new footnote be a placeholder rather than a string?

### ISSUE THREAD

**Issue by actforjason** [stevencohn/OneMore#704]
Each time add a footnote, need first delete the original string.

**Comment by actforjason** [comment]
Alternatively，"new footnote" can be replaced with ": ".

**Comment by stevenmcohn** [comment]
Working as designed.

**Comment by stevencohn** [comment]
https://github.com/stevencohn/OneMore/issues/704

**Comment by actforjason** [comment]
Sorry I don’t understand what you mean

**Comment by stevencohn** [comment]
Sorry not sure how that comment got in there :-) 

This is working as intended. Add Footnote will always add a new footnote entry. If you want to change the text of a footnote, just change the text directly.

**Comment by actforjason** [comment]
But take a step more every time, that is, modify the text, can it be directly entered after the serial number, isn’t it very good?

**Comment by stevencohn** [comment]
I'll consider it
