### ISSUE TITLE
When sorting a list of titled links ("Text to display"), there should be an option to sort by the title of links vs sorting by the actual link. 

### ISSUE THREAD

**Issue by Virility** [stevencohn/OneMore#706]
Case in point is when you have a bunch of Youtube links. A list might have links with an arbitrary video ids but ideally would be better to sort by the titles ("Text to display:" field in the Link display box).

**Comment by Virility** [comment]
Happy to see it implemented, would you be open to having the unwrap as a checkbox option?

**Comment by stevencohn** [comment]
By "unwrap" do you mean to remove the display text and only show the raw URL for these links, or to remove the hyperlink altogether, or ... ?

Either way, please submit it as a new ticket if it's different functionality.

**Comment by Virility** [comment]
will do :)
