### ISSUE TITLE
Exporting onenote page causes onemore to crash

### ISSUE THREAD

**Issue by Machiavelli09** [stevencohn/OneMore#707]
**Describe the bug**
Exporting onenote page causes onemore to crash.
Exporting works but to continue, "ending task" in task manager for Onenote and onemore or comsurogate" is necessary.

**To Reproduce**
1. Go to: Onemore/file/export
2. Choose: 1)Folder path 2) Format = HTML File
3. Click on: replace special caracters in the filename with underscores
4. Click on: Ok
5. See error

**Expected behavior**
Expecting to be able to go back to one note and save another page without ending task in task manager.

**Screenshots**
![image](https://user-images.githubusercontent.com/117470957/200029820-99489ba9-967c-4c10-86b1-cfff6bc58efe.png)

![image](https://user-images.githubusercontent.com/117470957/200030246-8fd37d85-bd84-4873-b885-a3586307541a.png)

**Environment (if applicable):**
 - OneNote Version: Microsoft® OneNote® pour Microsoft 365 MSO (Version 2209 Build 16.0.15629.20200) 64 bits 
 - OneMore Version installed version: 5.2.1 ; Last updated: 24-Oct-2022

**Comment by stevencohn** [comment]
I'm sorry you're having problems. Does it happen with every page or just this one?

**Comment by Machiavelli09** [comment]
Hi,

Sorry for my late reply.
It happens with every page I have.

Thanks,


Le ven. 4 nov. 2022, 1 h 06 p.m., Steven ***@***.***> a
écrit :

**Comment by stevencohn** [comment]
I've been trying to make this fail but can't. Some things to consider/try:

* The output path cannot exceed 239 characters in length
* If this is a locked section, it must be unlocked first
* Do the pages that fail have links to other pages? If so, those pages must still exist (can navigate to them from the page)
* Do the pages that fail have any attachments? If so, those attachments must still exist (can open them from the page)

Please run the command and if it fails, attach the log file found at %appdata%\OneMore.log

**Comment by Machiavelli09** [comment]
Hello Steve,

Thank you so much for your help and for One more.

My assumptions for the failures are:
1) Inconformity of the titles of the pages.
2) The pages were very heavy due to the many photos.

However since the last updates, One More works perfectly!

Thank you so much again,
Musto
