### ISSUE TITLE
Is there a way to add Style Shortcut into the popup over selected  text 

### ISSUE THREAD

**Issue by actforjason** [stevencohn/OneMore#710]
Just like OneNote Styles，which is more convenient than key shortcuts. 
![image](https://user-images.githubusercontent.com/57058325/200158330-6e971dd8-51ec-46c9-be9e-b39b046aaa14.png)

**Comment by stevencohn** [comment]
No. Microsoft has not provided any way to do this.

**Comment by actforjason** [comment]
Is it possible to automatically replace the OneNote style with the OneMore style when the OneNote style is detected to be applied？

**Comment by stevencohn** [comment]
No there is not. Microsoft does not provide events that can be monitored like that.

**Comment by actforjason** [comment]
There is a gap between dream and reality.😅
