### ISSUE TITLE
Show option in list sort dialog to sort anchor's links with plain text items vs sort anchor's text with other with plain text items (the default).

### ISSUE THREAD

**Issue by Virility** [stevencohn/OneMore#716]
After this commit https://github.com/stevencohn/OneMore/commit/5dd9611a315fc0dfc699f62587a31031aae08d34 the default behavior right now is sorting an anchor's text with other plain text items indiscriminately. I think the preferred option should default to this first behavior but also have an option in the dialog to sort the links themselves, as was done prior to the commit (sorting against the anchor link).

**Comment by stevencohn** [comment]
So as a normal user of OneNote, focused on collecting notes and information, I would want to sort what I see. If that means sorting items in a list, I would want all items in that list to be sorted. This is how it should work right now. (Previously, it was in fact a defect where it was considering the URL of the hyperlink instead of its displayed text.)

Why would you want to sort using information that you can't actually see on the page?

**Comment by Virility** [comment]
Some websites are tricky since the information you want to sort through is concealed not in the title (in visible text) but in the link retained in hyperlink. Like websites will straight up have their brand name as the whole title, but still the links can show the different metadata, often even sorting by just the first argument in the url is useful enough.

Sorting across domains via the hyperlink is useful as is visible text, especially on long lists. A part of information collecting is coming across many domains to research a topic perhaps and lists are often used as data dumps. Grouping the same domains can reveal a collection of links of the some of the important domains and helps me sort through the information as quick as possible.

**Comment by Virility** [comment]
Some websites are tricky since the information you want to sort through is concealed not in the title (in visible text) but in the link retained in hyperlink. Like websites will straight up have their brand name as the whole title, but still the links can show the different metadata, often even sorting by just the first argument in the url is useful enough.

Sorting across domains via the hyperlink is useful as is visible text, especially on long lists. A part of information collecting is coming across many domains to research a topic perhaps and lists are often used as data dumps. Grouping the same domains can reveal a collection of links of the some of the important domains and helps me sort through the information as quick as possible. It helps to have that all in one note app and I think it would aid the research process a bit. Though if it's too specific of a request I can always migrate the sorting to an external app :)

A quick example would be in a folder of Github project links, you might have 
![image](https://user-images.githubusercontent.com/8846783/200720847-81ca6cc2-8dff-41c8-bf10-c04c8ec3f903.png)
and 
![image](https://user-images.githubusercontent.com/8846783/200720892-194d70bb-de8a-493c-9671-24f97b3f139a.png)

They share the same parent link, and would be grouped together by sorting with link, but mix it in with different domains discussing the same topic and sorting by text it'll get lost pretty quickly, specially since I export my bookmarks into OneNote regularly.

**Comment by stevencohn** [comment]
The current implementation is correct. List items are sorted by the visual text of each item. 

To sort links independently, even as an additional option, would be an exception beyond what most users need and want. 

Closing for now.
