### ISSUE TITLE
The Info Block option is not shown in the context menu after being enabled in the Settings

### ISSUE THREAD

**Issue by meibye** [stevencohn/OneMore#717]
**Describe the bug**
The Info Block option is not shown in the context menu after being enabled in the Settings.

**To Reproduce**
1. Go to More
2. Click on Settings and select Context Menu
3. Scroll down and enable Info Block. Click Yes when asked to restart OneNote
4. Right click the mouse to show the context menu which should show the Info Block option

**Expected behavior**
Expect that the Info Block options should be shown in the context menu.

**Screenshots**

**Environment (if applicable):**
 - OneNote Version: Microsoft® OneNote® 2016 MSO (Version 2210 Build 16.0.15726.20068) 32-bit 
 - OneMore Version 5.3.0

**Additional context**
Add any other context about the problem here. Attach page XML file or the app log file as appropriate. You can find the log file here: %localappdata%\temp\OneMore.log

**Comment by stevencohn** [comment]
Looks like Warning block is included instead of Info block. OK
