### ISSUE TITLE
Make all the dialogs related to "Run Plugin" show on the same monitor where OneNote is running

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#72]
Right now the error dialogs are showing up only on the main monitor although I have OneNote on a secondary monitor
The same for the warning before clearing the log file
I think that now that we have this Run plugin the "Clear log" command should get its own button and we should be allowed to place it on the quick access tool bar. If you are testing plugin code that might be needed

**Comment by 1001QAdotNET** [comment]
OK that would work.

**Comment by stevencohn** [comment]
FYI, Microsoft.Windows.Forms dialogs are stubborn and it's all I can do to guarantee that they are shown as topmost windows above all others, let alone try to force them to appear on a different monitor. So, they work. It's not perfect. But they work.
