### ISSUE TITLE
AddIn not loading

### ISSUE THREAD

**Issue by KlausSGS** [stevencohn/OneMore#726]
**Describe the bug**
Install completes successfully but the AddIn does not load.
Neither for the normal user nor the admin used for installation.

**To Reproduce**
Login as non admin user on Win11 22H2.
Start Powershell with another user with admin rights.
Start winget install -e --id wethat.onenotetaggingkit
installs v5.3.0
returns: installed successfully 
Logoff user
Logon user
Start OneNote
-> no addin visible
-> no Addin in OneNote addin list

**Expected behavior**
Install using runas admin user.
Logoff / Logon user.
Start OneNote.
AddIn loads.

**Environment (if applicable):**
 - OneNote Version: [O365 32bit v2208]
 - Windows 11 22H2 (Enterprise Edition, german)
 - OneMore Version [5.3]

**Additional context**
[WinGet-stevencohn.OneMore.5.3.0-2022-11-18-15-01-49.769.log](https://github.com/stevencohn/OneMore/files/10041911/WinGet-stevencohn.OneMore.5.3.0-2022-11-18-15-01-49.769.log)

**Comment by stevencohn** [comment]
Are you really trying to use winget to install OneMore (you maybe incorrectly typed onenotetaggingkit above, which is not this!)

winget is not a supported method of installing OneMore. I can look into it, but that would be a new feature request, not a defect.

Please see the [installation guide here](https://github.com/stevencohn/OneMore#install). If that still fails, let me know.

**Comment by KlausSGS** [comment]
I tried the install using winget and also tried installing the x64 MSI - same result.
The AddIn regkeys go to the admin users registry only.
Sorry copied the wrong commandline - but did the same with OneMore. The other AddIn loads as expected.

In the meantime I uninstalled with winget, and installed from scratch using the MSI - same result.
Then I added the normal user to the local administrators group, logged in again and restarted the MSI installer and chose "repair".
That **worked**. The AddIn is loading and is still loading after having taken away the admin rights from the user.

So it seems the installer does not work if the admin account is **not the current** user account.
I guess in order to set everything up for other users the MSI would need a repair or some other mechanism to transfer the settings into the user profile after the actual installation.

**Comment by stevencohn** [comment]
Thanks for the explanation.

It should work as you described, even running with a different admin user than the current user. When the current normal user logs out and then logs in again, it may take a minute to sync everything up including copying the registry settings. This takes advantage of a Windows feature for remotely deploying applications and that delay is intrinsic to that Windows feature.

I haven't seen this fail as you described but I'll look into since I haven't tried this scenario in a few months.

**Comment by stevencohn** [comment]
closing as stale, not reproducible
