### ISSUE TITLE
Request: Ability to Import PDF files in bulk

### ISSUE THREAD

**Issue by lcarnegie** [stevencohn/OneMore#728]
**Describe the solution you'd like**
It would be great if you could build in the ability to bulk-import PDF files into OneMore. I'm a university student and my weekly materials all come in PDF, so it would really makes things faster if I could import all of my files quickly! I know you already offer the option to import PowerPoints and Word docs into OneNote in bulk, so it would make a lot of sense if you could also import PDFs in bulk too!

**Describe alternatives you've considered**
I know OneTastic offers this feature, but it's just too expensive to justify the simple task I'm trying to do. Worse come to worst, I might just have to learn Visual Studio and C# to code this thing myself!

THE FINE PRINT
This is a hobby project that I started for myself. I'm happy to take requests and will promise to consider each one carefully but offer no guarantees that I will ultimately agree to their usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
Consider points in #862

**Comment by stevencohn** [comment]
Initial implementation will be a simple addition to the existing OneMore File/Import dialog, in which you can enter one.pdf file name or a wildcard *.pdf file name. You'll have the option to append all imported content to the current page or create a new page per file, just like it handles importing other files.
