### ISSUE TITLE
Feature Request: Add typewriter mode to OneNote

### ISSUE THREAD

**Issue by osman1963** [stevencohn/OneMore#73]
Typewriter mode, making the screen scroll up and keeping the active line always in the middel would be a great addition, especially for those who write lots of lines in a session. 
Hope it's not complicated in programming.
And as always.. thanks for the great add-in..you made our lives lot easier 👍

**Comment by stevencohn** [comment]
I don't think that's possible with the OneNote API. It should already keep content visible while typing although the cursor will be at the bottom of the window if you've already filled in the entire viewport. You could just shrink the window so the bottom is closer to your line of sight (I know, not a great solution but hey, it's 7:30am and I'm only half way through my coffee)

**Comment by stevencohn** [comment]
What about https://typora.io/
You could write in that and then copy content into OneNote when you're done

**Comment by osman1963** [comment]
Two lovely solutions, especially the first one, very practical. I tried the typora solution before, but prefer of course doing it in the same app, inside ON I mean. However, I really love your add-in and just dream about making it always better, especially with your always swift response and updates. 
So, just an idea from an ex very old programmer (not programming for over 20 years now)  reagrding this typewriter mode (feel free to laugh if you find it silly). 1) detect the cursor position, 2) if in middle of page, then scroll page up, move cursor line down.
Also another feautre request: the number of pages to appear beside the section title. 
Thanks again and have a lovely morning

**Comment by stevencohn** [comment]
While I can detect the caret location, there's no way to force the window to scroll. Office apps typically have a single client area that covers the entire window and any regions within that are opaque to the outside world. 

Add page count in the section title is possible. But I think that needs to be low priority, if I do it at all. Can you post that as a separate ticket feature request?

**Comment by stevencohn** [comment]
Closing this pertaining to typewriter mode request. If you want feature to add page count to section titles, please submit a separate ticket
