### ISSUE TITLE
Import Markdown "loses" headers

### ISSUE THREAD

**Issue by RobertBernstein** [stevencohn/OneMore#731]
**Describe the bug**
When I import .md files, all of the headers, e.g., # or ##, etc., get converted into Normal style text instead of Heading 1, Heading 2, etc. OneNote styles.

**To Reproduce**
1. Go to the Home ribbon, File, Import, and choose a markdown file (*.md).
2. When it imports, all of the headers are styled correctly, but they're not actual OneNote Header styles.  They show as Normal OneNote style.

**Expected behavior**
I expected the headers to be maintained as OneNote header styles, e.g., Heading 1, Heading 2, not to be converted to Normal OneNote styles with the correct appearance of the headers.

**Screenshots**
This is what the imported text looks like:
![image](https://user-images.githubusercontent.com/845559/203120270-647ba9f6-870f-448a-b40a-090e107d3d1a.png)

You can see that the Styles menu shows that it's Normal text, not Heading 1.
![image](https://user-images.githubusercontent.com/845559/203120420-462fec08-96e4-4c7e-8d62-0fe184ab14d9.png)

**Environment (if applicable):**
 - OneNote Version: [e.g. Office 2019, O365, also 32bit or 64bit?]

Microsoft OneNote for Microsoft 365 MSO (Version 2210 Build 16.0.15726.20188) 64-bit 

![image](https://user-images.githubusercontent.com/845559/203121020-6e30eb4d-dc7d-4ffc-a7b8-2ab043bdec77.png)

 - OneMore Version [e.g. 3.4 - from the About dialog or from the log file]
5.3.0

**Additional context**
I have stepped through the code in VS 2022 and see that the markdowndeep code converts the Headings to HTML h1, h2, etc., tags.  But the `clippy.Paste()` code looks like it's leveraging OneNote's internal paste mechanism to convert the HTML to OneNote's XML markdown, which treats the headers like Normal style text with attributes to make them look like actual headings.

Is there a good way to get OneNote to convert those headers to actual Heading 1, Heading 2 as part of the clipboard paste process?

Thanks!

**Comment by stevencohn** [comment]
OneMore uses a nuget package called MarkdownDeep to convert the markdown to HTML and then it imports the HTML. Yes, some context is lost in translation.

To properly translate, a custom provider would need to be created to convert from markdown to OneNote directly. At this time, this enhancement will be prioritized related to ongoing initiatives.
