### ISSUE TITLE
Shortcut(s) to Duplicate Line Current Line Up/Down

### ISSUE THREAD

**Issue by megamorphg** [stevencohn/OneMore#732]
**Is your feature request related to a problem? Please describe.**
I frequently need to duplicate a line (and then edit it), especially related to code.

**Describe the solution you'd like**
1. Have caret anywhere on a line of text
2. Press shortcut to duplicate line up or down (Alt + Up or Alt + Down)
3. Line duplicates and caret goes to the newly generated line at same position within the line as it was

**Describe alternatives you've considered**
I can create an AHK script to do this but I wanted to see if this is something you would like to add as a keyboard shortcut instead especially the AHK script may be slower.

**Comment by stevencohn** [comment]
Duplicate Paragraph command added to Edit menu, bound to Alt+Shift+C

Duplicate Paragraph Above command available on Command Pallette, but can also assign your own key sequence from Settings/Keyboard

**Comment by stevencohn** [comment]
Nope, I absolutely broke it,.100% :-(

**Comment by stevencohn** [comment]
Will be fixed as part of #766
