### ISSUE TITLE
Add option to import images along with Import Hyperlinks command

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#734]
You can try to reproduce the bug with this page
https://www.blog.pythonlibrary.org/2021/09/14/python-101-how-to-work-with-images/

**Comment by stevencohn** [comment]
Once imported, use the _References... Replace URLs with Images_ command.

... Until I can add that as an automated option to the import dialog

**Comment by stevencohn** [comment]
It was in fact a defect.
