### ISSUE TITLE
Applying a Custom Style takes more than a minute and hangs OneNote while applying

### ISSUE THREAD

**Issue by julie777** [stevencohn/OneMore#739]
**Describe the bug**
When I apply a custom style it takes a very long time to complete. Previously it completed quickly.

**To Reproduce**
1. click on a title
2. `<ctrl><alt><shift>1`
3. wait
4. wait some more
5. finally the style changes.

This happens regardless of how I invoke the change
- cursor in title
- entire title selected
- use keyboard shortcut
- use quick style button in ribbon

**Expected behavior**
I expect a near instantaneous application of the style

**Screenshots**

**Environment (if applicable):**
 - OneNote Version:  O365, 64bit
 - OneMore Version 
 
![image](https://user-images.githubusercontent.com/5090005/203629339-92c067a0-3e65-4fb8-9f16-e0892ba28e7f.png)

**Additional context**
I recently changed from office 365 32bit to 64bit. I'm not sure if that change was when the problem started. I also upgraded to the latest version of OneMore. Again, I am not sure when the problem started relative to the two upgrades.

A bit more investigation revealed that on a new page with a single word style changes for that word appear immediately. 
The page that is slow has almost 6000 words in several hierarchical lists.

The log doesn't tell me much:
35220:1] Running command ApplyStyleCommand
35220:9] Running command ApplyStyleCommand
35220:1] Running command ApplyStyleCommand
35220:1] Running command ApplyStyleCommand
35220:1] Running command ApplyStyleCommand
35220:1] Running command WordCountCommand
35220:8] SaveToMRU using derived name WordCountCmd

**Comment by stevencohn** [comment]
This is due to the OneNote Interop API provided by Microsoft. I have a document with 47,000 words After adding some timed diagnostic logging, you can see how long each phase take when applying a custom Emphasis style to a selected text range:

```
16320:1] Running command ApplyStyleCommand
16320:1] ..applying style (13) Emphasis
16320:1] ..loaded page, applying style @ 00:02.45
16320:1] ..applied style, saving page @ 00:02.46
16320:1] ..saved @ 01:03.01
```

Loading the page takes only 2.45 seconds. Applying the style takes about 0.01s. But saving the page takes over a minute.

I'm researching alternatives that will save parts of a page. I've never had luck in the past but maybe that was a while ago so I'm hoping seeing it with fresh eyes will uncover a solution... wish me luck!

**Comment by jasonjac2** [comment]
So, keep us posted on updating partial page update and anything we can do to add weight to it.  I posted into MS newsgroups about Graph API issue with partial page updates.

**Comment by stevencohn** [comment]
Saw that @jasonjac2 and I'm following the ticket. I need to gather more evidence before raising my own ticket

**Comment by julie777** [comment]
> ```
> 16320:1] Running command ApplyStyleCommand
> 16320:1] ..applying style (13) Emphasis
> 16320:1] ..loaded page, applying style @ 00:02.45
> 16320:1] ..applied style, saving page @ 00:02.46
> 16320:1] ..saved @ 01:03.01
> ```

What does the "16320:1]" at the beginning of each log line mean?

**Comment by julie777** [comment]
@stevencohn 
> Loading the page takes only 2.45 seconds. Applying the style takes about 0.01s. But saving the page takes over a minute.

Well, I guess my though about being proportional to the amount of page content was correct. 

I also had some of the same issues with OneNote when creating Onetastic macros. Some operations just take a long time, and worse Microsoft has a fast way but it is not exposed in the API.

**Comment by stevencohn** [comment]
First two fields are ProcessId and managed ThreadId

**Comment by julie777** [comment]
I am going to close this. The issue does document the cause.
