### ISSUE TITLE
Feature request: Search all the articles that contain certain keywords, allow the user to select them and move or copy to another section

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#74]
Currently there is no way to search all the articles that contain certain keyworkds and then select the results and perform certain operations with them 
All you can do after searching is to click on an article
I would like to be able to select the results of my search (the list of articles) and then move them to a section I chose

Concrete example: When clipping articles form internet using the web clipper they all go in a default section that I pick
Later on when I research a subject I would like to be able to search the default section for all the articles that contain specific keywords and then move/copy the results of that search to a section where I am grouping all the articles for that topic that I am currently researching

**Comment by stevencohn** [comment]
https://github.com/stevencohn/OneMore/releases/tag/3.5

**Comment by CLITrees** [comment]
You are amazing , thank you
Your addon will soon literally be packed with extremely good features, better than what MS included
