### ISSUE TITLE
Duplicate page in context menu

### ISSUE THREAD

**Issue by drandarov-io** [stevencohn/OneMore#741]
**Is your feature request related to a problem? Please describe.**
I often need to duplicate a OneNote page or template, and copy and paste is finnicky. It's one of the most common things I do in OneNote page management.

**Describe the solution you'd like**
I would like to have a "Duplicate" option in addition to "Copy" and "Paste" like many other tools offer.
![image](https://user-images.githubusercontent.com/13102251/203730953-1fc9c523-0203-4346-bfd3-9b47f4138001.png)

**Describe alternatives you've considered**
The only alternative I know is copy and pasting the page, setting up some kind of automation or using "Move or Copy..." which puts the page at the bottom of the section, which is also problemetic when there are a lot of pages.

**Additional context**
-

**Comment by jasonjac2** [comment]
See lower on the menu "Move or Copy" copies a page to a new location.  The only pain is that it puts it as the last page on the list, then you have to use OneMore's function to move it to the top, if like me, you have hundreds of pages.

**Comment by drandarov-io** [comment]
> See lower on the menu "Move or Copy" copies a page to a new location. The only pain is that it puts it as the last page on the list, then you have to use OneMore's function to move it to the top, if like me, you have hundreds of pages.

I've added it to the alternatives above, but as you have stated. It's still a rather frustrating alternative.
