### ISSUE TITLE
Sorting list leads to data loss

### ISSUE THREAD

**Issue by Virility** [stevencohn/OneMore#742]
https://user-images.githubusercontent.com/8846783/203868263-af762e89-3bd8-4cb8-847a-6e83925d8971.mp4

Just a list of links and some text.

**Comment by stevencohn** [comment]
Seems to occur only when the text cursor is just before the very first character of the very first item.

Data loss is high-priority. Will fix immediately.

**Comment by stevencohn** [comment]
And thanks, I now know what echinoderm and syngnathidae are!

**Comment by Virility** [comment]
Right on! Swift fix, and I'm just trying to learn a little more by taking notes on those, haha. Cheers mate.
