### ISSUE TITLE
Editing a custom style doesn't allow color change

### ISSUE THREAD

**Issue by julie777** [stevencohn/OneMore#743]
**Describe the bug**

In OneMore I select edit styles and then click on the font color or highlight color and their are no choices. I think this has something to do with page theme because changing page theme changes colors of headings.

![image](https://user-images.githubusercontent.com/5090005/203870387-d39faa22-152d-45c8-afb9-bb8e579165cb.png)

**Environment (if applicable):**
 - OneNote Version: O365, or 64bit?]
 - OneMore Version 5.3.0

**Additional context**
I don't know if this is an interaction with "page theme", "page style" or "style theme". In fact I don't really understand which of the following are the same or something different:
- page template
- page style
- page theme
- style theme

In addition, after reading OneNote documentation about page templates, OneMore doc about custom styles and reading the wiki page about styles, I am still confused.

I understand the custom named text/paragraph styles.
I understand that if I "apply styles to page" the custom named styles will be applied to matching paragraphs.

How do I create a page style/page theme?

Do OneNote templates or OneMore page themes allow modification of the built in styles in OneNote?

**Comment by stevencohn** [comment]
Both the highlight button and the font color button are split buttons. If you click the main part of the button then a color dialog is displayed. If you click the down arrow then you see the "Default" option.

![image](https://user-images.githubusercontent.com/9964757/203979485-9d821300-b0e9-4307-bacd-0c36cf2d5943.png)


<img width="348" alt="image" src="https://user-images.githubusercontent.com/9964757/203979575-81f0451d-a630-445f-85c2-cc5bfa1a046d.png">

**Comment by julie777** [comment]
@stevencohn 
That seems backwards to me. 
Normally buttons with an arrow take the default action when the button is clicked and show more choices when the arrow is clicked.   I suspect that is why I never clicked the button, but only on the drop-down arrow. Then I was confused because there were no choices available.

For example test how the highlight and font color buttons on the Home tab in OneNote work. 
In the image below you can see that both buttons show that the current color is red and will be applied when the button is pressed.

![image](https://user-images.githubusercontent.com/5090005/204057018-7283460f-03cd-43f4-b170-007d90d7313d.png)

**Comment by stevencohn** [comment]
The default action is to change the color which displays the dialog.

The "Default" option is a special case. Internally, the color is set to "auto" which OneNote interprets as whatever the color is for the current context. 

So with what users are looking to do - and what it sounds like you're looking to do - is set the color to something specific and that's what the main part of the button is intended to do.

**Comment by stevencohn** [comment]
Honestly, it was a cheap solution to building a custom color selector dialog that also exposes an option to set a "default". With that, the SplitButton can become a simple Button and problem solved - but that's a ton of work for very little value

**Comment by julie777** [comment]
Maybe I will look at it if I have time. Sadly, I have to learn C# to help with OneMore. :-(

**Comment by stevencohn** [comment]
Will consider alternatives when tackling a refresh of that dialog. Closing this for now.
