### ISSUE TITLE
Consider enabling github discussions

### ISSUE THREAD

**Issue by julie777** [stevencohn/OneMore#744]
I've used other github repos that had discussions enabled. They were useful to keep usage questions that could be answered by other users partitioned from issues.
They also provided a place to have potentially lengthy discussions about possible features, etc.

Have you considered enabling github discussions.

**Comment by stevencohn** [comment]
I have and to be quite honest, I found that users are no disciplined enough to delineate Discussions from Issues and I found that I spent a lot of time curating the two.

**Comment by julie777** [comment]
> I have and to be quite honest, I found that users are not disciplined enough to delineate Discussions from Issues and I found that I spent a lot of time curating the two.

That makes sense. It can work without discussions partly because you don't have thousands of open issues.
I haven't spent the time to search issues based on: bug, feature request, or question. 
Maybe you could add an issue type for discussion?
A note in the README about issues and filtering by sub-type might be useful.

**Comment by julie777** [comment]
Okay. I am not really that lazy. 
For information to be used by all:
- the sub types that you choose when creating an issue is a label, just like all the other labels you see in the full list of issues.
- to filter issues by any label just add "label:question"  or replace question with any label, for example: high-priority.
- the filters section has a button for labels so you can see the complete list
![image](https://user-images.githubusercontent.com/5090005/204056663-60509b8c-b638-46ad-832b-9f92f3063409.png)
