### ISSUE TITLE
About wiki editing

### ISSUE THREAD

**Issue by julie777** [stevencohn/OneMore#745]
**How can I help you?**

The most general concept of a wiki is that anyone can create, read and update pages.
I am used to just fixing typos that I notice. 
Today while looking for information about custom styles I realized that the wiki page was outdated.

I haven't looked at how github manages permissions on the wiki, so I don't know if it is like the repo where you can give rights to maintainers...

I also don't know if there are ways review page history or diffs as there are in the wiki software that I have used previously. 
With wikis that I have used that allowed open editing there were notifications for page changes so that "principal maintainers" could monitor changes and diff to see details and handle changes they didn't like.

That is probably enough for you to respond with your thoughts about wiki maintenance.

Related: I noticed that you do link from the README to the wiki so that real documentation can be in the wiki. I would actually suggest streamlining the README much more, for example "how to install" or "developing onemore" could be presented better on a wiki page.

**Comment by stevencohn** [comment]
I started out with it enabled years ago and it almost immediately got abused, so nope.

**Comment by stevencohn** [comment]
I like your idea about simplifying the readme

**Comment by julie777** [comment]
> I like your idea about simplifying the readme

@stevencohn 
I will start looking into the process creating a pull request for the README and submitting corresponding wiki page changes.
