### ISSUE TITLE
Clarify the differences and interactions between Custom Styles and Page Themes

### ISSUE THREAD

**Issue by julie777** [stevencohn/OneMore#746]
Continued from my bug report about changing text color in Custom Styles which left me very confused. 

I am starting to understand. Most of my problems are, I believe, a result of inconsistent and/or confusing terminology.

My aha moment was when I was struggling with the menu choice "load styles". I originally though that this should be load style since only one file could be loaded. I was also struggling with how to create one of those "style" files.

I have spent a couple hours experimenting and examining the Custom Styles interface and writing notes. I believe that I now have a fairly complete understanding.

# My Current Understanding

<dl><dt>OneNote styles</dt>
<dd>named paragraph styles that cannot be modified.</dd>
<dt>OneMore Custom Styles</dt>
<dd>similar to OneNote styles, but can be both customized and extended with additional styles by the user.</dd>
<dt>OneMore Page Theme</dt>
<dd>a set of custom styles that can be loaded, edited, saved with a name and applied to the current page as a unit.</dd>
</dl>

## The following contributed to my confusion:
<dl><dt>OneNote Page Template</dt>
<dd>Because I was looking for correspondence with the multiple terms used by OneMore</dd>
<dt>OneMore Page Style</dt>
<dd>which I believe is an alias for Page Theme</dd>
<dt>OneMore Style Theme</dt>
<dd>Which I also believe is an alias for Page Theme</dd>
</dl>

# Potential Changes
I think that a number of changes, some easier than others, will make Custom Styles and Page Themes much easier to understand and use:

1.   Remove unnecessary terminology and standardize on one term for styles and another for themes. (I will be using Custom Style and Page Theme for the rest of this post.) This is mostly a documentation change and with search can be completed easily.

2.   Separate Custom Styles and Page Themes, both in the interface and the documentation. Looking at the Custom Styles menu you can see that the top part is about applying individual styles and the bottom part about managing page themes.

        a.    I would propose that the reference in the README and any feature list mentioning "custom styles" should add "as part of page themes". The Wiki page should be Page Themes and Paragraph Styles. The notion that you should be creating your own page themes is not obvious to those of us who have used Word for decades. It needs to be more prominent.

        b.    Separate the "Apply Style" menu which opens style choices that can be applied to a paragraph. Even better would be to present that in the same format as the OneNote styles in the ribbon.  Even better, make it possible to just remove OneNote Styles from the ribbon and replace it with OneMore Styles. (Currently OneMore doesn't allow customizing the OneMore section of the Ribbon or adding OneMore items to other ribbon groups. I will create a separate issue discussing this.)

        c.    create a separate menu for Page Themes that makes it very obvious that themes can be applied to pages as a whole, themes can be defined as a whole,  etc. The Page Themes menu might look like:
 		
```
                Page Themes
 		         Load Theme                               - means change the current theme
 		         Edit Themes
 		         Apply Theme                              - apply the current theme to the current page
 		         Create Style from Selection     - add this style to the Current Theme
 		         Change Page Theme                 - select and apply a new them to the current page (this is problematic and will be addressed below

```
3. Update the Page Theme dialog (called edit styles) and the Change Theme dialog. I am going to leave this empty for now, and wait until I see the response to details that I did provide.
		
@stevencohn 
If this seem reasonable to you then I will try to create a pull request. I haven't tried to build OneMore yet so it may take some time. I will also produce modified wiki pages for you to review.

**Comment by julie777** [comment]
I have spent a lot of time since I submitted this writing more about it and trying to describe a coherent suggestion. I hope to submit it soon.

**Comment by stevencohn** [comment]
This is work-in-progress and I hope to release it this weekend

**Comment by julie777** [comment]
I am going to add my current thoughts before you close the issue. I will go look at the pull request also.

**Describe the solution you'd like**

The goal is to
- use the standard Office terminology
- add clarity to OneMore
- provide ease of use for the user.

Using this section of the OneNote home ribbon with some reordering as a reference which I rearranged to clearly show hierarchy of Page Template/Style Set/formatting

![image](https://user-images.githubusercontent.com/5090005/216786894-0bfeb6c6-4c2e-48f9-8f3e-ebf63fb05f7a.png)

I am going to try and be as concise as possible in this post and I will elaborate later when necessary.

In MS Office there is a hierarchy of "style and formatting". Some of the products such as OneNote do not support as much as others such as Word. Starting from the top down or outside working in.

# Theme

A theme is for the overall look of the entire Office suite. Dark, Light, etc. are themes. Many of us have Office set to use the System Theme. 
- OneMore should stop using the word theme, because it really doesn't mean the same thing

# Page Template

MS uses page templates to completely customize pages. A page template can be set as a default for all new documents, selected when creating a document. Because OneNote has hierarchy and other aspects within a page that Word, etc. do not this means that a page theme could be very complicated.

In OneMore, a page template would have the same definition, but could be more easily specified and be changed for an existing page. OneMore should use Page Template to indicate a set of any customization applied to a page. This is the first item in the hierarchy and the left section of the formatting grouping of ribbon items. When OneNote creates a page it uses a default template. This should be a dropdown to change the template for the current page, which includes all settings.

OneMore should use the term "page template" and allow creating page templates that include other OneMore customizations.

Page Template selection is the first item in the ribbon and the most inclusive of the custom groupings of settings.

The current OneNote dropdown for page template selection would work, but it would be nice if the OneMore version of it displayed the template in use for the current page.

# Style Set

This is just a new term for the existing implementation of a group of text styles that are designed to work together.
A page template includes a Style Set as part of its definition.

Instead of changing the entire page template for an existing page, the user can change just the Style Set to change formatting without changing page attributes such as background image, page size, etc.

OneMore is different than OneNote because it allows definition of any number of named Style Sets. OneNote has one bult-in style set. Word has a built-in style set that can be modified. The OneMore solution is much more powerful as it allows referencing style sets by name and creating different page templates with different style sets by name instead of redefining all the individual values.

# Style

A style is a style set definition for a combination of formatting attributes for a given type of text element. It has smarts, so if the cursor is at a point in a paragraph and I apply the style "Heading 1" it knows to apply the style to the entire paragraph. It also understands (or should) that a paragraph scoped style such as heading controls not only the attributes on the words, but includes spacing withing and around the paragraph.
  A heading paragraph should have a blank line above and below it, those line should have defined heights, words should be "title cased" etc. 
  A word format such as "strong" should apply to only the word containing the cursor if there is no selection.
In general, there should be very few "word" formats as part of styles because those attributes are handled by formatting.

# Formatting

OneNote has a formatting section "Basic Text" in the ribbon which contains all the available attributes that can be applied to text. Some of these such as bold, or superscript are typically word attributes. Others are attributes that should be used to define styles and would not be commonly used when a users is used to using styles. These are attributes such as font, font size, and list or indentation.

There are a few, such as text color, or text highlight color that are often used in style definitions, but can be useful for individual words. OneNote has a strange way of organizing these, likely because for many users the default styles don't work and they can't change them. 

Another aspect - list and indent styles provided under "Basic Text" by OneNote are orthogonal to other styles. They only affect the paragraph layout and not the text attributes.

OneNote shows underline and strike-through as separate buttons, but superscript and subscript is a drop-down.
(For some reason, MicroSoft changed the highlight color dropdown to just a grid of colored boxes, instead of the normal color chooser that is still used for text color.   grrr...)

# Conclusion

In a perfect world, I would have a "Formatting" section in the ribbon with 
1. a dropdown that shows the current page template and allows choosing a new one to apply
2. a drowdown showing the current page Style Set (originally from the page template) and allowing changing it for the entire page.
3. a dropdown for paragraph styles that applies the selected style to either the paragraph containing the cursor, or to the selected paragraphs
4. Builtin shortcuts for styles would be mapped to the current style set for the page.
5. a group of buttons for formatting words with bold, super, sub, etc. and colors.
6. every selection would show the keyboard shortcut as it does now and trigger text for some items, "- " to create a list item, would continue to work.
7. The new formatting section would be more powerful and take up less screen space, and present the choices in obvious ways.

And, when applying a paragraph style, or a style set to a page, individual word attributes would be unaffected.

This would require adding metadata to the page XML to indicate page template and style set (which might have been changed from the page template). I haven't looked to see if something like this already exists or could be added.


These are all the individual attributes that can be applied to text, such as font size, bold, superscript, etc.  For the most part they are used on individual words, although many of them are really just attributes that one would use to create styles from. 

I have noticed that just like tags, any styles used in a page have their definition saved in the page so they remain the same regardless of any global settings changes. I am still thinking about the effects this has. (Regarding tags I have already written Onetastic macros to collect all the definitions from all notebooks, apply modifications globally etc.)

**Comment by stevencohn** [comment]
My latest branches from #746 have been merged today. It needs a little more refinement and testing to do but I expect it's just about done.

I've settled on "Styles Themes". I understand your arguments against using the word "theme" but this latest implementation, I believe, does a pretty good job at marrying what you call a Style Set with (optionally) a page color - that combination is what I'm calling a Style Theme. You can apply the currently loaded Style Theme to a page.  All of the commands under the Custom Styles drop down menu have been renamed accordingly.

<img width="241" alt="image" src="https://user-images.githubusercontent.com/9964757/216789709-68190951-001a-4a02-8cf4-30e77b03e3e2.png">

Page templates are interesting and perhaps something that I'll consider in the next phase. But realistically, the new implementation is only a couple of clicks away from what I think you're envisioning, albeit a little more manual to apply a page template and then apply a style theme.

> And, when applying a paragraph style, or a style set to a page, individual word attributes would be unaffected.

Yes! This is the next phase, to model the behavior more closely after how Word works. I do not think you need to complicate it with metadata. The style should dictate whether or not it overrides styling of words within a paragraph.

**Comment by stevencohn** [comment]
My latest branches from #746 have been merged today. It needs a little more refinement and testing to do but I expect it's just about done.

I've settled on simply "Styles". I believe this latest implementation does a pretty good job at marrying what you call a Style Set with (optionally) a page color. When you define a set of styles, you can also indicate that you want to force the page background to a chosen color with "Apply styles to page". If enabled, that background color is properly rendered in the style gallery as a hint that it will override the current page background. All of the commands under the Custom Styles drop down menu have been renamed accordingly.

Page templates are interesting and perhaps something that I'll consider in the next phase. But realistically, the new implementation is only a couple of clicks away from what I think you're envisioning, albeit a little more manual to apply a page template and then apply a style theme.

> And, when applying a paragraph style, or a style set to a page, individual word attributes would be unaffected.

Yes! This is the next phase, to model the behavior more closely after how Word works. I do not think you need to complicate it with metadata. The style should dictate whether or not it overrides styling of words within a paragraph. 

And in my defense, I originally implemented this wholesale restyling because that's how OneNote's built-in styles work. Also, the OneMore styles dialog does let you choose whether you want to recolor text. It is possible to add checkboxes to other properties too, like bold and italic, et. al. However, I'm conscious of how complex the Word style dialog is and don't want to make it too overwhelming. OneNote is first and foremost a knowledge management tool. While it's capable of creating quite fancy pages, that's not its primary competency; if you want that, then use Word ;-)
