### ISSUE TITLE
Add support for more customization of the Ribbon

### ISSUE THREAD

**Issue by julie777** [stevencohn/OneMore#747]
**Is your feature request related to a problem? Please describe.**

Most addins add to the Home ribbon which then gets so full that it starts collapsing items to a smaller format.
This causes the ribbon to be hard to use.
Most addins, such as OneMore also don't allow customizing their group in the ribbon, such as removing items not used.

**Describe the solution you'd like**
I would like the ability to have granular control of ribbon items to allow more customization for efficiency in my work environment.
1. make it possible to add/remove individual items in the OneMore group to hide what I don't use.
2. make individual items be separate commands that can be added to a custom group
3. provide the option to show OneMore as a separate tab on the ribbon instead of a group in the Home tab.

I like to use the home tab with custom group(s) to collect all the items that I frequently use and use the other tabs for infrequently used items. This works reasonably well for all the built in commands and groups. However, for addins that just add a group to the home tab with all their commands and don't allow any customization I run out of space in the home tab.

OneMore has so many commands that it has already resorted to several kinds of collapsing techniques, small items, dropdown lists etc. to keep its group a reasonable size. Sadly it is not the only addin that I use. I use Onetastic and it gave me the idea for (3) above because it can split its group and show macros in a separate ribbon tab and leave some of its commands in the home tab group. Even so, it still takes up too much space because it doesn't support enough of (1) and (2).

**Comment by stevencohn** [comment]
Sadly, allowing you to modify groups can't be done, at least to my knowledge (you said "most addins..." Are there any that do allow you to modify their groups directly - meaning not through some setting that tells it to morph itself?)

I've played with other (optional) layouts that categorize features and spread across tabs but never finished to be honest. I realize it's not the easiest thing in the world to create your own tabs but I left it to users to make up their own.

A little secret: my desire is to simplify OneMore, not keep adding on to it. I think there are features that I added because they sounded like a cool challenge but are either under-users or ill-designed and really have become nothing but a headache to maintain.... ah, one can dream anyway....

**Comment by jasonjac2** [comment]
I think asking for telemetry consent so you can see which features get used would be cool.  I know with my line of bsuiness system, some very vocal users shout for things and then I look at the audits later and they get used for a few weeks, never to be touched again.

I have a home1 tab which I move the OneMore group to, then add a OneMore1 group to the home tab and add the items I want in there - is that what you mean?
![image](https://user-images.githubusercontent.com/68282090/203984476-27a8723d-dd0d-45b0-a89f-6cf03363a169.png)

**Comment by stevencohn** [comment]
@jasonjac2 Indeed, telemetry is something I've considered. What tech have you used to store such data?

**Comment by jasonjac2** [comment]
Our system is a database system and I have written audit object, so I have a set of calls and register button clicks, enter / exit screen and any database changes.  It makes like much easier when we get asked whodunnit.  It all gets saved into the main database and then archived off into an audit database.  The audit database is probably 10x larger than the actual data database!

**Comment by stevencohn** [comment]
Oh just on-prem? I was hoping you had a cloud-based solution :-)

**Comment by jasonjac2** [comment]
As I don't have experience of cloudy solutions in this area, I asked the user group I run (ukDevGroup) and Richard, who lives his life in AWS and such like came back with: There are many solutions out there (no Delphi-friendly though that I have found - not cloudy anyway). Seeing as he's on C# there should be many good options though and many have a free tier that is often suitable for open-source or low-volume projects. Here are some I have used that I would recommend:
NewRelic (https://newrelic.com/)
DataDog (https://www.datadoghq.com/)
Sentry (https://sentry.io/)
Rollbar (https://rollbar.com/)
They all have their strengths and weaknesses. If he wants more insight on why I'd choose one over the other, I am happy to have a chat but this post could get long if I blurted it all out here :grimacing:

**Comment by stevencohn** [comment]
Brilliant. Thanks

**Comment by julie777** [comment]
> Sadly, allowing you to modify groups can't be done, at least to my knowledge (you said "most addins..." Are there any that do allow you to modify their groups directly - meaning not through some setting that tells it to morph itself?)
> 
> I've played with other (optional) layouts that categorize features and spread across tabs but never finished to be honest. I realize it's not the easiest thing in the world to create your own tabs but I left it to users to make up their own.
> 
> A little secret: my desire is to simplify OneMore, not keep adding on to it. I think there are features that I added because they sounded like a cool challenge but are either under-users or ill-designed and really have become nothing but a headache to maintain.... ah, one can dream anyway....

I too always try to simplify, both use and implementation.

Onetastic has some commands that show up in the command pane of "customize ribbon" so that you can add them to custom groups. It also has a setting to move all macros from the Onetastic section of the  Home tab and move them to a Macros tab that it creates on the ribbon. I can also remove many of the individual commands from the Onetastic section of the Home tab. Sadly, there are many issues with naming of the commands making them hard to find when customizing the ribbon, and missing functions, such as after removing the Onetastic group from the home tab, there is no way to add it back.

**Comment by stevencohn** [comment]
Oh OK, so it's not changing the built-in OneNote groups and doesn't allow you to update the Onetastic group through the normal OneNote customize ribbon dialog.

OneMore and OneTastic allow you modify their owns groups through their own settings, admittedly OneMore's is extremely limited. I understand though

**Comment by julie777** [comment]
Sorry if I was pushing too hard. My intent was just to share information and try to help make a great project even better.
I realize that you have to prioritize and don't have time to do everything.

How about a new label "Deferred until someone volunteers to work on it" worded in a more concise way?

**Comment by stevencohn** [comment]
Oh not pushing too hard at all! I value your input.

Usually such a label would be "help-wanted" which I have in the list but haven't used yet! :-)

**Comment by julie777** [comment]
I saw that, but the description seemed to imply something else, or maybe I misread it.

**Comment by stevencohn** [comment]
I changed it to "Looking for contributors to help out"
