### ISSUE TITLE
Change page theme background not applied properly when UI set to Dark/Dark

### ISSUE THREAD

**Issue by julie777** [stevencohn/OneMore#749]
**Describe the bug**
I changed the page theme to the current theme using the Change Page Theme dialog without changing anything, per the screenshot below. The background color stayed white. 

**To Reproduce**
1. Current page has a white background
2. Click Custom Styles/Change Page Theme
3. on my test the dialog is as shown below
4. the page background is still white

**Expected behavior**
I expect all the paragraph styles to be changed to match the Page Theme and the background to be set per the dialog.

**Screenshots**
![image](https://user-images.githubusercontent.com/5090005/203899062-76ca6b5e-1724-47c5-ac56-d76539554cfa.png)

**Environment (if applicable):**
 - OneNote Version: O365, 64bit
 - OneMore Version 5.3.0
 - 
**Additional context**
Part of the time I am getting an error when I select OK
I'm not sure where in this log the click on OK occurred.

33108:6] Running command ChangePageColorCommand
33108:6] Error running command ChangePageColorCommand
33108:6] System.Runtime.InteropServices.COMException
Message: System call failed. (Exception from HRESULT: 0x80010100 (RPC_E_SYS_CALL_FAILED))
Description: Unrecognized error code 0x80010100
ErrorCode: 0x80010100 (-2147417856)
HResult: 0x80010100 (-2147417856)
Source: office
StackTrace:    at Microsoft.Office.Core.IRibbonUI.Invalidate()
   at River.OneMoreAddIn.Commands.ChangePageColorCommand.UpdatePageColor(Page page, String color)
   at River.OneMoreAddIn.Commands.ChangePageColorCommand.<Execute>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.CommandFactory.<Run>d__6.MoveNext()
TargetSite: [office] Microsoft.Office.Core.IRibbonUI::Invalidate()

**Comment by julie777** [comment]
Well, a little more experimenting and Change Page Theme does apply the specified background color, except for black and white. It treats black as white and white as black. 

I suspect that has something to do with the OneNote Options/General/Office Theme being set to use System Setting and having the system set to Dark.

It still seems like black and white should match the actual page color.

**Comment by stevencohn** [comment]
Yes this only happens in dark mode when you still have the OneNote default dark background.

FYI, you can change the OneNote default dark background using its View/Switch Background button. Then OneMore's background theme is applied correctly. 

But I've confirmed, the dark/dark scenario is broken.
