### ISSUE TITLE
Documentation for valid regular expressions in "Search and Replace"

### ISSUE THREAD

**Issue by Chilangosta** [stevencohn/OneMore#75]
Love love this. I've been using Onetastic on and off for years now, and while I supported Omer's initial decision to make money from what was certainly a lot of work, it's kinda become too much for me.

I'm super interested in using the regex in Search and Replace; I'm having to do a lot of trial and error to determine what is valid and what is not. It would be awesome if you gave some more context on what to do in order to take advantage of the regex functionality! For instance, are lookaheads/lookbehinds supported, greedy/lazy, literal quoting, etc. It does look like there is some literal quoting, but I'm not sure how it works, or how to for instance search for a literal `+` or `"`, for example.

**Comment by stevencohn** [comment]
Hi, thanks! There's no magic here. It uses .NET's Regex.Match so it's standard regular expression syntax. 

It works basically line-by-line so don't expect it to recognize patterns that span paragraphs or across table cells. It's not very smart in fact.

To match literal tokens like plus and quote, use the normal regular express backslash escape sequence such as `\.` and `\+`
