### ISSUE TITLE
Include background color as part of the Page Theme

### ISSUE THREAD

**Issue by julie777** [stevencohn/OneMore#750]
**Is your feature request related to a problem? Please describe.**
The background color on the Change Page Theme dialog is surprising/confusing. In addition the warnings about contrast also add to the issue.

**Describe the solution you'd like**
Allow setting the page color in the Page Theme (edit settings) dialog.
Apply the page color as part of Changing/applying a page theme.

This eliminates problems of a theme being applied to a page which has a background color with insufficient contrast.

**Comment by stevencohn** [comment]
While I don't disagree that adding background to the Edit Styles dialog could be useful, there has been requests in the past to separately add the ability to set the background to more colors than OneNote's default 16.

**Comment by julie777** [comment]
So maybe a combination of both. If I want to set the background color as part of the Page Theme I can, but I can also leave it unset to work like it does now.

Part of my problem is that I am using dark mode in windows -> dark mode in MS365, but somehow I have white backgrounds on some pages. (I am in the process of trying to clean up the results of >10year of experimenting)

**Comment by stevencohn** [comment]
This will be resolved by #746
