### ISSUE TITLE
Is there a way to add additional commands to shortcuts?

### ISSUE THREAD

**Issue by julie777** [stevencohn/OneMore#752]
**How can I help you?**
I just realized that I can customize OneMore shortcuts. YAY!!!
This is something that drives me crazy in almost every app that I use. I want shortcuts for the things that I do often. I live by shortcuts in the browser, vscode, OneNote, etc.

Along with that I discovered the command pallet that works like VSCode. Good on you!

However, there doesn't seem to be a way to add new commands to the shortcut dialog. Am I missing something?

In addition the commands in settings allow providing an alias. What is that used for?

Also, they shortcuts dialog doesn't list every shortcut that OneMore provides. Or at least I don't think it does. I just found the long list of key bindings for OneMore in the Wiki.

My thoughts...
It seems like commands, aliases, and shortcuts all go together. Like you said, make it simpler. 
One dialog could accomplish listing and customizing all commands.

**Comment by julie777** [comment]
Another thought...

Choosing which commands are added to context menus could also be put in the unified command dialog.

I don't even know if OneMore provides a way to customize commands added to context menus. However, I really like that option because context menus can become very long and hard to use when various apps, addons, etc all add their own commands.

**Comment by stevencohn** [comment]
You can assign an alias to a command, making that alias also available in Command Pallette. Both will be available but you can type your own shorter alias for quicker access.

Some commands are parameterized which means they can't work in the Command Pallette. 

The list of commands available to be added to the context menu is currently a manual hard-coded programming task. When I introduced the Command Pallette, I began the process of making commands more dynamically discoverable and categorized, with the intent of letting that drive the context menu Settings as well. I just haven't gotten around to that yet.

**Comment by stevencohn** [comment]
Related to #753, same branch adds all possible commands to context menu sheet in Settings dialog

Context menu Settings sheet will be enhanced in a separate ticket.
