### ISSUE TITLE
"To Title Case" does not use proper guidance for deciding which words are capitalized

### ISSUE THREAD

**Issue by julie777** [stevencohn/OneMore#754]
**Is your feature request related to a problem? Please describe.**
"to title case" is simply capitalize all words. This would be another reasonable command, although I don't know of any specific use for it.

**Describe the solution you'd like**
I would like "to title case" to capitalize using the long standing definition that is used when writing anything that gets published.
I originally learned from [Chicago Manual of Style](https://www.chicagomanualofstyle.org/home.html), but here are a couple web links.
-  https://becomeawritertoday.com/what-is-title-case/
-  https://apastyle.apa.org/style-grammar-guidelines/capitalization/title-case

This is a low priority change.

**Comment by stevencohn** [comment]
Currently uses Microsoft's implementation of the .NET TextInfo.ToTitleCase method which admittedly is really Pascal-case and not Title-case at least for English. This method was chosen for its multi-lingual capabilities.

I'll look into the APA style as a simple enhancement which should cover a large percentage of most common cases
