### ISSUE TITLE
Feature Request: Saving selected pages as single html pages instead of all in one big html

### ISSUE THREAD

**Issue by osman1963** [stevencohn/OneMore#76]
Would it be possible to add this feature: selecting several pages then saving them each to a separate html file? and if possible too for the other formats already available in ON especially (pdf, docx). ?
Thanks for the adding the word count feature.. you are the best
Have a nice day :)

**Comment by stevencohn** [comment]
Not only is it possible, but it's done
https://github.com/stevencohn/OneMore/releases/tag/3.3

**Comment by osman1963** [comment]
wowwwww .. you are the very best .. 

Thank you sooo sooo much.. You really made my day 🥇
