### ISSUE TITLE
Shortcut to Delete Current Line

### ISSUE THREAD

**Issue by megamorphg** [stevencohn/OneMore#771]
**Is your feature request related to a problem? Please describe.**
Similar to #732, I frequently need to delete a line but usually due to using a template frequently.
I copy the template and then end up manually deleting a few bullet points from it.
I would like to be able to delete a paragraph with a single key and without having to select the line and then press delete.

**Describe the solution you'd like**
1. Have cursor anywhere on a line.
2. Press keyboard shortcut to delete line
3. Deletes that paragraph completely (if the paragraph was a bullet point in the middle of other bullets, the other bullets should be preserved)
4. Keeps cursor on the next line

**Describe alternatives you've considered**
Autohotkey (I currently do this now but am sometimes worried with using it because of sending so many delete buttons)

**Comment by jasonjac2** [comment]
"I would like to be able to delete a paragraph with a single key and without having to select the line and then press delete"
For a para, it's click in it somewhere, ctrl+a, ctrl+a, del.  Or did you want literally the line?
If para, I'm not sure it is worth the dev + another consideration is that to do that the whole page will be re-written so you will lose the - who edited & when.

**Comment by stevenmcohn** [comment]
"The developer" is happy leaving it here ;-)

Thanks

**Comment by jasonjac2** [comment]
@megamorphg you have pushed me to DL AHK, it has been on my list for a while.
