### ISSUE TITLE
Sidebar Outline

### ISSUE THREAD

**Issue by Benjamin-Watson0** [stevencohn/OneMore#778]
**Is your feature request related to a problem? Please describe.**

I think the sidebar outline is very helpful to control the article structure, but this function cannot be implemented in onenote. Can it be implemented through plug-ins.

**Additional context**

Thank you very much for your selfless dedication.😊

**Comment by stevencohn** [comment]
Sadly, no. Microsoft provides no APIs to control the OneNote sidebars.

**Comment by Benjamin-Watson0** [comment]
I understand. Thank you for your reply.
