### ISSUE TITLE
Using any OneMore features stops ongoing audio recording and deletes the recording

### ISSUE THREAD

**Issue by sstoilovABLE** [stevencohn/OneMore#784]
**Describe the bug**
Using any OneMore feature seems to interrupt ongoing audio recordings within OneNote and deletes the unfinished audio files!  

**To Reproduce**
1. Install OneMore. 
2. Open OneNote, open a new note, and click Record Audio on the Insert tab. 
3. Observe that the audio recording has started and the audio file has been inserted on the page together with the text "Audio recording started: <date and time>".
4. Go to the Home tab, and use any feature in the OneMore group - try setting a Custom Style or inserting a horizontal line for example. 
5. Observe that the audio recording has been stopped and the audio file has been removed from the page! 

**Expected behavior**
I expect to be able to use OneMore Custom Styles, insert horizontal lines and use other OneMore features without interrupting the audio recording! 

**Screenshots**
Not applicable, I think the steps are straightforward. 

**Environment (if applicable):**
 - Microsoft® OneNote® for Microsoft 365 MSO (Version 2210 Build 16.0.15726.20188) 64-bit 
 - OS: Windows 11 Pro, Version 22H2, OS build 22621.819
 - Machine: ASUS Zenbook 14-inch Flip OLED with a 2880x1800 resolution OLED screen.

**Additional context**
App log file: 
[OneMore.log](https://github.com/stevencohn/OneMore/files/10146522/OneMore.log)
The last couple of commands are me applying OneMore commands during audio recording and seeing that the recording has been interrupted.

**Comment by stevencohn** [comment]
_Note to self_ _Needs further research. Caused by rewriting page XML and overwriting embedded MediaFile. Might be solved by partial page rewrite but needs testing

**Comment by stevencohn** [comment]
_Note to self_ Alternative is to block OneMore functions while audio recording is in progress. XML will contain MediaIndex.MediaReference[@mediaID] element but no matching MediaFile.MediaReference[@mediaID] element.

**Comment by stevencohn** [comment]
It seems there is a gap in the way that the Interop API handles page updates when there is an active recording. I haven't found a way to preserve the active recording while updating a page through the API. So if it hurts, don't do that. Blocking OneMore commands that update the current page when there is an active recording on the page. A message box is displayed informing the user.
