### ISSUE TITLE
OneMore ribbon-bar selection very slow

### ISSUE THREAD

**Issue by varnk** [stevencohn/OneMore#79]
Every time I click on a OneMore ribbon button item, it takes a very long time for the sub-menu to display.  This is especially evident when choosing Custom Styles.  The delay can sometimes be up to 12 seconds.

**Comment by stevencohn** [comment]
Yes, it somehow it affected by the length of the current page. If you try it with an empty or very short page, you'll see that it's much faster. I'm investigating performance improvements but this is low priority because it works but it's just annoying.

**Comment by stevencohn** [comment]
See old discussion here https://github.com/stevencohn/OneMore/issues/24

**Comment by stevencohn** [comment]
Give this a shot:
https://github.com/stevencohn/OneMore/releases/tag/3.4.3
