### ISSUE TITLE
Navigation Pane - Separate Process / Floating Form

### ISSUE THREAD

**Issue by jasonjac2** [stevencohn/OneMore#793]
**Is your feature request related to a problem? Please describe.**
OneNote doesn't have tabs (like a browser) or a quick way of navigating to sections of a large page (like the navigation pane in Word).  In addition, when looking for things, I will have to click through a lot of page.

**Describe the solution you'd like**
A Navigator form that can be the repository of:
- where you have visited (I know you can get it in the cal, but this would be quicker to refresh or be polled to be kept up to date)
- A list of Pages and their headings for pages (pages are put onto the navigator using a hotkey or command when you are on a page).
- ability to navigate with keyboard and also remove items easily 
- have it saved in an XML or even a ON page so it can be manipulated and persistent
- I guess optionally save as and load to bring you back to a state of play
- Hotkey (maybe system wide) to bring the form to the fore and get focus
- Drag or move items up / down the list
- Have collapsible items under a page for headings (One + for the page, expands into the headings, with font or icon to say H1 ... H4 etc)
- It would become my swiss army knife for navigation
- Make it so that it could be extended to take things like search result links

**Describe alternatives you've considered**
Gem has a Pane command, 
OneTastic has favourites and shortcuts.
Using a HTML editor or even a ON page as a cache for the links and ensuring all pages have a ToC so I can copy and paste.

**Additional context**
I realise this is a big addition, but by starting small (Add Page / Add ToC for this page / Pin 

THE FINE PRINT
This is a hobby project that I started for myself. I'm happy to take requests and will promise to consider each one carefully but offer no guarantees that I will ultimately agree to their usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
_Note to self_ - this would require a polling mechanism to periodically check if the page has been updated and refresh headings and structure...

**Comment by valuex** [comment]
https://gitee.com/valuex/onflow

Previously, I developed this tool to quickly navigate through OneNote pages and paste the selected contents.

It seems that it's a option for your requirement.

You can get the complied version under \release folder.

**Comment by valuex** [comment]
> _Note to self_ - this would require a polling mechanism to periodically check if the page has been updated and refresh headings and structure...

How about enable the refreshing when user the activate the floating window either by shortcut or mouse click event?

**Comment by jasonjac2** [comment]
> Note to self - this would require a polling mechanism to periodically check if the page has been updated and refresh headings and structure...

A refresh button / hotkey would be fine - you know when the structure has changed IMO.  I would want to be as light weight as possible, so the navigation UI could have a large cache of pages.  I would have it like a cache of bookmarks and if I went to a page and knew it wasn't interesting, I would delete it from the navigator.

**Comment by jasonjac2** [comment]
I just realised in Gem that on the "Pane", a right click refresh actually refreshes the outline to whatever page you are on.  So that is pretty good I guess.  @valuex I haven't heard if  Gitee before.  I'm a bit reluctant to be downloading exe's from sites I don't know.  

@stevencohn how heavy a process is it to pull the last n entries from the history of where you have been (like you do in the Calendar tool - I am happy that it doesn't auto refresh and only does when you hit refresh - if it is expensive.

**Comment by stevenmcohn** [comment]
While OneNote has a "back" button that allows you to navigate to most recently visited pages, it does not expose this history list anywhere that I know of. I believe it's only stored in ephemeral memory since it resets when you close OneNote.

The OneMore Calendar relies on last-modified-dttm and created-dttm attributes readily available in the hierarchy XML.

**Comment by stevencohn** [comment]
While OneNote has a "back" button that allows you to navigate to most recently visited pages, it does not expose this history list anywhere that I know of. I believe it's only stored in ephemeral memory since it resets when you close OneNote.

The OneMore Calendar relies on last-modified-dttm and created-dttm attributes readily available in the hierarchy XML.

**Comment by jasonjac2** [comment]
History / Interesting recent pages: OK, so you would have to poll all instances for the "current page" to get a full history - but that isn't so interesting or more likely maybe not as good in terms of effort & reward.  

I would be happy with a hotkey to kind of add to the stack / buffer. When I am clicking about I quickly know if a page is interesting or not.  If you think of the way you kind of use browser tabs, when you are looking for something.  I google, ctrl-click a bunch of pages, skim some of them do more ctrl clicking on those pages, closing tabs as I realise I have gone down a rabbit hole.    I end up with a quickly curated set of tabs I want to read or may have the answer to the problem I am solving.

**Comment by stevencohn** [comment]
@jasonjac2  I'd like your input. Here are my thoughts for a initial drop

<img width="197" alt="image" src="https://user-images.githubusercontent.com/9964757/221415376-41341cd3-6569-408e-ae6f-560da0e2d255.png">

I have a plan for tracking navigation in which you must "stay" on a page for a prescribed amount of time (settings?) before it shows the heading list and adds it to the History list.

The history list is a restricted count of pages (settings?), that keeps track of the most recent n pages visited.

You can "pin" any page in the history list. "Pinned" is a more generic term than "Reading List". The user can decide what it means for them or for different use cases.

[ICO] is a placeholder for the notebook icon containing the page. Or maybe the second icon. This would let you kind of identify page context, but there would be a tooltip to show you its full notebook/section location as well.

Thoughts?

**Comment by stevencohn** [comment]
Prototype

<img width="266" alt="image" src="https://user-images.githubusercontent.com/9964757/222320689-49c2a03e-efbd-48e9-bde8-63ecde71d99b.png">

**Comment by jasonjac2** [comment]
Sorry for radio silence, I read the ticket on my phone, then forgot about it.  That looks great.  I will use that a lot!

Do you think you might combine it with Favourites or have it standalone?


How will you manage revisits of pages, i.e. remove the older instance from the history?

Super bonus for:
-  filterable 
- the ability to remove entries from the history rather
-  Save as HTML
- Copy Link
- Copy ALL links
- Hotkey to restore and minimize.

**Comment by stevencohn** [comment]
For now, the Pinned concept is intentionally separate from Favorites. I realize that means there are two very similar mechanisms to do almost the same thing but want to see how this pans out.

The History list is of limited length, a rolling queue, where the most recently page is always at the top. If you navigate naturally then the new page is inserted at the top and the last one is deleted, if the list is at the max. If you click an item in the list, the page is displayed but the list remains the same. Note that each item has its own tooltip that shows the last time the page was viewed

Filtering - debating why? The list is limited (settings) between 5 and 100 for performance reasons.
Remove - considering a _clear_ button to clear the history. Note the X on the Pinned row removes selected pinned items
Save as HTML - save what? Why?
Copy link - same as Copy link to Page, so why?
Copy all links - why?
Hotkey - already bound to Shift+Alt+N to open/focus the window

**Comment by jasonjac2** [comment]
Hi, a more speedy reply now.

... if you visit (rather than click) as page that is in the history list, I assume it stays in the same location?
Logically I think it moves to the top, but that may also be confusing, so I think leave it to however it works now.
Filtering: for >10 <100 a filter still has merits I think.  Currently, due to laziness, my favourites has about 10 items and still I filter. It just means Alt+F wee (gives me 2 hits an so I know down and enter gets the 2nd hit and I know what that is without looking).
Save As: 
1) I love the fact that the fav's are persisted in a way I can tinker with
2) I switch from project to project or get to a point in research, have some tabs I have been looking at, want to "stash" the MRU for later.
Copy Link: same as copy link to page - yep, see above, cherry pick 5+ links to paste to a "these are the ones I care about", saves clicking through them, then doing the copy link to page....  
Copy All: similar to save and copy link.  Grab all the links, paste them on a page, cut the ones that I don't care about, left with the list I do want to do something with. 
Compare with my Chrome, I google, ctrl click a few, read and close ones I don't care about, leaves me with a bunch of tabs I want to save for later.
Hotkey - great.  Does it have a minimize (favs doesn't, but it has a different use case, Nav would be open all the time and probably "keep on top" using PowerToys.

Thanks again - your a :star:

**Comment by jasonjac2** [comment]
drag to reorder for both pinned and history would be great.
Do you see the history persisting between sessions?
Save / Copy - I really wish the calendar allows selection and copy links.

**Comment by stevencohn** [comment]
Reorder of history doesn't make sense to me at all. (It just becomes Pinned in that case, doesn't it?) There are many apps like Photoshop that maintain history panels and they're all stacks/queues and can't be reordered because you can't change history!

First implementation, history is a single list, persisted between sessions, as is the Pinned list of course.

The window does it's best to be top-most

**Comment by jasonjac2** [comment]
history, you are right about re-ordering, but MRU's do jump up they are reopened, so there is some merit in moving a page to the top when it is revisited or re-gains focus.

Thanks I look forward to using.

**Comment by stevencohn** [comment]
@jasonjac2 https://github.com/stevencohn/OneMore/releases/tag/5.8.0

**Comment by stevencohn** [comment]
This one looks much better, https://github.com/stevencohn/OneMore/releases/tag/5.8.1

**Comment by jasonjac2** [comment]
Hi Steven, this is amazing, thank you.   I am not sure where the right place for pre-release feedback is, so I'll put it here.

Initial (from 10 mins) - looks great, I can see it tries to stay on top.  Interaction with OneNotes Find (ctrl+f) and global find (ctrl+e) works well (i.e. those popouts are over the top of the navigator while ON page remains behind0.

## Clipping of font in lists

![image](https://user-images.githubusercontent.com/68282090/223041949-c681b014-ffd5-46f4-adee-86822d718d6e.png)

## Extra Gap at position 0

Not sure if intentional, obviously takes up some space, but it does allow me to give focus to the list without clicking through to the page. 
![image](https://user-images.githubusercontent.com/68282090/223042079-68005160-b8ae-4ac1-b249-6a361bb96c96.png)

## Misc

- Ideally a way of giving focus to each of the 3 areas (ctrl + or click on purple space), then you can use keyboard.
- Splitter to change the 3 sections size, e.g. Make one of the sections larger
- Collapse & expand button when you want to focus on one of them
- Love the JSON data file - why JSON vs XML?
- Would love a tooltip to show the page path - you store it in the .JSON
- Copy to be able to include path - like copy Link to Page

Thank you so much for this, I will use it in anger today.

**Comment by jasonjac2** [comment]
5.8.1 - if the navigator is visible, but doesn't have focus, the hotkey doesn't do anything, so if you want to minimize it before going to another application, then you have to use the mouse.  

I'm not sure how to deal with it, but I guess I would think that hitting escape when the dialogue has focus would either close or minimize it and the hotkey would bring up the dialogue and give it focus

**Comment by jasonjac2** [comment]
The actual nav window stays on top of other applications when they have focus, which is a pain.   Thinking about how to make it more useful, maybe it would be better to have a hotkey to open / bring to front / give focus and the same to hide it if it has focus.  

Also a click on an item = open that page / goto that place & give that place focus (as it does now) and maybe a ctrl+click or a double click to do the same, but minimize the nav window.

Again, I'll use it all day and see how what works best.

**Comment by jasonjac2** [comment]
I have moved the nav window on the taskbar and use WIndows+num to minimize and restore it and that works pretty well, so a global hotkey would be great.

**Comment by jasonjac2** [comment]
On the "current page headings", the text is truncated too short, if truncated can they have ... at the end to denote truncation and also have a tooltip to show the whole heading.  

Are you happy to have this "as I go" or would you prefer me to compile a list?

**Comment by jasonjac2** [comment]
History page name doesn't change when page title changes.  I don't think this is critical at all until you re-visit the page.
Use Case - I created a page and it didn't have a title. 1st word on page = Critical.
later set title to: JAC Testing Linked Notes
History entry keeps the "Critical" title, even when I revisit the page.
Solution: when you revisit a page - check title OR allow refresh or check periodically.

**Comment by stevencohn** [comment]
Good feedback, cheers. Here it goes...

* _Gap above pinned and history_ - yes, this is because it's using a single column ListView and that's the header of the column; I'm developing a better control for this. So just ignore it for now. OK
* You discovered that clicking on any of the three areas gives it focus. OK
* Shift+Alt+N attempts to refocus the window but you're right, if it's already in a Normal state then it doesn't regain focus. NOK
* The thick dark purple line above the headers are splitters, you should be able to drag them. Next release will persist their ratios. OK
* Collapse and expand. Maybe... OK
* _JSON_ - since there could be many entries, JSON performs better and is smaller. Up to this point, all the files have been XML because that's the language of the OneNote Interop API so just keeping it consistent rather than json-for-json's take (nothing against "Jasons")
* _Include the path_ - you discovered the tooltips OK
* _Copy the path_ - already done. When you paste, it will paste a link with the title of the pages. But if you paste-as-text, it will paste the links. They're internal onenote:// links so probably unhelpful but there you go OK
* _Always on top_ - this is how this feature works in Windows. I'm not doing anything special here OK
* _Use hotkey instead of always-on-top_ - perhaps... OK
* _Restore when minimized_ - Shift+Alt+N should restore it OK
* _Flicker_ - agreed, NOK
* _Title update_ - agreed, NOK
* _Heading truncated_ - agreed, NOK

Thanks!

**Comment by jasonjac2** [comment]
When you have an empty line with a title font, you filter it out the blank entry from the list.  I like that Pane tool shows it as a blank line in the heading nav - it makes me go back and fix them. .... click link - Alt+shift+N. Makes for good page hygene.

Any idea about the clipping font?

**Comment by stevencohn** [comment]
> Any idea about the clipping font?

Investigating. Different screen DPI resolutions are, er uh, challenging

**Comment by jasonjac2** [comment]
Headers - can it include H3? I use H1 = Main heading, H2 = Dates, H3 = work done on that date.  Maybe a nice later as a persistent option on the dialogue.

High & multi DPI - oh yes, nearly crippled Delphi Development and taken them man years to try and fix in the IDE and compiled apps. Something about MS API being a bit Meh.

**Comment by stevencohn** [comment]
Is not showing headings of type H3? Or do you mean use the heading fonts in the pane itself?

It should show all heading levels like

<img width="214" alt="image" src="https://user-images.githubusercontent.com/9964757/223163891-61a981d9-3ecc-43b3-9e65-cc4e832c39f1.png">

**Comment by stevencohn** [comment]
That's probably the problem with clipping. I try for Segoe UI but it's probably not on your system so it's downgrading to Microsoft Sans Serif. It's an easy fix to measure the actual font used and adjust item heights accordingly.

Thanks for your beta testing by the way!

**Comment by jasonjac2** [comment]
This is from ON, so ON things it has Segue UI.
![image](https://user-images.githubusercontent.com/68282090/223168615-9ce9c072-f916-4975-a20c-7dc4792f68d1.png)

Display1: 
![image](https://user-images.githubusercontent.com/68282090/223169166-968f8ed8-1fea-4aa7-847c-7a8231114dbf.png)

Display 2: 
![image](https://user-images.githubusercontent.com/68282090/223169268-17b42de2-a74d-40ca-af9e-77d26cda8887.png)

History: ON fonts look jaggy on Display2.  Lovely on Display 1.  The navigator has the same clipping on both displays.

**Comment by stevencohn** [comment]
I've added 5.8.1b release builds here https://github.com/stevencohn/OneMore/releases/tag/5.8.1 if you have a chance.

**Comment by jasonjac2** [comment]
Looks great.  Off to bed now, but will use all day again tomorrow.  Immediately I can see: no flicker; no clipping, longer titles in top. 
When I installed it said: 
![image](https://user-images.githubusercontent.com/68282090/223230620-8972b661-9f7d-45c2-8fb0-4961bbd2bb7d.png)

So I had to manually uninstall 5.8.1, but I am guessing that is a pre-build thing.

**Comment by stevencohn** [comment]
Oh yeah, sorry about that. I didn't actually change the product version, just renamed the file! Should have warned you.

**Comment by jasonjac2** [comment]
All seems great.  I would still prefer that when the Navigator has focus and you press the hotkey again, it minimizes it and / or have a global hotkey.  I think I mentioned above I moved the Navigator taskbar icon to poistion 2 and then use WIndows +2 regardless of whether ON has focus to ..... minimize or restore and give focus to the Navigator.  It means when I alt+tab away from OneNote and the Nav is in my way, I don't have to use the mouse.

**Comment by stevencohn** [comment]
Win+DownArrow is the standard Windows keyboard shortcut to minimize a window. https://superuser.com/questions/988554/direct-shortcut-for-windows-maximize-minimize-restore-window
