### ISSUE TITLE
Multiple pages shown at one time?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [stevencohn/OneMore#796]
I'm brand new to OneMore, wanting to completely replace OneNote Gem with it.

I was wondering if there is a way to "split" the OneNote window to show 2 pages side by side vertically, and also if wanting to , split it into 3's and 4's to show 3 or 4 pages at a time, respectively?

I know I could open 2+ full OneNote windows and align them on the desktop to mimic that behavior, but I would really like to be able to split the single OneNote window?

**Comment by stevencohn** [comment]
No, there is no plan to do this

**Comment by YouveGotMeowxy** [comment]
Just wondering, is it even _possible_ to do this with an addin?

**Comment by stevencohn** [comment]
This sounds familiar and I seem to recall another add-in that attempted to do this but syncing a PDF with notes kept on a OneNote page. It was klunky at best. (I think I last looked over a year ago.) But that might be the closest I've heard to this.

OneNote doesn't have a split window capability so no, there is no API available to add-ins to do this either.

**Comment by julie777** [comment]
You can always open another OneNote window and use Windows window positioning commands to put them side by side.
