### ISSUE TITLE
Shrink space between background images after resizing

### ISSUE THREAD

**Issue by RandomCS50** [stevencohn/OneMore#803]
**Is your feature request related to a problem? Please describe.**
When trying to resize a group of images (e.g. powerpoint slides printed to One Note to take notes next to them) the space previously occupied by the images is left blank. The slides are not moved up to take up this space and white space is left. 

**Describe the solution you'd like**
Ideally, the images are resized and moved up to take up the white space. Perhaps this could be added as a toggle in case someone would rather this does not occur?

**Describe alternatives you've considered**
It is possible to cut all of the images into a text box and resize them there. This seems to prevent the issue and there is no white space. However, adding new text boxes next to the large one containing all of the images can be annoying at times as One Note sometimes thinks you are trying to interact with the large text box. 

**Additional context**
-

Thanks for having a look!

**Comment by stevencohn** [comment]
_Note to self_ - when printing from PPT to OneNote, images are placed on the page background, not in an Outline. The current resize command purposely do not change the position of background images. Will need to detect if background images are selected and, if so, present the user with an option to reposition them.
