### ISSUE TITLE
Table style goes kablooey after sorting a column

### ISSUE THREAD

**Issue by YouveGotMeowxy** [stevencohn/OneMore#805]
**Describe the bug**

I created a 2 column table: left column has all text (labels), right column has mac addresses.

I used the Style feature to give alternating colors (in my case light blue/darker blue.

I then right click in a cell and choose to either sort ascending or descending (it happens with either).

The result after sorting shows the style showing the alternating colors all over the place.

**To Reproduce**

Shown above.

**Expected behavior**

After sorting, the alternating line colors show as expected.

**Environment (if applicable):**
 - OneNote Version: [e.g. Office 2019, O365, also 32bit or 64bit?]                latest version as of today (12/15/2022)
 - OneMore Version [e.g. 3.4 - from the About dialog or from the log file]  latest version as of today (12/15/2022)

Let me know if any additional info is needed or helpful. :)

**Comment by stevencohn** [comment]
Unfortunately, this is not something that can be fixed. It would require that the table style be reapplied based on an event fired from the sorting action and there is no such event. 

The workaround is simply to reapply the style to the table or don't apply the style until after you've sorted the contents.

**Comment by YouveGotMeowxy** [comment]
Ok, it's not a huge deal, it just seems like odd behavior, so I thought I'd point it out in case no one was already aware. :)
