### ISSUE TITLE
Link References to Page Feature Request

### ISSUE THREAD

**Issue by kjdevelopers** [stevencohn/OneMore#806]
**Is your feature request related to a problem? Please describe.**
The functionality works well, but can we possibly change the "synopsis" to be focussed on the term being linked?

**Describe the solution you'd like**
I would love the option to have the sentence of the linked term be used instead of the first set of characters of the page.  When linking from a daily note, for instance, the synopisis isn't descriptive and not using it only links to the date of the daily note.

**Describe alternatives you've considered**
Another option, instead of the containing sentence of the linked term would be to include 50 characters before and 50 characters after the linked term.  That way, appearance is maintained.

This change would bring OneNote to the level of other note taking tools linking functionality found in products such as AmpleNote, Logseq, Craft.do, etc.

Thanks again for such a great toolset to truly bring OneNote to another level!
-Dave

**Comment by stevencohn** [comment]
This is a good idea and agree it gives better context. The alternate was chosen due to the fact that identifying a proper sentence is a surprisingly complicated problem when considering how to differentiate the end of a sentence from decimals like 4.5, and particularly names like Mr. John Q. Public... and to do that for different languages with different encodings.

**Comment by kjdevelopers** [comment]
I can completely see how difficult that could be. Would pulling a set amount of characters before and after be doable?  That would at least give some context to what was found. 

Again, it is so useful today and does a lot. I just really run into an issue when most of my linking is from a daily journal with many different types of information on one page.

**Comment by stevencohn** [comment]
Yes, that's what I meant by the "alternative was chosen". It will pull chars before and after. This is what will be available in the next release.
