### ISSUE TITLE
Check and Remove Broken Hyperlinks between OneNote Pages

### ISSUE THREAD

**Issue by DrMcGamer** [stevencohn/OneMore#808]
Hi,

I used the 'Link References to this Page' option on a page I no longer wish to maintain; however, I am unsure how to reverse all the newly created links to this page. In other words, I would like for all the words throughout my notebook which matched the page title to have their links removed.

So, considering the above, is it possible to 'undo' the changes made by 'Link References to this Page'?

Thanks in advance for any help you can provide.

**Comment by stevencohn** [comment]
Perhaps a more general "Remove broken links"

**Comment by DrMcGamer** [comment]
Thanks for your speedy reply @stevencohn.

Yes, I think that would not only solve the issue I described above quite nicely, but it would also be a useful feature of its own.

Is this something which is already available, or are there plans to implement this in a future release?

**Comment by stevencohn** [comment]
I'll target it for the next release.

**Comment by DrMcGamer** [comment]
Brilliant, thank you so much!

Oh, and I'm not sure if I should create a separate thread for this, but I thought I should mention an issue related to links:
- The automatic links, which are created from 'Link References to this Page', risk overwriting any previous links; is there any option/warning which would allow users to avoid this?

**Comment by stevencohn** [comment]
I'll investigate and get back to you

**Comment by seaspeak** [comment]
I have several questions about "Link References to this page" too.

## How to update the linking page titles if they were changed?
After creating the Linked References, I might change the page titles referencing to this page. But Refresh doesn't update their titles in the Linked References.

## How to delete or recreate the Linked References?
This might be a related question. Following the first question, 
1. If I try to delete an item or the whole list below "Linked References *[Refresh]*", Refresh won't generate the whole list?
2. If I delete the whole Linked Reference, "Link References to this page" generate nothing anymore.

**Comment by DrMcGamer** [comment]
Hi @stevencohn, 

Just wondered if there was any news regarding the planned update above? 

'Link References to this Page' is a great feature, but it would be so much more useful with the ability to remove, and/or identify, dead-links. 

Appreciate all the work you do on this btw - it has made working with OneNote on my PhD that bit less stressful.

Thanks

**Comment by stevencohn** [comment]
Sorry I haven't gotten to this yet. But I'm keeping it open and will hopefully get to it soon. Thanks for your interest

**Comment by DrMcGamer** [comment]
No worries at all, it's good to know that it's still in the pipeline.

I'll keep my fingers crossed that it'll be available sometime soon.

Thanks again.

**Comment by stevencohn** [comment]
Implemented by #1046
