### ISSUE TITLE
some icons of button dissapreared after window resotre

### ISSUE THREAD

**Issue by zhangzikai** [stevencohn/OneMore#809]
**Describe the bug**
some icons of button dissapreared after window resotre from system tray.the bug doesn't appear always. maybe the first few times you click the onenote in system tray.

**To Reproduce**
1.click onenote's close button to minize it to system tray
2.left click onenote in system tray to open quick notes(if right click onenote and click the "open onenote" menu item ,icons appeared normallly)
3.click the only button to toggle to normal view ,some icons just disappeared like the picture below
4. press ctrl+f1 (toggle the ribbon area ) twice ,the icons appeared 

**Expected behavior**
icons disappeared normallly

**Screenshots**
![Snipaste_2022-12-23_22-29-24](https://user-images.githubusercontent.com/18569635/209425374-e89c68f7-c08f-4f1e-8b13-c5491aa808d9.png)

**Environment (if applicable):**
 - OneNote Version: Microsoft® OneNote® 适用于 Microsoft 365MSO (版本 2212 Build 16.0.15928.20002) 64 位
 - OneMore Version 5.4.2
**Additional context**

2800:1] Starting dllhost 2800, CPU=2601Mhz, zh-CN/zh-CN, v5.4.2, OneNote 15.0, Office 16.0
2800:1] ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.15928.20098)
2800:1] ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
2800:1] ..OneAddInsUpdate(custom[])
2800:1] ..building ribbon
2800:1] ..building ribbon colorizer commands
2800:1] ..building ribbon language proofing commands
2800:1] ..OnStartupComplete(custom[])
2800:1] ..starting command service
2800:1] ..starting reminder service
2800:1] ..ready
2800:5] defining 142 hotkeys for input locale 2052
2800:1] OnBeginShutdown(custom[])
2800:1] ..shutting down UI
2800:1] ..OnDisconnection(RemoveMode:ext_dm_HostShutdown,custom:[])
2800:1] ..disposing 5 streams
2800:1] ..closing log
the log doesn't show any exception.

Thanks .

**Comment by stevencohn** [comment]
I saw it once but now am unable to reproduce it again. Seems to be a timing issue in the way OneNote invokes its callbacks to add-ins. I may need to file a support ticket to Microsoft.

It's low impact and Ctrl-F1 as you mentioned or clicking another ribbon tab and then clicking the Home tab again will force-load the icons.
