### ISSUE TITLE
Issue in "Table/Recalculate Formula" when page contains multiple tables

### ISSUE THREAD

**Issue by kenclark75** [stevencohn/OneMore#812]
I recently began using OneMore and find it extremely useful.
I have observed some unexpected behaviour in "Table/Recalculate Formula" which I believe may be a bug.

1. If a OneNote page contains only a single, small table, the formula recalculates accurately and rapidly.
2. If a OneNote page contains multiple tables, the formula in the selected table recalculates accurately but the process takes much longer.  It appears that all the tables are recalculated although only the selected table is updated.

My specific application is as follows:

I record my daily expenditure on food using a simple table with 5 rows for individual meals and snacks.
I use the "sum" function to calculate my daily total.

If the OneNote page contains only a single instance of this table, the formula recalculates almost instantly.
However, if I add separate copies of the table for each day of the month, the recalculation time increases to about 6 seconds.
Only the selected table is updated.

I created a new page and inserted a single, large table covering the whole of the month.
This still has functions to calculate the total spent on each individual day.
This also has a recalculation time of about 6 seconds but all calculations are now updated.

My own example is rather trivial but this might have greater impact on others if they perform more complex calculations.

**Comment by stevencohn** [comment]
Can you show an example? The majority of time with all OneMore Interop API flows is consumed by saving the page back to OneNote, not by the actual command logic. For example, given a page with 30 five-row tables, each with one formula, recalculation takes about 0.18s while saving the page takes approximately 1.2s. So based on the size and complexity of the page itself, it just may be the save operation that is expensive and there's little OneMore can do about that since the "save" is a single atomic Interop API call back to OneNote.

**Comment by kenclark75** [comment]
Thanks for the very prompt response.

I have attached my custom OneNote page templates file.
This contains 4 page templates which should illustrate the issue.

Day_1-Formula - This contains a single one-day table.
                             It recalculates instantly.

Month_31-Tables - This contains 31 copies of the above table.
                               It recalculates a single table in 5 seconds

Month_1-Formula - This is the same as the previous page except that I have
deleted all formulas except the first.
                               It takes 3 seconds to recalculate

Month_1-Table - This contains a single table covering the whole month.
                            It recalculates all tables in 6 seconds.

The times quoted are rough estimates.

I am running Windows 11 22H2 with all the latest updates
OneNote is "Microsoft® OneNote® for Microsoft 365 MSO (Version 2211 Build
16.0.15831.20098) 64-bit"
Processor Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz   2.90 GHz
Installed RAM 16.0 GB
Disk: Western Digital Blue SN570 500GB NVMe SSD

Regards, Ken Clark

**Comment by stevencohn** [comment]
After some extensive testing, I've isolated the slowness on the OneNote side, specifically, saving the page back to OneNote. 

1. I created a page with 12 large monthly calendars, created with the OneMore Calendar command, the size of the page is almost 1.2MB of XML.
2. I then added seven formulas to the bottom of each month, one for each day using sum() and average()
3. After making any changes to the input values and pressing Shift+F5 to recalculate formula values, results in:
   a. Formula recalculation completes in an average of 0.6 seconds
   b. Saving the page via the OneNote Interop layer takes on average 6.1 seconds

The only thing that theoretically could be done to improve this performance is to ensure that each table is in its own Outline. The Outline container is the smaller possible unit that OneMore can save independently. If the page contains only one Outline then it must resave the entire page.

**Comment by kenclark75** [comment]
Thank you for taking the time to investigate this issue.

I tried separating each individual table into its own outline.
This does, as you suggest, considerably improve the calculation time.
The only downside is that only the formula in the selected table is now
recalculated.
(Previously all formulae in all tables were recalculated.)

I shall probably stick with my original configuration. The 6 second
calculation time is only a very minor inconvenience.

Regards, Ken Clark
