### ISSUE TITLE
Enhancement to Favorites / Favourites - filter / fuzzy search

### ISSUE THREAD

**Issue by jasonjac2** [stevencohn/OneMore#813]
**Is your feature request related to a problem? Please describe.**
I use favourites more than any other command & I move favourites between machines. Currently I keep them to a minimum (in terms of # of pages) so that I don't have to scroll. 

This is similar to the Command Pallette feature

**Describe the solution you'd like**
I would like:
- Alias for page Name - 3 people in our team will all have their today page, if I could have an alias GGToday
- fuzzy incremental search - Page Name / Alias
- up and down arrows to move the selector even when the search box has focus

**Describe alternatives you've considered**

**Additional context**

THE FINE PRINT
This is a hobby project that I started for myself. I'm happy to take requests and will promise to consider each one carefully but offer no guarantees that I will ultimately agree to their usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
Do you know about the Alt+F "Choose Favorites" command? Is this ticket intended to be an enhancement of that?

**Comment by jasonjac2** [comment]
Sorry, I always assume everyone is on my page :-).  I was referring to the "Choose Favorites" command.  It is the only way I access fav's now and I use it probably every 3 mins when using oneNote.  If I had incremental fuzzy search I would have more like 100 pages in there.
![image](https://user-images.githubusercontent.com/68282090/210979065-9540fd9f-92b8-4d44-8e2b-7dcb3ef8f664.png)

**Comment by jasonjac2** [comment]
I would also add a shortcut to the top 10 entries (ctrl + 1 to 0 OR 0..9 if you're 0 based :-)).
![image](https://user-images.githubusercontent.com/68282090/210991678-28789cfa-67f7-4db5-86c2-0ae0a0c78a44.png)

**Comment by stevencohn** [comment]
Hi Jason, regarding this comment:

> Alias for page Name - 3 people in our team will all have their today page, if I could have an alias GGToday

Favorites are stored per Windows user in your own appdata folder. Are people on your team using the same workstation and same account? Otherwise, how can you see another person's favorites at all? If you can search on page name and path, would an alias still add value?

**Comment by stevencohn** [comment]
<img width="395" alt="image" src="https://user-images.githubusercontent.com/9964757/218336620-4ebb5ec7-49fe-4a58-8424-fa16a3336442.png">
