### ISSUE TITLE
The bold was removed when I  ‘apply style to page’

### ISSUE THREAD

**Issue by saltwater2233** [stevencohn/OneMore#815]
'custom styles ->apply style to page'
i think the bold should be preserved in the body text like font color.

**Comment by stevencohn** [comment]
All settings of a style are considered as absolute values. So whether bold/italic/underline are checked or not checked are specifically applied to the selected text.

No other Office or similar products have an option to override these choices or have the intelligence behind them to know when to automatically override or not override.
