### ISSUE TITLE
CropImage Runtime Error

### ISSUE THREAD

**Issue by linkbc** [stevencohn/OneMore#816]
Hi there Steve, first of all thanks for OneMore.

I'm attaching 3 clip where You can see the issue.
I'm using OneNote ver 16.0.10393.20026 on Windows 10.
After the runtime error, OneNote itself has to be terminated via taskmanager in order to regain full functionality.

![01](https://user-images.githubusercontent.com/15216831/212111716-6e91a231-8939-4f14-9142-6c3ddf8a0155.png)
![02](https://user-images.githubusercontent.com/15216831/212111718-763ce075-03d6-490e-8625-b24c3dcbb3b5.png)
![03](https://user-images.githubusercontent.com/15216831/212111712-fba94cef-27f2-4f0c-b7e7-9808fc5e3eb7.png)

**Comment by jasonjac2** [comment]
I think Steve will need a bit from the logs.  Log files are found in OneMore | About, there is a link to the log file.  I am not sure which bits he will need but I would:
- Close OneNote
- Rename the log file
- Start OneNote, do the minimum to create the problem
- Take a look at the log file and include anything that you think is relevant here.

**Comment by linkbc** [comment]
Sure Jasonjac2, thanks for the hint: here's the relevant part of the log

`11444:6] defining 142 hotkeys for input locale 1040
11444:5] Running command CropImageCommand
11444:5] Running command CropImageCommand
11444:5] ..schema error [width="334,0"] (System.Xml.Linq.XAttribute)`

**Comment by stevencohn** [comment]
_Note to self_ - EU decimal formatting?

**Comment by linkbc** [comment]
(Yes, Ciao from Italy)
