### ISSUE TITLE
Place cursor automatically when creating textboxes

### ISSUE THREAD

**Issue by tridian-tn** [stevencohn/OneMore#819]
**Is your feature request related to a problem? Please describe.**
The Command Palette is brilliant. However, when working at speed, and creating a text box or a variant such a code box, it's quite frustrating to have to put my hand on the mouse to put the cursor into the box, delete the template text (e.g. "Your code here...") and then type, particularly when having used the Command Palette with a keyboard shortcut.

**Describe the solution you'd like**
When a text box (or variant) is created, the cursor is put inside the box so that typing can start without using the mouse to place the cursor. Then the workflow really just becomes typetypetype...return...return...Ctrl-Shift-P...text...return....typetypetype

**Describe alternatives you've considered**
No alternatives, other than using the mouse to click, select, etc.

**Additional context**

THE FINE PRINT
This is a hobby project that I started for myself. I'm happy to take requests and will promise to consider each one carefully but offer no guarantees that I will ultimately agree to their usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
Actually, if you first select a bit of text and then insert a text box or code box, it will wrap the selected text in the box. If you're starting from nothing, type the start of what you want to capture, even if it's just a single letter, select it, and then run the command.

**Comment by tridian-tn** [comment]
@stevencohn It does, which is great. The only thing there is that focus still isn't in the box. It works if you use the mouse to select the "Text Box" command, but not if you use the Command Palette (at least, not for me)

**Comment by tridian-tn** [comment]
OK, many thanks Steven. In my case, after the text box is inserted with the Command Palette, typing doesn't do anything. Interestingly (to very small values of "interesting"), if I try to Alt-Tab away, but shift-Alt-Tab back before releasing Alt, OneNote gets the proper focus again and the cursor is just before the text box.
