### ISSUE TITLE
Feature request: Get a list of tags used in the current section or in the current page

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#82]
I would like to be able to get a list of tags used in the current page or in the current section
Ideally this should be exported to a page that becomes an index for the current section
I would like to see something like this

Programming Concepts Index    (<> denotes a tag, + denotes a collapsed paragraphs)
<function> ............ 5 (used 5 times)
       link to the first use
       link to the second use
       link to the third use 
        etc
        etc
<object> ............ 3 
       link to the first use
       link to the second use
       link to the third use 
+<etc>
+<etc>                                       

This could be named Tag Indexing or Tag Index (to avoid confusion with an Article or Section Index which would be just another feature request :-)) )

**Comment by stevencohn** [comment]
Other than exporting the search results as a new index page, is this much different than the built-in Find Tags command?

**Comment by 1001QAdotNET** [comment]
in the light of the things you explained me about how OneNote use tags it is probably not
See my comments in the other request for an alternative implementation for tags
Any variation of that idea will do as long as it is customizable and searchable

**Comment by stevencohn** [comment]
See #81
