### ISSUE TITLE
OneMore - Hybrid-Analysis (Virus Scanning, Thread Detection) Report

### ISSUE THREAD

**Issue by squirrelboot** [stevencohn/OneMore#822]
Hello!

I tend to be cautious about installing things to systems, and the system gives plenty of warnings regarding the 
**OneMore_5.4.3_Setupx64.msi** file.

![image](https://user-images.githubusercontent.com/7473583/213418990-747fe8b5-65af-4813-a07f-f05adec571fd.png)

VirusTotal [seems to be OK](https://www.virustotal.com/gui/file/43f8e000adef214a37e9f378ce4772bcdbfb4dc1d2763fa0b1caa08d7a8845a2/detection/f-43f8e000adef214a37e9f378ce4772bcdbfb4dc1d2763fa0b1caa08d7a8845a2-1674044402) with it. 

But I ran it through some obstacle course testing, and wanted to share the results with you here:
* [Initial Overview](https://www.hybrid-analysis.com/sample/43f8e000adef214a37e9f378ce4772bcdbfb4dc1d2763fa0b1caa08d7a8845a2) was flagged as Malicious.
* The in-depth analysis [is here](https://www.hybrid-analysis.com/sample/43f8e000adef214a37e9f378ce4772bcdbfb4dc1d2763fa0b1caa08d7a8845a2/63c7e41c6d29db580a65d657). 

I wondered if you had any kind of insight or feedback about this.

**Comment by stevencohn** [comment]
I admit I haven't run it through these tool. Good to know and I'll take a closer look.

The entire source code is in this Github repo along with its build.ps1 script. You can certainly build it yourself if you don't want to trust the .msi that I attach to each release.

**Comment by squirrelboot** [comment]
When looking for OneNote tools, it is hard not to miss your tool here on GitHub. 
Consider that, the use of this tool is wide. In some environments, external tools like this are not trusted explicitly. It helps to be vetted, and some review is done at bare minimum. 

From what I see, the biggest flag comes from this:
![image](https://user-images.githubusercontent.com/7473583/213441255-cc412dff-8275-469d-889c-96a661cf8927.png)
Even, VirusTotal has [one hit](https://www.virustotal.com/gui/file/f0db1955ea4a27f7afebbe2d44c8e6e94dfac325f1b369777e5d33226be360e9/details) on it, though that doesn't say much. 

One thing I did notice too was that:
* DNS Requests: No relevant DNS requests were made.
* Contacted Hosts: No relevant hosts were contacted.
* HTTP Traffic: No relevant HTTP requests were made.

Can you confirm your tool doesn't do any of the following?: 
Collect, report, analyze, share, or exfiltrate any information on contents of our OneNote?.

**Comment by stevencohn** [comment]
Absolutely! There is no callback to the mother ship, no telemetry captured, nothing.

I wish it indicated which entry point it doesn't like in OneMoreSetupActions.exe. This executable is invoked by the MSI to register OneMore in the Registry and to install the MSEdgeWebView component used for rendering and parsing HTML content - just as a content editor tool to convert between various file formats before storing in OneNote.

**Comment by squirrelboot** [comment]
Out of curiosity.. Do you sign with any [code signing certificates](https://codesigningstore.com/)? 
It's like 70$/yr. Something to consider.

I was reading about how it works with GitHub for example:
* [Reference 1 - https://tauri.app/v1/guides/distribution/sign-windows/](https://tauri.app/v1/guides/distribution/sign-windows)
* [Reference 2 - https://federicoterzi.com/blog/automatic-codesigning-on-windows-using-github-actions](https://federicoterzi.com/blog/automatic-codesigning-on-windows-using-github-actions/)
* [Reference 3 -https://codesigningstore.com/how-to-sign-an-exe-or-application-in-5-steps ](https://codesigningstore.com/how-to-sign-an-exe-or-application-in-5-steps)

**Comment by squirrelboot** [comment]
Ah, regarding OneMoreSetupActions.exe
https://www.virustotal.com/gui/file/f0db1955ea4a27f7afebbe2d44c8e6e94dfac325f1b369777e5d33226be360e9/behavior
Does that have more info which helps?

Lastly, I threw it by itself [into the arena](https://www.hybrid-analysis.com/sample/f0db1955ea4a27f7afebbe2d44c8e6e94dfac325f1b369777e5d33226be360e9).

**Comment by stevencohn** [comment]
No, I don't employ code signing. This is a free add-in, what I always refer to as a "hobby project" and don't receive much in donations. So this is an expense that I don't see as critical to support OneMore, at least for now.
