### ISSUE TITLE
Feature request: Select all the text with Similar Formatting

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#83]
I am currently using this in Word (paste the text in Word do the processing there and then move it to OneNote
With this you can change the format for everything with a specific format in your text or you can delete it
This is a very useful feature and it would be nive to have in OneNote

**Comment by stevencohn** [comment]
Have a working solution. One interesting thing to note however, OneNote does not allow multiple non-contiguous selection ranges within a single paragraph. This will result in selecting only the last range in the paragraph that meets the style criteria. Seems there's nothing I can do about that. You can emulate it by trying to select multiple non-contiguous words in a paragraph just using ctrl-click; it won't let you :-(

**Comment by 1001QAdotNET** [comment]
I guess a solution could be using an in memory copy of the doc and applying all the subsequent changes (mostly formatting and clean up ) to that
But that will change the approach for other features I guess

**Comment by stevencohn** [comment]
The good news is that you can apply any number of actions on those selections once made. It's only limited to style changes. I'll release it soon and peeps can see what they think

**Comment by 1001QAdotNET** [comment]
Thanks a lot for this one. I will test it soon I have no access to my environment till next week
