### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by julie777** [stevencohn/OneMore#835]
**Describe the bug**
When I start OneNote The OneMore dialog opens and asks if I want to update, but update fails.

Also, it would be very helpful if the log file provided the path to the file that is in-use and blocking the update.

**To Reproduce**
1. Open OneNote
2. Dialog appears
     
![image](https://user-images.githubusercontent.com/5090005/213934057-6dd70e8f-71a0-49c5-9113-35ab5eba2f39.png)

4. Select "Update"
5. Error Dialog displayed
     
![image](https://user-images.githubusercontent.com/5090005/213934096-463f1b55-e415-46b1-813e-e065eee8edca.png)

**Expected behavior**
The update should be installed

**Environment (if applicable):**
 - OneNote Version: O365,  64bit
 - OneMore Version 5.4.2

**Additional context**
18824:1] Starting dllhost 18824, CPU=2904Mhz, en-US/en-US, v5.4.2, OneNote 15.0, Office 16.0
18824:1] ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.15928.20216)
18824:1] ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
18824:1] ..OneAddInsUpdate(custom[])
18824:1] ..building ribbon
18824:1] ..building ribbon colorizer commands
18824:1] ..building ribbon groups
18824:1] ..building context menu
18824:1] ..OnStartupComplete(custom[])
18824:1] ..starting command service
18824:1] ..starting reminder service
18824:1] ..ready
18824:5] defining 143 hotkeys for input locale 1033
18824:6] Running command UpdateCommand
18824:9] Error running command UpdateCommand
18824:9] System.ComponentModel.Win32Exception
Message: The process cannot access the file because it is being used by another process
Source: System
StackTrace:    at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at River.OneMoreAddIn.Commands.Tools.Updater.Updater.<Update>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at River.OneMoreAddIn.Commands.UpdateCommand.<Execute>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.CommandFactory.<Run>d__5.MoveNext()
TargetSite: [System] System.Diagnostics.Process::StartWithShellExecuteEx()

**Comment by julie777** [comment]
I just read the note about breaking the installer and the manual update. I'm not sure why you can't fix the new update so it works. 
- One thing that could be done is to put a bold message in the Update Dialog if there is an installer problem. I didn't even read the dialog the first time. I just clicked update.
- Another thing, is you know that the installer is going to fail given the current version of OneMore. Why not just have the installer show a notice about manual update instead of trying to install and failing.

**Comment by julie777** [comment]
I am not sure why the instructions for the release say to uninstall the current version and then install 5.4.4. 
I didn't want to have the uninstall throw away all my ribbon customization, or any OneMore settings so I just closed OneNote and tried the 5.4.4 installer and it worked fine.

**Comment by stevencohn** [comment]
> I just read the note about breaking the installer and the manual update. I'm not sure why you can't fix the new update so it works.
> 
> * One thing that could be done is to put a bold message in the Update Dialog if there is an installer problem. I didn't even read the dialog the first time. I just clicked update.
> * Another thing, is you know that the installer is going to fail given the current version of OneMore. Why not just have the installer show a notice about manual update instead of trying to install and failing.

I obviously can't fix the update in 5.4.3 if you already have it installed. It's 5.4.3 (and 5.4.2) that has the broken code. 

This is what 5.4.4 fixes. I could make an assumption and tell the user to manually update in the dialog box but there may be other reasons why it can't update so checking the log file is OK.

Marking this as fixed by #823
