### ISSUE TITLE
Custom Styles are not applied correctly

### ISSUE THREAD

**Issue by julie777** [stevencohn/OneMore#836]
**Describe the bug**

Setting the style to custom heading 2 for a line also changes the style for lines above and below the current line.

Trying to use the custom Normal style to correct the problem doesn't fix it correctly.
I can't use the built in normal style to fix it because that discards all my lists, and in real use the problem happens on a very large scale across the page.

This has been giving me terrible problems on real OneNote pages.

**To Reproduce**
I created a simple example to make it easy to debug.

Using this text:
    This is normal
    heading 1
    this is normal
    heading 2
    this is normal

1. I typed from the beginning down to heading 1
2. I used `<ctrl><alt><shift>-1` to set the line to heading style
3. I hit enter to move to the next line and then typed the rest of the text, which is in the normal style
4. I clicked at the end of heading 2 to set the cursor position
      
![image](https://user-images.githubusercontent.com/5090005/213935562-d17ed332-3140-47bc-b904-5476573793a9.png)

6. I used the shortcut `<ctrl><alt><shift>-2` to set the style to heading 2
7. the heading 2 line was formatted with heading 2
8. but the line above and below the heading 2 line were formatted as heading 1
    
![image](https://user-images.githubusercontent.com/5090005/213935589-9d991514-c1db-4956-b7a9-ae3e8c26cabe.png)

9. select all the text below "heading 2" and select Normal from the OneMore custom styles
  (On real pages where I get many paragraphs converted to heading 2 I have tried to reformat all the normal text by selecting it and then selecting Normal from the OneMore Style menu)
10. the color is removed, but the text is still the size for heading 2.
    
![image](https://user-images.githubusercontent.com/5090005/213935913-e209b98f-6053-4676-adc3-17e239741296.png)

**Expected behavior**
I expect heading styles to only apply to the current line

**Screenshots**

**Environment (if applicable):**
 - OneNote Version: O365,  64bit
 - OneMore Version 5.4.4
 
This was happening with OneMore 5.4.2 also

**Additional context**

After step 8 xml content

```
<one:Page xmlns:one="http://schemas.microsoft.com/office/onenote/2013/onenote" ID="{98A7C30B-01BF-009E-37C9-488FF7CBA0B9}{1}{E19510377243990698647820110833477717133065441}" name="Test for onemoe" dateTime="2023-01-22T19:09:10.000Z" lastModifiedTime="2023-01-22T19:18:19.000Z" pageLevel="1" isCurrentlyViewed="true" selected="partial" lang="en-US">
  <one:QuickStyleDef index="0" name="PageTitle" fontColor="automatic" highlightColor="automatic" font="Open Sans" fontSize="20.0" spaceBefore="0.0" spaceAfter="0.0" />
  <one:QuickStyleDef index="1" name="p" fontColor="automatic" highlightColor="automatic" font="Open Sans" fontSize="12.0" spaceBefore="0.0" spaceAfter="0.0" />
  <one:QuickStyleDef index="2" name="h1" fontColor="#1E4E79" highlightColor="automatic" font="Calibri" fontSize="16.0" spaceBefore="0.0" spaceAfter="0.0" />
  <one:QuickStyleDef index="3" name="h2" fontColor="#2E75B5" highlightColor="automatic" font="Calibri" fontSize="14.0" spaceBefore="0.0" spaceAfter="0.0" />
  <one:PageSettings RTL="false" color="automatic">
    <one:PageSize>
      <one:Automatic />
    </one:PageSize>
    <one:RuleLines visible="false" />
  </one:PageSettings>
  <one:Title lang="en-US">
    <one:OE alignment="left" quickStyleIndex="0">
      <one:T><![CDATA[Test for onemoe]]></one:T>
    </one:OE>
  </one:Title>
  <one:Outline selected="partial">
    <one:Position x="36.0" y="86.4000015258789" z="0" />
    <one:Size width="183.2262878417969" height="129.5916595458984" />
    <one:OEChildren selected="partial">
      <one:OE alignment="left" quickStyleIndex="1">
        <one:T><![CDATA[This is normal]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="1">
        <one:T><![CDATA[]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="2" style="font-family:Calibri;font-size:18.0pt;color:#14324D">
        <one:T><![CDATA[This is heading 1]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="2">
        <one:T><![CDATA[This should be normal]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="3" selected="partial" style="font-family:Calibri;font-size:16.0pt;color:#276296">
        <one:T><![CDATA[Heading 2]]></one:T>
        <one:T selected="all"><![CDATA[]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="2">
        <one:T><![CDATA[Normal]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="2" style="font-family:'Open Sans';font-size:12.0pt;color:#1E4E79">
        <one:T><![CDATA[]]></one:T>
      </one:OE>
    </one:OEChildren>
  </one:Outline>
</one:Page>
```
After step 10 - trying to apply normal to the wrongly formatted text.

```
<one:Page xmlns:one="http://schemas.microsoft.com/office/onenote/2013/onenote" ID="{98A7C30B-01BF-009E-37C9-488FF7CBA0B9}{1}{E19510377243990698647820110833477717133065441}" name="Test for onemoe" dateTime="2023-01-22T19:09:10.000Z" lastModifiedTime="2023-01-22T19:27:20.000Z" pageLevel="1" isCurrentlyViewed="true" selected="partial" lang="en-US">
  <one:QuickStyleDef index="0" name="PageTitle" fontColor="automatic" highlightColor="automatic" font="Open Sans" fontSize="20.0" spaceBefore="0.0" spaceAfter="0.0" />
  <one:QuickStyleDef index="1" name="p" fontColor="automatic" highlightColor="automatic" font="Open Sans" fontSize="12.0" spaceBefore="0.0" spaceAfter="0.0" />
  <one:QuickStyleDef index="2" name="h1" fontColor="#1E4E79" highlightColor="automatic" font="Calibri" fontSize="16.0" spaceBefore="0.0" spaceAfter="0.0" />
  <one:QuickStyleDef index="3" name="h2" fontColor="#2E75B5" highlightColor="automatic" font="Calibri" fontSize="14.0" spaceBefore="0.0" spaceAfter="0.0" />
  <one:PageSettings RTL="false" color="automatic">
    <one:PageSize>
      <one:Automatic />
    </one:PageSize>
    <one:RuleLines visible="false" />
  </one:PageSettings>
  <one:Title lang="en-US">
    <one:OE alignment="left" quickStyleIndex="0">
      <one:T><![CDATA[Test for onemoe]]></one:T>
    </one:OE>
  </one:Title>
  <one:Outline selected="partial">
    <one:Position x="36.0" y="86.4000015258789" z="0" />
    <one:Size width="183.2262878417969" height="129.5916595458984" />
    <one:OEChildren selected="partial">
      <one:OE alignment="left" quickStyleIndex="1">
        <one:T><![CDATA[This is normal]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="1">
        <one:T><![CDATA[]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="2" style="font-family:Calibri;font-size:18.0pt;color:#14324D">
        <one:T><![CDATA[This is heading 1]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="2">
        <one:T><![CDATA[This should be normal]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="3" style="font-family:Calibri;font-size:16.0pt;color:#276296">
        <one:T><![CDATA[Heading 2]]></one:T>
      </one:OE>
      <one:OE selected="all" alignment="left" quickStyleIndex="2" style="font-family:Calibri;font-size:16.0pt;color:black">
        <one:T selected="all"><![CDATA[Normal]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="2" style="font-family:'Open Sans';font-size:12.0pt;color:#14324D">
        <one:T><![CDATA[]]></one:T>
      </one:OE>
    </one:OEChildren>
  </one:Outline>
</one:Page>
```

For reference my style definitions

![image](https://user-images.githubusercontent.com/5090005/213936288-ae01fa74-aca1-459f-86f8-f87fb2eec26a.png)

![image](https://user-images.githubusercontent.com/5090005/213936300-d74a2660-feb7-448b-9407-9b7c80380fd7.png)

![image](https://user-images.githubusercontent.com/5090005/213936305-23dea42f-ea15-44ee-b4c3-54a9c3ea73a0.png)

**Comment by stevencohn** [comment]
There is something strange going on in the Interop API that I'm not sure I can work around programmatically.

The only solution I can think of is immediately pressing Ctrl+Shift+N to force Normal style on lines following custom headers. Expanding on your example:

1. Typed "Normal text"<Enter>
2. Type "Heading 1" without pressing Enter
3. Press `Ctrl+Alt+Shift+1` to set the line to heading style
4. Press <Enter>
5. Press `Ctrl+Shift+N`
6. Type normal text<Enter>
7. Type normal text and press `Ctrl+Alt+Shift+2` ... at this point only this last line should be stylized.

**Comment by julie777** [comment]
Today I just notice another inconsistency. Sometimes after applying a heading style with OneMore Custom styles when I hit enter to move to another line/paragraph the heading style continues. It should only be applied to the current paragraph as that is how built in styles work.

**Comment by julie777** [comment]
> There is something strange going on in the Interop API that I'm not sure I can work around programmatically.
> 
> The only solution I can think of is immediately pressing `Ctrl+Shift+N` to force Normal style on lines following custom headers. Expanding on your example:
> 
>     1. Typed "Normal text"`Enter`
> 
>     2. Type "Heading 1" and then `Ctrl+Alt+Shift+1` and then `Enter`
> 
>     3. Press `Ctrl+Shift+N` and then type normal text and `Enter`
> 
>     4. Type normal text and `Ctrl+Alt+Shift+2` ... at this point only this last line should be stylized.

You marked this as answered, but your response didn't address the issue when trying to set a custom heading style to a paragraph that the style flows up and down the page to many other paragraphs. Maybe I should have created multiple bugs that were more specific, but I thought it was all part of the same issue.

**Comment by stevencohn** [comment]
This in fact is the same problem, the root of the problem. And yes, my answer is the only answer that is feasible at this time.

With built-in OneNote styles, it knows the follow a heading with a normal paragraph.

OneMore custom headings are based on the built-in OneNote headings, however, OneNote seems to treat them differently and continues the style on the next line. This is why I was suggesting pressing Ctrl+Shift+N to force it back to normal style on the next line.

There are many idiosyncrasies like this in the OneNote add-in integration.

**Comment by julie777** [comment]
I understand now. 

I'm not trying to be a pain, and I don't someone else to do all the work to fix problems for me. I have spent many hours in the last couple days trying to troubleshoot the issue and looking at the XML file after every change I make. 

OneNote seems to have a very complicated set of rules about when break up OE, T and even CDATA into separate items. Sometimes it makes sense and in other instances it does not.

Is there any information in the OneMore repo about this type of information?

**Comment by stevencohn** [comment]
Of course you're not a pain. You have really good feedback!

You hit the nail on the head. I suspect the OneNote team hadn't considered these possibilities when building their binary-to-XML converter. Something is getting lost in the translation. The complexity comes from a vague set of rules on how it applies styles hierarchically from QuickStyles to element styles to CDATA styles. This is something I've grown to "love/hate" over the years of developing OneMore :-) I wish their API was a bit more mature around these things; I suspect it's low on their priority list.

No, there's no information on this specifically. But with #746 (which I hope to release this weekend) I'll revamp the Wiki to provide a bit more help

**Comment by julie777** [comment]
Thanks.
BTW, what does CDATA mean? It uses a different format from the other XML elements, but it includes elements such as <span/>

**Comment by stevencohn** [comment]
CDATA is standard XML syntax, stands for Character Data.

Here's a stackoverlow article https://stackoverflow.com/questions/2784183/what-does-cdata-in-xml-mean

**Comment by julie777** [comment]
> CDATA is standard XML syntax, stands for Character Data.
> 
> Here's a stackoverlow article https://stackoverflow.com/questions/2784183/what-does-cdata-in-xml-mean

The reason I was confused is that OneNote seems to always use CDATA even for plain text, and what it puts in the CDATA appears to be HTML markup of the text.

```
<one:OE alignment="left" quickStyleIndex="1">
        <one:T><![CDATA[This should be normal]]></one:T>
      </one:OE>
      <one:OE alignment="left" spaceBefore="10.0" quickStyleIndex="3">
        <one:T><![CDATA[<span style='font-weight:bold;font-family:Cambria;font-size:13.0pt;color:#4F81BD'>Heading</span><span style='font-family:Calibri;font-size:14.0pt;color:black'> 2</span>]]></one:T>
      </one:OE>
```

In the example above there is no need for CDATA for "This line should be normal".
Then I changed style information for individual words in the paragraph and it puts <span> in the CDATA.

More OneNote craziness.

**Comment by stevencohn** [comment]
Yes that's true, it does always use CDATA for all text. But that actually makes it easier since it's consistent. 

I should have mentioned that the key to CDATA is that is _raw text_ so that special XML characters like greater-than and less-than aren't treated like XML element delimiters. 

OneNote does have a pretty nice way of optimizing and normalizing styles where QuickStyles get overridden by one:OE@style which can get overridden by CDATA embedded span@style. And if you overpopulate styles attributes at one level, OneNote will normalize it to the proper level, which makes it fun because what you send it to save isn't necessarily what it might actually save! OneMore I think does a pretty good job at deciphering all of this. I've learned what to expect. 

Last comment, the schema is published and fully described. I've included it in the OneMore repo [here for reference](https://github.com/stevencohn/OneMore/blob/main/Reference/0336.OneNoteApplication_2013.xsd).

**Comment by julie777** [comment]
> Yes that's true, it does always use CDATA for all text. But that actually makes it easier since it's consistent.
> 
> I should have mentioned that the key to CDATA is that is _raw text_ so that special XML characters like greater-than and less-than aren't treated like XML element delimiters.

I think an easier way to understand it for OneNote is that all text elements are represented as CDATA elements containing HTML formatted text and when formatting changes within a CDATA section that HTML <span> is used to apply the formatting attributes. (Maybe I am saying the same thing in different words.)
> 
> OneNote does have a pretty nice way of optimizing and normalizing styles where QuickStyles get overridden by one:OE@style which can get overridden by CDATA embedded span@style. And if you overpopulate styles attributes at one level, OneNote will normalize it to the proper level, which makes it fun because what you send it to save isn't necessarily what it might actually save! OneMore I think does a pretty good job at deciphering all of this. I've learned what to expect.

I have definitely seen the affects that optimization has when diffing changes.

> 
> Last comment, the schema is published and fully described. I've included it in the OneMore repo [here for reference](https://github.com/stevencohn/OneMore/blob/main/Reference/0336.OneNoteApplication_2013.xsd).

That really helps. 
I have been trying to construct a schema using the XML viewer and https://learn.microsoft.com/en-us/openspecs/office_file_formats/ms-one. You just saved me many hours of work.

I will probably keep trying to determine the set of rules that are used by OneNote to apply styles. 

One related question - if the the cursor is at some spot without a selection, when OneMore applies a quick style does it change the selection and apply the style, or does it just determine the implied scope of the style and apply it to that scope?

Is there any place I can look in the code for this? 

BTW, I still have not managed to build the project. I tried some time ago and installed many versions of Visual Studio and a slew of interops, etc. and could never get it to work. I'll probably try again this weekend.

**Comment by stevencohn** [comment]
Is the cursor is at a spot without a selected range greater than zero, it's still a selection. This can be seen in the XML Viewer as a highlighted one:T
```xml
<one:T selected="all"><![CDATA[]]></one:T>
```

OneMore style modules are in the Styles folder, the commands are in Commands\Styles.

What's your motivation? You have a nifty idea in the works?
