### ISSUE TITLE
Add to "word count" the ability to count for sections and notebooks

### ISSUE THREAD

**Issue by julie777** [stevencohn/OneMore#837]
**Is your feature request related to a problem? Please describe.**

"word count" is under the page sub-menu and it count words on the current page.

**Describe the solution you'd like**

I would like the ability to collect word count at different levels
- page
- section
- notebook
- all notebooks

A popup with the total count like the current "word count" would be a basic solution. Adding a button to the dialog to allow me to save the detailed information to a page (similar to data analysis) would be even better.

**Describe alternatives you've considered**

I could write a Onetastic macro that does exactly what I want. However, I believe that this is likely a feature that many users of OneMore would benefit from.

**Comment by stevencohn** [comment]
Added two commands, available from the Section context menu and the Notebook context menu respectively. Also available in the command palette.

* Total Words in Section
* Total Words in Notebook

Both commands generate a new report page in the current section detailing the word counts per page, total per section, and total per notebook.
