### ISSUE TITLE
Display two pages side by side

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#84]
Probably this is not possible unless you copy everything on the two pages to a third page, with the content of each of the source page in  its own DIV , with the destination divs side by side

**Comment by stevencohn** [comment]
You can open a page in a second OneNote window and then dock those tile those on the Windows desktop side by side. Go to the View ribbon bar and click New Window.

**Comment by 1001QAdotNET** [comment]
yes but that does not give you synchronous scrolling
