### ISSUE TITLE
OneNote for macOS edition please

### ISSUE THREAD

**Issue by omidshojaee** [stevencohn/OneMore#841]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

THE FINE PRINT
This is a hobby project that I started for myself. I'm happy to take requests and will promise to consider each one carefully but offer no guarantees that I will ultimately agree to their usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
Sorry I do not own a mac

**Comment by BH2WFR** [comment]
macos onenote doesn't support extensions.
