### ISSUE TITLE
Reminder errors

### ISSUE THREAD

**Issue by wiwa12** [stevencohn/OneMore#842]
**Describe the bug**
When add a reminder to a task no reminder shows up at the selected date/time
In the log errors for each reminder occure

**To Reproduce**
1. Select a paragraph
2. Reminder --> "Add or update reminder"
3. Select a date/time

**Expected behavior**
A reminder should pop up at the requested date/time

**Real behavior**
Nothing happens and errors in the log occur - see attached log
[OneMore.log](https://github.com/stevencohn/OneMore/files/10487811/OneMore.log)
The "Reminder Summary Report" is empty despite the fact that I created a number of reminder for paragraphs

**Environment (if applicable):**
 - OS Version :
            Edition	Windows 10 Pro (x64)
            Version	22H2
            Installiert am	‎14.‎01.‎2022
            Betriebssystembuild	19045.2486
            Leistung	Windows Feature Experience Pack 120.2212.4190.0

 - OneNote Version: O365, 32bit (Microsoft® OneNote® für Microsoft 365 MSO (Version 2211 Build 16.0.15831.20220) 32 Bit )
 - OneMore Version 5.4.4 (OneMore_5.4.4_Setupx64.msi)

Add any other context about the problem here. Attach page XML file or the app log file as appropriate. You can find the log file here: %localappdata%\temp\OneMore.log

I very much appreciate your work you´re doing on this great addon - thank you !!

**Comment by stevencohn** [comment]
Yep, I broke it in 5.4.3!

For all the C# developers out there, you may be interested to know...

Serialization of Reminders was broken when simplifying `using` statements. This misses the necessary `Flush` and `Close` calls that are done implicity in a `using { }` block, which updates the underlying stream. The result was truncated data stored on the page which could not be de-serialized. So this PR reverts the simplified `using` statement back to a `using { }` block

**Comment by tridian-tn** [comment]
> Yep, I broke it in 5.4.3!
> 
> 
> 
> For all the C# developers out there, you may be interested to know...
> 
> 
> 
> Serialization of Reminders was broken when simplifying `using` statements. This misses the necessary `Flush` and `Close` calls that are done implicity in a `using { }` block, which updates the underlying stream. The result was truncated data stored on the page which could not be de-serialized. So this PR reverts the simplified `using` statement back to a `using { }` block

This isn't good - I've recently refactored some code to use these! Does that mean that the using statements don't reliably dispose the object when the method ends?

**Comment by stevencohn** [comment]
It will reliably dispose the object and perform any other actions that that object's Dispose would normally do.

My problem is that I went from something like this:

```csharp
using (var stream = new StringWriter(memoryStream))
{
   stream.Write();
}
// reading from the string immediately following the using block works just fine!
```

to this

```csharp
using var stream = new StringWriter(memoryStream);
stream.Write();
// reading from the string here in the same block scope returns nothing because the stream hasn't called Flush() yet
```

So my solution was to either revert back to the using block or to explicitly call Flush() before attempting to peek at the stream.

I hope that helps.

**Comment by tridian-tn** [comment]
Understood - I'll be very careful with possible side-effects now. Thanks for taking the time to explain.
