### ISSUE TITLE
Advice on rendering OneNote pages in a browser control from the XML (I intend doign a plug in)

### ISSUE THREAD

**Issue by jasonjac2** [stevencohn/OneMore#843]
**How can I help you?**
I code write in Delphi and don't have a lot of experience presenting HTML.  I have access to the MS Edge embedded browse (WebView2?).  I could do with a hand relating to what I need to do to the XML to make it "pretty" or at least a similar visual representation as shown in the ON page.

My plugin is going to be a filter on a page to support my ever growing list of todo's on a page.  ctrl+f works well, but is a pain when I want to copy / move that item.  I want a view where you type  and get a *word* match on a word and the view shows you the hierarchy / indentation on the page.

e.g.
ToDo

- ToDO1
   - some text
- ToDo2
   - some text that includes Word
-ToDO3
   - some text

When I type Word in the search box the resulting view has

- ToDo2
   - some text that includes Word

And I can click it to go to that part of the page.

TIA JAC

THE FINE PRINT
This is a hobby project that I started for myself. I'm happy to take requests and will promise to consider each one carefully but offer no guarantees that I will ultimately agree to their usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around then I will probably reject the request - you've been warned!

**Comment by jasonjac2** [comment]
Thanks @stevencohn , "If I understand correctly, you have some logic that searches a page for matches and generates some sort of structured XML capturing the results."
That may be the end solution, but initially I am trying to render the ON page outside of ON.  Then I will do the filtering and re-rendering.  
"My first instinct would be to write XSLT to transform the XML into HTML. Most Web controls know how to render XSLT+XML[+CSS]"
Yes, that sounds exactly right, but are there any starter XSLT / CSS.

I realise that this may seem very basic and obvious to most :-).

Cheers,
JAC.

**Comment by stevencohn** [comment]
Doable. But not trivial. There are plenty of online resources for XSLT but one of the challenges will be associating QuickStyles since that would combine information from two elements across the document. I think that's possible but honestly haven't done much XSLT in recent years.

There's also OneMore's Export command that lets you save a page as HTML, but without the automation behind a plugin. This just uses internal OneNote functionality similar to the File/Export/as single-page HTML

**Comment by jasonjac2** [comment]
Thanks @stevencohn.  I wasn't hoping to match too much on the style front, just some kind of sensible representation so that when they hit a key and it filters Outlines & nodes out that you can clearly read what you are seeing and decide which elements you want to click on (to goto).

I'll do some googling and actually look at what is in the XML as I may be able to grab the bits I care about with some pretty basic token and text extraction.

**Comment by stevencohn** [comment]
This looks like a great place to start, if you're heading down the XSLT path... http://taoffi.isosoft.org/post/2018/04/30/onenote-page-xsl-transformation

**Comment by jasonjac2** [comment]
You find some good stuff..... A great starting point and also led me to his ON explorer and a Blog article about the initial idea behind ON.  Thanks.  Some bedtime reading!

**Comment by jasonjac2** [comment]
It is a shame his ON explorer code isn't available. His contact me form doesn't work.  I have run the explorer, it has some really great features and is kind of what I was looking for in one of my other posts about incremental page title search (I also want incremental page content search).

**Comment by stevencohn** [comment]
I just sent you an email. Enjoy

**Comment by stevencohn** [comment]
An alternative, if you're already at the programming level, is to use the OneNote Application object directly and call the Export function to export a specific page to an HTML file. This is how the OneMoreCalendar generates the page thumbnails when you right-click on a page.
