### ISSUE TITLE
Reminders not recognized 

### ISSUE THREAD

**Issue by Cossackx** [stevencohn/OneMore#845]
**Describe the bug**
Summary of reminders does not capture any reminders/to do. Tried using OneMore and organic OneNote methods to set reminder/to do.

![image](https://user-images.githubusercontent.com/121278003/214641659-ccf89451-e87a-4d96-ac93-b33e1052cc8d.png)

![image](https://user-images.githubusercontent.com/121278003/214641766-0272cc56-ec39-4a3f-adb8-942ba2d6d66c.png)

**Comment by Cossackx** [comment]
Using MSFT to tag reminder/to do.... 
![image](https://user-images.githubusercontent.com/121278003/214642145-5d2b642e-b2d2-4713-83b2-e56cb2a9b32b.png)

**Comment by stevencohn** [comment]
Known issue. Duplicate of #842

**Comment by Cossackx** [comment]
You rock! Thanks for the feedback on Reddit too. I would love to bounce some ideas off you. What's the best way to do that for you?

**Comment by stevencohn** [comment]
Send me a message from my Web site and we can start up an email convo... https://stevencohn.net/#contact
