### ISSUE TITLE
2 Bugs  in Import (word) feature

### ISSUE THREAD

**Issue by osman1963** [stevencohn/OneMore#85]
Nothing you can't fix while having your morning coffee I suppose.

Update: just 1 bug, the other seemed to be from my end.

Importing an Arabic word file results in it rendered as a series of squares with few scattered letters.

And of course thanks a million for the great add-in.. Mr. Genious

**Comment by stevencohn** [comment]
I'm glad you figured out the first problem. Regarding the squares, it may be due to a strange collection of fonts in the document or installed in Windows. I cut/pasted some text from the Internet into a Word doc and it seemed to work OK. Sorry I don't know anything about Arabic so I'm not sure.
