### ISSUE TITLE
When applying page style, the color of hyperlink text will also be changed

### ISSUE THREAD

**Issue by zhongguocn** [stevencohn/OneMore#850]
When applying page style, the color of hyperlink text will also be changed. 
I hope to keep the default color of hyperlink text.
Thanks.

**Comment by stevencohn** [comment]
Unfortunately, this is a known problem and cannot be fixed. I have a comment in the code [here](https://github.com/stevencohn/OneMore/blob/main/OneMore/Commands/Styles/ApplyStylesCommand.cs#L268). There is also an online discussion [here](https://answers.microsoft.com/en-us/msoffice/forum/all/change-onenote-hyperlink-color-programmatically/d673f8f8-dcd7-4910-9403-8b45379917a6).
