### ISSUE TITLE
Mermaid or graphviz or similar support

### ISSUE THREAD

**Issue by tridian-tn** [stevencohn/OneMore#852]
**Is your feature request related to a problem? Please describe.**
Diagram creation is very easy in markdown editors that support mermaid rendering. Zim wiki has a similar facility that uses graphviz. OneNote obviously has the facility to draw boxes etc and you can import Visio diagrams (if you own Visio), but it doesn't have the immediacy of creating a simple flowchart using basic text-based syntax. 

**Describe the solution you'd like**

On the assumption (and it is an assumption!) that a renderer can be used from One Note (web based or embedded into the OneMore add on, or an exterior dependency to be installed), it would be fantastic to have the facility to have a source block containing mermaid (or graphviz) code, and a link that regenerates an image of the generated diagram that's inserted below the source block (a bit like the links for TOCs)

**Describe alternatives you've considered**
Buying Visio, or manually drawing and maintaining flowcharts with native OneNote boxes. 

**Additional context**

THE FINE PRINT
This is a hobby project that I started for myself. I'm happy to take requests and will promise to consider each one carefully but offer no guarantees that I will ultimately agree to their usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
Or PlantUML

**Comment by jasonjac2** [comment]
Hi, I'm not familiar with PlanUML, but love the idea of being about to diagram from text to graphic and have tested mermaid in the past.

Just looked up PlantUML - it says you need java installed or is the intend to get the text -> .PNG conversion done in the cloud?

https://plantuml.com/starting

**Comment by stevencohn** [comment]
Hi @jasonjac2. There is a nuget package that works with a remote API by default. So while you'll need to be connected to the internet to use this function, you will not need to install Java or any other dependencies.

**Comment by jasonjac2** [comment]
Excellent, thanks for that.  So it will need a bit of a health warning about a round trip to to a 3rd party, so people don't commit their super secret plans.  Are there any other tools / commands that use 3rd party cloud / API resources?

JAC
