### ISSUE TITLE
Set Defaults for "Images->Resize and Adjust" Command

### ISSUE THREAD

**Issue by JRPX33** [stevencohn/OneMore#857]
I'm Really loving the "Resize and Adjust" Command --- I have a bunch of OneNote notebooks with HUGE images that are making the notebooks unmanageable and I've never seen a command like this on any other add-in.

However, it would be even more awesome if I could change the default settings of the command to be 100% and uncheck "preserve storage size".   I'm finding i have to reset these with each page I resize.

**Comment by stevencohn** [comment]
The default settings are designed to default to no-data-loss.

Currently, this dialog will remember the most-recently-used absolute width but it does not remember the percentage or the state of the preserve checkbox.

I can enhance it to remember all settings. Although, I'm considering whether that should reset when you close OneNote or persist... preferences?

**Comment by JRPX33** [comment]
Excellent point, having destructive defaults could lead to problems.

a  few ideas: 

1) Have a checkbox or button that says "Remember these settings for this session"
2) Have a preference that will allow it to persist through sessions...but have a red highlight in the dialog that says "Image detail will be lost" or something.  That would be my preference, since that's basically ALWAYS what I want.  But this could remind others to turn the feature off if they don't want that.

3) In looking at the latest version (I'm a bit behind because I got caught in the autoupdate thing:-) , I like the Lock next to height/width.   Maybe you could just put a lock next to "preserve storage size" and then any time preserve storage size is unchecked, have text below it warning that image resolution will be lost.

Thanks for looking into this!

**Comment by stevencohn** [comment]
The lock is a Photoshop-thing that maintains the aspect ratio between width and height. Unlock it to change the aspect ratio.

Proposed solution is to somehow highlight controls that affect data loss, probably tooltips. Persist settings. And provide a "Reset defaults" button. Simple.

**Comment by koppor** [comment]
> I can enhance it to remember all settings. 

Yes, please! I always need to change `100` to `50`in the resize box.

Reason: When pasting a picture, it is "always" twice the desired size. That means: The pasted size 

---

Example:

![image](https://github.com/stevencohn/OneMore/assets/1366654/cce4818d-6917-4dce-9d55-8e3d8ed7a02d)

---

> Although, I'm considering whether that should reset when you close OneNote or persist... preferences?

I would like to have it persisted permanently, because I do not change the setting.

What would be nice, is a button "reset to defaults"

![image](https://github.com/stevencohn/OneMore/assets/1366654/8e7a271d-e1e3-48c9-bf64-ce34d671b8da)

**Comment by stevencohn** [comment]
This work was completed in Jan 2023 and has been included for a couple of releases. It saves settings and has a _reset defaults_ button.

FYI, there will be a new release in the next few days so you may want to wait for that! :-)

**Comment by koppor** [comment]
> This work was completed in Jan 2023 and has been included for a couple of releases. It saves settings and has a _reset defaults_ button.

Here, version 5.9.0 does NOT remember the setting for "Percentage" (point 1 in the screenshot), but it has "Reset default values" at the bottom.

![image](https://github.com/stevencohn/OneMore/assets/1366654/c5336219-3fd7-416c-964e-008a6c47d34e)

**Comment by stevencohn** [comment]
Funny story. Looking at the code, it appears to be a bug and everything should have been saved all along! :laughing:
I'll fix it for the next release.
