### ISSUE TITLE
How can I enable the "update" button in the XML viewer tool?

### ISSUE THREAD

**Issue by julie777** [stevencohn/OneMore#868]
**How can I help you?**
When is "update" in the show xml tool enabled/disabled?

I haven't found any way to enabled it.

**Comment by stevencohn** [comment]
You have to disable these two checkboxes

<img width="228" alt="image" src="https://user-images.githubusercontent.com/9964757/216711157-c6914129-caf5-4cc5-a110-896763d2a449.png">

I'll update the wiki
