### ISSUE TITLE
Enhance the XML view tool

### ISSUE THREAD

**Issue by julie777** [stevencohn/OneMore#869]
# Problem

It drives me crazy when dialogs don't remember their positions. I have been constantly opening and closing the XML view while trying to debug a problem, and I have to resize it every time.
In addition, I also end up doing some manual formatting to wrap some of the long lines. When I do this I have to use spaces to indent because the tab key doesn't work.

# Proposed Solution

1. make the XML view a mode-less dialog so that I can leave it open and just refresh it. (Onetastic does this, but it doesn't allow changing text size and it is so small I can't read it. It also doesn't support the features in the OneMore XML view)
2. make the XML view dialog remember its last position and open in the same place and size
3. reduce the minimum width of the XML view. I can change the size from the default but the minimum width is wider than half my screen.
4. provide auto-formatting based on dialog width so that there is not horizontal scrolling required. (can be selectable with a checkbox)
5. provide the option to expand/collapse all XML tags. This is partly implemented for CDATA. For my purposes, which is diffing to see changes, a non-compact, fully expanded view reduces diffs to the bare minimum. 
6. Enable the tab key when the edit/text/content box has focus. Currently I have to use spaces. Auto-indent when inserting a newline would be great. Smart tab when I use the tab key would be good. Just inserting a tab or the number of spaces used for an indent level would be acceptable.

Note: auto-wrap, compact, fully expanded and whatever else one might want to do with formatting should somehow be implemented as a consistent solution.

**Comment by stevencohn** [comment]
Added checkbox to enable/disable saving window position.
Added checkbox to optionally write each attribute on its own line.

**Comment by julie777** [comment]
This doesn't seem to be working. I updated to version 5.6.0 today and the XML dialog doesn't remember its position when reopened. 

Should I resubmit the above items as separate feature requests? 

I lumped them together as part of making the XML viewer better, but I am not sure if you meant to implement some and reject some or just got busy and closed this issue with only some items addressed.

**Comment by stevencohn** [comment]
Did you click this?

<img width="195" alt="image" src="https://user-images.githubusercontent.com/9964757/218343397-87015004-37df-4b14-aa9a-3ac9fd7df5c4.png">

**Comment by stevencohn** [comment]
> Should I resubmit the above items as separate feature requests? I lumped them together as part of making the XML viewer better, but I am not sure if you meant to implement some and reject some or just got busy and closed this issue with only some items addressed.

### My solution
* Added checkbox to enable/disable saving window position.
* Added checkbox to optionally write each attribute on its own line.

This is as far as I'm taking it for now

**Comment by stevencohn** [comment]
@julie777 I just discovered what you mean... it does work. And it doesn't work.

It _will_ save the current window pos and size if you click either Update or Cancel. 
This does not work if you click the window "X" button.

I will fix resolve that. Don't worry about a ticket. I'll just take care of it.

**Comment by stevencohn** [comment]
By the way, you can press Esc to close it and save the pos too. This is what I normally do so I never noticed the "X" problem.
