### ISSUE TITLE
Add the version of the add-in info to the logs and automate collecting the info about OS/Patch level, OneNote version and OneMore version

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#87]
**Is your feature request related to a problem? Please describe.**
It would make the troubleshooting process easier and it will eliminate the back and forth between developer and users if this info is collected automatically (if possible)
In particular to the add-in info I am troubleshooting the 3.5-3.6-3.6.1 issues and I am seeing that the log is still there but I am not clear on what version of the add-in created the log entries ..so as I am going back and forth between these logs to see where the problem is I would like to know what was the version of the addin that created each group of log entries

**Describe the solution you'd like**
Add the version of the add-in info to the logs and automate collecting the info about OS/Patch level, OneNote version and OneMore version

**Describe alternatives you've considered**
N/A
**Additional context**
N?A

**Comment by stevencohn** [comment]
https://github.com/stevencohn/OneMore/releases/tag/3.6.2

**Comment by 1001QAdotNET** [comment]
Yeap...working fine I am now seeing the info there
If you need or want to, you can add the Windows version and build info

**Comment by stevencohn** [comment]
Windows version and build "should" have no effect; OneMore doesn't use any features specific to OS versions. Regardless, I'm not maintaining multiple OS builds so can't test all versions anyway.

**Comment by CLITrees** [comment]
OK then it is fine as is , that is actually good because I won't bother to include the above info in my bug reports anymore

**Comment by 1001QAdotNET** [comment]
OK then it is fine as is , that is actually good because I won't bother to include the above info in my bug reports anymore
