### ISSUE TITLE
Use OneMore to import HTML pages by provinding a link to the page instead of using the clipboard and copy and paste

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#88]
**Is your feature request related to a problem? Please describe.**
Use OneMore to import HTML pages instead of using a the clipboard

**Describe the solution you'd like**
by now we know that transiting the copied text via clipboard and pasting in into OneNote is not really a clean way to do it and formatting is lost even when using the OneMore paste RTF feature
I was wondering if there is an easy way to import HTML pages via OneMore directly by providing it a link to the web page that would be imported 
Then OneMore is in direct control and it can translate HTML to whatever is needed and compliant with the OneNote XML format
the user can clean up and other things later if needed but the most important thing is preserving the original format the sections and the paragraphs and the indentation of the original document

**Describe alternatives you've considered**
please see the previous tickets opened for this matter
**Additional context**
N/A

**Comment by stevencohn** [comment]
Well that's a nice feature regardless but I'm actually considering splitting the Paste RTF command into two - one that does what it does now and an advanced version that uses Word in the background to do the conversion. The reason to keep both is that using Word is slow, delays the action at least a few seconds depending on your machine speed.

But thanks, I'll keep this in mind. if/when I split the Paste RTF command

**Comment by 1001QAdotNET** [comment]
I am glad that you are not rejecting the idea :-)

**Comment by BrianPassante** [comment]
If I understand this Enhancement Request, it addresses a long-standing deficiency in the Android OneNote client that only saves a link to a WebPage or HTML Page the user is sharing or saving to OneNote (unlike the web browser clipper which can capture the entire web page PLUS the URL Link to reference).  So my Notebooks are littered with these LINK and title only pages that are difficult to update if I saved to OneNote using a mobile device.   What I would love is a utility or macro to run through a section and fix all pages that are just a link by dragging in the Full HTML Page.  Or even a Macro to trigger for the one page opened to do the same thing.  POssoible?  Does this enhacement permite a macro to do this?  Or is my idea a separate enhancement?  Thanks

**Comment by stevencohn** [comment]
Brian, your request speaks to the OP request and I think is still valid. This ticket kind of touches upon three features of OneNote

1. Paste RTF - is does this now, needs some tweaking but is pretty functional
2. Import Word and Powerpoint documents - does this now
3. "Expand" a URL on the page to the full content - this is the idea of the original request and something I think is a good idea and want to investigate. I'm thinking of working on it very soon.

Thanks!

**Comment by stevencohn** [comment]
@1001QAdotNET @BrianPassante (or anyone else that can add value here)

I'm working on a solution. It doesn't preserve 100% fidelity with the original Web page because it doesn't attempt to apply linked style sheets but will maintain the basic HTML and most inline styles. 

But I'm looking for a little more guidance on how users will want entry into this.... it could be one or more of the following, or something I haven't considered yet...

- Display a dialog to the user asking for the URL of a Web page and import that as a new OneNote page
   - the URL can be entered but can also be defaulted to the URL in the clipboard if one is present
   - give option to append to current page
   - give option to insert in current page at current cursor location
- Replace URL(s) on a page, retrieving the referenced Web page  (_might be impractical, TBD_)
   - option to replace only selected URL
   - option to replace all URLs on the page
   - option to "expand" all URLs on all pages in the current section

Thoughts? Other options?

**Comment by 1001QAdotNET** [comment]
Yes that (first bullet) is more than I hoped for
Probably using some custom CSS that the user can predefine or a default one could help
in the end it all comes down to set HTLM attributes which can be defaulted to a css file residing on the importing computer
One way to do it is to use a headless browser and get the page after the headless browser calculated the resulting style for each element of the page (so it will be the rendered page) 

Re second bullet -I think it is not practical, just leave the URLs where they are
Images should be retrieved and embedded though

**Comment by stevencohn** [comment]
I considered a headless browser but none really apply the CSS to the HTML elements. And even if they did, OneNote only recognizes and allows a very small subset, so you might get colors and maybe size but probably not much else.

**Comment by 1001QAdotNET** [comment]
Ok do what you can because in the end result is the same (dictated by OneNote) but at least using this type of approach give you more control in the future. As w e both know Copy and Paste is a lottery some times

**Comment by stevencohn** [comment]
I'm not using the copy/paste for this feature. It's really all about the limitation of OneNote. It "sanitizes" all input you give it so sometimes there's no much I can do.

**Comment by stevencohn** [comment]
I found this https://github.com/milkshakesoftware/PreMailer.Net
which is awesome and does exactly what I thought I needed: reading all embedded css link references and inlining the styles on the html elements. Cool!

But OneNote strips it all off anyway :-(

But the import seems to be working well... releasing today
