### ISSUE TITLE
Add before/after and collapse text option for Draw PlantUML command

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#881]
TO visually declutter the doc after the conversion there would be two options
-Indent the text under the picture and the collapse it
-remove the text and add it as alternate text for the newly created picture

These could be options that the user could chose between before the conversion
Also a progress bar seems to be needed while converting more complex graphs

**Comment by stevencohn** [comment]
I like the idea of an option (in Settings) to move the next after the image and into a collapsed paragraph.

Stuffing it in alt-text, that would break the built-in image "Copy text from image" command and I think confuse users, even if it was another option that they could choose. So no on that one.

**Comment by 1001QAdotNET** [comment]
Yes collapsing it makes more sense to me too as it is easily accessible that way

**Comment by 1001QAdotNET** [comment]
Thinking more about it I would say that there will be very practical to be able to edit the DOT code and then refresh the corresponding image. Is there a way to link them (the DOT code and an image that was generated) and then when you edit the code again the plugin should first check if the image was already generated and refresh that one instead or creating it again and the user ending with two images of which the older will need to be deleted manually. Not sure if this is easy to achieve but if it is possible, it would be fantastic.
