### ISSUE TITLE
Is there any features that let all the pictures in the article arrange in Center? (keep all the text arrange in leftside)

### ISSUE THREAD

**Issue by BH2WFR** [stevencohn/OneMore#887]
Is there any features that let all the pictures in the article arrange in Center? (keep all the text arrange in leftside)

======
I use this add-one for an year and it was quite useful and delicate
 thank for all the developers!

**Comment by stevencohn** [comment]
While I initially marked this as a feature request, I think it can be accomplished quite easily already.

1. OneMore's _Edit/Selected all images_
2. OneNote's _Paragraph alignment/Center_

**Comment by BH2WFR** [comment]
> While I initially marked this as a feature request, I think it can be accomplished quite easily already.
> 
> 1. OneMore's _Edit/Select all images_
> 2. OneNote's _Paragraph alignment/Center_

It works, thank you!
have a nice weekend ^_^
