### ISSUE TITLE
Add the Option to Colorize by a Custom Language -Like in Notepad++

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#888]
Not sure how the Colorize feature was implemented but it would be nice to have the option to add a Custom/User Language 
This could be an easy way or first step to start implementing the other related feature "Apply styles based on regular expressions"
This could be as simple as "word starts with" "word ends with", "word is all numbers" "word ends with" etc etc. More complex regex could be implemented later.

**Comment by stevencohn** [comment]
Languages are [all defined here](https://github.com/stevencohn/OneMore/tree/main/OneMore/Colorizer/Languages).

These JSON files (and associated PNG) are installed with OneMore on your system under `%ProgramFiles%\River\OneMoreAddIn\Colorizer\Languages`

It's extensible so you can drop a new JSON file into that folder on your installed system and OneMore will pick it up the next time your restart OneNote.

If you're adventurous enough to define a new language file, submit it as a PR and I'll add it to the build

**Comment by 1001QAdotNET** [comment]
That is something I can work with thank you. Just add a pointer to this in the menu I am sure many will take advantage of this feature.

**Comment by stevencohn** [comment]
Sorry. A pointer to what? The Colorize menu is already a first-class citizen of the OneMore menu.

**Comment by 1001QAdotNET** [comment]
How are the colors picked for each pattern?

**Comment by 1001QAdotNET** [comment]
`Sorry. A pointer to what? The Colorize menu is already a first-class citizen of the OneMore menu.`
Yes but few realize that you could easily extend that. Probably a link to help or to  the wiki -I apologize for that,  the info is there already but sometimes you have the impression you already know all about it and that was not my case :-|  for this issue

**Comment by stevencohn** [comment]
The "capture" property associates to an entry in the ..\Themes files
