### ISSUE TITLE
Searching online dictionaries the same way we do with search engines

### ISSUE THREAD

**Issue by osman1963** [stevencohn/OneMore#89]
Would it be possible to add this feature: searhing online dicitonaries, like the way we do with search engines now? I mean inserting the url with the appropriate template. I tried inserting it in the search engines option in settings for an online dicionary but it didn't work.
Namely, I used the following urls
https://www.macmillandictionary.com/dictionary/british/search?q={word}
https://www.macmillandictionary.com/dictionary/british/{word}
https://www.macmillandictionary.com/dictionary/british/q={word}
Nothing worked
Thanks in advance 
and as always, thanks a million for the great add-in

**Comment by stevencohn** [comment]
Use the first form and change "{word}" to "{0}"

https://www.macmillandictionary.com/dictionary/british/search?q={0}

**Comment by osman1963** [comment]
I guess it might be another technical issue, since the following quer string
https://www.macmillandictionary.com/dictionary/british/{word}
works fine in calibre.

**Comment by stevencohn** [comment]
It's not a technical issue. It's the way the two programs replace token in the URL differently. Calibre knows to looks for the token "{word}" where OneMore looks for the token "{0}".

**Comment by stevencohn** [comment]
I took another peek and it looks like you can use this:

https://www.macmillandictionary.com/dictionary/british/{0}

**Comment by osman1963** [comment]
Exactly, I even used some other dictionaries too, just replacing the search
word with {0}.
Thanks a million :)
