### ISSUE TITLE
Bulk Moving Pages From Various Sections Based On A Query To A Specified Section

### ISSUE THREAD

**Issue by TheOG-2670** [stevencohn/OneMore#890]
Came across this repository and want to express my admiration for what you've created. I'm absolutely blown away by all the features that a OneNote add-on like this offers as a FOSS product. Truly outstanding. Thank you for creating and maintaining this.

My question is this:
I was wondering whether this add-in supports something like moving multiple pages aggregated from different sections based on a search query to a single destination section in either the same or a different notebook.  Unless it's named differently or buried somewhere in the feature list from the README documentation, I couldn't find if it's supported.

Thanks!

**Comment by stevencohn** [comment]
HI, thanks for the message and the question.

Under the _Search and Tag_ menu, there is a command called _Search and Move or Copy_. This lets you search for words (using the built-in OneNote search functionality), it displays a list of pages that match, lets you choose, and then you can decide to move or copy them to a selected section.

Coming in the next release, there will be a way to file and organize your Quick Notes to a specified notebook or folder, and group them by week, month, quarter, year

I'd like to combine these types of commands into a suite of knowledge management features eventually.

**Comment by TheOG-2670** [comment]
Just tried it and it works flawlessly 😄 
Thank you so much! Have a great day!
