### ISSUE TITLE
About dialog text is not copyable

### ISSUE THREAD

**Issue by julie777** [stevencohn/OneMore#893]
**Is your feature request related to a problem? Please describe.**

When reporting an issue I always open OneMore/About in order to check the version. 
**Describe the solution you'd like**

I would like to be able to copy information from the about dialog so that I can paste it into the issue that I am creating.

An even better solution would be to add a "report issue" button to the OneMore menu, or the about dialog that creates the issue ready to edit with the following information already filled in: 
- OneMore version
- OneNote version
- current section of OneMore log file

**Comment by stevencohn** [comment]
Reasonable.

Although just when I clear up a bunch of tickets, you start adding new ones. Very annoying. 😉  (Cheers Julie! 😄)

**Comment by julie777** [comment]
@stevencohn 
You are responding so fast that I really have to work to keep up.  ;-)
Today was one of those days when I started a task and before I new it I spent most of the day logging issues for OneMore and another product.
