### ISSUE TITLE
Improve the issue template so that it is more readable after issue is submitted.

### ISSUE THREAD

**Issue by julie777** [stevencohn/OneMore#895]
I am just going to convert this entry to a form that I think would be easier to read/use. I suggest just compare this to another feature request to see what I mean.

# Problem to Solve

<(double click and type over)   Provide a clear and concise description of what the problem is. Ex. I'm always frustrated when [...]>

# New Feature/Solution

<A clear and concise description of what you want to happen.>

## Alternative Solutions

<A clear and concise description of any alternative solutions or features you've considered.>

# Additional Context

<Add any other context or screenshots about the feature request here.>

THE FINE PRINT
This is a hobby project that I started for myself. I'm happy to take requests and will promise to consider each one carefully but offer no guarantees that I will ultimately agree to their usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around then I will probably reject the request - you've been warned!

**Comment by julie777** [comment]
@stevencohn Thanks for all your hard work!

**Comment by stevencohn** [comment]
Updated. Not identical to your template but good idea. Thanks

**Comment by julie777** [comment]
Interestingly, the GitHub docs show a template that is similar to what I was proposing.
(https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)

```---
name: 🐞 Bug
about: File a bug/issue
title: '[BUG] <title>'
labels: Bug, Needs Triage
assignees: ''

---

<!--
Note: Please search to see if an issue already exists for the bug you encountered.
-->

### Current Behavior:
<!-- A concise description of what you're experiencing. -->

### Expected Behavior:
<!-- A concise description of what you expected to happen. -->

### Steps To Reproduce:
<!--
Example: steps to reproduce the behavior:
1. In this environment...
2. With this config...
3. Run '...'
4. See error...
-->

### Environment:
<!--
Example:
- OS: Ubuntu 20.04
- Node: 13.14.0
- npm: 7.6.3
-->

### Anything else:
<!--
Links? References? Anything that will give us more context about the issue that you are encountering!
-->
```

**Comment by stevencohn** [comment]
I'm happy with the way it is. Some times, asking users to overwrite or delete things to add their own text is "complicated" or just simply overlooked. So I prefer clean and simple.

**Comment by julie777** [comment]
@stevencohn 
I wasn't suggesting you change it, just providing a reference
