### ISSUE TITLE
XML viewer buttons are a little confusing.

### ISSUE THREAD

**Issue by julie777** [stevencohn/OneMore#896]
## Problem that I would like to resolve

The XML viewer/dialog can be used to view the XML for the current page, and optionally edit the XML content. Currently these two functions are not clearly separated.

### Content Changes

When I open the dialog there is an Update Page and a Cancel button at the bottom of the dialog.
The Update Page button is disabled, which makes sense because I haven't changed anything. 
The Cancel button is enabled which has the following issues:
- I haven't changed the XML content so there is no change to cancel
- clicking on Cancel closes the dialog

### Closing the Window

There is no close button to close the dialog when I am done looking at the XML, although there is a normal Windows X in the upper right corner. Actually, I have been calling it a dialog because it is modal. However, based on the normal Windows window controls in the header it is actually a window, and it looks like a window to the user.

To me that just makes it more confusing because I want it to be a window and non-modal.

## Solution

1. Separate the notion of editing from window control.
2. Provide a Close button to make that obvious.
3. Disable both Update and Cancel until changes are made to the XML.
4. Selecting Update or Cancel when enabled should not close the window.
5. Make the window non-modal.

**Comment by stevencohn** [comment]
Folding into #897
