### ISSUE TITLE
Validate Developer Notes for building OneMore

### ISSUE THREAD

**Issue by julie777** [stevencohn/OneMore#898]
@stevencohn 
I'm not sure of a better way to communicate with you, so it goes here.

I am trying to help with OneMore as much as possible. I think you created something very useful.

If I could get it to build for me I might be able to help with some of the bugs and small changes. I spent most of a day fighting Visual Studio in the past and finally gave up. I might try again this week. 

If you ever have some time to help me get it working I would be grateful, and I could probably pay back the time you spend helping me. We could find some way to set up a chat and work through it. We could also update the wiki with any additional information needed to get it to build.

thanks.

**Comment by stevencohn** [comment]
I'll go through [this section](Added checkbox to enable/disable saving window position.
Added checkbox to optionally write each attribute on its own line.) to make sure it's up to date and can be started from scratch.

**Comment by julie777** [comment]
@stevencohn 

Well, yesterday turned out to be just OneMore day.  :grin:

I spent the evening setting up my dev environment from scratch after uninstalling everything Visual Studio related. It was more difficult than it should be, but this time I got it to work - mostly. The build succeeded, but I still have warnings related to incompatible versions of some assemblies.

I kept notes about the issues and how I solved them. I think it was actually better for me to go through this without you wasting time checking the wiki page. Most of the issues wouldn't happen for you, because they were related to me starting from a different basic config of Windows 10.

I will provide a proposed wiki update for the documentation when I finish resolving the dependency issues.

**Comment by julie777** [comment]
@stevencohn 
It has been a long time since I last used Visual Studio, and I was programming in C++ then. (I have been using Python for the last nine years, and javascript for the last couple. I switched to VScode a couple years ago for both.)

I did use the project to help track down the bug with favorites, but I haven't tried building a debug version...

I will take me a little while to get up to speed with C# and linq before I can really help with the code.

I want to resolve the assembly version conflicts before I try to load a debugging build of OneMore into OneNote.

## Help Wanted

I would welcome any suggestions about resolving the conflicts.

I had an error when opening the solution that C:\Program Files (x86)\Microsoft SDKs\NuGetPackages did not exist. After trying several things I just created the directory and that error went away.
nuget is putting packages into %userprofile%/.nuget/packages and not in the directory noted above.

I changed my nuget settings trying to fix reference resolution.
![image](https://user-images.githubusercontent.com/5090005/218516929-304603ed-814c-4fc8-a3cb-978a07047f6f.png)
![image](https://user-images.githubusercontent.com/5090005/218517010-de2ad40b-b66f-4bf2-b66d-43c6ce94b3dd.png)

I finally had to change the path hint in the .csproj file to the actual path to get some references to resolve.

This my current error log for a complete build after clean of the solution.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		The package Chinese with version 0.5.0 could not be found in C:\Users\julie\.nuget\packages\. Run a NuGet package restore to download the package.	OneMoreCalendar			
Warning		Found conflicts between different versions of "System.Net.Http" that could not be resolved.
There was a conflict between "System.Net.Http, Version=4.1.1.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
    "System.Net.Http, Version=4.1.1.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" was chosen because it was primary and "System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" was not.
    References which depend on "System.Net.Http, Version=4.1.1.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" [C:\Users\julie\.nuget\packages\system.net.http\4.3.4\ref\net46\System.Net.Http.dll].
        C:\Users\julie\.nuget\packages\system.net.http\4.3.4\ref\net46\System.Net.Http.dll
          Project file item includes which caused reference "C:\Users\julie\.nuget\packages\system.net.http\4.3.4\ref\net46\System.Net.Http.dll".
            C:\Users\julie\.nuget\packages\system.net.http\4.3.4\ref\net46\System.Net.Http.dll
    References which depend on "System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" [C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\System.Net.Http.dll].
        C:\Users\julie\.nuget\packages\htmlagilitypack\1.11.46\lib\Net45\HtmlAgilityPack.dll
          Project file item includes which caused reference "C:\Users\julie\.nuget\packages\htmlagilitypack\1.11.46\lib\Net45\HtmlAgilityPack.dll".
            C:\Users\julie\.nuget\packages\htmlagilitypack\1.11.46\lib\Net45\HtmlAgilityPack.dll
        C:\Users\julie\.nuget\packages\plantuml.net\1.4.80\lib\net461\PlantUml.Net.dll
          Project file item includes which caused reference "C:\Users\julie\.nuget\packages\plantuml.net\1.4.80\lib\net461\PlantUml.Net.dll".
            C:\Users\julie\.nuget\packages\plantuml.net\1.4.80\lib\net461\PlantUml.Net.dll	OneMore			
Warning		Found conflicts between different versions of "System.Runtime" that could not be resolved.
There was a conflict between "System.Runtime, Version=4.1.1.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
    "System.Runtime, Version=4.1.1.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" was chosen because it was primary and "System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" was not.
    References which depend on "System.Runtime, Version=4.1.1.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" [C:\Users\julie\.nuget\packages\system.runtime\4.3.1\ref\net462\System.Runtime.dll].
        C:\Users\julie\.nuget\packages\system.runtime\4.3.1\ref\net462\System.Runtime.dll
          Project file item includes which caused reference "C:\Users\julie\.nuget\packages\system.runtime\4.3.1\ref\net462\System.Runtime.dll".
            C:\Users\julie\.nuget\packages\system.runtime\4.3.1\ref\net462\System.Runtime.dll
    References which depend on "System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" [C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\Facades\System.Runtime.dll].
        c:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.20348.0\Windows.winmd
          Project file item includes which caused reference "c:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.20348.0\Windows.winmd".
            Windows
            System.Runtime.WindowsRuntime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=MSIL	OneMore			
Warning		The referenced component 'System.Net.Http' could not be found.	OneMoreCalendar			

```


The missing Chinese one showed up after I completely deleted my .nuget directory to see if everything would be updated correctly. It shows up as installed in solution packages.
![image](https://user-images.githubusercontent.com/5090005/218521427-b5b6f4f0-d83b-4790-adbb-829dd738e469.png)

The build output has many WARNINGS that don't show in the error output. I am not sure why the ones above do and the others don't.

Is it normal for the output to duplicate all the entries?
```
------ Starting pre-build validation for project 'Setup' ------ 
------ Starting pre-build validation for project 'Setup' ------ 
WARNING: Unable to find dependency 'SYSTEM.NET.PRIMITIVES' (Signature='B03F5F7F11D50A3A' Version='4.0.10.0') of assembly 'System.Net.Http.dll'
WARNING: Unable to find dependency 'SYSTEM.NET.PRIMITIVES' (Signature='B03F5F7F11D50A3A' Version='4.0.10.0') of assembly 'System.Net.Http.dll'
```
for the rest of the output every entry appears twice.

I have many of these warnings
```
WARNING: 'System.Runtime.dll' should be excluded because its source file 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.dll' is under Windows System File Protection.
```
and these
```WARNING: Two or more objects have the same target location ('[targetdir]\system.objectmodel.dll')```

This one is a little different
```
WARNING: Configuration file 'C:\Users\julie\juliehome\code\projects\OneMore\OneMoreCalendar\obj\Debug\OneMoreCalendar.exe.config' is being used to configure all executables
```

**Comment by stevencohn** [comment]
I only have this:

<img width="581" alt="image" src="https://user-images.githubusercontent.com/9964757/218522682-57b66c2c-9a20-4cbf-8883-57e19b5f41eb.png">

**Comment by stevencohn** [comment]
The installer build has many warning, yes. Ignore them.

**Comment by stevencohn** [comment]
The only thing you should _need_ to change in the csproj is the version of the SDK as mentioned in the "Developing OneMore" section

**Comment by julie777** [comment]
> The only thing you should _need_ to change in the csproj is the version of the SDK as mentioned in the "Developing OneMore" section

I followed the instructions and it couldn't resolve the reference until I changed 
```
<HintPath>..\..\..\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.20348.0\Windows.    winmd</HintPath>
```
to
```
<HintPath>c:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.20348.0\Windows.    winmd</HintPath>
```

I tried to find out how the hint path is resolved, but after a reasonable amount of time I just "made it work".

**Comment by stevencohn** [comment]
I've updated the [Developer Getting Started page](https://onedrive.live.com/redir?resid=6925D0374517D4B4%2158723&authkey=%21AN6SD9aiIbjQLi0&page=View&wd=target%28Developers.one%7C04d5a868-ef95-4e66-9d60-7a75f1029a31%2FGetting%20Started%7C1fc6d51f-b5c6-4243-ab8a-967dac9f6c86%2F%29&wdorigin=NavigationUrl) with more detail that will hopefully walk through all the necessary details to get up and running.

**Comment by julie777** [comment]
I am in the process of reinstalling and getting the build running again. I will post my notes when I finish.
