### ISSUE TITLE
Save the OneNote current layout and restore it when needed

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#90]
**Is your feature request related to a problem? Please describe.**
I find myself very often adjusting the Navigation bar(the one with the notebooks) and/or the Pages bar to fit a size that would be better for different activities. Also many times I need to hide one for them (the Notebooks bar or the ribbon etc etc)
These also change depending on the screen where the program is dispalyed

**Describe the solution you'd like**
I would like to be able to save the current layout and bring it back easily when needed without having to manually adjust the above things

**Describe alternatives you've considered**
N/A
**Additional context**
N/A

**Comment by stevencohn** [comment]
While that would be very cool, I'm afraid there is no way to control the layout of the ribbon bars beyond what the add-on itself adds.

**Comment by 1001QAdotNET** [comment]
understood.... OK I had no idea , no problem then I will have to live with that :-)
