### ISSUE TITLE
Faster Favorites with the keyboard

### ISSUE THREAD

**Issue by julie777** [stevencohn/OneMore#900]
# Problem to Solve

It takes more keystrokes than I would like to open a favorite. (I do love favorites!)
I have favorites added to the QAT so that `<alt>-3` will open the menu. Then I have to move my hand to the arrow keys and scroll while visually searching the list to select the page I want to go to.

# New Feature/Solution

(I have no idea if this is possible with the interface available to a OneNote add-in.)

**I would like a "type to select" interface for the favorites drop-down.**

I like to use Gmail as an example of an efficient interface, and Gmail uses the "type to select" drop-down textbox to filter and select from the menu very nicely for labels.

The Details
- type `<gl>` in gmail (which is `<alt>-3` for my OneMore favorites).
- the drop down list of all possible choices opens and shows a text box at the top which captures the following keystrokes, unless they are arrows or `<enter>`.
- typing parts of the desired selection reduces the choices available by filtering and at any point the top choice can be selected by `<enter>`

This is insanely fast because:
- fingers stay at the home location on the keyboard
- the list of choices reduces very fast with only a few letters typed
- it is not required to know the exact name of the selection because the letters can match anywhere in the choice
- the user quickly learns to type a group of letters and then hit enter for the most commonly used choices

In addition the implementation filter is simple because it is a simple and exact text match.

BTW, it just occurred to me that this is exactly how I open applications in Windows for those not pinned to the task bar and opened with `<win>-N`. 
I open Fusion 360 with `<win> f <enter>`
I do realize that Windows is remembering past uses to selection Fusion 360 with `f` instead of Firefox. However, `<win>-f-u-<enter>` would always work as there are no other apps installed with `fu` in the name.

My use case is often
- quickly jump to a favorite page
- jot down a note or add some information
- use "return to previous page" to jump back

My QAT starts with Back, Foward, Favorites

**Comment by stevencohn** [comment]
Press Alt+F to open the OneMore Favorites dialog, which has been enhanced a bit in 5.7.0.
Good 'nuf?

**Comment by julie777** [comment]
@stevencohn 
It is just not fair. You are releasing faster than I can enter issues. `<LOL>`

I will have to settle for complaining that the installer closed OneNote but didn't reopen it when the install finished. <smile>

Oops, I spoke too soon. 
(I am about to submit after attempting to make it work. I realize that this is a mess, but it is a chronological log of everything I did to provide you more details.)

`<alt>-f` and this

![image](https://user-images.githubusercontent.com/5090005/218358231-61ab8267-e398-4d81-86b4-00b22e60c455.png)

and the details from the dialog

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Xml.XmlException: The ' ' character, hexadecimal value 0x20, cannot be included in a name.
   at System.Xml.XmlConvert.VerifyNCName(String name, ExceptionType exceptionType)
   at System.Xml.Linq.XName..ctor(XNamespace ns, String localName)
   at System.Xml.Linq.XNamespace.GetName(String localName, Int32 index, Int32 count)
   at River.OneMoreAddIn.FavoritesProvider.<>c__DisplayClass20_0.<ConfirmByName>b__0(XElement n)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at River.OneMoreAddIn.FavoritesProvider.<ConfirmByName>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at River.OneMoreAddIn.FavoritesProvider.<ValidateFavorites>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.FavoritesProvider.<LoadFavorites>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at River.OneMoreAddIn.Commands.Favorites.FavoritesDialog.<BindOnLoad>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
River.OneMoreAddIn
    Assembly Version: 5.7.0.0
    Win32 Version: 5.7.0
    CodeBase: file:///C:/Program%20Files/River/OneMoreAddIn/River.OneMoreAddIn.dll
----------------------------------------
office
    Assembly Version: 15.0.0.0
    Win32 Version: 15.0.4613.1000
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/office/15.0.0.0__71e9bce111e9429c/office.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4550.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4435.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.Web.Extensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4494.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Web.Extensions/v4.0_4.0.0.0__31bf3856ad364e35/System.Web.Extensions.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4494.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
Microsoft.Office.Interop.OneNote
    Assembly Version: 15.0.0.0
    Win32 Version: 15.0.4420.1017
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.Office.Interop.OneNote/15.0.0.0__71e9bce111e9429c/Microsoft.Office.Interop.OneNote.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

Continue let me see the dialog and start typing, but there are no choices.
The last entry in the log doesn't seem useful
```

26804:1] Starting dllhost 26804, CPU=2904Mhz, en-US/en-US, v5.7.0, OneNote 15.0, Office 16.0
26804:1] ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.16026.20146)
26804:1] ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
26804:1] ..OneAddInsUpdate(custom[])
26804:1] ..building ribbon
26804:1] ..building ribbon colorizer commands
26804:1] ..building ribbon groups
26804:1] ..building context menu
26804:1] ..OnStartupComplete(custom[])
26804:1] ..starting command service
26804:1] ..starting reminder service
26804:1] ..ready
26804:5] defining 148 hotkeys for input locale 1033
26804:9] Running command UpdateCommand
26804:9] Running command GotoFavoriteCommand
26804:9] Running command AboutCommand
```

Selecting favorites from the ribbon showed the list normally.

I closed and then reopened OneNote and the problem still occurs. 
I right clicked in the OneMore section of the ribbon so that I could customize the ribbon to see the command...
This happened.

![image](https://user-images.githubusercontent.com/5090005/218358947-a898d51f-0d7c-4662-8d27-956925a2479b.png)

Not sure what happened, as it is not reproducible and I now have the ribbon customize dialog open.
After looking around, I closed the dialog and clicked on favorites and the menu is empty.
![image](https://user-images.githubusercontent.com/5090005/218359840-45738d44-3052-440f-b62e-f4db93ec913d.png)

Closed OneNote and after reopening checked favorites and they are all there.
Open shortcuts from the Favorites menu and it showed the generated page from a version 4 variant where `<alt>-f` was for search and move/copy. 
I deleted the shortcut page and did it again and it generated a new v5 shortcut page which doesn't show the `<alt>-f` shortcut at all.

Closed OneNote and tried to do a modify/repair install of OneMore to see if that helped and

![image](https://user-images.githubusercontent.com/5090005/218361022-17f48d14-64e7-4fde-a855-3309121f9c3e.png)

This is getting ugly!

I completely uninstalled OneMore and reinstalled v5.7 and the error still persists when using the shortcut key for favorites.

**Comment by jasonjac2** [comment]
I get the same error when invoking the fav's dialogue with Ctrl+f and also when going into manage fav's.

If you want a copy of my favs .xml let me know and I will e-mail them to you.


System.Xml.XmlException: The ' ' character, hexadecimal value 0x20, cannot be included in a name.
   at System.Xml.XmlConvert.VerifyNCName(String name, ExceptionType exceptionType)
   at System.Xml.Linq.XName..ctor(XNamespace ns, String localName)
   at System.Xml.Linq.XNamespace.GetName(String localName)
   at System.Xml.Linq.XName.Get(String expandedName)
   at System.Xml.Linq.XName.op_Implicit(String expandedName)
   at River.OneMoreAddIn.FavoritesProvider.<>c__DisplayClass20_0.<ConfirmByName>b__0(XElement n)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at River.OneMoreAddIn.FavoritesProvider.<ConfirmByName>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at River.OneMoreAddIn.FavoritesProvider.<ValidateFavorites>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.FavoritesProvider.<LoadFavorites>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at River.OneMoreAddIn.Commands.Favorites.FavoritesDialog.<BindOnLoad>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by jasonjac2** [comment]
If I rename my fav's file all is OK, so I think it is parsing the favourites and possibly displaying them.

**Comment by stevencohn** [comment]
@julie777 please kick off an email discussion by contacting me here https://stevencohn.net/#contact

I don't like to post my email in these issues due to junk mail spiders.

**Comment by jasonjac2** [comment]
@stevencohn  I've e-mailed you a copy of my fav's so you can see which one of the fav's looks like it might cause the issue.

**Comment by stevencohn** [comment]
Got it but it loads fine so I'm hoping Julie's helps diagnose the problem. Meanwhile, I throwing in all kinds of error handling. If it can't read the file, it will start from scratch. But if there's a specific problem, I may be able to fix it.

**Comment by jasonjac2** [comment]
@julie777 Julie,
I have coding envy now. I started setting up the C# environment ages ago, but didn't get to the point of compiling.
 
I've also had the issue where alt+f brings up the file menu, but it seems to sort itself out.  There are definately some weird things happening if you click or invoke things too quickly.  I find clickng off the instance onto another instance and back again seems to fix it (maybe).

Strange the @stevencohn didn't have the error when using my fav's .xml as all the labels have spaces in them.

**Comment by stevencohn** [comment]
> Making it easy to change the OneMore shortcut ...
You can customize all OneMore shortcuts in the OneMore Settings dialog

> maybe that provides a way to replace the normal style shortcut bindings...
The first nine styes defined are also customizable in the Keyboard settings

I can fix the space issue now. It would only happen for existing favorites that were created prior to 5.7 and do not have the notebookID and pageID attributes. If those attributes do not exist, it falls back on the screentip attribute to determine if the page is still valid and that's where it's complaining about the space.

**Comment by stevencohn** [comment]
The Alt problem is transitional. If you just click on the OneMore menu, it re-actives the bindings if they were lost. I haven't figure out why/when it looses the bindings.

**Comment by stevencohn** [comment]
BTW, If an Alt binding is overriden, like Alt+F, you can still press [Alt] followed by [F} will activate the File menu. Not standard, I totally understand, but just an observation

**Comment by julie777** [comment]
@jasonjac2 
> @julie777 Julie, I have coding envy now. I started setting up the C# environment ages ago, but didn't get to the point of compiling.

My goal is to update the development setup documentation so that anyone can get it building. You can be the test for that.
