### ISSUE TITLE
Discussing Custom Styles and How the Affect the XML Page Representation

### ISSUE THREAD

**Issue by julie777** [stevencohn/OneMore#914]
@stevencohn 

I really which that discussions were enabled for topics like this.

After spending time trying to find out why Custom Styles often don't work as expected and spending way to much time looking at page content, style definitions and page XML I am left with an incomplete understanding.

I have several thoughts about the debugging process that I will submit as feature requests.

I there already a document somewhere that documents what you know about:
- styles and how they are applied by OneNote natively
- how styles and manual formatting interact
- how differing style definitions for different pages are managed

I am going back to the MS OneNote developer documentation to see if I can learn more, but it is never easy. In addition I am going to try and set up a test that makes changes and captures the XML after each change to use as a reference.

I really think this should be a discussion among all OneMore developers and users who want to participate. I should have the goal to share knowledge and build a complete understanding. 

That would let us solve all the issues at once instead of continuing to find new problems on an ongoing basis.

**Comment by stevencohn** [comment]
I can provide a brain dump as a doc page. I don't claim to know it all (I'm not a Microsoft OneNote engineer) but I can write down what I've learned over the years. It's actually simpler than you think (with caveats 😉 )

**Comment by julie777** [comment]
Most of my issues are finding the approriate MS documentation. So many of the links are old and broken, and often searching takes me to hundreds of pages about the new javascript model for everything.

I've long been frustrated by MS and their need to always change things, but almost never fix any of the existing problems with the changes.

**Comment by stevencohn** [comment]
You won't find it. It doesn't exist. 

There is meta information in the [XML Schema file here](https://github.com/stevencohn/OneMore/blob/main/Reference/0336.OneNoteApplication_2013.xsd) and in the [OneNote File Formats files here](https://learn.microsoft.com/en-us/openspecs/office_file_formats/ms-offfflp/6ae2fd93-51fc-4e75-a54a-1b175c627b51?redirectedfrom=MSDN). Good luck! They're not exactly light reading.

**Comment by stevencohn** [comment]
@julie777 Here's my write up on [OneNote Styles](https://onedrive.live.com/redir?resid=6925D0374517D4B4%2158723&authkey=%21AN6SD9aiIbjQLi0&page=View&wd=target%28Developing%20OneMore.one%7C04d5a868-ef95-4e66-9d60-7a75f1029a31%2F[Styles](https://github.com/stevencohn/OneMore/issues/914)%7Cd1f6507c-d49a-46c3-ab94-bf29b0d9a42f%2F%29&wdorigin=703)

It's a first pass. Let me know if you have any questions.

**Comment by stevencohn** [comment]
Closing this for now. I'll keep adding info to the new Wiki as time allows.
