### ISSUE TITLE
XML Viewer enforces a minimum page width that is too wide

### ISSUE THREAD

**Issue by julie777** [stevencohn/OneMore#915]
# Problem to Solve

I can't shrink the XML viewer to half screen because its minimum size is locked.

# To Reproduce

Just try to resize the window so the width is narrow.

# Expected Behavior

The minimum acceptable behavior would be to let it resize smaller until the heading information (check boxes and such) would no longer fit. On my screen by reducing space between the columns in the header it would allow a 20% smaller width.

Even better would be to re-flow the heading so that it could be even narrower. I can visualize my screen with the header rearranged into two columns and that would not reduce its usefulness, but then I could reduce the width of the window to about 1/3 of my screen width.

# Screenshots

**Comment by stevencohn** [comment]
Minimum size = 800 x 500

**Comment by julie777** [comment]
Thanks.
