### ISSUE TITLE
Information displayed at the bottom of the XML tool window is displaying poorly

### ISSUE THREAD

**Issue by julie777** [stevencohn/OneMore#918]
# Problem to Solve

At the bottom of the XML tool window there is some metadata shown, but
- it seems smushed together vertically
- it is partly covered by the button(s)
- the link is too long to read and is not scroll-able
- the link is not copy-able

![image](https://user-images.githubusercontent.com/5090005/219174872-43426501-f07a-4a49-af90-a0b519f03c21.png)

# To Reproduce

1. Open the XML tool

# Expected Behavior

Show information so that it is usable.

(Note: Microsoft is the worst offender, displaying long text in narrow dialog boxes with no ability to resize or scroll.)

# Screenshots

# Environment (if applicable)

(@stevencohn I am not sure why you have if applicable. It seems like for a bug report it is necessary.)

Version 5.7.1 with OneNote 16.0.16026.20146

# Additional Context

Add any other context about the problem here. Attach page XML file or the app log file as appropriate. You can find the log file here: %localappdata%\temp\OneMore.log

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
I can solve the spacing issue. But other than that, the link is purely informational and otherwise useless. It is written to the log file when you press Shift+F8 but all it will do is open that page in OneNote, which you already have open.

**Comment by stevencohn** [comment]
Buttons moved up as part of #915

**Comment by julie777** [comment]
I didn't know about shift+F8. Thanks.
