### ISSUE TITLE
When using rollover highlighter it concatenates successive lines

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#92]
**Describe the bug**

**To Reproduce**
1. using the below XML doc if select the second line
2. hit the rollover highlighter (in my case in on the quick access ribbon)
3. the second line, selected, gets higlighted but then it is concatenated with the one above it, see the animated gif beow

**Expected behavior**
N/A
**Screenshots**
https://i.imgur.com/UHcPcmo.gif

**Environment (if applicable):**
 - OneNote Version: [e.g. Office 2019, O365, also 32bit or 64bit?]
 - OneMore Version [e.g. 3.4 - from the About dialog]

**Additional context**
`<one:Page xmlns:one="http://schemas.microsoft.com/office/onenote/2013/onenote" ID="xxxx}" name="Rollover highlighter bug" dateTime="2020-11-10T16:57:47.000Z" lastModifiedTime="2020-11-10T17:08:32.000Z" pageLevel="1" isCurrentlyViewed="true" selected="partial" lang="en-US">
  <one:QuickStyleDef index="0" name="PageTitle" fontColor="automatic" highlightColor="automatic" font="Calibri Light" fontSize="20.0" spaceBefore="0.0" spaceAfter="0.0" />
  <one:QuickStyleDef index="1" name="p" fontColor="automatic" highlightColor="automatic" font="Calibri" fontSize="11.0" spaceBefore="0.0" spaceAfter="0.0" />
  <one:Meta name="omHighlightIndex" content="0" />
  <one:PageSettings RTL="false" color="automatic">
    <one:PageSize>
      <one:Automatic />
    </one:PageSize>
    <one:RuleLines visible="false" />
  </one:PageSettings>
  <one:Title selected="partial" lang="en-US">
    <one:OE alignment="left" quickStyleIndex="0" selected="partial">
      <one:T><![CDATA[Rollover highlighter bug]]></one:T>
      <one:T selected="all"><![CDATA[]]></one:T>
    </one:OE>
  </one:Title>
  <one:Outline>
    <one:Position x="36.0" y="86.4000015258789" z="0" />
    <one:Size width="540.0" height="34.79000091552734" />
    <one:OEChildren>
      <one:OE alignment="left" quickStyleIndex="1">
        <one:T style="font-family:Calibri;font-size:10.5pt"><![CDATA[<span style='font-weight:bold'>Example</span>]]></one:T>
        <one:OEChildren>
          <one:OE alignment="left" quickStyleIndex="1" style="font-family:Calibri;font-size:9.0pt">
            <one:T><![CDATA[<span style='color:#888888'>testline</span><span style='color:#404040'><br>
</span><span style='font-weight:bold;color:#008800'>Lore ipsum</span><span style='color: #404040'>:</span>]]></one:T>
          </one:OE>
        </one:OEChildren>
      </one:OE>
    </one:OEChildren>
  </one:Outline>
</one:Page>`

**Comment by stevencohn** [comment]
This is due to an error in a routine that is common to many OneMore commands, so you'll notice the same behavior if you use the To uppercase, To lowercase, and Apply style commands. I'll get right on it.

**Comment by 1001QAdotNET** [comment]
Yeah the highlighter does that only when you select the entire row I think

**Comment by stevencohn** [comment]
Release 3.7.1 improves the way the Highlighter command and the Uppercase and Lowercase commands preserve existing styling of selected text elements. In some cases, it now preserves the soft-break but there are cases where OneNote is just stubborn and wants to do its own thing.

The behavior you see - merging two lines - happens only when there is a soft-break between the lines. A soft-break is created when you hold down Shift and press Enter (Shift+Enter) instead of just using Enter. Internally, it inserts a BR (HTML line break element) but it is technically the same text run (the same line). OneNote makes preserving this more complicated that it should be. Regardless, while I'll keep investigating, there may not be much I can reasonably do to fix it.

**Comment by CLITrees** [comment]
Got it, thank you. At least I know where the problem is and how to deal with it

**Comment by 1001QAdotNET** [comment]
Got it, thank you. At least I know where the problem is and how to deal with it
Please close this if you do not plan to continue work on this (I think you mentioned somewhere that it will still be on your list but not urgent or critical to fix)
