### ISSUE TITLE
Shortcut Ctrl-Shift-F used for Bold in OneNote

### ISSUE THREAD

**Issue by Shopworker** [stevencohn/OneMore#924]
I use OneMore since a few days, many fine functions.

Issue:
In OneNote i used Crtl-Shift-F for making text bold, this worked not after installing OneMore.

Could you make the ShortCut used in OneMore to another Shortcut as standard.

I changed the ShortCut in OneMore, so i can use the originally Shortcut in OneNote ;-)

Thanx,
      Stephan

**Comment by stevencohn** [comment]
Hi. Thanks for the comment.

Ctrl+Shift+F is not a standard key sequence in any Office apps that I know of. I've tested it in OneNote without OneMore installed and it does nothing.

The normal shortcut for making text bold is Ctrl+B.

**Comment by julie777** [comment]
Why not use `<ctrl>-b` like you do in every other editing app?
