### ISSUE TITLE
Extending the functionality for the wiki link page creation to copy the contents of the block

### ISSUE THREAD

**Issue by osman1963** [stevencohn/OneMore#93]
Here is the idea:
typing [[new page]] will create a new empty page in the same section.
My problem is that I summarize some long texts this way, giving each paragraph or so a title, then use this formula [[new page title]] to create pages for each paragraph, then sart copying/pasting the texts under each title to the corresponding page. thiis really time consumeing and boring.
So If you can use your genious and make it create a new page with the text in the block (copying it atuomatically) that would be great. May be by highlighting the title (insted of useing the [[]]) and clicking a new context menu command for example, so it creates a new page, with the first line as title and the rest of the block as the contents of the page.

Hope it is possible.
And Thanks a million for making our lives easier with this great add-in

**Comment by stevencohn** [comment]
Done
https://github.com/stevencohn/OneMore/releases/tag/3.8

**Comment by osman1963** [comment]
Thank you Thank you Thank you
