### ISSUE TITLE
Colorizer - different theme for language

### ISSUE THREAD

**Issue by NoralK** [stevencohn/OneMore#932]
# Problem to Solve

Ability to match color profile of a specific language from Visual Studio, PowerShell ISE, SSMS, etc.

# New Feature/Solution

Provide the ability to specify a customized theme for a specific language, if not found use the default theme.

## Alternative Solutions

Copy code into Word using Copy/Paste (Keep Source Formatting).  However, this method does not allow for light/dark themes, also if the editor does not support RTF/HTML copying to the clipboard then this method does not work.

**Comment by stevenmcohn** [comment]
Hi @NoralK, The OneNote Colorize commands are (mostly) based on Visual Studio syntax highlighting colors. If there are discrepancies, please let me know and I'll try to match it as closely as possible. The colors are all controlled by theme files so it's relatively easy to do. 

There are theme files for light mode and dark mode. I know some of them are not complete for dark mode. If there's a specific language that you're interested in, let me know and I'll take a look.

**Comment by stevencohn** [comment]
Hi @NoralK, The OneNote Colorize commands are (mostly) based on Visual Studio syntax highlighting colors. If there are discrepancies, please let me know and I'll try to match it as closely as possible. The colors are all controlled by theme files so it's relatively easy to do.

There are theme files for light mode and dark mode. I know some of them are not complete for dark mode. If there's a specific language that you're interested in, let me know and I'll take a look.

**Comment by stevencohn** [comment]
Also note that the current theme files are defined to suite light more OR dark mode. If you switch the background, you'll have to reapply the command.

The alternative is to use colors the work for both palettes but then neither will match VS due to the way OneNote translates colors.

**Comment by NoralK** [comment]
Thank you for the reply, I am not too concerned about light vs dark but it is good information to have.

My point is there are color differences between languages.  For example PowerShell strings are red and TypeScript strings are orange.  This is why a suggested add a customized theme for a specific language, maybe themes one for light, one for dark that falls back to the base theme colors.

Like I mentioned, I have a workaround but it is clunky and time consuming.  It would be nice to have this ability, but I understand if it cannot be added.

**Comment by stevencohn** [comment]
@NoralK I don't seem to be able to reproduce that. 

All language use the same theme file and there is only one definition of "string" which is defined as a maroon-like color. Here's an example

<img width="232" alt="image" src="https://user-images.githubusercontent.com/9964757/222931534-b094dde4-88e9-4be5-a464-309bcc6e1f90.png">

PowerShell variables are colored as an orange-red like this

<img width="141" alt="image" src="https://user-images.githubusercontent.com/9964757/222931634-c93d65fb-81b4-4c6e-94c2-165a64550089.png">

So do you have an example that shows what you means?
