### ISSUE TITLE
[FR] Paste image at max. defined size

### ISSUE THREAD

**Issue by foreachthing** [stevencohn/OneMore#934]
# Problem to Solve
When pasting images, from clipboard, into OneNote, OneNote feels the need to resize my tables all the time!
I capture at 4k and most people don't. But still OneNote is being silly and inserts at 72dpi, I guess.

# New Feature/Solution
Set a max width or height when pasting images from clipboard so the table(s) don't get fubared.

## Alternative Solutions
Paste, resize image, adjust table.

Thanks for all of your work!! 👍🏼

**Comment by stevencohn** [comment]
So I can't specifically _intercept_ the paste operation (Ctrl+V) unless I inject a privileged Windows hook which I don't really want to do. There are two alternatives.

1. Add a new command to emulate a paste operation and automatically set the viewed size, width and height, of the image. While this will prevent the asymmetric rubber-banding effect of table, maybe resulting in a slightly altered layout, this seems like a lot of work for (not much) gain?
2. You can use the Resize and Adjust feature to resize all images on the page, using the Limit option to _Do not enlarge smaller images_; that will shrink large images but leave small ones alone.

<img width="263" alt="image" src="https://user-images.githubusercontent.com/9964757/220418727-b6768da6-530b-44ef-83ee-1a139828aab1.png">

**Comment by foreachthing** [comment]
You just gave me an idea! 
I can access the clipboard and resize (by percentage) it and copy it again.

Well, "not much gain": I use it ip to 30x a day and have to resize every single image (not all have the same size) manually. Your resize/crop tool is very, very helpfull here!

I'll close here and thank you for your time answering my FR.
