### ISSUE TITLE
The "Analyze Data Storage" function caused the OneNote process to crash

### ISSUE THREAD

**Issue by cwtien** [stevencohn/OneMore#935]
# Problem to Solve

The previous problem reappeared
https://github.com/stevencohn/OneMore/issues/607

When using the "Analyze Data Storage" function, if there are too many files on the page, the OneNote process will crash. And the report of the data store cannot be output.

It can be used normally when the page file is small.
But in fact, this function is not necessary to use when the page file is small, and this function does not work when the page file is too large.

# This bug also affects other functions.
For example, "number pages", if there are too many pages, the number cannot be generated, but crashes.
For example, "total words in notebook", if there are too many pages, it will crash.

It can be speculated that any function involving "processing or counting multiple pages at the same time" has this problem, so if you decide to fix this bug, consider fixing it at the same time to reduce the workload.

# To Reproduce

1. Click on 'more'
2. Click on 'file'
3. Click on 'Analyze Data Storage'
4. Make sure that the number of pages of the current notebook page, the number of files and pictures is very large
5. tick 'Include page details for current section'，and click on 'OK'

# Expected Behavior

Analyze and output a storage size report as normal.

But actually the whole OneNote process will crash

# Screenshots

![1677084628515](https://user-images.githubusercontent.com/40879080/220700056-914774dc-07c4-4dc5-94f0-07e09b801e7b.jpg)

# Environment 

 - OneNote Version: Microsoft 365MSO (2212 Build 16.0.15928.20144) 64
 - OneMore Version  5.7.2 with OneNote 16.0.15928.20160

# Processes involved
By looking at the task manager, it involves dllhost.exe and COM Surrogate.
It may be that the number of image caches is too large to cause a flashback. Or too many OneNote pages loaded at one time lead to insufficient memory
It can be seen from the log that there is insufficient memory.

# Possible suggestions
1. Consider adding a "Thumbnail off" switch that might help
2. When running this function, first traverse the number of page files. If the number is too large, split it into several runs. Avoid flashbacks caused by too large image cache, Or too many OneNote pages loaded at one time lead to insufficient memory, and the function cannot be used.

# Additional Context

OneMore.log

01| Starting dllhost 16768, CPU=2801Mhz, zh-CN/zh-CN, v5.7.2, OneNote 15.0, Office 16.0, 2023-02-23 00:36
01| ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.15928.20160)
01| ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
01| ..OneAddInsUpdate(custom[])
01| ..building ribbon
01| ..building ribbon colorizer commands
01| ..building ribbon language proofing commands
01| ..OnStartupComplete(custom[])
01| ..starting command service
01| ..starting reminder service
01| ..ready
03| defining 148 hotkeys for input locale 4100
07| Running command AnalyzeCommand
07| ..cannot translate sectionDetailsBox, name not found
07| ..png caused 内存不足。
07| ..System.OutOfMemoryException
Message: 内存不足。
Source: System.Drawing
StackTrace:    在 System.Drawing.Image.GetThumbnailImage(Int32 thumbWidth, Int32 thumbHeight, GetThumbnailImageAbort callback, IntPtr callbackData)
   在 River.OneMoreAddIn.Commands.AnalyzeCommand.ReportImage(Table detail, XElement image, Boolean printout)
TargetSite: [System.Drawing] System.Drawing.Image::GetThumbnailImage()

07| ..png caused 内存不足。
07| ..System.OutOfMemoryException
Message: 内存不足。
Source: System.Drawing
StackTrace:    在 System.Drawing.Image.GetThumbnailImage(Int32 thumbWidth, Int32 thumbHeight, GetThumbnailImageAbort callback, IntPtr callbackData)
   在 River.OneMoreAddIn.Commands.AnalyzeCommand.ReportImage(Table detail, XElement image, Boolean printout)
TargetSite: [System.Drawing] System.Drawing.Image::GetThumbnailImage()

07| ..error getting page {70E33167-146F-075B-2610-AFDBB08A85BA}{1}{E1948152852265236260301987706581047515436901}
07| ..System.Runtime.InteropServices.COMException
Message: 远程过程调用失败。 (异常来自 HRESULT:0x800706BE)
Description: Unrecognized error code 0x800706BE
ErrorCode: 0x800706BE (-2147023170)
HResult: 0x800706BE (-2147023170)
Source: Microsoft.Office.Interop.OneNote
StackTrace:    在 Microsoft.Office.Interop.OneNote.ApplicationClassCOM.GetPageContent(String bstrPageID, String& pbstrPageXmlOut, PageInfo pageInfoToExport, XMLSchema xsSchema)
   在 River.OneMoreAddIn.OneNote.GetPage(String pageId, PageDetail detail)
TargetSite: [Microsoft.Office.Interop.OneNote] Microsoft.Office.Interop.OneNote.ApplicationClassCOM::GetPageContent()

07| 运行命令AnalyzeCommand时出错
07| System.NullReferenceException
Message: 未将对象引用设置到对象的实例。
Source: River.OneMoreAddIn
StackTrace:    在 River.OneMoreAddIn.Commands.AnalyzeCommand.ReportPage(Table table, String pageId)
   在 River.OneMoreAddIn.Commands.AnalyzeCommand.ReportPages(XElement container, XElement section, String folderPath, String skipId)
   在 River.OneMoreAddIn.Commands.AnalyzeCommand.<Execute>d__23.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 River.OneMoreAddIn.CommandFactory.<Run>d__5.MoveNext()
TargetSite: [River.OneMoreAddIn] River.OneMoreAddIn.Commands.AnalyzeCommand::ReportPage()

**Comment by cwtien** [comment]
This lack of memory also affects other functions.
For example, "number pages", if there are too many pages, the number cannot be generated, but crashes.
For example, "total words in notebook", if there are too many pages, it will crash.

It can be speculated that any function involving "processing or counting multiple pages at the same time" has this problem, so if you decide to fix this bug, consider fixing it at the same time to reduce the workload.

**Comment by cwtien** [comment]
This lack of memory also affects other functions.
For example, "number pages", if there are too many pages, the number cannot be generated, but crashes.
For example, "total words in notebook", if there are too many pages, it will crash.

It can be speculated that any function involving "processing or counting multiple pages at the same time" has this problem, so if you decide to fix this bug, consider fixing it at the same time to reduce the workload.

**Comment by stevencohn** [comment]
Thank you

**Comment by stevencohn** [comment]
How many pages are you talking about? How big are your notebooks?

**Comment by cwtien** [comment]
> How many pages are you talking about? How big are your notebooks?

The size of my notebook is 1.25GB, and the number of partition pages is about 400 pages.
Taking the "number pages" function as an example, the software crashes after about 40 pages are marked.
The "Analyze Data Storage" function may also crash on this order of magnitude, because the crash time is similar.
My win10 computer has 16GB of RAM.

**Comment by cwtien** [comment]
Hello, thank you very much for your efforts. I updated the latest version and tried it. It has some help. Now it can run for more than ten seconds without crashing.
But it will still flash back after more than ten seconds. The situation is the same as before. It crashes after analyzing dozens of pages.

**Comment by stevencohn** [comment]
Did you set the Thumbnails option to _None_?
