### ISSUE TITLE
Browse all the to-do items in all the notes in one place.

### ISSUE THREAD

**Issue by Benjamin-Watson0** [stevencohn/OneMore#936]
# Problem to Solve

Browse all the to-do items in all the notes in one place.
In many cases, we jotted down the to-do list in our notes, and later we forgot it. Because he is scattered in different articles. If you can view all the proxy items in all the notes at one time, it will be of great help for us to complete the to-do list

# New Feature/Solution
Browse all the to-do items in all the notes in one place.
This is convenient to manage the to-do list. It's also very convenient. I think it is perfect to add the to-do items in the notes to Microsoft to do.
## Alternative Solutions

I haven't thought too much for the time being.

# Additional Context

Thank you very much for your help.😁

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
OneNote already has a _Find Tags_ feature that allows you to filter by _unchecked items_

<img width="524" alt="image" src="https://user-images.githubusercontent.com/9964757/220937251-4aa74f29-b042-4a4c-bc4c-5192b7196d91.png">

**Comment by Benjamin-Watson0** [comment]
I don't know that the original search tag is used for this!! I have ignored it before.
Thank you very much. That's great. It seems necessary for me to carefully understand the functions of onenote.🧐
________________________________
发件人: Steven ***@***.***>
发送时间: 2023年2月23日 22:35
收件人: stevencohn/OneMore ***@***.***>
抄送: Benjamin Watson ***@***.***>; Author ***@***.***>
主题: Re: [stevencohn/OneMore] Browse all the to-do items in all the notes in one place. (Issue #936)


OneNote already has a Find Tags feature that allows you to filter by unchecked items

[image]<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F9964757%2F220937251-4aa74f29-b042-4a4c-bc4c-5192b7196d91.png&data=05%7C01%7C%7C0174538048be4106efd308db15ab2acf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638127597148297904%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5zRl%2FhzPScHuWZS29n9x19l%2BN1HxUmpEWzvT3CX32Jg%3D&reserved=0>
