### ISSUE TITLE
OneNote can't load OneMore

### ISSUE THREAD

**Issue by valuex** [stevencohn/OneMore#938]
# Problem to Solve

OneMore can't be loaded in OneNote

# To Reproduce

I recompiled OneMore 5.7.1 and added one feature to quickly jumped to a certain page by fuzzy search.  
It seems that the ```NavigateTo``` method is called in the wrong way.  (First mistake)
OneNote get stucked everytime I click it.
After several times trial, OneNote popup a window saying something like forbidden loading the add-in. (Sorry I forgot the original alert message)
And I clicked yes (2nd mistake), then OneNote can't load OneMore anymore.  
I've tried to uninstall and re-install Microsoft365, but still no luck here.

# Expected Behavior

OneNote can load OneMore as usual

# Screenshots

![image](https://user-images.githubusercontent.com/3627812/221199078-0c37c6d3-ca9a-4c5d-8e28-27a33af824ed.png)

# Environment (if applicable)

 - OneNote Version: Microsoft® OneNote® for Microsoft 365 MSO (Version 2302 Build 16.0.16130.20122) 64-bit 
 - OneMore Version 5.7.1/5.7.2

# Additional Context

```SaveToMRU using derived name **QuickVisitCmd**``` is defined in the revision I made based on OneMore5.7.1.
It seems that OneMore is not completely uninstalled even if I've un- and re-intalled MSOffice and OneMore 5.7.2.
Any suggestion on how to completely unistall OneMore?   

Add any other context about the problem here. Attach page XML file or the app log file as appropriate. You can find the log file here: %localappdata%\temp\OneMore.log

```
01| Starting dllhost 16412, CPU=2419Mhz, zh-CN/zh-CN, v5.7.2, OneNote 15.0, Office 16.0, 2023-02-19 15:38
01| ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.14332.20447)
01| ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
01| ..OneAddInsUpdate(custom[])
01| ..building ribbon
01| ..building ribbon colorizer commands
01| ..building ribbon language proofing commands
01| ..OnStartupComplete(custom[])
01| ..starting command service
01| ..starting reminder service
01| ..ready
03| defining 148 hotkeys for input locale 2052
07| Running command QuickVisitCommand
07| ..error invoking action
07| ..System.Runtime.InteropServices.COMException
Message: 远程过程调用失败。 (异常来自 HRESULT:0x800706BE)
Description: Unrecognized error code 0x800706BE
ErrorCode: 0x800706BE (-2147023170)
HResult: 0x800706BE (-2147023170)
Source: Microsoft.Office.Interop.OneNote
StackTrace:    在 Microsoft.Office.Interop.OneNote.ApplicationClassCOM.NavigateTo(String bstrHierarchyObjectID, String bstrObjectID, Boolean fNewWindow)
   在 Microsoft.Office.Interop.OneNote.ApplicationClass.NavigateTo_AutoBusyRetry(String bstrHierarchyObjectID, String bstrObjectID, Boolean fNewWindow)
   在 River.OneMoreAddIn.OneNote.<>c__DisplayClass65_0.<NavigateTo>b__0()
   在 River.OneMoreAddIn.OneNote.<InvokeWithRetry>d__28.MoveNext()
TargetSite: [Microsoft.Office.Interop.OneNote] Microsoft.Office.Interop.OneNote.ApplicationClassCOM::NavigateTo()

07| SaveToMRU using derived name QuickVisitCmd
```
THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by valuex** [comment]
[OneMore.zip](https://github.com/stevencohn/OneMore/files/10825085/OneMore.zip)

The project I wrote based on OneMore 5.7.1 as above.
Two times un-zip is needed, 1st to un-zip as *.7z file and 2nd to un-zip as folder

**Comment by stevencohn** [comment]
It's unclear what you've done or what you broke. 

* Please look at this about [redirecting the COM registration](https://onedrive.live.com/redir?resid=6925D0374517D4B4%2158723&authkey=%21AN6SD9aiIbjQLi0&page=View&wd=target%28Developers.one%7C04d5a868-ef95-4e66-9d60-7a75f1029a31%2FTechNote%20-%20COM%20Registration%7Ca8f82d6a-a30f-4694-8cf6-c302be2bafd8%2F%29&wdorigin=703)
* From an admin PowerShell prompt, run .\iq.ps1 to see if it reports any problems

**Comment by stevencohn** [comment]
let me take a look at the zip

**Comment by stevencohn** [comment]
OK.

1. NavigateTo is not being called incorrectly. It has multiple overrides and the last parameter can be optional. If you press F12 when the cursor is positioned over the method name in the VS text editor, it will open a decompiled version of IApplication where you can see all of the overrides.

2. You cannot call NavigateTo from your dialog as is. Either close the dialog and move that logic in QuickVisitCommand or call RunModeless as [done here](https://github.com/stevencohn/OneMore/blob/bc072891e80ed3a513742a41a919f8a074ddd077/OneMore/Commands/Search/SearchCommand.cs#L31)

**Comment by stevencohn** [comment]
Alternatively, you might think about extending GotoFavoritesCommand which already provides basic substring searching. Do you really need fuzzy searching?

**Comment by stevencohn** [comment]
I added more information regarding the challenges of running in [the COM surrogate here](https://onedrive.live.com/redir?resid=6925D0374517D4B4%2158723&authkey=%21AN6SD9aiIbjQLi0&page=View&wd=target%28Developers.one%7C04d5a868-ef95-4e66-9d60-7a75f1029a31%2FTechNote%20-%20COM%20Surrogate%7C12b188b6-089f-422b-a15f-591490e11095%2F%29&wdorigin=703)

**Comment by valuex** [comment]
> Alternatively, you might think about extending GotoFavoritesCommand which already provides basic substring searching. Do you really need fuzzy searching?

Yes, with the feature of fuzzy search,one can visit any page with 3~5 strokes. This is of super convenience for non-English users. E.g. for Chinese users, he/she only needs to type the 3～5 first Pinyin letters of page title  and navigate to the specific page, without need to input 2~3 Chinese Characters, which takes more strokes.
As for the current Favorite feature, it is good. But I think it still adds extra burden for the user to memorize the alias name.
And the action of adding to Favorite could be smarter by two ways:
1. recording the visited times, more times visiting, the user likes it more.
2. record the input chars as the "alias name". Multiple "alias names" can point to the same page or section. Next time when the user type any of these previously input chars, he/she can visit the desired page quickly.

**Comment by valuex** [comment]
> OK.
> 
> 1. NavigateTo is not being called incorrectly. It has multiple overrides and the last parameter can be optional. If you press F12 when the cursor is positioned over the method name in the VS text editor, it will open a decompiled version of IApplication where you can see all of the overrides.
> 
> 2. You cannot call NavigateTo from your dialog as is. Either close the dialog and move that logic in QuickVisitCommand or call RunModeless as [done here](https://github.com/stevencohn/OneMore/blob/bc072891e80ed3a513742a41a919f8a074ddd077/OneMore/Commands/Search/SearchCommand.cs#L31)
>  

Thanks, I will try it.

**Comment by stevencohn** [comment]
BTW, if you need a Levenshtein distance algorithm, [see here](https://github.com/stevencohn/OneMore/blob/main/OneMore/Helpers/Extensions/StringExtensions.cs#L118)
