### ISSUE TITLE
Deleting Reminders not just completing them

### ISSUE THREAD

**Issue by eddymicro** [stevencohn/OneMore#939]
Hello,

I and trying to use the reminders. Creating them and completing them works fine.  However I do not want to keep all reminders for ever, I would like the option to delete them.  The only way I can delete a reminder is to delete the page.  It should be possible to delete the reminder.

Ed

**Comment by stevencohn** [comment]
Voila!

Make sure your text cursor is on the paragraph with the reminder tag

<img width="351" alt="image" src="https://user-images.githubusercontent.com/9964757/221418201-95701f1b-d03f-4e25-9087-c878fca9a294.png">

**Comment by eddymicro** [comment]
Stevencohn/Onemore,

Thanks!! Sorry I missed it.  I have been a OneNote user for more than 10
years, I think your enhancements are really great!

Ed

**Comment by eddymicro** [comment]
Stevencohn/Onemore,

I have been testing the reminders, I found another possible issue. I
realize there are limitations and reminders must be on one single physical
machine.  If I create a reminder on my home PC.  It will work as expected.
If I open that page on my office computer, the reminder will break and the
due date gets set back to the start date.  It's fine if the reminders only
work on one machine. But for users like myself that have both a home and
office machine, opening that page on another machine removes the reminder &
sets it's due date back to the start date.  I can reproduce this every
time.  Maybe you can't fix this but I thought I should let you know.

Create Reminder on Machine A
Open that page on Machine B
Go back to that page on Machine A, the due date is now the start date and
the reminder summary page shows nothing.

Regards,

Ed

**Comment by stevencohn** [comment]
@eddymicro Thanks for this. This sound similar to an issue I fixed a while back. Maybe it wasn't as fixed as I thought it was! I'll investigate.

**Comment by stevencohn** [comment]
Closing this, continuing work under #952
