### ISSUE TITLE
Feature Request: Add a view botton to show pages as mindmap

### ISSUE THREAD

**Issue by valuex** [stevencohn/OneMore#94]
One can get OneNote notebooks-sections-pages hirarchy in xml format.   
And generally mindmap are stored in or can be generated from xml file. 
For example, [Blumind](https://github.com/funwaywang/Blumind) is an open source software written in C#, and store its mindmap contents in xml file.
It would be **a thrilling feature** to have an addin for OneNote to show the pages in OneNote as mindmap.
So that users can have a macroscopic view of their notes.  
Kindly consider to implement this feature.   
Thanks again for your wonderful work on developing  OneMore.

**Comment by 1001QAdotNET** [comment]
I would like to subscribe to this request too
While this is cool and I would like to see it done I doubt it is entirely possible
I think I have seen an addon for this (never tried it) but my opinion is that mind mapping requires better visualization features than OneNote currently have
The native XML tree structure will limit this to a tree view but usually a mind in not necessarily a tree (from my experience with freeplane, freemind and others)

**Comment by stevencohn** [comment]
Interesting but might be ton of work to make it useful. I think generating a bitmap or jpg would be feasible but to make it really useful might mean being able to hyperlink pages to enable navigation or the ability to hover over a page "node" and see the last update timestamp... something like that.

I'm currently thinking more about syntax highlighting for programming languages... :-)

**Comment by valuex** [comment]
I've done this by myself, and the program is at https://github.com/valuex/NotesMap/releases/. Anyone instrested in this function may visit and have a try.

**Comment by stevencohn** [comment]
Thanks for that. I did take a look and it certainly gives an impressive view of your OneNote notebooks. For me, I think I have a modestly sized OneNote footprint. But the view didn't really seem more useful than the built-in OneNote navigation panels, which I usually have visible at all times - notebooks with sections an section groups on the left and pages on the right. Not to mention the section and section group tabs along the top.

So I have to say I'm still not sold on the idea of a mind map of your OneNote notebooks/sections/pages.

**Comment by valuex** [comment]
Thanks for your voice. I think the mindmap is especially useful for users at two conditions. One is that when he or she is building the outline of notes as a whole ; the second is for reviewing whether the note structure is intact or not. 
And what you said is right. At this moment, it's far from complete. More work is needed to make it useful and user-friendly.

**Comment by stevencohn** [comment]
One thing I think would make this magical is a map that shows the links between pages. Now you're talking about a mind map and not just an ontology

**Comment by stevencohn** [comment]
I [quite modestly] think my idea is brilliant! Brilliant, I say!! So it'll be part of the next release...

**Comment by 1001QAdotNET** [comment]
While it might be cool and look nice I am not sure if it will help a lot
How many of us have links between pages ...I have none, all of them are pointing to Internet

**Comment by stevencohn** [comment]
I certainly do and it's a view that you can't get otherwise

**Comment by 1001QAdotNET** [comment]
a mindmap implies hierarchy and a root topic
you could use a section as root but if the pages link to each other you have circular references and a graph that is not a tree anymore. If you are fine with that sure it is entirely possible

**Comment by stevencohn** [comment]
That's exactly my point. A hierarchical mind map of the a OneNote construct is no different than the hierarchical view presented by the OneNote navigation panes. The only advantage a mind map would have over the built-in panes is that pages are exploded in context of their sections. But you can still understand the structure of your OneNote information using the panes. If you're looking for a particular page, use searching and tagging.

Internal page links can show relationships between pages in a section, pages across sections, and even pages across notebooks. It could be enhanced to show broken links. While mind maps are defined as hierarchical, the brain actually is not and almost always thinks in a graph-like pattern. So a hierarchy is only a small part of a true "mind map".

I'll ask once again, what's the root of the feature request? What are you actually trying to do? Is a mind map the only way to solve the problem?

I'm digging in my heals here for two reasons: 1) mind mapping drags in a huge amount of code and logic to build and 2) it's impossible to make anything that is not just a static image and that would barely be useful. I'm always interested in usefulness vs. effort, ROI. And I just don't see it here, sorry

**Comment by 1001QAdotNET** [comment]
I am not the requester here and I don't think it is doable in a integrated way within OneNote
I have been using mindmapping heavily before OneNote
There is problems with the way you learn and traverse the material
While the brain is used to make connections between different areas of a mind map the perception (the learning and the reading) are still sequential so in that sense the minmap tends to introduce too many ways to split the attention 
The mapping part of the mindmap comes into play when memorizing the material and relies on the old habit of the hunter to map the territory and find his home back , educated ability. Voluntary learning, studying comes in later in the evolution of the 
human brain and requires structure order tags etc
So depending on which way you want to use the thing it should be OneNote (for learning) and OneMore MindMap for helping you with memorizing and getting the big picture. 

In our case if you need to map the structure of a section I could see some usefulness there in the sense that you could navigate the doc in a better way but it will not help any of the cognitive processes indicated above if more detailed info (beyond the title of the page and how it links to other pages) is not provided. So you will need to dive into outline elements and their children and have structure within those, children that are indented so you can mindmap them and with this we reach the reason behind my approach. I too have some ideas about mindmaping in relation with OneNote but that is just on the whiteboard and in a long list of projects somewhere at the end of the list
What I would do after having the structure I am already working with (indentation hierarchy) would be to translate this via a script or in your case via OneMore into a FreeMind or FreePlane XML file and find a way to go back and fort between the two in the sense that the two should be able to update each other (If I add more structure to OneNote I should be able to update FreeMind/Plane and viceversa) The problem with this is that a translation is needed between the objects specific to each domain (mind mapping and notetaking)
So yes in the above sense I see the usefulness of such an endeavor but ..as I said initially OneNote is not the right tool for this and an addon will have a long way to go. I would be glad if you can prove me wrong . IMHO this will be a project in itself as big as OneMore

**Comment by 1001QAdotNET** [comment]
`The native XML tree structure will limit this to a tree view but usually a mind in not necessarily a tree (from my experience with freeplane, freemind and others)` <-- this is what I said earlier
when I said the above I was referring to the OneNote internal structure
the mindpaing software I played with organizes the structure as tree but it uses links to make references to other areas of the tree which I did not believe it could be done via XML but I overlooked the links that could be used for that. So I hope I did not leave the impression I am contradicting myself here

**Comment by stevencohn** [comment]
Cheers for that
