### ISSUE TITLE
It is not possible to add just the rotating highlighter to the context menu-the entire Edit menu shows up there

### ISSUE THREAD

**Issue by CLITrees** [stevencohn/OneMore#940]
I would like to see only the rotating highlighter in the context menu
However when I try that I am being forced to select the Edit menu otherwise the rotating highlighter does not show up at all
So if I select the Edit menu then the entire menu shows up there. It would be pointless to have that in the context menu as it does not streamline or simplifies the workflow -you still need two clicks to get to it

**Comment by CLITrees** [comment]
PS: we should be allowed to delete our comments if nothing else was already posted in response (in my case I need to do that as I use this user for some personal repos related to work so I forgot to switch to my other user ID (or Edge which is a POS switched me to that because it saw that chrome uses that)

**Comment by stevenmcohn** [comment]
test

**Comment by stevencohn** [comment]
So this is a Github feature that I don't have control over but do you see the three-dot menu on the upper left of your comment? If you click it, do you see the Delete option?

<img width="232" alt="image" src="https://user-images.githubusercontent.com/9964757/221986311-129d408a-17fb-4745-bfad-1e1cbbe6cabc.png">

**Comment by stevencohn** [comment]
To answer the ticket question though... You should be able to add just the rotating highlighter in the context menu. The Edit menu is a separate option.

<img width="204" alt="image" src="https://user-images.githubusercontent.com/9964757/221986860-7b0ba51b-2679-488b-b903-d99ffaafe8fc.png">


should result in something like this...

<img width="244" alt="image" src="https://user-images.githubusercontent.com/9964757/221986734-bdae19b1-503f-4407-820b-79701e082c6d.png">

**Comment by CLITrees** [comment]
no that option is not available for the initial post just for the replies
Here is a gif showing you that the context Edit menu shows up even if not selected in Settings
[https://i.imgur.com/bYJrBSP.gif](url)

**Comment by stevenmcohn** [comment]
Ah OK, yeah, you cannot delete a post. Just the way Github works. You can close it and add a comment to delete it and I'll happily take care of it for you

**Comment by stevencohn** [comment]
Ah OK, yeah, you cannot delete a post. Just the way Github works. You can close it and add a comment to delete it and I'll happily take care of it for you

**Comment by stevencohn** [comment]
(and yes, I just added that comment under the wrong account, deleted it, and then re-added it with my personal account 😢  )

**Comment by stevencohn** [comment]
So is this ticket valid? Or shall I delete it?

**Comment by CLITrees** [comment]
Yes it a valid issue, leave it like this now (with that user)

**Comment by stevencohn** [comment]
OK then can you please provide any other details on how you set this up? As I mentioned above, I tried a couple of different ways of reproducing the issue but could not. I started with an empty context menu and added just Rotating Highlighter = OK. I also tried a populated context menu and added Rotating Highlighter = OK. So, what am I missing?

**Comment by CLITrees** [comment]
I have it running properly on OneNote16 but not on OneNote 15
There is nothing special , both OneNote versions are on 5.6.0 version of OneMore
