### ISSUE TITLE
Any way to make new pages automatically use the custom styles title font instead of OneNote's?

### ISSUE THREAD

**Issue by HauntedBunnies13** [stevencohn/OneMore#943]
I understand that (for whatever stupid reason) OneNote's default styles cannot be changed, outside of changing the default text, but is there anyway to automatically change the title font when I open a new page, like a macro or anything?

**Comment by stevencohn** [comment]
Unfortunately no.

A good alternative is to create a custom page template and set that as the new page default.

**Comment by HauntedBunnies13** [comment]
Ah, that sucks, but that workaround works well enough for me.

I really don't get why Microsoft doesn't give us more customizability.
