### ISSUE TITLE
Arm64 Native Build For Windows

### ISSUE THREAD

**Issue by intzaaa** [stevencohn/OneMore#945]
I am currently using a Windows PC with a Qualcomm Snapdragon processor, it has a very long battery life and is great for taking notes with OneNote.
I would like to be able to get a native build for arm64 in the release, thanks!

**Comment by Test-Acount** [comment]
Couldn't agree more!!!

**Comment by stevencohn** [comment]
I do not have access to an arm64 processor. Does the OneMore _not_ install on arm64? Sorry that I have no idea!

**Comment by huangyinhaow** [comment]
> I do not have access to an arm64 processor. Does the OneMore not install on arm64? Sorry that I have no idea!

@stevencohn OneMore runs fine on ARM64 computers, but it will slow down OneNote's startup and operation somewhat.

**Comment by stevencohn** [comment]
Have you tried the latest 5.8.4 version? This improves performance a bit.

Older versions would attempt to enable/disable menu items based on the content of the page. The Office Ribbon does not do this very efficiently so it slowed down the overall experience quite a bit. Version 5.8.4 removes that altogether so it performs noticeably better. Every command that needs a certain context is now responsible for testing that context when you run the command.

**Comment by huangyinhaow** [comment]
> Have you tried the latest 5.8.4 version? This improves performance a bit.
> 
> Older versions would attempt to enable/disable menu items based on the content of the page. The Office Ribbon does not do this very efficiently so it slowed down the overall experience quite a bit. Version 5.8.4 removes that altogether so it performs noticeably better. Every command that needs a certain context is now responsible for testing that context when you run the command.

Well, I will try it later!

**Comment by huangyinhaow** [comment]
> Have you tried the latest 5.8.4 version? This improves performance a bit.
> 
> Older versions would attempt to enable/disable menu items based on the content of the page. The Office Ribbon does not do this very efficiently so it slowed down the overall experience quite a bit. Version 5.8.4 removes that altogether so it performs noticeably better. Every command that needs a certain context is now responsible for testing that context when you run the command.

The speed of the latest version is much faster than the old version! Thanks

**Comment by stevencohn** [comment]
Closing this for now as it seems to be working for Arm64 users
