### ISSUE TITLE
Increase font size not working with 

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#95]
**Describe the bug**
Pressing Increase font size twice for the below line reverts the change

**To Reproduce**
select the text and press increase size twice

**Expected behavior**
font size should increase
**Screenshots**
<one:Page xmlns:one="http://schemas.microsoft.com/office/onenote/2013/onenote" ID="{xxx}" name="Increase font size bug" dateTime="2020-11-15T15:34:36.000Z" lastModifiedTime="2020-11-15T15:35:02.000Z" pageLevel="1" isCurrentlyViewed="true" selected="partial" lang="en-US">
  <one:QuickStyleDef index="0" name="PageTitle" fontColor="automatic" highlightColor="automatic" font="Calibri Light" fontSize="20.0" spaceBefore="0.0" spaceAfter="0.0" />
  <one:QuickStyleDef index="1" name="cite" fontColor="#595959" highlightColor="automatic" font="Calibri" fontSize="9.0" spaceBefore="0.0" spaceAfter="0.0" />
  <one:PageSettings RTL="false" color="automatic">
    <one:PageSize>
      <one:Automatic />
    </one:PageSize>
    <one:RuleLines visible="false" />
  </one:PageSettings>
  <one:Title lang="en-US">
    <one:OE alignment="left" quickStyleIndex="0">
      <one:T><![CDATA[Increase font size bug]]></one:T>
    </one:OE>
  </one:Title>
  <one:Outline selected="partial">
    <one:Position x="36.0" y="86.4000015258789" z="0" />
    <one:Size width="127.5765380859375" height="10.98630237579346" />
    <one:OEChildren selected="partial">
      <one:OE alignment="left" quickStyleIndex="1" selected="partial" style="font-family:Calibri;font-size:9.0pt;color:black">
        <one:T selected="all"><![CDATA[<span style='font-weight:bold'>How to write your code</span>]]></one:T>
      </one:OE>
    </one:OEChildren>
  </one:Outline>
</one:Page>

**Comment by stevencohn** [comment]
I tried to repro what you have here but the code you pasted isn't complete and what I was able to reconstruct doesn't seem to repro the problem.

In THIS github editor, you can click the Insert Code button and that may preserve the full fidelity of the XML better. Then I will hopefully be able to repro this.

**Comment by CLITrees** [comment]
I hope this time it is OK
`<one:Page xmlns:one="http://schemas.microsoft.com/office/onenote/2013/onenote" ID="{xxxxxxx}" name="Increase font size bug" dateTime="2020-11-15T15:34:36.000Z" lastModifiedTime="2020-11-16T04:39:33.000Z" pageLevel="1" isCurrentlyViewed="true" lang="en-US">
  <one:QuickStyleDef index="0" name="PageTitle" fontColor="automatic" highlightColor="automatic" font="Calibri Light" fontSize="20.0" spaceBefore="0.0" spaceAfter="0.0" />
  <one:QuickStyleDef index="1" name="cite" fontColor="#595959" highlightColor="automatic" font="Calibri" fontSize="9.0" spaceBefore="0.0" spaceAfter="0.0" />
  <one:PageSettings RTL="false" color="automatic">
    <one:PageSize>
      <one:Automatic />
    </one:PageSize>
    <one:RuleLines visible="false" />
  </one:PageSettings>
  <one:Title lang="en-US">
    <one:OE alignment="left" quickStyleIndex="0">
      <one:T><![CDATA[Increase font size bug]]></one:T>
    </one:OE>
  </one:Title>
  <one:Outline>
    <one:Position x="36.0" y="86.4000015258789" z="0" />
    <one:Size width="127.5765380859375" height="10.98630237579346" />
    <one:OEChildren>
      <one:OE alignment="left" quickStyleIndex="1" style="font-family:Calibri;font-size:9.0pt;color:black">
        <one:T><![CDATA[<span style='font-weight:bold'>How to write your code</span>]]></one:T>
      </one:OE>
    </one:OEChildren>
  </one:Outline>
</one:Page>`

**Comment by 1001QAdotNET** [comment]
`<one:Page xmlns:one="http://schemas.microsoft.com/office/onenote/2013/onenote" ID="{00FDB721-225B-4FC9-B584-29A1411F8A59}{1}{E1956411989552384493531984919497857738633261}" name="Increase font size bug" dateTime="2020-11-15T15:34:36.000Z" lastModifiedTime="2020-11-16T04:39:33.000Z" pageLevel="1" isCurrentlyViewed="true" lang="en-US">
  <one:QuickStyleDef index="0" name="PageTitle" fontColor="automatic" highlightColor="automatic" font="Calibri Light" fontSize="20.0" spaceBefore="0.0" spaceAfter="0.0" />
  <one:QuickStyleDef index="1" name="cite" fontColor="#595959" highlightColor="automatic" font="Calibri" fontSize="9.0" spaceBefore="0.0" spaceAfter="0.0" />
  <one:PageSettings RTL="false" color="automatic">
    <one:PageSize>
      <one:Automatic />
    </one:PageSize>
    <one:RuleLines visible="false" />
  </one:PageSettings>
  <one:Title lang="en-US">
    <one:OE alignment="left" quickStyleIndex="0">
      <one:T><![CDATA[Increase font size bug]]></one:T>
    </one:OE>
  </one:Title>
  <one:Outline>
    <one:Position x="36.0" y="86.4000015258789" z="0" />
    <one:Size width="127.5765380859375" height="10.98630237579346" />
    <one:OEChildren>
      <one:OE alignment="left" quickStyleIndex="1" style="font-family:Calibri;font-size:9.0pt;color:black">
        <one:T><![CDATA[<span style='font-weight:bold'>How to write your code</span>]]></one:T>
      </one:OE>
    </one:OEChildren>
  </one:Outline>
</one:Page>`
I hope this time it is OK

**Comment by stevencohn** [comment]
https://github.com/stevencohn/OneMore/releases/tag/3.8.1

Note that it's not perfect. If you select a sentence in a paragraph, the entire paragraph will be affected

**Comment by 1001QAdotNET** [comment]
Ups, I did not notice that,  I am doing most of the pre-preocessing in Word where I can use select all the text with similar formatting and then I change the format for all the occurrences of that style.

Not sure if your comment is implying that you will fix the resizing for the entire paragraph. 
I can confirm that now pressing twice "Increase font size" works as expected

**Comment by stevencohn** [comment]
I may or may not fix it but it's not a "bug" :-)

**Comment by 1001QAdotNET** [comment]
Got it ! OK not a problem for me 
I am closing this one as the main issue raised here was addressed, thank you!
