### ISSUE TITLE
Clear Searched Page Tags

### ISSUE THREAD

**Issue by Cossackx** [stevencohn/OneMore#955]
# Problem to Solve
Clear Searched Page Tags

No way to purge the list of previously searched page tags.
# To Reproduce
![image](https://user-images.githubusercontent.com/121278003/222984895-59b2f3bd-7a6f-4780-9fe7-99a4c2fcf373.png)

# Expected Behavior

# Screenshots

# Environment (if applicable)

 - OneNote Version: [e.g. Office 2019, O365, also 32bit or 64bit?]
 - OneMore Version [e.g. 3.4 - from the About dialog or from the log file]

# Additional Context

Add any other context about the problem here. Attach page XML file or the app log file as appropriate. You can find the log file here: %localappdata%\temp\OneMore.log

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
Changing to a feature request since this is currently working as designed. The search history is provided as a convenient way to reproduce earlier searches. But I understand why one might want to clear the list as well.

**Comment by stevencohn** [comment]
I haven't been in this part of the code in years, so I apologize for the confusion.

This is not a list of recent search history. This is a list of tags that actually exist and are currently used on pages you've specified.

So it really is a convenient way of finding pages with a combination of one or more of these existing tags.
