### ISSUE TITLE
OneMore 5.7.2 doesn't do anything after install

### ISSUE THREAD

**Issue by hooligannes** [stevencohn/OneMore#959]
# Problem to Solve

Onemore does not work at all.

# To Reproduce

1. Install Onemore addin 5.7.2 and start OneNote
2. Click on any Onemore ribbon item
3. Nothing happens

# Expected Behavior
I expected features to work.

# Environment (if applicable)
 - OneNote Version: 2302 Build 16130.20186  O365 for Business 64bit
 - OneMore Version 5.7.2

# Additional Context

Onemore installed to "C:\Program Files\River\OneMoreAddIn"

The resulting messages in the application event log are:

> Product: OneMoreAddIn -- Installation completed successfully.

and

> Windows Installer installed the product. Product Name: OneMoreAddIn. Product Version: 5.7.2. Product Language: 1033. Manufacturer: River. Installation success or error status: 0.

Environment %temp% and %tmp% directories point to "F:\temp" and "F:\tmp" respectively
No "OneMore.log" file at those locations. Neither at "%localappdata%\temp\"

There isn't a settings file at %Appdata%\OneMore
All registry entries are present.
Environment %temp% and %tmp% directories point to "F:\temp" and "F:\tmp" respectively
There is a setup OneMoreSetup.log at "C:\Windows\SystemTemp" from a previous failed attempt last year. It seems I ran it with elevated permissions. That attempt kept showing the "OneMore failed to connect to OneNote" error.

[OneMoreSetup.log](https://github.com/stevencohn/OneMore/files/10904651/OneMoreSetup.log)

Below is the output from IQ.ps1
```
Versions...
OK Office version is 16.0
OK OneNote version is 15.0

AppID...
OK Registry::HKEY_CLASSES_ROOT\AppID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}

Root...
OK Registry::HKEY_CLASSES_ROOT\onemore

Shell...
OK Registry::HKEY_CLASSES_ROOT\onemore\shell\open\command
VERBOSE: "C:\Program Files\River\OneMoreAddIn\OneMoreProtocolHandler.exe" %1 %2 %3 %4 %5

AddIn...
OK Registry::HKEY_CLASSES_ROOT\River.OneMoreAddIn
OK Registry::HKEY_CLASSES_ROOT\River.OneMoreAddIn.1

CLSID...
OK Registry::HKEY_CLASSES_ROOT\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}
OK Registry::HKEY_CLASSES_ROOT\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\InprocServer32
OK Registry::HKEY_CLASSES_ROOT\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\InprocServer32\5.7.2.0
VERBOSE: Assembly = River.OneMoreAddIn, Version=5.7.2.0, Culture=neutral, PublicKeyToken=null
VERBOSE: CodeBase = C:\Program Files\River\OneMoreAddIn\River.OneMoreAddIn.dll
VERBOSE: RuntimeVersion = runtimeVersion
VERBOSE: Class = River.OneMoreAddIn.AddIn
OK Registry::HKEY_CLASSES_ROOT\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\ProgID
OK Registry::HKEY_CLASSES_ROOT\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\Programmable
OK Registry::HKEY_CLASSES_ROOT\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\TypeLib
OK Registry::HKEY_CLASSES_ROOT\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\VersionIndependentProgID

User...
OK Registry::HKEY_CURRENT_USER\SOFTWARE\Classes\AppID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}
OK Registry::HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\OneNote\AddIns\River.OneMoreAddIn
OK Registry::HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\River.OneMoreAddIn.dll
VERBOSE: C:\Program Files\River\OneMoreAddIn\River.OneMoreAddIn.dll
OK Registry::HKEY_CURRENT_USER\SOFTWARE\Policies\Microsoft\Office\16.0\Common\Security\Trusted Protocols\All Applications\onemore:

WebView2...
OK Registry::HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}
OK location = C:\Program Files (x86)\Microsoft\EdgeWebView\Application
VERBOSE: version = 110.0.1587.63
VERBOSE: location = C:\Program Files (x86)\Microsoft\EdgeWebView\Application
```

**Comment by julie777** [comment]
I have the same problem. I select install and the dialog closes and nothing happens.
Here is my log
```
01| Starting dllhost 17032, CPU=2904Mhz, en-US/en-US, v5.7.2, OneNote 15.0, Office 16.0, 2023-03-15 11:39
01| ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.16130.20218)
01| ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
01| ..OneAddInsUpdate(custom[])
01| ..building ribbon
01| ..building ribbon colorizer commands
01| ..building ribbon groups
01| ..building context menu
01| ..OnStartupComplete(custom[])
01| ..starting command service
01| ..starting reminder service
01| ..ready
03| defining 149 hotkeys for input locale 1033
07| Running command UpdateCommand
14| ..downloading MSI from https://github.com/stevencohn/OneMore/releases/download/5.8.2/OneMore_5.8.2_Setupx64.msi
14| ..creating install script C:\Users\julie\AppData\Local\Temp\OneMoreInstaller.ps1
```


I thought that I would do a little debugging.
The install script and the new install package were created in my temp directory.
The contents of the install script OneMoreInstaller.ps1 is
```
$guid = '{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}';
$processId = gcim Win32_Process | select ProcessId, CommandLine | where { $_.CommandLine -and $_.CommandLine.Contains($guid) } | foreach { $_.ProcessId }
if ($processId) { taskkill /pid $processId /f }
$processId = gcim Win32_Process | select ProcessId, Name | where { $_.Name -eq 'ONENOTE.EXE' } | foreach { $_.ProcessId }
if ($processId) { taskkill /fi 'pid gt 0' /im ONENOTE.exe /t /f }

C:\Users\julie\AppData\Local\Temp\OneMore_5.8.2_Setupx64.msi

```

**Comment by stevencohn** [comment]
I'm having a hard time reproducing this. Tried on three machines, one with an AD domain account, all with various level of UAC enabled. 2300 people have downloaded 5.8.2. I've only heard of four cases of installer failures.

I don't have enough information to reproduce and understand the issue. So for the few that sadly encounter this, and until I have more info, the best alternative is to close OneMore, download the installer, and run it manually.

**Comment by stevencohn** [comment]
My plan is avoid PowerShell altogether and instead run `OneMoreSetupActions.exe --uninstall-shutdown` in its place from Update.cs

**Comment by stevencohn** [comment]
@julie777 or @hooligannes If you're willing, I've uploaded an "Omega" build of 5.7.2 here https://github.com/stevencohn/OneMore/releases/tag/5.7.2

It doesn't use PowerShell at all. I'm very curious whether it works in your environments.

I'll incorporate this into the next (5.8.3) release. But, as before, it won't actually apply until you upgrade FROM 5.8.3 to a later release.

**Comment by hooligannes** [comment]
Here's one more detail.
I ran the omega version after uninstalling 5.8.2. The result was the same.
I tried a repair from the installer and this time I received the attached alert:
![image](https://user-images.githubusercontent.com/21229702/225625359-c74c3c42-bb4b-4226-903c-0caf7487d46a.png)

**Comment by stevencohn** [comment]
Yes, up until now, all of my systems have enabled unsigned PowerShell scripts since I do a lot of PowerShell scripting myself. So maybe that's why I haven't run into the issue with 5.7.2. 

The Omega build (OneMore_5.7.2_Setupx64-Omega.msi) doesn't use PowerShell. I haven't had a chance to build up a default Win 10 environment to try it out yet but will as soon as I can.

**Comment by stevenmcohn** [comment]
Thank you for trying. I'll set up a base virtual machine this weekend and do some debugging.

**Comment by stevenmcohn** [comment]
I think it's time to buy a new computer ;-) Just kidding, I'll take a look at the logs. Thanks

**Comment by hooligannes** [comment]
I can try in the laptop.

**Comment by stevencohn** [comment]
If you do, please try to enable MSI logging by following [the steps on this page](https://onedrive.live.com/redir?resid=6925D0374517D4B4%2158723&authkey=%21AN6SD9aiIbjQLi0&page=View&wd=target%28Getting%20Started.one%7Cd1eaf02b-5881-42a1-a83b-df7fe2f7f1af%2FTroubleshooting%7C1d621b93-d8b5-41a7-b9cc-66be3b662b71%2F%29&wdorigin=NavigationUrl) under OneMore Installer Problems.

> If the installer fails and the cause isn't clearly evident, enable MSI logging. Open the registry by using Regedit.exe, and then create the following subkey and keys:  


> * Path: HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\Installer 
> * Type: Reg_SZ 
> * Value: Logging 
> * Data: voicewarmupx 

>  
> When the installer runs, it will generate a log file in the %TEMP% folder named something like MSI1234.log

**Comment by hooligannes** [comment]
The laptop already has OneMore. I haven't done anything there beyond installing OneMore last year, back then I got the same symptoms and results.
My main PC already had MSI logging enabled. FInd it attached.
BTW, in my main PC the path to the log is %TMP% **not** %TMP%
[MSI29d76.LOG](https://github.com/stevencohn/OneMore/files/10996662/MSI29d76.LOG)

**Comment by hooligannes** [comment]
PS execution policy does not seem to be a cause. My user has the Unrestricted policy applied.
The issue appeared originally in my laptop. where it never worked.
In my main PC, I installed a version from the 4.X.X  I think that one did not work. but later ones did, probably v5.0.0 or 5.1.2. Then, after an Office or Windows update it stopped working.

**Comment by hooligannes** [comment]
One more clue. The settings file never gets created. The path is not **%Appdata%/Onemore** but **%Appdata%/ROaming/OneMore**

**Comment by stevencohn** [comment]
Which version of Windows are you running. On Windows 11, `%appdata%` is defined as `C:\Users\username\AppData\Roaming`

**Comment by hooligannes** [comment]
Windows 10.

Cordialmente,

Néstor Sánchez
Senior Partner

NES interactivos
ayudamos a tu empresa a crecer
________________________________

**Comment by hooligannes** [comment]
Hi Steve. I see the issue as completed. Can you please comment your plans? Should I uninstall until the next release is out? Thanks for your help.

**Comment by stevencohn** [comment]
> Update: BTW, I applied 8.4.2 and the problem remains. Nothing happens at all when I click on OneMore menu items.

Which version? the latest is 5.8.4. Are you saying it did install completely. OneMore is loading in OneNote and showing its buttons on the ribbon? But none of the buttons work? That sounds like a different problem. Can you upload your OneMore.log file please?

**Comment by Blumio** [comment]
I have exaclty the problem you describe. The icons are visible, but nothing happens when i click them. I just want to extract my images from a oneNote page by using your feature to export as html and then getting the images from the dedicated folder. 

I installed with OneMore_5.9.0_Setupx64.msi and the installation completed without errors. I don´t know where i can find the log you are talking about though.

**Comment by stevencohn** [comment]
Hi @Blumio.

The runtime log file is %TEMP%\OneMore.log (on Windows 11, this translates to C:\Users\USERNAME\AppData\Temp\OneMore.log where USERNAME is your username.

The installer create a log file in the same directory called OneMoreSetup.log
