### ISSUE TITLE
Regional using "," instead of "." not supported

### ISSUE THREAD

**Issue by zetoken** [stevencohn/OneMore#96]
**Describe the bug**
When Windows regional configuration does not use "." as a decimal separator then it throws this exception:
```
19628:1] Running command ApplyStylesCommand
19628:1] Error running command ApplyStylesCommand
19628:1] EXCEPTION - System.FormatException
Message...: Le format de la chaîne d'entrée est incorrect.
StackTrace:    à System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   à System.Double.Parse(String s)
   à River.OneMoreAddIn.Style.ParseFontSize(String size)
   à River.OneMoreAddIn.Style.ReadCss(String css)
   à River.OneMoreAddIn.Style..ctor(String css)
   à River.OneMoreAddIn.Stylizer.Clear(XElement element, Clearing clearing)
   à River.OneMoreAddIn.ApplyStylesCommand.ClearInlineStyles(String index, Boolean paragraph)
   à River.OneMoreAddIn.ApplyStylesCommand.ApplyStyles(List`1 styles)
   à River.OneMoreAddIn.ApplyStylesCommand.Execute(Object[] args)
   à River.OneMoreAddIn.CommandFactory.Run[T](Object[] args)
TargetSite: [mscorlib] System.Number::ParseDouble()
```

**To Reproduce**
1. Use "Français (France)" as the regional format
2. Click on "Apply Styles to Page"
3. See the error in the log

**Expected behavior**
Should not throw :).

**Environment (if applicable):**
From the log file:
`19628:1] Starting dllhost 19628, fr-FR/fr-FR, v3.8.1, OneNote 15.0, Office 16.0`

**Additional context**
`Double.Parse` should be aware of the current culture in `Style.ParseFontSize` method.

**Comment by stevencohn** [comment]
https://github.com/stevencohn/OneMore/releases/tag/3.8.2

**Comment by stevencohn** [comment]
I also included French translations, with my usual caveat:

Please note that translations were automated using my ResxTranslator utility against the Google translation engine. My apologies if there are any inaccurate translations. Let me know the proper translations and I'll fix them immediately. Thanks for your understanding.

**Comment by zetoken** [comment]
Thank you!

I can apply the default styles.
But I can"t edit existing one nor create a new one. This exception occurs:
```
************** Texte de l'exception **************
System.FormatException: Le format de la chaîne d'entrée est incorrect.
   à System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   à System.Double.Parse(String s)
   à River.OneMoreAddIn.StyleDialog.ShowSelection()
   à River.OneMoreAddIn.StyleDialog.StyleDialog_Shown(Object sender, EventArgs e)
   à System.Windows.Forms.Form.OnShown(EventArgs e)
   à System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   à System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   à System.Windows.Forms.Control.InvokeMarshaledCallbacks()
```
Similar problem in another part of the code.

I can't see any french language (my computer in set in french, Office too but all the menu items are written in english). Is there a setting to activate it?

**Comment by stevencohn** [comment]
Sorry. I'll keep testing/fixing/testing...

**Comment by stevencohn** [comment]
https://github.com/stevencohn/OneMore/releases/tag/3.8.3

Should be working now and include French translations... with the same caveat as above, I used Google translate so please forgive any odd translations.

**Comment by zetoken** [comment]
Excellent job, it looks fine now.
I'll contribute with a pull request if some google translations to French are bad.
