### ISSUE TITLE
what is the "My reading list“ in OneMore 5.8.2?

### ISSUE THREAD

**Issue by zhongguocn** [stevencohn/OneMore#961]
I just updated to onemore5.8.2. The `Navigator` is very good! Thank you.
There is a "`My Reading List`" area in the `Navigator` panel, which is always blank. What is displayed here? How can I display the page here?

**Comment by jasonjac2** [comment]
It is like your favourites.  There is a button on the History to copy the selected item to the My Reading List.  You can build up a list of pages that you always want at hand, e.g. things you should be reading or pages to return to.  There is a cross over with Favourites and I guess one day they may merge.
See:  [Navigator](https://onedrive.live.com/redir?resid=6925D0374517D4B4%2158723&authkey=%21AN6SD9aiIbjQLi0&page=View&wd=target%28The%20Basics.one%7Cf2cc1a14-be59-4df4-8ade-d330363d3296%2F[Navigator](https://github.com/stevencohn/OneMore/issues/961)%7C585812bb-9822-431a-afac-06c1a03e47bd%2F%29&wdorigin=703
) from the docs.

**Comment by zhongguocn** [comment]
I installed onemore on three computers for testing, and the results are all the same.
There are no buttons on the panel。
windows 11 , Office 365

![image](https://user-images.githubusercontent.com/38025627/223746566-c2233957-343a-42f7-a3e6-a22b97ba7db2.png)

**Comment by stevencohn** [comment]
Thanks for this report. I'm guessing the buttons are actuallly there if you move your mouse over the area, you should see a gray box appear. (Not OK, I realize.)

I believe I know why and will address this as soon as possible.

**Comment by jasonjac2** [comment]
for the record - I can see them in W10, OneMore: 5.8.2.  I can see you don't.
"It is recommended not to combine "My reading list" and Favorites, because I need to easily view relevant pages in my work, which are not always consistent with Favorites." agreed for some / most. 
Cheers,

**Comment by stevenmcohn** [comment]
What I'm considering for the next iteration is something like a new button to "Add selected to Favorites"; the Nav lists still remain independent but you can choose to promote items from the Nav window to your favorites list.

**Comment by stevencohn** [comment]
What I'm considering for the next iteration is something like a new button to "Add selected to Favorites"; the Nav lists still remain independent but you can choose to promote items from the Nav window to your favorites list.

**Comment by zhongguocn** [comment]
> What I'm considering for the next iteration is something like a new button to "Add selected to Favorites"; the Nav lists still remain independent but you can choose to promote items from the Nav window to your favorites list.

Very good. This should improve efficiency.
One suggestion: Can you set the Nav window as follows:
When browsing the OneNote page, quickly scroll the mouse to display the Nav window at the top. After the user clicks the directory in the Nav window, the window disappears after 3 seconds.
If the Nav window is set to translucent, it will be more beautiful.

**Comment by jasonjac2** [comment]
Hi, I like the idea of the auto fade, but sometimes I want it to stay up, other times I want it to go away.  I often need to refer to long pages and jump around a lot, so one of the key usages to me is having the current page Table of Contents always there to see.

What do you mean by: "quickly scroll the mouse to display the Nav window at the top. "

JAC

**Comment by zhongguocn** [comment]
>  What do you mean by: "quickly scroll the mouse to display the Nav window at the top. "
> JAC

I mean: when the user quickly scrolls the mouse wheel, he must be looking for a chapter in the long page. If the Nav window can appear automatically at this time, it will make users feel very considerate.
Of course, some people may not like it. You can set an option to turn it on or off.

**Comment by jasonjac2** [comment]
Ah I see, I am not sure that OM can pick up on that kind of movement - I like it, in the same way as I like gestures.  For me I try and really reduce Mouse use, but I certainly see the benefit.  We just need to not bring back "clippy" :-)  Copyright abused I am sure: 
![image](https://user-images.githubusercontent.com/68282090/224005091-9dd78be5-85e5-4507-8345-e941bb50f89e.png)

**Comment by koppor** [comment]
@stevencohn Thank you so much for the Navigator! This is what I always wanted. Now, I will use headings in OneNote! (for sure, it would be great if the Navigator was put inside OneNote to have easier Window Management. Thanks to [FancyZones](https://learn.microsoft.com/en-us/windows/powertoys/fancyzones), this is not that hard)

I just commented for the Googlers. Google should find this (or similar pages) for "OneNote TOC". For a TOC aside of the current page, the Navigator is **the** solution. 🏆
