### ISSUE TITLE
when OneMore says "you need to restart ON" on changes, it only closes this instance.

### ISSUE THREAD

**Issue by jasonjac2** [stevencohn/OneMore#963]
# Problem to Solve
You change a onemore setting (in this case a hotkey) from OM settings.  You OK and it says: "
---------------------------
OneMore
---------------------------
One or more changes require OneNote to be restarted. Do you want to restart OneNote now?
---------------------------
Yes   No   
---------------------------

if you say "yes", then it only closes and re-opens that one instance.  If you have multiple instances open, they stay open and the change doesn't take effect until the next full close.

V minor. 

# To Reproduce

See above.

# Expected Behavior

close all instances

# Screenshots

NA

# Environment (if applicable)
5.82 OneMore

# Additional Context

Add any other context about the problem here. Attach page XML file or the app log file as appropriate. You can find the log file here: %localappdata%\temp\OneMore.log

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
Best I can do at this time when more than one OneNote window is open is to tell the user "Multiple OneNote window are open. Close these windows and restart OneNote to apply new settings."
