### ISSUE TITLE
Cannot add code block / info block / warn block / small calendar

### ISSUE THREAD

**Issue by DrGierth** [stevencohn/OneMore#97]
First of all, thank you for providing this Addon for OneNote! Michael

**Describe the bug**
Cannot add code block / info block / warn block / small calendar. Nothing happens

**To Reproduce**
Use Commands from ribbon or context menu  

**Expected behavior**
The targeted snippets should appear.

**Screenshots**

**Environment (if applicable):**
 - OneNote Version: [e.g. Office 2019, O365, also 32bit or 64bit?]
![grafik](https://user-images.githubusercontent.com/12048733/99665941-9636b600-2a6a-11eb-9443-dd9997880b62.png)

 - OneMore Version [e.g. 3.4 - from the About dialog]
![grafik](https://user-images.githubusercontent.com/12048733/99666078-c3836400-2a6a-11eb-9a39-a04e3c516771.png)

**Additional context**
[OneMore.log](https://github.com/stevencohn/OneMore/files/5566716/OneMore.log)

**Comment by stevencohn** [comment]
Sorry about that. Darn programming! Miss one line of code and people tend to notice :-(

https://github.com/stevencohn/OneMore/releases/tag/3.8.4

**Comment by DrGierth** [comment]
Thank you for beeing so fast, Michael
