### ISSUE TITLE
Remove empty lines from the selected text

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#98]
**Is your feature request related to a problem? Please describe.**
Very often when I copy and paste text in OneNote I find empty lines that are not in the original text
They could be spacing added via other means in the original text but they get translated to lines that have to be manually deleted

**Describe the solution you'd like**
Allow the user to remove empty lines from the selected text

**Describe alternatives you've considered**
I am not sure if there is already this functionality under the Clean menu, I hve tested everything there but nothing worked

**Comment by stevencohn** [comment]
The third item, "Remove empty paragraphs and headers" will remove **repeated** empty lines between paragraphs, leaving a single empty line between paragraphs. It does this for the entire document, not for a selected region. There is no option currently to remove all empty lines between paragraphs entirely

**Comment by 1001QAdotNET** [comment]
The empty lines could be within a div as well, not just between paragraphs
I did try that feature and it left the text unchanged

**Comment by stevencohn** [comment]
There are not DIVs in OneNote desktop. Do you mean a soft-break within a paragraph? I wouldn't be able to tell which ones are intentional and which ones are arbitrary. And sometimes, OneNote just does what it does and I can't force it to do otherwise but I can take a look.

**Comment by 1001QAdotNET** [comment]
Yes sorry, within a One:T element
Still used to OneNote REST API with returns you HTML ...

Here is an example
<one:Page xmlns:one="http://schemas.microsoft.com/office/onenote/2013/onenote" ID="{xxxxxx}" name="Where does it come from?" dateTime="2020-11-25T14:10:25.000Z" lastModifiedTime="2020-11-25T14:26:42.000Z" pageLevel="1" isCurrentlyViewed="true" selected="partial" lang="en-US">
  <one:QuickStyleDef index="0" name="PageTitle" fontColor="automatic" highlightColor="automatic" font="Calibri Light" fontSize="20.0" spaceBefore="0.0" spaceAfter="0.0" />
  <one:QuickStyleDef index="1" name="p" fontColor="automatic" highlightColor="automatic" font="Calibri" fontSize="11.0" spaceBefore="0.0" spaceAfter="0.0" />
  <one:PageSettings RTL="false" color="automatic">
    <one:PageSize>
      <one:Automatic />
    </one:PageSize>
    <one:RuleLines visible="false" />
  </one:PageSettings>
  <one:Title lang="en-US">
    <one:OE alignment="left" quickStyleIndex="0">
      <one:T><![CDATA[]]></one:T>
    </one:OE>
  </one:Title>
  <one:Outline selected="partial">
    <one:Position x="36.0" y="86.4000015258789" z="0" />
    <one:Size width="490.8226623535156" height="106.3770751953125" />
    <one:OEChildren selected="partial">
      <one:OE alignment="left" spaceAfter="7.5" spaceBetween="18.0" quickStyleIndex="1">
        <one:T style="font-family:Calibri;font-size:18.0pt;&#xA;color:black"><![CDATA[Where does it come from?]]></one:T>
        <one:OEChildren>
          <one:OE alignment="left" quickStyleIndex="1" style="font-family:Calibri;font-size:10.5pt;color:black">
            <one:T><![CDATA[Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-]]></one:T>
          </one:OE>
        </one:OEChildren>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="1" selected="partial">
        <one:T style="font-family:Calibri;font-size:10.5pt;color:black"><![CDATA[]]></one:T>
        <one:OEChildren selected="partial">
          <one:OE alignment="left" quickStyleIndex="1" selected="partial" style="font-family:Calibri;font-size:10.5pt;color:black">
            <one:T><![CDATA[The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from &quot;de Finibus Bonorum et Malorum&quot; by Cicero are also reproduced in their exact original form, accompanied b]]></one:T>
            <one:T selected="all"><![CDATA[y]]></one:T>
            <one:T><![CDATA[ English versions from the 1914 translation by H. Rackham.]]></one:T>
          </one:OE>
        </one:OEChildren>
      </one:OE>
    </one:OEChildren>
  </one:Outline>
</one:Page>

**Comment by stevencohn** [comment]
Looks like a duplicate now of #99
