### ISSUE TITLE
Onemore not loading in Onenote anymore

### ISSUE THREAD

**Issue by edogd** [stevencohn/OneMore#980]
I think OneNote got updated today to version:
Microsoft® OneNote® for Microsoft 365 MSO (16.0.14326.20504) 64-bit 

After which the onemore plugging stopped showing up.  I have uninstalled and reinstalled version 5.8.2 and several other other versions of onemore and nothing works.

For each version, the installation completes successfully.  However, when I see that onemore is not up in onenote, I check the COM Add-in section in the Options.  I see the following
![image](https://user-images.githubusercontent.com/46937458/226071644-d64e98e4-0015-4fc4-bdfa-6da2d3b9f581.png)

How else can I debug this?

**Comment by stevencohn** [comment]
Please see the [Troubleshooting page here](https://onedrive.live.com/redir?resid=6925D0374517D4B4%2158723&authkey=%21AN6SD9aiIbjQLi0&page=View&wd=target%28Getting%20Started.one%7Cd1eaf02b-5881-42a1-a83b-df7fe2f7f1af%2FTroubleshooting%7C1d621b93-d8b5-41a7-b9cc-66be3b662b71%2F%29&wdorigin=NavigationUrl
)

**Comment by stevencohn** [comment]
I'm not even sure where that build came from. I don't see it listed anywhere on the [Office Release site](https://learn.microsoft.com/en-us/officeupdates/release-notes-microsoft365-apps) The closest match I could find near that build number is from 2021.

For example my build, updated last week, is Microsoft® OneNote® 2021 MSO (Version 2302 Build 16.0.16130.20298) 64-bit

**Comment by edogd** [comment]
### Log file
The log file seems to be old (ie before the OneNote update) per the modification date. I deleted it and reran onenote, but no new log file was created.

### OneMoreSetup.log
I checked OneMoreSetup.log and saw the following

```
======================================================================
starting action: --install .. 3/20/2023 12:00:08 PM
Installer architecture (x64), OS architecture (x64), requesting (x64)
OneMore installer running as user NT AUTHORITY\SYSTEM (S-1-5-18) elevated

Register... version 5.8.2

ShutdownOneNoteAction.Install ---
failed to run termination step of StopHost()
System.Management.ManagementException
Message: Invalid class 
Source: System.Management
StackTrace:    at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at System.Management.ManagementObjectCollection.get_Count()
   at OneMoreSetupActions.ShutdownOneNoteAction.StopHost()
TargetSite: [System.Management] System.Management.ManagementException::ThrowWithExtendedInfo()

install completed suspiciously

--------------------------------------------------
reentry action: --install-registrywow .. 3/20/2023 12:00:09 PM
OneMore installer running as user NT AUTHORITY\SYSTEM (S-1-5-18) elevated

RegistryWowAction.Install --- x64:True
1st chance, could not read CLSID or key missing
2nd chance, read CLSID ({DC67E480-C3CB-49F8-8232-60B0C2056C8E})
read path from LocalServer32 (C:\Program Files\Microsoft Office\Root\Office16\ONENOTE.EXE)
detected 64-bit install
WOW cloning not required

--------------------------------------------------
reentry action: --install-activesetup .. 3/20/2023 12:00:09 PM
OneMore installer running as user NT AUTHORITY\SYSTEM (S-1-5-18) elevated

ActiveSetupAction.Install ---
replacing '5.8.2' with '5,8,2'
```

"Install competed suspiciously" is the only strange thing I see.

### dllhost status
Task manager does show a dllhost process with /Processid:{88aba....

### iq.ps1 Output

```
Versions...
OK Office version is 16.0
OK OneNote version is 15.0 (64-bit)

AppID...
OK Registry::HKEY_CLASSES_ROOT\AppID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}

Root...
key not found: Registry::HKEY_CLASSES_ROOT\onemore
BAD Registry::HKEY_CLASSES_ROOT\onemore

Shell...
key not found: Registry::HKEY_CLASSES_ROOT\onemore\shell\open\command
BAD Registry::HKEY_CLASSES_ROOT\onemore\shell\open\command
VERBOSE:

AddIn...
OK Registry::HKEY_CLASSES_ROOT\River.OneMoreAddIn
OK Registry::HKEY_CLASSES_ROOT\River.OneMoreAddIn.1

CLSID...
OK Registry::HKEY_CLASSES_ROOT\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}
OK Registry::HKEY_CLASSES_ROOT\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\InprocServer32
OK Registry::HKEY_CLASSES_ROOT\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\InprocServer32\5.8.2.0
VERBOSE: Assembly = River.OneMoreAddIn, Version=5.8.2.0, Culture=neutral, PublicKeyToken=null
VERBOSE: CodeBase = C:\Program Files\River\OneMoreAddIn\River.OneMoreAddIn.dll
VERBOSE: RuntimeVersion = v4.0.30319
VERBOSE: Class = River.OneMoreAddIn.AddIn
OK Registry::HKEY_CLASSES_ROOT\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\ProgID
OK Registry::HKEY_CLASSES_ROOT\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\Programmable
OK Registry::HKEY_CLASSES_ROOT\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\TypeLib
OK Registry::HKEY_CLASSES_ROOT\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\VersionIndependentProgID

User...
OK Registry::HKEY_CURRENT_USER\SOFTWARE\Classes\AppID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}
bad value: Registry::HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\OneNote\AddIns\River.OneMoreAddIn\LoadBehavior, '2' <> '3'
OK Registry::HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\OneNote\AddIns\River.OneMoreAddIn
OK Registry::HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\River.OneMoreAddIn.dll
VERBOSE: C:\Program Files\River\OneMoreAddIn\River.OneMoreAddIn.dll
key not found: Registry::HKEY_CURRENT_USER\SOFTWARE\Policies\Microsoft\Office\16.0\Common\Security\Trusted Protocols\All Applications\onemore:
BAD Registry::HKEY_CURRENT_USER\SOFTWARE\Policies\Microsoft\Office\16.0\Common\Security\Trusted Protocols\All Applications\onemore:

WebView2...
OK Registry::HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}OK location = C:\Program Files (x86)\Microsoft\EdgeWebView\Application
VERBOSE: version = 111.0.1661.44
VERBOSE: location = C:\Program Files (x86)\Microsoft\EdgeWebView\Application
```

It appears the installer not working?

**Comment by stevencohn** [comment]
Interesting. What version of Windows do you have, as it shows in Settings/System/About?

<img width="453" alt="image" src="https://user-images.githubusercontent.com/9964757/226445499-7efba6f9-b1bf-4395-8a59-e7a994f30802.png">

**Comment by edogd** [comment]
Windows 10 Enterprise
Version: 20H2
7/7/2021
OS build: 19042.2728

**Comment by stevencohn** [comment]
I was able to test on Win10 22H2 Pro and that worked OK.
I wasn't able to install win10 20H2 Enterprise from July 2021.

Since this is Win 10 Enterprise, is this controlled by your company? Could they have added some blocking group policy?

**Comment by edogd** [comment]
It's possible that something was added to block it.  Is there a way to check?

**Comment by edogd** [comment]
What do you make of the "runtime error" is mscoree.dll from the screen shot in the first post above?

**Comment by stevencohn** [comment]
That's simply due to the fact that the Registry settings are not correct, as reported by iq.ps1.

**Comment by edogd** [comment]
Ok I tried installing 5.8.3, then ran the register-onemore.reg, and manually fixed Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\OneNote\AddIns\River.OneMoreAddIn\LoadBehavior to 3.
iq.ps1 output is all OK's now, but still no OneMore in OneNote and still the same error in the COM Add-ins window.

**Comment by edogd** [comment]
What version of/ features of .NET need to be installed? This is what I have:
![image](https://user-images.githubusercontent.com/46937458/226709780-5b1758d1-d719-4167-ba5d-99234ddb79f8.png)

**Comment by stevencohn** [comment]
https://dotnet.microsoft.com/en-us/download/dotnet-framework/net481

**Comment by edogd** [comment]
Problem was resolved somehow after IT fixed some corrupted setup files that were affecting other apps. Thanks for the help.
