### ISSUE TITLE
Font for custom styles changed without notification

### ISSUE THREAD

**Issue by julie777** [stevencohn/OneMore#982]
# Problem to Solve

This is probably an uncommon occurrence. I had to reinstall Windows and then all my applications.
I did save application configurations from AppData and restore them before installing the apps.

I reinstalled OneMore and had been using it for a few days. I realized that I had my styles set to a test set that I had been working on before my windows problems. I loaded "my normal" styles and proceeded to use them. Something didn't look right so I opened the style editor and found that the font had been changed to Microsoft Sans Serif. I assume that this is the default sans serif font. My styles had been using Open Sans which is not installed by default. I installed Open Sans, but my styles had already been modified and saved.

# To Reproduce

As above. I am sure that there is a simpler way to just uninstall the font that styles is using and see what happens.

# Expected Behavior

I would have liked to be notified when I loaded the style set that the font was missing so that I could install it and have my custom style remain as it was.

In addition, now that I fixed my custom style set I realize how painful it is to change the font for each style. I have all but one of my styles in the style set using Open Sans. I use a different font for code. 
I suspect that most people use one font for the majority of their styles.

I think a nice enhancement to the editor would be to have a way to set a base font for styles in a set. That font would be the default font for each style. Then an individual style, such as code, could be set with a specific font if desired. When changing the base font a dialog could ask if it should replace the font for all styles or only styles set to "base font".

# Screenshots

# Environment (if applicable)

 - OneNote Version: [e.g. Office 2019, O365, also 32bit or 64bit?]
 - OneMore Version [e.g. 3.4 - from the About dialog or from the log file]

# Additional Context

Add any other context about the problem here. Attach page XML file or the app log file as appropriate. You can find the log file here: %localappdata%\temp\OneMore.log

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
Easy fix. A warning dialog will be displayed if the file contains an unrecognized font family.
