### ISSUE TITLE
Onemore Portable Version

### ISSUE THREAD

**Issue by Oldance** [stevencohn/OneMore#986]
# As I and my colleagues want to use your tool we cant install it in the school laptop as we have not admin rights

May you please create a portable version that does not need installation or can be installed without need of admin rights.

Best regards Oldan

**Comment by stevencohn** [comment]
OneMore add-ins must be registration in the Windows System Registry which requires admin rights. There is no alternative to this. Sorry.

**Comment by Oldance** [comment]
Dear Steven,

Thank you very much for your quick answer and for developing this amazing tool. You are number one!

Best regards
Oldan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
