### ISSUE TITLE
info and warn snippets have different "deep color" in light and dark mode

### ISSUE THREAD

**Issue by wang001200** [stevencohn/OneMore#987]
when I insert snippets in light mode , they appear like this
![image](https://user-images.githubusercontent.com/6936272/226175955-c21278f0-a4a6-4463-810a-8eb150f28ec1.png)
switch to dark mode, they show up like this
![image](https://user-images.githubusercontent.com/6936272/226176003-aa225c48-a61c-4b31-85a9-f0366388bc28.png)

And when i insert these snippets in dark mode, they appear like this
![image](https://user-images.githubusercontent.com/6936272/226176060-3e1fb61b-e6cc-4c3a-911e-304844279131.png)
switch to light mode, they show up like this
![image](https://user-images.githubusercontent.com/6936272/226176156-34beb579-acaf-4112-885e-f1e769768cfa.png)

**Comment by stevencohn** [comment]
This was fixed recently by [this commit](https://github.com/stevencohn/OneMore/commit/a0652c6fcce75acc93ef304a30819212c0b87194)

It will be available in the next release.

**Comment by wang001200** [comment]
thank you 发自我的iPhone------------------ Original ------------------From: Steven  ***@***.***>Date: Sun,Mar 19,2023 8:54 PMTo: stevencohn/OneMore ***@***.***>Cc: wang001200 ***@***.***>, Author ***@***.***>Subject: Re: [stevencohn/OneMore] info and warn snippets have different "deepcolor" in light and dark mode (Issue #987)
This was fixed recently by this commit
It will be available in the next release.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/stevencohn/OneMore/issues/987#issuecomment-1475245626",
"url": "https://github.com/stevencohn/OneMore/issues/987#issuecomment-1475245626",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
