### ISSUE TITLE
Show Shortcuts is broken

### ISSUE THREAD

**Issue by julie777** [stevencohn/OneMore#988]
# Problem to Solve

Trying to view shortcuts causes error.
I suspect this is related to moving the wiki. 

# To Reproduce

1. Select Favorites/OneMore Keyboard Shortcuts
2. See error
![image](https://user-images.githubusercontent.com/5090005/226198055-2d1ec680-a0ec-475d-8288-1a8c030e3a97.png)

# Expected Behavior

A page listing the shortcuts should open.

I've never quite understood why keyboard shortcuts was under favorites.

I also don't understand why it creates a page in the notebook. 
The page is put in the current section which is random and it won't belong there.
Every other app I use just shows shortcuts in a dialog box. 
Given that OneMore allows changing the shortcuts, I imagine that you generate the list every time I look at it anyway so the saved notebook page would get stale.

# Screenshots

# Environment (if applicable)

 - OneNote Version:  O365
 - OneMore Version 5.8.2
 
# Additional Context

```
Running command ShowKeyboardShortcutsCommand
09| ..downloading template
16| ..error download shortcuts template (NotFound): Not Found, https://github.com/stevencohn/OneMore/raw/main/Templates/OneNote_Keyboard_Shortcuts.zip
16| SaveToMRU using derived name ShowKeyboardShortcutsCmd
```

**Comment by stevencohn** [comment]
Accidental file rename. Should work now.
