### ISSUE TITLE
Moving the wiki - good or bad?

### ISSUE THREAD

**Issue by julie777** [stevencohn/OneMore#989]
@stevencohn 

I just want to provide some feedback on moving the wiki to OneNote.

While I like the idea of using OneNote, and I know it is more powerful, there are some drawbacks.

1. The wiki as part of the github repo is 
  2. fast
  3. "searchable" as part of the repo
  4. can link to files in the repo
  5. can have access managed along with the repo

You don't notice the loading time issues with the wiki in onenote because it is your notebook. When a user follows the link to the new wiki there is a significant delay while the page syncs. This happens again when navigating to another page. It is not terrible, but it is significant.

If you decide to allow others to edit the wiki then you will need to provide access using OneNote/OneDrive/Microsoft accounts.

Google can't search your notebook and GitHub search won't work either.

I do realize that GitHub wiki is somewhat restrictive. I was in the process of trying to determine what it could do and how we could make the wiki better when Windows blew up on me. I was also trying to determine the best ways of searching on Github and communicating with the maintainers about it. It is sad that Github provides so much, but some of it doesn't work the way you would expect.

IMHO, using the Github wiki, or creating a documentation web site using github pages is the way to go. They are both free and more accessible. But, I do realize that using OneNote is going to be the easiest way for you to do all the formatting and presentation. I am just trying to provide a users perspective.

**Comment by stevencohn** [comment]
Well aware of all of these. I do look at the Web version almost as much as I look at it in OneNote native to make sure it still looks good. I spent so much time fiddling with markdown and/or HTML. I just want to write! I also found that general users ar intimidated by Github in general. It looks too technical. I may export the notebook to a Web site eventually but I'm not concerned.

What I would like to hear about is the content itself.

Linking is fully supported, so I'm not entirely sure what you mean about #4

**Comment by stevencohn** [comment]
> I am just trying to provide a users perspective.

You're much better than the average user! You have technical eye that most don't.

**Comment by jasonjac2** [comment]
I foudn the change from wiki to ON a bit of a jump and I thought links were broken (e.g. 1st link on https://github.com/stevencohn/OneMore/ docs to command pallette just takes you to the basic page).
Also, you can't copy a link from the ON page (i tried to copy the Command Pallette heading link to compare it with what was in GitHub).

I have wanted to suggest edits an you could clone the wiki, but of course you can't clone the ON and make suggestions.

**Comment by stevencohn** [comment]
That's not a broken link. The command palette link goes to the basic page on purpose. The command palette is only mentioned on the basic page, scroll down.

Not sure why Microsoft doesn't allow copying links from a view only page. That seems wrong but it is what it is. Work around is to open the link and copy it from the address bar.

**Comment by jasonjac2** [comment]
... goes to the basic page - yes, I guess I was expecting it to goto the H3 for the command pallette.  When I saw it and a couple of other clicks took me to the basic page, I just assumed it was all "basic page" linking.

If you put a ToC on each page in yoru ON, would I then be able to copy the link to that actual heading.


Another release - well done.  I'll DL it tomorrow.

Cheers,
JAC.

**Comment by maphew** [comment]
Side note to the main topic: I was very happy to discover the Onemore Wiki can be opened in desktop Onenote by using _File >> Info >> Edit in desktop app_ **from the web version**. So after the initial sync there is no more delays and you can use full in-onenote search. That said, it is still a detriment that the contents are not open to public search engines.

To that end my contribution to the main topic is the idea of: automatic or semi-automatic method of exporting a Notebook/Section/Page to markdown and/or html, which could then be hosted publicly via all the standard mechanisms. I see the wiki page for [File Commands](https://onedrive.live.com/view.aspx?resid=6925D0374517D4B4%2158723&id=documents&wd=target%28Commands.one%7CDEFB70F1-1B5E-4CA1-95DB-A5227B84D8DE%2FFile%20Commands%7C05C20CEE-54D7-494B-9B82-87E7E6AF2B20%2F%29
) says _R-click >> File >> Export_ has markdown and html as options.

**Comment by stevencohn** [comment]
I admit I do like that idea and have contemplated using OneMore's Archive to HTML command to build out a Web site. Archive will export an entire section or notebook to a .zip file as HTML, whereas the Export command only exports a single page. I would only need to enhance the Archive function to generate index.htm pages to tie it all together.

The other thing I'd need to do is buy a domain name and host it so..... anyone want to buy onemore.com? It's a bargain at only $237,600 US!

**Comment by maphew** [comment]
urk, that's crazy. Domain squats are such a blight. _OneMoreAddin.{anything}_ is available though. Another option is use GitHub Pages and onemore.github.io.

That's good to know about Archive. I hadn't discovered that yet, and was gearing up to write a request for Exporting more than a page at a time.  :-)

**Comment by stevencohn** [comment]
onemoreaddin.com coming soon...

**Comment by jasonjac2** [comment]
I am very impressed, going to have an in depth read this weekend, especially the dev pages.

**Comment by maphew** [comment]
https://onemoreaddin.com/Get%20Started/Welcome%20to%20OneMore.htm looks great! I'm impressed, and inspired to get cracking on my own Onenote exports-to-website.
