### ISSUE TITLE
OneNote shortcut for move page doesn't work now.

### ISSUE THREAD

**Issue by julie777** [stevencohn/OneMore#991]
# Problem to Solve

I use `<ctrl><alt>m` to move pages. The shortcut now does nothing. (This is actually what led me to enter the show shortcut bug.)

I have no proof that this is caused by OneMore, but it worked before my last OneMore update.

# To Reproduce

1. Select a page in the nav sidebar
2. `<ctrl><alt>m`
3. nothing happens

# Expected Behavior

The move page dialog should open.

# Screenshots

# Environment (if applicable)

 - OneNote Version: O365
 - OneMore Version 5.8.2

# Additional Context

Add any other context about the problem here. Attach page XML file or the app log file as appropriate. You can find the log file here: %localappdata%\temp\OneMore.log

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
I'm pretty sure OneMore doesn't override Ctrl+Alt+M. 

On my own laptop, Ctrl+Alt+M open up Macrium Reflect backup software! So I disabled it there and, voila! it started working as expected in OneNote again.

Make sure you don't have other software that may be overriding this key def.

**Comment by julie777** [comment]
@stevencohn 
You are a genius. I had installed Macrium Reflect to try something. I wasn't connecting it starting with the shortcut because its window was in the background.

**Comment by stevencohn** [comment]
Sounds like this ticket can be closed then. Please let me know if there's anything else.
