### ISSUE TITLE
tool buttons were blank in the Navigator window 5.8.3

### ISSUE THREAD

**Issue by zhongguocn** [stevencohn/OneMore#992]
windows 11 x64+Office 365+OneMore 5.8.3 x64

tool buttons were blank in the Navigator window.

**Comment by stevencohn** [comment]
Are the buttons there? If you move your mouse over the same region, do the buttons light up, if you click them do they work? Or are the buttons simply not there at atll?

<img width="262" alt="image" src="https://user-images.githubusercontent.com/9964757/226325594-ff2d47d1-89bf-4f51-aa0d-81f6e635f5fc.png">

**Comment by stevencohn** [comment]
Seems to be related to screen resolution/scaling. I'll take a look.

**Comment by stevencohn** [comment]
Set autoscale mode of NavigatorWindow to DPI
Fixed layout of Settings ContextMenuSheet

**Comment by zhongguocn** [comment]
> Set autoscale mode of NavigatorWindow to DPI Fixed layout of Settings ContextMenuSheet

The buttons simply not there at all.

bug report:
After installing version 5.8.3, editing content in OneNote and using Microsoft Pinyin input methods can become very slow. However, the speed of using Microsoft Pinyin input method in other programs is normal.

**Comment by wang001200** [comment]
> > Set autoscale mode of NavigatorWindow to DPI Fixed layout of Settings ContextMenuSheet
> 
> The buttons simply not there at all.
> 
> bug report: After installing version 5.8.3, editing content in OneNote and using Microsoft Pinyin input methods can become very slow. However, the speed of using Microsoft Pinyin input method in other programs is normal.

aha， me too.

**Comment by stevencohn** [comment]
I have a solution for the slowness. It will be in the next release. I'll try to push that out as soon as possible.

**Comment by wang001200** [comment]
> I have a solution for the slowness. It will be in the next release. I'll try to push that out as soon as possible.

it seems affect other M365（such as excel），is it even possible？

**Comment by stevencohn** [comment]
There is no connection between OneMore and Excel. So I would say no.
