### ISSUE TITLE
Install works now Yay!   Can it restart OneNote?

### ISSUE THREAD

**Issue by julie777** [stevencohn/OneMore#997]
# Problem to Solve

5.8.3 closed OneNote and installed without error which is great.

# New Feature/Solution

If the installer closes OneNote it would be nice if it opened OneNote when complete.
Just add a line to the end of the update script please.

## Alternative Solutions

Provide a clear and concise description of any alternative solutions or features you've considered.

# Additional Context

Provide any other context or screenshots about the feature request here.

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
No, I wish I could. I've wanted it myself for a while. The installer is a single-bundle installer that run start-to-finish as the SYSTEM account. While I know the username of the user that started the installer, there is no way for the installer to run onenote.exe as that user without prompting for a password. For obvious security reasons, this type of impersonation is not allowed.

This would require a new bootstrap-initiated installer. Something that's way down on the backlog at the moment.
